### ISSUE TITLE
Test relative performance of 32-bit and 64-bit desktop installers and apps

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#1001]
Issue https://github.com/phetsims/weddell/issues/114 describes a need for a 32-bit Windows version of our desktop app.  It would be nice if we could just replace our current 64-bit app with a 32-bit version, but we probably don't want to do that if the performance of the 32-bit app is significantly lower than that of the 64-bit version.  I have built 32- and 64-bit app installers and would like the QA team to install them and report on whether the installation or the performance of the app is significantly worse for the 32-bit version.

The two installers can be found at https://phet-dev.colorado.edu/weddell/dist/2023-11-06/.

Ideally we would also test the 32-bit version on 32-bit hardware, but I don't know if we have any of that available.  Please let me know.

Assigning to @KatieWoe and @kathy-phet for prioritization.

Windows 64 build:
- [x] Tester = KW, Platform = Win 11, Time = 1.5
- [ ] Tester = , Platform = , Time = 

Windows 32 build:
- [x] Tester =NS  , Platform =  win10, Time = 2
- [x] Tester = KW, Platform = Win 11, Time = 1.5

**Comment by KatieWoe** [comment]
Commenting to add that I don't know of a 32-bit device we have.

**Comment by KatieWoe** [comment]
I tested one or two java sims on both installers on a device in the office. Things looked ok. Calling it here

**Comment by KatieWoe** [comment]
I didn't see any noticeable difference between the two builds.

**Comment by jbphet** [comment]
Thanks QA team.  I'll move forward with deployment of the 32-bit version.  Closing.
