### ISSUE TITLE
Test MacOS desktop installer version 1.0.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#1003]
I've rebuilt the MacOS version of the desktop installer for https://github.com/phetsims/weddell/issues/116.  This should be tested.

BIG NOTE: I build this *without* using the new code signing cert because when I tried using the old one it worked fine (which was not the case on Windows).  So, in the interest of saving time and keeping life simple, I just went with it.  The app installed fine with no warnings on the Mac that is available to me.  Please watch closely for any indications of problems that could be related.

Verification can be relatively light.  I'd recommend:
- Installing it at least two different Macs, making sure that it installs correctly and presents no warnings
- Verifying that some of the most recently released sims are present, such as "Kepler's Laws" and "Center and Variability"
- Spot checking a handful of other HTML5 sims
- Trying some of the Java sims if you have a Mac set up for it.  If not, up to you whether to pursue it, but please note whether or not this was done

The app installer file can be found at https://phet-dev.colorado.edu/weddell/dist/2023-11-15/

Please contact me with any questions.

**Comment by Nancy-Salpepi** [comment]
I'm on a MacBook Air with macOS 14 and the app worked well. 
Java sims loaded without issue. 
The only thing I noticed was with Kepler's Laws-- the planet sometimes stops super briefly and then starts again, but I don't think it affects learning goals at all.

**Comment by KatieWoe** [comment]
Things looked ok to me as well.

**Comment by JaronDroder** [comment]
Tested on MacBook Pro IOS 13, all sims loaded well and no notable issues with any.

**Comment by jbphet** [comment]
Thanks team!  I'll move forward with deployment.  Closing.
