### ISSUE TITLE
SVG image browser testing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/qa#1011]
Based on some of my initial testing, it seems browsers may have updated SVG image handling such that we might be able to use SVG base64 data URIs directly. I'd like to have testing done to verify whether this is possible on all of our platforms.

Testing URL: https://bayes.colorado.edu/dev/phettest/scenery/tests/svg/

For each test, I'd like the following things to appear as below (note the "base64 Data URL" part, we'll want to ignore the ".svg URL" and utf Data URL" sections):

1. The "<img> from base64 Data URL" should appear as below (anything that doesn't have the gradient should be considered "broken" and reported, with screenshot and info):
![image](https://github.com/phetsims/qa/assets/480878/233beb94-7edb-459d-a625-10af87358a0c)
2. The "Canvas from <img> from base64 Data URL" should appear as below (anything that doesn't have the gradient should be considered "broken" and reported, with screenshot and info):
![image](https://github.com/phetsims/qa/assets/480878/417de57f-c894-4cfa-befc-b991c025322b)
3. The "Read from Canvas from <img> from base64 Data URL (should be purple)" should similarly appear as below (anything non-purple should be reported):
![image](https://github.com/phetsims/qa/assets/480878/d69e0eac-e732-4163-ab07-c0ba7f7d0deb)
4. Ignore everything else on the page!

I'd like this to be done for every supported browser/OS combination that we can reasonably do (if it breaks on any supported platform combination, we probably won't be able to use this method). So if something is broken, please report it immediately (with all available info/screenshots), and pause testing.

Additionally, for every browser, I'd like to have the offline form tested if possible (i.e. go to the test URL, Ctrl/Cmd-S save or equivalent, "Save HTML only" to a file, then load the file in the browser with "file://"; usually this can be accomplished by finding the file in the file explorer/finder equivalent and opening it from there).

Let me know if there are any questions!

**Comment by KatieWoe** [comment]
- [ ] Win 11 Chrome
- [ ] Win 11 Firefox
- [ ] Win 11 Edge
---
- [ ] Win 10 Chrome
- [ ] Win 10 Firefox
- [ ] Win 10 Edge
---
- [ ] Chromebook Chrome
---
- [ ] iPadOS 15 Safari
- [ ] iPadOS 16 Safari
- [ ] iPadOS 17 Safari
---
- [ ] MacOS 10.14 Safari
- [ ] MacOS 10.14 Chrome
- [ ] MacOS 10.14 Firefox
---
- [ ] MacOS 10.15 Safari
- [ ] MacOS 10.15 Chrome
- [ ] MacOS 10.15 Firefox
---
- [ ] MacOS 11 Safari
- [ ] MacOS 11 Chrome
- [ ] MacOS 11 Firefox
---
- [ ] MacOS 12 Safari
- [ ] MacOS 12 Chrome
- [ ] MacOS 12 Firefox
---
- [ ] MacOS 13 Safari
- [ ] MacOS 13 Chrome
- [ ] MacOS 13 Firefox
---
- [ ] MacOS 14 Safari
- [ ] MacOS 14 Chrome
- [ ] MacOS 14 Firefox

**Comment by KatieWoe** [comment]
All supported platforms and browsers seem to be good

**Comment by jonathanolson** [comment]
Perfect, thank you so much!
