### ISSUE TITLE
Dev test: Area Model: Multiplication 1.0.0-dev.23

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#102]
Sim available at https://www.colorado.edu/physics/phet/dev/html/area-model-multiplication/1.0.0-dev.23/phet/area-model-multiplication_en_phet.html.

Would be great to get an initial "dev" test done (with whatever platforms would be appropriate, maybe just one with a mouse, and one with touch?)

For this testing, please create issues in https://github.com/phetsims/area-model-common/issues (ideally noting what screens are affected).

Helpful terms:

- There are three general types of screens: "proportional" screens (Decimals/Explore/Multiply/Partition) where things are "to-scale" like a grid, "generic" screens (Generic/Variables) which use fixed-visual-size abstract entries with keypads, and "game" screens (which under-the-hood uses the generic model).
- Partial products "selection" options are "hidden", "products" (the A), and "factors" (the a x b equivalent)
- Calculation "selection" options are "hidden", "line-by-line" and "all-lines"
- "Partition lines" are the horizontal/vertical lines that separate the visible area (the rectangle) into multiple "partitions". For proportional screens, the partition lines can be moved (when available), and on generic screens they are in a fixed location. On proportional screens, the size of each partition is determined by its width/height (displayed in its "partition label"). On generic screens, the size of each partition is entered into a box ("partition entry" which opens up a keypad).
- For proportional screens, the colors for "horizontal" numbers/partitions are red, and the colors for "vertical" ones are blue. This is green/purple for generic screens. NOTE that the vertical lines are "horizontal partition lines", since they create partitions along that side.
- For proportional screens, the green draggable thing is the "proportional drag handle", and the blue/red draggable things are "partition line drag handles". Checkboxes available are usually the "grid" checkbox and the "tile" checkbox (which enables a "tile" view in the main area display). The 20x20 or similar buttons are "scene selection" buttons, as each size combination (10x10, 20x20, 100x100, etc.) is a different "scene".

**Comment by phet-steele** [comment]
Dev done.

**Comment by jonathanolson** [comment]
Thanks!
