### ISSUE TITLE
Website Regression Test

### ISSUE THREAD

**Issue by mattpen** [phetsims/qa#1020]
<h1>Website Regression Test</h1>

**Mentions**: @kathy-perkins @chrisklus @mattpen @KatieWoe 

<h3>When Problems are Found</h3>

New Issues should be opened in https://github.com/phetsims/website-meteor/issues/new
Please ping `@mattpenn` or `@chrisklus` on slack if you have questions for the developers.

<h3>Pages To Test</h3>

- Home page: https://ox-dev.colorado.edu
- Registration page: https://ox-dev.colorado.edu/en/register
- Edit Profile page: https://ox-dev.colorado.edu/en/edit-profile
- Change Password page: https://ox-dev.colorado.edu/en/change-password
- Change Email page: https://ox-dev.colorado.edu/en/change-email
- Forgot Password page: https://ox-dev.colorado.edu/en/reset-password-request
- Resend Confirmation page: https://ox-dev.colorado.edu/en/resend-email-confirmation
- Browse page: https://ox-dev.colorado.edu/en/simulations/browse
- Filter page: https://ox-dev.colorado.edu/en/simulations/filter
- HTML Sim page: (e.g.) https://ox-dev.colorado.edu/en/simulations/build-a-nucleus
- HTML Prototype page: (e.g.) https://ox-dev.colorado.edu/en/simulations/sound-waves
- Java+CheerpJ page: (e.g.) https://ox-dev.colorado.edu/en/simulations/fluid-pressure-and-flow
- Translated Sims page: https://ox-dev.colorado.edu/en/simulations/translated
- Inclusive Design: https://ox-dev.colorado.edu/en/inclusive-design
- PhET Global: https://ox-dev.colorado.edu/en/phet-global
- DEIB page: https://ox-dev.colorado.edu/en/deib-in-stem-ed
- Team page: https://ox-dev.colorado.edu/en/about/team
- Supporters page: https://ox-dev.colorado.edu/en/our-supporters
- Partnerships page: https://ox-dev.colorado.edu/en/partnerships
- Offline Access page: https://ox-dev.colorado.edu/en/offline-access
- Privacy Policy page: https://ox-dev.colorado.edu/en/privacy-policy
- Source Code page: https://ox-dev.colorado.edu/en/about/source-code
- Licensing page: https://ox-dev.colorado.edu/en/licensing
- For Translators page: https://ox-dev.colorado.edu/en/for-translators

Note that there is no need to test any simulations, any activity related pages, the help center, the teaching resources pages, or the research page. 

<h3>Translations</h3>
Please test all of the above pages in these translations:

- English (en)
- Spanish (es)
- One RTL locale (e.g. ar_SA)

<h3>Platforms To Test</h3>

- Windows 10 + Latest Chrome
- Windows 10 + Latest Firefox
- macOS + Safari
- iOS + Safari
- Chrome OS + Chrome
- Android + Chrome
- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver

<h3>Test Matrices</h3>

- [General Test Matrix](https://docs.google.com/spreadsheets/d/1fMQS3_y869LV2OKNiIz5-03_S7IgfzebsjUtYlbGGCI/edit#gid=0)

<h3>Focus and Special Instructions</h3>

There have been significant changes in how the website is built and structured.  This test is meant to look for regressions and changes from the current website.  There are no new features to evaluate.  

Things to focus on:
- Does the layout for each page match the same page on phet.colorado.edu?
- Do all links, buttons, form inputs, and other interactive controls work as expected?
- Are there any English strings present when testing other locales?
- For any forms, try breaking/omitting all input controls to see if invalid data can be submitted
- For any user forms, please test the processes to completion (e.g. submit a registration form, then follow through with the email confirmation process)
- Test everything (particularly forms) with both Mouse and Keyboard(TAB) Navigation.
- If there is a console available, check for errors and include them in the Problem Description.
- Accessibility: the website does not provide specific accessibility features, but rather should be accessible with standard screen readers when using screen reader navigation.
  - NVDA: https://dequeuniversity.com/screenreaders/nvda-keyboard-shortcuts
  - VoiceOver: https://www.apple.com/voiceover/info/guide/_1131.html
  - JAWS: https://support.freedomscientific.com/Content/Documents/Manuals/JAWS/Keystrokes.txt

---
<h2>For QA...</h2>

<details>
<summary><b>Accessibility features</b></summary>

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[here](https://github.com/phetsims/qa/blob/main/documentation/accessibility-bugs.md). If you find a screen reader bug,
please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel
controls. Please test magnfication and make sure it is working as intended and well with the use cases of the
simulation. Due to the way screen readers handle user input, magnification is NOT expected to work while using a screen
reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
I noticed on the Android tablet that switching from the filter page to the browse page was very slow and there wasn't any indication that loading was happening. Not exactly a bug, but rather odd.

**Comment by mattpen** [comment]
@KatieWoe - We can add a spinner to that transition. Can you open an issue as a bug please?

**Comment by KatieWoe** [comment]
It behaves the same on the published site, so I don't think it's a bug, but navigating the Browse page with NVDA was rather bewildering. It was a bit hard to focus on individual sims in the list and nothing was read when you scrolled the list with the buttons on the side.

**Comment by KatieWoe** [comment]
QA is done
