### ISSUE TITLE
Regression test AccessibleValueHandler for step attribute change

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/qa#1035]
I am hopeful that a change in https://github.com/phetsims/sun/issues/873 will work well but we need to make sure it still sounds OK when using a screen reader.  This change is to fix https://github.com/phetsims/greenhouse-effect/issues/388 - in that issue NVDA would report some slider values as 'invalid'.

Can you please help me test a few platforms that I don't have access to? Can you please try out

- greenhouse-effect, 
- john-travoltage
- ratio-and-proportion

with 

- [ ] iOS Safari  + VoiceOver
- [x] Safari + VoiceOver
- [ ] NVDA + Firefox
- [ ] JAWS + Chrome

Just to make sure you can use the sliders (or arms/legs/hands) in each sim and don't hear "invalid" or other strange output.

In 2018, we tried this change and it made sliders inoperable on iOS VoiceOver, so that is the platform I am most worried about.

**Comment by Nancy-Salpepi** [comment]
noting that this known a11y bug for VO: https://github.com/phetsims/a11y-research/issues/164 still occurs. 

https://github.com/phetsims/qa/assets/87318828/b8567593-33a3-46b6-8bc3-b47c08c669f5

**Comment by Nancy-Salpepi** [comment]
I'm on iPad 9th generation with iPadOS 17.3 and the sliders are also unusable for me. In Greenhouse, when the concentration slider has focus, as I swipe it doesn't move the thumb at all. VO just keeps repeating "Moderate levels of greenhouse gases." Same for JT -- it just repeats "foot of rug" over and over but doesn't move the foot (I didn't have an issue in published).

**Comment by jessegreenberg** [comment]
Darn! Alright, thanks @Nancy-Salpepi. We will have to reassess in https://github.com/phetsims/sun/issues/873. We can close this.
Thanks for testing this!
