### ISSUE TITLE
Test school search

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/QA#104]
- [ ] “EL”: Elementary
- [x] “ELEM”: Elementary
- [ ] “Sch”: School
- [ ] “H S”: High School
- [ ] "HS": High School
- [ ] “MS”: Middle School
- [ ] “Mdle”: Middle
- [ ] “J H”: Junior High
- [ ] “CTR”: Center
- [ ] "jr" ->"junior"
- [ ] "sr"->"senior".

For 3. the sorting order is now :

- [ ] a. Does the school name include the search string as an exact (case-insensitive) substring?
- [ ] b. alpha-numeric

- [ ] A search for "tricounty" will not match a school name with "tri county" and a search for "tri county" will not match a school name with "tricounty". A search for "tri-county" would match all 3, a search for "tricounty" would match "tri-county" and "tricounty", and a search for "tri county" would match "tri county" and "tri-county".

- [ ] All 50 state abbreviations.

- [ ] Alabama 
- [ ] Alaska 
- [ ] Arizona 
- [ ] Arkansas 
- [ ] California 
- [x] Colorado 
- [ ] Connecticut 
- [ ] Delaware 
- [ ] Florida 
- [ ] Georgia 
- [ ] Hawaii 
- [ ] Idaho 
- [ ] Illinois
- [ ] Indiana 
- [ ] Iowa 
- [ ] Kansas 
- [ ] Kentucky 
- [ ] Louisiana 
- [ ] Maine 
- [ ] Maryland 
- [ ] Massachusetts 
- [ ] Michigan 
- [ ] Minnesota 
- [ ] Mississippi 
- [ ] Missouri 
- [ ] Montana
- [ ] Nebraska 
- [ ] Nevada 
- [ ] New Hampshire 
- [ ] New Jersey 
- [ ] New Mexico 
- [ ] New York 
- [ ] North Carolina 
- [ ] North Dakota 
- [ ] Ohio 
- [ ] Oklahoma 
- [ ] Oregon 
- [ ] Pennsylvania
- [ ] Rhode Island 
- [ ] South Carolina 
- [ ] South Dakota 
- [ ] Tennessee 
- [ ] Texas 
- [ ] Utah 
- [ ] Vermont 
- [ ] Virginia 
- [ ] Washington 
- [ ] West Virginia 
- [ ] Wisconsin 
- [ ] Wyoming

**Comment by oliver-phet** [comment]
Report search issues here: https://github.com/phetsims/website-meteor/issues

**Comment by lmulhall-phet** [comment]
@oliver-phet and @mattpen have managed to get the school created to school found ratio down to where they want it. Closing this issue for now.
