### ISSUE TITLE
Regression test AccessibleValueHandler step attribute

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/qa#1040]
This is a continuation from https://github.com/phetsims/qa/issues/1035.

We have a new fix for https://github.com/phetsims/sun/issues/873 that we hope is compatible with VoiceOver. Can you please check

- greenhouse-effect,
- john-travoltage

With 
- [x]  iOS Safari + VoiceOver
- [x]  Safari + VoiceOver
- [x]  Chrome + JAWS

Just to make sure you can use the sliders (or arms/legs/hands) in each sim and don't hear "invalid" or other strange output?

Thanks!

**Comment by Nancy-Salpepi** [comment]
QA is done! Sliders are working!

**Comment by jessegreenberg** [comment]
Great! OK, thanks for testing this! Closing.
