### ISSUE TITLE
Dev-Lite Test: Mean Share and Balance (Screen: Leveling Out) 1.1.0-dev.1

### ISSUE THREAD

**Issue by marlitas** [phetsims/qa#1049]
<h1>Dev-Lite Test</h1>

**Mentions**: @marlitas, @jbphet, @amanda-phet 

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/mean-share-and-balance/issues)
- [phet top-level directory](https://phet-dev.colorado.edu/html/mean-share-and-balance/1.1.0-dev.1)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/mean-share-and-balance/1.1.0-dev.1/phet/mean-share-and-balance_all_phet.html)

<h3>Test Matrix</h3>

- [x] Tester 1 (Tester = KW, Platform = Win 11 Chrome, Time = 1 hr{max 2 hours}
- [x] Tester 2 (Tester = NS , Platform = mac + safari , Time = .75{max 2 hours}

<h3>Features included</h3>

- [ ] <s> PhET-iO </s>
- [x] Alternative Input
- [ ] <s> UI Sound
- [ ] Sonification
- [ ] Description
- [ ] Voicing </s>
- [x] Dynamic Locale

<h3>Focus and Special Instructions</h3>

While working on development for Mean Share and Balance we noticed that we were able to hit buggy situations in the Leveling Out screen. We were never able to find a consistent way to replicate, but did see the bug show up with either how the candy bars stack or the amounts of candy bars visible in the notepad area. 

It would be of great help to have QA spend some time messing with the candy bars in the notepad area to see if we can find consistent steps to reproduce these bugs so we can address them in the code.

It is recommended that QA try dragging and dropping the candy bars both with mouse and keyboard input, Increasing/decreasing  the number of candy bars on a plate, and adding and removing people, resetting, and syncing data to try and suss out any bugs. 

To be clear, this dev-lite test only includes the second screen: Leveling Out.

<h3>Issues to Verify</h3>

There are no existing issues to verify.

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<hr>

</details>

<details>
<summary><b>PhET-iO features</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
  sure the simulation loads without crashing or throwing errors.

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Interactive Description
  - Sound and Sonification
  - Pan and Zoom
  - Mobile Description
  - Voicing
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[here](https://github.com/phetsims/qa/blob/main/documentation/accessibility-bugs.md). If you find a screen reader bug,
please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel
controls. Please test magnfication and make sure it is working as intended and well with the use cases of the
simulation. Due to the way screen readers handle user input, magnification is NOT expected to work while using a screen
reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
From the start, trying to drag a candy bar from the leftmost stack, without having done anything else, will cause the bar to be stuck to the right of the pile and not drag any further left. Reset all or adding/taking away people seems to fix this, it only happens on first load so far.

https://github.com/phetsims/qa/assets/41024075/a496ecc4-dce2-499f-9227-e9226f8d9555

**Comment by KatieWoe** [comment]
If you drag one of the bottom two bars from the left stack, then hit reset all, that bar will be invisible until an interaction occurs. This doesn't seem to happen with the top bar.

https://github.com/phetsims/qa/assets/41024075/8063c405-9916-4df9-a521-d6f11162e120

**Comment by KatieWoe** [comment]
Further. If you move a bar from the left stack, sync, then reset all, the spot you drug from will be blank and the bar will be stacked up on top.


https://github.com/phetsims/qa/assets/41024075/772609f1-4fa2-4243-b3d1-8e656a474340

**Comment by KatieWoe** [comment]
If you remove all the bars from the left person, drag the bar from the second over to the first, and reset, this bug occurs. If you add a third person, and drag the second's bar over there this bug will also happen.


https://github.com/phetsims/qa/assets/41024075/e5b3fc43-9b56-4278-80d7-c3c10d731ebc

**Comment by KatieWoe** [comment]
QA is done
