### ISSUE TITLE
Test the installers that are live on the site as of 3/5/2018

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#105]
The installers are now being built using the _all.html files.  A number of other issues have been fixed, and the code has been revised to use ES6 features such as async/await.  All platforms and configurations (i.e. with activities and without) should be tested.

The installer builder will be set to run at 1am on Sunday, 3/4/2018, after which I'll disable it until the results of this testing are complete.

The following GitHub issues should be verified as part of this effort:
- [x] https://github.com/phetsims/installer-builder/issues/54
- [x] https://github.com/phetsims/installer-builder/issues/145
- [x] https://github.com/phetsims/installer-builder/issues/159

**Comment by jbphet** [comment]
Note to self and @zepumph: If and when QA gives the thumbs up on this, we should delete the branch on which the development for the _all.html files was done and close the related issue, see https://github.com/phetsims/installer-builder/issues/137.

**Comment by phet-steele** [comment]
@jbphet tested these on win chrome and mac chrome (the 4 versions) and they worked fine.

**Comment by zepumph** [comment]
This is awesome @phet-steele thanks for the hard work. I'm going to go delete the branch now. Closing.
