### ISSUE TITLE
Sync and edit transcripts from early math in-person workshop

### ISSUE THREAD

**Issue by catherinecarter** [phetsims/qa#1055]
In the Early Math folder (see @catherinecarter if link is needed), the transcripts for the videos need to be created and edited. 

Things to look for: 
- correct words (e.g., "same" in transcript might actually be, "sim")
- edits have smooth transitions
- teachers/facilitator are not talking too long or are inaudible
- make suggestions for shortening the length of videos 

How to start
- Open the video
- Click on "Edit"
- Choose "Video Settings" on right
- Transcript
- Generate
- Refresh

Videos
- [x] video 1
- [x] video 2
- [x] video 3
- [ ] video 4
- [ ] video 5
- [ ] video 6
- [ ] video 7
- [ ] video 8
- [ ] video 9
- [ ] video 10 (missing)
- [x] video 11
- [x] video 12
- [x] video 13
- [x] video 14

**Comment by KatieWoe** [comment]
@catherinecarter asked us to put this on hold for now.

**Comment by catherinecarter** [comment]
Thanks for both of your help on this! The transcripts are complete. Closing.
