### ISSUE TITLE
 Update Surface tablet to Win 10

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/QA#106]
https://github.com/phetsims/tasks/issues/889 was closed and issue moved here

@oliver-phet said:

> Tablet is in QA office.
> @phet-steele assign to a QA member of your choice!

**Comment by lmulhall-phet** [comment]
@oliver-phet @ariel-phet I assume you're talking about Hutchins? (The Surface tablet on the green shelf.) If so, I just checked and it looks like it's running Windows 10.

**Comment by oliver-phet** [comment]
Thanks, @lmulhall-phet. I'll close this for now, then.
