### ISSUE TITLE
Identify sims that have Safari 17.4 quadratic rendering problem

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#1069]
In https://github.com/phetsims/graphing-quadratics/issues/206, @Nancy-Salpepi discovered a bug in Safari 17.4 on Apple chips.  That bug was related to using SVG to draw quadratic curves, and was resolved for graphing-quadratics. 

The bug is being tracked more generally in https://github.com/phetsims/scenery/issues/1628.

In https://github.com/phetsims/graphing-quadratics/issues/206#issuecomment-2032904300, @kathy-phet said:
> @Nancy-Salpepi @KatieWoe - Sounds like you should keep an eye out for additional related issues to this on other sims. 

According to @jonathanolson, sims that use these methods of `kite.Shape` are liable to have this problem:

* quadraticCurveTo
* quadraticCurveToPoint (the method that was failing in graphing-quadratics)
* quadraticCurveToRelative
* quadraticCurveToPointRelative
* smoothQuadraticCurveTo
* smoothQuadraticCurveToRelative

Sims that call one or more of those methods directly include:

- [x] area-builder
- [x] balloons-and-static-electricity
- [x] build-an-atom
- [x] energy-skate-park
- [ ] faradays-electromagnetic-lab (for drawing the coils)
- [x] faradays-law
- [ ] fluid-pressure-and-flow
- [ ] fraction-comparison
- [x] gene-expression
- [x] geometric-optics (for drawing the lens and mirror shapes)
- [x] hookes-law (for the Energy plot)
- [x] neuron
- [x] projectile-data-lab
- [x] projectile-motion
- [x] proportion-playground
- [x] states-of-matter

One or more of those methods are also used in these scenery-phet UI components:

`BicyclePumpNode` (used to draw the pump handle and front edge)
- [x] gas-properties
- [x] states-of-matter

`ProbeNode`
- [x] beers-law-lab
- [x] bending-light
- [x] circuit-construction-kit-common (the CCK suite)
- [x] energy-skate-park
- [x] ph-scale
- [x] wave-interference

`ReturnButton / ReturnIcon`
- [x] build-a-nucleus
- [x] calculus-grapher
- [x] expression-exchange
- [x] forces-and-motion-basics
- [x] fractions-common (the fractions suite)
- [x] number-suite-common (the numbers suite)

**Comment by pixelzoom** [comment]
@KatieWoe You'll probably want to check with @kathy-phet to confirm that this is a project worth doing, or whether to wait until problems are reported.

This is obviously a huge amount of stuff to test. And without assistance from the sim developer, it's not at all clear what should even be tested.  For the sims that I'm familar with, I've provided details above.  

It's also possible that @jonathanolson might be able to prune this task down a bit. Also worth following up on where @jonathanolson is with reporting this problem to the WebKit team for https://github.com/phetsims/scenery/issues/1628, and whether a fix for Safari 17.4 is forthcoming.

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
@KatieWoe Can you please summarize what was tested, and what the results were?

**Comment by pixelzoom** [comment]
> Also worth following up on where @jonathanolson is with reporting this problem to the WebKit team for https://github.com/phetsims/scenery/issues/1628, and whether a fix for Safari 17.4 is forthcoming.

And did someone follow up on this?

**Comment by KatieWoe** [comment]
Sorry, I missed this earlier. We looked through the sims in the Safari browser and focused in particular on graphs, changing lines, the items described such as probes, and looked for graphical issues and disappearing elements. I don't believe we encountered similar issues, or they would have been recorded.

**Comment by pixelzoom** [comment]
👍🏻
