### ISSUE TITLE
Test CCK DC and DC-Virtual Lab 1.0.1-rc.1

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#107]
See https://github.com/phetsims/circuit-construction-kit-common/issues/432

It was requested we change the max number of wires from 20 to 25.  I made the change and published RCs:

https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.1-rc.1/circuit-construction-kit-dc_en.html

https://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc-virtual-lab/1.0.1-rc.1/circuit-construction-kit-dc-virtual-lab_en.html

If our build philosophy did its job, the only change in the code is the change from 20=>25 wires (I have not confirmed this in a diff though).  We need to "spot check" the RC's, making sure the wire count is right, and checking that no new issues have inadvertently crept in.

Assigning to @ariel-phet to prioritize/schedule/delegate.

**Comment by samreid** [comment]
I used 

cat circuit-construction-kit-dc_en-rc.html | tr \" \\n > out-quote.txt
cat circuit-construction-kit-dc_en_1.html | tr \" \\n > out-quote.txt

and a diff confirmed that the changes are as desired:
![image](https://user-images.githubusercontent.com/679486/37213944-c0e79274-2370-11e8-97b8-44d45d49dab7.png)

**Comment by lmulhall-phet** [comment]
@samreid I played with the sim for a few hours on Chrome and Firefox on a Windows machine and I didn't notice anything out of the ordinary.

**Comment by samreid** [comment]
That sounds good enough to me, @phet-steele or @ariel-phet did you want anything further before publication?

**Comment by phet-steele** [comment]
@samreid go for it.

**Comment by samreid** [comment]
Thanks, I'll continue in https://github.com/phetsims/circuit-construction-kit-common/issues/432
