### ISSUE TITLE
Updated Locale Testing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/qa#1085]
Testing related to https://github.com/phetsims/joist/issues/963 and https://github.com/phetsims/joist/issues/965.

Locale data for reference: https://github.com/phetsims/babel/blob/924ff2a0cc89ab2ec392c83221347945ccc23996/localeData.json

Behavior to test:

1. Three-letter ?locale query parameter codes (e.g. ?locale=spa) should be equivalent to the equivalent two-character (or extended) code, (e.g. ?locale=es). See the locale data above (anything listed with a locale3 field), examples are en/eng, zho/zh_CN, es/spa.
2. Providing a ?locale value that isn't in the desired format (e.g. xx, xxx, or xx_XX) should pop open the invalid query parameter dialog. Providing any locale IN that format ('x' meaning a-z, 'X' meaning A-Z) should NOT open the dialog, even if it is not a valid locale. Invalid locales (e.g. 'xx' or 'qq') should launch the sim in English.
3. Providing a ?locale value that isn't translated for the sim, AND whose fallbacks are not translated for the sim, will result in the sim loading in English. Fallbacks are in the locale data above (fallbackLocales). Examples are ak_FT: [ ak ], ar_SA: [ ar, ar_MA ], deu: [], pt: [ pt_BR ], es_ES: [ es ].
4. Providing a ?locale value that isn't translated for the sim, BUT a fallback IS translated, will load as the first fallback locale in the list. (can check with visuals of language, or in console with `phet.chipper.locale`).
5. Providing a ?locale value that is translated should load that locale.
6. Locale values in the locale switching part of the settings dialog should be properly sorted (see https://github.com/phetsims/joist/issues/965#issuecomment-2105383072, e.g. Urdu/Persian should not be sorted in weird spots) **In particular, please test this one feature across a range of supported platforms, especially the older ones**
7. String fallback should work, where if a translation does NOT have a translation for a string, but a fallback DOES, the first fallback with a translation will be used for that string. (e.g. in center-and-variability, es_PE itself does not yet have translations for the region-and-culture section (particularly the country strings, e.g. `preferences.tabs.localization.regionAndCulture.unitedStatesOfAmerica`, but the fallback of `es` DOES have translation for this. Additionally, spot-check to make sure there aren't regressions in translation compared to the production sims.
![image](https://github.com/phetsims/qa/assets/480878/0e0fcf01-aec1-48d4-9d16-9e1580b2af02)
8. Dynamic locale changes should work.
9. phet-io Studio runs, and doesn't complain. `${simName}.general.model.fallbackLocalesProperty` does not exist.
10. Navigating to a string in studio (while in a particular locale), editing the string should change it in the view. Launching with "Test" should load the simulation, and whenever in that particular (exact!) locale, it should have the changed value.
11. Locale query parameter should be case-insensitive (`ES` or `es_mx` should work), and `-` can be provided as a replacement for _, e.g. `es-mx` should work.

Testing should ideally be done on unbuilt versions (i.e. phettest) but also the built versions (they use different code for loading strings). Test the _all.html version.

Selected sims (with dev deployments containing the above changes):

Center and Variability
- https://phet-dev.colorado.edu/html/center-and-variability/1.2.0-dev.5/phet/center-and-variability_all_phet.html
- https://phet-dev.colorado.edu/html/center-and-variability/1.2.0-dev.5/phet-io/
- (phettest)

Acid-Base Solutions
- https://phet-dev.colorado.edu/html/acid-base-solutions/1.4.0-dev.7/phet/acid-base-solutions_all_phet.html
- https://phet-dev.colorado.edu/html/acid-base-solutions/1.4.0-dev.7/phet-io/
- (phettest)

**Comment by kathy-phet** [comment]
@jonathanolson - I believe one fix is needed ... since I didn't see it in your description. 

We had discussed making all of these case insensitive - so xx_XX and xx_xx or XX should all work OK and give you the correct locale. e.g. ES == es and PT_BR is same as pt_br. and pt_br == pt_BR. xxx==XXX or xxX or XxX. 

Did that become a larger concern? Or are you still OK making this case insensitive? I don't really see a reason to not create a bit of relaxing for that aspect, even though we will communicate the standard case when we describe it.

**Comment by kathy-phet** [comment]
@RVieyra @DianaTavares @solaolateju - Can you review and test this behavior from your perspectives and make sure we have addressed desired behavior around locales? 

@solaolateju - Please review the TO DOs with locale and make sure nothing is sim-related that is still needed. This is a last call for locale related sim needs since JO will maintenance release this - and we don't want to have to do that again since it is resource intensive.

**Comment by RVieyra** [comment]
I've done some spot-checking, and the functionality with the language codes looks good to me!

**Comment by jonathanolson** [comment]
I'll add the case-insensitivity for the query parameter!

**Comment by KatieWoe** [comment]
- [ ] Mac OS Safari Latest (Time = )
- [ ] Mac OS Chrome Latest (Time = )
- [ ] Mac OS Firefox Latest (Time = ) 

- [ ] Mac OS Safari Old (Time = )
- [ ] Mac OS Chrome Old (Time = )
- [ ] Mac OS Firefox Old (Time = ) 

- [ ] iPadOS Safari Latest (Time = )

- [ ] iPadOS Safari Old (Time = )

- [ ] Win 11 Chrome (Time = )
- [ ] Win 11 Firefox (Time = )

- [ ] Win 10 Chrome (Time = )
- [ ] Win 10 Firefox (Time = )

- [ ] Chromebook ChromeOS (Time = )

**Comment by jonathanolson** [comment]
I'm going to update the dev links momentarily for a version that includes case insensitivity!

**Comment by jonathanolson** [comment]
Updated links for case insensitivity, and added item 11 for testing.

**Comment by DianaTavares** [comment]
> @RVieyra @DianaTavares @solaolateju - Can you review and test this behavior from your perspectives and make sure we have addressed desired behavior around locales?

I reviewed the example simulations and I like them! I don't understand why some names of the locales star with a capital letter and others not (like español):

![image](https://github.com/phetsims/qa/assets/26031501/efa995ce-cc4c-42df-8aae-17d3a453e157)

But I don't see that as a problem.

**Comment by RVieyra** [comment]
@jonathanolson No, Spanish is never capitalized. It is "español" in Spanish.

**Comment by RVieyra** [comment]
Most languages won't capitalize the name of their language.

**Comment by jonathanolson** [comment]
To clarify, if it is in a context usually capitalized (or in the start of a sentence), it isn't ever capitalized?

Browsing https://es.wikipedia.org/wiki/Idioma_espa%C3%B1ol, it seems like there are contexts where it is capitalized (most notably on the right in bold):
![image](https://github.com/phetsims/qa/assets/480878/246164e4-1622-43a3-a95e-ba08ad76f4b2)

**Comment by RVieyra** [comment]
It would be capitalized at the start of a sentence, but never in something like a list of languages or in the midst of a sentence like, "I don't speak Spanish." It would be "No hablo español."

**Comment by solaolateju** [comment]
Yes, I agree with Rebecca. `español` isn't capitalized from what I found.

**Comment by solaolateju** [comment]
@jonathanolson for the sort, It appears we are currently using the language code (for example, es/español is close to English  ). I suggest we use the English string. Allow for more control and easier navigation for users.

For example,
- Iranian Persian (fa/fas) and Afghanistan Persian (fa_DA/prs) would appear in different places using either the code or locale name (endonym). They are currently named Persian and Persian (Dari). They would help teachers/students/translator  find all the options available to them. They probably would miss it if they are separated.

**Comment by KatieWoe** [comment]
Fallback locale does not seem to work. For CaV I used `?locale=es_ES` which should fall back to es, but goes to English.
![es_ES](https://github.com/phetsims/qa/assets/41024075/299443ea-6a0a-4117-a0c5-5765e5b382c2)

**Comment by KatieWoe** [comment]
The case sensitivity changes in example 11 don't seem to work for me. At least if the codes are invalid/not translated.

**Comment by Nancy-Salpepi** [comment]
@KatieWoe you said:
>Fallback locale does not seem to work. For CaV I used ?locale=es_ES which should fall back to es, but goes to English.

I see from your screenshot that you are in dev.4.....it works for me in the updated link (dev.5) and in main.

**Comment by Nancy-Salpepi** [comment]
@jonathanolson On mac + FF I see a warning (not error) every once in a while when I change ?locale:
<img width="500" alt="Screenshot 2024-05-24 at 8 41 18 AM" src="https://github.com/phetsims/qa/assets/87318828/d44abe77-3dc2-4a7c-8a0b-d5429e298e46">

**Comment by KatieWoe** [comment]
This is in MR. Calling QA to focus on the MR. @jonathanolson please close when ready

**Comment by jonathanolson** [comment]
Closed, thank you!
