### ISSUE TITLE
Testing Java 10

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/QA#109]
@phet-steele Java 10 came out today. It would be good to download, and test a few sims with, just to make sure nothing catastrophic is occuring.

**Comment by ariel-phet** [comment]
Maybe not actually a bug....but labeling legacy-bug since Java is kind of a hassle :)

**Comment by phet-steele** [comment]
http://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html

**Comment by jonathanolson** [comment]
Does this mean we should encourage use of the JAR files more?

**Comment by ariel-phet** [comment]
Marking for dev meeting, as I have lots of questions....

One the current JRE recommended for my computer to update is still "Java 8"

>  Version 8 Update 161
> Release date January 16, 2018

**Comment by samreid** [comment]
I skimmed through http://mail.openjdk.java.net/pipermail/discuss/2017-November/thread.html#4586 and did not see a timeline for removal of WebStart support.

> When do we actually expect them to start recommending JRE 10?

I'm not sure, but at the time of writing https://java.com/en/download/ is pointing to Version 8 Update 161

Perhaps one day we will need to provide instructions on how to access older versions of JREs.

**Comment by pixelzoom** [comment]
This isn't new to Java 10. WebStart was deprecated in Java 9.  See http://www.oracle.com/technetwork/java/javase/9-deprecated-features-3745636.html, search for "Java Deployment Technologies are deprecated".

**Comment by pixelzoom** [comment]
Looks like Java 8 may be the only version that does include WebStart.  See [Oracle Java SE Support Roadmap](http://www.oracle.com/us/technologies/java/eol-135779.html):

> **Support of Deployment Technology and JavaFX**
The web deployment technology, consisting of the Java Plugin and Web Start technologies, has a shorter support lifecycle. For major releases through Java SE 7, and for the Java SE 8 Plugin, Oracle provides five (5) years of Premier Support for these technologies. Java SE 8 will continue to support Web Start through Premiere and Extended Support timeframes. Java deployment technology will not be supported beyond Java SE 8. See the Oracle Lifetime Support Policy for details.
> 
> Deployment Technology for Java SE 6 and Java SE 7 has been removed as of October 2017.  Although the deployment stack may be included in Java SE 9 or later releases, Java SE 8 is the recommended and only supported version of the deployment stack.  The Java SE 8 deployment stack may be used to run Java SE 6, or Java SE 7 applications on Windows platforms.

**Comment by pixelzoom** [comment]
According to the above, "Java SE 8 is the recommended and only supported version of the deployment stack".  To run from the PhET website, PhET legacy sims require Java WebStart. And I don't think PhET wants to spend time/resources trying to make unsupported versions of WebStart play nice.  So I recommend that PhET change system requirements for legacy sims to Java 8, and only Java 8.

**Comment by samreid** [comment]
@mattpen can you please add a Help Center entry about this issue, with the recommendation to use Java 8?  If a client is unable to run WebStart using Java 6/7/9/10, we will let them know about this issue and recommend that they get Java 8.

@ariel-phet also points out that we could remove the "Run Now" button for Java sims, and recommend clients use the "Download" button.

@oliver-phet points out that either way will disrupt client usage.

@ariel-phet said perhaps we will wait until Java starts updating to 9/10, then decide what to do.

@mattpen points out that Java 11 coming in Sept is a long term release.

@mattpen says it is not trivial, but not too difficult to remove the "Run Now" button from all the Java sims.  

@ariel-phet says maybe we can outfit the code so we can "flip the switch" to get rid of the "Run Now" button once Java updates start causing trouble.

**Comment by samreid** [comment]
Also leaving open and assigned to @phet-steele to see how sims run on Java 10 (using JARs).

**Comment by zepumph** [comment]
Installer Builder issue in https://github.com/phetsims/installer-builder/issues/168, unassigning.

**Comment by phet-steele** [comment]
> Also leaving open and assigned to @phet-steele to see how sims run on Java 10 (using JARs).

I did this awhile ago on Mac and Windows and didn't have any concerns.
