### ISSUE TITLE
 iOS App: PhET for Schools

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/qa#1090]
# iOS App: PhET for Schools QA Test

## Links and dates

- Sim release for testing the online update system: Projectile Data Lab (any version)
- Sim release for testing the offline update system: Calculus Grapher (any version)
- App Previous Version: 1.4.1
- App Test Version: 1.5.0
- Public test flight link: https://testflight.apple.com/join/9hIEwNVM

## OS versions to test

For iOS, test the earliest and latest versions of the OS that are in the QA arsenal, and make a note of the version
you test if it is different from the one mentioned.

- [ ] Latest iOS, 17? (Time = 1.5) (Actual Version tested = 17.5.1)
- [ ] Earliest iOS, 12 (Time = 1) (Actual Version tested = 13.7)

## Form Factors to test

Only necessary if the test includes user interface features.

- [ ] iPhone (Time = )
- [ ] iPad (Time = )~

## Specific Test Cases

1. Upon install, the app should prompt for an Access Code.  QA should use this access code: **23AP000A**. If testing after June 1, use the code **24AP000A**.
2. There should be no way to evade the prompt in (1), e.g. by clicking the background, hitting esc on a keyboard, using the back button, or any other means.  
3. Once a valid code is entered, the submit button should be clickable.  After submitting the code, the app should work normally. 
4. In the PhET Info screen (tap the PhET logo in the bottom right of the collection view), there is a new section for the PhET For Schools Program.
5. The expiration date should be Aug 31, 2024 if your access code started with "23", or 2025 if your access code started with "24"
6. The access code you entered should show up.
7. Validate that the access code can be changed using the button.  Change it to 23QA888Z and verify that the dialog has the correct info, then change it back to 23QA999Q.
8. Verify statistics for app and sim runs are reported:
    1.  You can access the analytics by logging in to https://phet-direct.colorado.edu/analytics (creds provided separately)
    2. After you launch the app or run any sim, you should see a log of the event in the "Most recently collected events" table.
    3. After you run any sim, the appropriate count should be updated in the "Sim runs per organization" table.
    4. After you enter a new access code, the appropriate count should be updated in the "Unique Users per Organization" table. 
    5. If you run the app or sims offline, all of the events will be reported at once after you (a) bring the device online and (b) conduct another app launch or sim run

## Simulation Update Test Cases

These should be tested for every update.

<details>
<summary>
<h3>New releases are fetched.</h3>
</summary>

1. Delete any old versions of the app and install a fresh test flight copy.
2. Open the app, making sure that internet access is enabled on the device.
3. Within 2 hours, the app should have the *Sim release for testing the online update system*
   in <a href="#links-and-dates">Links and dates</a>.

</details>

<details>
<summary>
<h3>Strings available in Spanish</h3>
</summary>

1. Set the device language to Spanish (test a few "regions", if possible)
2. Open the app, ensure the app strings are available and translated (especially Access info in the PhET info screen)

</details>

**Comment by oliver-phet** [comment]
@Nancy-Salpepi @KatieWoe I created TestFlight build (77) for version 1.5.0, but my device can't seem to access it. I'm going to try to rebuild to version (1080) - hopefully that fixes the issue.

**Comment by oliver-phet** [comment]
@Nancy-Salpepi @KatieWoe build (1080) is up and running! I was able to access using the TestFlight link: https://testflight.apple.com/join/9hIEwNVM

**Comment by KatieWoe** [comment]
Something odd I've noted about the statistics collection. When changing code or reinstalling the app, if you use a code that was previously used on that device, that is remembered and the unique users count does not go up for iOS. This is not the case for Android. I don't necessarily consider this a bug, but it is inconsistent behavior.

**Comment by oliver-phet** [comment]
> Something odd I've noted about the statistics collection. When changing code or reinstalling the app, if you use a code that was previously used on that device, that is remembered and the unique users count does not go up for iOS. This is not the case for Android. I don't necessarily consider this a bug, but it is inconsistent behavior.

@apoc64 did some investigation and the User Defaults where the unique identifier is saved is _shared_ with other apps. 
@KatieWoe Do you also have the PhET production app installed?

**Comment by KatieWoe** [comment]
I deleted the production version of the app from a test device, but I still saw this behavior of the count only going up once for the device.

**Comment by Nancy-Salpepi** [comment]
>I did on that particular device, yes. @Nancy-Salpepi also saw this, did you have the production app on that device as well?

I don't believe so. I deleted what I had on the iPad before I started testing.

**Comment by KatieWoe** [comment]
This round of testing is done I believe, until fixes are released to test

**Comment by oliver-phet** [comment]
@KatieWoe @Nancy-Salpepi new TestFlight build 81 has been published.
You can access here: https://testflight.apple.com/join/9hIEwNVM

Because it is a lower version number (81) vs others (1080) I had to jump through hoops to access:

1. click the link above
2. Open in test flight
3. Previous builds 
![9E04C199-6279-4D0C-A2B3-4B99B9CB1E9E_1_201_a](https://github.com/phetsims/qa/assets/5090275/9cde3820-1eca-46f9-979b-8560eba23ef1)
4. Select (81)

**Comment by oliver-phet** [comment]
https://github.com/phetsims/qa/issues/1090

This build should fix:
- Access Code info doesn't update issues/631
- Contain an updated cache (all recent sims included)
- Should be production Release (debug and additional options not available)

Incomplete (first) collection view is a known bug and will be fixed in future update.
Unique ID will likely be preserved in Grafana

**Comment by KatieWoe** [comment]
All three things seem fixed to me.
