### ISSUE TITLE
Spot check screen reader support

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/qa#1093]
It would be helpful to make sure that https://github.com/phetsims/scenery/issues/1141 hasn't broken any screen reader access. Can you please briefly test greenhouse-effect on main for each of these? 
- [x] NVDA
- [x] JAWS
- [x] iOS VoiceOver
- [x] VoiceOver

Hopefully it doesn't take more than 5 minutes per device, I just want to make sure that input isn't obviously broken and behaves as it did in https://github.com/phetsims/qa/issues/1092.

This is not urgent, for whenever you have a moment.

Thanks!

**Comment by jessegreenberg** [comment]
Oh good point, thanks. If it is broken in main, that is an issue. I think the main thing to check for is that you can still interact with things. My change has the largets chance of breaking input. So to test, make sure you can double tap on buttons to click them, swipe to use sliders, and so on. For the alerts, as long as it is working like we discussed in https://github.com/phetsims/utterance-queue/issues/117#issuecomment-2127753196, it is OK.

**Comment by Nancy-Salpepi** [comment]
mobileVO calls radio buttons checkboxes AND radio buttons but I think that might have been happening prior to your changes.

**Comment by jessegreenberg** [comment]
OK, thanks - I will take a look at that.

**Comment by jessegreenberg** [comment]
I am seeing that too with with iOS 17.5.1 in a very basic example outside of a PhET sim (https://htmlpreview.github.io/?https://github.com/phetsims/a11y-research/blob/main/reader-intro.html), so that is just how VoiceOver does it. Ill add that to the list of accessibility bugs.

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Great, thank you @KatieWoe and @Nancy-Salpepi!
