### ISSUE TITLE
Locale Updates - check website translations of language names

### ISSUE THREAD

**Issue by mattpen** [phetsims/qa#1097]
QA, can you please verify that instances of languages names are showing up properly for sim translations on the website?  Translated Language names should match the latest babel data here: https://github.com/phetsims/babel/blob/main/localeData.json

- [ ] Translated Sims Table: https://ox-dev.colorado.edu/en/simulations/translated
- [ ] Locale Filter Dropdown: https://ox-dev.colorado.edu/en/simulations/filter
- [ ] Translations Table for a Sim Page, such as CAV: https://ox-dev.colorado.edu/en/simulations/center-and-variability/translations

**Comment by KatieWoe** [comment]
Albanian/shqipe/shqip don't match on the Sims Table

**Comment by mattpen** [comment]
I fixed the link in the original comment for `Translated Sims Table`, which should fix Katie's comment above.

**Comment by KatieWoe** [comment]
Ok, I did a brief check on all of them, and a bit more in-depth on the Sim table. I noticed that the Chinese locales had formatting inconsistent between https://ox-dev.colorado.edu/en/simulations/translated and https://github.com/phetsims/babel/blob/main/localeData.json.
I'm also unsure why https://ox-dev.colorado.edu/en/simulations/filter?&type=html is ordered as it is.

**Comment by mattpen** [comment]
@KatieWoe - the formatting and ordering problems should be fixed.

**Comment by KatieWoe** [comment]
Sorry I hadn't responded to this earlier, I somehow missed it. Those two things look ok on ox-dev from what I can tell.

**Comment by mattpen** [comment]
Thanks!
