### ISSUE TITLE
Locale MR 2 - PhET-iO Hydrogen Standard Wrapper changes

### ISSUE THREAD

**Issue by zepumph** [phetsims/qa#1098]
Hello QA! We have another MR related to recent locale changes. This time it is only for PhET-iO Hydrogen simulations. The goal is to support the new form of `?locale` in the PhET-iO Standard Wrapper. The previous changeset did not do this correctly.

Some issue linking:
https://github.com/phetsims/joist/issues/970
https://github.com/phetsims/phet-io/issues/1881
https://github.com/phetsims/chipper/issues/1441
https://github.com/phetsims/qa/issues/1089
central main locale feature issue: https://github.com/phetsims/joist/issues/963
https://github.com/phetsims/joist/issues/965

previous QA testing:
original dev tests: https://github.com/phetsims/qa/issues/1085
phet brand MR: https://github.com/phetsims/qa/issues/1089

@jonathanolson @kathy-phet @brent-phet @JacquiHayes @arouinfar.

The feature is described here: https://github.com/phetsims/phet-io/issues/1881#issuecomment-1287618206

For testing, here is an outline of the things to test for each sim. 
* In PhET brand just do couple of sanity `?locale` checks similar to how the previous QA test was done.
* In studio, ensure that the `?locale` query parameter works well (similar to above bullet).
* The following tests should be done with and without `?locale` provided to studio:
	* change locale in studio tree with localeProperty, make sure it works, and make sure testing the standard wrapper loads with that locale.
	* download standard wrapper and run the following tests on the downloaded wrapper:		
		* ensure no query parameter loads the value of the `localeProperty` in studio upon download.
		* use `?locale` and it should work as expected in PhET brand, no matter what the query parameter and localeProperty values were from studio (testing locale3/hyphens/case-insensitivity/etc). EXCEPT!! There will never be a Warning dialog for badly formatted locales, and instead will be an assertion (only in phetioDebug=true).
					
Thanks again and let me know if you have any questions.

Links:

**acid-base-solutions 1.3** (https://github.com/phetsims/joist/issues/970)

- [x] [acid-base-solutions 1.3.7-rc.1](https://phet-dev.colorado.edu/html/acid-base-solutions/1.3.7-rc.1/phet/acid-base-solutions_all_phet.html)
- [x] [acid-base-solutions 1.3.7-rc.1 phet-io](https://phet-dev.colorado.edu/html/acid-base-solutions/1.3.7-rc.1/phet-io/acid-base-solutions_all_phet-io.html?phetioStandalone)
- [x] [acid-base-solutions 1.3.7-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/acid-base-solutions/1.3.7-rc.1/phet-io/wrappers/studio)

**beers-law-lab 1.7** (https://github.com/phetsims/joist/issues/970)

- [x] [beers-law-lab 1.7.12-rc.1](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.12-rc.1/phet/beers-law-lab_all_phet.html)
- [x] [beers-law-lab 1.7.12-rc.1 phet-io](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.12-rc.1/phet-io/beers-law-lab_all_phet-io.html?phetioStandalone)
- [x] [beers-law-lab 1.7.12-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.12-rc.1/phet-io/wrappers/studio)

**calculus-grapher 1.0** (https://github.com/phetsims/joist/issues/970)

- [x] [calculus-grapher 1.0.10-rc.1](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.10-rc.1/phet/calculus-grapher_all_phet.html)
- [x] [calculus-grapher 1.0.10-rc.1 phet-io](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.10-rc.1/phet-io/calculus-grapher_all_phet-io.html?phetioStandalone)
- [x] [calculus-grapher 1.0.10-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.10-rc.1/phet-io/wrappers/studio)

**center-and-variability 1.1** (https://github.com/phetsims/joist/issues/970)

- [x] [center-and-variability 1.1.8-rc.1](https://phet-dev.colorado.edu/html/center-and-variability/1.1.8-rc.1/phet/center-and-variability_all_phet.html)
- [x] [center-and-variability 1.1.8-rc.1 phet-io](https://phet-dev.colorado.edu/html/center-and-variability/1.1.8-rc.1/phet-io/center-and-variability_all_phet-io.html?phetioStandalone)
- [x] [center-and-variability 1.1.8-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/center-and-variability/1.1.8-rc.1/phet-io/wrappers/studio)

**circuit-construction-kit-dc 1.3** (https://github.com/phetsims/joist/issues/970)

- [x] [circuit-construction-kit-dc 1.3.13-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.13-rc.1/phet/circuit-construction-kit-dc_all_phet.html)
- [x] [circuit-construction-kit-dc 1.3.13-rc.1 phet-io](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.13-rc.1/phet-io/circuit-construction-kit-dc_all_phet-io.html?phetioStandalone)
- [ ] [circuit-construction-kit-dc 1.3.13-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.13-rc.1/phet-io/wrappers/studio)

**circuit-construction-kit-dc-virtual-lab 1.3** (https://github.com/phetsims/joist/issues/970)

- [ ] [circuit-construction-kit-dc-virtual-lab 1.3.11-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.11-rc.1/phet/circuit-construction-kit-dc-virtual-lab_all_phet.html)
- [ ] [circuit-construction-kit-dc-virtual-lab 1.3.11-rc.1 phet-io](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.11-rc.1/phet-io/circuit-construction-kit-dc-virtual-lab_all_phet-io.html?phetioStandalone)
- [ ] [circuit-construction-kit-dc-virtual-lab 1.3.11-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.11-rc.1/phet-io/wrappers/studio)

**concentration 1.7** (https://github.com/phetsims/joist/issues/970)

- [ ] [concentration 1.7.12-rc.1](https://phet-dev.colorado.edu/html/concentration/1.7.12-rc.1/phet/concentration_all_phet.html)
- [ ] [concentration 1.7.12-rc.1 phet-io](https://phet-dev.colorado.edu/html/concentration/1.7.12-rc.1/phet-io/concentration_all_phet-io.html?phetioStandalone)
- [ ] [concentration 1.7.12-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/concentration/1.7.12-rc.1/phet-io/wrappers/studio)

**density 1.1** (https://github.com/phetsims/joist/issues/970)

- [ ] [density 1.1.9-rc.1](https://phet-dev.colorado.edu/html/density/1.1.9-rc.1/phet/density_all_phet.html)
- [ ] [density 1.1.9-rc.1 phet-io](https://phet-dev.colorado.edu/html/density/1.1.9-rc.1/phet-io/density_all_phet-io.html?phetioStandalone)
- [ ] [density 1.1.9-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/density/1.1.9-rc.1/phet-io/wrappers/studio)

**friction 1.6** (https://github.com/phetsims/joist/issues/970)

- [ ] [friction 1.6.13-rc.1](https://phet-dev.colorado.edu/html/friction/1.6.13-rc.1/phet/friction_all_phet.html)
- [ ] [friction 1.6.13-rc.1 phet-io](https://phet-dev.colorado.edu/html/friction/1.6.13-rc.1/phet-io/friction_all_phet-io.html?phetioStandalone)
- [ ] [friction 1.6.13-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/friction/1.6.13-rc.1/phet-io/wrappers/studio)

**geometric-optics 1.3** (https://github.com/phetsims/joist/issues/970)

- [ ] [geometric-optics 1.3.8-rc.1](https://phet-dev.colorado.edu/html/geometric-optics/1.3.8-rc.1/phet/geometric-optics_all_phet.html)
- [ ] [geometric-optics 1.3.8-rc.1 phet-io](https://phet-dev.colorado.edu/html/geometric-optics/1.3.8-rc.1/phet-io/geometric-optics_all_phet-io.html?phetioStandalone)
- [ ] [geometric-optics 1.3.8-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/geometric-optics/1.3.8-rc.1/phet-io/wrappers/studio)

**geometric-optics-basics 1.3** (https://github.com/phetsims/joist/issues/970)

- [ ] [geometric-optics-basics 1.3.8-rc.1](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.8-rc.1/phet/geometric-optics-basics_all_phet.html)
- [ ] [geometric-optics-basics 1.3.8-rc.1 phet-io](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.8-rc.1/phet-io/geometric-optics-basics_all_phet-io.html?phetioStandalone)
- [ ] [geometric-optics-basics 1.3.8-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.8-rc.1/phet-io/wrappers/studio)

**graphing-quadratics 1.3** (https://github.com/phetsims/joist/issues/970)

- [ ] [graphing-quadratics 1.3.9-rc.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.9-rc.1/phet/graphing-quadratics_all_phet.html)
- [ ] [graphing-quadratics 1.3.9-rc.1 phet-io](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.9-rc.1/phet-io/graphing-quadratics_all_phet-io.html?phetioStandalone)
- [ ] [graphing-quadratics 1.3.9-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.9-rc.1/phet-io/wrappers/studio)

**gravity-and-orbits 1.6** (https://github.com/phetsims/joist/issues/970)

- [ ] [gravity-and-orbits 1.6.20-rc.1](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.20-rc.1/phet/gravity-and-orbits_all_phet.html)
- [ ] [gravity-and-orbits 1.6.20-rc.1 phet-io](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.20-rc.1/phet-io/gravity-and-orbits_all_phet-io.html?phetioStandalone)
- [ ] [gravity-and-orbits 1.6.20-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.20-rc.1/phet-io/wrappers/studio)

**greenhouse-effect 1.2** (https://github.com/phetsims/joist/issues/970)

- [ ] [greenhouse-effect 1.2.9-rc.1 phet-io](https://phet-dev.colorado.edu/html/greenhouse-effect/1.2.9-rc.1/phet-io/greenhouse-effect_all_phet-io.html?phetioStandalone)
- [ ] [greenhouse-effect 1.2.9-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/greenhouse-effect/1.2.9-rc.1/phet-io/wrappers/studio)

**greenhouse-effect 1.3** (https://github.com/phetsims/joist/issues/970)

- [ ] [greenhouse-effect 1.3.1-rc.1](https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.1-rc.1/phet/greenhouse-effect_all_phet.html)
- [ ] [greenhouse-effect 1.3.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.1-rc.1/phet-io/greenhouse-effect_all_phet-io.html?phetioStandalone)
- [ ] [greenhouse-effect 1.3.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.1-rc.1/phet-io/wrappers/studio)

**keplers-laws 1.2** (https://github.com/phetsims/joist/issues/970)

- [ ] [keplers-laws 1.2.3-rc.1](https://phet-dev.colorado.edu/html/keplers-laws/1.2.3-rc.1/phet/keplers-laws_all_phet.html)
- [ ] [keplers-laws 1.2.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/keplers-laws/1.2.3-rc.1/phet-io/keplers-laws_all_phet-io.html?phetioStandalone)
- [ ] [keplers-laws 1.2.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/keplers-laws/1.2.3-rc.1/phet-io/wrappers/studio)

**molecule-polarity 1.3** (https://github.com/phetsims/joist/issues/970)

- [ ] [molecule-polarity 1.3.8-rc.1](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.8-rc.1/phet/molecule-polarity_all_phet.html)
- [ ] [molecule-polarity 1.3.8-rc.1 phet-io](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.8-rc.1/phet-io/molecule-polarity_all_phet-io.html?phetioStandalone)
- [ ] [molecule-polarity 1.3.8-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.8-rc.1/phet-io/wrappers/studio)

**molecule-shapes 1.6** (https://github.com/phetsims/joist/issues/970)

- [ ] [molecule-shapes 1.6.11-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.11-rc.1/phet/molecule-shapes_all_phet.html)
- [ ] [molecule-shapes 1.6.11-rc.1 phet-io](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.11-rc.1/phet-io/molecule-shapes_all_phet-io.html?phetioStandalone)
- [ ] [molecule-shapes 1.6.11-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.11-rc.1/phet-io/wrappers/studio)

**molecule-shapes-basics 1.6** (https://github.com/phetsims/joist/issues/970)

- [ ] [molecule-shapes-basics 1.6.11-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.11-rc.1/phet/molecule-shapes-basics_all_phet.html)
- [ ] [molecule-shapes-basics 1.6.11-rc.1 phet-io](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.11-rc.1/phet-io/molecule-shapes-basics_all_phet-io.html?phetioStandalone)
- [ ] [molecule-shapes-basics 1.6.11-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.11-rc.1/phet-io/wrappers/studio)

**my-solar-system 1.3** (https://github.com/phetsims/joist/issues/970)

- [ ] [my-solar-system 1.3.5-rc.1](https://phet-dev.colorado.edu/html/my-solar-system/1.3.5-rc.1/phet/my-solar-system_all_phet.html)
- [ ] [my-solar-system 1.3.5-rc.1 phet-io](https://phet-dev.colorado.edu/html/my-solar-system/1.3.5-rc.1/phet-io/my-solar-system_all_phet-io.html?phetioStandalone)
- [ ] [my-solar-system 1.3.5-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/my-solar-system/1.3.5-rc.1/phet-io/wrappers/studio)

**natural-selection 1.5** (https://github.com/phetsims/joist/issues/970)

- [ ] [natural-selection 1.5.8-rc.1](https://phet-dev.colorado.edu/html/natural-selection/1.5.8-rc.1/phet/natural-selection_all_phet.html)
- [ ] [natural-selection 1.5.8-rc.1 phet-io](https://phet-dev.colorado.edu/html/natural-selection/1.5.8-rc.1/phet-io/natural-selection_all_phet-io.html?phetioStandalone)
- [ ] [natural-selection 1.5.8-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/natural-selection/1.5.8-rc.1/phet-io/wrappers/studio)

**ph-scale 1.6** (https://github.com/phetsims/joist/issues/970)

- [ ] [ph-scale 1.6.14-rc.1](https://phet-dev.colorado.edu/html/ph-scale/1.6.14-rc.1/phet/ph-scale_all_phet.html)
- [ ] [ph-scale 1.6.14-rc.1 phet-io](https://phet-dev.colorado.edu/html/ph-scale/1.6.14-rc.1/phet-io/ph-scale_all_phet-io.html?phetioStandalone)
- [ ] [ph-scale 1.6.14-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/ph-scale/1.6.14-rc.1/phet-io/wrappers/studio)

**ph-scale-basics 1.6** (https://github.com/phetsims/joist/issues/970)

- [ ] [ph-scale-basics 1.6.13-rc.1](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.13-rc.1/phet/ph-scale-basics_all_phet.html)
- [ ] [ph-scale-basics 1.6.13-rc.1 phet-io](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.13-rc.1/phet-io/ph-scale-basics_all_phet-io.html?phetioStandalone)
- [ ] [ph-scale-basics 1.6.13-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.13-rc.1/phet-io/wrappers/studio)

**projectile-data-lab 1.0** (https://github.com/phetsims/joist/issues/970)

- [ ] [projectile-data-lab 1.0.2-rc.1](https://phet-dev.colorado.edu/html/projectile-data-lab/1.0.2-rc.1/phet/projectile-data-lab_all_phet.html)
- [ ] [projectile-data-lab 1.0.2-rc.1 phet-io](https://phet-dev.colorado.edu/html/projectile-data-lab/1.0.2-rc.1/phet-io/projectile-data-lab_all_phet-io.html?phetioStandalone)
- [ ] [projectile-data-lab 1.0.2-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/projectile-data-lab/1.0.2-rc.1/phet-io/wrappers/studio)

**projectile-sampling-distributions 1.0** (https://github.com/phetsims/joist/issues/970)

- [x] [projectile-sampling-distributions 1.0.2-rc.1](https://phet-dev.colorado.edu/html/projectile-sampling-distributions/1.0.2-rc.1/phet/projectile-sampling-distributions_all_phet.html)
- [x] [projectile-sampling-distributions 1.0.2-rc.1 phet-io](https://phet-dev.colorado.edu/html/projectile-sampling-distributions/1.0.2-rc.1/phet-io/projectile-sampling-distributions_all_phet-io.html?phetioStandalone)
- [x] [projectile-sampling-distributions 1.0.2-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/projectile-sampling-distributions/1.0.2-rc.1/phet-io/wrappers/studio)

**Comment by Nancy-Salpepi** [comment]
@zepumph in https://github.com/phetsims/qa/issues/1089 if I added `?locale=`  without anything after the equals sign, the sim loaded in English. Now the sim doesn't go past the splash screen and this appears in the console:
<img width="514" alt="Screenshot 2024-06-20 at 11 58 30 AM" src="https://github.com/phetsims/qa/assets/87318828/293de55d-60fa-4b4b-a8f6-b8c843f1f3ea">

**Comment by zepumph** [comment]
These are both excellent reports. Looks like some versions like ABS  1.3 need a default optional tandem for the QueryParameterWarningDialog. This is in main now, but will be buggy for sims before 3/24, https://github.com/phetsims/joist/commit/0de4d977ae63984215748fc5c0b25d4b701ea4c6

The other one will also require a patch. We are not graceful the null case of the query parameter.

**Comment by Nancy-Salpepi** [comment]
@zepumph 
When a regional locale (e.g.de-li) has some common code strings translated but no sim-specific strings, opening the localization menu in the preferences will show no selected language.
Likewise, in studio the localeProperty will indicate that de-li is the current language, but there will be no radio button for it. 

<img width="840" alt="Screenshot 2024-06-20 at 4 02 01 PM" src="https://github.com/phetsims/qa/assets/87318828/28026388-4283-4335-91d0-9f8aadf5b87b">

**Comment by KatieWoe** [comment]
https://github.com/phetsims/qa/issues/1098#issuecomment-2181489185. This also seems to be the case if you use a locale that isn't translated, but its fallback is. Such as es_ES

**Comment by Nancy-Salpepi** [comment]
For https://githuhb.com/phetsims/qa/issues/1098#issuecomment-2181489185 is does still seem to work correctly in the standard wrapper
When adding ?locale =de-li to the end of the url, German will be selected in the localization tab.

<details>
  <summary>image</summary>
<img width="1018" alt="Screenshot 2024-06-20 at 5 06 57 PM" src="https://github.com/phetsims/qa/assets/87318828/25f9dbed-2624-4745-a304-6016d474e72b">
</details>

**Comment by KatieWoe** [comment]
When testing the locale parameter on a downloaded sim from the studio wrapper, it does not give an error for invalid entries, such as `locale=x`

**Comment by Nancy-Salpepi** [comment]
This no longer seems to be working:
>String fallback should work, where if a translation does NOT have a translation for a string, but a fallback DOES, the first fallback with a translation will be used for that string. (e.g. in center-and-variability, es_PE itself does not yet have translations for the region-and-culture section 

<details>
  <summary>image</summary>
<img width="481" alt="Screenshot 2024-06-20 at 8 20 43 PM" src="https://github.com/phetsims/qa/assets/87318828/8b7388f2-ce6f-4ccb-81f1-896c962d35df">
 </details>

**Comment by Nancy-Salpepi** [comment]
Further investigation of https://github.com/phetsims/qa/issues/1098#issuecomment-2181768905 shows that the with ?locale=es the region and culture section isn't translated either. 

I looked back at https://github.com/phetsims/qa/issues/1085 and we tested CAV 1.2.0-dev.5, but here were are testing 1.1.8-rc.1.

**Comment by KatieWoe** [comment]
On hold until say so from @zepumph

**Comment by zepumph** [comment]
New RCs have been created. We will pick things back up in https://github.com/phetsims/qa/issues/1103. Thanks QA.
