### ISSUE TITLE
RC Test: Forces and Motion Basics 2.3.0-rc.2

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#11]
( @jessegreenberg @arouinfar @oliver-phet ) 

2.3.0-rc.2 is ready for RC testing. 

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-rc.2/forces-and-motion-basics_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-rc.2/forces-and-motion-basics_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1U2-hwtOCMVTnnWaviONSJUNEqseKB-d_1Sc_ttZRILU/edit#gid=1018120986)**

**Issues to Verify**
This RC is to address the user requested features from the following link.
[See here](https://github.com/phetsims/forces-and-motion-basics/issues/220#issuecomment-305549179) for a list of the things that were changed in the parent issues.
Here is the list of changes from that issue:
>- All changes are in the "Net Force" screen
>- NetForceScreenView includes two new ```CartStopperNodes``` placed at a location which will stop movement of the cart.
>- The cart can move about twice as far along the screen since the stoppers are placed farther than the previous version allowed the cart to move.
>- The pullers stand up when the game is over
>- The speedometer was added to the center of the cart, showing speed of the moving cart
>- A "Speed" checkbox was added to the control panel, which toggles visibility of a speedometer

**Please also verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any new issues are found, please note them in https://github.com/phetsims/forces-and-motion-basics/issues/227 and reference this issue.  

Added labels from https://github.com/phetsims/QA/issues/5, as this issue replaces it.

**Comment by phet-steele** [comment]
@jessegreenberg, done! But not done with #12
