### ISSUE TITLE
Document Steele's mind

### ISSUE THREAD

**Issue by phet-steele** [phetsims/QA#110]
Started here: https://docs.google.com/document/d/1Fr-B66SD-6Xt7egNv9ZeSXdcsK6k8Lkc0nqR853_eJ4/edit?usp=sharing

Final draft due first week of May.

**Comment by ariel-phet** [comment]
I see no section on the proper use of gifs....but otherwise looking good.

I am going to mark for dev meeting next week, to see if devs think there are any topics missing from the table of contents.

**Comment by jessegreenberg** [comment]
Looking good. The "what to do" section under "Dev Testing" is very valuable, will something similar be added under the "RC Testing" section?

**Comment by lmulhall-phet** [comment]
@jessegreenberg Yeah, it'll be fairly comprehensive when we're done with it.

**Comment by Denz1994** [comment]
+1 to adding a tutorial on the use of gifs in issues. I've always found them really helpful. Seems like a good read for newer devs as well.

**Comment by jonathanolson** [comment]
Didn't see references to continuous testing or phettest?

**Comment by lmulhall-phet** [comment]
View the finished version of the "QA Handbook" here: https://docs.google.com/document/d/1Fr-B66SD-6Xt7egNv9ZeSXdcsK6k8Lkc0nqR853_eJ4/edit#heading=h.oz7vdnbiq4ni.

**Comment by lmulhall-phet** [comment]
I'm happy to copy and paste the above into a Google doc, if anyone wants.

**Comment by lmulhall-phet** [comment]
Assigning to @ariel-phet. I finished my QA Handbook. (Maybe go over it in a dev meeting?) Clara's handbook is for student workers, not the QA team lead.

**Comment by lmulhall-phet** [comment]
I think we can close this issue at this point.
