### ISSUE TITLE
Dev Test: Hooke's Law 1.1.0-dev.18

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/qa#1102]
<h1>Dev Test</h1>

**Mentions**: @Nancy-Salpepi @KatieWoe @kathy-phet @pixelzoom

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/hookes-law/issues)
- [phet top-level directory](https://phet-dev.colorado.edu/html/hookes-law/1.1.0-dev.18)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/hookes-law/1.1.0-dev.18/phet/hookes-law_all_phet.html)

<h3>Test Matrix</h3>

Please include all (non-screen reader) feature testing in these records if applicable.

- [x] Latest macOS, Safari (Time = 2 hrs)
- [x] Latest iOS, Safari (Time = .75)
- [x] Windows 10/11, Firefox (Time = 3 hrs)
- [x] Windows 11, Chrome (Time = 2)
- [x] Latest Chrome OS, Chrome (Time = 2hrs)

Light testing, or optionally skip if time crunch:

- [x] Latest macOS, Chrome (Time = 1hr)
- [ ] Windows 10, Chrome (Time = )

<h3>Features included</h3>

- ~PhET-iO~
- [x] Dynamic Locale
- ~Alternative Input~
- ~UI Sound~
- ~Sonification~
- ~Description~
- ~Voicing~

<h3>Focus and Special Instructions</h3>

We are re-publishing this sim off of main with only PhET brand. The goal for the publication is to make the sim easier to maintain. In addition to a typical dev test, can you please make sure there are no regressions or unexpected changes from the last version?

New features include pan and zoom and dynamic locale, since these now are enabled by default in main.

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<hr>

</details>

<details>
<summary><b>PhET-iO features</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
  sure the simulation loads without crashing or throwing errors.

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Interactive Description
  - Sound and Sonification
  - Pan and Zoom
  - Mobile Description
  - Voicing
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[here](https://github.com/phetsims/qa/blob/main/documentation/accessibility-bugs.md). If you find a screen reader bug,
please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel
controls. Please test magnfication and make sure it is working as intended and well with the use cases of the
simulation. Due to the way screen readers handle user input, magnification is NOT expected to work while using a screen
reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by jessegreenberg** [comment]
Just noting a couple of things I noticed comparing to the published version. The layout has changed and now this text has scaled down:
![image](https://github.com/phetsims/qa/assets/6396244/da35bdd5-e08b-424d-af48-de2107e87f22)

We gained a decimal point on this number control:
![image](https://github.com/phetsims/qa/assets/6396244/1b6f9739-cf0c-4fde-b1dc-9a12360d362f)

**Comment by Nancy-Salpepi** [comment]
A couple of other differences I see when comparing to the published version:
-  On the Energy screen, the Energy Checkbox is now centered on the panel
- On the Energy screen, when at max values the Applied Force arrow now touches the panel. 

Dev Version vs. Published:

<img width="359" alt="Screenshot 2024-06-28 at 8 30 10 AM" src="https://github.com/phetsims/qa/assets/87318828/6d07670f-2fbb-4f2f-8be7-3d49426dd64f"> <img width="359" alt="Screenshot 2024-06-28 at 8 29 58 AM" src="https://github.com/phetsims/qa/assets/87318828/eee656ba-788b-4a92-bf88-2e70e9f09ae4">

**Comment by KatieWoe** [comment]
Shorter strings can move the images next to them, which didn't happen in published. Both dynamic and non-dynamic locale seems impacted.
![moving](https://github.com/phetsims/qa/assets/41024075/60c6c338-e879-4ab1-898d-bbf4589cff7b)

**Comment by marlitas** [comment]
@KatieWoe Why is this not in the project board?

**Comment by Nancy-Salpepi** [comment]
>@KatieWoe Why is this not in the project board?

Didn't even realize it wasn't there. I moved it over (even though I'm not Katie 🙃)

**Comment by KatieWoe** [comment]
Sorry bout that. Slipped my mind.

**Comment by Matthew-Moore240** [comment]
To add to @KatieWoe [comment](https://github.com/phetsims/qa/issues/1102#issuecomment-2197271982) it was a little easier to see using ?stringTest=dynamic 



Arrows moving quite a bit. 


https://github.com/phetsims/qa/assets/48224214/8271d087-394e-41b5-af0e-fd5247acca56

**Comment by KatieWoe** [comment]
Memory test looked ok. If there is a leak it is small.
![memhooke](https://github.com/phetsims/qa/assets/41024075/b9cebad6-4358-411e-9892-e1aa7272a534)

**Comment by kathy-phet** [comment]
@jessegreenberg @KatieWoe @Nancy-Salpepi - If you haven't already, can you please move your dynamic layout comments to this issue that is already open, so they are all compiled in there: https://github.com/phetsims/hookes-law/issues/81
Thanks!

**Comment by jessegreenberg** [comment]
Yes, I moved comments above into https://github.com/phetsims/hookes-law/issues/81#issuecomment-2198782920.

**Comment by KatieWoe** [comment]
QA is done

**Comment by Nancy-Salpepi** [comment]
QA credits: Jaron Droder, Matthew Moore, Nancy Salpepi, Kathryn Woessner

**Comment by pixelzoom** [comment]
All of the issues reported in comments herein were moved to their own issues, and have been addressed. 

Memory testing indicates no leaks, see https://github.com/phetsims/hookes-law/issues/67.

We're ready to move to RC testing. Closing.
