### ISSUE TITLE
(Take 2) Locale MR 2 - PhET-iO Hydrogen Standard Wrapper changes 

### ISSUE THREAD

**Issue by zepumph** [phetsims/qa#1103]
Hello again! This is the second round of RC tests for the Standard PhET-iO Wrapper portion of the the new locale query parameter feature. The previous QA issue is here: https://github.com/phetsims/qa/issues/1098, and didn't go too well. I believe we have patched up everything though, and are ready for the next go. 

This content is the same as the previous QA issue:

The feature is described here: https://github.com/phetsims/phet-io/issues/1881#issuecomment-1287618206

For testing, here is an outline of the things to test for each sim. 
* In PhET brand just do couple of sanity `?locale` checks similar to how the previous QA test was done.
* In studio, ensure that the `?locale` query parameter works well (similar to above bullet).
* The following tests should be done with and without `?locale` provided to studio:
	* change locale in studio tree with localeProperty, make sure it works, and make sure testing the standard wrapper loads with that locale.
	* download standard wrapper and run the following tests on the downloaded wrapper:		
		* ensure no query parameter loads the value of the `localeProperty` in studio upon download.
		* use `?locale` and it should work as expected in PhET brand, no matter what the query parameter and localeProperty values were from studio (testing locale3/hyphens/case-insensitivity/etc). EXCEPT!! There will never be a Warning dialog for badly formatted locales, and instead will be an assertion (only in phetioDebug=true).

--------

And I'll also link the original testing instructions for the main locale release: https://github.com/phetsims/qa/issues/1089#issue-2314004886

All of the above should work well now. We made many automated tests on our side to test the majority of the featurset, and so (hopefully) this will feel like a spot check instead of a thorough testing of each release. Please do dive deep a couple times though.

Please report any problems in this issue, and they will likely be handled over in https://github.com/phetsims/joist/issues/970.

And as always, thank you for doing this horrible, horrible work. I appreciate you!

--------------------------------

**Release Candidate links**

**acid-base-solutions 1.3** (https://github.com/phetsims/joist/issues/970)

- [x] [acid-base-solutions 1.3.7-rc.2](https://phet-dev.colorado.edu/html/acid-base-solutions/1.3.7-rc.2/phet/acid-base-solutions_all_phet.html)
- [x] [acid-base-solutions 1.3.7-rc.2 phet-io](https://phet-dev.colorado.edu/html/acid-base-solutions/1.3.7-rc.2/phet-io/acid-base-solutions_all_phet-io.html?phetioStandalone)
- [x] [acid-base-solutions 1.3.7-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/acid-base-solutions/1.3.7-rc.2/phet-io/wrappers/studio)

**beers-law-lab 1.7** (https://github.com/phetsims/joist/issues/970)

- [x] [beers-law-lab 1.7.12-rc.2](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.12-rc.2/phet/beers-law-lab_all_phet.html)
- [x] [beers-law-lab 1.7.12-rc.2 phet-io](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.12-rc.2/phet-io/beers-law-lab_all_phet-io.html?phetioStandalone)
- [x] [beers-law-lab 1.7.12-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.12-rc.2/phet-io/wrappers/studio)

**calculus-grapher 1.0** (https://github.com/phetsims/joist/issues/970)

- [x] [calculus-grapher 1.0.10-rc.2](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.10-rc.2/phet/calculus-grapher_all_phet.html)
- [x] [calculus-grapher 1.0.10-rc.2 phet-io](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.10-rc.2/phet-io/calculus-grapher_all_phet-io.html?phetioStandalone)
- [x] [calculus-grapher 1.0.10-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.10-rc.2/phet-io/wrappers/studio)

**center-and-variability 1.1** (https://github.com/phetsims/joist/issues/970)

- [x] [center-and-variability 1.1.8-rc.2](https://phet-dev.colorado.edu/html/center-and-variability/1.1.8-rc.2/phet/center-and-variability_all_phet.html)
- [x] [center-and-variability 1.1.8-rc.2 phet-io](https://phet-dev.colorado.edu/html/center-and-variability/1.1.8-rc.2/phet-io/center-and-variability_all_phet-io.html?phetioStandalone)
- [x] [center-and-variability 1.1.8-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/center-and-variability/1.1.8-rc.2/phet-io/wrappers/studio)

**circuit-construction-kit-dc 1.3** (https://github.com/phetsims/joist/issues/970)

- [x] [circuit-construction-kit-dc 1.3.13-rc.2](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.13-rc.2/phet/circuit-construction-kit-dc_all_phet.html)
- [x] [circuit-construction-kit-dc 1.3.13-rc.2 phet-io](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.13-rc.2/phet-io/circuit-construction-kit-dc_all_phet-io.html?phetioStandalone)
- [x] [circuit-construction-kit-dc 1.3.13-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.13-rc.2/phet-io/wrappers/studio)

**circuit-construction-kit-dc-virtual-lab 1.3** (https://github.com/phetsims/joist/issues/970)

- [x] [circuit-construction-kit-dc-virtual-lab 1.3.11-rc.2](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.11-rc.2/phet/circuit-construction-kit-dc-virtual-lab_all_phet.html)
- [x] [circuit-construction-kit-dc-virtual-lab 1.3.11-rc.2 phet-io](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.11-rc.2/phet-io/circuit-construction-kit-dc-virtual-lab_all_phet-io.html?phetioStandalone)
- [x] [circuit-construction-kit-dc-virtual-lab 1.3.11-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.11-rc.2/phet-io/wrappers/studio)

**concentration 1.7** (https://github.com/phetsims/joist/issues/970)

- [x] [concentration 1.7.12-rc.2](https://phet-dev.colorado.edu/html/concentration/1.7.12-rc.2/phet/concentration_all_phet.html)
- [x] [concentration 1.7.12-rc.2 phet-io](https://phet-dev.colorado.edu/html/concentration/1.7.12-rc.2/phet-io/concentration_all_phet-io.html?phetioStandalone)
- [x] [concentration 1.7.12-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/concentration/1.7.12-rc.2/phet-io/wrappers/studio)

**density 1.1** (https://github.com/phetsims/joist/issues/970)

- [x] [density 1.1.9-rc.2](https://phet-dev.colorado.edu/html/density/1.1.9-rc.2/phet/density_all_phet.html)
- [x] [density 1.1.9-rc.2 phet-io](https://phet-dev.colorado.edu/html/density/1.1.9-rc.2/phet-io/density_all_phet-io.html?phetioStandalone)
- [x] [density 1.1.9-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/density/1.1.9-rc.2/phet-io/wrappers/studio)

**friction 1.6** (https://github.com/phetsims/joist/issues/970)

- [x] [friction 1.6.13-rc.2](https://phet-dev.colorado.edu/html/friction/1.6.13-rc.2/phet/friction_all_phet.html)
- [x] [friction 1.6.13-rc.2 phet-io](https://phet-dev.colorado.edu/html/friction/1.6.13-rc.2/phet-io/friction_all_phet-io.html?phetioStandalone)
- [x] [friction 1.6.13-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/friction/1.6.13-rc.2/phet-io/wrappers/studio)

**geometric-optics 1.3** (https://github.com/phetsims/joist/issues/970)

- [x] [geometric-optics 1.3.8-rc.2](https://phet-dev.colorado.edu/html/geometric-optics/1.3.8-rc.2/phet/geometric-optics_all_phet.html)
- [x] [geometric-optics 1.3.8-rc.2 phet-io](https://phet-dev.colorado.edu/html/geometric-optics/1.3.8-rc.2/phet-io/geometric-optics_all_phet-io.html?phetioStandalone)
- [x] [geometric-optics 1.3.8-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/geometric-optics/1.3.8-rc.2/phet-io/wrappers/studio)

**geometric-optics-basics 1.3** (https://github.com/phetsims/joist/issues/970)

- [x] [geometric-optics-basics 1.3.8-rc.2](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.8-rc.2/phet/geometric-optics-basics_all_phet.html)
- [x] [geometric-optics-basics 1.3.8-rc.2 phet-io](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.8-rc.2/phet-io/geometric-optics-basics_all_phet-io.html?phetioStandalone)
- [x] [geometric-optics-basics 1.3.8-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.8-rc.2/phet-io/wrappers/studio)

**graphing-quadratics 1.3** (https://github.com/phetsims/joist/issues/970)

- [x] [graphing-quadratics 1.3.9-rc.2](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.9-rc.2/phet/graphing-quadratics_all_phet.html)
- [x] [graphing-quadratics 1.3.9-rc.2 phet-io](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.9-rc.2/phet-io/graphing-quadratics_all_phet-io.html?phetioStandalone)
- [x] [graphing-quadratics 1.3.9-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.9-rc.2/phet-io/wrappers/studio)

**gravity-and-orbits 1.6** (https://github.com/phetsims/joist/issues/970)

- [x] [gravity-and-orbits 1.6.20-rc.2](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.20-rc.2/phet/gravity-and-orbits_all_phet.html)
- [x] [gravity-and-orbits 1.6.20-rc.2 phet-io](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.20-rc.2/phet-io/gravity-and-orbits_all_phet-io.html?phetioStandalone)
- [x] [gravity-and-orbits 1.6.20-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.20-rc.2/phet-io/wrappers/studio)

**greenhouse-effect 1.2** (https://github.com/phetsims/joist/issues/970)

- [x] [greenhouse-effect 1.2.9-rc.2 phet-io](https://phet-dev.colorado.edu/html/greenhouse-effect/1.2.9-rc.2/phet-io/greenhouse-effect_all_phet-io.html?phetioStandalone)
- [x] [greenhouse-effect 1.2.9-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/greenhouse-effect/1.2.9-rc.2/phet-io/wrappers/studio)

**greenhouse-effect 1.3** (https://github.com/phetsims/joist/issues/970)

- [x] [greenhouse-effect 1.3.1-rc.2](https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.1-rc.2/phet/greenhouse-effect_all_phet.html)
- [x] [greenhouse-effect 1.3.1-rc.2 phet-io](https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.1-rc.2/phet-io/greenhouse-effect_all_phet-io.html?phetioStandalone)
- [x] [greenhouse-effect 1.3.1-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/greenhouse-effect/1.3.1-rc.2/phet-io/wrappers/studio)

**keplers-laws 1.2** (https://github.com/phetsims/joist/issues/970)

- [x] [keplers-laws 1.2.3-rc.2](https://phet-dev.colorado.edu/html/keplers-laws/1.2.3-rc.2/phet/keplers-laws_all_phet.html)
- [x] [keplers-laws 1.2.3-rc.2 phet-io](https://phet-dev.colorado.edu/html/keplers-laws/1.2.3-rc.2/phet-io/keplers-laws_all_phet-io.html?phetioStandalone)
- [x] [keplers-laws 1.2.3-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/keplers-laws/1.2.3-rc.2/phet-io/wrappers/studio)

**molecule-polarity 1.3** (https://github.com/phetsims/joist/issues/970)

- [x] [molecule-polarity 1.3.8-rc.2](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.8-rc.2/phet/molecule-polarity_all_phet.html)
- [x] [molecule-polarity 1.3.8-rc.2 phet-io](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.8-rc.2/phet-io/molecule-polarity_all_phet-io.html?phetioStandalone)
- [x] [molecule-polarity 1.3.8-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.8-rc.2/phet-io/wrappers/studio)

**molecule-shapes 1.6** (https://github.com/phetsims/joist/issues/970)

- [x] [molecule-shapes 1.6.11-rc.2](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.11-rc.2/phet/molecule-shapes_all_phet.html)
- [x] [molecule-shapes 1.6.11-rc.2 phet-io](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.11-rc.2/phet-io/molecule-shapes_all_phet-io.html?phetioStandalone)
- [x] [molecule-shapes 1.6.11-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.11-rc.2/phet-io/wrappers/studio)

**molecule-shapes-basics 1.6** (https://github.com/phetsims/joist/issues/970)

- [x] [molecule-shapes-basics 1.6.11-rc.2](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.11-rc.2/phet/molecule-shapes-basics_all_phet.html)
- [x] [molecule-shapes-basics 1.6.11-rc.2 phet-io](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.11-rc.2/phet-io/molecule-shapes-basics_all_phet-io.html?phetioStandalone)
- [x] [molecule-shapes-basics 1.6.11-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.11-rc.2/phet-io/wrappers/studio)

**my-solar-system 1.3** (https://github.com/phetsims/joist/issues/970)

- [x] [my-solar-system 1.3.5-rc.2](https://phet-dev.colorado.edu/html/my-solar-system/1.3.5-rc.2/phet/my-solar-system_all_phet.html)
- [x] [my-solar-system 1.3.5-rc.2 phet-io](https://phet-dev.colorado.edu/html/my-solar-system/1.3.5-rc.2/phet-io/my-solar-system_all_phet-io.html?phetioStandalone)
- [x] [my-solar-system 1.3.5-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/my-solar-system/1.3.5-rc.2/phet-io/wrappers/studio)

**natural-selection 1.3** (https://github.com/phetsims/joist/issues/970)

- [x] [natural-selection 1.3.18-rc.1 phet-io](https://phet-dev.colorado.edu/html/natural-selection/1.3.18-rc.1/phet-io/natural-selection_all_phet-io.html?phetioStandalone)
- [x] [_natural-selection 1.3.18-rc.1 phet-io Studio_](https://phet-dev.colorado.edu/html/natural-selection/1.3.18-rc.1/phet-io/wrappers/studio)

**natural-selection 1.5** (https://github.com/phetsims/joist/issues/970)

- [x] [natural-selection 1.5.8-rc.2](https://phet-dev.colorado.edu/html/natural-selection/1.5.8-rc.2/phet/natural-selection_all_phet.html)
- [x] [natural-selection 1.5.8-rc.2 phet-io](https://phet-dev.colorado.edu/html/natural-selection/1.5.8-rc.2/phet-io/natural-selection_all_phet-io.html?phetioStandalone)
- [x] [natural-selection 1.5.8-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/natural-selection/1.5.8-rc.2/phet-io/wrappers/studio)

**ph-scale 1.6** (https://github.com/phetsims/joist/issues/970)

- [x] [ph-scale 1.6.14-rc.2](https://phet-dev.colorado.edu/html/ph-scale/1.6.14-rc.2/phet/ph-scale_all_phet.html)
- [x] [ph-scale 1.6.14-rc.2 phet-io](https://phet-dev.colorado.edu/html/ph-scale/1.6.14-rc.2/phet-io/ph-scale_all_phet-io.html?phetioStandalone)
- [x] [ph-scale 1.6.14-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/ph-scale/1.6.14-rc.2/phet-io/wrappers/studio)

**ph-scale-basics 1.6** (https://github.com/phetsims/joist/issues/970)

- [x] [ph-scale-basics 1.6.13-rc.2](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.13-rc.2/phet/ph-scale-basics_all_phet.html)
- [x] [ph-scale-basics 1.6.13-rc.2 phet-io](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.13-rc.2/phet-io/ph-scale-basics_all_phet-io.html?phetioStandalone)
- [x] [ph-scale-basics 1.6.13-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.13-rc.2/phet-io/wrappers/studio)

**projectile-data-lab 1.0** (https://github.com/phetsims/joist/issues/970)

- [x] [projectile-data-lab 1.0.2-rc.2](https://phet-dev.colorado.edu/html/projectile-data-lab/1.0.2-rc.2/phet/projectile-data-lab_all_phet.html)
- [x] [projectile-data-lab 1.0.2-rc.2 phet-io](https://phet-dev.colorado.edu/html/projectile-data-lab/1.0.2-rc.2/phet-io/projectile-data-lab_all_phet-io.html?phetioStandalone)
- [x] [projectile-data-lab 1.0.2-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/projectile-data-lab/1.0.2-rc.2/phet-io/wrappers/studio)

**projectile-sampling-distributions 1.0** (https://github.com/phetsims/joist/issues/970)

- [x] [projectile-sampling-distributions 1.0.2-rc.2](https://phet-dev.colorado.edu/html/projectile-sampling-distributions/1.0.2-rc.2/phet/projectile-sampling-distributions_all_phet.html)
- [x] [projectile-sampling-distributions 1.0.2-rc.2 phet-io](https://phet-dev.colorado.edu/html/projectile-sampling-distributions/1.0.2-rc.2/phet-io/projectile-sampling-distributions_all_phet-io.html?phetioStandalone)
- [x] [projectile-sampling-distributions 1.0.2-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/projectile-sampling-distributions/1.0.2-rc.2/phet-io/wrappers/studio)

**Comment by Nancy-Salpepi** [comment]
I'm seeing 2 issues with the standard wrapper right now:
1. For the standard wrapper, the behavior of ABS is different than Beer's Law when adding ?phetioDebug=true + invalid locale. 
     -- in ABS, I don't get past the splash screen and assertion errors appear in the console, while in Beer's Law I see the assertion error, but the sim will open in the language it was save in. 
<img width="514" alt="Screenshot 2024-07-01 at 4 25 41 PM" src="https://github.com/phetsims/qa/assets/87318828/99bfce87-1f74-4d9b-85b3-5ae008471d44">

Beer's Law:
<img width="514" alt="Screenshot 2024-07-01 at 4 27 04 PM" src="https://github.com/phetsims/qa/assets/87318828/e3634374-7fba-4bec-9994-377a38cc02e3">

2. If I download a wrapper in a locale other than English and then add an invalid locale to it I get different results:
   -- with ?phetioDebug=true it will open in the language I downloaded it in from studio
   -- with ?phetioDebug=false it will open in English

Ex: For Beer's Law: add ?locale=es-pe to the end of the studio url. Then download the wrapper. 
      Add an incorrectly formatted locale to the standard wrapper url --> it opens in English
      Add ?phetioDebug=true + invalid locale.  --> it opens in es-pe.

**Comment by zepumph** [comment]
For (1), it is all about how this chunk may or may not have a try catch around it. Either way it isn't ideal that things are handled on the wrapper side instead of from the sim. This try/catch was from 1/30/24 in https://github.com/phetsims/phet-io-wrappers/issues/637.

**Comment by zepumph** [comment]
For (2). This is because when assertions are disabled, the fallback logic when setting a bogus locale defaults back to English. Without assertions, the full algorithm is able to execute and successfully fallback to the default. When assertions are enabled, the setting of the query parameter locale asserts out before the full algorithm can be executed, and so no new value is set during the "third locale setting phase" in the standard wrapper. Thus, the value from the state (second phase) remains.


For both of these inconsistencies, I have a meeting with @arouinfar to discuss and see what desired behavior is actually best.

**Comment by KatieWoe** [comment]
Similar to https://github.com/phetsims/qa/issues/1103#issuecomment-2200981688, if I put in a valid locale that isn't translated (I used ak in pH Scale Basics) it opens in English rather than the locale I made the file in.

**Comment by KatieWoe** [comment]
For some sims, such as the projectile data sims, instead of 2), the sim doesn't load at all due to the assertion.

**Comment by KatieWoe** [comment]
I think so. Sorry about that.

**Comment by KatieWoe** [comment]
I'm unable to use the locale parameters on the standard wrappers generated by Natural Selection 1.13.18.
![unable](https://github.com/phetsims/qa/assets/41024075/19a8ab77-e1fd-4f9c-9c61-d2039fc9c375)

**Comment by zepumph** [comment]
Ahh shoot. Yes, NS 1.3 only needs a spot check. It doesn't support the locale query parameter. I should have mentioned it, and I'm sorry to waste your time. Thanks for the report.

**Comment by KatieWoe** [comment]
QA is done

**Comment by zepumph** [comment]
Yay! Thanks QA. I'll kick off production versions now.
