### ISSUE TITLE
Test energy-skate-park-basics/1.3.2-phetiorc.1 with floating control panels

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#111]
From https://github.com/phetsims/energy-skate-park-basics/issues/412 we published https://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.3.2-phetiorc.1/wrappers/index/

This will need testing on 3-4 platforms with a sampling of the following query parameters:

[no query parameters]
&controlPanelLocation=floating
&controlPanelLocation=fixed
&controlPanelLocation=floating&webgl=false
&controlPanelLocation=fixed&webgl=false

We should test it in Instance Proxies to make sure it is behaving normally and at least one other phet-io wrapper to make sure it behaves properly there too.  We will not be able to test the layout query parameters in the iframe-based wrappers, because the iframes have fixed sizes.  You can use the "Events: colorized" to test the query parameters and layout.

This is time sensitive and shouldn't take too long, so I'll mark priority as high for now.  Assigning to @ariel-phet to prioritize, schedule, delegate.

**Comment by phet-steele** [comment]
For reference, the last time 1.3 was tested: phetsims/tasks/issues/763.

Issues there should be verified. There was another rc after that linked task, but no new issues were found.

**Comment by phet-steele** [comment]
Initial testing of the query parameters on macOS 10.13.3 Chrome looked kosher.

**Comment by samreid** [comment]
I published 1.3.2 here: https://phet-io.colorado.edu/sims/energy-skate-park-basics/1.3.2-phetio/wrappers/index/

If the build process worked properly, the only changes will be in the new query parameter--so mainly we need to test the query parameter and spot check that nothing went wrong.

**Comment by phet-steele** [comment]
@samreid this has passed testing.

**Comment by samreid** [comment]
Thanks @phet-steele, I notified the client.
