### ISSUE TITLE
Maintenance Test: Build a Molecule 1.0 RTL Chemical Formulas

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/qa#1113]
Issues: https://github.com/phetsims/build-a-molecule/issues/220, https://github.com/phetsims/joist/issues/973, https://github.com/phetsims/chipper/issues/1355

Main link: https://phet-dev.colorado.edu/html/build-a-molecule/1.0.22-rc.1/phet/build-a-molecule_all_phet.html
fa locale link: https://phet-dev.colorado.edu/html/build-a-molecule/1.0.22-rc.1/phet/build-a-molecule_all_phet.html?locale=fa

Can QA do a maintenance spot test (make sure nothing looks broken by the change). Ideally test a few RTL locales that are supported for the sim, and ensure that the chemical formulas look OK.

**Comment by KatieWoe** [comment]
Saw some problems in ar-sa. fa and ar looked ok
![notall](https://github.com/user-attachments/assets/86d3d568-4f94-429b-b6a9-ee5f9f0973c8)

**Comment by jonathanolson** [comment]
@KatieWoe ahh, it looks like... my patch fixed the first screen(?), but there is a problem with the second screen also.

**Comment by jonathanolson** [comment]
Can you test https://phet-dev.colorado.edu/html/build-a-molecule/1.0.22-rc.2/phet/build-a-molecule_all_phet.html now? (new RC).

Additionally, it seems like some of the Arabic translation strings are somewhat unfortunately ordered. If you see O<sub>2</sub>3, it is because the translation is placing the 3 before the formula but in RTL order, so it will be directly to the right. I'm not sure what is ideal here, but the individual formula units should be correct.

**Comment by KatieWoe** [comment]
This is what I see. The mis-ordered coefficients described in https://github.com/phetsims/build-a-molecule/issues/220#issuecomment-771029210 and https://github.com/phetsims/qa/issues/1113#issuecomment-2229617798. I also found this in `?locale=ps`.
![ps](https://github.com/user-attachments/assets/0c50e59d-c6bb-4ea5-8468-1b57b27e9bbb)

**Comment by jonathanolson** [comment]
I'll need to fix the rest of this with a manual translation patch. The above looks good to me, thanks!
