### ISSUE TITLE
Website Activities Pages

### ISSUE THREAD

**Issue by chrisklus** [phetsims/qa#1122]
<h1>Website Activities Pages</h1>

**Mentions**: @kathy-perkins @mattpen @KatieWoe @amanda-phet @oliver-phet @arouinfar @terracoda 

<h3>When Problems are Found</h3>

New Issues should be opened in https://github.com/phetsims/website-meteor/issues/new
Please ping `@mattpenn` or `@chrisklus` on slack if you have questions for the developers.

Note: Please wait to test screen readers and keyboard navigation until @chrisklus gives the all clear. @terracoda and @chrisklus are still iterating on some fixes.

<h3>Pages To Test</h3>

- Landing page: https://ox-dev.colorado.edu/en/activities
- Filter page: https://ox-dev.colorado.edu/en/activities/filter
- Sim Filter page: https://ox-dev.colorado.edu/en/simulations/keplers-laws/activities
- Activity page: https://ox-dev.colorado.edu/en/activities/7474
- Contribution Guidelines page: https://ox-dev.colorado.edu/en/activities/contribution-guidelines
- Contribution Form page: https://ox-dev.colorado.edu/en/activities/contribute
- Edit Activity page: https://ox-dev.colorado.edu/en/activities/edit/7474
- My Activities page (My Bookmarks) https://ox-dev.colorado.edu/en/activities/my-bookmarks
- My Activities page (My Contributions) https://ox-dev.colorado.edu/en/activities/my-contributions
- Review page: https://ox-dev.colorado.edu/en/activities/manage

<h3>Translations</h3>
Please test all of the above pages in these translations:

- English (en)
- Spanish (es)
- One RTL locale (e.g. ar_SA)

<h3>Platforms To Test and Test Matrix</h3>

- [x] Windows 11 + Latest Chrome (Tester = KW) (Time = 6)
- [x] Windows 10 + Latest Firefox (Tester = CH) (Time = 5) (Tester = NS ) (Time = 2.5 )
- [x] macOS + Safari (Tester = NS ) (Time = 6.5)
- [x] iOS + Safari (Tester =JD ) (Time = 6)
- [x] Chrome OS + Chrome (Tester = MM) (Time = 5)
- [x] Android + Chrome (Tester = KW) (Time = 6)
- [x] Windows 10/11 + Latest Chrome + Latest JAWS (Tester = KW) (Time = 6)
- [x] Windows 10 + Latest Firefox + Latest NVDA (Tester = MM) (Time = 5)
- [x] macOS + Safari + VoiceOver (Tester = NS) (Time = 7)
- [x] iOS + Safari + VoiceOver (Tester = KW) (Time = 3)
- [x] Admin User Testing Mac + Safari (Tester = NS ) (Time = included above )
- [x] Non-Admin Reviewer Mac + Safari (Tester = NS ) (Time = included above )

<h3>Test Matrices</h3>

<h3>Focus and Special Instructions</h3>

Note that activity 7474 + Kepler's Law's is used as an example in these page links, but activities have varying features that will alter the content of the pages. It seems best to test all of the features by creating your own activities on ox-dev, so the features can be tested fully from the author side to the user side. This also includes the flow back and forth between an author and an activity reviewer. An example flow may look like:

* An author submits an activity on the contribution form. It has a status of "Submitted".
* A reviewer chooses the activity to review and marks it "Under Review". Under the Review Status History on the activity page (only viewable by the activity author, PhET team members, and Activity Reviewers), the email of the reviewer who marked the activity Under Review should be listed in the history. The same information is available to just PhET team members and Activity Reviewers in the table on the Review page. NOTE: the email of the reviewer is not available to the author. 
* The reviewer finishes reviewing the activity and decides it needs changes before being approved. They mark it "Modifications Needed".
* The author can then go edit their activity and resubmit it for approval.
* The reviewer re-reviews it and checks "Approved", and marks the status "Completed".
* The activity should then appear publicly on the filter page, etc (based on "Approved").

---
<h2>For QA...</h2>

<details>
<summary><b>Accessibility features</b></summary>

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[here](https://github.com/phetsims/qa/blob/main/documentation/accessibility-bugs.md). If you find a screen reader bug,
please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel
controls. Please test magnfication and make sure it is working as intended and well with the use cases of the
simulation. Due to the way screen readers handle user input, magnification is NOT expected to work while using a screen
reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
I find it odd that an activity can be approved, but still under review. Should approving it mark it as such automatically?

**Comment by mattpen** [comment]
> I find it odd that an activity can be approved, but still under review. 

This is a pretty legitimate situation.
1. An activity is approved, but without a gold star.
2. The author makes some updates and submits it for review to try to get a gold star.
3. A reviewer puts it in "Under Review" to evaluate the changes, but does not remove the "Approved" since it was already published.

> Should approving it mark it as such automatically?

I think this would be a good improvement, if you click the "Approved" checkbox that it also changes the status to "Completed". @amanda-phet what do you think?

**Comment by KatieWoe** [comment]
The website in general seems to be rather laggy on the android tablet.

**Comment by KatieWoe** [comment]
Not necessarily a bug, but I wonder if there is a way to alert a screen reader that the review page has loaded. At the moment, if they get to it fast enough the page seems mostly blank and they may not know when its done loading.

**Comment by mattpen** [comment]
> Not necessarily a bug, but I wonder if there is a way to alert a screen reader that the review page has loaded.

@KatieWoe - can you open that as a new issue?

**Comment by KatieWoe** [comment]
All platforms have been tested. We have noticed instances of bugs popping up after we've tested something, so I'm not certain how stable everything is. How do you want to move forward?

**Comment by mattpen** [comment]
> How do you want to move forward?

We have a lot to fix in the queue at the moment. Let's get everything addressed first, I'm thinking we may need to run a second test on a few specific items (I'm thinking the autocomplete comboboxes and the modals), but I'll let you know.

**Comment by mattpen** [comment]
Issues MP & CK are planning to fix in this iteration:

- [ ] https://github.com/phetsims/website-meteor/issues/773
- [ ] https://github.com/phetsims/website-meteor/issues/776
- [ ] https://github.com/phetsims/website-meteor/issues/770
- [ ] https://github.com/phetsims/website-meteor/issues/769

These issues are require decisions about priority, workload, or design in order to fix them in this iteration:

- [ ] https://github.com/phetsims/website-meteor/issues/773
- [ ] https://github.com/phetsims/website-meteor/issues/768

**Comment by mattpen** [comment]
Spot Check is open, closing!
