### ISSUE TITLE
Spot Check: Android App

### ISSUE THREAD

**Issue by mattpen** [phetsims/qa#1126]
# Android App Spot Check

## What to test

- [x] Latest Android App: https://play.google.com/store/apps/details?id=edu.colorado.phet.androidApp

## Things to test

- Tablet with the latest version of Android (14+)
  - [x] General spot test that the sims, app info dialogs, phet info dialog, favorite button, and filters/search are working as expected.
- Tablet with the earliest version of Android that PhET owns 
  - [ ] General spot test that the sims, app info dialogs, phet info dialog, favorite button, and filters/search are working as expected.
- Chromebook 
  - [x] Remove any currently installed apps, install the latest app from the Play Store, then put your device in offline mode. 
 Open the app and verify that projectile-sampling-distributions exists and is on version 1.0.4 or later.
  - [x] Verify that the app is not prompting for an access code.
  - [x] Verify that the app is not incrementing any statistics in Grafana - no new runs should be reported here: https://phet-direct.colorado.edu/analytics/d/admhh4fd1wmpsf/last-100-events?orgId=1 (see @mattpen for credentials if needed)
  - [x] General spot test that the sims, app info dialogs, phet info dialog, favorite button, and filters/search are working as expected.

**Comment by Nancy-Salpepi** [comment]
Unfortunately I can't test with my Chromebook.
1. Signed into Chromebook using phethelp email
2. Went to Google Play store and searched "phet"
3. The app didn't appear when "This Device was selected in the dropdown"
4. The app appeared when I selected "Google Mediatek MT81" but it also says that my Chromebook isn't compatible and I was unable to download.
<img width="569" alt="Screenshot 2024-08-09 at 10 56 51 AM" src="https://github.com/user-attachments/assets/2794dca1-62af-484e-a01f-9c40625e0f09">
<img width="569" alt="Screenshot 2024-08-09 at 10 57 11 AM" src="https://github.com/user-attachments/assets/2cd16904-3e4a-4b16-8f35-3130fb773c42">

**Comment by KatieWoe** [comment]
I was unable to test the oldest Android OS Tablet (8.1). I got a message that the device was not compatible.

**Comment by KatieWoe** [comment]
QA is done. Not sure why I can't install the app on the OS 8.1, when I could last time. Spot check was fairly short.
