### ISSUE TITLE
Spot check: iOS apps

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/qa#1127]
# iOS App Spot Check

## What to test

- [x] Latest iOS "PhET Simulations" App:  version 1.5.0 build (1) - deployed via testflight
- [x] Latest iOS "PhET4Schools Access Program" app: version 1.5.1 build (1) - deployed via testflight

## Things to test

- [x] Remove any currently installed apps, install the latest app from TestFlight, then put your device in offline mode. 
 Open the app and verify that 1-3 phet-brand releases mentioned in https://github.com/phetsims/qa/issues/1114 are present and working as expected.
- [x] Verify that the "PhET Simulations" app is not prompting for an access code
- [x] Verify that the "PhET4Schools Access Program" app requires an access code (use `23AP888Z` to test)
- [x] Verify that the "PhET Simulations" app is not incrementing any statistics in Grafana - no new runs should be reported here: https://phet-direct.colorado.edu/analytics/d/admhh4fd1wmpsf/last-100-events?orgId=1 (see @mattpen for credentials if needed)
- [x] Verify that the "PhET4Schools Access Program" app is properly collecting statistics in Grafana - new runs should be reported here with `23AP888Z`: https://phet-direct.colorado.edu/analytics/d/admhh4fd1wmpsf/last-100-events?orgId=1 (see @mattpen for credentials if needed)
- [x] General spot test that the sims, app info dialogs, phet info dialog, favorite button, and filters/search are working as expected.

## Devices to test

- [x] iPad
- [x] iPhone
- [x] (if possible) iPad <iOS 15.0 (this update now requires iOS 15.0+ so it would be nice to verify that requirement is now working)

**Comment by Nancy-Salpepi** [comment]
@oliver since this is the first time I have ever tested with an iPhone, I'm wondering if the sims were also so stretched when holding the phone vertically?
<img width="205" alt="Screenshot 2024-08-07 at 3 01 54 PM" src="https://github.com/user-attachments/assets/3a628a81-3272-4d99-929f-257a10ed39ce"><img width="216" alt="Screenshot 2024-08-07 at 3 02 12 PM" src="https://github.com/user-attachments/assets/7b8f6e66-0260-40d5-9d59-a2120421487a">

**Comment by oliver-phet** [comment]
> @oliver-phet since this is the first time I have ever tested with an iPhone, I'm wondering if the sims were also so stretched when holding the phone vertically?

Yeah, that is expected behavior and is an accepted consequence of supporting portrait!

**Comment by Nancy-Salpepi** [comment]
Second question @oliver-phet, the new Phet version appeared on my iPad today (yay). I turned off my wifi and opened it, but not all the sims were done downloading (they appeared gray) and clicking on one resulted in this message: 
<img width="494" alt="Screenshot 2024-08-07 at 3 11 56 PM" src="https://github.com/user-attachments/assets/f5031909-1ff1-4f87-88d1-94075b096a3a">
Is that expected?

**Comment by Nancy-Salpepi** [comment]
Last question @oliver-phet (I hope)! Is it normal to see "missing" under Access Code Status? I'm wondering if that was when I was trying to figure out steps for the crash.
<img width="936" alt="Screenshot 2024-08-07 at 3 41 04 PM" src="https://github.com/user-attachments/assets/8f63bdb9-850b-4f49-9316-7791587f4100">

**Comment by oliver-phet** [comment]
@Nancy-Salpepi to your second comment: `missing` is expected if an access code hasn't been entered yet. We shouldn't ever have any `sim-run` with `missing` (just `app-run`). If you were repeatedly opening the access code version without entering a code, I'd expect to see lots of `missing`. So, I don't think this is an issue.

First comment - I'd like a deeper dive into the exact steps here. There certainly shouldn't be any sims awaiting an upload download immediately after opening the app (without internet). I just tested and I didn't see any sims awaiting an update upon first app launch. It _would be_ possible to get a situation like your screenshot if you opened the app with internet and disabled internet mid-update. Can you clarify the steps to reproduce?

**Comment by Nancy-Salpepi** [comment]
Sorry Oliver--I'm not sure what I did the first time! It is working fine on the iPad.

**Comment by KatieWoe** [comment]
I had at least one crash and forced close while opening the app. I told it to alert the developer, but if you want a full issue let me know.

**Comment by KatieWoe** [comment]
I didn't see https://github.com/phetsims/phet-ios-app/issues/637 on the iPad in the office, so it may be more device specific.

**Comment by KatieWoe** [comment]
Something else I noticed that I hadn't thought about before this. The iPad sim does not have heart outlines in the corners of the sims, only when they are favorited are they there. You need to go into the sim, or info dialog, to click the heart. I thought this was intentional, so I didn't mention it before (if I recall correctly this lack was in the last test too). The android app still has those heart outlines, so I'm no longer sure what the intended behavior is. If this needs an issue, let me know.

**Comment by Matthew-Moore240** [comment]
#636

> I didn't see [phetsims/phet-ios-app#637](https://github.com/phetsims/phet-ios-app/issues/637) on the iPad in the office, so it may be more device specific.

@Nancy-Salpepi and I are both on the same version of iOS 17.5.1 if that helps.

**Comment by KatieWoe** [comment]
I had just updated the one in the office to 17.6, but I think the one at home was 17.5.1, so if either of you see it, either before or after an update, recording that in the issue would be a great help.

**Comment by KatieWoe** [comment]
QA is done
