### ISSUE TITLE
Dev Test: PhET Desktop App v1.0.3 (dist 2024-09-18), Windows only

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#1144]
<h1>Desktop Installer Test</h1>

**Mentions**: @kathy-phet, @oliver-phet, and @KatieWoe

<h3>Links</h3>

- [github repository for issues](https://github.com/phetsims/weddell/issues)
- [Windows installer](https://phet-dev.colorado.edu/weddell/dist/2024-09-18/phet-windows-app.exe)

<h3>Focus and Special Instructions</h3>

A fresh build of the desktop installer has been requested in https://github.com/phetsims/weddell/issues/122.  I've fixed a few things and rebuilt the Windows version.  I'm running into some problems building the Mac version, so it seemed reasonable to move forward with testing the Windows one, since that's what most people use.

<h3>Issues to Verify</h3>

- [x] Verify that only locales that have at least one simulation are present in the installed app, see https://github.com/phetsims/weddell/issues/76
- [x] Verify that sims are sorted based on title for non-English locales, see https://github.com/phetsims/weddell/issues/104
- [x] Verify that "Mean: Share and Balance" is present, and any other sims that you're aware of that have been published
for the first time after Nov 2023 are present in the sim.

Testing:

- [ ] Tester = NS , Platform = Win10, Time = 1
- [x] Tester = KW, Platform = Win 11, Time = 2

**Comment by Nancy-Salpepi** [comment]
@jbphet is this correct alphabetical order for French?
![simOrderInFrench](https://github.com/user-attachments/assets/128caf21-166d-4d07-ae27-9918fa1f37fd)

**Comment by KatieWoe** [comment]
QA is done

**Comment by jbphet** [comment]
I've added an additional issue based on @Nancy-Salpepi's question above because I believe it represents a bug.  I'll follow up on the individual issues spawned by this testing, and will close this issue.
