### ISSUE TITLE
RC test: Area Model: Multiplication 1.0.0-rc.3

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#115]
@ariel-phet @amanda-phet @kathy-phet, Area Model: Multiplication 1.0.0-rc.1 is ready for RC testing.

**[Link to sim](https://bayes.colorado.edu/dev/html/area-model-multiplication/1.0.0-rc.1/phet/area-model-multiplication_all_phet.html)**

**[Link to iFrame](https://bayes.colorado.edu/dev/html/area-model-multiplication/1.0.0-rc.1/phet/area-model-multiplication_all_iframe_phet.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1frqdgCyRcqWN1nrBAL_qFt6teQVDteWSCnEyXplks4g/edit?usp=drive_web&ouid=111544391491372222057)** FIRST focus on Wiin 7+ Chrome, macOS 10.11+ Chrome, iPad Air 2, Chromebook, then others when time allows.

**Issues to Verify**
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/area-model-common/issues/119 (check iPad performance)
- [x] https://github.com/phetsims/area-model-common/issues/128 or https://github.com/phetsims/area-model-common/issues/101 (if there are major memory leaks)

**Please also verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test
- [x] Does AR need to be notified for any LOL updates?

If any new issues are found, please note them in https://github.com/phetsims/area-model-common/issues and reference this issue. Please note which screens/sims are affected.
 
**(Other potentially useful items)**  

Sim-specific query parameters useful for testing:  
• `?showAnswers` - Adds a button for game screens that fills in the answers when clicked.
• `?maximumCalculationSize` - Fills in generic screens with values that trigger a certain maximum layout size

Sim-specific terminology: Use the glossary from https://github.com/phetsims/area-model-common/blob/master/doc/implementation-notes.md

@ariel-phet please assign and prioritize

**Comment by jonathanolson** [comment]
Preempted by rc.2: https://bayes.colorado.edu/dev/html/area-model-multiplication/1.0.0-rc.2/phet/area-model-multiplication_en_phet.html

The changes on the branches were:

- Changes fonts on the screen/navbar icons, see https://github.com/phetsims/area-model-common/issues/114
- Fix for where a non-IE11 supported function was used, see https://github.com/phetsims/area-model-common/issues/137
- Fix unreported issue where the touch area for edit buttons/readouts did not switch between vertical/horizontal.
- Fix unreported issue where `Ax+b` dual-spinner entries on variables game challenges would report as wrong incorrectly.

Presumably verify the above fixes (see @phet-steele for details), and if there is any other testing it can be completed on rc2.

**Comment by jonathanolson** [comment]
Preempted by rc.3: https://bayes.colorado.edu/dev/html/area-model-multiplication/1.0.0-rc.3/phet/area-model-multiplication_en_phet.html

The changes on the branches were:

- Yellow "enter" button, see https://github.com/phetsims/area-model-common/issues/142
- Don't use Number.parseInt, see https://github.com/phetsims/area-model-common/issues/141

Presumably verify the above fixes (see @phet-steele for details), and if there is any other testing it can be completed on rc3.

**Comment by phet-steele** [comment]
![greenlight](https://user-images.githubusercontent.com/5863899/39215252-6f61543e-47d4-11e8-9bf6-6775e7a075f1.png)

**Comment by jonathanolson** [comment]
Deployed, closing.
