### ISSUE TITLE
RC-Test Lite: PhET Desktop App v1.0.3 (dist 2024-10-10)

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#1153]
<h1>Desktop App Installer Test</h1>

**Mentions**: @kathy-phet, @oliver-phet, @RVieyra, @solaolateju

<h3>Links</h3>

- [github repository for issues](https://github.com/phetsims/weddell/issues)
- [Installers](https://phet-dev.colorado.edu/weddell/dist/2024-10-10)

<h3>Focus and Special Instructions</h3>

This is the second QA test for this update of the desktop app installer.  The first only included the Windows installer,
this test includes the Mac version as well.  Also, the first test identified several issues which have now been\
addressed.  These are listed below.  This round of testing should verify the basic functionality of the app and make
sure it is ready to distribute to our users.

<h3>Issues to Verify</h3>

These issues should have the "status:ready-for-review" label. Unless an issue says to close after verifying, assign the
issue back to the developer.

- [x] https://github.com/phetsims/weddell/issues/76
- [x] https://github.com/phetsims/weddell/issues/103
- [x] https://github.com/phetsims/weddell/issues/104
- [x] https://github.com/phetsims/weddell/issues/130
- [x] https://github.com/phetsims/weddell/issues/127
- [x] https://github.com/phetsims/weddell/issues/125

Testing:

- [x] Tester = KW, Platform = Win 11, Time = 2 hrs
- [x] Tester = NS, Platform = MacOS 15 , Time = 2 hrs

**Comment by Nancy-Salpepi** [comment]
QA is done.

**Comment by jbphet** [comment]
Thanks QA team - I'll follow up on the individual issues and close this one.  I've logged a separate issue for the observation noted by @solaolateju about the shape of the icon.  Closing.
