### ISSUE TITLE
Maintenance release testing for Safari input

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#117]
Main issue is https://github.com/phetsims/scenery/issues/770 (Working around Safari's iOS 11.3+ passive events changes and lack of touch-action:none).

NOTE: Please go through one of the bottom "exemplar" sims first to see if there are any problems before testing other sims. If there is a problem with that one sim (or really any regression), please interrupt testing and let me know.

The main problem was that, for iPads/iPhones after iOS 11.3+, dragging anywhere in the sim will scroll the sim (like it's a normal web page). Testers should try out a public sim on our website to verify what the buggy behavior looks like. Each sim below should be tested to make sure that it does NOT have that issue (plus ~10-30 seconds of testing to make sure something crazy isn't going wrong).

- [x] https://bayes.colorado.edu/dev/html/acid-base-solutions/1.2.12-rc.3/acid-base-solutions_en.html
- [x] https://bayes.colorado.edu/dev/html/area-builder/1.1.7-rc.1/area-builder_en.html
- [x] https://bayes.colorado.edu/dev/html/arithmetic/1.0.11-rc.1/arithmetic_en.html
- [x] https://bayes.colorado.edu/dev/html/atomic-interactions/1.0.5-rc.1/atomic-interactions_en.html
- [x] https://bayes.colorado.edu/dev/html/balancing-act/1.1.11-rc.1/balancing-act_en.html
- [x] https://bayes.colorado.edu/dev/html/balancing-chemical-equations/1.1.11-rc.1/balancing-chemical-equations_en.html
- [x] https://bayes.colorado.edu/dev/html/balloons-and-static-electricity/1.2.5-rc.1/balloons-and-static-electricity_en.html
- [x] https://bayes.colorado.edu/dev/html/beers-law-lab/1.4.6-rc.1/beers-law-lab_en.html
- [x] https://bayes.colorado.edu/dev/html/bending-light/1.1.8-rc.1/bending-light_en.html
- [x] https://bayes.colorado.edu/dev/html/build-an-atom/1.6.1-rc.1/build-an-atom_en.html
- [x] https://bayes.colorado.edu/dev/html/capacitor-lab-basics/1.5.1-rc.1/capacitor-lab-basics_en.html
- [x] https://bayes.colorado.edu/dev/html/charges-and-fields/1.0.5-rc.1/charges-and-fields_en.html
- [x] https://bayes.colorado.edu/dev/html/circuit-construction-kit-dc/1.0.2-rc.1/circuit-construction-kit-dc_en.html
- [x] https://bayes.colorado.edu/dev/html/circuit-construction-kit-dc-virtual-lab/1.0.2-rc.1/circuit-construction-kit-dc-virtual-lab_en.html
- [x] https://bayes.colorado.edu/dev/html/color-vision/1.1.11-rc.1/color-vision_en.html
- [x] https://bayes.colorado.edu/dev/html/concentration/1.3.8-rc.1/concentration_en.html
- [x] https://bayes.colorado.edu/dev/html/energy-skate-park-basics/1.1.7-rc.1/energy-skate-park-basics_en.html
- [x] https://bayes.colorado.edu/dev/html/expression-exchange/1.1.1-rc.1/expression-exchange_en.html
- [x] https://bayes.colorado.edu/dev/html/faradays-law/1.1.11-rc.1/faradays-law_en.html
- [x] https://bayes.colorado.edu/dev/html/forces-and-motion-basics/2.3.1-rc.1/forces-and-motion-basics_en.html
- [x] https://bayes.colorado.edu/dev/html/fraction-matcher/1.1.9-rc.1/fraction-matcher_en.html
- [x] https://bayes.colorado.edu/dev/html/friction/1.4.1-rc.1/friction_en.html
- [x] https://bayes.colorado.edu/dev/html/function-builder/1.0.11-rc.1/function-builder_en.html
- [x] https://bayes.colorado.edu/dev/html/function-builder-basics/1.0.3-rc.1/function-builder-basics_en.html
- [x] https://bayes.colorado.edu/dev/html/gene-expression-essentials/1.0.2-rc.1/gene-expression-essentials_en.html
- [x] https://bayes.colorado.edu/dev/html/graphing-lines/1.2.2-rc.1/graphing-lines_en.html
- [x] https://bayes.colorado.edu/dev/html/graphing-slope-intercept/1.0.2-rc.1/graphing-slope-intercept_en.html
- [x] https://bayes.colorado.edu/dev/html/gravity-and-orbits/1.1.3-rc.1/gravity-and-orbits_en.html
- [x] https://bayes.colorado.edu/dev/html/gravity-force-lab/2.1.3-rc.1/gravity-force-lab_en.html
- [x] https://bayes.colorado.edu/dev/html/hookes-law/1.0.11-rc.1/hookes-law_en.html
- [x] https://bayes.colorado.edu/dev/html/isotopes-and-atomic-mass/1.0.10-rc.1/isotopes-and-atomic-mass_en.html
- [x] https://bayes.colorado.edu/dev/html/john-travoltage/1.3.2-rc.1/john-travoltage_en.html
- [x] https://bayes.colorado.edu/dev/html/least-squares-regression/1.1.8-rc.1/least-squares-regression_en.html
- [x] https://bayes.colorado.edu/dev/html/make-a-ten/1.0.4-rc.1/make-a-ten_en.html
- [x] https://bayes.colorado.edu/dev/html/molarity/1.3.2-rc.1/molarity_en.html
- [x] https://bayes.colorado.edu/dev/html/molecule-polarity/1.0.3-rc.1/molecule-polarity_en.html
- [x] https://bayes.colorado.edu/dev/html/molecule-shapes/1.1.12-rc.1/molecule-shapes_en.html
- [x] https://bayes.colorado.edu/dev/html/molecule-shapes-basics/1.1.10-rc.1/molecule-shapes-basics_en.html
- [x] https://bayes.colorado.edu/dev/html/molecules-and-light/1.4.1-rc.1/molecules-and-light_en.html
- [x] https://bayes.colorado.edu/dev/html/neuron/1.1.5-rc.1/neuron_en.html
- [x] https://bayes.colorado.edu/dev/html/ohms-law/1.3.9-rc.1/ohms-law_en.html
- [x] https://bayes.colorado.edu/dev/html/pendulum-lab/1.0.3-rc.1/pendulum-lab_en.html
- [x] https://bayes.colorado.edu/dev/html/ph-scale/1.2.12-rc.1/ph-scale_en.html
- [x] https://bayes.colorado.edu/dev/html/ph-scale-basics/1.2.12-rc.1/ph-scale-basics_en.html
- [x] https://bayes.colorado.edu/dev/html/plinko-probability/1.1.3-rc.1/plinko-probability_en.html
- [x] https://bayes.colorado.edu/dev/html/projectile-motion/1.0.3-rc.1/projectile-motion_en.html
- [x] https://bayes.colorado.edu/dev/html/proportion-playground/1.0.2-rc.1/proportion-playground_en.html
- [x] https://bayes.colorado.edu/dev/html/reactants-products-and-leftovers/1.1.11-rc.1/reactants-products-and-leftovers_en.html
- [x] https://bayes.colorado.edu/dev/html/resistance-in-a-wire/1.4.1-rc.1/resistance-in-a-wire_en.html
- [x] https://bayes.colorado.edu/dev/html/rutherford-scattering/1.0.8-rc.1/rutherford-scattering_en.html
- [x] https://bayes.colorado.edu/dev/html/states-of-matter/1.0.3-rc.1/states-of-matter_en.html
- [x] https://bayes.colorado.edu/dev/html/states-of-matter-basics/1.0.3-rc.1/states-of-matter-basics_en.html
- [x] https://bayes.colorado.edu/dev/html/trig-tour/1.0.10-rc.1/trig-tour_en.html
- [x] https://bayes.colorado.edu/dev/html/under-pressure/1.1.6-rc.1/under-pressure_en.html
- [x] https://bayes.colorado.edu/dev/html/unit-rates/1.0.5-rc.1/unit-rates_en.html
- [x] https://bayes.colorado.edu/dev/html/wave-on-a-string/1.1.10-rc.1/wave-on-a-string_en.html

Furthermore, the 6 sims here are exemplars of the 6 different patches that were used (because of incompatible changes made to Scenery between sim publications). For these, I would like testing with mouse/touch/stylus input done on a variety of platforms (including iPhone if possible), to see if this introduces input bugs. This includes dragging things while the pointer goes out of the window, how it behaves in iframes, how it works with gestures, or anything else that looks/feels buggy. For non-Safari based things, somewhat brief testing should be used (a good chance nothing changes), but for Safari-based things (desktop and mobile Safari) it changes a lot of how input may work, and I want to make sure it doesn't break things.

- [x] https://bayes.colorado.edu/dev/html/acid-base-solutions/1.2.12-rc.3/acid-base-solutions_en.html
- [x] https://bayes.colorado.edu/dev/html/ph-scale/1.2.12-rc.1/ph-scale_en.html
- [x] https://bayes.colorado.edu/dev/html/gravity-and-orbits/1.1.3-rc.1/gravity-and-orbits_en.html
- [x] https://bayes.colorado.edu/dev/html/balloons-and-static-electricity/1.2.5-rc.1/balloons-and-static-electricity_en.html
- [x] https://bayes.colorado.edu/dev/html/projectile-motion/1.0.3-rc.1/projectile-motion_en.html
- [x] https://bayes.colorado.edu/dev/html/circuit-construction-kit-dc/1.0.2-rc.1/circuit-construction-kit-dc_en.html

Assigning to @ariel-phet to prioritize.

**Comment by ariel-phet** [comment]
Since this bug renders sims pretty unusable in our app, seems like next priority after Area Model 1.0

**Comment by phet-steele** [comment]
@jonathanolson @ariel-phet we have too many sims.

I tested on iOS 11.3, iOS 11.2.5, iOS 9.3.5, Win 10 all four browsers, macOS 10.13.14 Safari and Chrome, and our Android tablet. No regressions form this patch and the sims work correctly on iOS 11.3.

**Comment by phet-steele** [comment]
Oh and @lmulhall-phet did an iPad Pro iOS 11.3 with a stylus and didn't report any problems.

**Comment by jonathanolson** [comment]
Thanks!
