### ISSUE TITLE
Dev Test: Friction 1.5.0-dev.6

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#127]
Due to some work to address https://github.com/phetsims/friction/issues/71 and https://github.com/phetsims/friction/issues/70, as well as miscellaneous cleanup to the code, the code for the Friction sim has undergone some significant changes.  It would be good to test the sim and make sure no problems were introduced.

Please test the sim for correct behavior.  Note that it will look a bit different from the currently published version - this is intentional and is not a bug.  The testing should verify that the sim behaves correctly and performs adequately on all supported platforms and that no issues were introduced that would negatively impact learning.

**Comment by lmulhall-phet** [comment]
@ariel-phet, I'm labeling this top since there's nothing else to test at the moment.

**Comment by lmulhall-phet** [comment]
I'm guessing @jbphet wants https://bayes.colorado.edu/dev/html/friction/1.5.0-dev.6/phet/friction_all_phet.html tested. @JRomero0613, we're going to test on the following:
- [ ] macOS: Safari, FF, Chrome
- [ ] Windows 10: Edge, IE, FF, Chrome
- [ ] iOS: Safari
- [ ] Android: Chrome
- [ ] Chrome OS: Chrome

**Comment by lmulhall-phet** [comment]
QA is done.

**Comment by jbphet** [comment]
@lmulhall-phet - can you provide a summary conclusion?  Do we have confidence that my recent changes didn't introduce any new issues that would require further effort other than the "about" dialog issue above?

**Comment by lmulhall-phet** [comment]
@jbphet, aside from the About dialogue issue, I didn't see anything that would warrant further effort. Closing this issue.
