### ISSUE TITLE
Maintenance Release: PhET-iO sims for scenery#770

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#128]
@jonathanolson @samreid @kathy-phet, we are ready for the RC testing of phet-io sims that have the maintenance patch applied for phetsims/scenery#770. 

See https://github.com/phetsims/phet-io/issues/1329#issuecomment-395073989 for steps to complete this issue, all rc versions and links to PhET-iO wrappers are there. 

We are keeping links in that issue because it is in a private repo, and we speak of partners and phet-io files that should remain private. If you have any questions, please speak to @samreid or @zepumph.

@ariel-phet please assign and prioritize.

**Comment by ariel-phet** [comment]
@lmulhall-phet current top testing priority. Definitely ask the @zepumph @jonathanolson or @samreid if questions arise

**Comment by lmulhall-phet** [comment]
@zepumph, QA has looked at everything in https://github.com/phetsims/phet-io/issues/1329#issuecomment-395490539. The issues we've found are referenced in this issue. Passing this over to you. If you need any more testing done, let me know.

**Comment by jonathanolson** [comment]
I'll wait on phet-io people to tell me when to do the production deployments.

**Comment by zepumph** [comment]
It looks like https://github.com/phetsims/function-builder/issues/119 is the only issue that needs investigating for this maintenance release.

**Comment by samreid** [comment]
https://github.com/phetsims/function-builder/issues/119 is also assigned to @jonathanolson, so I'll assign this issue to him as well.

**Comment by KatieWoe** [comment]
The labeling system in the QA repository is to remove the priority tags when QA testing is finished.  Removing priority:2-high.  Thank you.

**Comment by samreid** [comment]
Thanks @KatieWoe!

**Comment by jonathanolson** [comment]
Thanks for the testing!

Additional discussion will be in https://github.com/phetsims/phet-io/issues/1329 since testing is done.
