### ISSUE TITLE
Dev Test: Equality Explorer 1.0.0-dev.125

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#131]
This issue is for the first round of dev testing on the Equality Explorer family of sims.  The majority of testing during implementation has been on Chrome, Safari and Mobile Safari.   Please do a thorough shakedown on a few platforms, including iPad and Edge.   There is no need for a test matrix, unless you'd like to create one.

[Equality Explorer 1.0.0-dev.125](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.125/phet/equality-explorer_en_phet.html)

Resources:

- Start by reading [model.md](https://github.com/phetsims/equality-explorer/blob/master/doc/model.md) and the _Terminology_ section of [implementation-notes.md](https://github.com/phetsims/equality-explorer/blob/master/doc/implementation-notes.md).
- The lock feature is complicated enough to require its own testing document, [lock-scenarios.md](https://github.com/phetsims/equality-explorer/blob/master/doc/lock-scenarios.md).
- Sim-specific query parameters are documented in [EqualityExplorerQueryParameter.js](https://github.com/phetsims/equality-explorer/blob/master/js/common/EqualityExplorerQueryParameters.js). 

Please mention this issue in any GitHub issues that you create.

@ariel-phet @amanda-phet FYI.

Liam's Edits: Changed title, assigning @ariel-phet for prioritization.

**Comment by pixelzoom** [comment]
Please create any GitHub issues in the equality-explorer repository, regardless of which sim you find them in.

**Comment by ariel-phet** [comment]
@lmulhall-phet marking as medium for the moment, as there are a few things that would be good to be finished up first. However, this must be complete by 7/5 so priority will get bumped up at some point.  However, this sim should be tested first as Basics and Two Variables are really variants overall.

**Comment by ariel-phet** [comment]
Bumping to high priority

**Comment by ariel-phet** [comment]
Looks like this can be top priority again

**Comment by lmulhall-phet** [comment]
QA is done.

**Comment by pixelzoom** [comment]
Thank you QA team.  I'll self-assign until related issue are closed.
