### ISSUE TITLE
Dev Test: Equality Explorer: Basics 1.0.0-dev.12

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/QA#132]
This issue is for the first round of dev testing on the Equality Explorer family of sims.  The majority of testing during implementation has been on Chrome, Safari and Mobile Safari.   Please do a thorough shakedown on a few platforms, including iPad and Edge.   There is no need for a test matrix, unless you'd like to create one.

[Equality Explorer: Basics 1.0.0-dev.12](https://phet-dev.colorado.edu/html/equality-explorer-basics/1.0.0-dev.12/phet/equality-explorer-basics_en_phet.html) 

Resources:

- Start by reading [model.md](https://github.com/phetsims/equality-explorer/blob/master/doc/model.md) and the _Terminology_ section of [implementation-notes.md](https://github.com/phetsims/equality-explorer/blob/master/doc/implementation-notes.md).
- The lock feature is complicated enough to require its own testing document, [lock-scenarios.md](https://github.com/phetsims/equality-explorer/blob/master/doc/lock-scenarios.md).
- Sim-specific query parameters are documented in [EqualityExplorerQueryParameter.js](https://github.com/phetsims/equality-explorer/blob/master/js/common/EqualityExplorerQueryParameters.js). 

For any issues that you create, please mention #131 and create them in the equality-explorer repository, regardless of which sim you find them in. 95% of the code lives in equality-explorer.

@ariel-phet @amanda-phet FYI.

Liam's Edits: Changed title, assigning @ariel-phet for prioritization.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/QA/issues/131#issuecomment-398157620:
> Please create any GitHub issues in the equality-explorer repository, regardless of which sim you find them in. 95% of the code lives in equality-explorer.

**Comment by ariel-phet** [comment]
@lmulhall-phet marking as medium for the moment, as there are a few things that would be good to be finished up first. However, this must be complete by 7/5 so priority will get bumped up at some point.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/QA/issues/131#issuecomment-402783023, @lmulhall-phet said:
> QA is done.

Is QA also done for this sim?

**Comment by lmulhall-phet** [comment]
> Is QA also done for this sim?

Yes.

**Comment by pixelzoom** [comment]
All related issues are linked to https://github.com/phetsims/QA/issues/131#issuecomment-402783023, so closing this issue.
