### ISSUE TITLE
Dev test: Energy Skate Park Basics 1.4.0-dev.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#134]
@samreid @zepumph @ariel-phet @kathy-phet, Energy Skate Park Basics 1.4.0-dev.1 is ready for dev testing. The sim has gone through significant changes since the last publication so it would be good to do a thorough dev test before republishing for LoL and PhET-iO. In particular, this sim hasn't been tested since the transition from PropertySet to Property, and that was complicated enough to deserve its own issue (https://github.com/phetsims/energy-skate-park-basics/issues/371). But there have been other miscelaneous changes for bugs and memory leaks.

Both PhET and PhET-iO brands will need to be tested, but this issue is just for the PhET brand. It was recommended that I wait to create a task for testing PhET-iO until learning more in https://github.com/phetsims/QA/issues/19.

[Link to sim](https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.4.0-dev.1/phet/energy-skate-park-basics_en_phet.html)

@ariel-phet please assign and prioritize

**Comment by ariel-phet** [comment]
Marking as low priority for the moment since EqEx and BASE need to get done first

**Comment by lmulhall-phet** [comment]
@ariel-phet, moving this to top since there are no other testing tasks in the repo other than Java EF&C.

**Comment by lmulhall-phet** [comment]
@ariel-phet, moving down to medium B/C EqEx.

**Comment by KatieWoe** [comment]
Issue is also present on iOS 9.3.5 on the iPad Air 2.

**Comment by lmulhall-phet** [comment]
Moving back to top for the moment, @ariel-phet.

**Comment by ariel-phet** [comment]
Moving to high priority since #153 takes precedence

**Comment by jessegreenberg** [comment]
Great, thanks @KatieWoe. A number of issues came out of this test, so I think we should fix or resolve those issues and then proceed with a PhET-io dev test at thata time. Closing this issue, thanks for the good work team.
