### ISSUE TITLE
RC Test: Balloons and Static Electricity 1.4.0-rc.2

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#136]
@terracoda @emily-phet @lmulhall-phet Ballons and Static Electricity 1.4.0-rc.2 is ready for rc testing. The last rc only found one issue that required a minor fix so this is only a spot check.

[Link to Sim](https://bayes.colorado.edu/dev/html/balloons-and-static-electricity/1.4.0-rc.2/phet/balloons-and-static-electricity_all_phet_debug.html)

[Link to iframe](https://bayes.colorado.edu/dev/html/balloons-and-static-electricity/1.4.0-rc.2/phet/balloons-and-static-electricity_all_iframe_phet.html)

[Link to a11y-view](https://bayes.colorado.edu/dev/html/balloons-and-static-electricity/1.4.0-rc.2/phet/balloons-and-static-electricity_a11y_view.html)

Please make sure that the following issue has been fixed:
- [x] https://github.com/phetsims/balloons-and-static-electricity/issues/427

This fix changed how the charges were drawn, so please make sure that the charges still look good on a few platforms, particularly on startup.

Adding "top" priority label since that was the priority of the last RC, but @ariel-phet @lmulhall-phet please change if that is not correct.

**Comment by lmulhall-phet** [comment]
@jessegreenberg, after refreshing 20+ times, I wasn't able to reproduce.

Looks good on:
- [ ] macOS + FF
- [ ] macOS + Chrome
- [ ] macOS + Safari
- [ ] Win10 + FF
- [ ] Win10 + Chrome
- [ ] Win10 + Edge
- [ ] iOS + Safari
- [ ] Chrome OS + Chrome
- [ ] Android + Chrome

**Comment by jessegreenberg** [comment]
Awesome, thanks @lmulhall-phet. Is there anything else or is this issue complete?

**Comment by lmulhall-phet** [comment]
@jessegreenberg, as long as you think the fixes you made in https://github.com/phetsims/balloons-and-static-electricity/commit/75ca2b772300fdf28129a2933dc8a3a7406be561 aren't likely to affect anything other than the way the charges are drawn, then I think this issue is complete.

**Comment by jessegreenberg** [comment]
Awesome, thanks. It was a 5 line change private to MinusChargesCanvasNode, I am confident that it didn't affect anything other than the charges in the wall. Your tests in https://github.com/phetsims/QA/issues/136#issuecomment-400722324 seem very sufficient. I think we are ready to deploy this sim.

**Comment by jessegreenberg** [comment]
Sim was redeployed: https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_en.html

Closing this issue.

**Comment by terracoda** [comment]
@jessegreenberg, you rock!
