### ISSUE TITLE
Energy Forms and Changes, Java version

### ISSUE THREAD

**Issue by phet-steele** [phetsims/QA#141]
Sim found here: https://phet.colorado.edu/en/simulation/energy-forms-and-changes

About 2 years ago I was asked to be on the lookout for prime-time Java testing for this sim. Since porting to HTML5 is well underway, I think that time is now. We want to test the Java version thoroughly to identify any bugs that are currently present and may be unintentionally ported. 

Please report any issues in https://github.com/phetsims/energy-forms-and-changes/issues

***Please mark any of the issues discovered with the label  "type:legacy-bug"***

Note this testing was requested 4 years ago at phetsims/tasks/issues/73, but I'm not sure how well that went or if much testing was performed. I copy/pasted the "progress" of that issue here (which is why "Mac" is already checked).

Please the two main operating systems on their latest version:
- [ ] Mac
- [ ] Windows

@ariel-phet feel free to un-check Mac, and please prioritize.

**Comment by ariel-phet** [comment]
Marking "low" at the moment, as this will be best as a background task.

**Comment by ariel-phet** [comment]
I am fine with this issue now being closed. We will be thoroughly testing the HTML5 version, but good to know any obvious bugs that may have come with ported code are addressed.
