### ISSUE TITLE
RC Test: Equality Explorer: Basics 1.0.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#145]
Equality Explorer: Basics 1.0.0-rc.1 is ready for RC testing.   According to the schedule, RC1 testing needs to be completed by Wednesday 7/18, so labeling this issue as "priority:1-top".

**[Link to sim](https://phet-dev.colorado.edu/html/equality-explorer-basics/1.0.0-rc.1/phet/equality-explorer-basics_en_phet.html)**

**[Link to iFrame](https://phet-dev.colorado.edu/html/equality-explorer-basics/1.0.0-rc.1/phet/equality-explorer-basics_en_iframe_phet.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1OA3O2j8Ruek4ELKLpYrMpKI6XVXB9qMDjO_Gt2YZFnU/edit#gid=2)**

**Issues to verify**

None.

**Please also verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

NOTE: It is not necessary to verify the lock feature test scenarios found in lock-scenarios.md, since this sim does not include the lock feature.

If any new issues are found, please note them in https://github.com/phetsims/equality-explorer/issues and reference this issue.  (You read that right. Note them in equality-explorer, not equality-explorer-basics.)

**Useful info**  

Sim-specific query parameters useful for testing can be found in [EqualityExplorerQueryParameters](https://github.com/phetsims/equality-explorer/blob/master/js/common/EqualityExplorerQueryParameters.js).  

Common-code query parameters that are useful include `speed` (to slow down animation speed to facilitate multitouch testing). See documentation in [initialize-globals.js](https://github.com/phetsims/chipper/blob/master/js/initialize-globals.js).

Before testing, please read the _Terminology_ section of [implementation-notes.md](https://github.com/phetsims/equality-explorer/blob/master/doc/implementation-notes.md).  Please try to use this terminology in GitHub issues.

**Comment by lmulhall-phet** [comment]
We don't have multiple top priorities.

**Comment by KatieWoe** [comment]
QA is done with these test.

**Comment by pixelzoom** [comment]
Excellent, thank you QA team!

**Comment by pixelzoom** [comment]
Note that there is no need for 1.0.0-rc.2 for this sim.  The 2 issues to be verified (phetsims/equality-explorer#138 and phetsims/equality-explorer#144) are for features that are not present in _Equality Explorer: Basics_.

**Comment by pixelzoom** [comment]
Following this RC test, I needed to make equality-explorer-basics dependent on equality-explorer 1.0 HEAD, so that we're using the same code in all 3 sims, the credits are the same, etc.  Here are the steps that I used to update the dependencies:

```
% cd equality-explorer-basics
% grunt checkout-target --target=1.0
% cd equality-explorer
% git checkout 1.0
% cd equality-explorer-basics
% grunt
% cp build/phet/dependencies.json dependencies.json
% git add dependencies.json
% git commit -m “use equality-explorer 1.0 HEAD”
% git push
% grunt checkout-master
```
