### ISSUE TITLE
RC Test: Expression Exchange 1.1.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#15]
Expression Exchange 1.1.0-rc.2 is ready for spot checking (most of the testing was completed on rc.1, see https://github.com/phetsims/QA/issues/9).

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.1.0-rc.2/expression-exchange_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.1.0-rc.2/expression-exchange_en-iframe.html)**

**Issues to Verify**
Two issues were addressed in this release.  Please test the these and check them off after addressing. If they are resolved, close them.  If not, they should be updated.
- [x] https://github.com/phetsims/expression-exchange/issues/68##
- [x] https://github.com/phetsims/expression-exchange/issues/121##

**Comment by phet-steele** [comment]
![greenlight](https://user-images.githubusercontent.com/5863899/27751137-1f4c01f0-5d98-11e7-96a2-e297c72e8093.png)
