### ISSUE TITLE
Maintenance release testing for vibe/joist/chipper patches

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#154]
Please mainly see https://github.com/phetsims/special-ops/issues/112 (tracked there since some of the phet-io information is private).

This is the first (automated) maintenance release with full chipper 2.0 and phet-io support, so definitely let me know about how we should handle QA/releases in the future (@KatieWoe or @ariel-phet if you have any suggestions, I want to try to minimize the time we need in the future for these). The list of links in the issue is auto-generated now (based on what issues were patched for what sim branches, etc.), so I can definitely change things up if desired.

Assigning to @ariel-phet since I'm not sure what priority this should be at.

**Comment by ariel-phet** [comment]
@KatieWoe this seems like a good issue to chip away at in parallel with some other testing (or if someone just needs something a bit more mindless to do for awhile). There is plenty to test but each test is short, so putting at medium priority for the moment. 

I would suggest wrapping @lmulhall-phet into this testing a bit so you two can discuss if there might be ways to streamline in the future. And of course I am happy to discuss as well if you are unclear about the concepts behind maintenance releases.

**Comment by jonathanolson** [comment]
Looks like the "not working" cases are expected, and not triggered by the maintenance release. Thanks, closing.
