### ISSUE TITLE
Testing Tambo Load Times

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/QA#155]
See phetsims/tambo/issues/18.

We need to test how Tambo changes load time on all of our devices.

**[Testing Matrix](https://docs.google.com/spreadsheets/d/1UJJBD0PAYkta0b1EaWktToXwPZm3e3sXWN1ktcUEmfE/edit?usp=sharing)**

There are two sims to look at, each with two snapshots. The first snapshot is before the merge with the sound control branch, the second snapshot is after the merge with the sound control branch.

We need to test for each sim on each device/browser:
- [x] Time to load before before merge
- [x] Time to load after merge
- [x] Time to load after merge with the query parameter `?tambo`

We should do three trials for each test, and then find the average. Timing should last from the moment you hit enter to the moment the sim can be interacted with.

Pre-merge snapshots:
+ https://phet-dev.colorado.edu/html/charges-and-fields/1.1.0-dev.5/phet/charges-and-fields_en_phet.html
+ https://phet-dev.colorado.edu/html/color-vision/1.3.0-dev.1/phet/color-vision_en_phet.html

Post-merge snapshots:
+ https://phet-dev.colorado.edu/html/charges-and-fields/1.1.0-dev.6/phet/charges-and-fields_en_phet.html
+ https://phet-dev.colorado.edu/html/color-vision/1.3.0-dev.2/phet/color-vision_en_phet.html

@ariel-phet can you please assign a priority for this task?

**Comment by jbphet** [comment]
The list above looks good, but I want to make sure that you also build in finding the difference so that we can clearly see how much longer it takes to load the sims with the sound features in place.  This could probably be automated - just a formula in the spreadsheet - but would make it much easier for us to interpret the results.

**Comment by KatieWoe** [comment]
It should be in the testing matrix.

**Comment by ariel-phet** [comment]
Looks like this testing is well underway, but good to finish up early next week (before next dev meeting on Thursday)

**Comment by KatieWoe** [comment]
QA is finished.  Results are in the testing matrix

**Comment by jbphet** [comment]
Thanks.  We reviewed this in last week's meeting and concluded that the numbers look reasonable and there is no need to invest effort in reducing the load times.  Closing.
