### ISSUE TITLE
Firefox testing for Pointer Events change

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#156]
For https://github.com/phetsims/scenery/issues/837 (https://github.com/phetsims/equality-explorer/issues/141), I'd like to have the workaround change tested on all Firefox platforms to make sure it didn't introduce any additional input issues.

Can https://phet-dev.colorado.edu/html/area-model-algebra/1.1.0-dev.1/phet/area-model-algebra_en_phet.html (and the iframe test at https://phet-dev.colorado.edu/html/area-model-algebra/1.1.0-dev.1/phet/area-model-algebra_all_iframe_phet.html) be tested for all Firefox platforms to try to ensure no other mouse/touch/etc. input issues arose with the change?

- [x] Mac OS X 10.11.6
- [x] Mac OS 10.12.6+
- [x] Win 7
- [x] Win 8.1
- [x] Win 10

**Comment by KatieWoe** [comment]
Actually, on second thought, a bunch of these that I just listed we don't have touch screens for.  We don't support firefox on ipads, I don't believe, but I can check them as well.

**Comment by KatieWoe** [comment]
It looks like it might just be windows 10 with firefox and a touchscreen.  In which case, done.

**Comment by jonathanolson** [comment]
I'd like mouse testing also, so mouse+Firefox on those other platforms would be good to test (the change will affect it).

**Comment by KatieWoe** [comment]
Ok.  Sounds good.

**Comment by jonathanolson** [comment]
Thanks!
