### ISSUE TITLE
Area Model dev testing for 1.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#157]
@amanda-phet and @ariel-phet, Area Model is ready for its 1.1 dev testing (since the Firefox issue is patched).

I'd like the following 4 sims to have normal dev testing done:

- https://phet-dev.colorado.edu/html/area-model-algebra/1.1.0-dev.1/phet/area-model-algebra_en_phet.html
- https://phet-dev.colorado.edu/html/area-model-decimals/1.1.0-dev.1/phet/area-model-decimals_en_phet.html
- https://phet-dev.colorado.edu/html/area-model-introduction/1.1.0-dev.1/phet/area-model-introduction_en_phet.html
- https://phet-dev.colorado.edu/html/area-model-multiplication/1.1.0-dev.1/phet/area-model-multiplication_en_phet.html

Please report any issues in the area-model-common repo

In particular it would be good to test these sims on the following platforms

- [x] Mac Safari
- [x] Win Chrome
- [x] iPad 2

There are some known performance issues on iPad2, but as long as they are not egregious in "normal use" (so slowly changing the grid to deliberate places, not rapidly adjusting for no reason) it should be fine.

**Comment by ariel-phet** [comment]
Marking as current top testing priority

**Comment by KatieWoe** [comment]
QA is finished testing.

**Comment by jonathanolson** [comment]
Thanks, I'll investigate the issues!
