### ISSUE TITLE
Performance Check: Energy Skate Park: Basics

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#158]
This issue is from https://github.com/phetsims/energy-skate-park-basics/issues/431#issuecomment-408950041, but enough needs to be done that thought a QA issue was appropriate.

**Link to version to test**: https://bayes.colorado.edu/dev/html/energy-skate-park-basics/1.4.0-trackCanvasInChrome.1/phet/energy-skate-park-basics_en_phet.html

There was an issue where on certain Chromium platforms, tracks would get "filled in" between control points. See the issue for more info if you are interested. But this seems to be fixed by rendering the track with canvas. However, this could have significant memory/performance implications. @samreid said
> The main platforms to test the canvas solution will be iPad2 and our lowest supported retina iPad, because allocating an extra fullscreen raster will take a lot of memory.

@KatieWoe can you please test this version on 
- [ ] iPad2 + Chrome
- [ ] retina iPad + Chrome
- [ ] Windows 10 Chrome
- [ ] MacOS Chrome
- [ ] Any other Chromium based platforms that we have easy access to.

Please be on the lookout for a degradation in performance, or perhaps a sim crash or failure to load. An iPad might say "Something went wrong, the page was reloaded." (or something like that).

@ariel-phet can you please prioritize? This is part of #134, and deploying Energy Skate Park: Basics with LoL support and redeploying for PhET-iO.

**Comment by KatieWoe** [comment]
Windows 10 Chrome.  Performance seems mostly ok on this device so far.  I have noticed an increase in lag when dragging objects, particularly when dragging the tracks on the playground screen.

**Comment by KatieWoe** [comment]
iPad 2 + Chrome
Worked well for a short time.  However, the sim began to slow, show lag, and then crashed as described in the issue.  The problem seems to come from changing screens.  The first time a screen is changed it seems to handle it, but it crashes after a second attempt to change screens.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, if that is already the case I think there is no need to keep testing for the moment.

**Comment by jessegreenberg** [comment]
I am going to close this issue and we will keep thinking and maybe make another one here soon.

**Comment by KatieWoe** [comment]
Just tested on the same device on safari and the same thing happened, so I don't think that issue is Chrome exclusive.  Hope that helps.

**Comment by jessegreenberg** [comment]
Wait, it crashed in Safari? The change we made should only impact Chrome. @KatieWoe can you please see if https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.4.0-dev.1/phet/energy-skate-park-basics_en_phet.html also crashes?

**Comment by KatieWoe** [comment]
It does, though a bit less.  Liam says that the iPad2 tends to crash quite a bit, so it may be an issue with the device.

**Comment by KatieWoe** [comment]
Looking through it on both links a second time it is quite bad on iPad2, more so than it usually is.  Sorry we didn't catch it earlier in dev testing.

**Comment by jessegreenberg** [comment]
Interesting. @KatieWoe can you please see if this is happening with the published version on the PhET website?

**Comment by KatieWoe** [comment]
It seems much better on the website.  I talked to Liam and he said that it was better during the previous round of dev testing as well.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe. In that case, we should look through other changes and see if any would have caused this. Otherwise it might be common code changes. I will create an issue in energy-skate-park-basics to look into this and continue there, this issue can be closed.
