### ISSUE TITLE
Test changes for admin profile edit page

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#159]
There were recently some changes to the edit profile page requested by the website admins, see phetsims/website#721.  We should test registration, user profile edits, and admin profile edits to verify that the changes did not affect the user's registration experience.  We specifically need to verify that when users edit their own account, that they are not able to navigate through the process by clicking on the progress indicators and that all fields  are still properly validated.

The dev version is currently published on ox-dev, available via links in the top right and the admin > users page.

We do not need to test or report problems with the layout, especially in the header and navigation.  This will be handled separately.

**Comment by KatieWoe** [comment]
Assigning Ariel for priority.

**Comment by JRomero0613** [comment]
I have done some testing and when inputting an empty value for the primary email address the alert that pops up is: "This email address has already been registered. Please check your inbox for a confirmation email.". Obviously there is no email in the box so I'm not sure why it says the email is already in use, maybe we should make a different alert message when no string has been input.

**Comment by lmulhall-phet** [comment]
On macOS+Chrome+FF+Safari, the ability to click directly to the "Admin Only" tab seems to be working.

**Comment by KatieWoe** [comment]
When registering it asks to input your email address a second time.  However, when autofill comes up for this section it tries to fill in a physical address.  The blurred out section is my parents address.
![image](https://user-images.githubusercontent.com/41024075/43614615-60422d98-9671-11e8-9e90-4f8debc37594.jpg)

**Comment by KatieWoe** [comment]
QA is finished

**Comment by mattpen** [comment]
> The pickers that are used to select a number of years of teaching experience are very small, difficult to make out, difficult to use, and look like they are overlapping.

@KatieWoe - These elements are created by the browser and are dependent on your local settings.  When I test this in Win 10/Firefox, the pickers look much larger than in your screenshot and roughly the same size as in chrome.  There is no way to style these specifically, I would need to create a custom component from scratch or just hide them altogether.

**Comment by mattpen** [comment]
> Attempted to copy paste Hamlet into name input. Error occurred, but when going back to reedit the profile, Hamlet is still there.

I'm unable to recreate this bug, can you post a screenshot?

**Comment by KatieWoe** [comment]
![screen1](https://user-images.githubusercontent.com/41024075/43653183-8da3de42-9704-11e8-8f91-cfdb40148a4d.PNG)
![screen2](https://user-images.githubusercontent.com/41024075/43653192-9197d102-9704-11e8-88e7-462e7f2cd53d.PNG)

This time around it signed me out and when I signed in and edited it, the name was what it was before hand.  I think I copied a bit more this time, so that might be a difference.

**Comment by KatieWoe** [comment]
Here we go.
![screen3](https://user-images.githubusercontent.com/41024075/43653329-f3195c66-9704-11e8-8e36-a7f548ce6b49.PNG)
Only seems to work if you copy a certain amount.  This was just scene 1 from Hamlet.

**Comment by mattpen** [comment]
> Attempted to copy paste Hamlet into name input.

I thought you meant just "Hamlet", not the entire play.  We have a 255 character limit on strings in the DB, I'll add a check for this to validation.

**Comment by mattpen** [comment]
> You can enter invalid Twitter handles.

We aren't actually using these for anything, and there is no plan to add auto-validation at this time.

**Comment by mattpen** [comment]
> Can enter invalid zip codes, notably negative zip codes. (EDIT: Seems like the range is [-9999, 99999].)

You can actually enter any 5 digit string for the zip code.  I don't think we're planning to do any postal validation on these, but I'll change the acceptable range to only numeric strings 00000-99999.

**Comment by mattpen** [comment]
> It would be a nice to be able to go to the previous tab when editing profile!

This was the original behavior but we switched to a through process in order to encourage people to fill in all of the missing data.

**Comment by mattpen** [comment]
> It seems like my first name can't be 600 characters long. Disappointing!

No, the limit is 255.

**Comment by mattpen** [comment]
> When registering it asks to input your email address a second time. However, when autofill comes up for this section it tries to fill in a physical address. The blurred out section is my parents' address.

I added an autofill attribute which should fix this in most cases.

**Comment by mattpen** [comment]
> The fields don't handle > 15 copy-pastes of Hamlet very well.

I added string length checking to all fields, nothing can be more than 255 characters now.

**Comment by mattpen** [comment]
> I've noticed that hitting return when entering something into a field when editing profile will make you go to the next tab. Is this intentional?

This is intentional but maybe not ideal.  We discussed it during the initial deploy and decided it was acceptable.

**Comment by mattpen** [comment]
> maybe we should make a different alert message when no string has been input [in the primary email].

Will do.
