### ISSUE TITLE
Dev test: Resistance In A Wire 1.3.0-dev.1

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#16]
This test is before moving to rcs for phet and phet-io brands. The sim was instrumented for PhET-iO a few months ago, and went through a good amount of refactoring during that. The only visually noticeable changes are the slider thumbs. Internal implementations have changes substantially since its 1.2 release to the phet website, including using HSlider now. @phet-steele please let me know if you want more in a dev test issue. @ariel-phet please assign and prioritize.

 http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-dev.1/resistance-in-a-wire_en.html

Please test on 

- [x] Windows Chrome
- [x] iPad 2 
- [x] Mac Safari

**Comment by ariel-phet** [comment]
Should be a pretty quick dev test

**Comment by phet-steele** [comment]
@zepumph this is done.

**Comment by phet-steele** [comment]
> @phet-steele please let me know if you want more in a dev test issue.

What you wrote was great! Brief explanation + a few platforms + link is great.

**Comment by zepumph** [comment]
Thanks @phet-steele, I'll take care of those issues.
