### ISSUE TITLE
Verify that new sonification lib (tambo) generates sound on supported platforms

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#160]
The tambo repo contains some new code for generating and controlling sound.  There hasn't been much testing yet to verify that it works on our supported platforms, and I think we're at a good point to do such testing.  Please set up a test matrix and verify that sound generation works in the tambo demo on all platforms with the exception of IE11 - it will definitely not work there.  More specifically, please run the following tests:

On all supported platforms except IE11, verify that:
+ The sim loads without errors on the console (there may be sound-related warnings in Chrome, that's okay)
+ The popping sound occurs when balls are added to the container on the 1st screen
+ Bouncing sounds are played when the balls bounce on the wall in the first screen
+ The sliders on the second screen both produce sounds when moved
+ A sound loop can be turned on/of with the A/B switch on the 2nd screen
+ The thunder sound is produced on the 2nd screen
+ The basic sound can be played using the button on the 3rd screen
+ No sound is initially played by the "enhanced sound" button on the 3rd screen, but it works after enhanced sounds are turned on through the PhET menu
+ Verify that none of these generate sound if it is turned off using the icon on the nav bar

On IE11:
+ verify that the sim loads and runs and does NOT generate sound, and that a warning about this is output on the console

Version to test: https://phet-dev.colorado.edu/html/tambo/1.0.0-dev.4/phet/tambo_en_phet.html

Please see me if you have any questions.

Link to Matrix: https://docs.google.com/spreadsheets/d/1OcdAM0BCecBIoLu_XEL02Ay5f2xxXHLUDqnTp-YBu-8/edit?usp=sharing

**Comment by ariel-phet** [comment]
@KatieWoe current top testing priority

**Comment by KatieWoe** [comment]
I noticed that the loop seems to have a gap when played in Windows 10 Firefox.

**Comment by lmulhall-phet** [comment]
Weird scraping/static noise during/after sounds play on our iPad 2 with iOS 9.3.5 (Tycho). Occurs with speakers and headphones.

Sound isn't working on our iPad Air 2 with iOS 11.4.1 (Pauling). See https://github.com/phetsims/vibe/issues/35. However, with https://phet-dev.colorado.edu/html/tambo/1.0.0-dev.4/phet/tambo_en_phet.html, sound is working fine with headphones.

**Comment by lmulhall-phet** [comment]
Got this while testing iPad Air 2 with iOS 11.4.1:

```
[Error] InvalidStateError: The object is in an invalid state.
	stop (tambo_en_phet.html:1029:1093714)
	stop (tambo_en_phet.html:1029:1093714)
	(anonymous function) (tambo_en_phet.html:1029:1168065)
	r (tambo_en_phet.html:1029:438287)
	step (tambo_en_phet.html:1029:438204)
	stepSimulation (tambo_en_phet.html:1029:984606)
	stepOneFrame (tambo_en_phet.html:1029:983856)
	runAnimationLoop (tambo_en_phet.html:1029:983714)
	runAnimationLoop
```

**Comment by lmulhall-phet** [comment]
Similar error on macOS 10.11.6 + Safari:

```
[Error] InvalidStateError (DOM Exception 11): The object is in an invalid state.
	stop (tambo_en_phet.html:1029:1093713)
	stop (tambo_en_phet.html:1029:1093713)
	(anonymous function) (tambo_en_phet.html:1029:1168064)
	r (tambo_en_phet.html:1029:438286)
	step (tambo_en_phet.html:1029:438203)
	stepSimulation (tambo_en_phet.html:1029:984605)
	stepOneFrame (tambo_en_phet.html:1029:983855)
	runAnimationLoop (tambo_en_phet.html:1029:983713)
	runAnimationLoop
```

**Comment by KatieWoe** [comment]
QA is done.  Issues are linked, or posted in comments if short.

**Comment by jbphet** [comment]
Thanks @KatieWoe and team.  I'll go through this and close once I'm sure we have issues logged for everything.

**Comment by jbphet** [comment]
Issues logged, closing.
