### ISSUE TITLE
Molarity 1.4.0-rc.1 RC test

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#161]
@ariel-phet, Molarity 1.4.0-rc.1 is ready for RC testing.

**[Link to sim _en.html](https://phet-dev.colorado.edu/html/molarity/1.4.0-rc.1/phet/molarity_en_phet.html)**
**[Link to sim _all.html](https://phet-dev.colorado.edu/html/molarity/1.4.0-rc.1/phet/molarity_all_phet.html)**
**[Link to sim iframe](https://phet-dev.colorado.edu/html/molarity/1.4.0-rc.1/phet/molarity_all_iframe_phet.html)**
**[Link to sim XHTML](https://phet-dev.colorado.edu/html/molarity/1.4.0-rc.1/phet/xhtml/molarity_all_phet.html)**
**[Link to phet-io standalone](https://phet-dev.colorado.edu/html/molarity/1.4.0-rc.1/phet-io/molarity_all_phet-io.html?phetioStandalone)**
**[Link to phet-io studio](https://phet-dev.colorado.edu/html/molarity/1.4.0-rc.1/phet-io/wrappers/studio/studio.html)**

**[Normal RC Test Matrix](https://docs.google.com/spreadsheets/d/1tb4vFUYbqCPPIDPOiV6BkamOZiZyWujxaF4al_2q4k4/edit#gid=1884702031)**

**[phet io RC Test Matrix](https://docs.google.com/spreadsheets/d/1OG5et_umDGDNI4v9K1acaAs4fR_8c_3rMM6qn8D8hLY/edit?usp=sharing)**

**Issues to Verify**
(*all should be marked "status:fixed-pending-testing"*)  
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- Mainly test the XHTML like the iframe, to ensure that it still works appropriately

**Please also verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test
- [x] Does AR need to be notified for any LOL updates?

If any new issues are found, please note them in https://github.com/phetsims/molarity/issues and reference this issue.  

@ariel-phet please assign and prioritize

**Comment by KatieWoe** [comment]
@samreid and @zepumph would you like us to test all of the phet-io wrappers for this test, or just add these two wrappers to the regular rc?

**Comment by samreid** [comment]
PhET-iO testing for a sim should include testing all of the wrappers linked from the landing page:
https://phet-dev.colorado.edu/html/molarity/1.4.0-rc.1/phet-io/

@jonathanolson is there a template you used to create this issue that I should update?

**Comment by samreid** [comment]
Also, @KatieWoe a reminder to reassign issues when asking a question, to make sure the intended recipients don't miss it.

**Comment by jonathanolson** [comment]
I modified the main RC template in the QA repo.

**Comment by KatieWoe** [comment]
@samreid so just to be clear, this a phet-io test, and not a normal rc, or is it both?

**Comment by jonathanolson** [comment]
It is testing both the phet and phet-io brands, so it is essentially both.

**Comment by samreid** [comment]
We are striving to get to a point where RC's normally test PhET brand and PhET-iO brand at the same time.  I don't recall 100% of the conversation around Molarity but it seems we want to publish it for PhET and PhET-iO.

**Comment by KatieWoe** [comment]
QA is done.  Note: testing for phet-io was done on Mac OS 10.12 as is indicated on the testing matrix, not on the newest OS 10.13.  Let me know if testing should be changed to test 10.13 instead.

**Comment by pixelzoom** [comment]
Unassigning myself. (No issues found, so nothing for me to fix.)

**Comment by jonathanolson** [comment]
Closing. @samreid and @zepumph will let @pixelzoom know when to publish the next RC, and whether to grab new SHAs for the release branch. Thanks for the testing!

**Comment by pixelzoom** [comment]
Summary:
No sim-specific issues were found.  PhET-iO issues need to be addressed before proceeding with next RC.  Next RC test will be done in https://github.com/phetsims/QA/issues/166.
