### ISSUE TITLE
Getting Kelly Started

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/QA#163]
@ariel-phet @oliver-phet

- [x] GitHub Email, GitHub Account, Join Organization
- [x] Add Kelly to the QA Team
- [x] Add Kelly to the Google Group
- [x] Google Calendar
- [x] Phases of Development
- [x] GitHub Workflow
- [x] How to Test & Tricks-of-the-Trade (simulation locations, query parameters, development tools, etc.)
- [x] Practice Creating an Issue
- [x] Introduce Test Server
- [x] Introduce Website
- [x] Website Account
- [ ] Picture for Website and Bio
- [x] Slack
- [x] Key
- [x] phet@lists.colorado.edu
- [x] QA Book
- [x] Finish All Administrative Paperwork
- [x] W4 and Direct Deposit Up-to-Date on myCUinfo
- [ ] Picture for GitHub

**Comment by lmulhall-phet** [comment]
Should we close this @KatieWoe?

**Comment by KatieWoe** [comment]
The pictures are still unchecked.  But I think we can.
