### ISSUE TITLE
Test particle behavior after changes to thermostats

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#164]
In the course of addressing https://github.com/phetsims/states-of-matter-basics/issues/15 and some of the concerns described in https://github.com/phetsims/states-of-matter/issues/214 I ended up making some changes to both the isokinetic thermostat and the Andersen thermostat code.  It would be good to verify that the behavior of the particles in the container didn't change radically as a result.  The intent of the changes was to minimize the amount of drift to the right or left when the particles are in solid form with no heat or cooling applied and when the particles start in solid form and are heated.  Please test the behavior of the particles in the container on the dev version linked below and log any behavior that is significantly different from the current published version (v1.0.3) and log any significant and potentially problematic differences.

https://phet-dev.colorado.edu/html/states-of-matter/1.1.0-dev.3/phet/states-of-matter_en_phet.html

**Comment by KatieWoe** [comment]
Assigning @ariel-phet for priority.

**Comment by ariel-phet** [comment]
@KatieWoe hoping to get SOM re-released soon, so marking high priority

**Comment by KatieWoe** [comment]
QA is finished

**Comment by jbphet** [comment]
Thanks for the testing, I'll start addressing the issues that resulted.  Closing.
