### ISSUE TITLE
Spot Check: Drag interruption when sim is made inactive

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#17]
From https://github.com/phetsims/build-an-atom/issues/162, a fix was applied in https://github.com/phetsims/scenery/issues/619 which fixes buggy behavior when dragging is interrupted.

@phet-steele could you please verify that the issue with interrupting dragging with the "Pause" feature is fixed in https://github.com/phetsims/build-an-atom/issues/162?

In case they are needed, here are the steps to test with the harness:

- Launch:
http://harness.legendsoflearning.com

- Put the link to the sim in the entry for "Game URL".  Please include the ?legendsOfLearning query parameter.

Please let me know if you have any questions.

**Comment by jessegreenberg** [comment]
@ariel-phet could you please prioritize the spot check?

**Comment by ariel-phet** [comment]
@phet-steele lets make this top priority to move the legends of learning forward

**Comment by phet-steele** [comment]
Already been handled in https://github.com/phetsims/scenery/issues/619#issuecomment-313760911
