### ISSUE TITLE
Check a11y functions in the iOS app TableView

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#171]
The new table view for browsing some in the iOS app (iPhones only) needs to be checked to make sure it is accessible. The primary things to check will be compatibility with voice over and focus highlighting.

**Comment by KatieWoe** [comment]
Linking to phetsims/QA/issues/168

**Comment by KatieWoe** [comment]
@mattpen should this be closed with https://github.com/phetsims/QA/issues/168?

**Comment by mattpen** [comment]
@KatieWoe - it can be closed, but please keep these concerns in mind when testing future builds.  Do we need a checklist/matrix?

**Comment by KatieWoe** [comment]
Mentioning or linking to this might be useful, probably all that's needed is to add a line saying "Please test the mobile app with voice over as well."  More useful might be a list with any issues you want us to confirm.  I have them assigned to me, but the rest of the QA team may find it useful to have a list.
@mattpen
