### ISSUE TITLE
Comb through the website to find typos, inaccuracies, etc.

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/QA#175]
For example...

![screen shot 2018-08-21 at 7 06 43 pm](https://user-images.githubusercontent.com/31285590/44437028-63dd3c00-a575-11e8-88a0-3261d9e68b23.png)

...we don't specify which Windows OS(s) we support for HTML5 sims.

**Comment by lmulhall-phet** [comment]
Should we change OS X to macOS?

> macOS is the second major series of Macintosh operating systems. The first is colloquially called the "classic" Mac OS, which was introduced in 1984, and the final release of which was Mac OS 9 in 1999. The first desktop version, Mac OS X 10.0, was released in March 2001, with its first update, 10.1, arriving later that year. After this, Apple began naming its releases after big cats, which lasted until OS X 10.8 Mountain Lion. Since OS X 10.9 Mavericks, releases have been named after landmarks in California.[10] Apple shortened the name to "OS X" in 2012 and then changed it to "macOS" in 2016, adopting the nomenclature that they were using for their other operating systems, iOS, watchOS, and tvOS. The latest version is macOS High Sierra, which was publicly released in September 2017.

src: https://en.wikipedia.org/wiki/MacOS

**Comment by KatieWoe** [comment]
The research section has a section called Publications on PhET Simulations by other Researchers.  This section has many publications with no links.  Is this intentional (ie. there is no link to add)?
![link](https://user-images.githubusercontent.com/41024075/44470841-ee5e8380-a5e7-11e8-8145-dd9a89a477cf.PNG)

**Comment by KatieWoe** [comment]
Two more broken links on that page.
![twomore](https://user-images.githubusercontent.com/41024075/44477582-4f8e5300-a5f8-11e8-950f-06e59c677cfd.PNG)

**Comment by JRomero0613** [comment]
In the help center under getting started the text alignment under the "How do I embed PhET simulations?" section is inconsistent with the rest of the text sections. The second paragraph does not have a space between itself and the proceeding paragraph. The screenshot I have attached shows this as well as another section with the standard formatting. 
![helpcenterpic](https://user-images.githubusercontent.com/30352536/44535872-59778b00-a6b8-11e8-84a9-d6462883b390.JPG)

**Comment by JRomero0613** [comment]
In the offline access center under the Chromebook section there is a piece of text that says "Find it on the Play Store here." where I am assuming the "here" should link to the Play Store android app download. If this is intended then disregard this but otherwise a link needs to be created.

**Comment by KatieWoe** [comment]
Is sonification still called sonification or is it called sound?
![sound](https://user-images.githubusercontent.com/41024075/44542867-3f937380-a6cb-11e8-8297-6ba65030081d.PNG)

**Comment by JRomero0613** [comment]
On the offline access screen of the website there are a couple of issues. The first involves not having a link to google chrome, where the other browsers have links. This can be seen in the attached screenshot. The second involves the Internet Explorer link seen in the screenshot below directing to a page that can not be found. I'm testing on Mac so this might be the cause of the issue but I think that the link should work regardless.
![screen shot 2018-09-20 at 10 58 20 am](https://user-images.githubusercontent.com/30352536/45834381-2da1f200-bcc4-11e8-8b55-c92ad8fff005.png)
The last issue is that when the drop down menu for "Desktop/Laptop Computer" or "Chromebook" is selected the bottom of the web page extends much further down than the regular bottom banner. To replicate this open either of these menus and scroll down to the bottom of the page. Once you scroll past the regular bottom banner the page continues with nothing but white space on it.

**Comment by lmulhall-phet** [comment]
Regarding https://github.com/phetsims/QA/issues/175#issuecomment-415510683, I asked @jbphet and he said "sound".

**Comment by lmulhall-phet** [comment]
Made issue in website repo, so closing this issue.
