### ISSUE TITLE
RC Test: Rutherford Scattering 1.1.0-rc.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#181]
@ariel-phet @KatieWoe, rutherford-scattering/1.1.0-rc.1 is ready for RC testing. This release is only phet brand with no a11y. The release is motivated by getting sims released off of master with chipper 2.0, as well as other common code improvements like a new general projector mode query parameter. Document issues in https://github.com/phetsims/rutherford-scattering/issues and link to this issue. 

Assigning @ariel-phet for prioritization.

Note: I hacked a lot out of the RC template, @KatieWoe if I went overboard please let me know.

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/rutherford-scattering/1.1.0-rc.1/phet/rutherford-scattering_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/rutherford-scattering/1.1.0-rc.1/phet/rutherford-scattering_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/rutherford-scattering/1.1.0-rc.1/phet/xhtml/rutherford-scattering_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/114xkSYOrKXVR6g5ThJ-tZVQLEMEjubgnpWypa2tvqEg/edit#gid=289364597)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>
</details>

**Comment by ariel-phet** [comment]
@KatieWoe this is "back burner" work for when QA is slow. No rush, but the more sims on chipper 2.0, the better.

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Thanks very much @KatieWoe and everyone, we are ready for the next RC.

**Comment by jessegreenberg** [comment]
Not quite ready, I am not sure if https://github.com/phetsims/joist/issues/515 should block publication of this sim. But this issue can remain closed.
