### ISSUE TITLE
Test Windows installer with activities

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/QA#182]
Waiting to hear back from user on their operating system version (so that we can match).

User is receiving errors (related to teaching activity files) when attempting to install.
![1](https://user-images.githubusercontent.com/5090275/45170727-cc572a80-b1bd-11e8-9872-b1e9900e7f0b.png)
![2](https://user-images.githubusercontent.com/5090275/45170728-cc572a80-b1bd-11e8-9092-731391339d4a.png)
![3](https://user-images.githubusercontent.com/5090275/45170729-cc572a80-b1bd-11e8-860b-ed3160d6c6dd.png)
![4](https://user-images.githubusercontent.com/5090275/45170730-cc572a80-b1bd-11e8-92cd-1ba25ce4b751.png)
![5](https://user-images.githubusercontent.com/5090275/45170731-ccefc100-b1bd-11e8-832c-dfb559546592.png)
![6](https://user-images.githubusercontent.com/5090275/45170732-ccefc100-b1bd-11e8-9b40-bc14b82c39e1.png)
![7](https://user-images.githubusercontent.com/5090275/45170733-ccefc100-b1bd-11e8-9815-7db79f32558d.png)

**Comment by phet-steele** [comment]
@oliver-phet those error messages would seem to suggest they copied the installer onto a computer using a USB drive, then tried to access the copied files after the USB drive was disconnected...or something.

**Comment by phet-steele** [comment]
@KatieWoe @oliver-phet I don't know if QA ever tests installing from a CD (I know I never did), which it looks like this user is doing?

**Comment by oliver-phet** [comment]
It could have been a DVD or USB drive.

**Comment by KatieWoe** [comment]
@phet-steele I've never done it.

**Comment by KatieWoe** [comment]
Win 10 and Win 7 off internet seems fine.  I did run into some brief trouble by getting a network error when trying to download the installer on Win 7 chrome.  Using Firefox worked fine, and I believe this an issue with chrome or its settings.

**Comment by KatieWoe** [comment]
@oliver-phet Just tested the installer on Win 8.1 and I didn't see any problems there either.  Let me know if you get more information about how their set up.

**Comment by oliver-phet** [comment]
> operating system is windows 7
> Destination folder is in C:
> Downloaded setup was at E:

**Comment by KatieWoe** [comment]
@oliver-phet Just downloaded the installer on to a usb and used it to install on Win 7.  The drive was E: and it installed into C: with the same file path.  Didn't encounter any problems.  Sorry that's not very much use.

**Comment by oliver-phet** [comment]
Ok, it is sounding like the users .exe file is corrupted. I'm going to have them re-download the installer. Closing for now.
