### ISSUE TITLE
Check master versions of all sims

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#184]
We have run into a couple of cases recently where the master version of a sim, i.e. the version shown in `package.json`, is behind what it should be due to some pre-chipper-2.0 phet-io releases.  Issue https://github.com/phetsims/john-travoltage/issues/297 is an example of this, and @pixelzoom also reported that it was a problem for concentration.  It would be good to go through all sims and make sure that the versions shown in package.json is correct.

@KatieWoe - feel free to stop by and discuss with me if you need more info.

**Comment by jbphet** [comment]
@phet-steele - I just briefed @KatieWoe on it, and I think it would be good for her, since it will help to familiarize her with our version numbering scheme.

**Comment by phet-steele** [comment]
Alright, I found and made phetsims/make-a-ten/issues/286 before reading that @KatieWoe is taking over. I'll stop there (I was NOT going alphabetical).

**Comment by KatieWoe** [comment]
Making a checklist of versions to check:
@phet-steele no problem.  Just made a checklist of versions to check.  Would you mind marking any that you have confirmed?

- [ ] acid-base-solutions
- [ ] area-builder
- [ ] area-model-algebra
- [ ] area-model-counting
- [ ] area-model-decimals
- [ ] area-model-introduction
- [ ] area-model-multiplication
- [ ] arithmetic
- [ ] atomic-interactions
- [ ] baa-iframe-demo
- [ ] balancing-act
- [ ] balancing-chemical-equations
- [ ] balloons-and-static-electricity
- [ ] beaker
- [ ] beers-law-lab
- [ ] bending-light
- [ ] blackbody-spectrum
- [ ] blast
- [ ] build-a-fraction
- [ ] build-a-molecule
- [ ] build-an-atom
- [ ] bumper 
- [ ] button-test
- [ ] buttons
- [ ] capacitor-lab-basics
- [ ] capacitor-lab
- [ ] chains
- [ ] charges-and-fields
- [ ] chipper
- [ ] circuit-construction-kit-basics
- [ ] circuit-construction-kit-black-box-study
- [ ] circuit-construction-kit-black-box
- [ ] circuit-construction-kit-dc-virtual-lab
- [ ] circuit-construction-kit-dc
- [ ] color-vision
- [ ] concentration
- [ ] coulombs-law
- [ ] curve-fitting
- [ ] deploy-dev-tests
- [ ] diagram-demo
- [ ] energy-forms-and-changes
- [ ] energy-skate-park-basics
- [ ] energy-skate-park
- [ ] equality-explorer-basics
- [ ] equality-explorer-two-variables
- [ ] equality-explorer
- [ ] estimation
- [ ] example-sim
- [ ] expression-exchange
- [ ] faraday
- [ ] faradays-law
- [ ] fluid-pressure-and-flow
- [ ] forces-and-motion-basics
- [ ] fraction-comparison
- [ ] fraction-matcher
- [ ] fractions-equality
- [ ] fractions-intro
- [ ] fractions-mixed-numbers
- [ ] friction
- [ ] function-basics
- [ ] function-builder-basics
- [ ] function-builder
- [ ] gene-expression-essentials
- [ ] graphing-lines
- [ ] graphing-quadratics
- [ ] graphing-slope-intercept
- [ ] gravity-and-orbits
- [ ] gravity-force-lab-basics
- [ ] gravity-force-lab
- [ ] hookes-law
- [ ] interaction-dashboard
- [ ] isotopes-and-atomic-mass
- [ ] jb-tests
- [ ] jg-tests
- [ ] john-travoltage
- [ ] least-squares-regression
- [ ] lightbulb
- [ ] lingo
- [ ] make-a-ten
- [ ] making-tens
- [ ] masses-and-springs
- [ ] models-of-the-hydrogen-atom
- [ ] molarity
- [ ] molecule-polarity
- [ ] molecule-shapes-basics
- [ ] molecule-shapes
- [ ] molecules-and-light
- [ ] neuron
- [ ] ohms-law
- [ ] optics-lab
- [ ] pendulum-lab
- [ ] ph-scale-basics
- [ ] ph-scale
- [ ] phet-io-wrapper-sonification
- [ ] phet-io-wrapper-visualizing-engagement
- [ ] phet-io
- [ ] phet-metacog
- [ ] plinko-probability 
- [ ] projectile-motion
- [ ] proportion-playground
- [ ] protein-synthesis
- [ ] reactants-products-and-leftovers
- [ ] resistance-in-a-wire
- [ ] rutherford-scattering
- [ ] samreid
- [ ] scenery-phet 
- [ ] seasons
- [ ] smorgasbord
- [ ] states-of-matter-basics
- [ ] states-of-matter
- [ ] sugar-and-salt-solutions
- [ ] sun
- [ ] tambo
- [ ] test-dir
- [ ] together
- [ ] trig-tour
- [ ] under-pressure
- [ ] unit-rates
- [ ] vegas
- [ ] wave-interference
- [ ] wave-on-a-string
- [ ] wilder

**Comment by phet-steele** [comment]
@KatieWoe a handful of these are not sims, are you meant to check them?

**Comment by KatieWoe** [comment]
I asked @jbphet and he said that it could be useful, so I should while I'm at it.

**Comment by KatieWoe** [comment]
Update, several of those commits were made in error, due to a misunderstanding on my part.  They should be fixed now.  Sorry about that.

**Comment by KatieWoe** [comment]
Finished.  Most fixes were done in commits.  One was made into an issue.  Unchecked italics items were ones that I was unsure how to handle, mostly non-sims.

**Comment by jbphet** [comment]
Thanks for your efforts on this @KatieWoe, and I think that should do it for now.  I looked through the unaddressed items in the list, and I think we can just deal with them on a case-by-case basis if something needs to be republished from that repo. Closing.
