### ISSUE TITLE
Maintenance Release: Forces And Motion Basics 2.1.12-rc.1 phet-io

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#189]
@samreid @kathy-phet @DianaTavares @jessegreenberg(responsible dev), FAMB is ready for a maintenance release.

This version is to support a study that begins this Friday, Sept 21st.

This republication only has one change. It removed the "close warning" that occurs when recording to metacog. To test these changes, QA will want to do all steps under the "**Third**" heading in [the previous QA issues](https://github.com/phetsims/QA/issues/187) but instead use this updated recording link.  There is one main exception now, as there will not be a prompt before leaving the page, instead you will just go back/exit immediately. This is expected and desired.  

Here is the link to use to record with:

https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.1.12-rc.1/wrappers/iframe/iframe.html?url=../login/login.html?screens=2.3&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=7&promptText=This%20is%20a%20test,%20have%20fun%20qa&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=forces-and-motion-basics-qatest2&phet-io.emitInputEvents=true&phet-io.emitStates=true&phet-io.emitStatesInterval=60&launchLocalVersion&metacog

Here are the variables I would like to test on:

* throttled recording speed (maybe 3? normal, slow, very very slow)
* browsers
* devices (no need for tablets)

Please make a few recordings to each, request them, and then use [this playback wrapper](https://phet-dev.colorado.edu/mjkauzmann/FAMB-2.1-phetio-playback/metacog/playback/) (same as the previous one) to ensure that the recordings are entact.

A few notes:

* @KatieWoe you can use the same application_id as last time, though let me know if you need it again.
* I set a new recording id (widget_id) so you shouldn't get any sessions you recorded in the other link. 

We are mainly interested to note that (a) the recordings are working well, and (b) on slower connections they are not being clipped off too early, i.e. there are too many events that haven't been sent when the browser tab is closed.

@ariel-phet please assign and prioritize.

**Comment by zepumph** [comment]
Here is the link to this version's wrapper index: https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.1.12-rc.1/wrappers/index/

**Comment by KatieWoe** [comment]
- [ ] Win 10 Chrome Fast
- [ ] Win 10 Chrome Medium
- [ ] Win 10 Chrome Slow
- [ ] Win 10 Firefox Fast
- [ ] Win 10 Firefox Medium
- [ ] Win 10 Firefox Slow
- [ ] Win 10 Edge Fast
- [ ] Win 10 Edge Medium
- [ ] Win 10 Edge Slow

- [ ] Mac OS 10.13 Chrome Fast
- [ ] Mac OS 10.13 Chrome Medium
- [ ] Mac OS 10.13 Chrome Slow
- [ ] Mac OS 10.13 Firefox Fast
- [ ] Mac OS 10.13 Firefox Medium
- [ ] Mac OS 10.13 Firefox Slow
- [ ] Mac OS 10.13 Safari Fast
- [ ] Mac OS 10.13 Safari Medium
- [ ] Mac OS 10.13 Safari Slow

- [ ] Chrome OS Fast
- [ ] Chrome OS Medium
- [ ] Chrome OS Slow

@zepumph any other combinations you want  us to test?

**Comment by zepumph** [comment]
Yes that looks great. For each one, it would be best if right before stopping the recording, you recorded something very noticeable (like three checkboxes in a row). That way we know if definitively if events got clipped off (one of the checkbox clicks wasn't there).

**Comment by ariel-phet** [comment]
@KatieWoe current top priotiy, especially given the time sensitive nature

**Comment by KatieWoe** [comment]
QA is done.  Everything checked looks fine.
Amount of Time **Lost** for unchecked boxes (out of 4 minutes):
Medium Win 10 chrome = 3:45
Slow Win 10 chrome = 2:45
Medium Win 10 firefox = 2:55
Slow Win 10 firefox = 3:50
Medium Mac chrome = 1:40
Slow Mac chrome = 3:00
Medium Mac firefox = 3:00
Slow Mac firefox = 3:50
Medium Mac safari = 3:10
Slow Mac safari = 3:40
Fast Chrome OS = only 2 or 3 seconds
Medium Chrome OS = 1:45
Slow Chrome OS = 2:10

**Note:**  The dev tools or apps used to throttle varied for each platform, so differences may be due to amount individual dev tools throttled, rather than the platform itself.

**Comment by zepumph** [comment]
@KatieWoe and I looked into what "slow/medium/fast" meant on a few platforms, and here are some speed tests we (mainly she) did.

Chrome for me:
```
throttle ping down up
normal: 67 80.71 9.16
fast 3g: 68 1.50 .54
slow 3g: 12 .39 (crashed speedtest)
```

For @KatieWoe:
```
chrome normal: ping 4ms Down 135 Mbps Up 162 Mbps
chrome medium: ping 2 ms Down 1.49 Mbps Up .54 Mbps
chrome slow: ping 2 ms Down .39 Mbps Up .28 Mbps

safari:
Medium Downlink: Bandwidth 780 kbps Delay 100 ms
Medium Uplink: Bandwidth 330 kpbs Delay 100 ms
Slow Downlink: Bandwidth 240 kbps Delay 400 ms
Slow Uplink: Bandwidth 200 kbps Delay 400 ms

Firefox normal Ping 3 ms D 154.31 Mbps U 152.2 Mbps
Firefox medium Ping 3 D 136.22 U .25
Firefox slow Speedtest gave me a latency test error

**Comment by zepumph** [comment]
We have decided that there is too much data loss for us to publish this. Thanks QA for all your hard work! We will test another workaround (hiding the sim frame on closewarning) in #190. Closing.
