### ISSUE TITLE
Maintenance Release: Forces And Motion Basics 2.1.12-rc.2 phet-io

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#190]
@samreid @kathy-phet @DianaTavares @jessegreenberg(responsible dev), FAMB is ready for a maintenance release.

This version is to support a study that begins this Friday, Sept 21st.
previous qa in https://github.com/phetsims/QA/issues/189

In this version, we turned the closewarning on again. We also added logic to "hide" the sim after the closewarning is triggered, so you should see a blank screen once trying to exit/back out of the page and electing to "cancel" (staying on the page to let the data save).

So this version is almost identical to what was tested in #187. As a result, we just need to make sure that the hiding logic is working as expected, and that the recording works well. 

@KatieWoe please record to metacog with a few devices and a few browsers. It would be good to throttle some recordings, but I don't think anything as thorough as https://github.com/phetsims/QA/issues/189#issuecomment-422570056 is needed.

Recording link with fresh widget_id:
https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.1.12-rc.2/wrappers/iframe/iframe.html?url=../login/login.html?sim=forces-and-motion-basics&screens=2.3&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=7&promptText=Enter%20your%20Student%20ID&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=forces-and-motion-basics-qatest3&phet-io.emitInputEvents=true&phet-io.emitStates=true&phet-io.emitStatesInterval=60&metacog&launchLocalVersion

Wrapper index to sanity check:
https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.1.12-rc.2/wrappers/index/

**Comment by KatieWoe** [comment]
- [ ] Win 10 Chrome
- [ ] Win 10 Firefox
- [ ] Win 10 Edge
- [ ] Win 10 Chrome Throttle
---
- [ ] Mac OS Chrome
- [ ] Mac OS Firefox
- [ ] Mac OS Safari
- [ ] Mac OS Firefox Throttle
---
- [ ] Chrome OS

**Comment by KatieWoe** [comment]
QA is done.
