### ISSUE TITLE
Make sure that phet-io metacog recording is documented for QA

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#191]
@KatieWoe, we have been doing a lot of Metacog recording for phet-io maintenance releases, and it will continue to be a part of phet-io testing in the future. This issue is to make sure that QA has all the resources consolidated and organized to explain the full metacog stack as we have just been exercising for FAMB. For the most part, the only complete place I see it explained is in https://github.com/phetsims/QA/issues/187#issue-360088338.

What do you think is best here?

**Comment by KatieWoe** [comment]
@zepumph Best method would probably be for us to put it in the QA book, probably worded fairly similarly to that comment, but generalized and maybe with a few tweaks.

**Comment by KatieWoe** [comment]
@zepumph This is what I'm considering adding to the QA book in the phet-io instructions section.  Let me know if you think anything is missing or should be changed i.e. I should put the playback link we used before in or should take out a link, etc..

#### Metacog Recording Testing
- _What?_ This is a method of checking a recording that does not use a play back wrapper.
- _How?_ First, make the recording using the link provided.  Check that you are recording to metacog by looking in the console for the line `Recorder initialized, sending data to: ["metacog"]`.  When you are done, press either the back arrow or x out of the tab.  You should be prompted to stay while the process finishes.  DO NOT LEAVE, instead press cancel and wait for the go-ahead to leave.  (Note: Firefox may not show the dialog if you use the back arrow.)  Wait for thirty minutes before moving to the next step.  Use this [link](http://phettest.colorado.edu/phet-io-website/root/metacog/request-data.html) to retrieve the data.  Paste the provided URL into the URL box, the provided ID into the Application ID, and the email you want to receive the logs in into the email box.  Nothing else needs to be entered.  If you have the console open when you hit submit you will get an ID number you can use if something goes wrong with the retrieval.  The email will take about 20 minutes.  Make sure the gz file is uncompressed.  Use the provided playback link to test the recording. [This](https://github.com/phetsims/phet-io/blob/master/doc/metacog.md) may be helpful.

**Comment by zepumph** [comment]
This is really great thanks! 

For "what"  I would say something like,  "This test exercises the full recording and playback process used for PhET studies. This includes recording to and retrieving from our data back end partner, Metacog." maybe something about how the playback should be the exact same as when recording with '?localFile'. 

The "how" is very nice. I would recommend saying that the application ID won't be provided in the issue, because it's like a password, but you can ask the phetio dev if they don't give it to you. Also change "the provided playback link"  to say the one in the wrapper index. Thanks for this! Tagging @samreid in case he has edits. Otherwise you are good to document.

**Comment by KatieWoe** [comment]
All added with suggested changes in the two above commits.  Closing now.

**Comment by samreid** [comment]
Looks good, thanks!
