### ISSUE TITLE
Maintenance Release: Energy Skate Park Basics 1.3.6-rc.1

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#192]
@samreid @kathy-phet @DianaTavares @jessegreenberg(responsible dev) ESPB is ready for a maintenance release.

This publication is to support a PhET-iO interaction study, see https://github.com/phetsims/energy-skate-park/issues/21 for details. I'm sorry to say that this is as much of a rush job as for FAMB. Thank you all for your hard work!

The only code we added was on the wrapper side, with the exception of a new query parameter: `phetioEmitStatesInterval`.

The testing required for this release is to make sure that the features added are working as expected, as well as testing the full process that will be used in the upcoming study (i.e. recording to metacog). The study will start next Wednesday, Sept. 26th

This test will be very similar to the recent  FAMB testing in #187  

## First
 please test the simulation as you would normally for a maintenance release. Make sure that on one or two devices, all the links works as expected, and play around with it for a few seconds.

[Link to wrapper index](https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.3.6-rc.1/wrappers/index)

Notes:
* You will need to add the `?relativeSimPath` query parameter  (or `&relativeSimPath` if there is already other query parameters) to each link in the wrapper index. I'm sorry.
* As always it is good to note that this sim was originally published in Jan 2017. As a result, when finding bugs, see if the bug is present in [the previous version](https://phet-io.colorado.edu/sims/energy-skate-park-basics/1.3.5-phetio/wrappers/index/) and/or in master before creating an issue. 
* Note this old version of the wrapper index doesn't have a link directly to the sim, here it is in case you need it: https://phet-io.colorado.edu/sims/energy-skate-park-basics/1.3.5-phetio/energy-skate-park-basics_en-phetio.html?phetioStandalone

## Second
Below is the link to the study link that records to the console, not to metacog:

https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.3.6-rc.1/wrappers/iframe/iframe.html?url=../login/login.html?screens=1,2&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=9&promptText=Enter%20your%209%20Digit%20Student%20ID&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=energy-skate-park-baics-test&phetioEmitInputEvents=true&phetioEmitStates=true&phetioEmitStatesInterval=60&relativeSimPath&console

- [ ] Please test this link fully by entering a 9 digit number, like "111111111", and testing the redirected wrapper

## Third
Test metacog record and playback via the following link, please consult #191 and https://github.com/phetsims/QA/issues/187#issue-360088338 for specifics.
Link to record: 
https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.3.6-rc.1/wrappers/iframe/iframe.html?url=../login/login.html?screens=1,2&wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=9&promptText=Enter%20your%209%20Digit%20Student%20ID&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=energy-skate-park-baics-qatest1&phetioEmitInputEvents=true&phetioEmitStates=true&phetioEmitStatesInterval=60&relativeSimPath&metacog

Link for playback:
https://phet-dev.colorado.edu/mjkauzmann/FAMB-2.1-phetio-playback/metacog/playback/

@ariel-phet for priority and assignment.

**Comment by KatieWoe** [comment]
Per Slack:
>Kathryn Woessner [10:04 AM]
I just tried to enter 098765432 and it says "Error: 098765432 should be a number
Michael Kauzmann [10:05 AM]
Can't start with 0, weird error though. In the issue please comment and assign me to see if that happens in master. It should be fixed in master, though likely not in the branch.

Other than that, QA is done

**Comment by zepumph** [comment]
It is not a problem in master. `0000000` is an acceptable 7 digit number. I think we are ready to close.
