### ISSUE TITLE
Can a11y-* test templates be deleted now?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#193]
@KatieWoe now that we have the general templates for testing, do you think it is OK to delete the test templates prefixed with a11y-?

**Comment by KatieWoe** [comment]
@jessegreenberg it might be useful to leave up for a bit longer in case we find problems with the general templates in the first little bit of implementation.  But I think after a bit of time if the QA team and the developers both find the general template useful, we will delete the old templates.

**Comment by jessegreenberg** [comment]
OK, sounds good @KatieWoe, Ill go ahead and close this issue. Thanks for clarifying.
