### ISSUE TITLE
Twitter Card Maintenance Release Testing

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#195]
All links should get a quick "did anything major break" test done, 10-20 seconds or so, running with no query parameters. If it didn't work in previous maintenance releases, it can be skipped (but please note it still!)

The only other thing to test is for the presence of `{{sim-name}}-twitter-card.png`.  I've verified this via a script but please double check.

Assigning to @ariel-phet for priority. 

Release Candidate links

acid-base-solutions 1.2 (phetsims/website#583)

- [x] [acid-base-solutions 1.2.15-rc.1](https://phet-dev.colorado.edu/html/acid-base-solutions/1.2.15-rc.1/acid-base-solutions_en.html)

area-builder 1.1 (phetsims/website#583)

- [x] [area-builder 1.1.10-rc.1](https://phet-dev.colorado.edu/html/area-builder/1.1.10-rc.1/area-builder_en.html)

arithmetic 1.0 (phetsims/website#583)

- [x] [arithmetic 1.0.14-rc.1](https://phet-dev.colorado.edu/html/arithmetic/1.0.14-rc.1/arithmetic_en.html)

atomic-interactions 1.0 (phetsims/website#583)

- [x] [atomic-interactions 1.0.8-rc.1](https://phet-dev.colorado.edu/html/atomic-interactions/1.0.8-rc.1/atomic-interactions_en.html)

balancing-act 1.1 (phetsims/website#583)

- [x] [balancing-act 1.1.14-rc.1](https://phet-dev.colorado.edu/html/balancing-act/1.1.14-rc.1/balancing-act_en.html)

balancing-chemical-equations 1.1 (phetsims/website#583)

- [x] [balancing-chemical-equations 1.1.14-rc.1](https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.1.14-rc.1/balancing-chemical-equations_en.html)

beers-law-lab 1.4 (phetsims/website#583)

- [x] [beers-law-lab 1.4.9-rc.1](https://phet-dev.colorado.edu/html/beers-law-lab/1.4.9-rc.1/beers-law-lab_en.html)

bending-light 1.1 (phetsims/website#583)

- [x] [bending-light 1.1.11-rc.1](https://phet-dev.colorado.edu/html/bending-light/1.1.11-rc.1/bending-light_en.html)

charges-and-fields 1.0 (phetsims/website#583)

- [x] [charges-and-fields 1.0.10-rc.1](https://phet-dev.colorado.edu/html/charges-and-fields/1.0.10-rc.1/charges-and-fields_en.html)

color-vision 1.1 (phetsims/website#583)

- [x] [color-vision 1.1.14-rc.1](https://phet-dev.colorado.edu/html/color-vision/1.1.14-rc.1/color-vision_en.html)

concentration 1.3 (phetsims/website#583)

- [x] [concentration 1.3.11-rc.1](https://phet-dev.colorado.edu/html/concentration/1.3.11-rc.1/concentration_en.html)

energy-skate-park-basics 1.1 (phetsims/website#583)

- [x] [energy-skate-park-basics 1.1.10-rc.1](https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.1.10-rc.1/energy-skate-park-basics_en.html)

faradays-law 1.1 (phetsims/website#583)

- [x] [faradays-law 1.1.14-rc.1](https://phet-dev.colorado.edu/html/faradays-law/1.1.14-rc.1/faradays-law_en.html)

fraction-matcher 1.1 (phetsims/website#583)

- [x] [fraction-matcher 1.1.12-rc.1](https://phet-dev.colorado.edu/html/fraction-matcher/1.1.12-rc.1/fraction-matcher_en.html)

function-builder 1.0 (phetsims/website#583)

- [x] [function-builder 1.0.14-rc.1](https://phet-dev.colorado.edu/html/function-builder/1.0.14-rc.1/function-builder_en.html)

gravity-and-orbits 1.1 (phetsims/website#583)

- [x] [gravity-and-orbits 1.1.6-rc.1](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.1.6-rc.1/gravity-and-orbits_en.html)

gravity-force-lab 2.1 (phetsims/website#583)

- [x] [gravity-force-lab 2.1.6-rc.1](https://phet-dev.colorado.edu/html/gravity-force-lab/2.1.6-rc.1/gravity-force-lab_en.html)

hookes-law 1.0 (phetsims/website#583)

- [x] [hookes-law 1.0.14-rc.1](https://phet-dev.colorado.edu/html/hookes-law/1.0.14-rc.1/hookes-law_en.html)

isotopes-and-atomic-mass 1.0 (phetsims/website#583)

- [x] [isotopes-and-atomic-mass 1.0.13-rc.1](https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.0.13-rc.1/isotopes-and-atomic-mass_en.html)

least-squares-regression 1.1 (phetsims/website#583)

- [x] [least-squares-regression 1.1.11-rc.1](https://phet-dev.colorado.edu/html/least-squares-regression/1.1.11-rc.1/least-squares-regression_en.html)

make-a-ten 1.0 (phetsims/website#583)

- [x] [make-a-ten 1.0.7-rc.1](https://phet-dev.colorado.edu/html/make-a-ten/1.0.7-rc.1/make-a-ten_en.html)

molecule-shapes 1.1 (phetsims/website#583)

- [x] [molecule-shapes 1.1.15-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes/1.1.15-rc.1/molecule-shapes_en.html)

molecule-shapes-basics 1.1 (phetsims/website#583)

- [x] [molecule-shapes-basics 1.1.13-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.1.13-rc.1/molecule-shapes-basics_en.html)

neuron 1.1 (phetsims/website#583)

- [x] [neuron 1.1.8-rc.1](https://phet-dev.colorado.edu/html/neuron/1.1.8-rc.1/neuron_en.html)

ohms-law 1.3 (phetsims/website#583)

- [x] [ohms-law 1.3.12-rc.1](https://phet-dev.colorado.edu/html/ohms-law/1.3.12-rc.1/ohms-law_en.html)

ph-scale 1.2 (phetsims/website#583)

- [x] [ph-scale 1.2.15-rc.1](https://phet-dev.colorado.edu/html/ph-scale/1.2.15-rc.1/ph-scale_en.html)

ph-scale-basics 1.2 (phetsims/website#583)

- [x] [ph-scale-basics 1.2.15-rc.1](https://phet-dev.colorado.edu/html/ph-scale-basics/1.2.15-rc.1/ph-scale-basics_en.html)

rutherford-scattering 1.0 (phetsims/website#583)

- [x] [rutherford-scattering 1.0.11-rc.1](https://phet-dev.colorado.edu/html/rutherford-scattering/1.0.11-rc.1/rutherford-scattering_en.html)

states-of-matter 1.0 (phetsims/website#583)

- [x] [states-of-matter 1.0.6-rc.1](https://phet-dev.colorado.edu/html/states-of-matter/1.0.6-rc.1/states-of-matter_en.html)

states-of-matter-basics 1.0 (phetsims/website#583)

- [x] [states-of-matter-basics 1.0.6-rc.1](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.0.6-rc.1/states-of-matter-basics_en.html)

trig-tour 1.0 (phetsims/website#583)

- [x] [trig-tour 1.0.13-rc.1](https://phet-dev.colorado.edu/html/trig-tour/1.0.13-rc.1/trig-tour_en.html)

under-pressure 1.1 (phetsims/website#583)

- [x] [under-pressure 1.1.9-rc.1](https://phet-dev.colorado.edu/html/under-pressure/1.1.9-rc.1/under-pressure_en.html)

unit-rates 1.0 (phetsims/website#583)

- [x] [unit-rates 1.0.8-rc.1](https://phet-dev.colorado.edu/html/unit-rates/1.0.8-rc.1/unit-rates_en.html)

wave-on-a-string 1.1 (phetsims/website#583)

- [x] [wave-on-a-string 1.1.13-rc.1](https://phet-dev.colorado.edu/html/wave-on-a-string/1.1.13-rc.1/wave-on-a-string_en.html)

**Comment by phet-steele** [comment]
All the twitter cards are there!

**Comment by KatieWoe** [comment]
Tested Latest iOS, Win, and Mac OS.  QA is done.

**Comment by mattpen** [comment]
Thanks, I've kicked off the production deploy.
