### ISSUE TITLE
Suggestion: consolidate rc-test-template and rc-test-template-new

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#198]
As of this writing there are two RC test templates, named as described in the issue title.  This seems confusing, and having something like "new" in the title is going to be even more confusing once it gets a little older.  Can we just have one rc-test-template?  After all, creating new versions of things without having to rename them is exactly what git and GitHub are for.

If both versions are still needed, please rename them to something that makes it clear when one should be used over the other.

**Comment by KatieWoe** [comment]
Above commit changes "rc-test-template" to "old-relic-rc-test-template" and "rc-test-template-new" should be used from now on.  Keeping old test template for time being as a few issues were found with the new markup file and I want it there as a back up in case we decide the new template isn't sufficient.  After a few successful rcs, if the devs like the new template the old will be deleted.
