### ISSUE TITLE
Maintenance release testing for RichText changes

### ISSUE THREAD

**Issue by phet-steele** [phetsims/QA#2]
Maintenance release RCs for https://github.com/phetsims/scenery-phet/issues/312.

This was applied to all sims that contained RichText in their production version. It may not be used in some sims.

For all sims:

- Open the sim in Chrome, run through a ~30 second check to make sure the sim operates normally.

For sims that have RichText (usually subscript/superscript bits, I didn't do an exhaustive check):

- Open the sim with the query parameter `?stringTest=a%26lt;%3Ci%3Eb%3C%2Fi%3E`. Ensure any RichText output looks like:
![richtext-1-good](https://user-images.githubusercontent.com/480878/27502972-5d613482-5835-11e7-9ebd-a6e796a06fc4.PNG)
where if the 'b' is italic, then a '<' symbol is shown, instead of
![richtext-1-bad](https://user-images.githubusercontent.com/480878/27502977-61efc0cc-5835-11e7-8e32-5770d1ca3f4a.PNG)
where the 'b' is italic (no tags around it) but the '<' symbol is replaced with other content. Ignore anything non-RichText that looks like:
![richtext-1-ignore](https://user-images.githubusercontent.com/480878/27502983-75c71afa-5835-11e7-999b-40e4571b66b1.PNG)

- Open the sim with the query parameter `?stringTest=rtl`. Ensure any RichText output looks like:
![richtext-2-good](https://user-images.githubusercontent.com/480878/27503001-a342e68a-5835-11e7-9bc3-118e7579a347.PNG)
instead of
![richtext-2-bad](https://user-images.githubusercontent.com/480878/27503004-a8870d92-5835-11e7-8ef8-dbd8b0a5593e.PNG)

- [x] [function-builder-basics 1.0.1-rc.1](http://www.colorado.edu/physics/phet/dev/html/function-builder-basics/1.0.1-rc.1/function-builder-basics_en.html)
- [x] [graphing-lines 1.2.1-rc.1](http://www.colorado.edu/physics/phet/dev/html/graphing-lines/1.2.1-rc.1/graphing-lines_en.html)
- [x] [graphing-slope-intercept 1.0.1-rc.1](http://www.colorado.edu/physics/phet/dev/html/graphing-slope-intercept/1.0.1-rc.1/graphing-slope-intercept_en.html)
- [x] [john-travoltage 1.3.1-rc.1](http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.3.1-rc.1/john-travoltage_en.html)
- [x] [plinko-probability 1.1.1-rc.1](http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.1.1-rc.1/plinko-probability_en.html)
- [x] [proportion-playground 1.0.1-rc.1](http://www.colorado.edu/physics/phet/dev/html/proportion-playground/1.0.1-rc.1/proportion-playground_en.html)

- [x] [balloons-and-static-electricity 1.3.2-phetiorc.1](http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.3.2-phetiorc.1/wrappers/index/)
- [x] [build-an-atom 1.5.4-phetiorc.1](http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.5.4-phetiorc.1/wrappers/index/)
- [x] [john-travoltage 1.4.2-phetiorc.1](http://www.colorado.edu/physics/phet/dev/html/john-travoltage/1.4.2-phetiorc.1/wrappers/index/)
- [x] [plinko-probability 1.1.1-phetiorc.1](http://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.1.1-phetiorc.1/wrappers/index/)

**Comment by phet-steele** [comment]
@jonathanolson the above list passes. Did you not see it fit to patch Chains?

**Comment by jonathanolson** [comment]
@zepumph, patches were made on the release branch for plinko phet-io before I deployed, so I'll pass off deploying/testing responsibility to you (see https://github.com/phetsims/plinko-probability/commits/1.1-phetio).

Also it diverged from the plinko phet-brand branch, which I think was going to be avoided?

**Comment by jonathanolson** [comment]
Unassigned, I've taken care of the other production deploys.

**Comment by zepumph** [comment]
Only one person is using this version of phet-io plinko, and I will need to do a maintenance release for this in a week or so, because of a metacog library change. I think it will be best to hold off and do one release then. 

>Also it diverged from the plinko phet-brand branch, which I think was going to be avoided?

Could you explain a bit further? If I look at https://github.com/phetsims/plinko-probability/network I see that both branches have exactly the same content commits since they were created, albeit not the same shas.

**Comment by jonathanolson** [comment]
> Also it diverged from the plinko phet-brand branch, which I think was going to be avoided?

Sorry, I was incorrect about divergence (missed the QA credits update on one branch)!

**Comment by zepumph** [comment]
Sounds good. I will close this issue, and handle the new plinko probability release with https://github.com/phetsims/phet-io/issues/1121. Thanks for taking the lead @jonathanolson
