### ISSUE TITLE
RC Spot Check: Rutherford Scattering 1.1.0-rc.3

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#202]
@ariel-phet, rutherford-scattering/1.1.0-rc.3 is ready for RC testing. 1.1.0-rc.2 was completed, and this is the follow up test. A full test on all platforms is not necessary, just a spot check on a few platforms and to verify that the issue that was found is fixed.

Document issues in https://github.com/phetsims/rutherford-scattering/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Test all touchscreen inputs.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Focus and Special Instructions</h3>

Since the last RC, the only change is to the layout of the panels in the "Plum Pudding" screen. Please make sure that the panels on this screen
look OK with string tests. Otherwise, minor spot checking on a couple of platforms is sufficient.

<h3>Issues to Verify</h3>

- [x] [Misaligned string in Plum pudding screen](https://github.com/phetsims/rutherford-scattering/issues/151)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/rutherford-scattering/1.1.0-rc.3/phet/rutherford-scattering_all_phet_debug.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/rutherford-scattering/1.1.0-rc.3/phet/rutherford-scattering_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/rutherford-scattering/1.1.0-rc.3/phet/xhtml/rutherford-scattering_all_phet.html)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Devices to Test On (@jessegreenberg let me know if you have any changes you want):
---
- [] Win 10 Chrome full
- [ ] Win 10 Edge full
- [ ] Win 10 Firefox partial
---
- [ ] Mac OS 10.14 Chrome partial
- [ ] Mac OS 10.14 Safari full
- [ ] Mac OS 10.14 Firefox full
---
- [ ] Win 8.1 IE full
- [ ] Win 8.1 chrome partial
---
- [ ] Mac OS 10.13 Chrome partial
- [ ] Mac OS 10.13 Safari partial
---
- [ ] Chrome OS partial
---
- [ ] iOS 12 partial
- [ ] iOS 11 partial

**Comment by ariel-phet** [comment]
@KatieWoe currently a low priority, nice to republish this sim, but not pressing.

**Comment by jessegreenberg** [comment]
The only difference since the last RC is this commit https://github.com/phetsims/rutherford-scattering/commit/2c68f9bae6ef738dd1fc199b3cd708276c76fa45, which only changes layout of panels in the plum pudding screen. A "partial" test on all of the above is probably sufficient, does that sound reasonable @KatieWoe? What is the difference between a partial and full test?

**Comment by KatieWoe** [comment]
@jessegreenberg A full test would act like a normal rc.  A partial test would mostly just look at any issues to confirm, or a quick check to make sure nothing had broken.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, in that case I don't think we need any more "full" testing for this RC. Just partial testing on the platforms you listed seems like plenty.

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, sounds great. I think this is ready for deployment then, but this will probably need the patch from https://github.com/phetsims/QA/issues/213. It looks like the 1.0 version got the patch, 1.1 will need it too before deployment.

**Comment by jessegreenberg** [comment]
I created rc.4 that is identical to rc.3 but with the patch in joist for that issue. Since 1.0 was patched, I should check in on that issue and make sure that 1.0 isn't redeployed.

**Comment by jessegreenberg** [comment]
Comments made in issues related to https://github.com/phetsims/QA/issues/213, this can be closed.
