### ISSUE TITLE
Dev test: Coulomb's Law 1.0.0-dev.19

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/QA#203]
@arouinfar , @emily-phet , @jessegreenberg coulombs-law/1.0.0-dev.19 is ready for dev testing. Document issues in https://github.com/phetsims/coulombs-law/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome, Firefox, and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Issues to Verify</h3>

- [x] [Missing string found in CT (should be fixed now)](https://github.com/phetsims/coulombs-law/issues/68)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Coulomb's Law](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-dev.19/phet/coulombs-law_en_phet.html)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) Dev Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.

<h3>Focus and Special Instructions</h3>

See the issues below, but please pay special attention to keyboard navigation within Firefox.

<h3>Issues to Verify</h3>

- [x] [Firefox lags with ruler keyboard dragging](https://github.com/phetsims/coulombs-law/issues/41)

Please note that this hasn't been specifically fixed as we couldn't really ascertain the cause. We opted to push its full fix to 1.1, but it would be useful to know if this is still persisting and any more details that we may not have gathered in the first round.

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-dev.19/phet/coulombs-law_a11y_view.html)**
- **[Coulolmb's Law (a11y)](https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-dev.19/phet/coulombs-law_en_phet.html?accessibility)**

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a screen reader.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by arouinfar** [comment]
It's super exciting to see CL moving into QA testing!

@mbarlow12 it was my understanding that CL would be published without any a11y features. While  it's true that keyboard navigation is functional with `?accessibility`, it's missing the keyboard dialog (https://github.com/phetsims/coulombs-law/issues/58#issuecomment-399185697) and there's a also a known keyboard nav issue with the ruler (https://github.com/phetsims/coulombs-law/issues/41). Both of these issues were deferred until version 1.1+. Perhaps this issue should be amended to remove a11y testing.

**Comment by ariel-phet** [comment]
@KatieWoe this task is similar priority to #199 since both are new sims, and this would be an exiting one to get published.

**Comment by arouinfar** [comment]
@mbarlow12 since keyboard nav is deferred until 1.1, I'm not sure that the dialog is necessary, but I'll leave it up to you.

**Comment by emily-phet** [comment]
I may be mis-remembering, but I believe a11y features were deferred because there was some urgency to get additional sims out for the start (or at least, early part of) the Fall start to school. Since that's not the case now, I don't see any reason to defer deploying with keyboard nav, if all it takes is adding in the already designed dialog, and QA testing keyboard nav. If significant issues come up in QA testing, we can triage from there and decide to defer at that point if necessary. 

Does this seem reasonable @ariel-phet

**Comment by arouinfar** [comment]
That all sounds reasonable to me @emily-phet, so long as @mbarlow12 has the bandwidth for it.

**Comment by KatieWoe** [comment]
QA is done

**Comment by mbarlow12** [comment]
@KatieWoe after the updates from @jessegreenberg in https://github.com/phetsims/john-travoltage/issues/317, is the full screen IE issue resolved for CL and GFL(:B)?

If so, then with the ruler dragging deferred to 1.1, I'd say we can move on to the next stage.

**Comment by KatieWoe** [comment]
@mbarlow12 https://github.com/phetsims/john-travoltage/issues/317#issuecomment-427474308
Yes it should be resolved for both sims.

**Comment by mbarlow12** [comment]
@ariel-phet do I have the go ahead to move into RC testing?

**Comment by ariel-phet** [comment]
@mbarlow12 sort of....I don't see the keyboard dialog?

Could you publish a version that includes the keyboard dialog...I don't see it when I run
https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-dev.19/phet/coulombs-law_all_phet.html?accessibility

Please publish a dev version that includes that, and have @arouinfar do a quick spot check of the dialog, and if all looks good feel free to move onto RC. Make sure the RC also includes a check of the projector mode.

**Comment by mbarlow12** [comment]
@arouinfar @ariel-phet  here's a new dev version with the keyboard help dialog.

https://phet-dev.colorado.edu/html/coulombs-law/1.0.0-dev.20/phet/coulombs-law_en_phet.html

Let me know what tweaks need to be made before heading to RC.

**Comment by phet-steele** [comment]
RC in #210.
