### ISSUE TITLE
Should there be some testing of the debug version during RC QA testing?

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#204]
In https://github.com/phetsims/coulombs-law/issues/70 @jessegreenberg and I found an assertion that was only triggered in the build version, so it only happened when running a sim built with assertions left in (debug version or `--mangle=false` option). Do we think that it would be good for QA to test on the debug version for RC. 

I don't think it warrants another item to the list. Perhaps QA can choose "randomly" one block of their matrix to test with the debug version each full RC. If they encounter performance issues, they can compare it will the normal built sim. 

@KatieWoe @ariel-phet how does this sound? Marking for dev meeting to see it if it worth it.

**Comment by KatieWoe** [comment]
I'd like to make sure I have a better understanding of what the debug version is and how its different, but in general I don't necessarily have a problem with this.

**Comment by zepumph** [comment]
The difference between versions are that in the debug version (a) assertions are left in, and (b) the file isn't mangled/minified so that it is easier to read (hence it may be slower).

**Comment by samreid** [comment]
Please see this thread: "Should QA tests be able to test with assertions enabled?" https://github.com/phetsims/tasks/issues/722

**Comment by zepumph** [comment]
The last comment there from @phet-steele:

>QA knows the debug versions exist, and they know when to use them 👍

If that is true then all is good here. The main reason I brought up this issue was because phetsims/coulombs-law#70 was the first time that I saw an issue only triggered with assertions in built mode. 

@KatieWoe do you feel like you have a good grasp on when/how to use the debug version? Anything else for this issue?

**Comment by KatieWoe** [comment]
@zepumph I don't really.  It hadn't been brought up until now so I'm just starting to look into it.  Hopefully I'll be able to ask someone to walk me through it this week and we'll be good after that though.

**Comment by pixelzoom** [comment]
The more important issue here is that the built version is somehow different enough to trigger an assertion failure.  Do we understand why that is the case?

**Comment by samreid** [comment]
> The more important issue here is that the built version is somehow different enough to trigger an assertion failure.

I don't understand what this means.  What is the built version different from?  We are talking about comparing the built version to the built debug version.  The hypothesis is that QA team should be running some tests with the debug version and ?ea to catch issues that would perhaps silently fail in the main built version.

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/coulombs-law/issues/70 we found that the buildt version is different from the requireJS version, and we don't know why yet.

If the QA team tests the debug version, https://github.com/phetsims/coulombs-law/issues/70 and other issues like it will be caught in the future.

**Comment by pixelzoom** [comment]
Rather than adding additional testing to QA's plate, I think we'd be better off understanding and fixing the root cause of the difference between requirejs and built versions.  Before adding to QA tests, consider adding to CT tests.

**Comment by jessegreenberg** [comment]
Discussion from 10/11/18

@KatieWoe wondered if the debug version requires the ?ea query param. Devs said that assertions are enabled by default.

@KatieWoe says that @phet-steele would test with the debug version in the background with ?fuzzMouse testing.

We discussed that if a QA issue is found while testing a built version, the debug version could be used to find more information upstream. @KatieWoe said that she would put the debug version on a machine and run in the background that won't take any additional time. She will make a note of this in the QA handbook.
