### ISSUE TITLE
Getting Laura Started

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/QA#206]
@ariel-phet @oliver-phet

- [x] GitHub Email, GitHub Account, Join Organization
- [x] Add Laura to the QA Team
- [x] Add Laura to the Google Group
- [x] Google Calendar
- [x] Phases of Development
- [x] GitHub Workflow
- [x] How to Test & Tricks-of-the-Trade (simulation locations, query parameters, development tools, etc.)
- [x] Practice Creating an Issue
- [x] Introduce Test Server
- [x] Introduce Website
- [x] Website Account
- [x] Picture for Website and Bio
- [x] Slack
- [x] Key
- [x] phet@lists.colorado.edu
- [x] QA Book
- [x] Finish All Administrative Paperwork
- [x] W4 and Direct Deposit Up-to-Date on myCUinfo
- [x] Picture for GitHub

**Comment by ariel-phet** [comment]
Let me know if you need anything here, but I do not think any action by me is necessary currently.
