### ISSUE TITLE
Spot Test Nav Bar on iOS

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#207]
QA, please complete a quick spot test of the nav bar on Mobile Safari and Chrome for iOS.  Please test on a small device (<809px width) and a large device(> 810px width), as there are two version of the nav menu.  Please test using normal touch interaction and using VoiceOver swipe navigation.  We should verify that the menus open/close when touched once, or when focused with the swipe nav.  All links should be tested to verify that they are working properly.  I'm already aware that (a) the links direct to a page without the nav bar and (b) the PhET/CU logos may be broken.

To clarify:
Small nav bar:
![image](https://user-images.githubusercontent.com/11747676/46691157-719c5e80-cbc1-11e8-9fb0-9ecdce111d4f.png)
Large nav bar:
![image](https://user-images.githubusercontent.com/11747676/46691169-7b25c680-cbc1-11e8-9dac-11cb07fb1153.png)

The new nav bar can be found at https://ox-dev.colorado.edu/reskin/.

Assigning @ariel-phet for priority, this currently isn't blocking anything on my end.

**Comment by KatieWoe** [comment]
Other than the above issue everything looks good and the links work.  I tested on iPhone 7 iOS 11.4.1 and iPad Air 2 iOS 12.0.1.  @mattpen do you want any other range of devices tested?  If not, QA is done.

**Comment by mattpen** [comment]
That's great for now!  Thanks!
