### ISSUE TITLE
Performance test mobile a11y: round 3

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#209]
I found a couple places where performance could be improved for mobile VO in https://github.com/phetsims/scenery/issues/852.

@KatieWoe can you please check this version of gravity-and-orbits to see how the sim is behaving now on devices where performance was previously terrible?
https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-pdomTransform.4/phet/gravity-and-orbits_en_phet.html?accessibility&mobileA11yTest

  - [x] Windows 7 Chrome
  - [ ] iOS10
  - [x] Chrome OS
  - [x] Mac OS 10.14 Chrome

Like last time, if the sim outright crashes no need to test any further.

**Comment by KatieWoe** [comment]
@ariel-phet for priority

**Comment by KatieWoe** [comment]
@jessegreenberg just did the Mac 10.14 and it still runs a bit slow but it is much, much better.

**Comment by KatieWoe** [comment]
iOS 10 is still crashing before reaching the home screen

**Comment by jessegreenberg** [comment]
OK thanks @KatieWoe. Since this seemed promising on  Mac 10.14 could you please check the other two platforms? The crash is strange because I also tested on iOS 9.3 before creating this issue.

**Comment by KatieWoe** [comment]
Chrome OS looks ok

**Comment by KatieWoe** [comment]
Win 7 looks ok
@jessegreenberg QA is done

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe. Could you please confirm that this sim (without a11y and new PDOM positioning) is not crashing on iOS 10?
https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-pdomTransform.4/phet/gravity-and-orbits_en_phet.html

while this version is?

https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-pdomTransform.4/phet/gravity-and-orbits_en_phet.html?accessibility&mobileA11yTest

**Comment by KatieWoe** [comment]
@jessegreenberg the first link you gave me just now is also crashing the sim.  This seems very odd.  I checked the published version and it, at least, seems fine on iOS 10.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, can you try the complied version on phettest?

**Comment by KatieWoe** [comment]
@jessegreenberg built version from phettest looks ok

**Comment by jessegreenberg** [comment]
Thanks! OK, closing this issue, I may have access to iOS10 (or later) and will see if it is crashing there, otherwise I might return for assistance to check on what could be causing the crashing.
