### ISSUE TITLE
Dev test: Molecule Polarity 1.0.0-dev.23

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#21]
This is the first dev test of Molecule Polarity.

Dev test:
http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-dev.23/molecule-polarity_en.html

iFrame test:
http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-dev.23/molecule-polarity_en-iframe.html

This sim was ported from Java, and consists of 3 screens. 

The first 2 screens ("Two Atoms", "Three Atoms") have the following differences from the Java version:
• Turning the E-field on/off will show/hide the plates.  See https://github.com/phetsims/molecule-polarity/issues/52. In the Java version, the plates were always visible, and the polarity indicators were shown/hidden. 
• When the sim starts, "cueing arrows" are shown around the molecules. Their behavior is specified in https://github.com/phetsims/molecule-polarity/issues/50#issuecomment-315423864.  In the Java version, the overall behavior was different, and the rotation arrows were a custom cursor.

The third screen ("Real Molecules") is not fully implemented, since we don't have a 3D molecule viewer for HTML5.  Since it's likely to be some time before a 3D viewer is implemented, PhET decided to publish without that functionality, see https://github.com/phetsims/molecule-polarity/issues/27.  A dialog in the "Real Molecules" screen directs the user to the Java version.

Sim-specific query parameters are documented in [MPQueryParameters.js](https://github.com/phetsims/molecule-polarity/blob/master/js/common/MPQueryParameters.js). Ignore the `realMolecules` query parameter, there is no need to test it. 

I have tested primarily on Chrome, Safari and Mobile Safari.  Please spot check on other platforms. This sim does not currently use WebGL.

Please mention this issue in any GitHub issues that you create.

Assigned to @ariel-phet for prioritization.

**Comment by pixelzoom** [comment]
Since this sim was ported in 2014, there is no "Terminology" section per se in the documentation. You might find it useful to skim through [model.md](https://github.com/phetsims/molecule-polarity/blob/master/doc/model.md), followed by [implementation-notes.md](https://github.com/phetsims/molecule-polarity/blob/master/doc/implementation-notes.md), before testing this sim.

**Comment by phet-steele** [comment]
@pixelzoom, this testing is done.

**Comment by pixelzoom** [comment]
Thank you @phet-steele and QA team - you found some good stuff.

All related issues have been addressed and are closed.  So closing this issue.

@emily-phet We're ready to proceed to RC testing as soon as https://github.com/phetsims/molecule-polarity/issues/73 is closed.
