### ISSUE TITLE
Dev test: Graphing Quadratics 1.0.0-dev.38

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#211]
@KatieWoe, @amanda-phet, Graphing Quadratics 1.0.0-dev.38 is ready for dev testing.  This is a test of the PhET brand only; PhET-iO is not included. 

Deadline for completion of this dev test in 10/29/18. This version will _not_ be shared with a client. 

Document issues in https://github.com/phetsims/graphing-quadratics/issues and link to this issue.

Prior to testing, please read [model.md](https://github.com/phetsims/graphing-quadratics/blob/master/doc/model.md) and the Terminology section of [implementation-notes.md](https://github.com/phetsims/graphing-quadratics/blob/master/doc/implementation-notes.md).  Please try to use this terminology in any issues that are created, so that we're all speaking the same language.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Link(s)</h3>

- [Graphing Quadratics 1.0.0-dev.38](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.0-dev.38/phet/graphing-quadratics_en_phet.html)

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
QA is done.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.

**Comment by pixelzoom** [comment]
All issues address with the exception of #82. Closing.
