### ISSUE TITLE
RC Testing for Maintenance Release--Full Screen removal on iOS

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#213]
Full details are in https://github.com/phetsims/special-ops/issues/122, which also provides the full list of RC URLs to be tested.  This issue is for prioritization/scheduling amongst the other QA issues.  The bird's eye view summary from https://github.com/phetsims/special-ops/issues/122 is:

> For https://github.com/phetsims/joist/issues/524, we performed a maintenance release https://github.com/phetsims/joist/issues/525 to remove the PhET Menu "Full Screen" from mobile safari.

Assigning to @ariel-phet for prioritization/scheduling/delegation, and to add any other labels as appropriate.

**Comment by KatieWoe** [comment]
QA is done.

**Comment by samreid** [comment]
Thanks @KatieWoe, I'll close this one and continue in https://github.com/phetsims/special-ops/issues/122
