### ISSUE TITLE
RC Test: Atomic Interactions 1.1.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#216]
@KatieWoe, @ariel-phet, atomic-interactions/1.1.0-rc.1 is ready for RC testing. This is being done as part of the update of all sims in the States of Matter suite, so a fair amount of this code was verified during the test cycle for States of Matter 1.1.0.  However, the standalone version of Atomic Interactions has additional features versus the Atomic Interactions screen in the States of Matter sim, and these features should be thoroughly tested.

Please document issues in https://github.com/phetsims/atomic-interactions/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.

<h3>Focus and Special Instructions</h3>

Much of the code that comprises this sim was tested during the recent 1.1 release of the States of Matter simulation.  However, there are some differences between this sim and how the "Atomic Interactions" screen in States of Matter looks and behaves, so the testing should focus on these differences.

<h3>Issues to Verify</h3>

- [x] [Query parameter doesn't work for setting projector mode](https://github.com/phetsims/atomic-interactions/issues/71)
- [ ] [User comments: O-O formation issues](https://github.com/phetsims/atomic-interactions/issues/65)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/atomic-interactions/1.1.0-rc.1/phet/atomic-interactions_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/atomic-interactions/1.1.0-rc.1/phet/atomic-interactions_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/atomic-interactions/1.1.0-rc.1/phet/xhtml/atomic-interactions_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1KffV-UyjeB7GyCcdDooE5Nh02k3QUTlo9MVHT3E89G8/edit#gid=824594451)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fatomic-interactions%2F1.1.0-rc.1%2Fphet%2Fatomic-interactions_en_phet.html%3FlegendsOfLearning)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Edge Performance: dragging the atoms shows a fair amount of lag.  This tends to happen in edge, so I'm leaving it here as a comment.

**Comment by KatieWoe** [comment]
Note: This visual bug was seen on firefox, Mac 10.14.  I took a picture and attempted to reproduce but have been unable to do so.  As such, per @jbphet I have not made an issue.  I will do so if I am able to reproduce.  This comment is to record the instance to make a future issue easier to make.
![img_0678](https://user-images.githubusercontent.com/41024075/49047696-7c24ae80-f195-11e8-98d1-98f1343508e8.jpg)

**Comment by KatieWoe** [comment]
QA is done

**Comment by jbphet** [comment]
Thanks QA team.  I'll follow up on the issues in the next RC.  Closing.
