### ISSUE TITLE
Dev test: Masses And Springs Basics 1.0.0-dev.11

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#220]
Masses-And-Springs-Basics is ready for the first round of dev testing. This dev test should foucus on catching bugs and any sim breaking behavior. This is a Phet brand sim and isn't instrumented for Phet-IO. Please report any bugs to https://github.com/phetsims/masses-and-springs-basics/issues. 

Thanks, @ariel-phet and @arouinfar for the design input. Tagging @ariel-phet to mark priority or add further input.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome, Firefox, and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Issues to Verify</h3>

- [x] Please determine if ghost images of sliders are present on platforms/browsers related to https://github.com/phetsims/masses-and-springs/issues/334

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Masses and Springs Basics](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.11/phet/masses-and-springs-basics_en_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
@Denz1994 the reset all pointer area may need another look.  See https://github.com/phetsims/friction/issues/65

**Comment by Denz1994** [comment]
Opening a new issue related to  https://github.com/phetsims/QA/issues/220#issuecomment-439101227.

**Comment by KatieWoe** [comment]
Major browsers tested.  I'd like to keep this open a bit longer to see if we find anything new, but it looks like most major bugs have been found.  Lowering priority.

**Comment by KatieWoe** [comment]
Didn't see https://github.com/phetsims/masses-and-springs/issues/334 while testing.  QA is done.

**Comment by Denz1994** [comment]
All sim related issues have been addressed. Related issues are either closed, fixed-awaiting-deploy for MAS maintenance release, or require verification in the next dev test. I'll close this issue and open a new issue for a second round of dev testing.
