### ISSUE TITLE
Initial dev testing for Studio redesign

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#224]
In https://github.com/phetsims/phet-io-wrappers/issues/143 we have been redesigning studio, and @zepumph and @chrisklus and I worked on this starting last week.  We deployed a one-off version of graphing-quadratics with the newly redesigned Studio, and it would be good to do some initial cross-platform testing.  As noted in https://github.com/phetsims/phet-io-wrappers/issues/204, this is not expected to work on IE, so that should not be tested in this initial test.

To test:
Make sure Studio launches and behaves properly on our supported platforms except for iPad and IE11.  Perhaps test Chrome first to become familiar with how it should behave, since that platform was used for development and has been more thoroughly vetted.  Also, please reach out to @chrisklus @zepumph or me, @samreid if there are questions about how things should work.  

Some caveats: if your screen is too wide, you won’t see the panel under the sim.  For now, you may just need to reduce the width of your window.  Other TODOs are marked in this issue: https://github.com/phetsims/phet-io-wrappers/issues/143#issuecomment-440859324

The testing URL is password protected, but we are seeing a convention that PhET-iO links are listed in special-ops, so we'll do that for now.  We discussed making this QA repo private, but that hasn't been done (and may not be necessary since PhET-iO links are password protected).

Assigning initially to @ariel-phet for scheduling/prioritization/delegation.  Please let us know if we omitted any information for this issue.

UPDATE: I recalled that in prior issues we put most of the detail in the special-ops issue, but I realized I've done that backwards here.  Please let me know if that's important to correct.

**Comment by KatieWoe** [comment]
Platforms:
- [ ] Win 10 chrome
- [ ] Win 10 firefox
- [ ] Win 10 edge
- [ ] Win 8.1 chrome
- [ ] Win 8.1 firefox
- [ ] Win 7 chrome
- [ ] Win 7 firefox
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 firefox
- [ ] Mac 10.14 safari
- [ ] Mac 10.13 chrome
- [ ] Mac 10.13 firefox
- [ ] Mac 10.13 safari
- [ ] Mac 10.12 chrome
- [ ] Mac 10.12 firefox
- [ ] Mac 10.12 safari
- [ ] Mac 10.11 chrome
- [ ] Mac 10.11 firefox
- [ ] Mac 10.11 safari
- [ ] Mac 10.10 safari
---
- [ ] Chrome OS

**Comment by samreid** [comment]
@ariel-phet said:

> Is this issue relevant anymore? Seems quite stale, and with the new GQ push, perhaps this one should just be closed?

In my opinion, this will be covered in upcoming dev tests.  Tagging @zepumph in case he feels otherwise or wants to save info from this issue.  Closing.
