### ISSUE TITLE
WebGL blending testing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#226]
I made some significant changes in https://github.com/phetsims/energy-skate-park/issues/39, and it would be great to get some testing done to make sure I didn't break anything.

The main buggy case I'd look for would be if something rendered with WebGL is either too light, too dark, or shows the issue in https://github.com/phetsims/energy-skate-park/issues/39 (where the blending is off). Anything else that is different than previous WebGL behavior (different antialiasing/appearance/etc.) would also be good to note.

Internally there are three different types of independent things that could break:

1. WebGL rectangles (e.g. ESPB chart)
2. WebGL images (e.g. ESPB skater)
3. Custom WebGL rendering code (neuron / ESPB things / bending-light wave beam / charges-and-fields voltage background / etc.)

It would be great to get ESPB (and maybe ESP for the original issue) testing done on most available platforms, and also test neuron/bending-light/charges-and-fields.

**Comment by KatieWoe** [comment]
Platforms:
- [ ] Win 10 chrome
- [ ] Win 10 firefox
- [ ] Win 10 edge
---
- [ ] Win 8.1 chrome
- [ ] Win 8.1 firefox
- [ ] Win 8.1 IE
---
- [ ] Win 7 chrome
- [ ] Win 7 firefox
- [ ] Win 7 IE
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 firefox
- [ ] Mac 10.14 safari
---
- [ ] Mac 10.13 chrome
- [ ] Mac 10.13 firefox
- [ ] Mac 10.13 safari
---
- [ ] Mac 10.12 chrome
- [ ] Mac 10.12 firefox
- [ ] Mac 10.12 safari
---
- [ ] Mac 10.11 chrome
- [ ] Mac 10.11 firefox
- [ ] Mac 10.11 safari
---
- [ ] Mac 10.10 safari
---
- [ ] Chrome OS
---
- [ ] iOS 9
- [ ] iOS 10
- [ ] iOS 11
- [ ] iOS 12

**Comment by ariel-phet** [comment]
@KatieWoe Energy Skate Park is still quite away from being complete, but it would be good to get some initial testing on this issue sooner than later. Marking medium priority, but perhaps while doing some other RC testing on a particular platform sprinkle in a bit of this testing.

**Comment by KatieWoe** [comment]
I found this behavior in the graph when changing the mass of the skater in ESPB.  Is this related to this issue?
![energy](https://user-images.githubusercontent.com/41024075/49758248-bb65fb80-fc7b-11e8-9fd2-d2eb3acc13ee.gif)

**Comment by jonathanolson** [comment]
What is the issue in the graph?

**Comment by KatieWoe** [comment]
Potential bar looks buggy and only shows up slightly, kinetic doesn't show up at all.  You have to zoom in quite a lot to even see this much, even though there is a lot of movement.

**Comment by jonathanolson** [comment]
Probably unlikely, but maybe reference this issue if you're going to create an ESPB issue.

**Comment by KatieWoe** [comment]
A few problems were found on iOS 12 12 testing.  Marking that as complete, but please note.

**Comment by KatieWoe** [comment]
Possibly related to https://github.com/phetsims/energy-skate-park/issues/55.  iOS 9 neuron crashed fairly quickly when trying to adjust size and play the stimulate neuron animation at the same time.

**Comment by jbphet** [comment]
>  @jbphet since it might not be webgl related.

That's not quite what I said.  To be clear, I think what I intended to communicate was that on some older iOS devices we might be using the backup renderer, which is canvas, instead of WebGL, since WebGL may not be supported.  As I think about it, I believe I recall that all iOS devices were supporting WebGL, so this is probably **not** happening.

There is a query parameter that can force the use of the backup renderer if you'd like to test this and see if the behavior is different.  I believe it's `webgl=false`.

**Comment by KatieWoe** [comment]
@jbphet didn't see it with webgl=false, but I also didn't see it when I took the querry parameter away, so it may or may not be connected.

**Comment by KatieWoe** [comment]
@jonathanolson checked on all devices.  Possible issues linked or discussed above.

**Comment by jonathanolson** [comment]
Thanks!
