### ISSUE TITLE
RC test: Balancing Chemical Equations 1.2.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#237]
@KatieWoe , @arouinfar, @ariel-phet, Balancing Chemical Equations 1.2.0-rc.1 is ready for RC testing. 

This RC is for `brand=phet` only (no PhET-io, no a11y), and it will not be provided to a client.  The deadline mentioned in https://github.com/phetsims/balancing-chemical-equations/issues/130 is "March", presumably 2019.

Document issues in https://github.com/phetsims/balancing-chemical-equations/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.
- If this is rc.1 please do a memory test.

<h3>Focus and Special Instructions</h3>

According to https://github.com/phetsims/balancing-chemical-equations/issues/130, the primary motivation for this release is ePub and LoL support.  Secondary is to pick up general common-code enhancements, and sim-specific changes identified in "Issues to Verify".

Sim-specific query parameters can be found in [BCEQueryParameters](https://github.com/phetsims/balancing-chemical-equations/blob/master/js/common/BCEQueryParameters.js). `playAll` and `showReward` are both useful for testing.

<h3>Issues to Verify</h3>

- [x] [disable showAnswers in production versions](https://github.com/phetsims/balancing-chemical-equations/issues/118)
- [x] [use AccordionBox](https://github.com/phetsims/balancing-chemical-equations/issues/125)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.2.0-rc.1/phet/balancing-chemical-equations_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.2.0-rc.1/phet/balancing-chemical-equations_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.2.0-rc.1/phet/xhtml/balancing-chemical-equations_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/19RihisZxrUu_Loz_9qNWTeSpiBLOdDikYoJKUHHZDJA/edit#gid=149374087)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe as discussed over Slack, this sim is aiming to be republished by March. Several high priority tests are likely to come down the pipe, but potentially not until next week, so adding this to the cue, to hopefully get it done sooner than later.

**Comment by KatieWoe** [comment]
Memory Tests:
Start: 20.5 MB
1 min: 59.7 MB
2 min: 83.5 MB
3 min: 104 MB
4 min: 122 MB
5 min: 145 MB
6 min: 174 MB
7 min: 202 MB
8 min: 219 MB
9 min: 238 MB
10 min: Memory tab crashed when trying to take snapshot

**Comment by KatieWoe** [comment]
QA is done.
