### ISSUE TITLE
Dev test: Masses And Springs Basics 1.0.0-dev.15

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#241]
@ariel-phet , @arouinfar , MassesAndSpringsBasics/1.0.0-dev.15 is ready for the second round of dev testing. Document issues in https://github.com/phetsims/masses-and-springs-basics/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.

<h3>Focus and Special Instructions</h3>

Please note any doubled images on hSliders when dragging (i.e. spring constant slider) as a result of https://github.com/phetsims/masses-and-springs/issues/334. Also please test for any i18n issues.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Issues to Verify</h3>

- [x] [Ghost image of slider #334](https://github.com/phetsims/masses-and-springs/issues/334)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-dev.15/phet/masses-and-springs-basics_all_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe currently marking as high priority, but that could quickly change if a google sim (like EFAC) gets into the queue

**Comment by lmulhall-phet** [comment]
QA is done!

**Comment by arouinfar** [comment]
Sim is now in RC (see #281), closing.
