### ISSUE TITLE
Dev test for Fractions: Equality 1.0.0-dev.7

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#251]
@amanda-phet, @ariel-phet, @kathy-phet, fractions-equality/1.0.0-dev.7 is ready for dev testing. There is a hard deadline of January 31st (it's a Google sim). Document issues in https://github.com/phetsims/fractions-common/issues and link to this issue.

**Special Note**
@KatieWoe this sim includes "Fraction Matcher" as the game. The game need not be thoroughly tested as very little code for that game has been touched. Fraction matcher will be getting revisited soon, but for this dev test, the game should generally be given a quick run through to make sure nothing is broken, but the game in this particular sim does should not need to be "banged on" very hard.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/fractions-equality/1.0.0-dev.7/phet/fractions-equality_en_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe current top priority

I know @phet-steele has interest in dev testing these sims so also assigning him

**Comment by lmulhall-phet** [comment]
![fraction-suite-memory-test](https://user-images.githubusercontent.com/31285590/50715112-e3593c80-1038-11e9-83e5-697a481186ce.png)

**Comment by lmulhall-phet** [comment]
| **Minute** | **MB** |
|:----------:|:------:|
| 0          | 27.8   |
| 1          | 65.0   |
| 2          | 79.7   |
| 3          | 75.1   |
| 4          | 72.1   |
| 5          | 77.2   |
| 6          | 73.8   |
| 7          | 78.5   |
| 8          | 74.2   |
| 9          | 75.4   |
| 10         | 77     |

**Comment by KatieWoe** [comment]
QA is done

**Comment by jonathanolson** [comment]
Thanks!
