### ISSUE TITLE
Dev test for Fractions: Intro 1.0.0-dev.17

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#252]
@amanda-phet, @ariel-phet, @kathy-phet, fractions-intro/1.0.0-dev.17 is ready for dev testing. There is a hard deadline of January 31st (it's a Google sim). Document issues in https://github.com/phetsims/fractions-common/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/fractions-intro/1.0.0-dev.17/phet/fractions-intro_en_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe current top priority

I know @phet-steele has interest in dev testing these sims so also assigning him

**Comment by lmulhall-phet** [comment]
![fraction-suite-memory-test](https://user-images.githubusercontent.com/31285590/50715099-d5a3b700-1038-11e9-8098-20cabf1ad9fb.png)

**Comment by lmulhall-phet** [comment]
| **Minute** | **MB** |
|:----------:|:------:|
| 0          | 49.5   |
| 1          | 69.1   |
| 2          | 69.5   |
| 3          | 68.7   |
| 4          | 71.5   |
| 5          | 74.9   |
| 6          | 79     |
| 7          | 76.8   |
| 8          | 79.1   |
| 9          | 77.6   |
| 10         | 74.6   |

**Comment by KatieWoe** [comment]
QA is done

**Comment by jonathanolson** [comment]
Thanks!
