### ISSUE TITLE
RC test: Balancing Chemical Equations 1.2.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#255]
@KatieWoe , @arouinfar, @ariel-phet, Balancing Chemical Equations 1.2.0-rc.2 is ready for RC testing. 

This RC is for `brand=phet` only (no PhET-io, no a11y), and it will not be provided to a client.  The deadline mentioned in https://github.com/phetsims/balancing-chemical-equations/issues/130 is "March", presumably 2019.

There is no need to do a full test matrix for this RC.  See the "Issues to Verify" section below. 

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.
- If this is rc.1 please do a memory test.

<h3>Focus and Special Instructions</h3>

According to https://github.com/phetsims/balancing-chemical-equations/issues/130, the primary motivation for this release is ePub and LoL support.  Secondary is to pick up general common-code enhancements, and sim-specific changes identified in "Issues to Verify".

Sim-specific query parameters can be found in [BCEQueryParameters](https://github.com/phetsims/balancing-chemical-equations/blob/master/js/common/BCEQueryParameters.js). `playAll` and `showReward` are both useful for testing.

<h3>Issues to Verify</h3>

- [x] [use AccordionBox](https://github.com/phetsims/balancing-chemical-equations/issues/125)
- [x] [Memory Leak](https://github.com/phetsims/balancing-chemical-equations/issues/134)
- [x] [Smile covers tools when strings are doubled](https://github.com/phetsims/balancing-chemical-equations/issues/138)
- [x] [AccordionBox title bars have a cursor but are not clickable when closed](https://github.com/phetsims/balancing-chemical-equations/issues/139)

There is no need to do a full test matrix for this RC.  These issues are all platform-independent, so it's sufficient to test them on 1 or 2 platforms.  Check these issues off and close them if they are fixed, noting the test platform in the issue. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.2.0-rc.2/phet/balancing-chemical-equations_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.2.0-rc.2/phet/balancing-chemical-equations_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.2.0-rc.2/phet/xhtml/balancing-chemical-equations_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/19RihisZxrUu_Loz_9qNWTeSpiBLOdDikYoJKUHHZDJA/edit#gid=149374087)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome Full
- [ ] Win 10 firefox
- [ ] Win 10 edge Full
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 firefox Full
- [ ] Mac 10.14 safari Full
---
- [ ] iOS 12 Full
- [ ] iOS  10
---
- [ ] Chrome OS
---
- [ ] Win 7 IE Full
- [ ] Win 7 chrome
- [ ] Mac 10.11 safari
- [ ] Mac 10.11 firefox

**Comment by pixelzoom** [comment]
@KatieWoe That quite a few more platforms than are necessary to test these particular issues. But if you have the time, I'll defer to your decision.

**Comment by KatieWoe** [comment]
@pixelzoom If something with higher priority comes in the repo we'll cut it down.  At the moment we have time.  Thanks.

**Comment by KatieWoe** [comment]
@pixelzoom EFAC just came in to the repo.  If you are satisfied with this level of testing, we can call this done.  If you want any other platforms checked, let me know.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe. Based on the platforms that you've tested, I'm comfortable with calling this "done" and moving forward. I'll proceed with publishing 1.2.0.
