### ISSUE TITLE
Setup 6 iPads for Emily

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/QA#256]
@KatieWoe There are 6 new iPads and 6 cases in F925.

Here's the checklist so far of setup items:

- [ ] Unwrap all the iPads and put them in the cases (do not apply a screen protector if one is included)
- [ ] Enable restricted mode to only allow Safari app
- [ ] Prevent Web Content {Allowed Websites Only}
Sites to allow: phet-io, phet, phet-dev, bayes https://support.apple.com/en-us/HT201304

It sounds like the tablets need to be ready by next Tuesday Jan 22. I can help out, if needed.

**Comment by emily-phet** [comment]
iPads are being used this week in PISEC! Assuming this was all completed.
