### ISSUE TITLE
RC test for fractions-mixed-numbers 1.0.0-rc.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#262]
@amanda-phet, @ariel-phet, @kathy-phet, fractions-mixed-numbers/1.0.0-rc.1 is ready for RC testing. There is a hard deadline of January 31st (it's a Google sim). Document issues in https://github.com/phetsims/fractions-common/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.
- If this is rc.1 please do a memory test. JO NOTE: This sim can use a decent amount of memory. I've been resetting all screens first and it is quite stable, but if every level of each game has been interacted with (and fuzzing pulls out hundreds of pieces in the labs/etc.) then it can use a lot of memory.

<h3>Issues to Verify</h3>

- [x] [I18n layout](https://github.com/phetsims/fractions-common/issues/68)
- [x] [Next button for games](https://github.com/phetsims/fractions-common/issues/47)
- [x] [Text cues in games](https://github.com/phetsims/fractions-common/issues/43)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/fractions-mixed-numbers/1.0.0-rc.1/phet/fractions-mixed-numbers_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/fractions-mixed-numbers/1.0.0-rc.1/phet/fractions-mixed-numbers_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/fractions-mixed-numbers/1.0.0-rc.1/phet/xhtml/fractions-mixed-numbers_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1GJ66Lbp_YxnNp74E1sw8LogWZMaWaj8aY3OkFCwNa60/edit#gid=2054964291)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@katie - good to finish off EFAC and RIAW testing, but this is next priority on deck

**Comment by KatieWoe** [comment]
@jonathanolson had iOS 10 crash at least once.  It may be some sort of safari problem on iOS 10.

**Comment by KatieWoe** [comment]
Memory results comparable to dev test results

**Comment by JRomero0613** [comment]
On Windows 10 Edge there are some slight performance issues, mostly related to dragging objects around the screen where the object will be "laggy" and not keep up with the cursor location. The sim is usable otherwise, I'll leave the decision whether to invest effort into increasing performance with the devs.

**Comment by jonathanolson** [comment]
Thanks!

rc.2 switched from Canvas to SVG on Edge, so hopefully it will have improved performance.
