### ISSUE TITLE
Screenshots for Sims to publish soon

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/QA#267]
Several sims are due to publish 1.0 in the next week.  Please show me what screenshots you would like for any of these sims you are responsible for:
- EFC
- WI
- Build a fraction
- Fractions Equality
- Fractions Intro
- Fractions MN

@ariel-phet I'm not certain of the designer for all of these sims.  Am I missing anyone?

**Comment by arouinfar** [comment]
Thanks @KatieWoe. Since the screenshots need to be committed to individual sim repos, it's probably best to keep track of of them there. In general, I lead science sim design, and @amanda-phet leads math sim design. I've assigned the EFAC and WI issues to myself, and Fractions issues to Amanda.
