### ISSUE TITLE
Website: Test Clever Integration

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#275]
We should do some general testing of the Clever Integration as well as regression testing for registration and profile editing.

The following use cases should be fully tested:

- [x] Creating a PhET account from a Clever account
- [x] Signing into a PhET account after account creation
- [x] Linking an existing PhET account to a Clever account
- [x] Linking an existing PhET account where the password has been forgotten. (Make sure the clever account is linked after clicking Forgot Password).
- [x] Accessing PhET with a Student account without being sent to the registration process

We should also perform an end to end test of the following to ensure there are no regressions:

- [x] Creating a new PhET account using the normal registration process (https://ox-dev.colorado.edu/en/register)
- [x] Editing a personal PhET account (https://ox-dev.colorado.edu/en/edit-profile)

To sign up for PhET OR to login to PhET (after sign up) with a Clever account, use the following link: https://clever.com/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fox-dev.colorado.edu%2Fservices%2Fsso%2Fclever&client_id=2bf8d7a0573961a1a456&district_id=5beb1a66876c630001ee2727.  Currently, the "Log in with Clever" link is not useable because we are in "Sandbox" mode. 

Sandbox accounts which can be used to create PhET accounts (on ox-dev) can be found here: http://assets.clever.com/devdocs/cleverusd.zip, or I can look one up quickly if you ping me on Slack.

@KatieWoe - Please let me know if you have any questions.

@ariel-phet - Can you please assign priority?

**Comment by ariel-phet** [comment]
@KatieWoe EFAC and Wave Interference should be the sole focus of QA until they are finished, but this issue and app testing will likely be next.

**Comment by mattpen** [comment]
@KatieWoe - The Edit Profile workflow should be working again.  Also I've fixed the regression in the link existing account use case and finished implementing the forgot password sequence (remember, you must do the entire sequence in one browser session).

**Comment by KatieWoe** [comment]
Completed all tests on Win 10 chrome, firefox, and Internet Explorer, and on Mac 10.14 Safari.  QA is done unless you have any other platforms/tests you want done @mattpen

**Comment by lmulhall-phet** [comment]
@mattpen says this hasn't been deployed yet, but it's OK to close.
