### ISSUE TITLE
RC test: Molecule Polarity 1.0.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#28]
@phet-steele, @emily-phet, @kathy-phet, @ariel-phet:

Molecule Polarity 1.0.0-rc.1 is ready for RC testing.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-rc.1/molecule-polarity_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/molecule-polarity/1.0.0-rc.1/molecule-polarity_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1CeGzSMVfMmnFA7ZQYQM4ekOJXAIS1JKTmcFgdQ3KFGM/edit#gid=2)**

**Issues to Verify**

This is the first RC test, so there are no issues to verify. If you're interested in issues that were found during dev testing, see https://github.com/phetsims/QA/issues/21.

**Please also verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any new issues are found, please note them in https://github.com/phetsims/molecule-polarity/issues and reference this issue.  

**Query Parameters**  

Sim-specific query parameters are documented in [MPQueryParameters.js](https://github.com/phetsims/molecule-polarity/blob/master/js/common/MPQueryParameters.js). Ignore the `realMolecules` query parameter, there is no need to test it.

**Comment by pixelzoom** [comment]
@ariel-phet please prioritize, keeping my vacation schedule in mind (see PhET calendar).

**Comment by ariel-phet** [comment]
@phet-steele this test would be ideal to complete by EOB July 26. If it is completed with no major issues, we be able to publish it before @pixelzoom goes on vacation. 

I know there are several high priority items in the queue (and the Android app will be coming up). If you don't see this test being completed by then, just let me know. It will be fine to finish off while @pixelzoom is on vacation and publish when he returns.

**Comment by phet-steele** [comment]
![greenlight](https://user-images.githubusercontent.com/5863899/28584463-1942c136-712a-11e7-8c75-17fcba2787c8.png)

**Comment by pixelzoom** [comment]
Thank you @phet-steele and QA team.

No issues found, proceeding with publication.
