### ISSUE TITLE
RC test for molecule-shapes-basics 1.2.0-rc.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#280]
@ariel-phet, molecule-shapes-basics/1.2.0-rc.1 is ready for RC testing. Document issues in https://github.com/phetsims/molecule-shapes/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.
- If this is rc.1 please do a memory test.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested, list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>Issues to Verify</h3>

- [ ] [Non-WebGL screenshot reversed](https://github.com/phetsims/molecule-shapes/issues/149)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.0-rc.1/phet/molecule-shapes-basics_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.0-rc.1/phet/molecule-shapes-basics_en_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.0-rc.1/phet/xhtml/molecule-shapes-basics_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1unvmW2TY_gUQy2pA6vlU641qKR_DNgKFEiSOu4iSZ9M/edit#gid=1202900105)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by jonathanolson** [comment]
Main issue for creating this release: https://github.com/phetsims/molecule-shapes-basics/issues/9

**Comment by ariel-phet** [comment]
@katiewoe #277 and #278 should come first, but this sim we also want to republish before March, should be straightforward as just being republished off master.

**Comment by KatieWoe** [comment]
This looks like it may be a memory leak.  @jonathanolson let me know if you want an issue for it.
Start: 59.5
1: 70.6
2: 72.8
3: 74.4
4: 75.8
5: 77.3
6: 78.9
7: 80.2
8: 81.4
9: 82.7
10: 84.0
20: 91.0
30: 98.9
40: 105

**Comment by ariel-phet** [comment]
moving to high priority in the queue

**Comment by KatieWoe** [comment]
QA is done.  Since the app came out and that was the stated date for dropping iOS 9 (and 10 I believe) those two platforms were only tested for performance.

**Comment by jonathanolson** [comment]
This release branch had patches related to https://github.com/phetsims/chipper/issues/720 and https://github.com/phetsims/brand/issues/34 applied since the last RC. This sim should have another RC done, if only to test the brand-related changes briefly.

**Comment by jonathanolson** [comment]
Thanks for testing, I should have rc.2 momentarily.
