### ISSUE TITLE
RC test: Masses and Springs Basics 1.0.0-rc.2

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#281]
@ariel-phet , @arouinfar , Masses and Springs: Basics 1.0.0-rc.2 is ready for RC testing. Document issues in https://github.com/phetsims/masses-and-springs-basics/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR if it not there.
- If this is rc.1 please do a memory test.

<h3>Issues to Verify</h3>

- [ ] [Add Credits](https://github.com/phetsims/masses-and-springs-basics/issues/31)

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-rc.2/phet/masses-and-springs-basics_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-rc.2/phet/masses-and-springs-basics_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.0-rc.2/phet/xhtml/masses-and-springs-basics_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/10S3RzdeJ0O3W98OIMsfGLtRtxF-gLpTarxm0JTXyd34/edit#gid=1132017447)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe there is no hard deadline on this sim, but we would of course appreciate getting it published sooner than later. Graphing Lines sims and Molecule Shapes sims testing take priority over this one since those both have soft deadlines in early March.

**Comment by Denz1994** [comment]
Referencing this [issue](https://github.com/phetsims/masses-and-springs/issues/344#issuecomment-461153279) to fix placeholders in RC branch before production. https://github.com/phetsims/masses-and-springs/issues/344

**Comment by KatieWoe** [comment]
Memory Test Results:
Start: 41.6
1 min: 47.6
2 min: 49.2
3 min: 49.9
4 min: 50.2
5 min: 50.5
6 min: 50.9
7 min: 51.4
8 min: 51.5
9 min: 51.7
10 min: 51.8

**Comment by KatieWoe** [comment]
QA is done

**Comment by Denz1994** [comment]
#296 is now open and issues should be verified there. Closing this issue.
