### ISSUE TITLE
Dev test: Fraction Matcher 1.2.0-dev.10

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#294]
@ariel-phet, @amanda-phet, fraction-matcher/1.2.0-dev.10 is ready for dev testing. Document issues in https://github.com/phetsims/fractions-common/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.

<h3>Focus and Special Instructions</h3>

This new version (compared to the production version) reimplements a lot of things. This should remove some of the old bugs in the previous version, but may introduce new bugs or different/broken behavior. I'd love it if the behavior between this version and the production version could be compared, to make sure there is nothing missing or significantly different. Layout/sizing will be different (it's now using the default layout bounds, and shapes should now have equal area).

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/fraction-matcher/1.2.0-dev.10/phet/fraction-matcher_all_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Memory results
![memresults](https://user-images.githubusercontent.com/41024075/53912193-a0561e00-4015-11e9-95e1-f0311f2dbf0f.jpg)

**Comment by KatieWoe** [comment]
QA is done

**Comment by jonathanolson** [comment]
Thanks! I'll be working on the issues.
