### ISSUE TITLE
Test usability on small phone screens

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/QA#295]
Per @kathy-phet We should test the published sims for usability on smaller mobile devices.  Particular focus should be given to older sims at the top of this list.  This can be done both on the app and safari.  Make sure you check all interactions and look at the pointer areas as well.  Please test published version.
- [x] Build an Atom
- [x] Resistance in a Wire
- [x] Ohm's Law
- [x] Molarity
- [x] Beer's Law Lab
- [x] Balloons and Static Electricity
- [x] Gravity Force Lab
- [x] Concentration
- [x] John Travoltage
- [x] Forces and Motion: Basics
- [x] Friction
- [x] Under Pressure
- [x] Acid-Base Solutions
- [x] Balancing Act
- [x] Fraction Matcher
- [x] Graphing Lines
- [x] Balancing Chemical Equations
- [x] pH Scale
- [x] Color Vision
- [x] Wave on a String
- [x] Area Builder
- [x] pH Scale: Basics
- [x] Faraday's Law
- [x] Energy Skate Park: Basics
- [x] Reactants, Products and Leftovers
- [x] Molecule Shapes: Basics
- [x] Molecule Shapes
- [x] Least-Squares Regression
- [x] Molecules and Light
- [x] Hooke's Law
- [x] Arithmetic
- [x] Bending Light
- [x] Trig Tour
- [x] Neuron
- [x] Isotopes and Atomic Mass
- [x] Function Builder
- [x] Rutherford Scattering
- [x] Charges And Fields
- [x] Atomic Interactions
- [x] Plinko Probability
- [x] Gravity And Orbits
- [x] States of Matter
- [x] States of Matter: Basics
- [x] Make a Ten
- [x] Unit Rates
- [x] Proportion Playground
- [x] Function Builder: Basics
- [x] Graphing Slope-Intercept
- [x] Expression Exchange
- [x] Molecule Polarity
- [x] Projectile Motion
- [x] Pendulum Lab
- [x] Circuit Construction Kit: DC
- [x] Circuit Construction Kit: DC - Virtual Lab
- [x] Capacitor Lab: Basics
- [x] Gene Expression Essentials
- [x] Area Model Introduction
- [x] Area Model Multiplication
- [x] Area Model Decimals
- [x] Area Model Algebra
- [x] Equality Explorer
- [x] Equality Explorer: Basics
- [x] Equality Explorer: Two Variables
- [x] Masses and Springs
- [x] Graphing Quadratics
- [x] Coulomb's Law
- [x] Fractions: Equality
- [x] Build a Fraction
- [x] Fractions: Intro
- [x] Fractions: Mixed Numbers
- [x] Wave Interference
- [x] Energy Forms and Changes

**Comment by KatieWoe** [comment]
Notes on Build an Atom:  Most things could be selected on the 2nd or 3rd try, if not the first.  Trying to select parts of the table in the game were the hardest, but selecting checkboxes and opening boxes also proved difficult.

**Comment by kathy-phet** [comment]
@KatieWoe - I had a few thoughts as you have time for this testing issue. Can you create an issue in each of the appropriate sim repos to document the current pointer areas using screenshots with ?showPointerAreas, and note any troubling spots, or suggestions you have for improvement (bigger pointer areas or swipe to pick up behavior)? For BAM, one thing I noticed when using ?showPointerAreas, was that I could not see the areas for the radio buttons Orbits vs Cloud. Those were the buttons I was finding hard to click on my phone, and it would be good to be able to review and increase those pointer areas, if it is possible to do so. We should look closely at the places where showPointerAreas isn't adding a box/region as it likely means it hasn't been adjusted upwards at all. Thanks!

**Comment by kathy-phet** [comment]
Also - if there isn't a downside to making the pointerArea bigger (e.g. like it overlaps with another pointer area), then its probably best to have it bigger. Like on BalancingAct - the toggle to turn the side posts on/off has an enlarged pointer area, but it seems a bit small to me given that there really isn't anything that would interfere with a larger pointerArea and the only reason you would touch down there would be to toggle the posts.

**Comment by kathy-phet** [comment]
This is a useful, recent, article about touch accuracy - https://uxmovement.com/mobile/optimal-size-and-spacing-for-mobile-buttons/. 
Looks like aiming for a 60 pixel target would be good - if there isn't something preventing that. Their minimum is 42 pixels, but with accuracy impacts. Interesting how button spacing and sizing go together in this article.

**Comment by KatieWoe** [comment]
Template for Issues: 
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:

Screenshots:

**Comment by arouinfar** [comment]
> Can you create an issue in each of the appropriate sim repos to document the current pointer areas using screenshots with ?showPointerAreas, and note any troubling spots, or suggestions you have for improvement 

@kathy-phet do you still want issues created for sims where there aren't any issues found, like https://github.com/phetsims/molarity/issues/78?

**Comment by KatieWoe** [comment]
Sims in italics don't seem to have any issue made for them.

**Comment by kathy-phet** [comment]
@ariel-phet - Question for you on this ... can these tweaks to the sims to address touch area be done as maintenance releases? And if so, it seems like it would potentially fall in the nice-to-be-done before we release 1.3 of the iPhone App category so that they would be bundled in the release. Full new builds from master and RCs on all of these is to big of a lift to get done in that amount of time.

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
@kathy-phet asked in https://github.com/phetsims/QA/issues/295#issuecomment-482739743:
> @ariel-phet - Question for you on this ... can these tweaks to the sims to address touch area be done as maintenance releases? ...

@ariel-phet asked me to comment on this.  It would be possible to do in maintenance releases, but relatively expensive.  I've had to made changes to core UI components in common code, and patching them in release branches will not be straightforward.  And I have yet to change a pointer area that I think will significantly improve the UX of sims on a phone.

**Comment by ariel-phet** [comment]
Considering such changes are likely amenable to a maintenance release, closing
