### ISSUE TITLE
RC Testing for Maintenance Release--Brands Logo update R to TM

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#299]
For more details and a list of RC links to be tested, go to https://github.com/phetsims/special-ops/issues/131. This issue has been opened to track assignment and prioritization. A synopsis of this maintenance release is below: 

> For phetsims/brand#34 @jonathanolson and @Denz1994 performed a maintenance release to convert all ® logos to ™

Assigning to @ariel-phet for prioritization.

**Comment by Denz1994** [comment]
Holding off on assignment until links for sims currently in RC are provided.

**Comment by Denz1994** [comment]
Separate issues will be created in QA for each sim that is currently in RC testing. See https://github.com/phetsims/QA/issues/298#issuecomment-474568490 (EFAC) and https://github.com/phetsims/QA/issues/296#issuecomment-474936060 (MASB) as examples. 

This shouldn't block testing for currently available links (sims not in RC testing).

Assigning to @ariel-phet for prioritization.

**Comment by ariel-phet** [comment]
@Denz1994 I know this is an important maintenance release to @kathy-phet marking as top priority.

I am assuming testing will involve mainly just spot checking each sim, you and @jonathanolson will probably want to provide testing instruction for QA and a checklist of sims

**Comment by Denz1994** [comment]
From the initial [comment](https://github.com/phetsims/QA/issues/299#issue-423549165): 

> For more details and a list of RC links to be tested, go to phetsims/special-ops#131.

A separate issue was created in special-ops for reasons described [here](https://github.com/phetsims/special-ops/issues/131#issue-423546064).

**Comment by KatieWoe** [comment]
QA is done.  See main issue for more details.

**Comment by jonathanolson** [comment]
Finished the maintenance release for this (all production deployed, and I verified brand changes for every production sim)
