### ISSUE TITLE
Website QA: Team Page translatability

### ISSUE THREAD

**Issue by phet-steele** [phetsims/QA#3]
@phet-steele - I've made the "Our Team" page translatable and it required a significant retooling of the entire Team Member process.  Could you please schedule a QA test for the Team Page?  The proposed changes are currently deployed to https://ox-dev.colorado.edu/en/about/team

The processes that were affected include:
- [x] Creating a new Team Member
- [x] Deleting a Team Member
- [x] Editing an existing Team Member
- [ ] Translating the Team Page
- [ ] Previewing a translation of the Team Page

Everything should be translatable except for the names of people and companies.

**Comment by JRomero0613** [comment]
I'm not sure if there is anything we can do on our end to fix this issue but when using the drop down menu all the way at the bottom of the website and selecting a different language the drop down menu still has the text "Choose one" showing. I feel that this should read out "Choose one" in whatever language has been selected. This is a pretty small issue so I'm not sure if a fix is required.

**Comment by lmulhall-phet** [comment]
I'm going through old issues assigned to me and this is one of them.

I'm not sure how to translate the team member page.

This is what the translation utility looks like now:

![Screen Shot 2019-07-24 at 12 12 42 PM](https://user-images.githubusercontent.com/31285590/61817791-95592a00-ae0c-11e9-8a37-e0b17feb9285.png)

I can translate the about page, but I don't see how/where I can translate the team member page.

@mattpen, does this issue still need to be worked on? If so, how does one translate the team member page. (There might be something I'm overlooking and if this is case, I apologize.)

**Comment by mattpen** [comment]
@lmulhall-phet - this is not currently active.  I'll have to reenable this in order for you to test it.

**Comment by lmulhall-phet** [comment]
I'm happy to test if/when you need it.

**Comment by mattpen** [comment]
Removing assignment due to low priority.

**Comment by ariel-phet** [comment]
This issue has gone quite stale. Closing
