### ISSUE TITLE
Spot Check: Build an Atom 1.6.0-rc.4

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#30]
From #27, the remaining issue was phetsims/build-an-atom#170 involving an issue with the touch areas on arrow buttons for some challenges in the game.  @phet-steele can you please verify that it is fixed in 

http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.6.0-rc.4/build-an-atom_en.html

Once verified, this sim can be redeployed and we can deploy as our first sim to Legends of Learning.

**Comment by phet-steele** [comment]
Verified on Win 10 Chrome 60.0.3112.78.
