### ISSUE TITLE
Dev Test: Ohms Law 1.4.0-dev.29

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#303]
As a follow up to #289, it would be good to verify that the remaining issues found have been fixed before the next release. Sorry it has been a while since the last test. Please verify that these issues have been fixed, and test the simulation to make sure that no knew issues have crept in.

**[Link to sim](https://phet-dev.colorado.edu/html/ohms-law/1.4.0-dev.29/phet/ohms-law_en_phet.html
)**
- [x] [Performance on iPad Air 2](https://github.com/phetsims/ohms-law/issues/132) (Can you please compare against performance in this version? [dev.26](https://phet-dev.colorado.edu/html/ohms-law/1.4.0-dev.26/phet/ohms-law_en_phet.html))
- [x] [Mobile VO allows gesture input](https://github.com/phetsims/ohms-law/issues/131)

**Comment by KatieWoe** [comment]
@ariel-phet for priority

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Thank you @KatieWoe!
