### ISSUE TITLE
Dev Test: Circuit Construction Kit: DC 1.0.0-dev.129 (and virtual lab)

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#31]
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.129/circuit-construction-kit-dc_en.html
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc-virtual-lab/1.0.0-dev.8/circuit-construction-kit-dc-virtual-lab_en.html

These versions were prepared in https://github.com/phetsims/circuit-construction-kit-dc/issues/109.  They are based on the same code, but VL is supposed to have no 1st screen and no virtual ammeter.

We tested a bit previously to get a good version ready for AAPT, but this will be the first formal dev test.  @ariel-phet can you please prioritize, schedule and delegate?  Also, please let me know if this issue requires any more information or issue labels.

Please test on the following:

- [ ] iPad 2
- [ ] iPad Air
- [ ] Windows Chrome
- [ ] Mac Safari

If there is a performance type issue on the iPad2, please comment if it also exists on the Air.

UPDATE July 31, 3:59PM by @samreid.  For https://github.com/phetsims/circuit-construction-kit-dc/issues/124 we published new dev versions with wire icons.  I updated the test versions to dev.129 and dev.8

**Comment by ariel-phet** [comment]
@phet-steele making this current top priority (along with android app testing)

**Comment by samreid** [comment]
We have more changes on the way for https://github.com/phetsims/circuit-construction-kit-dc/issues/125 and https://github.com/phetsims/circuit-construction-kit-dc/issues/111

**Comment by samreid** [comment]
I'll close this issue and work on the aforementioned issues.  When they are fixed, I'll open a new issue for QA testing.
