### ISSUE TITLE
Dev test: Circuit Construction Kit: DC 1.1.0-dev.3

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#311]
@ariel-phet circuit-construction-kit-dc/1.1.0-dev.3 is ready for dev testing. @kathy-phet wants to share this with a client around the end of April.  Please document issues in https://github.com/phetsims/circuit-construction-kit-common/issues and link to 
this issue.

Assigning @ariel-phet for prioritization, and to update the General Dev Test Platforms list.
@ariel-phet, do you want any others issues addressed or features added before proceeding with dev test?  Please also look through this template and update anything you can see that needs to be updated, and please label accordingly.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.

<h3>Focus and Special Instructions</h3>

The new component is the Fuse, which appears on the 2nd page of the carousel.  The fuse should be thoroughly tested,
but the rest of the sim needs to be tested as well to make sure nothing was broken during the last several months.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

These issues should have the "status:fixed-pending-testing" label. Check these issues off and close them if they are
fixed. Otherwise, post a comment in the issue saying that it wasn't fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.1.0-dev.3/phet/circuit-construction-kit-dc_en_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
Current top testing priority

**Comment by KatieWoe** [comment]
QA is done with the dev test.

**Comment by KatieWoe** [comment]
https://github.com/phetsims/QA/issues/314 is out so I'm closing this.
