### ISSUE TITLE
Dev test: Circuit Construction Kit: DC 1.1.0-dev.7

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#314]
@ariel-phet, circuit-construction-kit-dc/1.1.0-dev.7 is ready for dev testing. I'm not certain about deadlines.  Document issues in https://github.com/phetsims/circuit-construction-kit-common/issues and link to this issue.  I expect we will want to test "DC: Virtual Lab" at the same time, so I have published a dev version and linked it below.  @ariel-phet please correct me if it should not be tested now, or if it should have a separate issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.

<h3>Focus and Special Instructions</h3>

Prior dev testing was completed in https://github.com/phetsims/QA/issues/311.  Since then, we've also worked on:

* Improvements for hit areas for the accordion box button, see https://github.com/phetsims/circuit-construction-kit-common/issues/491
* Improved readout for the fuse values: https://github.com/phetsims/circuit-construction-kit-common/issues/480
* Reversing the red/black probes on the voltmeter, see https://github.com/phetsims/circuit-construction-kit-common/issues/482

@ariel-phet requested a "sanity" dev test one one or two platforms before RC (like chrome and iPad)".

For each discovered issue, please compare to the published version and report whether the problem is new or pre-existing in the published version.

<h3>General Dev Test Platforms</h3>

- [x] Latest Chrome on Win
- [x] Latest iOS, Mobile Safari

<h3>Link(s)</h3>

- **[CCK:DC](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.1.0-dev.7/phet/circuit-construction-kit-dc_en_phet.html)**
- **[CCK-DC-virtual lab](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.1.0-dev.1/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
Current top priority

**Comment by ariel-phet** [comment]
And yes, @samreid makes sense to publish both

**Comment by KatieWoe** [comment]
QA is done.

**Comment by samreid** [comment]
Thanks @KatieWoe!  All issues tracked elsewhere, closing.
