### ISSUE TITLE
Dev Test: Resistance In A Wire 1.3.0-phetiodev.9

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#32]
@emily-phet

This a test for the newly phet-io instrumented sim, as well as major refactoring and layout changes. This dev test is in preparation for a dev release to be delivered to sonification collaborators to add accessibility to RIAW, so please focus on phet-io features.

This test is very similar to https://github.com/phetsims/QA/issues/24 in that this sim will be delivered to 3rd parties, but for development purposes only.

http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-phetiodev.9/wrappers/index/

Please check that these issues are solved:

- [x] https://github.com/phetsims/resistance-in-a-wire/issues/28
- [x] https://github.com/phetsims/resistance-in-a-wire/issues/91

There are some know layout problems currently like https://github.com/phetsims/ohms-law/issues/68 (effects RIAW too). The focus of this test is for functionality and logic testing. 
@emily-phet and I spoke about this release, and the goal would be to have something to deliver by next Tuesday. I am out of town until Friday.

@ariel-phet please assign and prioritize

**Comment by ariel-phet** [comment]
@phet-steele this should be high priority given the proposed timeline (but App testing still takes precedence)

**Comment by zepumph** [comment]
@phet-steele talked about this, and he didn't find anything but the maxWidth bug. Here is another link to parooze through. If all looks good. I'll give it out to accessibility folks.

**Comment by phet-steele** [comment]
@zepumph, phetiodev.10 checks out, but I made a few commits to fix the QA credits that would be good to pick up.

**Comment by zepumph** [comment]
Alright I picked up these changes. Thanks for the help @phet-steele 

http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-phetiodev.11/wrappers/index/

Closing
