### ISSUE TITLE
issues with “status:ready-for-qa” label 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#324]
[rc-test-template.md](https://github.com/phetsims/QA/blob/master/issue-templates/rc-test-template.md) currently refers to “status:ready-for-QA” label in multiple places.  The label is actually “status:ready-for-qa” (lowercase).   Since we have multiple “QA:*” labels, perhaps the label should be changed, so that we're using uppercase everywhere. If not, then the template should be changed to refer to “status:ready-for-qa”.

**Comment by pixelzoom** [comment]
This is inconsistency is not a big deal for GitHub searches, because they are apparently case insensitive.  E.g. "is:issue label:status:ready-for-QA" and "is:issue label:status:ready-for-qa" will find the same issues.

**Comment by KatieWoe** [comment]
Since it is already lowercase, it should be fine to stick with that.  I'll adjust the templates/book.  Thanks for pointing out.

**Comment by KatieWoe** [comment]
Done in above commit.  Closing
