### ISSUE TITLE
specify which iFrame link to include in rc-test-template.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#325]
[rc-test-template.md](https://github.com/phetsims/QA/blob/master/issue-templates/rc-test-template.md) currently contains this markdown:

```
- **[Simulation](all_phet_link)**
- **[iFrame](link)**
```

For Simulation, it explicitly asks for the "all_phet_link".   But it does not specify for iFrame, and there are 2 choices (en_iframe_phet.html, all_iframe_phet.html).  I'm guessing that you want all_iframe_phet.html. But please specify which iFrame link to include.

**Comment by KatieWoe** [comment]
It should also be all.  I'll adjust the template.

**Comment by KatieWoe** [comment]
Done in above commit.  Closing
