### ISSUE TITLE
Recent versions of sims on phet-dev don't load on iPad Pro

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/QA#329]
I tethered my iPad Pro while trying to load pH Scale Basics 1.3.0-rc.1. There are five errors in the console:

```
[Error] SecurityError: The operation is insecure.
	getForString (ph-scale-basics_all_phet.html:996:850)
	getAllForString (ph-scale-basics_all_phet.html:996:1026)
	(anonymous function) (ph-scale-basics_all_phet.html:997:2719)
	Global Code (ph-scale-basics_all_phet.html:997:4919)
[Error] TypeError: undefined is not an object (evaluating 'phet.chipper.queryParameters["phet-app"]')
	(anonymous function) (ph-scale-basics_all_phet.html:999:340)
	Global Code (ph-scale-basics_all_phet.html:999:3532)
[Error] TypeError: undefined is not an object (evaluating 'window.phet.chipper.queryParameters.gameUpLogging')
	(anonymous function) (ph-scale-basics_all_phet.html:1001:100)
	Global Code (ph-scale-basics_all_phet.html:1001:898)
[Error] TypeError: undefined is not an object (evaluating 'phet.chipper.queryParameters.strings')
	(anonymous function) (ph-scale-basics_all_phet.html:1010)
	Global Code (ph-scale-basics_all_phet.html:1036)
[Error] TypeError: window.phet.chipper.strings.get is not a function. (In 'window.phet.chipper.strings.get("PH_SCALE/choice.water")', 'window.phet.chipper.strings.get' is undefined)
	(anonymous function) (ph-scale-basics_all_phet.html:1037:528947)
	u (ph-scale-basics_all_phet.html:1037:3676)
	l (ph-scale-basics_all_phet.html:1037:2481)
	u (ph-scale-basics_all_phet.html:1037:3575)
	l (ph-scale-basics_all_phet.html:1037:2481)
	u (ph-scale-basics_all_phet.html:1037:3575)
	l (ph-scale-basics_all_phet.html:1037:2481)
	u (ph-scale-basics_all_phet.html:1037:3575)
	l (ph-scale-basics_all_phet.html:1037:2481)
	u (ph-scale-basics_all_phet.html:1037:3575)
	l (ph-scale-basics_all_phet.html:1037:2481)
	u (ph-scale-basics_all_phet.html:1037:3575)
	l (ph-scale-basics_all_phet.html:1037:2481)
	u (ph-scale-basics_all_phet.html:1037:3575)
	(anonymous function) (ph-scale-basics_all_phet.html:1037:4047)
```

We can load these same sims on our iPad Air 2's running the same iOS version, 12.3.1. I will check to see if they are throwing any errors.

@ariel-phet, I'm not sure who to assign to investigate, so I'll leave that to you.

**Comment by zepumph** [comment]
Developer meeting discussion:
* Let's try the en version of the sim and see if it behaves differently.
* If this is different perhaps we need to adjust the issue template to point to the en version.
* @KatieWoe to ask @phet-steele why we use the all HTML file for testing. (let's make an issue)
* Should we get an iPad Pro? 
  * AP: we could, but it's kinda expensive, let's see if we really need it.

**Comment by zepumph** [comment]
@lmulhall-phet please "kick it to @ariel-phet" with whatever you find in the en version.

**Comment by lmulhall-phet** [comment]
Settings > Safari > Privacy & Security > Prevent Cross-Site Tracking needs to be off. If it's on, you'll get the above errors. @zepumph, does it make sense that having that setting on would produce those errors?

**Comment by lmulhall-phet** [comment]
Might be a good idea to add this to the Help Center.

**Comment by ariel-phet** [comment]
@lmulhall-phet can you please see if the *_en_phet.html files of recent sims also produce this error on your iPad?

There really shouldn't be a difference between the _en_phet.html and _all_phet.html except for the inclusion of strings and the acceptance of a query parameter. But perhaps the way we have done this query parameter is causing errors.

Can you check the en_phet.html files before we move ahead with the next step?

**Comment by lmulhall-phet** [comment]
Sorry, I forgot to write that I checked the en version. Yes, the en version produces the same error, but the problem stems from Safari settings, not the iPad or the sims.

**Comment by KatieWoe** [comment]
Since this seems solved, is it alright if I close @ariel-phet?

**Comment by ariel-phet** [comment]
@KatieWoe I actually want to discuss at dev meeting, lets leave open

**Comment by samreid** [comment]
@lmulhall-phet @KatieWoe or @ariel-phet can you please elaborate on what "Prevent Cross-Site Tracking" means, why it impacts our sims, and why users may have turned that on?

**Comment by KatieWoe** [comment]
Best explanation I found for what it is:
>Social media sites often put Share, Like, or Comment buttons on other websites. These buttons can be used to track your web browsing—even if you don’t use them. Safari blocks that tracking. If you still want to use the buttons, you’ll be asked for your permission to allow the site to see your activities on the other websites.

No idea why it would impact our sims.
I looked on my phone, and it seemed to be on by default, but seemed to be off by default on one of our iPads.  For some reason, I didn't seem to get these errors with either device while it was on.

**Comment by jonathanolson** [comment]
I'll at a minimum try to make sure this doesn't error out (if possible). Ideally we'll find a way to get query string information in that situation.

**Comment by samreid** [comment]
`QueryStringMachine. getForString` is where the first error is thrown.  It is a simple method, maybe it would be easy to create an isolated test case to try to understand exactly what is causing the problem.

**Comment by lmulhall-phet** [comment]
I may have found something. Checking the "Block all cookies" checkbox in Safari on my MacBook will produce the same errors and the same behavior, which makes me wonder if I made a mistake in thinking it was the "Prevent cross-site tracking" preference that was causing the problem. I could have sworn that having "Prevent cross-site tracking" off solved the problem and it didn't have to do with the cookies preference. I'll take a look at my iPad tonight.

**Comment by jonathanolson** [comment]
I noticed there was a QueryStringMachine error if "Block all cookies" was enabled on Safari desktop. Patched above so that it doesn't prevent loading of the sim.

**Comment by jonathanolson** [comment]
"Prevent Cross-Site Tracking" is enabled on both my phone/macbook, and it hasn't prevented running sims at all. From its description, it seems to be a preventative measure for browser fingerprinting, which should not be related to query string handling.

**Comment by jonathanolson** [comment]
I'm not finding any other security/privacy settings that I can enable to break things, so I'm curious if the localStorage patch above changes the iPad Pro behavior.

Being able to debug live (with the device in person, or at least remote but viewable) would be quite helpful for this situation.

@lmulhall-phet do you mind testing off of master? Let me know if I should deploy a dev version for testing.

**Comment by lmulhall-phet** [comment]
@jonathanolson, sure we can try that. I bring my iPad to work now, so we can do the test whenever you're ready to deploy a dev version.

**Comment by lmulhall-phet** [comment]
I think @jonathanolson integrated the changes into master. I mistakenly thought he needed to deploy a dev version. Sorry about that. I checked a few sims and none of them failed to load. Closing.
