### ISSUE TITLE
Dev Test: Circuit Construction Kit: DC 1.0.0-dev.135 (and virtual lab)

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#33]
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.135/circuit-construction-kit-dc_en.html
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc-virtual-lab/1.0.0-dev.9/circuit-construction-kit-dc-virtual-lab_en.html

These versions are based on the same code, but VL is supposed to have no 1st screen and no virtual ammeter.

We tested a bit previously to get a good version ready for AAPT, but this will be the first formal dev test (after #31 was abandoned).

Please test on the following:

- [x] iPad 2
- [x] iPad Air
- [x] Windows Chrome
- [x] Mac Safari
- [x] LoL

If there is a performance type issue on the iPad2, please comment if it also exists on the Air.

I'll assign the same priority and assignees as @ariel-phet did in #31

**Comment by samreid** [comment]
@kathy-phet also requested to check this in the legends of learning harness.

**Comment by phet-steele** [comment]
@kathy-phet @samreid we can finish this dev.

**Comment by samreid** [comment]
Thanks @phet-steele, we'll proceed on the code review and possibly updating the prototype.
