### ISSUE TITLE
Why are sims behaving differently on iPad Pro?

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/QA#330]
Kathy recently received an email (please add to issue @oliver-phet) detailing an issue a user found on the new version of the iPad Pro. I recently had an issue where I couldn't load recent (how recent?) versions of sims from phet-dev.colorado.edu on my iPad Pro. See https://github.com/phetsims/QA/issues/329.

I'll look into how recent the versions need to be for the sims not to load.

I think it would be a good idea do testing on iPad Pro before sims are published. Don't know how the logistics of this will work; maybe we should add iPad Pro to the testing matrix, @KatieWoe.

**Comment by oliver-phet** [comment]
From kathy:
> iPad Pro having "unreliable touch and drag responsiveness" using the sims directly on the website.

**Comment by KatieWoe** [comment]
This seems handled.  Tested on devices in apple store and by @lmulhall-phet.  Closing for now.
