### ISSUE TITLE
Maintenance Release: phet-io dependencies

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#332]
@jonathanolson @ariel-phet @kathy-phet @samreid @KatieWoe we are ready for RC testing for the maintenance release regarding phet-io dependencies.
Original issue: https://github.com/phetsims/chipper/issues/661

Overall testing criteria:
* For phet and phet-io branded sims, we just need basic MR testing. I think that is just playing with each link for X seconds or something. You know better than I do here.
* There was one extra lab book wrapper link added for CLB 1.6 phet-io. Please do the same for that one.

area-model-algebra 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [area-model-algebra 1.0.6-rc.1](https://phet-dev.colorado.edu/html/area-model-algebra/1.0.6-rc.1/phet/area-model-algebra_en_phet.html)

area-model-decimals 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [area-model-decimals 1.0.6-rc.1](https://phet-dev.colorado.edu/html/area-model-decimals/1.0.6-rc.1/phet/area-model-decimals_en_phet.html)

area-model-introduction 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [area-model-introduction 1.0.6-rc.1](https://phet-dev.colorado.edu/html/area-model-introduction/1.0.6-rc.1/phet/area-model-introduction_en_phet.html)

area-model-multiplication 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [area-model-multiplication 1.0.6-rc.1](https://phet-dev.colorado.edu/html/area-model-multiplication/1.0.6-rc.1/phet/area-model-multiplication_en_phet.html)

balancing-chemical-equations 1.2 (https://github.com/phetsims/chipper/issues/661)

- [x] [balancing-chemical-equations 1.2.3-rc.1](https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.2.3-rc.1/phet/balancing-chemical-equations_en_phet.html)

balloons-and-static-electricity 1.3-phetio (https://github.com/phetsims/chipper/issues/661)

- [x] [balloons-and-static-electricity 1.3.10-rc.1 phet-io](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.3.10-rc.1/balloons-and-static-electricity_en-phetio.html?phetioStandalone)
- [ ] [balloons-and-static-electricity 1.3.10-rc.1 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.3.10-rc.1/wrappers/instance-proxies/instance-proxies.html?sim=balloons-and-static-electricity&relativeSimPath)

balloons-and-static-electricity 1.4 (https://github.com/phetsims/chipper/issues/661)

- [x] [balloons-and-static-electricity 1.4.7-rc.1](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.4.7-rc.1/phet/balloons-and-static-electricity_en_phet.html)

build-a-fraction 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [build-a-fraction 1.0.4-rc.1](https://phet-dev.colorado.edu/html/build-a-fraction/1.0.4-rc.1/phet/build-a-fraction_en_phet.html)

build-an-atom 1.5-phetio (https://github.com/phetsims/chipper/issues/661)

- [x] [build-an-atom 1.5.12-rc.1 phet-io](https://phet-dev.colorado.edu/html/build-an-atom/1.5.12-rc.1/build-an-atom_en-phetio.html?phetioStandalone)
- [ ] [build-an-atom 1.5.12-rc.1 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/build-an-atom/1.5.12-rc.1/wrappers/instance-proxies/instance-proxies.html?sim=build-an-atom&relativeSimPath)

build-an-atom 1.6 (https://github.com/phetsims/chipper/issues/661)

- [x] [build-an-atom 1.6.7-rc.1](https://phet-dev.colorado.edu/html/build-an-atom/1.6.7-rc.1/build-an-atom_en.html)

capacitor-lab-basics 1.5 (https://github.com/phetsims/chipper/issues/661)

- [x] [capacitor-lab-basics 1.5.7-rc.1](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.5.7-rc.1/capacitor-lab-basics_en.html)

capacitor-lab-basics 1.6 (https://github.com/phetsims/chipper/issues/661)

- [x] [capacitor-lab-basics 1.6.13-rc.1](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.13-rc.1/phet/capacitor-lab-basics_en_phet.html)
- [x] [capacitor-lab-basics 1.6.13-rc.1 phet-io](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.13-rc.1/phet-io/capacitor-lab-basics_all_phet-io.html?phetioStandalone)
- [ ] [capacitor-lab-basics 1.6.13-rc.1 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.13-rc.1/phet-io/wrappers/instance-proxies/instance-proxies.html?sim=capacitor-lab-basics&relativeSimPath)
- [x] [capacitor-lab-basics 1.6.13-rc.1 phet-io Lab Book](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.13-rc.1/phet-io/wrappers/lab-book/lab-book.html?sim=capacitor-lab-basics&relativeSimPath)

circuit-construction-kit-dc 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [circuit-construction-kit-dc 1.0.8-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.0.8-rc.1/circuit-construction-kit-dc_en.html)

circuit-construction-kit-dc-virtual-lab 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [circuit-construction-kit-dc-virtual-lab 1.0.8-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.0.8-rc.1/circuit-construction-kit-dc-virtual-lab_en.html)

coulombs-law 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [coulombs-law 1.0.3-rc.1](https://phet-dev.colorado.edu/html/coulombs-law/1.0.3-rc.1/phet/coulombs-law_en_phet.html)

energy-forms-and-changes 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [energy-forms-and-changes 1.0.5-rc.1](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.0.5-rc.1/phet/energy-forms-and-changes_en_phet.html)

equality-explorer 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [equality-explorer 1.0.6-rc.1](https://phet-dev.colorado.edu/html/equality-explorer/1.0.6-rc.1/phet/equality-explorer_en_phet.html)

equality-explorer-basics 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [equality-explorer-basics 1.0.6-rc.1](https://phet-dev.colorado.edu/html/equality-explorer-basics/1.0.6-rc.1/phet/equality-explorer-basics_en_phet.html)

equality-explorer-two-variables 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [equality-explorer-two-variables 1.0.6-rc.1](https://phet-dev.colorado.edu/html/equality-explorer-two-variables/1.0.6-rc.1/phet/equality-explorer-two-variables_en_phet.html)

expression-exchange 1.1 (https://github.com/phetsims/chipper/issues/661)

- [x] [expression-exchange 1.1.7-rc.1](https://phet-dev.colorado.edu/html/expression-exchange/1.1.7-rc.1/expression-exchange_en.html)

forces-and-motion-basics 2.3 (https://github.com/phetsims/chipper/issues/661)

- [x] [forces-and-motion-basics 2.3.10-rc.1](https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.3.10-rc.1/forces-and-motion-basics_en.html)

fractions-equality 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [fractions-equality 1.0.4-rc.1](https://phet-dev.colorado.edu/html/fractions-equality/1.0.4-rc.1/phet/fractions-equality_en_phet.html)

fractions-intro 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [fractions-intro 1.0.4-rc.1](https://phet-dev.colorado.edu/html/fractions-intro/1.0.4-rc.1/phet/fractions-intro_en_phet.html)

fractions-mixed-numbers 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [fractions-mixed-numbers 1.0.4-rc.1](https://phet-dev.colorado.edu/html/fractions-mixed-numbers/1.0.4-rc.1/phet/fractions-mixed-numbers_en_phet.html)

friction 1.5 (https://github.com/phetsims/chipper/issues/661)

- [x] [friction 1.5.4-rc.1](https://phet-dev.colorado.edu/html/friction/1.5.4-rc.1/phet/friction_en_phet.html)

gene-expression-essentials 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [gene-expression-essentials 1.0.8-rc.1](https://phet-dev.colorado.edu/html/gene-expression-essentials/1.0.8-rc.1/gene-expression-essentials_en.html)

graphing-lines 1.3 (https://github.com/phetsims/chipper/issues/661)

- [x] [graphing-lines 1.3.3-rc.1](https://phet-dev.colorado.edu/html/graphing-lines/1.3.3-rc.1/phet/graphing-lines_en_phet.html)

graphing-quadratics 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [graphing-quadratics 1.0.3-rc.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.3-rc.1/phet/graphing-quadratics_en_phet.html)

graphing-slope-intercept 1.1 (https://github.com/phetsims/chipper/issues/661)

- [x] [graphing-slope-intercept 1.1.3-rc.1](https://phet-dev.colorado.edu/html/graphing-slope-intercept/1.1.3-rc.1/phet/graphing-slope-intercept_en_phet.html)

isotopes-and-atomic-mass 1.1 (https://github.com/phetsims/chipper/issues/661)

- [x] [isotopes-and-atomic-mass 1.1.1-rc.1](https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.1-rc.1/phet/isotopes-and-atomic-mass_en_phet.html)

john-travoltage 1.4-phetio (https://github.com/phetsims/chipper/issues/661)

- [x] [john-travoltage 1.4.10-rc.1 phet-io](https://phet-dev.colorado.edu/html/john-travoltage/1.4.10-rc.1/john-travoltage_en-phetio.html?phetioStandalone)
- [ ] [john-travoltage 1.4.10-rc.1 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/john-travoltage/1.4.10-rc.1/wrappers/instance-proxies/instance-proxies.html?sim=john-travoltage&relativeSimPath)

john-travoltage 1.5 (https://github.com/phetsims/chipper/issues/661)

- [x] [john-travoltage 1.5.5-rc.1](https://phet-dev.colorado.edu/html/john-travoltage/1.5.5-rc.1/phet/john-travoltage_en_phet.html)

masses-and-springs 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [masses-and-springs 1.0.4-rc.1](https://phet-dev.colorado.edu/html/masses-and-springs/1.0.4-rc.1/phet/masses-and-springs_en_phet.html)

masses-and-springs-basics 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [masses-and-springs-basics 1.0.3-rc.1](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.3-rc.1/phet/masses-and-springs-basics_en_phet.html)

molarity 1.4 (https://github.com/phetsims/chipper/issues/661)

- [x] [molarity 1.4.6-rc.1](https://phet-dev.colorado.edu/html/molarity/1.4.6-rc.1/phet/molarity_en_phet.html)
- [x] [molarity 1.4.6-rc.1 phet-io](https://phet-dev.colorado.edu/html/molarity/1.4.6-rc.1/phet-io/molarity_all_phet-io.html?phetioStandalone)
- [x] [molarity 1.4.6-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molarity/1.4.6-rc.1/phet-io/wrappers/studio/studio.html?sim=molarity&relativeSimPath)

molecule-polarity 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [molecule-polarity 1.0.9-rc.1](https://phet-dev.colorado.edu/html/molecule-polarity/1.0.9-rc.1/molecule-polarity_en.html)

molecule-shapes 1.2 (https://github.com/phetsims/chipper/issues/661)

- [x] [molecule-shapes 1.2.2-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes/1.2.2-rc.1/phet/molecule-shapes_en_phet.html)

molecule-shapes-basics 1.2 (https://github.com/phetsims/chipper/issues/661)

- [x] [molecule-shapes-basics 1.2.2-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.2-rc.1/phet/molecule-shapes-basics_en_phet.html)

molecules-and-light 1.4 (https://github.com/phetsims/chipper/issues/661)

- [x] [molecules-and-light 1.4.7-rc.1](https://phet-dev.colorado.edu/html/molecules-and-light/1.4.7-rc.1/molecules-and-light_en.html)

pendulum-lab 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [pendulum-lab 1.0.9-rc.1](https://phet-dev.colorado.edu/html/pendulum-lab/1.0.9-rc.1/pendulum-lab_en.html)

plinko-probability 1.1 (https://github.com/phetsims/chipper/issues/661)

- [x] [plinko-probability 1.1.12-rc.1](https://phet-dev.colorado.edu/html/plinko-probability/1.1.12-rc.1/plinko-probability_en.html)

projectile-motion 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [projectile-motion 1.0.9-rc.1](https://phet-dev.colorado.edu/html/projectile-motion/1.0.9-rc.1/projectile-motion_en.html)

proportion-playground 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [proportion-playground 1.0.9-rc.1](https://phet-dev.colorado.edu/html/proportion-playground/1.0.9-rc.1/proportion-playground_en.html)

reactants-products-and-leftovers 1.2 (https://github.com/phetsims/chipper/issues/661)

- [x] [reactants-products-and-leftovers 1.2.4-rc.1](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.2.4-rc.1/phet/reactants-products-and-leftovers_en_phet.html)

resistance-in-a-wire 1.3-phetio (https://github.com/phetsims/chipper/issues/661)

- [x] [resistance-in-a-wire 1.3.7-rc.1 phet-io](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.3.7-rc.1/resistance-in-a-wire_en-phetio.html?phetioStandalone)
- [ ] [resistance-in-a-wire 1.3.7-rc.1 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.3.7-rc.1/wrappers/instance-proxies/instance-proxies.html?sim=resistance-in-a-wire&relativeSimPath)

resistance-in-a-wire 1.6 (https://github.com/phetsims/chipper/issues/661)

- [x] [resistance-in-a-wire 1.6.3-rc.1](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.3-rc.1/phet/resistance-in-a-wire_en_phet.html)

rutherford-scattering 1.1 (https://github.com/phetsims/chipper/issues/661)

- [x] [rutherford-scattering 1.1.3-rc.1](https://phet-dev.colorado.edu/html/rutherford-scattering/1.1.3-rc.1/phet/rutherford-scattering_en_phet.html)

states-of-matter 1.1 (https://github.com/phetsims/chipper/issues/661)

- [x] [states-of-matter 1.1.4-rc.1](https://phet-dev.colorado.edu/html/states-of-matter/1.1.4-rc.1/phet/states-of-matter_en_phet.html)

states-of-matter-basics 1.1 (https://github.com/phetsims/chipper/issues/661)

- [x] [states-of-matter-basics 1.1.2-rc.1](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.1.2-rc.1/phet/states-of-matter-basics_en_phet.html)

wave-interference 1.0 (https://github.com/phetsims/chipper/issues/661)

- [x] [wave-interference 1.0.4-rc.1](https://phet-dev.colorado.edu/html/wave-interference/1.0.4-rc.1/phet/wave-interference_en_phet.html)

**Comment by KatieWoe** [comment]
From Slack:
Kathryn Woessner [3:35 PM]
Having trouble launching from instance proxies in https://github.com/phetsims/QA/issues/332.  Is there an extra step we need?

Michael Kauzmann [3:36 PM]
what link?

Kathryn Woessner [3:36 PM]
I was on https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.3.7-rc.1/wrappers/instance-proxies/instance-proxies.html?sim=resistance-in-a-wire&relativeSimPath
But Liam also tested one and it did the same thing
He also says the html file from generate html doesn't work
Ones marked studio (like molarity) seem to work

Michael Kauzmann [6:16 PM]
I also see that that's broken too. (edited)

**Comment by KatieWoe** [comment]
Other than that, QA is done

**Comment by zepumph** [comment]
Thanks @KatieWoe. @jonathanolson let me know if you need anything from here.

**Comment by jonathanolson** [comment]
Thanks, closing!
