### ISSUE TITLE
Dev test: Graphing Quadratics 1.1.0-dev.4

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#334]
@pixelzoom, @samreid, @kathy-phet, @ariel-phet, @chrisklus, Graphing Guadratics 1.1.0-dev.4 ready for dev testing. The goal is to have GQ published with PhET-iO by 7/19/19. Document issues in https://github.com/phetsims/graphing-quadratics/issues if you think it is sim specific, and in https://github.com/phetsims/phet-io/issues if you think it may be general phet-io issue (we can also always move it later) and please link to this issue.

From @zepumph's understanding, little work has been done on this simulation for phet brand since its publication. The main purpose of this dev test is to expose issues with the general phet-io related work, so heavily testing the wrappers will be important to this test. That said, this is the sim that we wish to publish first, so also let us know of sim specific stuff.

Furthermore, phet-io dev testing is new thing! Let @zepumph or another phet-io team member know if you have any questions about how the phet-io features/wrappers work. Also we should edit the test template or other documentation to make things clearer if needed.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>PhET-iO Dev Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices (like this one), save the "basic example of a functional wrapper" as a .html file and open it. Make sure the simulation loads without crashing or throwing errors.
- Try to break each wrapper
- In Studio try to break the simulation by manipulating the elements in the tree to the left (make sure that you display "all" elements when testing, not just "featured" ones.

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.0-dev.4/phet-io/)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by pixelzoom** [comment]
Slack discussion clarifying the purpose of this dev test:

Chris Malley [4:53 PM]
Can you help me understand the purpose of the dev test in https://github.com/phetsims/QA/issues/334?  I haven’t done the PhET-iO work on the sim-specific code yet, unless you have.

Michael Kauzmann [4:54 PM]
I have not either.

The purpose is get a test going because time is short, emphasizing on the wrapper suite, which has had 2 years of changes since the last test, and likely stuff will come up. We didn't want that stuff to come up with 2 weeks left before publication.
Sorry that we weren't clear in the GQIO timeline issue.

Chris Malley [4:55 PM]
OK, thanks for the clarification.  So the emphasis is on testing Studio, wrappers, etc. and not on verifying that GQ PhET-iO instrumentation meets requirements?

Michael Kauzmann [4:56 PM]
Yes indeed.
We have yet to really work out a QA process for the latter yet.

Chris Malley [4:56 PM]
Would you mind if I copy-paste this exchange into the issue?

Michael Kauzmann [4:56 PM]
I was going to ask that!
Go crazy

Chris Malley [4:56 PM]
:japanese_ogre::scream_cat::ghost:

**Comment by KatieWoe** [comment]
Test Latest Mac, Windows, and ChromeOS all browsers.  Test simple wrappers on iOS.
Most testing on Studio, State, and Mirror Input.  Ignore Dif wrapper for now.
Studio instructions: Test tree navigation and effect on sim/vice versa.  Test hyperlinks in types radio button: all and selected.  Test scrolling and changing section size.  Test launch/html.  Test search.  Record any oddities.
Do both the normal and metacog recording.  Focus metacog on non-Win and non-chrome/firefox.
Note to self: update Studio in QA book after dev test.

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome
- [ ] Win 10 firefox
- [ ] Win 10 edge
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 firefox
- [ ] Mac 10.14 safari
- [ ] ChromeOS
- [ ] iOS 12

**Comment by KatieWoe** [comment]
QA is done

**Comment by zepumph** [comment]
Thanks @KatieWoe. Sorry that this has taken so long. Can you please test this link for metacog recording. Note that I just recording a 20 second session, so there should already be one there.

https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.0-dev.4/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=9&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=graphing-quadratics-test&phetioEmitInputEvents=true&phetioEmitStates=true&phetioEmitStatesInterval=60&metacog

Let me know if you have any questions.

Here is an exhaustive list to test if you have the time.
* Test recording on a few different browsers and devices, 
* Record a variety of interactions within the sim (including browser tab change and resize)
* Record at a few different internet speeds (see if you can throttle via the browser developer tools

Thanks!

**Comment by KatieWoe** [comment]
Recording Tests:
- [ ] Win 10 chrome
- [ ] Win 10 firefox
- [ ] Win 10 edge
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 firefox
- [ ] Mac 10.14 safari
- [ ] ChromeOS
- [ ] iOS 12

**Comment by KatieWoe** [comment]
Took Mac firefox off due to no longer supporting it.

**Comment by lmulhall-phet** [comment]
Recordings look good on macOS.

**Comment by KatieWoe** [comment]
QA is done the sequel

**Comment by lmulhall-phet** [comment]
QA Is Done 2: Electric Boogaloo

**Comment by zepumph** [comment]
Awesome. Thank you QA! Closing.
