### ISSUE TITLE
Test Powerpoint add-in on latest version of CU Office

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/QA#335]
We need someone to download the latest version of Office through OIT (using CU credentials) and test the powerpoint add-in on both Windows and Mac.

**Comment by KatieWoe** [comment]
Doesn't seem to work

**Comment by oliver-phet** [comment]
Can you screenshot or copy/paste the errors for both Mac and Windows?

**Comment by KatieWoe** [comment]
I don't get one on my Windows device, I'm not sure why.  I tried updating it, but I can get a screenshot for Mac at least.

**Comment by KatieWoe** [comment]
On Mac:
![Screen Shot 2019-06-05 at 2 07 29 PM](https://user-images.githubusercontent.com/41024075/58987063-f6189e80-879b-11e9-9aaa-7e765eb655b5.png)

**Comment by lmulhall-phet** [comment]
Works on Windows 10 + Office 2016.

For some reason OIT doesn't have a download for Office 2019 for Windows 10. Tested Windows 10 with Office 365 and got the exact same error message:

![Error](https://user-images.githubusercontent.com/31285590/58990346-ee102d00-87a2-11e9-9556-4627c6113f85.PNG)
