### ISSUE TITLE
Dev test: Pendulum Lab 1.0.0-dev.14

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#34]
@ariel-phet and @arouinfar, Pendulum Lab 1.0.0-dev.14 is ready for general dev testing.

URL: http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.14/pendulum-lab_en.html

There have been a lot of model/view changes (particularly with layout), so a full test would be great.

Also let me know if https://github.com/phetsims/pendulum-lab/issues/102 is still an issue.

Please test on the following:

- [x] iPad 2
- [x] iPad Air
- [x] Chrome (Windows)
- [x] Safari (MacOS)

> Steele, this would be high priority, after CCK.

**Comment by phet-steele** [comment]
@jonathanolson @arouinfar this sim performed pretty well!
