### ISSUE TITLE
Dev test: Gas Properties 1.0.0-dev.38 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#342]
@KatieWoe, @arouinfar, @ariel-phet, @kathy-phet, gas-properties/1.0.0-dev.38 is ready for dev testing.  This sim is `brand=phet` only.  It has no PhET-iO and no a11y instrumentation. 

It's highly desirable to have this testing completed by 7/2/19.

Document issues in https://github.com/phetsims/gas-properties/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.

<h3>Focus and Special Instructions</h3>

* During implementation, this sim has been tested primarily on macOS+Chrome and iOS.  Other platforms need a good shakedown.

* Multitouch could use a more thorough shakedown. Most interaction can be performed simultaneously.  Some interaction are mutually exclusive by design (sorry, there is no list).  For example, you cannot resize the container and move its lid at the same time.

* Memory testing was done in https://github.com/phetsims/gas-properties/issues/103, if you want to compare results.

* @pixelzoom will likely be gone during most or all of this dev test. Please refer "How is this supposed to work?" questions to @arouinfar, who is the lead designer.   You can also consult the [Gas Properties design document](https://docs.google.com/document/d/1HOCO6vXfqlHIf3MrdldaiZTPFKYWTzS9Jm8fw-b25EU/edit), which is mostly up-to-date.

* The "Hold Constant" radio button group (found only on the _Ideal_ screen) allows the user to hold one quantity constant while one or more of the other quantities change.  In some situations that becomes possible, and the sim will display an "Oops!" dialog.  For a description of this feature, see the table in the "Hold Constant" subsection of the [Gas Properties design document](https://docs.google.com/document/d/1HOCO6vXfqlHIf3MrdldaiZTPFKYWTzS9Jm8fw-b25EU/edit). 

* [model.md](https://github.com/phetsims/gas-properties/blob/master/doc/model.md) and [implementation-notes.md](https://github.com/phetsims/gas-properties/blob/master/doc/implementation-notes.md) are works in progress, but you may want to give them a quick read before testing.

* Be sure to check out the "Options" dialog, accessible via the PhET menu. 

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Issues to Verify</h3>

As of this writing, there are no specific issues too verify.  All known issues have been addressed.

<h3>Link(s)</h3>

- **[Simulation](https://bayes.colorado.edu/dev/html/gas-properties/1.0.0-dev.38/phet/gas-properties_all_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
Slight bump down in priority due to app testing

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
Thank you @KatieWoe and QA team!

**Comment by pixelzoom** [comment]
With the exception of https://github.com/phetsims/gas-properties/issues/125, issues identified by this dev test have been addressed and are properly labeled.  So I'm going to close this issue.
