### ISSUE TITLE
RC Spot Check: Ohms Law 1.4.0-rc.4

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#345]
@emily-phet @terracoda @KatieWoe Ohms Law 1.4.0-rc.4 is ready for an RC spot check. This comes after #327.

Only one remaining issue came out of the previous RC. Changes from the last RC are small enough that we don't need to do another full RC. Please just verify that the issue is resolved in this build, then do a quick spot check that all seems well.

Link to RC: https://phet-dev.colorado.edu/html/ohms-law/1.4.0-rc.4/phet/ohms-law_en_phet.html

Issues to spot check:

  - [x] phetsims/ohms-law#146 (Safari freezes if sim left untouched for 3 minutes)

Assigning to @ariel-phet to prioritize.

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome (with and without Jaws)
- [ ] Win 10 firefox (with and without NVDA)
- [ ] Win 10 edge
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 firefox
- [ ] Mac 10.14 safari (with and without VO)
---
- [ ] Win 7 IE
- [ ] Mac 10.11 safari
---
- [ ] ChromeOS
- [ ] iOS 12 (with and without VO)
---
@jessegreenberg to approve test devices

**Comment by jessegreenberg** [comment]
List looks great, thanks!

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe then this sim is ready for publication.

**Comment by KatieWoe** [comment]
This is published.  Closing.
