### ISSUE TITLE
updates to PhET Asset Inventory

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#347]
Corrections are needed for test machines in the [PhET Asset Inventory](https://docs.google.com/spreadsheets/d/1XqnlW8DAlt2fZHDfDgkTMmMLpJZ1c0equBaPdkn2V08/edit#gid=0).

In https://github.com/phetsims/ph-scale/issues/83#issuecomment-498415377, Hopper was reported to be running "iOS 12", and that's what is shown in the table.  Please update to include the specific version of iOS 12.

In https://github.com/phetsims/ph-scale/issues/83#issuecomment-498415377, Leibniz was also reported to be running "iOS 12".  The inventory says "iOS 9.3.5".   Which is correct? 

I'm not sure who I should assign this to.  Since these are test machines, I'll start with @KatieWoe .

**Comment by KatieWoe** [comment]
Things look better on the spreadsheets on both the first and last pages.  Thanks @etwa4650
