### ISSUE TITLE
Dev test: Projectile Motion 1.0.0-dev.9

### ISSUE THREAD

**Issue by andrea-phet** [phetsims/QA#35]
Test link:
http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-dev.9/projectile-motion_en.html

Known issues:
* https://github.com/phetsims/projectile-motion/issues/131
* https://github.com/phetsims/projectile-motion/issues/129

**Comment by ariel-phet** [comment]
@phet-steele this sim should be higher priority than pendulum lab given that Andrea is only with us a bit more this summer.

**Comment by andrea-phet** [comment]
Done.
