### ISSUE TITLE
Maintenance Release Spot Check

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#351]
@mattpen and I recently went through the maintenance release process for https://github.com/phetsims/scenery/issues/883. This bug only impacted sims where keyboard navigation was enabled. And the maintenance release process only identified the following three sims as needing the patch. @KatieWoe can you please test these versions to make sure that this issue was resolved and no other breaking issues have been introduced? Only short spot checking (10-30 seconds) should be required for each.

balloons-and-static-electricity 1.4 (https://github.com/phetsims/scenery/issues/883)

- [x] [balloons-and-static-electricity 1.4.8-rc.2](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.4.8-rc.2/phet/balloons-and-static-electricity_en_phet.html)
  - [x] [balloons-and-static-electricity 1.4.8-rc.2 iframe](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.4.8-rc.2/phet/balloons-and-static-electricity_en_iframe_phet.html)

john-travoltage 1.5 (https://github.com/phetsims/scenery/issues/883)

- [x] [john-travoltage 1.5.6-rc.1](https://phet-dev.colorado.edu/html/john-travoltage/1.5.6-rc.1/phet/john-travoltage_en_phet.html)
  - [x] [john-travoltage 1.5.6-rc.1 iframe](https://phet-dev.colorado.edu/html/john-travoltage/1.5.6-rc.1/phet/john-travoltage_en_iframe_phet.html)

molecules-and-light 1.4 (https://github.com/phetsims/scenery/issues/883)

- [x] [molecules-and-light 1.4.8-rc.1](https://phet-dev.colorado.edu/html/molecules-and-light/1.4.8-rc.1/molecules-and-light_en.html)
  - [x] [molecules-and-light 1.4.8-rc.1 iframe](https://phet-dev.colorado.edu/html/molecules-and-light/1.4.8-rc.1/molecules-and-light_en-iframe.html)

Assigning to @ariel-phet for prioritization.

**Comment by jessegreenberg** [comment]
I am seeing an issue with the first link, reassigning back to me to investigate before handing to QA.

**Comment by jessegreenberg** [comment]
I updated the balloons-and-static-electricity link in the issue. The process knew that BASE was the only sim that had to be rebuilt, that is way cool.

To test https://github.com/phetsims/scenery/issues/883 you will need sim iframes, so I added links to iframes too.  This is ready again.

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Thank you @KatieWoe, we are ready to deploy to production.
