### ISSUE TITLE
Submit Firefox graphical glitch bug to their bug tracker

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#352]
See https://github.com/phetsims/ph-scale/issues/81 for the main example of behavior where something moving leaves artifacts on the screen. This seems to be a general SVG issue.

I believe https://bugzilla.mozilla.org/home would be a good starting place.

**Comment by KatieWoe** [comment]
Draft Bug Report:

Devices: Windows or Mac machines
Firefox Versions: 67.0-67.0.4
Problem Description: When SVG is attempting to redraw a box getting progressively smaller, ghostly images of the larger can be left behind for a bit as lighter colored bars of color.
Video:

**Comment by jonathanolson** [comment]
Looks like good steps to reproduce, as long as we can give out that link. I'll let others or @ariel-phet make that call.

**Comment by KatieWoe** [comment]
@jessegreenberg helped make an html version that works with an iframe.  Comment above edited.

**Comment by KatieWoe** [comment]
Bug submitted: https://bugzilla.mozilla.org/show_bug.cgi?id=1561030
