### ISSUE TITLE
Drop Mac Firefox

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/QA#353]
On 6/20/19 we decided in dev meeting that we would drop support for Firefox on Mac devices (not Windows) due to the usage being less than 1%.  This means that I nee to change the test matrix and QA book.  In addition, for awhile at least, we will treat it a bit like the iOS 9 and iOS 10 devices.  We will make sure the sim opens and runs acceptably, but not dig for bugs.

**Comment by oliver-phet** [comment]
Help center updated.

**Comment by KatieWoe** [comment]
https://docs.google.com/spreadsheets/d/1jl8z3MjmGBeU_Z5voMIN-rBF9al6LNyey9ZIuOpoUzA/edit#gid=1953870942 is tentative Matrix.  Needs to be tested.

**Comment by lmulhall-phet** [comment]
I feel slighted.

**Comment by lmulhall-phet** [comment]
I made some tweaks to the test completion percentage cell formulas. Let me know if you think everything is OK, @KatieWoe. I also dropped the HTML download test for iPad 2.

**Comment by KatieWoe** [comment]
Test matrix done

**Comment by KatieWoe** [comment]
QA book updated as well.  Closing
