### ISSUE TITLE
Spot checks for delayed chipper startup

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#354]
See https://github.com/phetsims/chipper/issues/764 and https://github.com/phetsims/tasks/issues/1002 for background information.

I've dev-deployed https://phet-dev.colorado.edu/html/charges-and-fields/1.1.0-dev.7 with the patch for those issues, which will delay the sim require.js startup until suitable conditions (i.e. iframe that isn't hidden) exist.

Some example HTML (can be saved as a file and viewed in a browser) that can help trigger the issue is:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hidden Sim test</title>
  </head>
  <body>

  <div hidden id="container">
    <iframe width="800" height="600" src="https://phet-dev.colorado.edu/html/charges-and-fields/1.1.0-dev.7/phet/charges-and-fields_en_phet.html" id="iframe" allowfullscreen scrolling="no" title="Some Title"></iframe>
  </div>

  <button id="testButton">Toggle Hidden</button>

  </body>

  <script type="text/javascript">
    const container = document.getElementById( 'container' );
    const button = document.getElementById( 'testButton' );
    button.addEventListener( 'click', ( event ) => {
      if ( container.hidden ) {
        container.removeAttribute( 'hidden' );
      }
      else {
        container.hidden = true;
      }
    } );
  </script>
</html>
```

I'd recommend trying out the phet and phet-io brand files in multiple configurations (LoL, anywhere iframes are concerned, and particularly any place the sim may be hidden) to see if this breaks anything.

I'd also appreciate some cross-browser testing to ensure that this won't break on any of our supported platforms.

@ariel-phet, anything else you think should be tested for this change?

**Comment by ariel-phet** [comment]
@KatieWoe I think this would be good to basically test on all supported platforms and in the ways @jonathanolson mentions above. High priority for the moment since not much in the testing queue, but will get bumped down if other things come up.

**Comment by jonathanolson** [comment]
Additionally, the above HTML is now at the link https://phet-dev.colorado.edu/olsonjb/hidden-test.html, so I'd like that tested on all platforms if possible.

**Comment by lmulhall-phet** [comment]
# Testing Platforms

- [ ] iOS 11 + Safari
- [ ] iOS 12 + Safari
***
- [ ] macOS 10.10 + Safari
- [ ] macOS 10.11 + Safari
- [ ] macOS 10.11 + Chrome
- [ ] macOS 10.12 + Safari
- [ ] macOS 10.12 + Chrome
- [ ] macOS 10.13 + Safari
- [ ] macOS 10.13 + Chrome
- [ ] macOS 10.14 + Safari
- [ ] macOS 10.14 + Chrome
***
- [ ] Win7 + IE
- [ ] Win7 + Chrome
- [ ] Win7 + FF
***
- [ ] Win10 + Edge
- [ ] Win10 + Chrome
- [ ] Win10 + FF
***
- [ ] ChromeOS

**Comment by lmulhall-phet** [comment]
Test the following items:

* https://phet-dev.colorado.edu/html/charges-and-fields/1.1.0-dev.7/phet/charges-and-fields_all_phet.html
* https://phet-dev.colorado.edu/html/charges-and-fields/1.1.0-dev.7/phet/charges-and-fields_all_iframe_phet.html
* https://phet-dev.colorado.edu/html/charges-and-fields/1.1.0-dev.7/phet/xhtml/charges-and-fields_all.xhtml
* https://phet-dev.colorado.edu/olsonjb/hidden-test.html
* https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fcharges-and-fields%2F1.1.0-dev.7%2Fphet%2Fcharges-and-fields_all_phet.html%3FlegendsOfLearning

**Comment by KatieWoe** [comment]
@jonathanolson the hidden/unhidden html doesn't seem to load (nothing on the progress bar) on Win 10 firefox. 
![consoleerror](https://user-images.githubusercontent.com/41024075/60620544-b9d75e80-9d98-11e9-8087-8afcdbf4b002.png)

**Comment by KatieWoe** [comment]
Sim looks fine on the hidden/unhidden page of iOS 12 safari.  But the page can be scrolled up and down.
https://drive.google.com/file/d/1gCA2uQmrh6Kgs_-WjOnG5dC7XXqQRgYK/view?usp=sharing

**Comment by lmulhall-phet** [comment]
https://phet-dev.colorado.edu/olsonjb/hidden-test.html not working on Win7 + IE.

**Comment by KatieWoe** [comment]
Safari 10.1.2 on Mac 10.10.5 won't show the sim when the hidden button is clicked much like in Edge.
Error:
```
SntaxError: Can't create duplicate variable that shadows a global property: 'container'
N (anonymous function)
```

**Comment by KatieWoe** [comment]
QA is done.  Let me know if the comments above should be issues and where they should go.

**Comment by jonathanolson** [comment]
Thanks!
