### ISSUE TITLE
Testing support for Map

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#355]
From https://github.com/phetsims/tasks/issues/992, we would like to be able to use Map, but there is some uncertainty on how well it works on our supported platforms. We made some tests that exercise several Map features that will help us understand this to decide if we can use it.

 **Link to test:** https://phet-dev.colorado.edu/html/jg-tests/map-tests.html

Please run this test on all of our supported platforms and report any issues here. If the tests pass, it will look like this:
![image](https://user-images.githubusercontent.com/6396244/60309181-84ef8580-991a-11e9-9fdb-985a6aa89c8c.png)

If tests fail, they will show up red on that page.

Thanks!

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome
- [ ] Win 10 firefox
- [ ] Win 10 edge
---
- [ ] Win 7 chrome
- [ ] Win 7 firefox
- [ ] Win 7 IE
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 safari
---
- [ ] Mac 10.13 chrome
- [ ] Mac 10.13 safari
---
- [ ] Mac 10.12 chrome
- [ ] Mac 10.12 safari
---
- [ ] Mac 10.11 chrome
- [ ] Mac 10.11 safari
---
- [ ] Mac 10.10 safari
---
- [ ] Chrome OS
- [ ] iOS 12
- [ ] iOS 11

**Comment by KatieWoe** [comment]
Fails on Win 7 IE
Syntax error
Source: https://phet-dev.colorado.edu/html/jg-tests/map-tests.html:22

**Comment by KatieWoe** [comment]
Happens on Win 10 IE as well
![bug](https://user-images.githubusercontent.com/41024075/60375299-dacd3780-99c5-11e9-86a9-bce55dfc4e0b.png)

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, great.  We will take results back to phetsims/tasks#992

**Comment by jessegreenberg** [comment]
Shoot, it failed in IE11 because I used es6 in the tests.

**Comment by jessegreenberg** [comment]
Here is the output when I remove ES6:

![image](https://user-images.githubusercontent.com/6396244/60458788-81efe000-9c0d-11e9-9d53-193216899286.png)

So IE11 just doesn't like `new Map( iterable )`. Re-closing.

**Comment by jessegreenberg** [comment]
I identified all the tests that are failing in IE11. Closing.
