### ISSUE TITLE
Website: test new navigation bar

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#356]
QA team, please test the new header/navigation bar for the website.  Please make sure all interaction works as expected and that the view is ideal in all cases.

Please test the following pages thoroughly:

- [ ] https://ox-dev.colorado.edu/
- [ ] https://ox-dev.colorado.edu/ar_SA/ (RTL language format testing only)
- [ ] https://ox-dev.colorado.edu/en/simulation/friction
- [ ] https://ox-dev.colorado.edu/ar_SA/simulation/friction (RTL language format testing only)

Additionally, please complete a cursory spot check of various other pages across the website just to confirm there are no problems with layout.  Please test the standard device/browser configurations.  If a device can display both the wide and narrow view, please test interaction in both layouts. Please test mouse, touch, keyboard and multi-modal interaction.  It would be nice to test these with standard screen readers (NVDA, VoiceOver, TalkBack) as well if time allows.

The only things that need to be tested are anything in the header, i.e. the navigation dropdown menus, the search widget, and the login/user links/menus.

Keyboard interaction for the navigation menu is specified in the following links.  For QA, please note in particular the description of the action assigned to specific keys.
https://www.w3.org/TR/wai-aria-practices-1.1/#menubar
https://www.w3.org/TR/wai-aria-practices-1.1/#menu

Please open issues in the website repo for any bugs/problem reports.

@ariel-phet please assign a priority.

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome
- [ ] Win 10 chrome Jaws
- [ ] Win 10 firefox
- [ ] Win 10 firefox NVDA
- [ ] Win 10 edge
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 firefox
- [ ] Mac 10.14 safari
- [ ] Mac 10.14 safari VO
---
- [ ] Win 7 chrome
- [ ] Win 7 firefox
- [ ] Win 7 IE
---
- [ ] Mac 10.13 chrome
- [ ] Mac 10.13 firefox
- [ ] Mac 10.13 safari
---
- [ ] Mac 10.12 chrome
- [ ] Mac 10.12 firefox
- [ ] Mac 10.12 safari
---
- [ ] Mac 10.11 chrome
- [ ] Mac 10.11 firefox
- [ ] Mac 10.11 safari
---
- [ ] Mac 10.10 safari
---
- [ ] iPad iOS 12
- [ ] iPad iOS 11
- [ ] iPhone (Not officially supported but I know we did some design for it)
---
- [ ] Chrome OS
---
@mattpen any other platforms you'd like looked at?

**Comment by ariel-phet** [comment]
Current top testing priority

**Comment by KatieWoe** [comment]
QA is done
