### ISSUE TITLE
Labels and other Github process changes

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/QA#358]
Some suggestions to the github process I would like to propose.
a11y bug tag: often a bug is specific to keyboard nav or screen readers, and requires a different dev than other issues for a test.  A specific tag for this type of bug would be nice.
Removing Severity from report a problem page: This is handled on github by the priority labels
@ariel-phet to review/discuss

**Comment by lmulhall-phet** [comment]
If we're going to change the report a problem page, I propose the following.

This...
```
Test device:

Operating System:

Browser:

Problem description:

Steps to reproduce:

Severity:

Screenshots:

Troubleshooting information (do not edit):
Name: ‪Atomic Interactions‬
URL: https://phet.colorado.edu/sims/html/atomic-interactions/latest/atomic-interactions_en.html
Version: 1.0.11 2019-06-23 07:08:59 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"HEAD"},"atomic-interactions":{"sha":"685d8242","branch":"HEAD"},"axon":{"sha":"b4404f00","branch":"HEAD"},"babel":{"sha":"6981a4bd","branch":"master"},"brand":{"sha":"63879db6","branch":"HEAD"},"chipper":{"sha":"b7650b7f","branch":"HEAD"},"dot":{"sha":"23b13772","branch":"HEAD"},"joist":{"sha":"b936e158","branch":"HEAD"},"kite":{"sha":"3b656b9a","branch":"HEAD"},"nitroglycerin":{"sha":"ad3cb990","branch":"HEAD"},"phet-core":{"sha":"c48bf320","branch":"HEAD"},"phetcommon":{"sha":"e0a87654","branch":"HEAD"},"phetmarks":{"sha":"3fdfece0","branch":"HEAD"},"query-string-machine":{"sha":"05231e54","branch":"HEAD"},"scenery":{"sha":"c556604e","branch":"HEAD"},"scenery-phet":{"sha":"9d87b624","branch":"HEAD"},"sherpa":{"sha":"bcc28cd6","branch":"HEAD"},"states-of-matter":{"sha":"8ff9bed9","branch":"HEAD"},"sun":{"sha":"10af95af","branch":"HEAD"},"tandem":{"sha":"4a8edbc9","branch":"HEAD"}}
```

should be this...

```
Instructions: Copy the form below and paste it into a GitHub issue at the following address.
https://github.com/phetsims/qa/issues
Please fill out the form as accurately and concisely as you can.

**Test Device**

**Operating System**

**Browser**

**Problem Description**

**Steps to Reproduce**

**Visuals**

<details>
<summary><b>Troubleshooting Information</b></summary>
Name: ‪Atomic Interactions‬
URL: https://phet.colorado.edu/sims/html/atomic-interactions/latest/atomic-interactions_en.html
Version: 1.0.11 2019-06-23 07:08:59 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
Language: en-US
Window: 1440x821
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
</details>
```

**Comment by ariel-phet** [comment]
@KatieWoe sounds good, I will bring at up at dev meeting, as both these should be relatively quick.

As a note, likely changing the report a problem would just be for sims going forward (doesn't seem worth a maintenance release since any sim we are doing QA on is likely going through a move off of master).

**Comment by phet-steele** [comment]
> As a note, likely changing the report a problem would just be for sims going forward (doesn't seem worth a maintenance release...

Report a Problem is a link to a page on our website. No sim maintenance releases required.

**Comment by pixelzoom** [comment]
@KatieWoe Do you mean "label"?  A "tag" is something different in git/guthub parlance; it's a reference to a specific point in the history of a repo.

**Comment by KatieWoe** [comment]
label

**Comment by ariel-phet** [comment]
@mattpen is on the case, he will make this label, and edit the report a problem page.

**Comment by KatieWoe** [comment]
Thanks

**Comment by mattpen** [comment]
What if we just redirect the user to a prefilled github issue?  You can add title/body with query parameters, heres an example: https://github.com/phetsims/QA/issues/new?title=foo&body=bar

**Comment by KatieWoe** [comment]
Do you mean they would create an issue themselves?  I would be hesitant to do that just because I have seen such lovely issues come in as "you can't set the dog on fire," "its broken," "you ***."

**Comment by mattpen** [comment]
@KatieWoe - that's what @lmulhall-phet proposed above ^^

Here's a [detailed example](https://github.com/phetsims/QA/issues/new?title=Bug%20Report&body=Report%20a%20Problem%0AInstructions%3A%20Copy%20the%20form%20below%20and%20paste%20it%20into%20a%20GitHub%20issue%20at%20the%20following%20address.%20https%3A%2F%2Fgithub.com%2Fphetsims%2Fqa%2Fissues%2Fnew%20Please%20fill%20out%20the%20form%20as%20accurately%20and%20concisely%20as%20you%20can.%20%0A%0A%2A%2ATest%20device%2A%2A%0A%0A%2A%2AOperating%20System%2A%2A%0A%0A%2A%2ABrowser%2A%2A%0A%0A%2A%2AProblem%20description%2A%2A%0A%0A%2A%2ASteps%20to%20reproduce%2A%2A%0A%0A%2A%2AVisuals%2A%2A%0A%0A%0ATroubleshooting%20information%3A%0A%21%21%21%21%21%20DO%20NOT%20EDIT%20%21%21%21%21%21%0AFeatures%20missing%3A%20touch%0AUser%20Agent%3A%20Mozilla%2F5.0%20%28Windows%20NT%2010.0%3B%20Win64%3B%20x64%29%20AppleWebKit%2F537.36%20%28KHTML%2C%20like%20Gecko%29%20Chrome%2F75.0.3770.100%20Safari%2F537.36%0ALanguage%3A%20en-US%0AWindow%3A%201920x937%0APixel%20Ratio%3A%201%2F1%0AWebGL%3A%20WebGL%201.0%20%28OpenGL%20ES%202.0%20Chromium%29%0AGLSL%3A%20WebGL%20GLSL%20ES%201.0%20%28OpenGL%20ES%20GLSL%20ES%201.0%20Chromium%29%0AVendor%3A%20WebKit%20%28WebKit%20WebGL%29%0AVertex%3A%20attribs%3A%2016%20varying%3A%2030%20uniform%3A%204096%0ATexture%3A%20size%3A%2016384%20imageUnits%3A%2016%20%28vertex%3A%2016%2C%20combined%3A%2032%29%0AMax%20viewport%3A%2016384x16384%0AOES_texture_float%3A%20true&labels=type:bug)

**Comment by KatieWoe** [comment]
I disagree with that section.  The template itself is fine, but I don't think that an issue should be made unfiltered.  There's no guarantee that an issue would be clear enough yet for a developer to look at at best, and it would open us up to a fair amount of spam at worst.

**Comment by mattpen** [comment]
> I have seen such lovely issues come in as "you can't set the dog on fire," "its broken," and "you ***."

Those could just be closed and ignored, although I have wondered about that poor dog (my son spent an hour trying to light it on fire in CCK).  Those same people would send us an email with the same information that would need to be deleted anyway.

**Comment by mattpen** [comment]
> it would open us up to a fair amount of spam at worst.

OK, I'll leave the phethelp email link in.

**Comment by mattpen** [comment]
New label added in: 7f2a84ac265f9a2839555f1720879940b1043ce4

**Comment by mattpen** [comment]
The template updates are pending a redeploy of the website.
