### ISSUE TITLE
Dev test: website front page

### ISSUE THREAD

**Issue by chrisklus** [phetsims/QA#359]
@mattpen, @ariel-phet, @amanda-phet, @arouinfar, @oliver-phet, the website front page is ready for dev testing (excluding the image carousel). Please document issues in https://github.com/phetsims/website-meteor/issues and link to this issue.

@ariel-phet please assign a priority.

QA team, please test the new front page for the website, excluding the image carousel (the rotating banner of images at the top of the page).  Please make sure all interaction works as expected and that the view is ideal in all cases.

Link: https://ox-dev.colorado.edu/

Please test the standard device/browser configurations.  If a device can display both the wide and narrow view, please test interaction in both layouts. Please test mouse, touch, keyboard and multi-modal interaction.  It would be nice to test these with standard screen readers (NVDA, VoiceOver, TalkBack) as well if time allows.

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome
- [ ] Win 10 chrome Jaws
- [ ] Win 10 firefox
- [ ] Win 10 firefox NVDA
- [ ] Win 10 edge
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 safari
- [ ] Mac 10.14 safari VO
---
- [ ] Win 7 chrome
- [ ] Win 7 firefox
- [ ] Win 7 IE
---
- [ ] Mac 10.13 chrome
- [ ] Mac 10.13 safari
---
- [ ] Mac 10.12 chrome
- [ ] Mac 10.12 safari
---
- [ ] Mac 10.11 chrome
- [ ] Mac 10.11 safari
---
- [ ] Mac 10.10 safari
---
- [ ] iPad iOS 12
- [ ] iPad iOS 12 VO
- [ ] iPad iOS 11
- [ ] Latest iOS on iPhone
- [ ] Latest iOS on iPhone + VoiceOver
---
- [ ] Chrome OS
---
@chrisklus any other platforms you'd like looked at?

**Comment by chrisklus** [comment]
@KatieWoe that looks great, thanks

**Comment by KatieWoe** [comment]
QA is done.  Not much new that wasn't discussed in previous test, but we tried to link relevant issues here as well.
