### ISSUE TITLE
Dev Test: New Splash Screen

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#36]
From https://github.com/phetsims/joist/issues/408 https://github.com/phetsims/joist/issues/407 and https://github.com/phetsims/joist/issues/349 we have made the following changes to the splash screen:

1. It should be sized proportionally to the screen size
2. It should show a pulsing animation while downloading

I published an Energy Skate Park: Basics version here that has these changes.  It will need to be tested on all of our supported platforms because it uses new preload code + css that may have platform-specific issues.
http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.3.1-dev.6/energy-skate-park-basics_en.html

Before setting the entire QA team loose on this, it would be best if @ariel-phet could review the current implementation for design issues (sizing and how the pulse-download animation looks).  If all is well, then we can expand the testing.  If your internet connection is too fast, you may have trouble seeing the download part of the animation.  You can use Chrome Dev Tools to throttle your download speed.  View => Developer => Developer Tools=> Network => "No throttling" (in the top right) can be changed as desired.
![image](https://user-images.githubusercontent.com/679486/29244535-cade00c6-7f77-11e7-9713-9768df3ee86f.png)

**Comment by samreid** [comment]
A reminder to test phetsims/joist#408 phetsims/joist#407 when this gets to the QA team.

**Comment by ariel-phet** [comment]
@samreid all looks good to me

**Comment by samreid** [comment]
Thanks @ariel-phet.  A reminder to the QA team during testing to test out phetsims/joist#408 phetsims/joist#407 in particular.

**Comment by ariel-phet** [comment]
@samreid anything to add before @phet-steele takes over

**Comment by samreid** [comment]
It's all set, let me know how it goes.

**Comment by phet-steele** [comment]
@samreid looks good on our supported platforms. All linked issues have been taken care of as well.

**Comment by samreid** [comment]
Thanks @phet-steele, I'll merge this to master and it will be ready for new deploys from master.

**Comment by samreid** [comment]
I'll proceed in https://github.com/phetsims/joist/issues/391, many thanks @phet-steele
