### ISSUE TITLE
Maintenance release testing for delayed analytics

### ISSUE THREAD

**Issue by chrisklus** [phetsims/QA#360]
For https://github.com/phetsims/phet-ios-app/issues/484.

QA team, please quickly test each of these links for 10-30 seconds to make sure nothing is badly broken in the sim. Please also open the dev tools, go to the network tab, and make sure that at least one "collect" gif is present (there are two in the screenshot below) and immediate.gif is present. If the network tab is empty by the time you navigate to it, reload the page and you should see it being populated. 

Only one browser, say Chrome, and only one test device, say a Mac laptop, is needed for testing.

Example in Chrome dev tools:
<img width="1581" alt="Screen Shot 2019-07-08 at 4 21 55 PM" src="https://user-images.githubusercontent.com/5618316/60846486-d6aad200-a19c-11e9-865c-0c71cbb7717e.png">

If any problems are found, please just comment in this issue, don't open new issues. 

Assigning to @ariel-phet for prioritization.

**Release Candidate links**

acid-base-solutions 1.2 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [acid-base-solutions 1.2.19-rc.1](https://phet-dev.colorado.edu/html/acid-base-solutions/1.2.19-rc.1/acid-base-solutions_en.html)

area-builder 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [area-builder 1.1.14-rc.1](https://phet-dev.colorado.edu/html/area-builder/1.1.14-rc.1/area-builder_en.html)

area-model-algebra 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [area-model-algebra 1.0.7-rc.1](https://phet-dev.colorado.edu/html/area-model-algebra/1.0.7-rc.1/phet/area-model-algebra_en_phet.html)

area-model-decimals 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [area-model-decimals 1.0.7-rc.1](https://phet-dev.colorado.edu/html/area-model-decimals/1.0.7-rc.1/phet/area-model-decimals_en_phet.html)

area-model-introduction 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [area-model-introduction 1.0.7-rc.1](https://phet-dev.colorado.edu/html/area-model-introduction/1.0.7-rc.1/phet/area-model-introduction_en_phet.html)

area-model-multiplication 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [area-model-multiplication 1.0.7-rc.1](https://phet-dev.colorado.edu/html/area-model-multiplication/1.0.7-rc.1/phet/area-model-multiplication_en_phet.html)

arithmetic 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [arithmetic 1.0.18-rc.1](https://phet-dev.colorado.edu/html/arithmetic/1.0.18-rc.1/arithmetic_en.html)

atomic-interactions 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [atomic-interactions 1.0.12-rc.1](https://phet-dev.colorado.edu/html/atomic-interactions/1.0.12-rc.1/atomic-interactions_en.html)

balancing-act 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [balancing-act 1.1.18-rc.1](https://phet-dev.colorado.edu/html/balancing-act/1.1.18-rc.1/balancing-act_en.html)

balancing-chemical-equations 1.2 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [balancing-chemical-equations 1.2.4-rc.1](https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.2.4-rc.1/phet/balancing-chemical-equations_en_phet.html)

balloons-and-static-electricity 1.3-phetio (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [balloons-and-static-electricity 1.3.11-rc.1 phet-io](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.3.11-rc.1/balloons-and-static-electricity_en-phetio.html?phetioStandalone)
- [ ] [balloons-and-static-electricity 1.3.11-rc.1 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.3.11-rc.1/wrappers/instance-proxies/instance-proxies.html?sim=balloons-and-static-electricity&relativeSimPath)

balloons-and-static-electricity 1.4 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [balloons-and-static-electricity 1.4.9-rc.1](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.4.9-rc.1/phet/balloons-and-static-electricity_en_phet.html)

beers-law-lab 1.4 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [beers-law-lab 1.4.13-rc.1](https://phet-dev.colorado.edu/html/beers-law-lab/1.4.13-rc.1/beers-law-lab_en.html)

bending-light 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [bending-light 1.1.15-rc.1](https://phet-dev.colorado.edu/html/bending-light/1.1.15-rc.1/bending-light_en.html)

build-a-fraction 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [build-a-fraction 1.0.5-rc.1](https://phet-dev.colorado.edu/html/build-a-fraction/1.0.5-rc.1/phet/build-a-fraction_en_phet.html)

build-an-atom 1.4-phetio (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [build-an-atom 1.4.8-rc.1 phet-io](https://phet-dev.colorado.edu/html/build-an-atom/1.4.8-rc.1/build-an-atom_en-phetio.html?phetioStandalone)
- [x] [build-an-atom 1.4.8-rc.1 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/build-an-atom/1.4.8-rc.1/wrappers/instance-proxies/instance-proxies.html?sim=build-an-atom&relativeSimPath)

build-an-atom 1.5-phetio (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [build-an-atom 1.5.13-rc.1 phet-io](https://phet-dev.colorado.edu/html/build-an-atom/1.5.13-rc.1/build-an-atom_en-phetio.html?phetioStandalone)
- [x] [build-an-atom 1.5.13-rc.1 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/build-an-atom/1.5.13-rc.1/wrappers/instance-proxies/instance-proxies.html?sim=build-an-atom&relativeSimPath)

build-an-atom 1.6 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [build-an-atom 1.6.8-rc.1](https://phet-dev.colorado.edu/html/build-an-atom/1.6.8-rc.1/build-an-atom_en.html)

capacitor-lab-basics 1.6 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [capacitor-lab-basics 1.6.14-rc.1](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.14-rc.1/phet/capacitor-lab-basics_en_phet.html)
- [x] [capacitor-lab-basics 1.6.14-rc.1 phet-io](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.14-rc.1/phet-io/capacitor-lab-basics_all_phet-io.html?phetioStandalone)
- [x] [capacitor-lab-basics 1.6.14-rc.1 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.14-rc.1/phet-io/wrappers/instance-proxies/instance-proxies.html?sim=capacitor-lab-basics&relativeSimPath)

charges-and-fields 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [charges-and-fields 1.0.41-rc.1](https://phet-dev.colorado.edu/html/charges-and-fields/1.0.41-rc.1/charges-and-fields_en.html)

circuit-construction-kit-dc 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [circuit-construction-kit-dc 1.0.9-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.0.9-rc.1/circuit-construction-kit-dc_en.html)

circuit-construction-kit-dc-virtual-lab 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [circuit-construction-kit-dc-virtual-lab 1.0.9-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.0.9-rc.1/circuit-construction-kit-dc-virtual-lab_en.html)

color-vision 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [color-vision 1.1.18-rc.1](https://phet-dev.colorado.edu/html/color-vision/1.1.18-rc.1/color-vision_en.html)

concentration 1.3 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [concentration 1.3.15-rc.1](https://phet-dev.colorado.edu/html/concentration/1.3.15-rc.1/concentration_en.html)

coulombs-law 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [coulombs-law 1.0.4-rc.1](https://phet-dev.colorado.edu/html/coulombs-law/1.0.4-rc.1/phet/coulombs-law_en_phet.html)

energy-forms-and-changes 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [energy-forms-and-changes 1.0.6-rc.1](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.0.6-rc.1/phet/energy-forms-and-changes_en_phet.html)

energy-skate-park-basics 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [energy-skate-park-basics 1.1.14-rc.1](https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.1.14-rc.1/energy-skate-park-basics_en.html)

equality-explorer 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [equality-explorer 1.0.7-rc.1](https://phet-dev.colorado.edu/html/equality-explorer/1.0.7-rc.1/phet/equality-explorer_en_phet.html)

equality-explorer-basics 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [equality-explorer-basics 1.0.7-rc.1](https://phet-dev.colorado.edu/html/equality-explorer-basics/1.0.7-rc.1/phet/equality-explorer-basics_en_phet.html)

equality-explorer-two-variables 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [equality-explorer-two-variables 1.0.7-rc.1](https://phet-dev.colorado.edu/html/equality-explorer-two-variables/1.0.7-rc.1/phet/equality-explorer-two-variables_en_phet.html)

expression-exchange 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [expression-exchange 1.1.8-rc.1](https://phet-dev.colorado.edu/html/expression-exchange/1.1.8-rc.1/expression-exchange_en.html)

faradays-law 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [faradays-law 1.1.18-rc.1](https://phet-dev.colorado.edu/html/faradays-law/1.1.18-rc.1/faradays-law_en.html)

forces-and-motion-basics 2.3 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [forces-and-motion-basics 2.3.11-rc.1](https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.3.11-rc.1/forces-and-motion-basics_en.html)

fraction-matcher 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [fraction-matcher 1.1.16-rc.1](https://phet-dev.colorado.edu/html/fraction-matcher/1.1.16-rc.1/fraction-matcher_en.html)

fractions-equality 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [fractions-equality 1.0.5-rc.1](https://phet-dev.colorado.edu/html/fractions-equality/1.0.5-rc.1/phet/fractions-equality_en_phet.html)

fractions-intro 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [fractions-intro 1.0.5-rc.1](https://phet-dev.colorado.edu/html/fractions-intro/1.0.5-rc.1/phet/fractions-intro_en_phet.html)

fractions-mixed-numbers 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [fractions-mixed-numbers 1.0.5-rc.1](https://phet-dev.colorado.edu/html/fractions-mixed-numbers/1.0.5-rc.1/phet/fractions-mixed-numbers_en_phet.html)

friction 1.5 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [friction 1.5.5-rc.1](https://phet-dev.colorado.edu/html/friction/1.5.5-rc.1/phet/friction_en_phet.html)

function-builder 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [function-builder 1.0.18-rc.1](https://phet-dev.colorado.edu/html/function-builder/1.0.18-rc.1/function-builder_en.html)

function-builder-basics 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [function-builder-basics 1.0.9-rc.1](https://phet-dev.colorado.edu/html/function-builder-basics/1.0.9-rc.1/function-builder-basics_en.html)

gene-expression-essentials 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [gene-expression-essentials 1.0.9-rc.1](https://phet-dev.colorado.edu/html/gene-expression-essentials/1.0.9-rc.1/gene-expression-essentials_en.html)

graphing-lines 1.3 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [graphing-lines 1.3.4-rc.1](https://phet-dev.colorado.edu/html/graphing-lines/1.3.4-rc.1/phet/graphing-lines_en_phet.html)

graphing-quadratics 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [graphing-quadratics 1.0.4-rc.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.0.4-rc.1/phet/graphing-quadratics_en_phet.html)

graphing-slope-intercept 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [graphing-slope-intercept 1.1.4-rc.1](https://phet-dev.colorado.edu/html/graphing-slope-intercept/1.1.4-rc.1/phet/graphing-slope-intercept_en_phet.html)

gravity-and-orbits 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [gravity-and-orbits 1.1.10-rc.1](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.1.10-rc.1/gravity-and-orbits_en.html)

gravity-force-lab 2.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [gravity-force-lab 2.1.10-rc.1](https://phet-dev.colorado.edu/html/gravity-force-lab/2.1.10-rc.1/gravity-force-lab_en.html)

hookes-law 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [hookes-law 1.0.18-rc.1](https://phet-dev.colorado.edu/html/hookes-law/1.0.18-rc.1/hookes-law_en.html)

isotopes-and-atomic-mass 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [isotopes-and-atomic-mass 1.1.2-rc.1](https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.2-rc.1/phet/isotopes-and-atomic-mass_en_phet.html)

john-travoltage 1.4-phetio (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [john-travoltage 1.4.11-rc.1 phet-io](https://phet-dev.colorado.edu/html/john-travoltage/1.4.11-rc.1/john-travoltage_en-phetio.html?phetioStandalone)
- [x] [john-travoltage 1.4.11-rc.1 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/john-travoltage/1.4.11-rc.1/wrappers/instance-proxies/instance-proxies.html?sim=john-travoltage&relativeSimPath)

john-travoltage 1.5 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [john-travoltage 1.5.7-rc.1](https://phet-dev.colorado.edu/html/john-travoltage/1.5.7-rc.1/phet/john-travoltage_en_phet.html)

least-squares-regression 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [least-squares-regression 1.1.15-rc.1](https://phet-dev.colorado.edu/html/least-squares-regression/1.1.15-rc.1/least-squares-regression_en.html)

make-a-ten 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [make-a-ten 1.0.11-rc.1](https://phet-dev.colorado.edu/html/make-a-ten/1.0.11-rc.1/make-a-ten_en.html)

masses-and-springs 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [masses-and-springs 1.0.5-rc.1](https://phet-dev.colorado.edu/html/masses-and-springs/1.0.5-rc.1/phet/masses-and-springs_en_phet.html)

masses-and-springs-basics 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [masses-and-springs-basics 1.0.4-rc.1](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.4-rc.1/phet/masses-and-springs-basics_en_phet.html)

molarity 1.4 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [molarity 1.4.7-rc.1](https://phet-dev.colorado.edu/html/molarity/1.4.7-rc.1/phet/molarity_en_phet.html)
- [x] [molarity 1.4.7-rc.1 phet-io](https://phet-dev.colorado.edu/html/molarity/1.4.7-rc.1/phet-io/molarity_all_phet-io.html?phetioStandalone)
- [x] [molarity 1.4.7-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molarity/1.4.7-rc.1/phet-io/wrappers/studio/studio.html?sim=molarity&relativeSimPath)

molecule-polarity 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [molecule-polarity 1.0.10-rc.1](https://phet-dev.colorado.edu/html/molecule-polarity/1.0.10-rc.1/molecule-polarity_en.html)

molecule-shapes 1.2 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [molecule-shapes 1.2.3-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes/1.2.3-rc.1/phet/molecule-shapes_en_phet.html)

molecule-shapes-basics 1.2 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [molecule-shapes-basics 1.2.3-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.3-rc.1/phet/molecule-shapes-basics_en_phet.html)

molecules-and-light 1.4 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [molecules-and-light 1.4.9-rc.1](https://phet-dev.colorado.edu/html/molecules-and-light/1.4.9-rc.1/molecules-and-light_en.html)

neuron 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [neuron 1.1.13-rc.1](https://phet-dev.colorado.edu/html/neuron/1.1.13-rc.1/neuron_en.html)

ohms-law 1.4 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [ohms-law 1.4.1-rc.1](https://phet-dev.colorado.edu/html/ohms-law/1.4.1-rc.1/phet/ohms-law_en_phet.html)

pendulum-lab 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [pendulum-lab 1.0.10-rc.1](https://phet-dev.colorado.edu/html/pendulum-lab/1.0.10-rc.1/pendulum-lab_en.html)

ph-scale 1.2 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [ph-scale 1.2.19-rc.1](https://phet-dev.colorado.edu/html/ph-scale/1.2.19-rc.1/ph-scale_en.html)

ph-scale-basics 1.2 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [ph-scale-basics 1.2.19-rc.1](https://phet-dev.colorado.edu/html/ph-scale-basics/1.2.19-rc.1/ph-scale-basics_en.html)

plinko-probability 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [plinko-probability 1.1.13-rc.1](https://phet-dev.colorado.edu/html/plinko-probability/1.1.13-rc.1/plinko-probability_en.html)

projectile-motion 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [projectile-motion 1.0.10-rc.1](https://phet-dev.colorado.edu/html/projectile-motion/1.0.10-rc.1/projectile-motion_en.html)

proportion-playground 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [proportion-playground 1.0.10-rc.1](https://phet-dev.colorado.edu/html/proportion-playground/1.0.10-rc.1/proportion-playground_en.html)

reactants-products-and-leftovers 1.2 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [reactants-products-and-leftovers 1.2.5-rc.1](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.2.5-rc.1/phet/reactants-products-and-leftovers_en_phet.html)

resistance-in-a-wire 1.3-phetio (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [resistance-in-a-wire 1.3.8-rc.1 phet-io](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.3.8-rc.1/resistance-in-a-wire_en-phetio.html?phetioStandalone)
- [x] [resistance-in-a-wire 1.3.8-rc.1 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.3.8-rc.1/wrappers/instance-proxies/instance-proxies.html?sim=resistance-in-a-wire&relativeSimPath)

resistance-in-a-wire 1.6 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [resistance-in-a-wire 1.6.4-rc.1](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.4-rc.1/phet/resistance-in-a-wire_en_phet.html)

rutherford-scattering 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [rutherford-scattering 1.1.4-rc.1](https://phet-dev.colorado.edu/html/rutherford-scattering/1.1.4-rc.1/phet/rutherford-scattering_en_phet.html)

states-of-matter 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [states-of-matter 1.1.5-rc.1](https://phet-dev.colorado.edu/html/states-of-matter/1.1.5-rc.1/phet/states-of-matter_en_phet.html)

states-of-matter-basics 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [states-of-matter-basics 1.1.3-rc.1](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.1.3-rc.1/phet/states-of-matter-basics_en_phet.html)

trig-tour 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [trig-tour 1.0.17-rc.1](https://phet-dev.colorado.edu/html/trig-tour/1.0.17-rc.1/trig-tour_en.html)

under-pressure 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [under-pressure 1.1.13-rc.1](https://phet-dev.colorado.edu/html/under-pressure/1.1.13-rc.1/under-pressure_en.html)

unit-rates 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [unit-rates 1.0.12-rc.1](https://phet-dev.colorado.edu/html/unit-rates/1.0.12-rc.1/unit-rates_en.html)

wave-interference 1.0 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [wave-interference 1.0.5-rc.1](https://phet-dev.colorado.edu/html/wave-interference/1.0.5-rc.1/phet/wave-interference_en_phet.html)

wave-on-a-string 1.1 (https://github.com/phetsims/phet-ios-app/issues/484)

- [x] [wave-on-a-string 1.1.17-rc.1](https://phet-dev.colorado.edu/html/wave-on-a-string/1.1.17-rc.1/wave-on-a-string_en.html)

**Comment by ariel-phet** [comment]
@KatieWoe since this supports the iOS app, this should be current top priority

**Comment by KatieWoe** [comment]
https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.3.11-rc.1/wrappers/instance-proxies/instance-proxies.html?sim=balloons-and-static-electricity&relativeSimPath is incredibly laggy.

**Comment by KatieWoe** [comment]
Same with https://phet-dev.colorado.edu/html/build-an-atom/1.4.8-rc.1/wrappers/instance-proxies/instance-proxies.html?sim=build-an-atom&relativeSimPath.  The phet-io instances proxies in general may have this problem.

**Comment by etwa4650** [comment]
@KatieWoe Im not seeing any lag on my device. (Mac OS 10.14 & Chrome)

**Comment by KatieWoe** [comment]
Ok.  I'll try resetting or something.  But its very consistent for me on Win 10 chrome, and only on the instance proxie pages

**Comment by KatieWoe** [comment]
Other than that, QA is done

**Comment by chrisklus** [comment]
Thanks @KatieWoe and @etwa4650! All of the production links work as well, so I'm going to close here.
