### ISSUE TITLE
Dev test: circuit-construction-kit-dc/1.1.0-dev.8 and circuit-construction-kit-dc-virtual-lab/1.1.0-dev.2

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#361]
@ariel-phet, circuit-construction-kit-dc/1.1.0-dev.8 and circuit-construction-kit-dc-virtual-lab/1.1.0-dev.2 are ready for dev testing. 
We will need a usable dev version for use in a class on July 15, so testing should complete before then with enough time to address discovered issues. Document issues in https://github.com/phetsims/circuit-construction-kit-common/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.

<h3>Focus and Special Instructions</h3>

This version introduces the fuse.  Prior dev tests were completed in 
https://github.com/phetsims/QA/issues/311
https://github.com/phetsims/QA/issues/314

Test all of the features related to the fuse, including but not limited to creating, deleting,
resetting, changing current rating. Test in combination with other simulation features.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[CCK DC](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.1.0-dev.8/phet/circuit-construction-kit-dc_en_phet.html)**
- **[Virtual Lab](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.1.0-dev.2/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe marking as top priority given the timeline mentioned above

**Comment by KatieWoe** [comment]
Memory Test Results.  @samreid some of these are a bit worrying, but I didn't see a crash.  I'll leave it up to you if it is at all worth pursuing.

**CCK**
Start: 28.6
1 min: 66.3
2 min: 93.5
3 min: 71.1
4 min: 121
5 min: 101
6 min: 114
7 min:130
8 min: 130
9 min: 104
10 min: 120

**CCK VL**
Start: 18.1
1 min: 42.4
2 min: 74.7
3 min: 38.1
4 min: 55.2
5 min: 90.9
6 min: 54.6
7 min:57.0
8 min: 132
9 min: 106
10 min: 53.8

**Comment by samreid** [comment]
The memory results are volatile because of the large number of created and disposed components.  The low values in the preceding comment are likely recently after the reset button has been pressed. In https://github.com/phetsims/circuit-construction-kit-common/issues/499#issuecomment-506921285 we described a procedure to temporarily disable fuzzing so the simulation can be reset before a memory snapshot is taken (may be useful in the future or in other simulations).  Based on these results, I don't think further memory investigation is necessary for this dev test.

**Comment by KatieWoe** [comment]
Doesn't seem to be anything new since the last dev test.  QA is done.

**Comment by samreid** [comment]
Excellent, thanks!  Closing.
