### ISSUE TITLE
RC Test: Graphing Quadratics 1.1.0-rc.1 PhET-iO

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#366]
@pixelzoom @kathy-phet @amanda-phet @arouinfar @samreid @chrisklus @zepumph, graphing-quadratics/1.1.0-rc.1 is ready for RC testing. 
The goal is to have this sim published by Friday, July 19th. Document issues in https://github.com/phetsims/graphing-quadratics/issues or https://github.com/phetsims/phet-io/issues (if appropriate) and link to this issue. This simulation is the first phet-io publication in over two years. Good work team for getting this far!

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.0-rc.1/phet/graphing-quadratics_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.0-rc.1/phet/graphing-quadratics_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.0-rc.1/phet/xhtml/graphing-quadratics_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/178AxwmvOyQXFRqCYWnLGsbDiZFDsfLagE2T7cnJn8Dc/edit#gid=1074992345)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>PhET-iO RC Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
	- Please give extra focus to studio, mirror-inputs, and state wrapper.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make sure the simulation loads without crashing or throwing errors.

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.0-rc.1/phet-io/)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1wIL0Q4B2A3Tr-cmRFrQ_3QHlIN_aKNJaRssHj1qkcVo/edit#gid=559865388)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Testers: General matrix is up.  PhET-iO matrix will go up as well as an update to the QA book with diff wrapper instructions.  Will update this comment when that is finished.

**Comment by KatieWoe** [comment]
Diff wrapper instructions, now in QA book:
>Dif Wrapper Test
What? This is a wrapper that allows you to compare the differences between a previous build and the current build.
How? To test this wrapper you will need to test two different cases by entering a url into the box. The first url should be for the wrapper currently being tested, and it should show no differences. The second url will be provided in the issue and should show some difference.

Note that there is no usable second url at this time.  So for this test just use the first url (the wrapper url we are currently testing.)  If this changes I will let you know and post the new url.

**Comment by KatieWoe** [comment]
@ariel-phet since this is such a long RC (phet-io) and is on a tight schedule I'm going to move it to top priority unless you have any objections.

**Comment by KatieWoe** [comment]
Metacog recording should only be done by:
- [ ] Win 10 chrome
- [ ] Mac 10.4 safari
- [ ] Chrome OS

The URL is: https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.0-rc.1/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&encryption=encryptNumberV1&numberOfDigits=9&publisher_id=5d4c8ae1&key_name=phet-study_2018_q4&widget_id=graphing-quadratics-test_rc&phetioEmitInputEvents=true&phetioEmitStates=true&phetioEmitStatesInterval=60&metacog
See Katie for the id to get the data

**Comment by KatieWoe** [comment]
On Edge (Phet Brand) I am seeing a fairly sizable https://github.com/phetsims/energy-forms-and-changes/issues/203 style issues where parts of the line will disappear or be drawn outside of the graph.

**Comment by ariel-phet** [comment]
@KatieWoe that does not warrant an issue, I think we are going to generally ignore odd rendering issues on Edge and wait them out until the chromium version unless they are truly egregious. It seems the issues you had discussed were happening every now and then, not all the time.

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
Since all of the issues discovered during this RC have been addressed, we are planning to maintenance patch the fixes into the RC branch, publish an RC and have it spot checked.
