### ISSUE TITLE
Dev Test: Charges and Fields [+PhET-iO]

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#37]
In late 2016, Charges and Fields PhET-iO went through an RC for a PhET-iO version, see https://github.com/phetsims/tasks/issues/736

5 issues were raised, 3 of which have been fixed and verified.  The remaining 2 issues are: 

- [x] https://github.com/phetsims/phet-io/issues/915
- [x] https://github.com/phetsims/phet-io/issues/914

which are fixed and pending testing.

I noticed that the QA team has several other issues on their radar at the moment, so I was hesitant to create a new dev version now (as noted in https://github.com/phetsims/phet-io/issues/863#issuecomment-322341631 ).  The aforementioned issues may be tested in phettest.colorado.edu but before we go to full dev or RC testing, but when the priority/time is right for this issue, let @samreid or @zepumph know and they will create you a dev version on the spot.

Reassigned to @ariel-phet for prioritization, scheduling, delegation and labeling.

**Comment by samreid** [comment]
One other point, I think we are trying to get into a pattern where we test the non-phet-io and the phet-io versions and publish them simultaneously.

**Comment by zepumph** [comment]
To put it in terms of https://github.com/phetsims/QA/issues/19, this seems to be the type of phet-io dev test that will be moving on to an RC.

**Comment by samreid** [comment]
From https://github.com/phetsims/QA/issues/19#issuecomment-320722872


*It is assumed, in this case, that all wrappers will be tested. At least one browser per device listed [here](https://docs.google.com/spreadsheets/d/1o5txil6dVHk1BfHA3fT5LIQc19JBSOg0v-BYBQe9A7A/edit#gid=2) will be tested.*

- Mention the appropriate designers: @arouinfar (sim) and @samreid + @zepumph (phet-io)
- Note the purpose of this sim (general release, for a study, etc...).: PhET-iO release
- Sim version wrapper index link (will be published when QA team is ready)
- A complete checklist of any issues to be verified: provided in top comment
- Any relevant deadlines.  @kathy-phet said it would be good to have 20 PhET-iO sims by Jan 1, 2018, and yesterday @kathy-phet said: 

> Finishing up charges and field phet-io was also in you possible list. This would be good to make available, so if it fits to wrap that up then that would be good.

**Comment by ariel-phet** [comment]
Medium priority until some of the current high priority items finish off (CCK, projectile motion, pendulum lab)

**Comment by samreid** [comment]
I published a dev version here:
http://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.1.0-phetiodev.1/wrappers/index/

**Comment by samreid** [comment]
I published a new dev version as described in https://github.com/phetsims/charges-and-fields/issues/130#issuecomment-324766969

**Comment by phet-steele** [comment]
@samreid @zepumph This got pretty decent coverage.  I hesitate to say this dev version is done testing though. It would probably be a better idea to get a new dev version before continuing than to keep going with this dev version. @samreid would you like to do another IOU until CCK is finished?

**Comment by samreid** [comment]
Sounds good, let me know when you are ready for the next dev version.

**Comment by samreid** [comment]
Next dev versions should include LOL features in joist.

**Comment by ariel-phet** [comment]
Closing this issue. iO has changed quite a bit, and this issue is stale.
