### ISSUE TITLE
Add dev tools error reporting to the QA book?

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#372]
@samreid @chrisklus and @zepumph were wondering if we could add console error to github issues when applicable. Perhaps in the QA book somewhere it could read, "if using a device with developer tools, check the console and report any errors there with the Github issue. Note that most of the time the first error or two is the most important."  What do you think?

**Comment by KatieWoe** [comment]
I'll add it during the next round of edits.

**Comment by phet-steele** [comment]
This section used to exist, but this document has been out of my hands for a while so I couldn't tell you what happened to it:

> Opening the Console
The console is a workspace which shows and allows access to the internal workings of a webpage. It is used often in testing to make sure that the sim is doing what it should be. To access the console, right click and click on the option which says Inspect, or Inspect Element. Then click the console button. The hotkey for Mac is Command+Option+i and for Windows is Control+Shift+i.

and then a reminder later:

> make sure to have the console open! It is either helpful or required for the testing. Refer to the Opening the Console section to see how to open a console on your browser.

**Comment by KatieWoe** [comment]
Done.  Closing
