### ISSUE TITLE
Spot check: Graphing Quadratics 1.1.0-rc.4

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#373]
We cherry picked commits from issues fixed in the prior testing issue, https://github.com/phetsims/QA/issues/366, Please spot check the following issues:

- [x] https://github.com/phetsims/phet-io/issues/1529
- [x] https://github.com/phetsims/phet-io/issues/1530
- [x] https://github.com/phetsims/phet-io/issues/1531
- [x] https://github.com/phetsims/graphing-quadratics/issues/134

From here we will publish phet and phet-io brands.

Sim: https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.0-rc.4/phet/graphing-quadratics_all_phet.html

Wrapper index: https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.0-rc.4/phet-io

**Comment by zepumph** [comment]
Sorry I forgot to tag @samreid @chrisklus @pixelzoom @kathy-phet @ariel-phet.

**Comment by samreid** [comment]
@KatieWoe checked off all of the aforementioned issues.  Perhaps this means QA is complete and this is ready for production publication?

**Comment by KatieWoe** [comment]
I'm checking some of the other aspects and was going to do a quick check on a Mac this morning, but if you're happy with it, then I don't feel too bad stopping.  Otherwise, I'll be done before status, or just after.

**Comment by samreid** [comment]
Please take your time and let us know how it goes, thanks!

**Comment by KatieWoe** [comment]
We are done.

**Comment by zepumph** [comment]
Thanks @KatieWoe!

**Comment by zepumph** [comment]
T
