### ISSUE TITLE
Dev Test: wave-interference/2.0.0-dev.7 and wave-intro/1.0.0-dev.10

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#389]
@ariel-phet @KatieWoe @kathy-phet and @arouinfar, wave-interference/2.0.0-dev.7 and wave-intro/1.0.0-dev.10 are ready for dev testing. In previous discussion, we have said RC testing Aug 1 would be good and that it would be good to publish Wave Interference by the end of summer.  I have combined these two tests since they have the same SHAs and will be maintained together.  Please document issues in https://github.com/phetsims/wave-interference/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- If there is a console available, check for errors and include them in the Problem Description.

<h3>Focus and Special Instructions</h3>

In Wave Interference, there are two main new features.  (a) the "Diffraction" screen, which has previously been through a dev test in https://github.com/phetsims/QA/issues/322 and (b) which is the "Play Tone" feature in the Waves Screen.  However, other features in all screens have changed, so the sim will need a thorough test.  Waves Intro is a new sim which shows one scene per screen and also has the "Play Tone" feature.  This is the first dev test for Waves Intro.  No PhET-iO or A11y for either sim in this dev test.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Link(s)</h3>

- **[Wave Interference 2.0.0-dev.7](https://phet-dev.colorado.edu/html/wave-interference/2.0.0-dev.7/phet/wave-interference_en_phet.html)**
- **[Waves Intro 1.0.0-dev.10](https://phet-dev.colorado.edu/html/waves-intro/1.0.0-dev.10/phet/waves-intro_en_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe this would be the next priority after Gas properties testing

**Comment by arouinfar** [comment]
@samreid dev.9 of Waves Intro includes the "Sound Effect" checkbox for the light source sonification. Since the sound design (except for Play Tone) has been deferred for 1.0, this checkbox should not be included in the simulation.

**Comment by samreid** [comment]
Thanks @arouinfar, I published dev.7 and dev.10 to remove the "Sound Effect" button for this dev test.  @KatieWoe please be aware I incremented these versions for testing.

**Comment by KatieWoe** [comment]
Large amount of lag on 4th screen in Edge is fairly large.  I'm guessing we're not concerned enough for an issue @ariel-phet?

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
@KatieWoe I didn't notice any comments specifically related to "Waves Intro" and wanted to double check that it was included during this testing.

**Comment by KatieWoe** [comment]
@samreid yes it was.  A few of the issues do say "applies to both sims" or only applies to ___, etc.

**Comment by samreid** [comment]
Excellent, thanks for confirming.  I'll leave this issue open to track the related issues until we're ready for RC.

**Comment by samreid** [comment]
All issues discovered during dev testing have been closed or deferred, thanks! Closing.
