### ISSUE TITLE
RC Test: Projectile Motion 1.0.0-rc.1

### ISSUE THREAD

**Issue by andrea-phet** [phetsims/QA#39]
@ariel-phet @arouinfar , Projectile Motion 1.0.0-rc.1 is ready for RC testing.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-rc.1/projectile-motion_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.0-rc.1/projectile-motion_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1XlyFnVFVxdWvkLsx-WDeTEZqg0o-rrNw_Epx2tLPJoc/edit#gid=2)**

**Please verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any new issues are found, please note them in https://github.com/phetsims/projectile-motion/issues and reference this issue.  

 
**(Other potentially useful items)**  

No sim-specific query parameters

Sim-specific terminology:  
• tracer - the blue tool you can drag from the toolbox and use to view information about trajectories

**Comment by ariel-phet** [comment]
@phet-steele this should be a high priority, right behind CCK testing (ideally in parallel with finishing off CCK testing)

**Comment by phet-steele** [comment]
@pixelzoom @andrea-phet @ariel-phet @arouinfar Testing done, see above scenery-phet issue.

**Comment by andrea-phet** [comment]
Thanks @phet-steele , closing.

**Comment by pixelzoom** [comment]
Reopening.  

@andrea-phet When a release candidate has not passed, we typically leave the RC test issue open until the next RC issue is created, so we can easily see which related issues need to be regressed.  

We (you and I) should discuss how to proceed with the next RC.  Because of phetsims/scenery-phet#332, we could either (1) pull in master of everything and do a full test matrix, or (2) try to branch and patch the scenery-phet and do a spot test.

**Comment by pixelzoom** [comment]
@andrea-phet I believe that we're ready for the next RC (1.0.0-rc.2).   

When you build 1.0.0-rc.2, you'll need to substitute the branch of scenery-phet that's mentioned in https://github.com/phetsims/scenery-phet/issues/332#issuecomment-324421158.  After the `grunt checkout-shas` step, go to scenery-phet and do `git checkout projectile-motion-1.0`.  

The full steps for the build are:

```
% cd projectile-motion
% git checkout 1.0
% git pull
(set version id to "1.0.0-rc.2" in package.json, commit, push)
% cd ../perennial
% grunt checkout-shas --repo=projectile-motion
% cd ../scenery-phet
% git checkout projectile-motion-1.0
(test requirejs version)
% cd ../projectile-motion
% grunt
(test built version)
% grunt deploy-rc
% cd ../perennial
% grunt checkout-shas --repo=projectile-motion
% cd ../projectile-motion
% git checkout master
``` 

When you create the new QA issue using [rc-test-template.md](https://github.com/phetsims/QA/blob/master/issue-templates/rc-test-template.md), under "Issues To Verify" include the 5 issues shown above https://github.com/phetsims/QA/issues/39#issuecomment-323830718. Mention that the RC requires only spot testing on a few platforms, not a full test matrix.

**Comment by pixelzoom** [comment]
I just saw @andrea-phet's slack message asking me if I could publish 1.0.0-rc.2, so I'll take care of that.

**Comment by pixelzoom** [comment]
1.0.0-rc.2 has been created, see https://github.com/phetsims/QA/issues/44.  Closing.
