### ISSUE TITLE
Dev test: Energy Skate Park 1.0.0-dev.4

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#397]
@arouinfar, @ariel-phet energy-skate-park/1.0.0-dev.4 is ready for dev testing. This is the first dev test of energy-skate-park, although the sim is quite similar to energy-skate-park-basics. The largest changes from the basics version are that you can record skater data (Measure screen and Graphs screens) play back skater states from graphs (Graphs screen), as well as change gravity and skater mass. Please test these new features thoroughly in particular. It would also be helpful to get a sense of sim performance, please test this sim on an array of slow platforms and report results. Finally, document any issues in https://github.com/phetsims/energy-skate-park/issues and link to this issue. Thanks!

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- If there is a console available, check for errors and include them in the Problem Description.
- Rung through the string tests on at least one platform, especially if it is about to go to rc.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested, list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.4/phet/energy-skate-park_all_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by arouinfar** [comment]
Exciting to see this going up for a dev test! 

@jessegreenberg @ariel-phet @KatieWoe I need to focus on the upcoming workshop I'll be giving in Peru 8/16. I likely won't be very responsive on GitHub for the next two weeks, but if anything blocking comes up, please let me know.

**Comment by KatieWoe** [comment]
Seeing https://github.com/phetsims/energy-skate-park-basics/issues/440 here too.  I'm guessing it should be deffered as well.  @ariel-phet @jessegreenberg let me know if you want a new issue for this.
![morepointy](https://user-images.githubusercontent.com/41024075/63127153-e8874e00-bf6e-11e9-9398-eba452b62484.png)
![pointytracks](https://user-images.githubusercontent.com/41024075/63127154-e8874e00-bf6e-11e9-9f9c-17ba7af8d612.png)

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Awesome, thank you for the testing @KatieWoe and team. In the original ticket
> It would also be helpful to get a sense of sim performance, please test this sim on an array of slow platforms and report results.

I didn't see anything mentioned so just checking in, did you notice any performance issues on slow platforms @KatieWoe?

**Comment by KatieWoe** [comment]
Sorry, I missed that.  I'm going to do a quick second check.

**Comment by KatieWoe** [comment]
Looks acceptable on IE, iOS 9 and iOS 10

**Comment by jessegreenberg** [comment]
OK, that is great to hear @KatieWoe. Thank you for checking.
