### ISSUE TITLE
RC Test: Resistance In A Wire 1.3.0-rc.1 and 1.3.0-phetiorc.1

### ISSUE THREAD

**Issue by phet-steele** [phetsims/QA#4]
Phet link:
http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-rc.1/resistance-in-a-wire_en.html

PhET-iO link to wrappers index (password protected and hidden in the parent version dir):
http://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-phetiorc.1/wrappers/index

These two versions were just created from master shas. The sim was newly instrumented for PhET-iO and went through major code refactoring and review in the process (thanks @samreid @veillette for all the help), so it will be useful to publish a phet version while we are at it. 

Please reference this issue in any related issues that are created.

There are no sim-specific query parameters.

Assigning to @ariel-phet for priority and delegation.

**Comment by phet-steele** [comment]
We need to maintenance these shas into these releases

phetsims/scenery-phet@f210433
phetsims/scenery-phet@727d5bd

**Comment by phet-steele** [comment]
Discussed with @zepumph, this sim will be given the same treatment as Molarity. The move to rc before dev was not ideal, so we will be closing this issue and starting with a 1.3.0-phetiodev.1. After that passes, we can move on to RCs for both brands. Assigning to @zepumph to deploy the needed version.

**Comment by zepumph** [comment]
Taken care of in #88, closing because these rc's will be stale by the time new rc's come out. We will start with rc.2 then.
