### ISSUE TITLE
Dev Test: PhET-iO Layout changes

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#40]
In https://github.com/phetsims/phet-io/issues/749 @phet-steele discovered that full-page iframes did not lay out correctly.  I proposed a fix which was at odds with https://github.com/phetsims/phet-io/issues/507 but appears to be working in the latest version of chrome.  So the dev version published in https://github.com/phetsims/phet-io/issues/749#issuecomment-323787689 needs to be tested.

Reassigned to @ariel-phet for prioritization, scheduling, delegation.

**Comment by samreid** [comment]
The only things that need to be tested are the full-size iframes, such as the "recording" wrapper.  But it should be tested on all supported platforms.

**Comment by EthanWJohnson** [comment]
All the frames are working and i'm not seeing any clipping whatsoever.

**Comment by samreid** [comment]
Excellent, thanks! Closing.
