### ISSUE TITLE
Test Spanish+English installers for Peru workshop

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#402]
Fresh installers have been requested for an upcoming workshop, see https://github.com/phetsims/installer-builder/issues/243.  I set up an overnight cron job to build the versions with Spanish as the primary language and English as an option, and it appears to have succeeded.  These installers should be tested so that we're sure they work.

Our current understanding is that only the Windows versions are going to be used, so for now the tests should be for the with-activities and without-activities Windows OS versions, and the MacOS and Linux versions can be ignored.

The installers can be found at https://bayes.colorado.edu/dev/multi-language-installer/es-en_2019-08-09/.

**Comment by KatieWoe** [comment]
Clicking index in the main file leads to the English, not the Spanish, main page.  This was seen in the "with-activities" version.

**Comment by KatieWoe** [comment]
Tested both is English and Spanish.  Passes installer tests.  Only problem I found was https://github.com/phetsims/QA/issues/402#issuecomment-520008898

**Comment by jbphet** [comment]
Thanks @KatieWoe.  Can you check if there is an issue in the installer-builder repo for the issue you described above and, if not, create one?  From our conversation, it sounded like you were aware of some history surrounding this.  After that, this issue can be closed.
