### ISSUE TITLE
Test English+Spanish installers for Peru workshop

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#403]
This is the sister issue of #402.  There are four configurations of installers needed for an upcoming workshop in Peru, and this GitHub issue is for testing two of them:
+ English as primary language, Spanish as an option, no activities
+ English as primary language, Spanish as an option, with activities

Only Windows OS versions need to be tested, at least for now.

The installers have been successfully built and are available at https://bayes.colorado.edu/dev/multi-language-installer/en-es_2019-08-10/.

**Comment by KatieWoe** [comment]
Looks good

**Comment by jbphet** [comment]
Thanks @KatieWoe.
