### ISSUE TITLE
RC Test: Energy Skate Park: Basics for LOL

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#41]
In https://github.com/phetsims/energy-skate-park-basics/issues/375 @kathy-phet recommended publishing Energy Skate Park: Basics for Legends of Learning.  I tested that master in Mac Chrome works correctly with the "pause in 5 seconds" when dragging the skater, track or track vertices, and that pausing works correctly.  We will need to do a RC test on this sim to make sure nothing was disturbed and that LOL is still good to go (cross-platform).  The sim would be republished on the PhET website.  Also, this is a phet-io sim, and according to our recent decisions on publishing, we should fully retest the PhET-iO features.  This may be an unfortunate use of time if we decide not to share the tested PhET-iO version with collaborators for fear of breaking APIs.

I'm scheduling this as an "I owe you an RC" release, please give me (or someone else on the development team) a 30-minute warning before you are ready to start testing and we'll publish a fresh version.

Assigned to @ariel-phet for scheduling, prioritization and delegation.

EDIT: changed "may wish to fully retest" to "should fully retest"

**Comment by phet-steele** [comment]
@samreid @zepumph we are ready for a phet-io rc! (probably a new issue to track it?)

**Comment by samreid** [comment]
Let me ask around if master is stable.

**Comment by samreid** [comment]
I also asked: I’m supposed to publish an Energy Skate Park: Basics RC for PhET-iO and PhET brand.  Do we use 2 branches still?

**Comment by samreid** [comment]
@jessegreenberg replied:

Master is stable as far as I know
And yes, my understanding is that we are still doing 2 branches for phet and phetio brands

**Comment by samreid** [comment]
In https://github.com/phetsims/energy-skate-park-basics/issues/379 I prepared the versions for testing.  Since the instructions are above, we can use this issue for testing (I think).

PhET-iO version deployed here:
http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.4.0-phetiorc.1/wrappers/index/

PhET version deployed here:
http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.4.0-rc.1/energy-skate-park-basics_en.html

**Comment by phet-steele** [comment]
@samreid we are going to test phet-io first and it would be good to have its own issue. I'll make it and move the priority label there and take off this one (to avoid confusion).

**Comment by phet-steele** [comment]
phet-io test is in #50. We should wait until that passes before proceeding with the phet version.

**Comment by samreid** [comment]
Please hold off on testing until I can patch in a joist fix.

**Comment by ariel-phet** [comment]
@jessegreenberg this issue is pretty stale, and may have been superceded by recent testing. Assigning to you to sort out given that you are now in the driver's seat for this sim.

**Comment by jessegreenberg** [comment]
Sim received dev testing prior to release for LoL/PhET-iO. Issues were found from that and we still need to dev test PhET-iO brand prior to release. That is being tracked in other issues so closing this one.
