### ISSUE TITLE
RC test Forces and Motion: Basics 2.3.0-phetiorc.3

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#42]
@samreid @zepumph @kathy-phet @ariel-phet Forces and Motion: Basics 2.3.0-phetiorc.3 is ready for RC testing.

This RC has master SHA's so a full RC test is required (even though we are starting on rc.3).  This RC is to support adding Legends of Learning features to Forces and Motion: Basics. Since FAMB is a phetio sim, we need to deploy a phet-io version at the same time. Rather than deploy both PhET and PhET-iO RCs now, we are starting with the phetio version so that we won't have to create two new RC's if issues are found.  Here is the link to index.

[Root Directory](http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-phetiorc.3/)

[Testing Matrix](https://docs.google.com/spreadsheets/d/1u6QGleGnexfDMvASBiGq8daSHfcTge6fRvqDoLIzoJw/edit#gid=1458813081)

If any new issues are found, please note them in phetsims/forces-and-motion-basics/issues and reference this issue.

Assigning @phet-steele and @ariel-phet to assign priority for testing.

**Comment by jessegreenberg** [comment]
Forgot to link in the issue, these issues should have been fixed from the previous RC, @phet-steele can you please verify?

- [ ] https://github.com/phetsims/forces-and-motion-basics/issues/231
- [ ] https://github.com/phetsims/forces-and-motion-basics/issues/230

**Comment by samreid** [comment]
@ariel-phet will you please iterate through the issues linked above and help identify which are essential to fix before publication, and which should be classified as "aesthetic/non-essential"?

**Comment by ariel-phet** [comment]
@samreid I made comments in issues I thought were non-essential currently

**Comment by samreid** [comment]
Excellent, thanks!

**Comment by jessegreenberg** [comment]
@phet-steele just an update on this issue, changes for the above issues were small or aesthetic so we are going to try to patch fixes and do a spot check RC next (unless big things are found in the remainder of this test).

**Comment by phet-steele** [comment]
@jessegreenberg let's go ahead and get that spot check going.

**Comment by jessegreenberg** [comment]
Sounds good!

**Comment by jessegreenberg** [comment]
rc.4 will need a cherry-pick for https://github.com/phetsims/special-ops/issues/82.

**Comment by jessegreenberg** [comment]
A new RC was created in https://github.com/phetsims/QA/issues/54 this can be closed.
