### ISSUE TITLE
RC Test: Blackbody Spectrum 1.0.4-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#422]
@kathy-phet, @DianaTavares, @arouinfar, @ariel-phet, @KatieWoe, blackbody-spectrum/1.0.4-rc.1 is ready for RC testing. This is a PhET-brand maintenance release from the 1.0 release branch.  This release is driven primarily by a user-reported issue about a problem with the spectral power density (the issue is linked below), and the testing should focus on making sure that this issue is resolved and that no new problems were introduced as a result of the changes.

Since the model was changed, and since the view was changed for different ranges, it is important to verify this on all platforms.  The focus of the testing should be on the shape and size of the curve (more on this below) and on scaling up and down of the axes, particularly the vertical axis.

According to @kathy-phet, this is a high priority, so I will label as such and assign to @KatieWoe.  @ariel-phet can intervene if he disagrees.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version

<h3>Issues to Verify</h3>

- [x] [User feedback: flux values](https://github.com/phetsims/blackbody-spectrum/issues/110)

In order to verify the issue linked about, the curve should be compared to the Flash version of the sim.  The peak of the curve should be roughly the same for this new HTML version and the previous Flash version, whereas the values were quite different for the previous HTML versions.

If the issue is fixed, please assign it to @oliver-phet so that he can be ready to notify translators once the new version is published.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.4-rc.1/phet/blackbody-spectrum_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.4-rc.1/phet/blackbody-spectrum_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.4-rc.1/phet/xhtml/blackbody-spectrum_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1751poga7KGilWooIQiYqGKjjlIoFXpKFqgvLvGUMhzM/edit#gid=260815728)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fblackbody-spectrum%2F1.0.4-rc.1%2Fphet%2Fblackbody-spectrum_all_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
Moving to top priority

**Comment by KatieWoe** [comment]
QA is done.  I admit I don't fully understand the physics of https://github.com/phetsims/blackbody-spectrum/issues/110 so it is a bit hard to check.  But things look ok from what I can see.

**Comment by kathy-phet** [comment]
Just confirming - this looks great to me too!

**Comment by jbphet** [comment]
Thanks QA team!  Neither of the two issues found during the testing are show stoppers, so I am moving forward with publication of this version.  Closing.
