### ISSUE TITLE
Maintenance release testing for iPadOS 13 resizing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#427]
For https://github.com/phetsims/phet-core/issues/64. I'd like the normal "very brief, nothing is horribly wrong" testing per sim, and also ideally that we could test:

1. Sims behave normally in Chrome (or some desktop browser) when resized
2. Sims resize properly on iPadOS 13 (when loaded as portrait, switched to landscape, then switched to portrait again).
3. Sims size properly in full-screen on iPadOS 13. 

Ideally I'd like this done fairly soon, I believe the release planned for the 19th.

acid-base-solutions 1.2 (https://github.com/phetsims/phet-core/issues/64)

- [x] [acid-base-solutions 1.2.22-rc.3](https://phet-dev.colorado.edu/html/acid-base-solutions/1.2.22-rc.3/acid-base-solutions_en.html)

area-builder 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [area-builder 1.1.17-rc.2](https://phet-dev.colorado.edu/html/area-builder/1.1.17-rc.2/area-builder_en.html)

area-model-algebra 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [area-model-algebra 1.0.10-rc.2](https://phet-dev.colorado.edu/html/area-model-algebra/1.0.10-rc.2/phet/area-model-algebra_en_phet.html)

area-model-decimals 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [area-model-decimals 1.0.10-rc.2](https://phet-dev.colorado.edu/html/area-model-decimals/1.0.10-rc.2/phet/area-model-decimals_en_phet.html)

area-model-introduction 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [area-model-introduction 1.0.10-rc.2](https://phet-dev.colorado.edu/html/area-model-introduction/1.0.10-rc.2/phet/area-model-introduction_en_phet.html)

area-model-multiplication 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [area-model-multiplication 1.0.10-rc.2](https://phet-dev.colorado.edu/html/area-model-multiplication/1.0.10-rc.2/phet/area-model-multiplication_en_phet.html)

arithmetic 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [arithmetic 1.0.21-rc.2](https://phet-dev.colorado.edu/html/arithmetic/1.0.21-rc.2/arithmetic_en.html)

atomic-interactions 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [atomic-interactions 1.0.15-rc.2](https://phet-dev.colorado.edu/html/atomic-interactions/1.0.15-rc.2/atomic-interactions_en.html)

balancing-act 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [balancing-act 1.1.21-rc.2](https://phet-dev.colorado.edu/html/balancing-act/1.1.21-rc.2/balancing-act_en.html)

balancing-chemical-equations 1.2 (https://github.com/phetsims/phet-core/issues/64)

- [x] [balancing-chemical-equations 1.2.7-rc.2](https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.2.7-rc.2/phet/balancing-chemical-equations_en_phet.html)

balloons-and-static-electricity 1.3-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [balloons-and-static-electricity 1.3.14-rc.2 phet-io](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.3.14-rc.2/balloons-and-static-electricity_en-phetio.html?phetioStandalone)
- [x] [balloons-and-static-electricity 1.3.14-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.3.14-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=balloons-and-static-electricity&relativeSimPath)

balloons-and-static-electricity 1.4 (https://github.com/phetsims/phet-core/issues/64)

- [x] [balloons-and-static-electricity 1.4.12-rc.2](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.4.12-rc.2/phet/balloons-and-static-electricity_en_phet.html)

beers-law-lab 1.4 (https://github.com/phetsims/phet-core/issues/64)

- [x] [beers-law-lab 1.4.16-rc.2](https://phet-dev.colorado.edu/html/beers-law-lab/1.4.16-rc.2/beers-law-lab_en.html)

beers-law-lab 1.5-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [beers-law-lab 1.5.14-rc.2 phet-io](https://phet-dev.colorado.edu/html/beers-law-lab/1.5.14-rc.2/beers-law-lab_en-phetio.html?phet-io.standalone)
- [x] [beers-law-lab 1.5.14-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/beers-law-lab/1.5.14-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=beers-law-lab&launchLocalVersion)

beers-law-lab 1.6-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [beers-law-lab 1.6.13-rc.2 phet-io](https://phet-dev.colorado.edu/html/beers-law-lab/1.6.13-rc.2/beers-law-lab_en-phetio.html?phetioStandalone)
- [x] [beers-law-lab 1.6.13-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/beers-law-lab/1.6.13-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=beers-law-lab&launchLocalVersion)

bending-light 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [bending-light 1.1.18-rc.2](https://phet-dev.colorado.edu/html/bending-light/1.1.18-rc.2/bending-light_en.html)

blackbody-spectrum 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [blackbody-spectrum 1.0.5-rc.2](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.5-rc.2/phet/blackbody-spectrum_en_phet.html)

build-a-fraction 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [build-a-fraction 1.0.8-rc.2](https://phet-dev.colorado.edu/html/build-a-fraction/1.0.8-rc.2/phet/build-a-fraction_en_phet.html)

build-an-atom 1.4-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [build-an-atom 1.4.11-rc.2 phet-io](https://phet-dev.colorado.edu/html/build-an-atom/1.4.11-rc.2/build-an-atom_en-phetio.html?phetioStandalone)
- [x] [build-an-atom 1.4.11-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/build-an-atom/1.4.11-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=build-an-atom&relativeSimPath)

build-an-atom 1.5-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [build-an-atom 1.5.16-rc.2 phet-io](https://phet-dev.colorado.edu/html/build-an-atom/1.5.16-rc.2/build-an-atom_en-phetio.html?phetioStandalone)
- [x] [build-an-atom 1.5.16-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/build-an-atom/1.5.16-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=build-an-atom&relativeSimPath)

build-an-atom 1.6 (https://github.com/phetsims/phet-core/issues/64)

- [x] [build-an-atom 1.6.11-rc.2](https://phet-dev.colorado.edu/html/build-an-atom/1.6.11-rc.2/build-an-atom_en.html)

capacitor-lab-basics 1.3-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [capacitor-lab-basics 1.3.13-rc.2 phet-io](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.3.13-rc.2/capacitor-lab-basics_en-phetio.html?phet-io.standalone)
- [x] [capacitor-lab-basics 1.3.13-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.3.13-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=capacitor-lab-basics&launchLocalVersion)

capacitor-lab-basics 1.6 (https://github.com/phetsims/phet-core/issues/64)

- [x] [capacitor-lab-basics 1.6.17-rc.2](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.17-rc.2/phet/capacitor-lab-basics_en_phet.html)
- [x] [capacitor-lab-basics 1.6.17-rc.2 phet-io](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.17-rc.2/phet-io/capacitor-lab-basics_all_phet-io.html?phetioStandalone)
- [x] [capacitor-lab-basics 1.6.17-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.17-rc.2/phet-io/wrappers/instance-proxies/instance-proxies.html?sim=capacitor-lab-basics&relativeSimPath)

charges-and-fields 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [charges-and-fields 1.0.45-rc.2](https://phet-dev.colorado.edu/html/charges-and-fields/1.0.45-rc.2/charges-and-fields_en.html)

charges-and-fields 1.0-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [charges-and-fields 1.0.17-rc.2 phet-io](https://phet-dev.colorado.edu/html/charges-and-fields/1.0.17-rc.2/charges-and-fields_en-phetio.html?phet-io.standalone)
- [x] [charges-and-fields 1.0.17-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/charges-and-fields/1.0.17-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=charges-and-fields&launchLocalVersion)

circuit-construction-kit-black-box-study 1.1-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [circuit-construction-kit-black-box-study 1.1.14-rc.2 phet-io](https://phet-dev.colorado.edu/html/circuit-construction-kit-black-box-study/1.1.14-rc.2/circuit-construction-kit-black-box-study_en-phetio.html?phetioStandalone)
- [x] [circuit-construction-kit-black-box-study 1.1.14-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/circuit-construction-kit-black-box-study/1.1.14-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=circuit-construction-kit-black-box-study&relativeSimPath)

circuit-construction-kit-dc 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [circuit-construction-kit-dc 1.1.3-rc.2](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.1.3-rc.2/phet/circuit-construction-kit-dc_en_phet.html)

circuit-construction-kit-dc-virtual-lab 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [circuit-construction-kit-dc-virtual-lab 1.1.3-rc.2](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.1.3-rc.2/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html)

color-vision 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [color-vision 1.1.21-rc.2](https://phet-dev.colorado.edu/html/color-vision/1.1.21-rc.2/color-vision_en.html)

color-vision 1.2-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [color-vision 1.2.13-rc.2 phet-io](https://phet-dev.colorado.edu/html/color-vision/1.2.13-rc.2/color-vision_en-phetio.html?phet-io.standalone)
- [x] [color-vision 1.2.13-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/color-vision/1.2.13-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=color-vision&launchLocalVersion)

concentration 1.3 (https://github.com/phetsims/phet-core/issues/64)

- [x] [concentration 1.3.18-rc.2](https://phet-dev.colorado.edu/html/concentration/1.3.18-rc.2/concentration_en.html)

concentration 1.5-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [concentration 1.5.12-rc.2 phet-io](https://phet-dev.colorado.edu/html/concentration/1.5.12-rc.2/concentration_en-phetio.html?phet-io.standalone)
- [x] [concentration 1.5.12-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/concentration/1.5.12-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=concentration&launchLocalVersion)

coulombs-law 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [coulombs-law 1.0.7-rc.2](https://phet-dev.colorado.edu/html/coulombs-law/1.0.7-rc.2/phet/coulombs-law_en_phet.html)

diffusion 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [diffusion 1.0.2-rc.3](https://phet-dev.colorado.edu/html/diffusion/1.0.2-rc.3/phet/diffusion_en_phet.html)

energy-forms-and-changes 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [energy-forms-and-changes 1.0.9-rc.2](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.0.9-rc.2/phet/energy-forms-and-changes_en_phet.html)

energy-skate-park-basics 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [energy-skate-park-basics 1.1.17-rc.2](https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.1.17-rc.2/energy-skate-park-basics_en.html)

energy-skate-park-basics 1.3-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [energy-skate-park-basics 1.3.12-rc.2 phet-io](https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.3.12-rc.2/energy-skate-park-basics_en-phetio.html?phetioStandalone)
- [x] [energy-skate-park-basics 1.3.12-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/energy-skate-park-basics/1.3.12-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=energy-skate-park-basics&relativeSimPath)

equality-explorer 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [equality-explorer 1.0.10-rc.2](https://phet-dev.colorado.edu/html/equality-explorer/1.0.10-rc.2/phet/equality-explorer_en_phet.html)

equality-explorer-basics 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [equality-explorer-basics 1.0.10-rc.2](https://phet-dev.colorado.edu/html/equality-explorer-basics/1.0.10-rc.2/phet/equality-explorer-basics_en_phet.html)

equality-explorer-two-variables 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [equality-explorer-two-variables 1.0.10-rc.2](https://phet-dev.colorado.edu/html/equality-explorer-two-variables/1.0.10-rc.2/phet/equality-explorer-two-variables_en_phet.html)

expression-exchange 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [expression-exchange 1.1.11-rc.2](https://phet-dev.colorado.edu/html/expression-exchange/1.1.11-rc.2/expression-exchange_en.html)

faradays-law 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [faradays-law 1.1.21-rc.2](https://phet-dev.colorado.edu/html/faradays-law/1.1.21-rc.2/faradays-law_en.html)

faradays-law 1.3-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [faradays-law 1.3.15-rc.2 phet-io](https://phet-dev.colorado.edu/html/faradays-law/1.3.15-rc.2/faradays-law_en-phetio.html?phet-io.standalone)
- [x] [faradays-law 1.3.15-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/faradays-law/1.3.15-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=faradays-law&launchLocalVersion)

forces-and-motion-basics 2.1-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [forces-and-motion-basics 2.1.104-rc.2 phet-io](https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.1.104-rc.2/forces-and-motion-basics_en-phetio.html?phet-io.standalone)
- [x] [forces-and-motion-basics 2.1.104-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.1.104-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=forces-and-motion-basics&launchLocalVersion)

forces-and-motion-basics 2.3 (https://github.com/phetsims/phet-core/issues/64)

- [x] [forces-and-motion-basics 2.3.14-rc.2](https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.3.14-rc.2/forces-and-motion-basics_en.html)

fraction-matcher 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [fraction-matcher 1.1.19-rc.2](https://phet-dev.colorado.edu/html/fraction-matcher/1.1.19-rc.2/fraction-matcher_en.html)

fractions-equality 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [fractions-equality 1.0.8-rc.2](https://phet-dev.colorado.edu/html/fractions-equality/1.0.8-rc.2/phet/fractions-equality_en_phet.html)

fractions-intro 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [fractions-intro 1.0.8-rc.2](https://phet-dev.colorado.edu/html/fractions-intro/1.0.8-rc.2/phet/fractions-intro_en_phet.html)

fractions-mixed-numbers 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [fractions-mixed-numbers 1.0.8-rc.2](https://phet-dev.colorado.edu/html/fractions-mixed-numbers/1.0.8-rc.2/phet/fractions-mixed-numbers_en_phet.html)

friction 1.5 (https://github.com/phetsims/phet-core/issues/64)

- [x] [friction 1.5.8-rc.2](https://phet-dev.colorado.edu/html/friction/1.5.8-rc.2/phet/friction_en_phet.html)

function-builder 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [function-builder 1.0.21-rc.2](https://phet-dev.colorado.edu/html/function-builder/1.0.21-rc.2/function-builder_en.html)

function-builder-basics 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [function-builder-basics 1.0.12-rc.2](https://phet-dev.colorado.edu/html/function-builder-basics/1.0.12-rc.2/function-builder-basics_en.html)

gas-properties 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [gas-properties 1.0.1-rc.3](https://phet-dev.colorado.edu/html/gas-properties/1.0.1-rc.3/phet/gas-properties_en_phet.html)

gases-intro 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [gases-intro 1.0.2-rc.3](https://phet-dev.colorado.edu/html/gases-intro/1.0.2-rc.3/phet/gases-intro_en_phet.html)

gene-expression-essentials 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [gene-expression-essentials 1.0.12-rc.2](https://phet-dev.colorado.edu/html/gene-expression-essentials/1.0.12-rc.2/gene-expression-essentials_en.html)

graphing-lines 1.3 (https://github.com/phetsims/phet-core/issues/64)

- [x] [graphing-lines 1.3.7-rc.2](https://phet-dev.colorado.edu/html/graphing-lines/1.3.7-rc.2/phet/graphing-lines_en_phet.html)

graphing-quadratics 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [graphing-quadratics 1.1.3-rc.2](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.3-rc.2/phet/graphing-quadratics_en_phet.html)
- [x] [graphing-quadratics 1.1.3-rc.2 phet-io](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.3-rc.2/phet-io/graphing-quadratics_all_phet-io.html?phetioStandalone)
- [x] [graphing-quadratics 1.1.3-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.3-rc.2/phet-io/wrappers/studio

graphing-slope-intercept 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [graphing-slope-intercept 1.1.7-rc.2](https://phet-dev.colorado.edu/html/graphing-slope-intercept/1.1.7-rc.2/phet/graphing-slope-intercept_en_phet.html)

gravity-and-orbits 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [gravity-and-orbits 1.1.13-rc.2](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.1.13-rc.2/gravity-and-orbits_en.html)

gravity-force-lab 2.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [gravity-force-lab 2.1.13-rc.2](https://phet-dev.colorado.edu/html/gravity-force-lab/2.1.13-rc.2/gravity-force-lab_en.html)

hookes-law 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [hookes-law 1.0.21-rc.2](https://phet-dev.colorado.edu/html/hookes-law/1.0.21-rc.2/hookes-law_en.html)

isotopes-and-atomic-mass 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [isotopes-and-atomic-mass 1.1.6-rc.2](https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.6-rc.2/phet/isotopes-and-atomic-mass_en_phet.html)

john-travoltage 1.4-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [john-travoltage 1.4.14-rc.2 phet-io](https://phet-dev.colorado.edu/html/john-travoltage/1.4.14-rc.2/john-travoltage_en-phetio.html?phetioStandalone)
- [x] [john-travoltage 1.4.14-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/john-travoltage/1.4.14-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=john-travoltage&relativeSimPath)

john-travoltage 1.5 (https://github.com/phetsims/phet-core/issues/64)

- [x] [john-travoltage 1.5.10-rc.2](https://phet-dev.colorado.edu/html/john-travoltage/1.5.10-rc.2/phet/john-travoltage_en_phet.html)

least-squares-regression 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [least-squares-regression 1.1.18-rc.2](https://phet-dev.colorado.edu/html/least-squares-regression/1.1.18-rc.2/least-squares-regression_en.html)

make-a-ten 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [make-a-ten 1.0.14-rc.2](https://phet-dev.colorado.edu/html/make-a-ten/1.0.14-rc.2/make-a-ten_en.html)

masses-and-springs 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [masses-and-springs 1.0.8-rc.2](https://phet-dev.colorado.edu/html/masses-and-springs/1.0.8-rc.2/phet/masses-and-springs_en_phet.html)

masses-and-springs-basics 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [masses-and-springs-basics 1.0.7-rc.2](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.7-rc.2/phet/masses-and-springs-basics_en_phet.html)

molarity 1.4 (https://github.com/phetsims/phet-core/issues/64)

- [x] [molarity 1.4.10-rc.2](https://phet-dev.colorado.edu/html/molarity/1.4.10-rc.2/phet/molarity_en_phet.html)
- [x] [molarity 1.4.10-rc.2 phet-io](https://phet-dev.colorado.edu/html/molarity/1.4.10-rc.2/phet-io/molarity_all_phet-io.html?phetioStandalone)
- [x] [molarity 1.4.10-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/molarity/1.4.10-rc.2/phet-io/wrappers/studio/studio.html?sim=molarity&relativeSimPath)

molecule-polarity 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [molecule-polarity 1.0.13-rc.2](https://phet-dev.colorado.edu/html/molecule-polarity/1.0.13-rc.2/molecule-polarity_en.html)

molecule-shapes 1.2 (https://github.com/phetsims/phet-core/issues/64)

- [x] [molecule-shapes 1.2.6-rc.2](https://phet-dev.colorado.edu/html/molecule-shapes/1.2.6-rc.2/phet/molecule-shapes_en_phet.html)

molecule-shapes-basics 1.2 (https://github.com/phetsims/phet-core/issues/64)

- [x] [molecule-shapes-basics 1.2.6-rc.2](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.6-rc.2/phet/molecule-shapes-basics_en_phet.html)

molecules-and-light 1.3-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [molecules-and-light 1.3.11-rc.2 phet-io](https://phet-dev.colorado.edu/html/molecules-and-light/1.3.11-rc.2/molecules-and-light_en-phetio.html?phet-io.standalone)
- [x] [molecules-and-light 1.3.11-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/molecules-and-light/1.3.11-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=molecules-and-light&launchLocalVersion)

molecules-and-light 1.4 (https://github.com/phetsims/phet-core/issues/64)

- [x] [molecules-and-light 1.4.12-rc.2](https://phet-dev.colorado.edu/html/molecules-and-light/1.4.12-rc.2/molecules-and-light_en.html)

neuron 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [neuron 1.1.16-rc.2](https://phet-dev.colorado.edu/html/neuron/1.1.16-rc.2/neuron_en.html)

ohms-law 1.4 (https://github.com/phetsims/phet-core/issues/64)

- [x] [ohms-law 1.4.5-rc.2](https://phet-dev.colorado.edu/html/ohms-law/1.4.5-rc.2/phet/ohms-law_en_phet.html)

pendulum-lab 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [pendulum-lab 1.0.13-rc.2](https://phet-dev.colorado.edu/html/pendulum-lab/1.0.13-rc.2/pendulum-lab_en.html)

ph-scale 1.3 (https://github.com/phetsims/phet-core/issues/64)

- [x] [ph-scale 1.3.2-rc.2](https://phet-dev.colorado.edu/html/ph-scale/1.3.2-rc.2/phet/ph-scale_en_phet.html)

ph-scale-basics 1.3 (https://github.com/phetsims/phet-core/issues/64)

- [x] [ph-scale-basics 1.3.2-rc.2](https://phet-dev.colorado.edu/html/ph-scale-basics/1.3.2-rc.2/phet/ph-scale-basics_en_phet.html)

phet-io-test-sim 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [phet-io-test-sim 1.0.4-rc.2 phet-io](https://phet-dev.colorado.edu/html/phet-io-test-sim/1.0.4-rc.2/phet-io/phet-io-test-sim_all_phet-io.html?phetioStandalone)
- [x] [phet-io-test-sim 1.0.4-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/phet-io-test-sim/1.0.4-rc.2/phet-io/wrappers/studio

phet-io-test-sim 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [phet-io-test-sim 1.1.7-rc.2 phet-io](https://phet-dev.colorado.edu/html/phet-io-test-sim/1.1.7-rc.2/phet-io/phet-io-test-sim_all_phet-io.html?phetioStandalone)
- [x] [phet-io-test-sim 1.1.7-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/phet-io-test-sim/1.1.7-rc.2/phet-io/wrappers/studio

phet-io-test-sim 1.2 (https://github.com/phetsims/phet-core/issues/64)

- [x] [phet-io-test-sim 1.2.3-rc.2 phet-io](https://phet-dev.colorado.edu/html/phet-io-test-sim/1.2.3-rc.2/phet-io/phet-io-test-sim_all_phet-io.html?phetioStandalone)
- [x] [phet-io-test-sim 1.2.3-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/phet-io-test-sim/1.2.3-rc.2/phet-io/wrappers/studio

plinko-probability 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [plinko-probability 1.1.16-rc.2](https://phet-dev.colorado.edu/html/plinko-probability/1.1.16-rc.2/plinko-probability_en.html)

projectile-motion 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [projectile-motion 1.0.13-rc.2](https://phet-dev.colorado.edu/html/projectile-motion/1.0.13-rc.2/projectile-motion_en.html)

proportion-playground 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [proportion-playground 1.0.13-rc.2](https://phet-dev.colorado.edu/html/proportion-playground/1.0.13-rc.2/proportion-playground_en.html)

reactants-products-and-leftovers 1.2 (https://github.com/phetsims/phet-core/issues/64)

- [x] [reactants-products-and-leftovers 1.2.8-rc.2](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.2.8-rc.2/phet/reactants-products-and-leftovers_en_phet.html)

resistance-in-a-wire 1.3-phetio (https://github.com/phetsims/phet-core/issues/64)

- [x] [resistance-in-a-wire 1.3.11-rc.2 phet-io](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.3.11-rc.2/resistance-in-a-wire_en-phetio.html?phetioStandalone)
- [x] [resistance-in-a-wire 1.3.11-rc.2 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.3.11-rc.2/wrappers/instance-proxies/instance-proxies.html?sim=resistance-in-a-wire&relativeSimPath)

resistance-in-a-wire 1.6 (https://github.com/phetsims/phet-core/issues/64)

- [x] [resistance-in-a-wire 1.6.7-rc.2](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.7-rc.2/phet/resistance-in-a-wire_en_phet.html)

rutherford-scattering 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [rutherford-scattering 1.1.7-rc.2](https://phet-dev.colorado.edu/html/rutherford-scattering/1.1.7-rc.2/phet/rutherford-scattering_en_phet.html)

states-of-matter 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [states-of-matter 1.1.8-rc.2](https://phet-dev.colorado.edu/html/states-of-matter/1.1.8-rc.2/phet/states-of-matter_en_phet.html)

states-of-matter-basics 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [states-of-matter-basics 1.1.6-rc.2](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.1.6-rc.2/phet/states-of-matter-basics_en_phet.html)

trig-tour 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [trig-tour 1.0.20-rc.2](https://phet-dev.colorado.edu/html/trig-tour/1.0.20-rc.2/trig-tour_en.html)

under-pressure 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [under-pressure 1.1.16-rc.2](https://phet-dev.colorado.edu/html/under-pressure/1.1.16-rc.2/under-pressure_en.html)

unit-rates 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [unit-rates 1.0.15-rc.2](https://phet-dev.colorado.edu/html/unit-rates/1.0.15-rc.2/unit-rates_en.html)

wave-interference 1.0 (https://github.com/phetsims/phet-core/issues/64)

- [x] [wave-interference 1.0.8-rc.2](https://phet-dev.colorado.edu/html/wave-interference/1.0.8-rc.2/phet/wave-interference_en_phet.html)

wave-on-a-string 1.1 (https://github.com/phetsims/phet-core/issues/64)

- [x] [wave-on-a-string 1.1.20-rc.2](https://phet-dev.colorado.edu/html/wave-on-a-string/1.1.20-rc.2/wave-on-a-string_en.html)

**Comment by KatieWoe** [comment]
Not really a bug, but something to be aware of.  The X in the full screen mode of iOS 13 can obscure parts of the sim.
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/65067343-8641b480-d943-11e9-9003-76c581e8c370.png)

**Comment by KatieWoe** [comment]
https://github.com/phetsims/tambo/issues/78 occurs

**Comment by KatieWoe** [comment]
https://phet-dev.colorado.edu/html/john-travoltage/1.4.14-rc.2/john-travoltage_en-phetio.html?phetioStandalone seems to be having trouble with sound, even though it isn't tambo.

**Comment by KatieWoe** [comment]
QA is done.  Not sure what to do about https://github.com/phetsims/QA/issues/427#issuecomment-532835219

**Comment by jonathanolson** [comment]
I believe the john-travoltage issue will be improved by patching of vibe (in a similar way to tambo) which would be accomplished during the same maintenance release.

Pushed out production deploys, @ariel-phet is there anything we need to handle for the large X blocking part of the sim? I'll be continuing to look into the related issues.

**Comment by ariel-phet** [comment]
@jonathanolson it is seeming to me more and more that on iOS devices full screen is just highly problematic. Let's you and I plan to discuss in person today after buoyancy meeting.

**Comment by ariel-phet** [comment]
Will deal with full screen issues in https://github.com/phetsims/phet-core/issues/64, closing
