### ISSUE TITLE
Test keyboard navigation with bluetooth keyboard on iOS 13

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#428]
Related to https://github.com/phetsims/phet-core/issues/64, platform.mobileSafari won't work anymore for iOS 13. We hid the keyboard help dialog on mobile safari because bluetooth keyboard navigation didn't work, tab navigation and keycode reporting were broken.

Apple's decision to be more "desktop like" may indicate this problem has been fixed.

It would be helpful to test a bluetooth keyboard with iOS 13 and see if keyboard nav works. If it does, then all is well.

If it is still broken, we will need to either decide whether we are OK with the keyboard help button showing up while Bluetooth keyboards don't work or find another solution.

@KatieWoe said she has access to iOS 13 but not a bluetooth keyboard. @oliver-phet @ariel-phet do you know if we have one around the offices or would it be possible to get one to test?

**Comment by oliver-phet** [comment]
I gave @KatieWoe the bluetooth keyboard that was in the dev office. Hopefully that works!

**Comment by KatieWoe** [comment]
Looks good

**Comment by jessegreenberg** [comment]
Thats great, thanks! @KatieWoe can you comment on what was tested? For instance, were you able to tab to the balloon in https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.4.12-rc.2/phet/balloons-and-static-electricity_en_phet.html and pick it up/move it around?

**Comment by KatieWoe** [comment]
Yeah, that's pretty much exactly what I did, just to make sure it worked.  Let me know if you want more thorough testing.

**Comment by jessegreenberg** [comment]
Nope, I think thats perfect. Thanks for checking!
