### ISSUE TITLE
Getting Liam Started

### ISSUE THREAD

**Issue by phet-steele** [phetsims/QA#43]
@ariel-phet @oliver-phet

- [x] GitHub email/account, join the organization
- [x] Share to google-group
- [x] Add to QA folder
- [x] Availability posted in the calendar
- [x] Go over the phases of sim development
- [x] Go over GitHub workflow
- [x] Explain the testing tricks-of-the-trade (sim locations, query params, dev tools, etc...)
- [x] Practice creating an issue
- [x] Introduce test-server
- [x] Introduce the website
- [x] Website account
- [x] Introduce PhET-iO
- [x] Picture for website
- [x] Access to phet@lists.colorado.edu
- [x] Finish all admin paperwork
- [x] W4 and Direct Deposit up-to-date on myCUinfo

For @lmulhall-phet to research if they please (don't have to, it's not a compete doc):

[Modern PhET Look and Feel Cross Platform](https://docs.google.com/document/d/1Fg4E6VNMsnId7CjsyqHKnZeIoQ4N-5ezM9PTkj7N3PM/edit)

**Comment by oliver-phet** [comment]
- [ ] Added to phetlist

**Comment by phet-steele** [comment]
@oliver-phet that's in the above list!

**Comment by oliver-phet** [comment]
Whoops!

**Comment by oliver-phet** [comment]
We're done. Closing!

**Comment by lmulhall-phet** [comment]
Sounds good!
