### ISSUE TITLE
Dev test: vector-addition 1.0.0-dev.36

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#434]
@KatieWoe, @arouinfar, @ariel-phet, @kathy-phet, vector-addition/1.0.0-dev.36 is ready for dev testing. 

This sim is `brand=phet` only. It has no PhET-iO and no a11y instrumentation.

Document issues in https://github.com/phetsims/vector-addition/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- If there is a console available, check for errors and include them in the Problem Description.
- Rung through the string tests on at least one platform, especially if it is about to go to rc.

<h3>Focus and Special Instructions</h3>

* [model.md](https://github.com/phetsims/vector-addition/blob/master/doc/model.md) is required reading before testing.  [implementation-notes.md](https://github.com/phetsims/vector-addition/blob/master/doc/implementation-notes.md) is a work in progress, but you may still want to give it a quick skim.

* During implementation, this sim has been tested primarily on macOS+Chrome and iOS. Other platforms need a good shakedown.

* See https://github.com/phetsims/vector-addition/issues/197#issuecomment-535779200 for a list of multitouch interactions.

* Memory testing was done in https://github.com/phetsims/vector-addition/issues/87, if you want to compare results.

* There are no sim-specific query parameters that would be useful for QA.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [ ] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Issues to Verify</h3>

There are no specific issues to verify.  All known issues have been addressed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/vector-addition/1.0.0-dev.36/phet/vector-addition_all_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by arouinfar** [comment]
@pixelzoom `vector-addition` right?

**Comment by pixelzoom** [comment]
Oh duh.

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
Thanks @KatieWoe and QA team! 

Looks like there are 2 minor issues to fix - #218 and #220.   I'll get those done, then proceed to RC testing.

Closing.
