### ISSUE TITLE
Dev test: molarity 1.5.0-dev.23 (a11y instrumentation)

### ISSUE THREAD

**Issue by twant** [phetsims/QA#436]
@zepumph, @emily-phet, @Matthew-phet, @terracoda, @ariel-phet molarity/1.5.0-dev.23 is ready for dev testing. 

This sim has been instrumented with sound and PDOM accessibility features. 

Document issues in https://github.com/phetsims/molarity/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- If there is a console available, check for errors and include them in the Problem Description.
- Rung through the string tests on at least one platform, especially if it is about to go to rc.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [ ] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/molarity/1.5.0-dev.23/phet/molarity_en_phet.html)**

<hr>

</details>
<details>
<summary><b>Accessibility (a11y) Dev Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature testing doesn't negatively affect the sim in any way.
- Load the a11y view and make sure that interacting with all elements in the simulation updates the appropriate descriptions in the PDOM.

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/molarity/1.5.0-dev.23/phet/molarity_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/molarity/1.5.0-dev.23/phet/molarity_en_phet.html)**

<h3>Screen Readers</h3>

This sim supports screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to screen readers. If you simply need a refresher on screen readers, please consult the [QA Book](link), which should have all of the information you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- [x] Windows 10 + Latest Chrome + Latest JAWS
- [x] Windows 10 + Latest Firefox + Latest NVDA
- [x] macOS + Safari + VoiceOver
- [ ] iOS + Safari + VoiceOver

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in [this Google Document](https://drive.google.com/open?id=12kTs-g-iKEIH1dyG7Q41_W_oNL4gUKbkW-IQgZjMUBw). If you find a screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a screen reader.

<h3>Final Requests</h3>

- [x] If this sim is being tested for a11y we may want to do some testing on Talkback to check on latest behavior of that screen reader. Please comment in the issue asking if Talkback should be tested. See https://github.com/phetsims/a11y-research/issues/144.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Bit confused about this part of the description:
> concentration readout range for this solution 0 to 2.250 molar

This information isn't usually available, especially when the sim doesn't have solution values checked, which it doesn't by default.  Can you explain this decision?

**Comment by twant** [comment]
@KatieWoe Thanks for the question! I am not sure about this choice, but @terracoda, @Matthew-phet and/or @emily-phet can probably give more insight.

**Comment by KatieWoe** [comment]
If I could make a suggestion, instead of giving numbers that aren't originally available you could say something like "concentration readout range is very small/moderately sized/large etc."

**Comment by terracoda** [comment]
@KatieWoe, yes, thank you for this question. 

@Matthew-phet, @emily-phet and I have discussed how best to describe the concentration readout range several times. And I agree that it does seem odd to include the values when Solution Values is not checked for this single detail. That said, we have considered many aspects of teh descriptions.

We felt we would have to describe a lot of detail about the Solution Concentration bar itself before we would be able to then describe that the coloured section of that bar is a different size for each solute - an in addition describe it in a way that makes sense to a non-visaul user. We felt a big description of the Solution Concentration bar would draw too much attention to it. Playing with the sliders, hearing the provided alerts, and understanding that the solution in the beaker is changing are much more important details. 

The learning goals of the sim are to develop an understanding of concentration (molarity), and also discover that each solute has a saturation point.

The description, "concentration readout range for this solution 0 to 0.500 molar" describes the exact range for the potassium permanganate solute without actually calling the max value "0.500 molar" the saturation point. We do not feel we are giving away an answer.

We came to a consensus that it might be more straight forward for a non-visual learner to compare actual numbers in this case. For example, a learner doing a deep exploration might put together that the readout range for Colbalt(II) chloride which is 0 to 4.350 molar is much greater than the readout range for potassium permanganate. That might help them make sense of why they can move the solute slider more before they hear the tinkle sounds and the "Solution saturated" alert.

Our goal, I think, in this case, is to provide an equivalently strong representation of the concept. The concept being that each solute has a different range between zero concentration and max concentration.

Another practice we try to follow in our description designs is to provide the most important or most recently changed information first, wherever possible.

For example, in the Beaker description we provide all the details of the solution first: 
- volume
- solute name
- colour
- solute amount (and solute name again)
- saturation state (when relevant)
- concentration level
- chemical formula
- readout range

It is only at the very end that we provide the readout range. 

Another thing to consider is how this description is accessed or delivered to users. The "State Descriptions" are only accessed on-demand while the user is reading. The actual readout range is never provided during interaction. This description is meant to provide the most useful information a user may need if they choose read the entire description of the beaker description.

I hope that puts the description in context a little better.
We could, at some point, provide the concentration readout range information differently, as you have suggested, but I think for now we will stick the numbers. 

This description was, indeed, one of our big challenges for this sim.

**Comment by emily-phet** [comment]
@KatieWoe Thanks for the good question!

I concur with @terracoda - we spent a lot of time trying negotiate the challenges brought up by the concentration readout...and we settled on the current solution (as @terracoda describes).

**Comment by KatieWoe** [comment]
Some lag on chromebook, especially on the left slider when particles are involved.  Not too bad.

**Comment by KatieWoe** [comment]
QA is done

**Comment by KatieWoe** [comment]
Can this be closed since it is in rc @zepumph
