### ISSUE TITLE
Issue Review: Magnification features

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#437]
Another version of a sim with magnification is ready for testing. Could you please review the following issues and make sure that they have been fixed since #419?

**Version to test**: https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-customZoom.11/phet/molecules-and-light_en_phet.html?a11y

- [x] https://github.com/phetsims/molecules-and-light/issues/217
- [x] https://github.com/phetsims/molecules-and-light/issues/214
- [x] https://github.com/phetsims/molecules-and-light/issues/213 
- [x] https://github.com/phetsims/molecules-and-light/issues/212
- [x] https://github.com/phetsims/molecules-and-light/issues/211
- [x] https://github.com/phetsims/molecules-and-light/issues/209
- [x] https://github.com/phetsims/molecules-and-light/issues/207
- [x] https://github.com/phetsims/molecules-and-light/issues/204

If any issues are not resoloved, please describe in issue and assign it back to me. And if you notice anything new please make a new issue in phetsims/molecules-and-light/issues.

Assigning to @ariel-phet to assign priority.

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Most excellent, many thanks.
