### ISSUE TITLE
iOS/iPadOS App v1.3(55) and v1.3(56)

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/QA#440]
This is probably the last test before 1.3 is released, so we'll do a thorough check on all platforms.

Assigning @ariel-phet for prioritization.

### iOS

- [x] 11
- [x] 12
- [x] 13 (latest)

### iPadOS

- [x] 13 (latest)

## Issues to Verify

- [x] [Hearts in collection view thumbnails get cut off](https://github.com/phetsims/phet-ios-app/issues/555) ✅
- [x] [1.3 cache should be up-to-date](https://github.com/phetsims/phet-ios-app/issues/536) ✅

**Comment by ariel-phet** [comment]
This is a concurrent priority with #432 - but it looks like nothing major has been found in that check so far. But #432 should be complete before actual app publication.

**Comment by KatieWoe** [comment]
Things look good on our end.
