### ISSUE TITLE
Spot Check: Gravity Force Lab Basics 1.0.0-rc.3

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#441]
Previous RC: https://github.com/phetsims/QA/issues/438

@terracoda, @emily-phet, @jessegreenberg, gravity-force-lab-basics:1.0.0-rc.3 is ready for RC testing.

This is the third RC test. Nothing was found during last RC testing save potential issues with some MR patches that our release here has been interfering with. @KatieWoe please make sure that the appropriate patches for the MR being done and tested over in https://github.com/phetsims/QA/issues/432#issuecomment-542567431.

You already mentioned that in https://github.com/phetsims/QA/issues/438#issuecomment-542755889

I have been pretty far out of the loop in terms of the MRs, and only getting a list of patches to make sure to include in releases. Please forward questions about that behavior to @jonathanolson. 

For the sim specific stuff, there really isn't any. Please just make sure that it isn't broken, especially when using a screen reader, and with mobile + VO.

@jessegreenberg feel free to recommend further testing if you feel like it is needed.

Folder:
https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.0.0-rc.3/phet/

Sim:
https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.0.0-rc.3/phet/gravity-force-lab-basics_all_phet.html

@ariel-phet please assign and prioritize.

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome (with and without Jaws)
- [ ] Win 10 firefox (with and without NVDA)
- [ ] Win 10 edge
---
- [ ] Mac 10.15 chrome
- [ ] Mac 10.15 firefox
- [ ] Mac 10.15 safari (with and without VO)
---
- [ ] Win 7 IE
- [ ] Mac 10.11 safari
---
- [ ] ChromeOS
- [ ] iPadOS 13 (with and without VO)
---
@zepumph to approve test devices

**Comment by zepumph** [comment]
Looks good to me, thanks!

**Comment by KatieWoe** [comment]
QA is done

**Comment by zepumph** [comment]
Thanks! We will work out https://github.com/phetsims/gravity-force-lab-basics/issues/185 and report back.
