### ISSUE TITLE
Maintenance Test: tambo fixes for iOS 13

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#442]
A maintenance patch has been made to address some issues with platform detection on iOS 13 that was causing problem with sound generation, see https://github.com/phetsims/tambo/issues/78.  The sims below all had this patch, and should be tested for correct sound generation.  The test should consist of two steps:
+ Make sure that sound is generated normally when the sim starts up, and isn't stalled until reset is pressed
+ Reload the sim, then before doing any other action, drag a finger in a non-interactive area of the sim, then test that sound generation works correctly.

Here is a list of the patched sims with links to the RCs:

build-a-fraction 1.0 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [build-a-fraction 1.0.10-rc.2](https://phet-dev.colorado.edu/html/build-a-fraction/1.0.10-rc.2/phet/build-a-fraction_en_phet.html)

circuit-construction-kit-dc 1.1 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [circuit-construction-kit-dc 1.1.5-rc.2](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.1.5-rc.2/phet/circuit-construction-kit-dc_en_phet.html)

circuit-construction-kit-dc-virtual-lab 1.1 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [circuit-construction-kit-dc-virtual-lab 1.1.5-rc.2](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.1.5-rc.2/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html)

coulombs-law 1.0 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [coulombs-law 1.0.9-rc.2](https://phet-dev.colorado.edu/html/coulombs-law/1.0.9-rc.2/phet/coulombs-law_en_phet.html)

diffusion 1.0 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [diffusion 1.0.4-rc.2](https://phet-dev.colorado.edu/html/diffusion/1.0.4-rc.2/phet/diffusion_en_phet.html)

energy-forms-and-changes 1.0 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [energy-forms-and-changes 1.0.11-rc.2](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.0.11-rc.2/phet/energy-forms-and-changes_en_phet.html)

fractions-equality 1.0 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [fractions-equality 1.0.10-rc.2](https://phet-dev.colorado.edu/html/fractions-equality/1.0.10-rc.2/phet/fractions-equality_en_phet.html)

fractions-intro 1.0 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [fractions-intro 1.0.10-rc.2](https://phet-dev.colorado.edu/html/fractions-intro/1.0.10-rc.2/phet/fractions-intro_en_phet.html)

fractions-mixed-numbers 1.0 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [fractions-mixed-numbers 1.0.10-rc.2](https://phet-dev.colorado.edu/html/fractions-mixed-numbers/1.0.10-rc.2/phet/fractions-mixed-numbers_en_phet.html)

friction 1.5 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [friction 1.5.10-rc.2](https://phet-dev.colorado.edu/html/friction/1.5.10-rc.2/phet/friction_en_phet.html)

gas-properties 1.0 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [gas-properties 1.0.3-rc.2](https://phet-dev.colorado.edu/html/gas-properties/1.0.3-rc.2/phet/gas-properties_en_phet.html)

gases-intro 1.0 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [gases-intro 1.0.4-rc.2](https://phet-dev.colorado.edu/html/gases-intro/1.0.4-rc.2/phet/gases-intro_en_phet.html)

graphing-lines 1.3 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [graphing-lines 1.3.9-rc.2](https://phet-dev.colorado.edu/html/graphing-lines/1.3.9-rc.2/phet/graphing-lines_en_phet.html)

graphing-quadratics 1.1 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [graphing-quadratics 1.1.5-rc.2](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.5-rc.2/phet/graphing-quadratics_en_phet.html)
- [x] [graphing-quadratics 1.1.5-rc.2 phet-io](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.5-rc.2/phet-io/graphing-quadratics_all_phet-io.html?phetioStandalone)
- [x] [graphing-quadratics 1.1.5-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.5-rc.2/phet-io/wrappers/studio

graphing-slope-intercept 1.1 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [graphing-slope-intercept 1.1.9-rc.2](https://phet-dev.colorado.edu/html/graphing-slope-intercept/1.1.9-rc.2/phet/graphing-slope-intercept_en_phet.html)

isotopes-and-atomic-mass 1.1 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [isotopes-and-atomic-mass 1.1.8-rc.2](https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.8-rc.2/phet/isotopes-and-atomic-mass_en_phet.html)

john-travoltage 1.5 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [john-travoltage 1.5.12-rc.2](https://phet-dev.colorado.edu/html/john-travoltage/1.5.12-rc.2/phet/john-travoltage_en_phet.html)

masses-and-springs-basics 1.0 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [masses-and-springs-basics 1.0.9-rc.2](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.9-rc.2/phet/masses-and-springs-basics_en_phet.html)

molecule-shapes 1.2 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [molecule-shapes 1.2.8-rc.2](https://phet-dev.colorado.edu/html/molecule-shapes/1.2.8-rc.2/phet/molecule-shapes_en_phet.html)

molecule-shapes-basics 1.2 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [molecule-shapes-basics 1.2.8-rc.2](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.8-rc.2/phet/molecule-shapes-basics_en_phet.html)

ohms-law 1.4 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [ohms-law 1.4.7-rc.2](https://phet-dev.colorado.edu/html/ohms-law/1.4.7-rc.2/phet/ohms-law_en_phet.html)

resistance-in-a-wire 1.6 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [resistance-in-a-wire 1.6.9-rc.2](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.9-rc.2/phet/resistance-in-a-wire_en_phet.html)

wave-interference 2.0 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [wave-interference 2.0.1-rc.2](https://phet-dev.colorado.edu/html/wave-interference/2.0.1-rc.2/phet/wave-interference_en_phet.html)

waves-intro 1.0 (fix iOS 13 sound issues, see https://github.com/phetsims/tambo/issues/78)

- [x] [waves-intro 1.0.1-rc.2](https://phet-dev.colorado.edu/html/waves-intro/1.0.1-rc.2/phet/waves-intro_en_phet.html)

**Comment by jbphet** [comment]
Assigning to @ariel-phet for prioritization.  This was discussed in last Thursday's status meeting, and @kathy-phet seemed to feel like it was pretty high priority so that sound would work correctly in the iOS app.

**Comment by jbphet** [comment]
There is another maintenance patch that is being done at this time that includes all of the sims above, so once the patch described in this GitHub issue has been verified, deploying of the sims listed in https://github.com/phetsims/QA/issues/432#issuecomment-542567431 should be deployed, and that will finish both maintenance releases.

**Comment by ariel-phet** [comment]
Concurrent top priority with #440

**Comment by KatieWoe** [comment]
QA is done

**Comment by jonathanolson** [comment]
Thanks!
