### ISSUE TITLE
Characterize performance and performance problems on Gravity and Orbits

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#443]
From https://github.com/phetsims/gravity-and-orbits/issues/286 @ariel-phet said:

> @samreid I was seeing the somewhat stuttering behavior on Win 7 Chrome. I have not done a thorough comparison of platforms. I just wonder if given the age of this sim there are some performance improvements to be had that are low hanging fruit (things we have learned since then).
> 
> We could have QA take a brief look at some point to see if performance issues are platform specific. I think having various options on (vectors, values, path, etc) makes things more obvious.

We would like to understand the performance of the published version, particularly any performance problems (sluggishness, stuttering, etc).  We would like to know if the problems are still in the latest dev version, and how they vary as a function of browser, device, etc.  Identifying and quantifying reproducible performance issues would be nice, so that a developer can work on improving them.  This does not need to be an exhaustive study.

Assigning to @ariel-phet for clarification, prioritization, scheduling and delegation.

UPDATE: You may also want to review related issue https://github.com/phetsims/gravity-and-orbits/issues/162

UPDATE: Here's a fresh dev version: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.3/phet/gravity-and-orbits_en_phet.html

**Comment by KatieWoe** [comment]
| Platform | Subjective Performance | FPS |
| --- | --- | --- |
| iPhone iOS 12 | | |
| iPad iOS 10 | | |
| iPad iOS 11 | | |
| iPad iOS 12 | | |
| iPadOS 13 | | |
| iPadOS 13 App | | |
| Mac 10.10 Safari | | |
| Mac 10.11 Safari | | |
| Mac 10.11 Chrome | | |
| Mac 10.12 Safari | | |
| Mac 10.12 Chrome | | |
| Mac 10.13 Safari | | |
| Mac 10.13 Chrome | | |
| Mac 10.14 Safari | | |
| Mac 10.14 Chrome | | |
| Mac 10.15 Safari | | |
| Mac 10.15 Chrome | | |
| Win 7 Chrome | | |
| Win 7 Firefox | | |
| Win 7 IE | | |
| Win 10 Chrome | | |
| Win 10 Firefox | | |
| Win 10 Edge | | |
| ChromeOS | | |

**Comment by ariel-phet** [comment]
@KatieWoe the list above looks comprehensive

**Comment by ariel-phet** [comment]
@KatieWoe do note, that I think all tests should be done with options "path" "velocity" and "force vectors" on

**Comment by KatieWoe** [comment]
Ok.  I wasn't aware.  I'll need to redo above then.

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
Thanks @KatieWoe!  Closing.
