### ISSUE TITLE
Maintenance testing for area-model 1.2 sims

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#447]
I'd like spot-checks for the following area-model 1.2 sims, to make sure that the recent maintenance patches work nicely (so they can be production deployed sometime):

- [ ] https://phet-dev.colorado.edu/html/area-model-algebra/1.2.0-rc.5/phet/area-model-algebra_en_phet.html
- [ ] https://phet-dev.colorado.edu/html/area-model-decimals/1.2.0-rc.5/phet/area-model-decimals_en_phet.html
- [ ] https://phet-dev.colorado.edu/html/area-model-introduction/1.2.0-rc.5/phet/area-model-introduction_en_phet.html
- [ ] https://phet-dev.colorado.edu/html/area-model-multiplication/1.2.0-rc.5/phet/area-model-multiplication_en_phet.html

This should include iOS-related testing (iPadOS glitches, full-screen, game audio tests)

The last RC testing was done in:

- https://github.com/phetsims/QA/issues/409
- https://github.com/phetsims/QA/issues/410
- https://github.com/phetsims/QA/issues/411
- https://github.com/phetsims/QA/issues/412

And the sim-specific patch issues (auto-generated by the maintenance release process):

- https://github.com/phetsims/area-model-algebra/issues/6
- https://github.com/phetsims/area-model-decimals/issues/8
- https://github.com/phetsims/area-model-introduction/issues/7
- https://github.com/phetsims/area-model-multiplication/issues/7

I believe @ariel-phet said that if these patches are good, we'll proceed to production deploys.

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome
- [ ] Win 10 firefox
- [ ] Win 10 edge
---
- [ ] Mac 10.15 safari
---
- [ ] Win 7 IE
---
- [ ] ChromeOS
- [ ] iPadOS 13

**Comment by ariel-phet** [comment]
high priority since should be quick but after #445 (or concurrently with #445 if on the same platform)

**Comment by KatieWoe** [comment]
QA is done

**Comment by jonathanolson** [comment]
Thanks, moving forward with production deployments!
