### ISSUE TITLE
Spot Check: Gravity Force Lab Basics 1.0.0-rc.4

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#449]
Previous RC: https://github.com/phetsims/QA/issues/441

@terracoda, @emily-phet, @jessegreenberg, @arouinfar gravity-force-lab-basics:1.0.0-rc.4 is ready for RC testing.

This is the fourth RC test. No sim specific changes have occurred since 2 rcs ago, save some MR patches. For this we only need to test the second item in https://github.com/phetsims/gravity-force-lab-basics/issues/186, which is phetsims/scenery#1006, 

- [x] https://github.com/phetsims/gravity-force-lab-basics/issues/186

That item is only for iOS 13 ipad, so likely just a spot check on that device is all that is needed. 

Folder:
https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.0.0-rc.4/phet/

Sim:
https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.0.0-rc.4/phet/gravity-force-lab-basics_all_phet.html

@ariel-phet please assign and prioritize.

**Comment by KatieWoe** [comment]
QA is done

**Comment by zepumph** [comment]
Sounds great I'll publish now.
