### ISSUE TITLE
RC testing for Pendulum Lab 1.0.0-rc.2

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#45]
@ariel-phet, @arouinfar, @kathy-phet, Pendulum Lab 1.0.0-rc.2 is ready for RC testing.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-rc.2/pendulum-lab_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-rc.2/pendulum-lab_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1RGAdl0nny_iapzsdlwvV2r4TMtZC8poJDe1Atm6I-Vo/edit#gid=407143293)**

**Issues to Verify**
(*all should be marked "status:fixed-pending-testing"*)  
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/pendulum-lab/issues/177

**Please also verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any new issues are found, please note them in https://github.com/phetsims/pendulum-lab/issues and reference this issue.  

 
**(Other potentially useful items)**  

Sim-specific terminology:  
• pendulum - a mass suspended from a pivot so that it can swing freely.
• lab - short for laboratory

**Comment by jonathanolson** [comment]
What are the instructions to create a testing matrix?

**Comment by ariel-phet** [comment]
@phet-steele on hold briefly for some potential minor polishes

**Comment by jonathanolson** [comment]
1.0.0-rc.2 has the desired pixel-polishing updates.

**Comment by ariel-phet** [comment]
@phet-steele current top testing priority

**Comment by phet-steele** [comment]
@kathy-phet can you confirm you want to test this sim in the LoL harness?

**Comment by kathy-phet** [comment]
yes please.

**Comment by phet-steele** [comment]
Done! Thanks QA team!

**Comment by jonathanolson** [comment]
Thanks!
