### ISSUE TITLE
Verify that sound still works on all sims that use it

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#456]
In https://github.com/phetsims/chipper/issues/806 I changed the way that sound is turned on or off for most simulations that use it.  I spot checked a fair number of the affected sims, but it would be good to have someone go through and verify that sound is working in the master version of all of them.  I would recommend testing one sim on all supported platforms, and then just checking that sound works on any platform for all other sims, since the most likely failure case is that sound didn't get correctly re-enabled and thus would not work on anything.

Here is a list of the affected sims:
- [x] area-builder
- [x] area-model-algebra
- [x] area-model-multiplication
- [x] arithmetic
- [x] balancing-act
- [x] balancing-chemical-equations
- [x] build-a-fraction
- [x] build-a-molecule
- [x] build-an-atom
- [x] equality-explorer
- [x] expression-exchange
- [x] fraction-matcher
- [x] fractions-equality
- [x] fractions-intro
- [x] fractions-mixed-numbers
- [x] graphing-lines
- [x] gravity-force-lab-basics
- [x] john-travoltage
- [x] make-a-ten
- [x] molarity
- [x] ohms-law
- [x] reactants-products-and-leftovers
- [x] resistance-in-a-wire
- [x] _tambo_?
- [x] wave-interference
- [x] waves-intro

(EDIT: removed chipper from list)

**Comment by KatieWoe** [comment]
In addition, John Travoltage should be checked on all of these platforms:
- [ ] Win 10 chrome
- [ ] Win 10 firefox
- [ ] Win 10 edge
---
- [ ] Win 7 chrome
- [ ] Win 7 firefox
- [ ] Win7 IE (won't have sound)
---
- [ ] Mac 10.15 chrome
- [ ] Mac 10.15 safari
---
- [ ] Mac 10.14 chrome
- [ ] Mac 10.14 safari
---
- [ ] Mac 10.13 chrome
- [ ] Mac 10.13 safari
---
- [ ] Mac 10.12 chrome
- [ ] Mac 10.12 safari
---
- [ ] Mac 10.11 chrome
- [ ] Mac 10.11 safari
---
- [ ] Mac 10.10 safari
---
- [ ] iPad OS 13 Safari
- [ ] iPad OS 13 app
- [ ] iPhone iOS 13 Safari
- [ ] iPhone iOS 13 app
---
- [ ] iOS 12
- [ ] iOS 11
---
- [ ] Chrome OS

**Comment by KatieWoe** [comment]
I've noticed that on safari the first sound has a bit of a "donk" noise that I couldn't find in the published version.

**Comment by KatieWoe** [comment]
The sim does not open on Mac OS 10.0, Safari 10.  I don't see an error in the console, but it does say there should be one there.  @jbphet I was on John Travoltage.

**Comment by KatieWoe** [comment]
Had some inconsistency on iPhone iOS 12, but likely due to the phone rather than code changes.

**Comment by KatieWoe** [comment]
Issues listed above.  Unsure how to check chipper or tambo.  Other than that, QA is done.

**Comment by jbphet** [comment]
@KatieWoe - I have a few questions:

> I've noticed that on safari the first sound has a bit of a "donk" noise that I couldn't find in the published version.

Which sim, browser, and OS?

> The sim does not open on Mac OS 10.0, Safari 10. I don't see an error in the console, but it does say there should be one there. @jbphet I was on John Travoltage.

Was this working prior to the code changes that we are testing here?  In other words, was there anything that made it seem to you like the sound changes are leading to this problem?

> Had some inconsistency on iPhone iOS 12, but likely due to the phone rather than code changes.

What was the nature of the inconsistency, and is it different for built master versions versus published versions?  I need to decide whether this is something I should spend time on, so I need a bit more to go on to make that decision.

**Comment by KatieWoe** [comment]
1. John Travoltage, Safari, Various Mac OS.  It wasn't consistent.
2. I believe it was.  It was working on published I believe.  I'm not certain what the cause would be.
3. Sometimes the sound wouldn't work for a bit, you'd come back to the sim and sound would work just fine for no discernible reason.  This tends to show up from time to time on iPad/Phone products and doesn't seem connected to changes made.

**Comment by KatieWoe** [comment]
2. Update.  It seems to be most/any sim.  I found the error, it says "undefined is not a function"

**Comment by jbphet** [comment]
> Unsure how to check chipper or tambo.

Tambo has a demo that tests sounds, and it should be exercised as part of this testing.

**Comment by KatieWoe** [comment]
Looks good

**Comment by jbphet** [comment]
I went ahead and verified tambo on Win 10 and Chrome, and it's fine.  Closing.
