### ISSUE TITLE
Add a few items to phet-io test in rc template

### ISSUE THREAD

**Issue by zepumph** [phetsims/qa#458]
From https://github.com/phetsims/phet-io-wrappers/issues/224, bullets to come.

**Comment by zepumph** [comment]
@KatieWoe. These items were added as part of review over in https://github.com/phetsims/phet-io-wrappers/issues/224. How do they sound to you?

**Comment by KatieWoe** [comment]
I was not aware that IE was supported with phet-io. It was never on the test matrix that I was aware of. For that reason it isn't generally tested during dev or rc testing. If this is not the case, let me know and I can make the necessary changes to add it to the testing rotation. @zepumph

**Comment by zepumph** [comment]
Today during PhET-iO meeting, we decided that the only thing needed for IE on PhET-iO is as follows:

* Load the wrapper index, and click the "Launch Template" button below the displayed wrapper template at the bottom of the code snippet. 

This should only be done for rc test on a single device. Nothing more needs to be done with IE. I think https://github.com/phetsims/QA/commit/cbc260263d82314fba2ff53e8a7bd21fc9ca7627 should be reverted. Thanks!

How does that sound?

**Comment by KatieWoe** [comment]
It sounds good.  I'll leave it for the next rc, just to check a bit more thoroughly, but remove it if everything seems fine.

**Comment by zepumph** [comment]
> I'll leave it for the next rc,

Sounds good. I'll just note that from our meeting today, it felt very clear that we don't support any of the wrappers suite wrappers on IE.

**Comment by KatieWoe** [comment]
I think this can be closed. @zepumph reopen if you disagree.

**Comment by samreid** [comment]
I added a note about updating QA credits, @KatieWoe does this look OK to you?

**Comment by KatieWoe** [comment]
That seems like a good idea to me!

**Comment by KatieWoe** [comment]
Added this to a few more templates. Closing again.
