### ISSUE TITLE
Verify zh_CN sim descriptions get added to app (12/3)

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/QA#460]
Note: this test will need to be performed ~11am Dec 3 to allow 24 hours for the metadata to update.

A Chinese translator recently updated/added translations for the sim descriptions for zh_CN. Can QA please open the app in Chinese (Simplified) and verify the [descriptions published on the website](https://phet.colorado.edu/zh_CN/simulations/category/html) are being reflected in the app?

**Comment by KatieWoe** [comment]
QA is done.  Looks fine on published app.

**Comment by oliver-phet** [comment]
@kathy-phet the app did indeed update with the updated Chinese descriptions Yu provided!
