### ISSUE TITLE
Dev test: Molecules and Light Interactive Descriptions

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#461]
In preparations for user interviews can you please test the interactive descriptions in this sim?
**Link to sim:** https://phet-dev.colorado.edu/html/molecules-and-light/1.5.0-dev.21/phet/molecules-and-light_en_phet.html?ea&a11y&supportsSound

Platforms to test:
- [x] Chrome (JAWS)
- [x] Firefox (NVDA)
- [x] Safari (VoiceOver)
- [x] iOS Safari (VoiceOver)

**Comment by KatieWoe** [comment]
Repo: https://github.com/phetsims/molecules-and-light

**Comment by KatieWoe** [comment]
Memory Test Results:
![memtests](https://user-images.githubusercontent.com/41024075/70834682-2f1f7480-1db8-11ea-999f-69e5d9dc1fd8.png)

**Comment by KatieWoe** [comment]
Calling an end here so changes can be made for tomorrow. Will likely have student workers look at it through the week to find any more hidden issues.

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, this has been great and we learned a lot from this. Closing.
