### ISSUE TITLE
PhET-iO addition to the QA Book

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#467]
@KatieWoe, over in https://github.com/phetsims/studio/issues/35 @samreid, @chrisklus, and I added functionality such that when you press the "launch" button in studio, or conduct any other state set on a PhET-iO sim, then the resetAllButton should automatically set the state back to that configuration when pressed. 

From this we would like to make sure that two things are checked
1. (I'm unsure this warrants its own part in the QA book) Please note that PhET-iO expects that there is only one ResetAllButton per screen, and if there is a scene reset or something, then it should not be a ResetAllButton. This is already a convention for PhET in general, but this code is now depending on that convention.
2. Please add documentation to "how to test studio" that makes sure that when the "launched" button is pressed with a custom state, a PhET-iO sim goes back to that state for each screen when its respective resetAllButton is pressed.

This functionality is live in master and can be tested on any PhET-iO sim (and should work). Please see https://github.com/phetsims/studio/issues/35 for more information.

**Comment by KatieWoe** [comment]
QA book changes added in the above commit. @zepumph if you agree with this, please close.

**Comment by zepumph** [comment]
Thanks!
