### ISSUE TITLE
Dev test: Energy Skate Park 1.0.0-dev.6

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#470]
Could you please give this sim a dev test? There have been enough changes since the last version that this would be useful before an RC.

Changes mostly involve conservation of energy in special cases (https://github.com/phetsims/energy-skate-park/issues/172, https://github.com/phetsims/energy-skate-park/issues/45, others). So please pay special attention to the behavior of energy and make sure that it is conserved.

For this test can you also please test performance of the sim on our slowest platforms?

[**Link to Sim**]( https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.6/phet/energy-skate-park_en_phet.html)

Also assigning to @ariel-phet to provide priority.

**Comment by ariel-phet** [comment]
Promoting to current top priority

**Comment by ariel-phet** [comment]
back to high priority so that #476 is top

**Comment by ariel-phet** [comment]
And back to the top priority

**Comment by KatieWoe** [comment]
- [ ] Latest macOS, Chrome and Safari
- [ ] Latest iOS, Safari
- [ ] Windows 10, all browsers
- [ ] Latest Chrome OS, Chrome

**Comment by KatieWoe** [comment]
I believe QA is done with this dev test

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Great, thank you @KatieWoe and team -

> For this test can you also please test performance of the sim on our slowest platforms?

I am not sure https://github.com/phetsims/QA/issues/470#issuecomment-585938038 covered this, can you comment on if any slower platforms were tested? Ideally we want to catch performance issues now before we create an RC branch.

**Comment by KatieWoe** [comment]
Ah, sorry. I missed the bit about slowest performing. I'll reopen and take a look.

**Comment by jessegreenberg** [comment]
Thank you!

**Comment by KatieWoe** [comment]
ChromeOS: Fair, some noticeable lag, particularly on third screen. FPS from 30-50
iOS 9 (not supported): Poor, prone to crashing, Normal and slow look similar/same
Mac OS 10.10 Safari: Good, no problems seen

**Comment by jessegreenberg** [comment]
Great, thanks @KatieWoe -

In https://github.com/phetsims/energy-skate-park/issues/42 we decided that this release will not need to support iOS 9, we expected that platform to be problematic.

@ariel-phet can you please comment on if more time is needed to optimize for ChromeOS? Third screen is most graphically intensive as it uses griddle, and optimizations would probably start there. But "fair" with 30-50 fps may also be acceptable.

**Comment by ariel-phet** [comment]
@KatieWoe for ChromeOS can you compare to the published version of ESPB for us? If things have some lag compared to published, we likely need to do some work @jessegreenberg considering the popularity of this platform.

**Comment by KatieWoe** [comment]
Quick look on published ESPB ChromeOS. It looked good: 55-60 fps. Honestly, I expected to get problems from https://github.com/phetsims/energy-skate-park-basics/issues/467, but it looks pretty good.

**Comment by jessegreenberg** [comment]
Interesting, that is surprising since it was reported as poor in https://github.com/phetsims/energy-skate-park-basics/issues/467. Ill open an issue in energy-skate-park to investigate more. This issue can be closed.
