### ISSUE TITLE
QA: Testing for phet-ios-app v1.3.2(70)

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/QA#472]
This version of the app should not appear outwardly different. Most areas have been touched but only in minor ways (to catch kills and edge cases). The main areas fo concern are:

- The update process
    - The update process was moved into its own class with a number of improvements. This has the highest likelihood of introducing bugs.
- UI updates as a result of changes
    - The underlying event system was improved and now more highly relies on notifications This means less work, but it may have introduced bugs
- The presentation of the Collection and List view
    - The underlying data structure for the collection and list were combined into one. This should be faster, have less bugs, etc, but some new bugs may have been introduced.

Note: The cache has been intentionally left in an old state in order to test the update system.

**Comment by KatieWoe** [comment]
From @ariel-phet 
@KatieWoe I think this version would be good to do a "thorough" test on. It does not need to be as exhaustive as a test for actually releasing a new version of the app, since we will need to do such a test anyhow before the next version, but since @chris-huxtable has done a fair bit of code clean-up we want to make sure we have a good "baseline" for this version as we move forward.

If any bugs are found, please note if they exist in the published version of the app or not.

**Comment by KatieWoe** [comment]
Original issue: https://github.com/phetsims/phet-ios-app/issues/585
Couldn't seem to transfer into a public repo

**Comment by KatieWoe** [comment]
QA is done for now.

**Comment by mattpen** [comment]
I'm not sure why I'm assigned.  @KatieWoe - did you need some help here?

**Comment by KatieWoe** [comment]
@mattpen https://github.com/phetsims/QA/issues/472#issuecomment-601938187
As said above. QA is done with this test flight version.

**Comment by KatieWoe** [comment]
@ariel-phet to delegate when he gets back

**Comment by ariel-phet** [comment]
Looks like things are assigned as needed. Closing
