### ISSUE TITLE
RC Test: Balancing Act 1.2.0-rc.1 PhET-iO

### ISSUE THREAD

**Issue by chrisklus** [phetsims/QA#473]
@KatieWoe, @ariel-phet, @kathy-phet, balancing-act/1.2.0-rc.1 is ready for RC testing. 

This is a test for specific features that we're sending to a client, not an actual standard RC test. It also only includes PhET-iO, and is not a fully instrumented version of the sim. Per the query parameters included in the wrapper links, only the second screen needs to be tested, and with the query parameter `stanford`. For these reasons, much of the typical RC template has been omitted. 

We're trying to deliver this to the client by the end of the week, so this is a high priority test.

Please document issues in https://github.com/phetsims/balancing-act/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>PhET-iO RC Test</b></summary>

<h3>Focus and Special Instructions</h3>

- [ ] Please do thorough testing of the standalone version with this link:
  * [standalone](https://phet-dev.colorado.edu/html/balancing-act/1.2.0-rc.1/phet-io/balancing-act_all_phet-io.html?postMessageOnError&phetioStandalone&stanford&screens=2)
- [ ] Please test the record and playback wrapper locally with these links:
  * [record](https://phet-dev.colorado.edu/html/balancing-act/1.2.0-rc.1/phet-io/wrappers/record/?console&stanford&screens=2)
  * [playback](https://phet-dev.colorado.edu/html/balancing-act/1.2.0-rc.1/phet-io/wrappers/playback/)
- [ ] Please do a Metacog cycle test with this link:
  * [login](https://phet-dev.colorado.edu/html/balancing-act/1.2.0-dev.5/phet-io/wrappers/login/?wrapper=record&validationRule=validateAlphaNumeric&numberOfCharacters=4&metacog&publisher_id=29da48a1&key_name=balancing-act-1.2-stanford&widget_id=balancing-act-1.2-stanford-test&stanford&screens=2)

Here are the requests from the client that we implemented for this version:

* Remove “People” from the simulated object box. 
* Limit the weight options of the bricks to 5kg, 10kg and 20kg. 
* It should say "setup" and "test"
* When in "test" cannot move objects
* Record log data of student actions
* Have mystery boxes with the weights that are different from the weights of all the bricks.
* Supply new values for the mystery weights

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/balancing-act/1.2.0-rc.1/phet-io/?stanford&screens=2)**
- **[Test Matrix](https://github.com/phetsims/QA/issues/473#issuecomment-580950903)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

**Comment by ariel-phet** [comment]
@KatieWoe concurrent top priority with #471

**Comment by KatieWoe** [comment]
- [ ] macOS 10.12 Safari
- [ ] macOS 10.12 Chrome
- [ ] iPad iOS 13 Safari (No Studio)
- [ ] macOS 10.15 Safari
- [ ] macOS 10.15 Firefox
- [ ] macOS 10.15 Chrome
- [ ] Win 10 (laptop) Edge
- [ ] Win 10 (laptop) Chrome
- [ ] Win 10 (laptop) Firefox
- [ ] Win 10 (laptop) IE (No Studio)
- [ ] Chromebook Chrome (latest)

**Comment by lmulhall-phet** [comment]
Linking https://github.com/phetsims/studio/issues/92 since it affects this sim.

**Comment by KatieWoe** [comment]
https://github.com/phetsims/balancing-act/issues/43 may happen here, but it is quite hard to tell.

**Comment by samreid** [comment]
Where there is a ❌next to "login", which issue (or issues) does that refer to?

**Comment by KatieWoe** [comment]
@samreid https://github.com/phetsims/phet-io-wrappers/issues/320

**Comment by KatieWoe** [comment]
This known issue: https://github.com/phetsims/phet-io-wrappers/issues/278. Is present with metacog on iPads.

**Comment by KatieWoe** [comment]
QA is done. Issues linked or discussed above.

**Comment by samreid** [comment]
@zepumph and I reviewed the referenced issues and agreed this is ready to share with our client, but we will mention that it may not work on Chromebooks and there may be problems if you interact with an object while it's animating.

**Comment by KatieWoe** [comment]
QA is done. Some uncertainty in metacog discussed in https://github.com/phetsims/balancing-act/issues/114. Not sure what causes it or the platform. Other issues linked above.

**Comment by chrisklus** [comment]
In https://github.com/phetsims/balancing-act/issues/115 the phet-io team cherry picked the fix for https://github.com/phetsims/studio/issues/92 and published 1.2.1.

Can we close @samreid @zepumph?

**Comment by samreid** [comment]
I'd like to leave this open until I have a chance to triage all the opened issues, if that's OK.  But if that interferes with the QA issues, let me know and I'll find another way.

**Comment by zepumph** [comment]
There look to be three BA specific issues from this QA:
https://github.com/phetsims/balancing-act/issues/112
https://github.com/phetsims/balancing-act/issues/95
https://github.com/phetsims/balancing-act/issues/113

All other open issues have GFL linked to it, and will be covered by that RC process.

**Comment by pixelzoom** [comment]
This issue sent me on a wild-goose chase related to https://github.com/phetsims/joist/issues/624.
I see 2 additional RCs (1.2.0-rc.2, 1.2.0-rc.3) and 3 published version (1.2.0, 1.2.1, 1.2.2) on phet-dev.    Can someone please document what happened here, and (if appropriate) close this issue.

**Comment by samreid** [comment]
This sim was published and shared with the client.  Closing.
