### ISSUE TITLE
Document link with bug report?

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#474]
From #471, There were many issues that came out of that test task. Many of them were on different PhET-iO wrappers. And sometimes (like for record/playback) they are the same wrapper but different link) I think for me it would helpful if the bug report can include the exact link used to produce the bug. 

@KatieWoe what do you think about that? Is that alright? Something for the QA book?

**Comment by KatieWoe** [comment]
Ok, but to clarify, if the issue is made in the sim's repo, is it ok to put those links in a public repo?

**Comment by lmulhall-phet** [comment]
@zepumph, @KatieWoe, QA used to put links in the test matrix next to the test that failed. We could do that again for tests where issues are specific to certain links.

**Comment by KatieWoe** [comment]
General wording in the above commit @zepumph

**Comment by zepumph** [comment]
>Ok, but to clarify, if the issue is made in the sim's repo, is it ok to put those links in a public repo?


That is a good point! If they are password protected, then maybe it ok? Let's double check with @samreid, but I think that in general these issues are often in phet-io/studio/phet-io-wrappers anyways. 

@samreid do you think we should keep phet-io links (even when password protected) out of public issues?

**Comment by samreid** [comment]
In my opinion, it is OK to put password protected phet-io links in public issues.  However, we would need to be careful that those links aren't made (temporarily) public for client studies.  You may wish to double check with @kathy-phet about this policy.

**Comment by zepumph** [comment]
I added it to the agenda Thursday.

**Comment by chrisklus** [comment]
from 02/06/20 phet-io meeting:

@kathy-phet is fine with password protected links in public issues.

**Comment by zepumph** [comment]
@KatieWoe over to you for review. Does that sound good with you? Should this be updated in the QA book at all?

**Comment by wandita** [comment]
test comment
wanda

**Comment by KatieWoe** [comment]
second test
