### ISSUE TITLE
Spot checks for Java certificate updates

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#475]
As part of https://github.com/phetsims/special-ops/issues/150, we've resigned a copy of all JAR files (under https://phet.colorado.edu/sims-copy/) that we'd like to get tested before things get copied over into the correct production place.

I've verified that all JAR files should be good to go (server-side), but I'd like spot checks on a few different platforms (can we try all supported platforms for Java as a default?), running an assorted number of JARs (feel free to test a different one for each platform, or a few each, so we get decent coverage - we shouldn't test all of them), to make sure we don't run into security issues. Additionally, faradays-law_be.jar and faradays-law_th.jar seem to show errors (and don't verify), but they were broken before. I'll note that issue elsewhere, but those can be ignored.

Assigning @ariel-phet for prioritization.

**Comment by ariel-phet** [comment]
Given that our Java sims are still used quite a bit, it would be good to make this issue high priority. Considering there are not many platforms (basically some Mac OS's and Windows 10) it should be fairly efficient to proceed with these checks.

**Comment by KatieWoe** [comment]
Molecule Shapes java keeps crashing when I try to open in (Mac 10.13.6).

**Comment by jonathanolson** [comment]
> Molecule Shapes java keeps crashing when I try to open in (Mac 10.13.6).

Does that differ from the production version?

**Comment by KatieWoe** [comment]
I would assume so. I never had reason to try and download it before this change.

**Comment by KatieWoe** [comment]
It does work on my Win 10 device

**Comment by jonathanolson** [comment]
Since we have an HTML5 version for the simulation, I'm not sure an issue is needed (or where it would go, other than molecule-shapes). Probably @ariel-phet's call?

**Comment by KatieWoe** [comment]
Notes for Win 10:
No problems in downloading or opening. However, I was (when discussing the installer) told that there would be Digital Signatures tab when looking at the properties window for the sim. I don't see that here.
![propertiesofjava](https://user-images.githubusercontent.com/41024075/74193611-dda73080-4c14-11ea-8d74-4ada1eb3fa9d.png)
@jonathanolson if I'm misunderstanding, please let me know.

**Comment by KatieWoe** [comment]
On Macs the sims are still from "an unidentified developer" and you still need to go through the security steps to open them.

**Comment by KatieWoe** [comment]
QA is done. Potential issues discussed above.

**Comment by jbphet** [comment]
@KatieWoe said:

>  I was (when discussing the installer) told that there would be Digital Signatures tab when looking at the properties window for the sim. I don't see that here.

@KatieWoe - Is this any different from what we are seeing on the currently live JAR files?  If not, then it doesn't really matter - we're just trying to make sure that nothing has been broken from signing the JAR files with the new certificate.

**Comment by KatieWoe** [comment]
@jbphet is not any different than the live JAR files that I can see.

**Comment by ariel-phet** [comment]
Can this be closed @jonathanolson @jbphet @Denz1994? Let's quickly discuss at dev meeting

**Comment by Denz1994** [comment]
I am okay with closing this one.

Regarding the installer, I checked the jar signature on alpha_decay_en.jar on the latest stable copy (peta backup) and compared it to the alpha_decay_en.jar from phet.colorado.edu. Both show a verified signature.

This was done by running:
`jarsigner -verify -verbose -certs <path_to_installer_sim>/alpha-decay_en.jar`
`jarsigner -verify -verbose -certs <path_to_downloaded_sim>/alpha-decay_en.jar`

Both returning a fairly large input reading:
```
Signed by "CN=University Of Colorado at Boulder - Code Signing
...
jar verified.

The signer certificate will expire on 2022-12-19.
...
```

Also, the issue mentioned [here](https://github.com/phetsims/QA/issues/475#issuecomment-584375500), requires that a java sim be verified via the jarsigner utility provided by the JDK. Using the properties tab only works to check for the digital signature of the installer, not the individual jar files.

**Comment by jonathanolson** [comment]
Seems fine to close, we presumably would have run into issues by now.

**Comment by jbphet** [comment]
Yep, I'm on board with closing it too, so I'll just do so.
