### ISSUE TITLE
Dev Test: CCK DC 1.0.0-dev.160

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#48]
Now that the code review is complete, we would like to run another dev test for CCK DC.  I published http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-dc/1.0.0-dev.160/circuit-construction-kit-dc_en.html

Things to test in particular:
1. This version uses SVG, so we should check performance (particularly on slower devices and firefox) to see whether it is acceptable.
2. Numerous changes occurred during the code review, so logic, physics, view all need to be verified.

Assigned to @ariel-phet to see if there's anything else to focus on in testing, and to prioritize/schedule/delegate.

Test platforms:

- [x] iPad 2
- [x] iPad Air
- [x] Win Chrome
- [x] Mac Safari

**Comment by ariel-phet** [comment]
Should be top priority along with finishing #45

**Comment by samreid** [comment]
I noticed a lot of checked boxes above.  Is this issue complete?

**Comment by phet-steele** [comment]
@samreid we could do with a new dev version when you get the chance. It doesn't appear that https://github.com/phetsims/circuit-construction-kit-dc/issues/96 is fixed in master yet.

**Comment by samreid** [comment]
https://github.com/phetsims/circuit-construction-kit-dc/issues/96 is fixed but I'm going to address https://github.com/phetsims/circuit-construction-kit-common/issues/404 before next dev version
