### ISSUE TITLE
Spot check: quality of PhET/Keyboard buttons after changing from mipmap to image

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#481]
In https://github.com/phetsims/joist/issues/607 we are trying to use image instead of mipmap. Mipmap was originally used to improve image quality in Firefox as the PhET logo looked very pixelated on that platform.

![image](https://user-images.githubusercontent.com/6396244/74557082-6b449200-4f2d-11ea-8cd3-cffe329a9c61.png)

Can you please compare the quality of these button in this version
https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.15/phet/balloons-and-static-electricity_en_phet.html

against the deployed version
https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_en.html

on all of our supported platforms?

https://github.com/phetsims/joist/issues/607 locks publication off of master, if that is helpful in determining priority of this issue. Also related to es6-modules and https://github.com/phetsims/chipper/issues/840 because if mipmap is required here, we know they must be supported in general. Assigning to @ariel-phet to prioritize.

**Comment by ariel-phet** [comment]
Just as quick datapoint, checking this button on Win 10 FF, no observable difference (FF often being a problem platform)

**Comment by ariel-phet** [comment]
@KatieWoe marking as high priority, and can probably be done in parallel with other testing when on a particular platform.

**Comment by KatieWoe** [comment]
- [ ] iPhone Safari
- [ ] iPad 10.12 Safari
- [ ] iPad 10.13 Safari
- [ ] iPad 10.13 App
---
- [ ] Mac 10.10 Safari
---
- [ ] Mac 10.11 Safari
- [ ] Mac 10.11 Chrome
---
- [ ] Mac 10.12 Safari
- [ ] Mac 10.12 Chrome
---
- [ ] Mac 10.13 Safari
- [ ] Mac 10.13 Chrome
---
- [ ] Mac 10.14 Safari
- [ ] Mac 10.14 Chrome
---
- [ ] Mac 10.15 Safari
- [ ] Mac 10.15 Chrome
---
- [ ] Win 10 IE
- [ ] Win 10 Edge
- [ ] Win 10 Firefox
- [ ] Win 10 Chrome
---
- [ ] ChromeOS

**Comment by KatieWoe** [comment]
QA is done. Looks good.

**Comment by jessegreenberg** [comment]
Great, thanks!
