### ISSUE TITLE
Dev Test: Android App

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#484]
Version 1.1-dev.4 of the Android App is available for testing.  It is available here: https://play.google.com/apps/internaltest/4697762600441754675.  Please me send the email address for any Play Store user that wishes to test the app.

This version of the app should have the new updated layout to match the iOS app v 1.3 and should show titles, descriptions, and simulations in the locale of the device. (App strings have not been added yet).  There are other changes but they are not of a visible nature (using compressed sims, database optimizations).

QA, please do a dev test of the app. Please complete a general test to make sure that all sims are launching, resources are in the correct locale, that the app receives updates correctly, and that all other functions of the app are working properly (sim info dialog, app info dialog, filters, search, etc). 

 It should be tested (at a minimum) on a phone and on our two Chromebooks (Lovelace and Euler I think?).  @oliver-phet - can you think of any other devices that should be tested?

**Comment by mattpen** [comment]
Specific issues to confirm:

https://github.com/phetsims/phet-android-app/issues/56
https://github.com/phetsims/phet-android-app/issues/55

**Comment by KatieWoe** [comment]
@ariel-phet for priority

**Comment by ariel-phet** [comment]
@KatieWoe higher than #483 lower than #479

**Comment by mattpen** [comment]
@KatieWoe - When opening device specific bugs, please note the Android version used on the device. This is normally found in Settings > About {{Device}} > Android Version.

**Comment by KatieWoe** [comment]
Due to https://github.com/phetsims/phet-android-app/issues/96, putting an end to this test.

**Comment by mattpen** [comment]
We'll create a new test when these bugs are solved.
