### ISSUE TITLE
spot check: Gravity Force Lab 2.2.0-rc.4

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#486]
@emily-phet @terracoda @jessegreenberg @arouinfar @kathy-phet @samreid @chrisklus, gravity-force-lab/2.2.0-rc.4 is ready for RC testing. This is the fourth RC test, and so we just need to spot check the issues found in the previous RC.
Document issues in https://github.com/phetsims/gravity-force-lab/issues and link to this issue.

This simulation is outfitted with:

All PhET-iO featured, including a designed api
Sound
Interactive Descriptions (alternative input and auditory descriptions)
Gesture Accessibility with support for mobile iOS

Links:

Phet brand simulation: https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-rc.4/phet/gravity-force-lab_en_phet.html
Wrapper index: https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.0-rc.4/phet-io/
Test matrix: https://docs.google.com/spreadsheets/d/1dPp2zsj4WW577vQNgCnx9d3cPNxh_JrJj_EQ8CaNqOc/edit#gid=860975363

Please verify the following issues:

- [x] https://github.com/phetsims/studio/issues/102
- [x] https://github.com/phetsims/studio/issues/107
- [x] https://github.com/phetsims/phet-io-wrappers/issues/336
- [x] https://github.com/phetsims/gravity-force-lab/issues/261
- [ ] Please tell me if there are more QA credits, or close this issue: https://github.com/phetsims/gravity-force-lab/issues/180

Previous QA issue (rc.3): https://github.com/phetsims/QA/issues/485 

As this is the fourth RC, I'm not sure that much more is needed after verifying issues beyond just a sanity check on a couple devices.

Thanks!

**Comment by KatieWoe** [comment]
- [ ] Win 10 chrome w/ Jaws and Phet-io
- [ ] Win 10 firefox w/ NVDA and Phet-io
- [ ] Win 10 edge
---
- [ ] macOS 10.15 Chrome
- [ ] macOS 10.15 Safari w/ VoiceOver and PhET-iO
---
- [ ] Win 10 IE and Phet-io
- [ ] Mac 10.12 Safari
---
- [ ] ChromeOS and Phet-io
- [ ] iPadOS 13 w/ VO and Phet-io

**Comment by terracoda** [comment]
@KatieWoe, we test VO on PhET-io?

**Comment by KatieWoe** [comment]
No, not generally. We might have looked at it at one point. It is VO on the vanilla sim and also test phet-io.

**Comment by zepumph** [comment]
Thanks you so much for such a quick turnaround!! I really appreciate it!
