### ISSUE TITLE
Dev testing for "decaf" simulations

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#489]
We ported simulations using CheerpJ 2.1 and published the results here:
https://phet-dev.colorado.edu/decaf/

@kathy-phet requested QA dev testing on these simulations to help identify the most important bugs.

Generally, we are looking to usability or technical barriers to publishing these on our website for broader use, so that we can discontinue most/all of our Java simulations.

For each simulation, navigate to the latest version (in most cases it is 1.0.0-dev.2).  Test the sims on a variety of different devices, including iPad, Chromebook, iPhone, Mac, Windows, or any of our supported platforms, but perhaps a slightly higher focus on platforms that cannot run Java themselves.

Issues should be opened in https://github.com/phetsims/decaf/issues

Please label with "type:bug" for problems that crash, or cause simulation failure.
Please label with "design:general" if you see behavior that could benefit from an improved design.

Please be aware I already opened a few issues from my basic spot testing.

@kathy-phet asked me to prioritize this investigation, but I'm not sure how that compares to other QA priorities.

**Comment by KatieWoe** [comment]
- [ ] battery-resistor-circuit
     - [ ] Win 10 Firefox
- [ ] battery-voltage
     - [ ] Win 10 IE
- [ ] bound-states
     - [ ] Mac 10.15 Safari
- [ ] capacitor-lab
     - [ ] Mac 10.15 Chrome
- [ ] conductivity
     - [ ] Chrome OS
- [ ] discharge-lamps
     - [ ] iPadOS 13
- [ ] eating-and-exercise
     - [ ] Win 10 Firefox
- [ ] efield
     - [ ] Win 10 IE
- [ ] electric-hockey
     - [ ] Mac 10.15 Safari
- [ ] faraday
     - [ ] Mac 10.15 Chrome
- [ ] fluid-pressure-and-flow
     - [ ] Chrome OS
- [ ] forces-1d
     - [ ] iPadOS 13
- [ ] fourier
     - [ ] Win 10 Firefox
- [ ] gene-network
     - [ ] Win 10 IE
- [ ] glaciers
     - [ ] Mac 10.15 Safari
- [ ] greenhouse
     - [ ] Mac 10.15 Chrome
- [ ] hydrogen-atom
     - [ ] Chrome OS
- [ ] ideal-gas
     - [ ] iPadOS 13
- [ ] ladybug-motion-2d
     - [ ] Win 10 Firefox
- [ ] lasers
     - [ ] Win 10 IE
- [ ] maze-game
     - [ ] Mac 10.15 Safari
- [ ] membrane-channels
     - [ ] Mac 10.15 Chrome
- [ ] microwaves
     - [ ] Chrome OS
- [ ] motion-2d
     - [ ] iPadOS 13
- [ ] motion-series
     - [ ] Win 10 Firefox
- [ ] moving-man
     - [ ] Win 10 IE
- [ ] mri
     - [ ] Mac 10.15 Safari
- [ ] natural-selection
     - [ ] Mac 10.15 Chrome
- [ ] nuclear-physics
     - [ ] Chrome OS
- [ ] optical-quantum-control
     - [ ] iPadOS 13
- [ ] optical-tweezers
     - [ ] Win 10 Firefox
- [ ] photoelectric
     - [ ] Win 10 IE
- [ ] plate-tectonics
     - [ ] Mac 10.15 Safari
- [ ] quantum-tunneling
     - [ ] Mac 10.15 Chrome
- [ ] quantum-wave-interference
     - [ ] Chrome OS
- [ ] radio-waves
     - [ ] iPadOS 13
- [ ] reactions-and-rates
     - [ ] Win 10 Firefox
- [ ] rotation
     - [ ] Win 10 IE
- [ ] self-driven-particle-model
     - [ ] Mac 10.15 Safari
- [ ] semiconductor
     - [ ] Mac 10.15 Chrome
- [ ] signal-circuit
     - [ ] Chrome OS
- [ ] soluble-salts
     - [ ] iPadOS 13
- [ ] sound
     - [ ] Win 10 Firefox
- [ ] sugar-and-salt-solutions
     - [ ] Win 10 IE
- [ ] the-ramp
     - [ ] Mac 10.15 Safari

**Comment by KatieWoe** [comment]
Things to keep in mind:
* Take note of how long sims take to load
* Check if in-sim problems occur in java version
* Check if problem is platform specific

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
Thanks @KatieWoe and @loganbraywork!  We appreciate it.  Closing and will continue in https://github.com/phetsims/decaf/issues/15
