### ISSUE TITLE
RC test for Pendulum Lab 1.0.0-rc.3

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#49]
@ariel-phet, @arouinfar, @kathy-phet, pendulum-lab 1.0.0-rc.3 is ready for RC testing.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-rc.3/pendulum-lab_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-rc.3/pendulum-lab_en-iframe.html)**

**Issues to Verify**
(*all should be marked "status:fixed-pending-testing"*)  
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/pendulum-lab/issues/188
- [x] https://github.com/phetsims/pendulum-lab/issues/187
- [x] https://github.com/phetsims/pendulum-lab/issues/186

If any new issues are found, please note them in https://github.com/phetsims/pendulum-lab/issues and reference this issue.

**Comment by ariel-phet** [comment]
@phet-steele this test can be more of a "spot check" - not every platform needs to be tested. I will let you choose which ones to work on, but I would think check iPad Air, chromebook, a PC platform, and a Mac platform

**Comment by lmulhall-phet** [comment]
phetsims/pendulum-lab#187 still seems to be an issue in Safari and Firefox on Mac. Doesn't seem to be an issue in Chrome on Mac.

**Comment by jonathanolson** [comment]
> phetsims/pendulum-lab#187 still seems to be an issue in Safari and Firefox on Mac. Doesn't seem to be an issue in Chrome on Mac.

Investigating.

**Comment by lmulhall-phet** [comment]
@jonathanolson -- I just tested it again, and it appears to be fine in Safari and Firefox. I think I copy and pasted the link to rc.2. I hope you didn't spend to much time investigating. Sorry about that.

**Comment by phet-steele** [comment]
![greenlight](https://user-images.githubusercontent.com/5863899/30397875-7ee9297a-988b-11e7-9640-bdb915599d72.png)

**Comment by jonathanolson** [comment]
Thanks, 1.0.0 pushed to the website!
