### ISSUE TITLE
QA Test: Google Doc submission

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#490]
@KatieWoe - it would be great if QA could test out the latest changes for activity submission on the website. This includes:

- [x] Adding Google Docs to existing activities
- [x] Creating new activities with just Google Docs, with just uploaded files, and with both.
- [x] Removing Google Docs from existing activities.

This can be tested using the interface at https://ox-dev.colorado.edu/en/teaching-resources/submit-activity.

Activities modified/approved/unapproved/added/deleted/etc when you are on the ox-dev domain will have no effect on the production site and are not permanent (will eventually be overwritten by the current state of production).  Feel free to make any changes you want on ox-dev.

Ping me if you want me to copy over the current state from production at any time. 

I believe this is fairly high priority, but I'm not aware of what all is in the QA pipeline at the moment.

**Comment by KatieWoe** [comment]
Most things look like they might be ok, but https://github.com/phetsims/website/issues/1015 leaves me unsure, so I'm going to pause until it is addressed. 
Additionally, @mattpen should google slides and sheets also work?

**Comment by oliver-phet** [comment]
@KatieWoe This process should support all of the formats listed on the submission page:

> Allowed Google Files: Docs, Sheets, Slides, Forms

**Comment by mattpen** [comment]
> phetsims/website#1015 leaves me unsure, so I'm going to pause until it is addressed.

This should be fixed now, please resume testing.

**Comment by KatieWoe** [comment]
Potential problem I noticed for people sharing from certain organizations.
The default setting for our colorado emails is anyone from University of Colorado can view. This means that if you post that link than none of the teachers will be able to open it (seen using my personal email). If you use a normal account it seems to be anyone with the link can view, but any teachers that have a similar set up to ours may run in to this same problem. Trish noted on Slack:
> I discovered a big idea. When I made a copy the settings changed from the original. Important Google doc lesson:)

Not much we can do about this other than keep an eye on those settings when approving activities and keeping it in mind when posting our own activities.
@kathy-phet @oliver-phet @ariel-phet @mattpen @amanda-phet @arouinfar So you are all aware of this situation.

**Comment by kathy-phet** [comment]
Yes, we will need to keep an eye our for making sure the share settings are appropriate. Thanks, Katie!

**Comment by kathy-phet** [comment]
Yep - for v2.

**Comment by KatieWoe** [comment]
Things look ok. @mattpen let me know if there are any more scenarios you can come up with that you want tested. I can't think of any myself at this point.

**Comment by mattpen** [comment]
This feature was deployed! Thanks for your help @KatieWoe.
