### ISSUE TITLE
Publishing new Java translations - impact on CheerpJ sims

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/QA#493]
Just creating this issue to think through publishing any new Java sim translations that will likely come if we publish CheerpJ versions of our sims. I believe the current translation process builds a new all.jar file. Would it make sense to come up with a process to kick off the CheerpJ build from that new all.jar (so that our website can incorporate a new translation in the CheerpJ variant)? Or would this be difficult/cost prohibitive?

**Comment by KatieWoe** [comment]
If it isn't difficult/costly, I think it would be a good idea. @oliver-phet is there any reason for me to hold off on translations while this is decided?

**Comment by oliver-phet** [comment]
@KatieWoe you can continue with translations like normal for now.

**Comment by oliver-phet** [comment]
From design 4/9:
It sounds like it should be very doable to republish the CheerpJ versions of the simulations if a new all.jar is published.

**Comment by oliver-phet** [comment]
This issue can be closed. If needed, we can republish CheerpJ versions.
