### ISSUE TITLE
Test Decaf Sims that have been redeployed after AffineTransformOp fixes

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#495]
From https://github.com/phetsims/decaf/issues/9#issuecomment-615909657, this is a continuation of https://github.com/phetsims/QA/issues/489 for the sims that failed to load with the AffineTransformOp failure.  CheerpJ published a new version of CheerpJ with a fix and I redeployed these:

https://phet-dev.colorado.edu/decaf/battery-voltage/1.0.0-dev.3/index.html
https://phet-dev.colorado.edu/decaf/fluid-pressure-and-flow/1.0.0-dev.4/index.html?simulation=fluid-pressure-and-flow
https://phet-dev.colorado.edu/decaf/greenhouse/1.0.0-dev.3/index.html
https://phet-dev.colorado.edu/decaf/lasers/1.0.0-dev.3/index.html
https://phet-dev.colorado.edu/decaf/moving-man/1.0.0-dev.3/index.html
https://phet-dev.colorado.edu/decaf/mri/1.0.0-dev.3/index.html

https://phet-dev.colorado.edu/decaf/optical-tweezers/1.0.0-dev.4/index.html?simulation=optical-tweezers
https://phet-dev.colorado.edu/decaf/optical-tweezers/1.0.0-dev.4/index.html?simulation=stretching-dna
https://phet-dev.colorado.edu/decaf/optical-tweezers/1.0.0-dev.4/index.html?simulation=molecular-motors

https://phet-dev.colorado.edu/decaf/photoelectric/1.0.0-dev.3/index.html
https://phet-dev.colorado.edu/decaf/reactions-and-rates/1.0.0-dev.3/index.html
https://phet-dev.colorado.edu/decaf/soluble-salts/1.0.0-dev.3/index.html

I already detected that discharge-lamps has another problem, and did not deploy it.

Assigning to @kathy-phet and/or @ariel-phet for priority and scheduling.

**Comment by kathy-phet** [comment]
Seems like there is some specific demand for reactions and rates. So if that could go through optimization steps that would be great. Thanks
Kathy

Sent from my iPhone

On Apr 18, 2020, at 12:10 PM, Sam Reid <notifications@github.com> wrote:

﻿

From phetsims/decaf#9 (comment)<https://github.com/phetsims/decaf/issues/9#issuecomment-615909657>, this is a continuation of #489<https://github.com/phetsims/QA/issues/489> for the sims that failed to load with the AffineTransformOp failure. CheerpJ published a new version of CheerpJ with a fix and I redeployed these:

https://phet-dev.colorado.edu/decaf/battery-voltage/1.0.0-dev.3/index.html
https://phet-dev.colorado.edu/decaf/fluid-pressure-and-flow/1.0.0-dev.4/index.html?simulation=fluid-pressure-and-flow
https://phet-dev.colorado.edu/decaf/greenhouse/1.0.0-dev.3/index.html
https://phet-dev.colorado.edu/decaf/lasers/1.0.0-dev.3/index.html
https://phet-dev.colorado.edu/decaf/moving-man/1.0.0-dev.3/index.html
https://phet-dev.colorado.edu/decaf/mri/1.0.0-dev.3/index.html

https://phet-dev.colorado.edu/decaf/optical-tweezers/1.0.0-dev.4/index.html?simulation=optical-tweezers
https://phet-dev.colorado.edu/decaf/optical-tweezers/1.0.0-dev.4/index.html?simulation=stretching-dna
https://phet-dev.colorado.edu/decaf/optical-tweezers/1.0.0-dev.4/index.html?simulation=molecular-motors

https://phet-dev.colorado.edu/decaf/photoelectric/1.0.0-dev.3/index.html
https://phet-dev.colorado.edu/decaf/reactions-and-rates/1.0.0-dev.3/index.html
https://phet-dev.colorado.edu/decaf/soluble-salts/1.0.0-dev.3/index.html

I already detected that discharge-lamps has another problem, and did not deploy it.

Assigning to @kathy-phet<https://github.com/kathy-phet> and/or @ariel-phet<https://github.com/ariel-phet> for priority and scheduling.

**Comment by samreid** [comment]
All of the sims listed above are published with the `cjGetRuntimeResources()` optimization which enables parallel downloads of the cheerpj files.

**Comment by ariel-phet** [comment]
@KatieWoe next priority after #494 (note Reaction and Rates would be good to get to early in testing)

**Comment by KatieWoe** [comment]
All links above open with Win 10 chrome

**Comment by lmulhall-phet** [comment]
All links open on macOS + Chrome. Reactions and Rates looks good on macOS + Chrome and macOS + Safari.

**Comment by loganbraywork** [comment]
All links open with Windows 10 Firefox

**Comment by KatieWoe** [comment]
On ChromeOS, Reactions and Rates can be noticeably slow when there are large numbers of atoms. This makes other aspects, such as the pump, temp controls, etc. slow to respond. Firefox on Windows was also slow when it came to sliders and buttons. IE issue noted in https://github.com/phetsims/decaf/issues/75. Otherwise, I think the basic tests for Reactions and Rates is done. @samreid @kathy-phet
