### ISSUE TITLE
Organization and Testing for Decaf Batch

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#497]
In https://github.com/phetsims/decaf/issues/79 I published a new batch of simulations for decaf testing.

In slack, @KatieWoe said:

> I would make sure each could open on Win Chrome, Win Firefox, Win Edge, Win IE, Mac 15 Chrome, Mac 15 Safari, iPad 13 Safari and Chrome OS. Probably do a bit of testing on each to determine if anything is unusably slow on important platforms.

We should decide how to track the testing for these simulations.  We would like to make it easy to see when a simulation is ready for publication, or, if not, what the problems are, and make it easy to deploy new versions for testing.  I sketched out a spreadsheet to start the discussion.

https://docs.google.com/spreadsheets/d/10bO1Eimm5Y7TH4o7QPebpNUaIItxYK-VnKcSe24TXmc/edit#gid=0

Let's discuss organization around this testing and how to proceed.  And the batch mentioned in https://github.com/phetsims/decaf/issues/79 and listed again in the prototype spreadsheet is ready for testing.

**Comment by KatieWoe** [comment]
Talked with Sam a bit already, added a device/platform, and chose what we would say about each (good, ok [meaning that it lags noticeably but doesn't hurt learning], and unusable).
Testing is underway.

**Comment by ariel-phet** [comment]
Concurrent top priority with #494

**Comment by KatieWoe** [comment]
Now in https://github.com/phetsims/QA/issues/499. Closing
