### ISSUE TITLE
Website: Dev Test the Browse and Filter Pages

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#498]
QA, please conduct a dev test of the new browse/filter pages on the website.  These are available at https://ox-dev.colorado.edu/en/simulations/browse and https://ox-dev.colorado.edu/en/simulations/filter.

Some things to verify:
- Layouts should be responsive and polished across all supported browsers/devices.
- Layouts should still look correct in other locales (not all strings are translated yet), including RTL locales.
- The new pages should be accessible with mouse, touch, keyboard navigation, and screen readers.
- Please do some cursory regression testing for the front page, the registration page, and the edit profile page.
- Check that sorting and filtering behave correctly.
- Verify that the hover tooltips are working correctly in all contexts.
- Verify that the simulation tiles are linking to the correct places.

Please open new issues in https://github.com/phetsims/website-meteor/issues and assign @chrisklus and @mattpen and add them to the Website: Browse/Filter Pages project.

**Comment by mattpen** [comment]
@KatieWoe - please don't start on this quite yet.  It will be ready soon!

**Comment by oliver-phet** [comment]
Also to test:
- If a user selects a locale on the filter page that does not match the website locale, clicking on a sim tile should take the user to the sim page with the Translations dropdown open.
- Verify that normal locale fallbacks are continuing to work as expected (example: es_MX>es>en) on sim launches.

**Comment by mattpen** [comment]
@ariel-phet - please assign priority.

@KatieWoe - This dev test is ready to go!

**Comment by ariel-phet** [comment]
Next priority after #499

**Comment by KatieWoe** [comment]
- [ ] Win 10 Chrome
- [ ] Win 10 Firefox
- [ ] Win 10 Edge [ ] 
- [ ] Win 10 IE
- [ ] Mac Chrome
- [ ] Mac Safari
- [ ] ChromeOS
- [ ] iPad Safari

**Comment by KatieWoe** [comment]
QA is done. More testing may be needed as fixes are done. If so, let us know @mattpen
