### ISSUE TITLE
Decaf testing for Java 7 batch

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#499]
I deployed a Java 7 batch here as part of https://github.com/phetsims/decaf/issues/89

https://phet-dev.colorado.edu/decaf/battery-resistor-circuit/1.0.0-dev.16/battery-resistor-circuit.html
https://phet-dev.colorado.edu/decaf/battery-voltage/1.0.0-dev.5/battery-voltage.html
https://phet-dev.colorado.edu/decaf/bound-states/1.0.0-dev.5/bound-states.html?simulation=band-structure
https://phet-dev.colorado.edu/decaf/bound-states/1.0.0-dev.5/bound-states.html?simulation=bound-states
https://phet-dev.colorado.edu/decaf/bound-states/1.0.0-dev.5/bound-states.html?simulation=covalent-bonds
https://phet-dev.colorado.edu/decaf/capacitor-lab/1.0.0-dev.4/capacitor-lab.html?simulation=capacitor-lab
https://phet-dev.colorado.edu/decaf/conductivity/1.0.0-dev.4/conductivity.html
https://phet-dev.colorado.edu/decaf/discharge-lamps/1.0.0-dev.4/discharge-lamps.html
https://phet-dev.colorado.edu/decaf/eating-and-exercise/1.0.0-dev.4/eating-and-exercise.html?simulation=eating-and-exercise
https://phet-dev.colorado.edu/decaf/efield/1.0.0-dev.4/efield.html
https://phet-dev.colorado.edu/decaf/electric-hockey/1.0.0-dev.4/electric-hockey.html
https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.22/faraday.html?simulation=faraday
https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.22/faraday.html?simulation=generator
https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.22/faraday.html?simulation=magnet-and-compass
https://phet-dev.colorado.edu/decaf/faraday/1.0.0-dev.22/faraday.html?simulation=magnets-and-electromagnets
https://phet-dev.colorado.edu/decaf/fluid-pressure-and-flow/1.0.0-dev.7/fluid-pressure-and-flow.html?simulation=fluid-pressure-and-flow
https://phet-dev.colorado.edu/decaf/forces-1d/1.0.0-dev.5/forces-1d.html
https://phet-dev.colorado.edu/decaf/fourier/1.0.0-dev.4/fourier.html
https://phet-dev.colorado.edu/decaf/gene-network/1.0.0-dev.4/gene-network.html?simulation=gene-machine-lac-operon
https://phet-dev.colorado.edu/decaf/glaciers/1.0.0-dev.4/glaciers.html
https://phet-dev.colorado.edu/decaf/greenhouse/1.0.0-dev.5/greenhouse.html?simulation=greenhouse
https://phet-dev.colorado.edu/decaf/hydrogen-atom/1.0.0-dev.4/hydrogen-atom.html
https://phet-dev.colorado.edu/decaf/ideal-gas/1.0.0-dev.4/ideal-gas.html?simulation=balloons-and-buoyancy
https://phet-dev.colorado.edu/decaf/ideal-gas/1.0.0-dev.4/ideal-gas.html?simulation=gas-properties
https://phet-dev.colorado.edu/decaf/ideal-gas/1.0.0-dev.4/ideal-gas.html?simulation=reversible-reactions
https://phet-dev.colorado.edu/decaf/ladybug-motion-2d/1.0.0-dev.4/ladybug-motion-2d.html?simulation=ladybug-motion-2d
https://phet-dev.colorado.edu/decaf/lasers/1.0.0-dev.5/lasers.html?simulation=lasers
https://phet-dev.colorado.edu/decaf/maze-game/1.0.0-dev.4/maze-game.html
https://phet-dev.colorado.edu/decaf/membrane-channels/1.0.0-dev.4/membrane-channels.html?simulation=membrane-channels
https://phet-dev.colorado.edu/decaf/microwaves/1.0.0-dev.4/microwaves.html
https://phet-dev.colorado.edu/decaf/molecule-polarity/1.0.0-dev.3/molecule-polarity.html?simulation=molecule-polarity
https://phet-dev.colorado.edu/decaf/motion-2d/1.0.0-dev.4/motion-2d.html
https://phet-dev.colorado.edu/decaf/motion-series/1.0.0-dev.4/motion-series.html?simulation=forces-and-motion
https://phet-dev.colorado.edu/decaf/motion-series/1.0.0-dev.4/motion-series.html?simulation=ramp-forces-and-motion
https://phet-dev.colorado.edu/decaf/moving-man/1.0.0-dev.12/moving-man.html?simulation=moving-man
https://phet-dev.colorado.edu/decaf/mri/1.0.0-dev.5/mri.html
https://phet-dev.colorado.edu/decaf/natural-selection/1.0.0-dev.4/natural-selection.html?simulation=natural-selection
https://phet-dev.colorado.edu/decaf/nuclear-physics/1.0.0-dev.4/nuclear-physics.html?simulation=alpha-decay
https://phet-dev.colorado.edu/decaf/nuclear-physics/1.0.0-dev.4/nuclear-physics.html?simulation=beta-decay
https://phet-dev.colorado.edu/decaf/nuclear-physics/1.0.0-dev.4/nuclear-physics.html?simulation=nuclear-fission
https://phet-dev.colorado.edu/decaf/nuclear-physics/1.0.0-dev.4/nuclear-physics.html?simulation=radioactive-dating-game
https://phet-dev.colorado.edu/decaf/optical-quantum-control/1.0.0-dev.4/optical-quantum-control.html
https://phet-dev.colorado.edu/decaf/optical-tweezers/1.0.0-dev.6/optical-tweezers.html?simulation=molecular-motors
https://phet-dev.colorado.edu/decaf/optical-tweezers/1.0.0-dev.6/optical-tweezers.html?simulation=optical-tweezers
https://phet-dev.colorado.edu/decaf/optical-tweezers/1.0.0-dev.6/optical-tweezers.html?simulation=stretching-dna
https://phet-dev.colorado.edu/decaf/photoelectric/1.0.0-dev.5/photoelectric.html
https://phet-dev.colorado.edu/decaf/quantum-tunneling/1.0.0-dev.4/quantum-tunneling.html
https://phet-dev.colorado.edu/decaf/quantum-wave-interference/1.0.0-dev.4/quantum-wave-interference.html?simulation=davisson-germer
https://phet-dev.colorado.edu/decaf/quantum-wave-interference/1.0.0-dev.4/quantum-wave-interference.html?simulation=quantum-wave-interference
https://phet-dev.colorado.edu/decaf/radio-waves/1.0.0-dev.4/radio-waves.html
https://phet-dev.colorado.edu/decaf/reactions-and-rates/1.0.0-dev.6/reactions-and-rates.html
https://phet-dev.colorado.edu/decaf/rotation/1.0.0-dev.4/rotation.html?simulation=rotation
https://phet-dev.colorado.edu/decaf/rotation/1.0.0-dev.4/rotation.html?simulation=torque
https://phet-dev.colorado.edu/decaf/self-driven-particle-model/1.0.0-dev.4/self-driven-particle-model.html
https://phet-dev.colorado.edu/decaf/semiconductor/1.0.0-dev.4/semiconductor.html
https://phet-dev.colorado.edu/decaf/signal-circuit/1.0.0-dev.4/signal-circuit.html
https://phet-dev.colorado.edu/decaf/soluble-salts/1.0.0-dev.5/soluble-salts.html
https://phet-dev.colorado.edu/decaf/sugar-and-salt-solutions/1.0.0-dev.4/sugar-and-salt-solutions.html?simulation=sugar-and-salt-solutions
https://phet-dev.colorado.edu/decaf/sugar-and-salt-solutions/1.0.0-dev.4/sugar-and-salt-solutions.html?simulation=sugar-and-salt-solutions-macro
https://phet-dev.colorado.edu/decaf/sugar-and-salt-solutions/1.0.0-dev.4/sugar-and-salt-solutions.html?simulation=sugar-and-salt-solutions-micro
https://phet-dev.colorado.edu/decaf/the-ramp/1.0.0-dev.4/the-ramp.html?simulation=the-ramp

This will not invalidate testing in #497, but new testing should be on these Java 7 sims.

@ariel-phet requested that @KatieWoe add these to the testing spreadsheet.

**Comment by KatieWoe** [comment]
Spreadsheet: https://docs.google.com/spreadsheets/d/10bO1Eimm5Y7TH4o7QPebpNUaIItxYK-VnKcSe24TXmc/edit#gid=147319993

**Comment by KatieWoe** [comment]
Spreadsheet (https://docs.google.com/spreadsheets/d/10bO1Eimm5Y7TH4o7QPebpNUaIItxYK-VnKcSe24TXmc/edit#gid=147319993) is pretty much done. There is a QA recommendation section that has Publish, No, and Publish with discussion (probably ok to publish but with issues you might want to go over). IE and Win chrome still finishing up, but I feel pretty good at this juncture. IE pretty much is not usable, ChromeOS is spotty, and iPad is hit or miss on controls. Let me know if you have questions.

**Comment by samreid** [comment]
Awesome, thanks!  Closing.
