### ISSUE TITLE
RC Test: Forces and Motion Basics 2.3.0-rc.1

### ISSUE THREAD

**Issue by phet-steele** [phetsims/QA#5]
( @jessegreenberg @arouinfar @oliver-phet ) 

2.3.0-rc.1 is ready for RC testing. 

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-rc.1/forces-and-motion-basics_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-rc.1/forces-and-motion-basics_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1U2-hwtOCMVTnnWaviONSJUNEqseKB-d_1Sc_ttZRILU/edit#gid=1018120986)**

**Issues to Verify**
This RC is to address the user requested features from the following link.
[See here](https://github.com/phetsims/forces-and-motion-basics/issues/220#issuecomment-305549179) for a list of the things that were changed in the parent issues.
Here is the list of changes from that issue:
>- All changes are in the "Net Force" screen
>- NetForceScreenView includes two new ```CartStopperNodes``` placed at a location which will stop movement of the cart.
>- The cart can move about twice as far along the screen since the stoppers are placed farther than the previous version allowed the cart to move.
>- The pullers stand up when the game is over
>- The speedometer was added to the center of the cart, showing speed of the moving cart
>- A "Speed" checkbox was added to the control panel, which toggles visibility of a speedometer

**Please also verify**
- [ ] stringTest=double (all strings doubled)
- [ ] stringTest=long (exceptionally long strings)
- [ ] stringTest=X (short strings)
- [ ] stringTest=rtl (right-to-left)
- [ ] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [ ] showPointerAreas (touchArea=red, mouseArea=blue)
- [ ] Full screen test
- [ ] Screenshot test
- [ ] Legends of Learning harness test

If any new issues are found, please note them in https://github.com/phetsims/forces-and-motion-basics/issues/227 and reference this issue.  

@ariel-phet please assign and prioritize

**Comment by jonathanolson** [comment]
This RC does not have all of the RichText fixes, see https://github.com/phetsims/QA/issues/6#issuecomment-311330798. Recommend applying the fix and releasing a new RC.

**Comment by jessegreenberg** [comment]
@phet-steele please hold off on testing until the next RC is deployed to include above fixes.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/QA/issues/11 is a new RC with the updated scenery-phet SHA. Closing.
