### ISSUE TITLE
RC Test: Energy Skate Park Basics 1.4.0-phetiorc.1

### ISSUE THREAD

**Issue by phet-steele** [phetsims/QA#50]
See #41 for any details.

[Root Directory](http://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.4.0-phetiorc.1)

[Testing Matrix](https://docs.google.com/spreadsheets/d/1kaJd59mURbe9tPcHZsJPRXZH2yU9jm_AjsdPSmojTcc/edit#gid=1455522512)

If any new issues are found, please note them in https://github.com/phetsims/energy-skate-park-basics/issues and reference this issue.

**Comment by phet-steele** [comment]
@samreid We can call this done, please review the above issues.

**Comment by samreid** [comment]
Thanks for testing, I'll continue in https://github.com/phetsims/energy-skate-park-basics/issues/375

**Comment by samreid** [comment]
Pinging @ariel-phet as a reminder to read through the open issues from Sep 19 above and see which need further testing or work before the next Dev test.

**Comment by ariel-phet** [comment]
@samreid will do....I had been ignoring for a bit since it seemed like other things were taking precedence

**Comment by phet-steele** [comment]
@samreid I appreciate getting AP on this, but I'm going to remove priority on this issue. Priority labels in this repo are used as a to-do list for the QA team. I don't want to cause confusion when the team thinks they are meant to test this sim. Besides, looks like AP is aware of the urgency now!

**Comment by ariel-phet** [comment]
@samreid @phet-steele all of the open issues have been reviewed, it looks to me like all open issues need further testing (most of them have further questions for the QA team that have not been answered). Back to @phet-steele and @samreid

**Comment by phet-steele** [comment]
@samreid I did what I could, but master is not that stable for this sim. It's hard to verify fixes for past problems 😢. @ariel-phet @samreid would you recommend QA take a pass at logging errors for this sim before getting much farther?

**Comment by jessegreenberg** [comment]
Very sorry, the break was my fault - @phet-steele isolated that the break was accidentally introduced in a commit I made. While adding some JSDoc I accidentally modified a variable name. I will review commits I made to ESPB and make sure nothing else was introduced.

Will further  testing for this issue be off of master or 1.4.0-phetiorc.1?

**Comment by ariel-phet** [comment]
@phet-steele I recommend getting master stable, and then testing off rc.2

**Comment by samreid** [comment]
Let's continue in https://github.com/phetsims/energy-skate-park-basics/issues/411
