### ISSUE TITLE
Testing new deploys microwaves and ideal gas

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#500]
I published microwaves and ideal gas (balloons and buoyancy + reversible reactions).  It seems like they should be spot checked before we give them to Oliver.

Can you please test using the phet.colorado.edu latest links?

**Comment by KatieWoe** [comment]
Can you link to the issues that were fixed @samreid so other testers know what to check for?

**Comment by samreid** [comment]
For ideal gas, no changes were made and hence it is just a sanity spot check

https://phet.colorado.edu/sims/cheerpj/ideal-gas/latest/ideal-gas.html?simulation=balloons-and-buoyancy
https://phet.colorado.edu/sims/cheerpj/ideal-gas/latest/ideal-gas.html?simulation=reversible-reactions

For Microwaves, it is the same as dev.4 but just a sanity check to make sure the production version is good.
https://phet.colorado.edu/sims/cheerpj/microwaves/latest/microwaves.html

**Comment by KatieWoe** [comment]
All 3 load and look ok on Win 10 Chrome. Microwaves may be able to use the size fix in extreme circumstances, but it isn't vital.
![microwaves](https://user-images.githubusercontent.com/41024075/81124168-00827180-8ef2-11ea-968c-3e2c530d4731.png)

**Comment by samreid** [comment]
Excellent, thanks!
