### ISSUE TITLE
Dev test: States of Matter 1.2.0-dev.4

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#501]
@KatieWoe and @arouinfar - States of Matter 1.2.0-dev.4 is ready for dev testing. This is being done in preparation for releasing the phet-io version of States of Matter Basics to a customer, hopefully within the next couple of weeks.  Testing the non-basics version should help to vet all changes that have been made in the process of adding phet-io to this sim. Please document issues in https://github.com/phetsims/states-of-matter/issues and link to this issue.

A lot of changes were made to the code over the course of adding PhET-iO support, so this testing is intended to make sure that no problems were introduced to the primary (i.e. non-PhET-iO) functionality and that the basic PhET-iO functionality works.  The structure and naming of the tandems are being reviewed by others, no need to do that as part of this testing.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Wrung through the string tests on at least one platform, especially if it is about to go to rc.

<h3>Focus and Special Instructions</h3>

This is intended to be release as a dev version to a customer who has plans to integrate it into a learning environment where they take advantage of PhET-iO features.  Because the addition of PhET-iO support has caused a lot of code to change, there will need to be a thorough regression test of the basic functionality on all platforms as well as testing of PhET-iO functionality.  Since we have made previous releases of PhET-iO-enabled simulations to this customer, those previous test tasks may also provide guidance.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-dev.4/phet/states-of-matter_all_phet.html)**

<hr>

</details>

<details>
<summary><b>PhET-iO Dev Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make sure the simulation loads without crashing or throwing errors.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, all browsers
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers, including IE
- [x] Latest Chrome OS, Chrome

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-dev.4/phet-io/)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
Marking high priority for now since this project is part of fulfilling a customer requirement

**Comment by ariel-phet** [comment]
@KatieWoe bumping to current top priority

**Comment by KatieWoe** [comment]
QA is done

**Comment by jbphet** [comment]
Thanks QA team!  I'll close this one and we will tackle the individual issues from here.
