### ISSUE TITLE
Flexible cloudflare SSL with sitekit (wordpress)

### ISSUE THREAD

**Issue by levani854** [phetsims/QA#502]
hope you ll help me. Hello i have problem. i installed site kit and connected to my google account i connected google search console, google analytics, adsense, and pagespeed insight, and it started work properly google tools data showed up in my dashboard. but i faced problem wen i activated flexible cloudflare SSL. google services started activating endless loop and i m still waiting and trying to solve problem. i tried deactive SSL and it worked site kit restored and showed up everything. but when i start activating SSL it occurs again. (endless loop)please tell me how to fix it and what's wrong with that. thank you in advance

**Comment by ariel-phet** [comment]
Hello @levani854 we think you might have posted this question to the incorrect github repo. We are the PhET project (http://phet.colorado.edu) and we cannot help you with this issue (which sounds like a wordpress specific issue). 

Closing.
