### ISSUE TITLE
how to communicate PhET-iO testing requirements to QA

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#504]
Over in https://github.com/phetsims/natural-selection/issues/58, we identified the need to have a general discussion about how to communicate PhET-iO testing requirements to QA. 

For example, Natural Selection has a long list of client requirements, and there are some rather complicated general requirements.  Do we need a document that describes what to test and how to test? Would the PhET-iO Design document suffice? Would the document that @arouinfar has been preparing for clients be useful?  Something else? 

It was suggested that this be discussed during weekly phet-io or design meeting.

**Comment by KatieWoe** [comment]
There is a section in the test template for special instruction and specific things to test as a starting point.

**Comment by pixelzoom** [comment]
Yep, I'm familiar with that section in the template.  But I don't think the full PhET-iO requirements and test instructions should live in dev/RC test issues.  I don't want to have to keep copying those things from issue to issue, since the lifetime of the PhET-iO requirements is longer than the issues. And in the case of Natural Selection, it's going to be a large amount of stuff to cram into an issue. Better to have a document that is reference from the QA GitHub issue(s).

**Comment by KatieWoe** [comment]
When this comes up for a meeting let me know. But at the very least it needs to be easy to find in the issue when we get a testing task.

**Comment by muedli** [comment]
@KatieWoe, perhaps a link in the dev or RC issue to the QA book? We could add @pixelzoom's testing requirements to the PhET-iO section of the QA book.

**Comment by KatieWoe** [comment]
It sounds like he's talking about different requirements for different sims, which means the QA book wouldn't be the place.

**Comment by pixelzoom** [comment]
Correct, sim-specific requirements.

**Comment by arouinfar** [comment]
> Would the document that @arouinfar has been preparing for clients be useful? Something else?

I'm not sure that the client guides are necessarily the most useful thing for QA. For pH Scale I created a general guide for instructional designers as well as a separate doc for the client-specific requests. The PhET-iO docs associated with ph-scale can be found here:
https://drive.google.com/drive/u/0/folders/1POGTwDdpP0YHGkslz1T0BrS9v14RbaRa

This folder is only accessible by the a subset of the PhET team, but I've given @KatieWoe and @muedli view access for the purpose of this discussion. (I see no reason why QA couldn't be shared on these documents, in general, though.)

The Client Request doc lists the specific tandems/procedures for each client-requested customization. This could be useful for QA, but for ph-scale, the customizations weren't particularly complicated and I don't think they necessitated specific testing.

The PhET-iO Guide is a bit general, and the only potentially useful information for QA would be the sim-specific query parameters. I would think that this information would be documented somewhere else for QA, though.

**Comment by pixelzoom** [comment]
I had not previously heard about these clients guides. I had a look - very nice!  If they are going to be part of standard process in the future, perhaps they should get a quick review by the developer.

**Comment by pixelzoom** [comment]
> The Client Request doc lists the specific tandems/procedures for each client-requested customization. This could be useful for QA, but for ph-scale, the customizations weren't particularly complicated and I don't think they necessitated specific testing.

For example, https://docs.google.com/document/d/1v8A13jjUtWsmvPdqi6qdJdrTqRC5j5EuMKT93IYgZk0/edit.

Whether the customizations were complicated is not really relevant. We need to know what the requested features were, what what phetioIDs can be tested to confirm that the requested features work.  And this looks like exactly what is needed for testing client requests. 

If we had something similar for "general requests that are sim-specific", then (combined with the Client Requests doc) I think we'd something that would be useful as a sort of QA checklist.

**Comment by ariel-phet** [comment]
@KatieWoe when you and your team get to testing pH Scale, please put feedback in this issue as to how using the pdf of client requests provided by @arouinfar  worked in terms of communicating testing requirements. We should refine the process if needed, so please mark down any recommendations or potential improvements in this issue.

**Comment by KatieWoe** [comment]
This worked really well. A better way of integrating this into the rc issue would be nice

**Comment by arouinfar** [comment]
Thanks @KatieWoe. All future PhET-iO QA tests will include the guides on the Wrapper Index Page. For example: https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.12/phet-io/

Does that address your concerns, or is there something you would like to see added to the QA issue templates?

**Comment by KatieWoe** [comment]
That should be enough

**Comment by KatieWoe** [comment]
I think this can be closed. If you disagree @arouinfar ot @pixelzoom feel free to reopen.
