### ISSUE TITLE
Dev test: gravity-and-orbits/1.2.0-dev.10

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#505]
@ariel-phet @KatieWoe @arouinfar, gravity-and-orbits/1.2.0-dev.10 is ready for dev testing. We had a milestone to release this to the client by May 22, as described in https://github.com/phetsims/gravity-and-orbits/issues/315. Also, @kathy-phet recommended to test this after States of Matter testing is complete (which looks like it wrapped up last week). 
 Document issues in https://github.com/phetsims/gravity-and-orbits/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.

<h3>Focus and Special Instructions</h3>

Physics implementation and numerical constants have changed, please test accordingly.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers
- [x] Latest Chrome OS, Chrome

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.10/phet/gravity-and-orbits_en_phet.html)**

<hr>

</details>

<details>
<summary><b>PhET-iO Dev Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make sure the simulation loads without crashing or throwing errors.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, all browsers
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers, including IE
- [x] Latest Chrome OS, Chrome

<h3>Focus and Special Instructions</h3>

Basic testing to make sure the client can achieve their customization goals for the PhET-iO version.

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.10/phet-io/)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Memory test looks ok:
![Memorytestresult](https://user-images.githubusercontent.com/41024075/83198478-78f8de80-a0fc-11ea-88d1-8c2ab6cb3c97.png)

**Comment by ariel-phet** [comment]
Current top testing priority

**Comment by zepumph** [comment]
As part of this issue, can you please confirm that https://github.com/phetsims/states-of-matter/issues/281 is fixed. That issue is not sim specific, and should be dealt with in this version of phet-io.

**Comment by KatieWoe** [comment]
ChromeOS seemed to be a bit slow generally. Particularly in Phet-io

**Comment by KatieWoe** [comment]
QA is done
