### ISSUE TITLE
PhET-iO Studio test

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#508]
Large amounts of work has gone into the Studio, mostly under the hood, in the past few weeks. This work centers around the structure of the tree, and how Studio keeps track of PhET-iO Elements on the wrapper side in https://github.com/phetsims/studio/issues/30. From this work, it would be great to get some QA time on Studio.

**What to test**
* [States of Matter Studio](https://phet-dev.colorado.edu/html/states-of-matter/1.2.0-dev.6/phet-io/wrappers/studio)
* [Charges and Fields Studio](https://phet-dev.colorado.edu/html/charges-and-fields/1.1.0-dev.9/phet-io/wrappers/studio)

**What to test (take 2)**
* Using the studio tree, and all studio features that may change the Studio tree
* A few browsers, all development has been done on Chrome (windows and mac), so perhaps expand to Firefox and Safari?
* Charges and fields creates some elements dynamically. Please exercise this by creating/destroying/manipulating-with-studio charged particles and electric field sensors. 
* The most important piece is to think of this as a regression test, as we didn't add any features, we only improved the code with refactoring. Let's make sure we didn't break anything.

Thanks!

Over to @ariel-phet to assign and prioritize.

**Comment by ariel-phet** [comment]
@KatieWoe this item should actually now be top priority

**Comment by KatieWoe** [comment]
- [ ] Win 10 Chrome
- [ ] Win 10 Firefox
- [ ] Win 10 Edge
- [ ] Mac 10.15 Chrome
- [ ] Mac 10.15 Safari
- [ ] ChromeOS
@zepumph let me know if there are any other platforms you want tested

**Comment by KatieWoe** [comment]
From Slack:
>Michael Kauzmann:spiral_calendar_pad:  10:50 AM
Today I heard @KatieWoe saying that there was still more testing to be done on the studio test. I know QA is swamped, so I wanted to say that I feel like I have gotten what I want out of this test, and Studio will still need to go through an RC test before any sim is published with it. All this is to say that I don't want this blocking other, likely higher priority testing. We already published the SOM dev version with the studio updates that we created the testing issue for.
Ariel Paul  11:21 AM
That sounds good to me

QA is done

**Comment by zepumph** [comment]
Thanks! This has been an excellent round of testing. Thanks for all the good bugs. Tagging @kathy-phet @samreid @chrisklus to let them know we cut things a bit short. We will pick this up next time we make an RC. There have been more changes in studio since this test version anyways, so it feels good to me!
