### ISSUE TITLE
RC Test: Build A Molecule 1.0.0-rc.1

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#509]
@ariel-phet , @arouinfar , build-a-molecule/1.0.0-rc.1 is ready for RC testing. Document issues in https://github.com/phetsims/build-a-molecule/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if there is a problem.

<h3>Focus and Special Instructions</h3>

This is the first RC, so there aren't many issues to verify and this sim has just completed a dev-test cycle. I would ask QA to pay close attention to the bonding behaviors of molecules, especially as mentioned in https://github.com/phetsims/build-a-molecule/issues/197#issue-637892197 and https://github.com/phetsims/build-a-molecule/issues/148#issuecomment-611099900. 

<h3>Issues to Verify</h3>

- [ ] [Add Proper Credits](https://github.com/phetsims/build-a-molecule/issues/168)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is "status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.1/phet/build-a-molecule_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.1/phet/build-a-molecule_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.1/phet/xhtml/build-a-molecule_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1tVDo3KDC-PyNlOh3rjunyKxzR47cTFgFUm9u-DJbGDo/edit#gid=820742464)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe could be done a a concurrent priority to #507

**Comment by KatieWoe** [comment]
Memory Test:
Start: 308 MB
1 min: 324
2 min: 329
3 min: 331
4 min: 332
5 min: console crashed

It looks like a fairly big memory footprint, but without an obvious leaks. Leaving it up to @Denz1994 on if it needs to be addressed.

**Comment by Denz1994** [comment]
> It looks like a fairly big memory footprint, but without an obvious leaks. Leaving it up to @Denz1994 on if it needs to be addressed.

The memory footprint should be fairly large compared to other sims due to the size of the Pubchem data set. We've taken steps to optimize this in #https://github.com/phetsims/build-a-molecule/issues/115 and #https://github.com/phetsims/build-a-molecule/issues/173.

**Comment by Denz1994** [comment]
As per a discussion on Slack with @ariel-phet, this issue will be closed and BAM should move to the next RC testing for spot-checking. Though the entire test matrix was not completed in this test we are confident enough to move forward to the next test cycle. 

The remaining open issues will be assigned for spot-checking in the next QA cycle. Closing this one for now.
