### ISSUE TITLE
Website: Test the Login Donation Ask

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#510]
QA, please test that the login donation dialog is looking correct on our supported devices and browsers.  For each account, this dialog will be displayed on login if it has not been shown within the past 30 days.  In addition, if the user clicks "I already donated in 2020!" it will not display again until Jan 1.

The logic on when to display will be very slow to test, this issue is just to focus on whether it appears correct when it does show up.  I can reset the counter as needed so you can test this.

**Comment by mattpen** [comment]
This is how it should appear in most cases.  It will wrap/scale down on smaller screens.

![image](https://user-images.githubusercontent.com/11747676/85307466-2eede900-b46d-11ea-944b-ccb190ee1fe0.png)

**Comment by KatieWoe** [comment]
@ariel-phet for priority.
Test on:
- [ ] iPhone
- [ ] iPad 12
- [ ] iPad 13
- [ ] iPad 13 VO
---
- [ ] Win 10 Chrome
- [ ] Win 10 Chrome Jaws
- [ ] Win 10 Firefox
- [ ] Win 10 Firefox NVDA
- [ ] Win 10 Edge
---
- [ ] ChromeOS
---
- [ ] Mac 10.15 Chrome
- [ ] Mac 10.15 Safari
- [ ] Mac 10.15 Safari VO
---
- [ ] Mac 10.14 Chrome
- [ ] Mac 10.14 Safari
- [ ] Mac 10.13 Chrome
- [ ] Mac 10.13 Safari
- [ ] Mac 10.12 Chrome
- [ ] Mac 10.12 Safari
- [ ] Mac 10.11 Chrome
- [ ] Mac 10.11 Safari
- [ ] Mac 10.10 Safari

**Comment by ariel-phet** [comment]
@KatieWoe as this should be quick and is important currently, it should be a concurrent top priority with #508 (so if you need a break from #508 test some platforms for this ask)

**Comment by KatieWoe** [comment]
QA is done
