### ISSUE TITLE
Dev Test: Gravity and Orbits 1.2.0-dev.16/phet-io/

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#519]
@ariel-phet, @arouinfar, @kathy-phet, @KatieWoe, 1.2.0-dev.16/phet-io/ is ready for dev testing. If this passes testing,
this dev version will be delivered to a client. Ideally by 11/1 for a dev version and 12/15 for a published version, but sooner is best for a dev delivery.  Please be aware this is the 2nd dev version for QA, and several of the issues discovered by QA in the first dev version were scheduled to be implemented for RC, but not for the 2nd dev version.  Document issues in https://github.com/phetsims/gravity-and-orbits/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.

<h3>Focus and Special Instructions</h3>

Only the PhET-iO version will be delivered to the client, but any bugs discovered in the PhET brand version will likely 
appear in the PhET-iO version as well.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers (IE dropped)
- [x] Latest Chrome OS, Chrome

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.16/phet/gravity-and-orbits_all_phet.html)**

<hr>

</details>

<details>
<summary><b>PhET-iO Dev Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, all browsers
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers (IE dropped)
- [x] Latest Chrome OS, Chrome

<h3>Focus and Special Instructions</h3>

For this version, studio and customizability are more important than other features like data stream.

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.16/phet-io/)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by samreid** [comment]
Adding a reference to the issue where we prepared the dev version: https://github.com/phetsims/gravity-and-orbits/issues/345

**Comment by ariel-phet** [comment]
Putting at medium priority at the moment, given the current QA backlog

**Comment by zepumph** [comment]
Discussed today during phet-io meeting. This dev version most likely has all the same phet-io bugs as reported in https://github.com/phetsims/QA/issues/514. These are currently fixed on master, but likely we should take a GAO dev version from master now before testing this.

**Comment by zepumph** [comment]
@pixelzoom mentioned that perhaps the best process is to have @KatieWoe ping @samreid when she is ready to test this. Then we can get a fresh dev version at that time.

**Comment by samreid** [comment]
I agree, the dev version 1.2.0-dev.12 is stale, please reach out to me when ready for testing and I'll publish a new version.

**Comment by samreid** [comment]
@ariel-phet or @KatieWoe can you estimate when QA may be ready for the next dev test for Gravity and Orbits?  It may help us ensure master is stable around that time.

**Comment by ariel-phet** [comment]
@samreid I think around Monday Aug 31st would be my guess currently, depending on how Ph Scale testing and such goes next week

**Comment by samreid** [comment]
I published a fresh dev version with both brands:
https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.16/phet/
https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.16/phet-io/

**Comment by KatieWoe** [comment]
I've sometimes seen times where the path doesn't fade, but I can't reproduce it reliably, I just see it some times. @arouinfar if you want to go over it let me know, but I'm not always convinced I'm seeing anything and I don't know what causes it, so let me know if you want an issue for it.
To be clear, the path goes away, but it does it suddenly, rather than tapering off.

**Comment by KatieWoe** [comment]
QA is done

**Comment by arouinfar** [comment]
> To be clear, the path goes away, but it does it suddenly, rather than tapering off.

This sounds like the path occasionally has full opacity, which seems relatively minor to me. Given that it isn't reliably reproduced, I don't think it warrants an issue.

**Comment by samreid** [comment]
All issues mentioned above are closed, ready for review or on my project board. Thanks for the great test @KatieWoe, closing.
