### ISSUE TITLE
Test iOS 11

### ISSUE THREAD

**Issue by phet-steele** [phetsims/QA#52]
@lmulhall-phet Please spot check with production HTML5 sims in mobile Safari:

- [x] phetsims/joist/issues/234 (just comment in that issue if it still occurs or not)
- [x] Below sims with sound have working sound
- [x] Molecule Shapes
- [x] Energy Skate Park Basics
- [x] Arithmetic
- [x] Acid Base Solutions
- [x] Charges and Fields
- [x] Color Vision
- [x] Projectile Motion
- [x] Plinko Probability
- [x] States of Matter
- [x] Wave on a String

Just spend about ~1 minute on each sim. At least do the above, but also feel free to do additional ones.

Then do everything again, but this time in...

- [x] ...the PhET App!! (Don't test the joist issue here)

Labeling top priority because it should be quick.

**Comment by lmulhall-phet** [comment]
Everything looks good! Closing. :)
