### ISSUE TITLE
Prototype test: Natural Selection 1.0.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#522]
@amanda-phet, @ariel-phet, @kathy-phet, @KatieWoe, natural-selection/1.0.0-rc.1 is ready for prototype testing. This simulation will be put on the website as a prototype and will likely have more bugs than a publication-ready simulation. 

Document issues in https://github.com/phetsims/natural-selection/issues and link to this issue. **Issues should focus on base usability and pedagogy.**

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Play with the simulation normally.
- Make sure you can't lose anything.
- Complete the test matrix.
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- Focus on pedagogy issues and bugs that break the sim. 
- If you find bugs beyond pedagogy/breaking, still document these bugs as github issues.
- If a11y aspects are present, test them, but with an eye for "normal use".

<h3>Focus and Special Instructions</h3>

There are many sim-specific query parameters in [NaturalSelectionQueryParameters.js](https://github.com/phetsims/natural-selection/blob/master/js/common/NaturalSelectionQueryParameters.js).  The only one that you need to consider for prototype testing is `secondsPerGeneration` (default 10), which determines how long it takes to complete 1 cycle of the generation clock. Decrease this value to make the clock run faster.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-rc.1/phet/natural-selection_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1UAboTyxa4BrN9jxYdR7yhzvJgxz0dtIy4cT5UwgGbDQ/edit#gid=415113551)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe assigning this one directly to @phet-steele as he expressed interest in performing this test as a way to "get back to the swing of things"

@phet-steele marking as medium priority as this test does not need to be extensive, but teachers will definitely be excited for the prototype version so sooner is better from that regard

**Comment by ariel-phet** [comment]
In terms of important testing this prototype is basically done (thanks @phet-steele!)

I will do some cursory testing on an iPad and ask @amanda-phet and @oliver-phet to take a quick look on Mac

**Comment by pixelzoom** [comment]
The 4 issues identified by @phet-steele have been addressed, awaiting review and verification in the next RC.

Assign this issue to me when @ariel-phet and @oliver-phet have complete their "quick looks" and I'll proceed with the next RC.  The next RC can likely be a "spot check" to verify the issues that @phet-steele identified.

**Comment by pixelzoom** [comment]
We'll also need to verify the model changes the @amanda-phet requested in the next RC -- https://github.com/phetsims/natural-selection/issues/152, https://github.com/phetsims/natural-selection/issues/153.

**Comment by amanda-phet** [comment]
I believe the testing matrix is complete now.

**Comment by pixelzoom** [comment]
In retrospect we should have done a dev test first. There have been a lot of changed required for this RC. And it has become increasingly difficult (and time-consuming) to patch changes into the 1.0 branch, to the point where forward progress on master has ground to a halt.  After consulting with @ariel-phet, I'm going to give up on try to patch the 1.0 branch, and only make changes in master.  The next RC will either be in a new branch, or I will merge all changes from master into 1.0.  And before that RC, we'll do a quick test on a dev version.

**Comment by pixelzoom** [comment]
"Issues to Verify" for the next RC:

PhET-iO:
- [ ] [empty client guides published with this sim design:phet-io](https://github.com/phetsims/ph-scale/issues/167)
- [ ] [Studio search feature is broken](https://github.com/phetsims/ph-scale/issues/172)
- [ ] [Add "Item" suffix to Solute combo box items](https://github.com/phetsims/ph-scale/issues/195)

**Comment by pixelzoom** [comment]
There's a new plan for the prototype, see https://github.com/phetsims/natural-selection/issues/116#issuecomment-682159770.

Closing this issue.
