### ISSUE TITLE
Dev test: Energy Skate Park 1.0.0-dev.17 Graphs Screen

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#523]
@arouinfar, @ariel-phet, @kathy-phet, @KatieWoe energy-skate-park/1.0.0-dev.17 is ready for a dev test of the **Graphs** screen. Document issues in https://github.com/phetsims/energy-skate-park/issues and link to this
issue.

Since the last dev test the Energy Graph was essentially re-written. And there are other new features on this screen too. The biggest one is skater playback after dragging the graph cursor. The screen should behave like

 - While running, the graph should record energy distribution and other physical state.
 - If you drag the cursor, skater and all other physical state should be restored to the current cursor time.
 - If you release the cursor to the left of the newest saved data on the plot, it will play back the simulation recording starting from where the cursor is dropped.
 - If you change any physical properties while the sim is playing back, all saved data to the right of the cursor should be removed.

Please test this part and the whole Energy graph in particular, but also please check the "Graphs" screen for other issues as well. Thanks!

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>General Dev Test Platforms</h3>

- [ ] Latest macOS, Chrome and Safari
- [ ] Latest iOS, Safari
- [ ] Windows 10, all browsers (IE dropped)
- [ ] Latest Chrome OS, Chrome

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.17/phet/energy-skate-park_all_phet.html?screens=3)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by arouinfar** [comment]
@ariel-phet @jessegreenberg I spent some time testing the Graphs screen, and I couldn't find any issues other than a minor pixel polish unrelated to the griddle work.

**Comment by ariel-phet** [comment]
@jessegreenberg I think that is good enough testing for this issue. Assigning back to you to close.

**Comment by jessegreenberg** [comment]
OK sounds good - thanks!
