### ISSUE TITLE
RC test: States of Matter: Basics 1.2.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#526]
@KatieWoe , @ariel-phet, @arouinfar, and @kathy-phet - states-of-matter-basics/1.2.0-rc.1 is ready for RC testing.  This includes both phet and phet-io brand and intended to be shared with a client in mid-August.  Document issues in https://github.com/phetsims/states-of-matter-basics/issues and link to this issue.

Since this sim is a subset of states-of-matter, and states-of-matter is also being released at this time, it would probably be best to thoroughly test states-of-matter, and then do a more basic test on this one.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

Since the phet-io version is being shared with a client who intends to integrate it into a learning environment, the phet-io version should be thoroughly tested.  Also, lots of under-the-hood changes have occurred, so the phet version should get a fair amount of scrutiny too.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.0-rc.1/phet/states-of-matter-basics_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.0-rc.1/phet/states-of-matter-basics_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.0-rc.1/phet/xhtml/states-of-matter-basics_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1-bBeW6JcfLnAsxM4-EIeNVLn0rBcI8J1ph15_rvtT5g/edit#gid=551340323)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fstates-of-matter-basics%2F1.2.0-rc.1%2Fphet%2Fstates-of-matter-basics_en_phet.html)**

<hr>

</details>

<details>
<summary><b>PhET-iO RC Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.
- For an update or maintenance release please check the backwards compatibility of the playback wrapper.
[Here's the link to the previous wrapper.](link)
- Load the login wrapper just to make sure it works. Do so by adding this link from the sim deployed root: 
  ```
  /wrappers/login/?wrapper=record&validationRule=validateDigits&&numberOfDigits=5&promptText=ENTER_A_5_DIGIT_NUMBER
  ```   
  Further instructions in QA Book
- Conduct a recording test to Metacog, further instructions in the QA Book. Do this for iPadOS + Safari and one other random platform.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.0-rc.1/phet-io/)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1xDwbLY-cFxZ3nuupCLgtp-Qx6mZOjQyWXFtJCu_hTTI/edit#gid=731578196)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe high priority but after #525 since this is a subset of that test.

**Comment by jbphet** [comment]
I'm going to close this, since I'm about to publish SOM 1.2.0-rc.2, and it would be better to roll a new release of SOMB as well so that SOM and SOMB are using as much of the same code as possible.
