### ISSUE TITLE
RC test: Atomic Interactions 1.2.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#527]
@KatieWoe , @ariel-phet, @arouinfar, and @kathy-phet - atomic-interactions/1.2.0-rc.1 is ready for RC testing.  While its "parent" sim (states-of-matter) is having both the phet and phet-io brands released, we are only doing the phet brand for this one.

For the most part, this sim is a subset of states-of-matter, but it has a feature where heterogeneous atoms can be chosen, which can't be done in SOM, so it would probably be best to test SOM thoroughly, then focus on this feature that is unique to atomic-interactions for additional testing.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

Issues to test:
[ ] - [Pinned and Moving strings very small](https://github.com/phetsims/atomic-interactions/issues/74)

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/atomic-interactions/1.2.0-rc.1/phet/atomic-interactions_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/atomic-interactions/1.2.0-rc.1/phet/atomic-interactions_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/atomic-interactions/1.2.0-rc.1/phet/xhtml/atomic-interactions_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1KffV-UyjeB7GyCcdDooE5Nh02k3QUTlo9MVHT3E89G8/edit#gid=1010763750)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D&url=https%3A%2F%2Fphet-dev.colorado.edu%2Fhtml%2Fatomic-interactions%2F1.2.0-rc.1%2Fphet%2Fatomic-interactions_en_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
@KatieWoe currently marking this test as low since it is not necessary as part of iO deliverables

**Comment by jbphet** [comment]
I'm going to close this, since I'm about to publish SOM 1.2.0-rc.2, and it would be better to roll a new release of AI as well so that SOM and AI are using as much of the same code as possible.
