### ISSUE TITLE
RC test Resistance in a Wire 1.3.0-phetiorc.3

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#53]
@emily-phet @terracoda @ariel-phet @phet-steele @zepumph, Resistance in a Wire 1.3.0-phetiorc.3 is ready for RC testing.

**[Root Directory](https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-phetiorc.3)**

**[Testing Matrix](https://docs.google.com/spreadsheets/d/1gTOrMepJm5-fnNVWc81_dC4AqB1GMsrQHzv8cIHRF60/edit#gid=2)**

**Keyboard Navigation**
<s>In addition to  PhET-iO, this version also has keyboard navigation.  Please test keyboard navigation on all of our supported platforms with a keyboard. See the "Keyboard Help Button" in the navigation bar for information about expected keyboard behavior.</s>
EDIT: Not testing keyboard-nav in PhET-iO.

If any new issues are found, please note them in https://github.com/phetsims/resistance-in-a-wire/issues and reference this issue.

Thanks! And let me know if we should discuss more about testing keyboard navigation.

Assigning to @ariel-phet to prioritize.

**Comment by emily-phet** [comment]
yay! one step closer to publication. :)

**Comment by terracoda** [comment]
Yes, exciting! I hope the RC testing goes well.

**Comment by zepumph** [comment]
@phet-steele can you confirm that https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-phetiorc.3/wrappers/index/ is working better and as expected. Please let me know if you need more from me.

**Comment by phet-steele** [comment]
> @phet-steele can you confirm that https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-phetiorc.3/wrappers/index/ is working better and as expected

Beautiful @zepumph! I do not think I need you for anything else here. I'll update links to point to the new rc.

**Comment by zepumph** [comment]
As a reminder, final commits from https://github.com/phetsims/resistance-in-a-wire/issues/104 will need to be cherry picked into the rc branch.

**Comment by jessegreenberg** [comment]
Thanks @phet-steele and QA team for diving into this.  In https://github.com/phetsims/resistance-in-a-wire/issues/107, we decided not to add keyboard navigation in phet-io releases. In the next RC keyboard navigation will be removed. I think that this RC can still proceed, without testing keyboard nav features in the wrappers, but @phet-steele let me know if you disagree.

**Comment by phet-steele** [comment]
@jessegreenberg @zepumph done! There is at least one cherry-pick noted above.

**Comment by jessegreenberg** [comment]
Awesome thank you @phet-steele!

**Comment by jessegreenberg** [comment]
Next RC deployed, closing.
