### ISSUE TITLE
QA should test with `?phetioDebug`

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#530]
@jbphet brought a bug to the attention of the phet-io team where an RC had a very blatant assertion error when setting States of Matter for PhET-iO state. This bug was easily triggered by adding `?phetioDebug` to the state wrapper. From this conversation and from looking at the rc template/qa book for PhET-iO testing, it looks like there is no testing with `?phetioDebug` during RC. This is a query parameter that we give to clients while developing wrappers to help them catch bugs early and often, and so I think it is important for it to get some testing. I don't think we need to double the wrapper testing by doing the same amount of work with the query parameter present, but it would be nice to get a couple wrappers and a couple devices doing this during RC. Most bugs caught caused during testing without `?phetioDebug` should also be caught with the query parameter present, so likely they could be used in exchange.

I know that QA is swamped, and PhET-iO testing already causes a lot of increase testing cost. With this in mind, @chrisklus and I recommend adding the following updates to the PhET-iO RC test:

* When testing studio, one browser/device combo should be tested with `?phetioDebug`. This includes launching/previewing customizations.
* When testing state wrapper, on browser/devivce combo should be tested with `?phetioDebug`.

Tagging related parties: @samreid and @ariel-phet 

@KatieWoe does this seem reasonable to you? If so, what is the best way to document these changes? Over to you for comment and documentation.

**Comment by KatieWoe** [comment]
Can we go over what this test does and I would look for in this test before I make these changes? @zepumph

**Comment by zepumph** [comment]
Sure thing, adding the query parameter `?phetioDebug` in a wrapper will tell the wrapper to load an entirely different version of the sim in the frame. Instead of the traditional, built version of the sim we load the `debug` version of the sim (see screenshot below). This `debug` version has assertions enabled, and will catch more bugs. @chrisklus and I, when discussing above, felt like most bugs caught in the normal wrapper (without `?phetioDebug`), would be also caught in the debug version. So testing with/out the query parameter should look the same, it is just an important, client-facing mode of the sim that would be good to get QA time on. I'm happy to answer any more questions, or talk if that is easier.

![image](https://user-images.githubusercontent.com/6856943/90161694-fa493000-dd3f-11ea-903e-a2bae6550b13.png)

**Comment by KatieWoe** [comment]
So testing with this would just replace one of the tests? Or would you want me to test with and without on one of the platforms?

**Comment by KatieWoe** [comment]
Documentation added. Closing

**Comment by zepumph** [comment]
Looks great!
