### ISSUE TITLE
Figure out how to "name blind" QA tester bug report applications and resumes

### ISSUE THREAD

**Issue by muedli** [phetsims/QA#534]
As part of this week's equity discussion, we thought it would be a good idea to "name blind", i.e. remove any identifying information, from QA tester applications. This way we won't let our unconscious biases seep into our hiring decisions.

@ariel-phet suggested having me take out any identifying info including name, place of origin, etc. and then forwarding them to Katie and Oliver for review. How should we go about doing this? Should we set up an email separate from phethelp for this?

**Comment by KatieWoe** [comment]
This suggestion seems ok as a first step. Should we set up a discussion for specifics etc?

**Comment by oliver-phet** [comment]
One quick way I thought of: We could collect "test tasks" via a Google form that is linked to a response spreadsheet. We could import those responses into another sheet that is de-identified. We'll use the de-identified spreadsheet to evaluate candidates (then identify as needed to set up an interview, ask for more information, etc.)

**Comment by muedli** [comment]
As long as we'd be able to keep the test task formatting etc. intact, I think @oliver-phet's suggestion is a good one. (It's nice to be able to see how a potential tester is formatting everything, how thorough they are, etc.)

**Comment by KatieWoe** [comment]
I agree with @muedli. If there is a way to keep that aspect, it might be nice, nut not necessary.

**Comment by oliver-phet** [comment]
We've created a Google form to collect applications and a de-identified linked spreadsheet.
