### ISSUE TITLE
RC Spot Check Forces and Motion Basics 2.3.0-phetiorc.4

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#54]
@kathy-phet @ariel-phet @zepumph @samreid Forces and Motion: Basics 2.3.0-phetiorc.4 is ready for RC testing. There were a few changes from the last RC, but all were small and "cosmetic" in nature for PhET-iO. A full RC is not necessary, but we should spot check the sim on a few platforms and verify that these issues were fixed.

This RC is to support adding Legends of Learning features for Forces and Motion: Basics. But we wanted the improvements in the PhET-iO version as well so new versions are going out for both brands.  If this version passes testing, a PhET brand 2.3 version will go out with the same SHAs.  Here is the link to index.

[Root Directory](https://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-phetiorc.4)

Please verify that the following issues were fixed:
- [x] https://github.com/phetsims/forces-and-motion-basics/issues/248
- [x] https://github.com/phetsims/forces-and-motion-basics/issues/245
- [x] https://github.com/phetsims/forces-and-motion-basics/issues/244
- [x] https://github.com/phetsims/forces-and-motion-basics/issues/242
- [x] https://github.com/phetsims/forces-and-motion-basics/issues/240
- [x] https://github.com/phetsims/forces-and-motion-basics/issues/237

If any new issues are found, please note them in phetsims/forces-and-motion-basics/issues and reference this issue.

@ariel-phet could you please prioritize this issue?  Also assigning to @phet-steele.

**Comment by kathy-phet** [comment]
Sounds great Jesse!

Sent from my iPhone

On Oct 13, 2017, at 7:01 PM, Jesse Greenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


@kathy-phet<https://github.com/kathy-phet> @ariel-phet<https://github.com/ariel-phet> @zepumph<https://github.com/zepumph> @samreid<https://github.com/samreid> Forces and Motion: Basics 2.3.0-phetiorc.4 is ready for RC testing. There were a few changes from the last RC, but all were small and "cosmetic" in nature for PhET-iO. A full RC is not necessary, but we should spot check the sim on a few platforms and verify that these issues were fixed.

This RC is to support adding Legends of Learning features for Forces and Motion: Basics. But we wanted the improvements in the PhET-iO version as well so new versions are going out for both brands. If this version passes testing, a PhET brand 2.3 version will go out with the same SHAs. Here is the link to index.

Root Directory<https://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-phetiorc.4/wrappers/>

Please verify that the following issues were fixed:

  *    phetsims/forces-and-motion-basics#248<https://github.com/phetsims/forces-and-motion-basics/issues/248>
  *    phetsims/forces-and-motion-basics#245<https://github.com/phetsims/forces-and-motion-basics/issues/245>
  *    phetsims/forces-and-motion-basics#244<https://github.com/phetsims/forces-and-motion-basics/issues/244>
  *    phetsims/forces-and-motion-basics#242<https://github.com/phetsims/forces-and-motion-basics/issues/242>
  *    phetsims/forces-and-motion-basics#240<https://github.com/phetsims/forces-and-motion-basics/issues/240>
  *    phetsims/forces-and-motion-basics#237<https://github.com/phetsims/forces-and-motion-basics/issues/237>

If any new issues are found, please note them in phetsims/forces-and-motion-basics/issues and reference this issue.

@ariel-phet<https://github.com/ariel-phet> could you please prioritize this issue? Also assigning to @phet-steele<https://github.com/phet-steele>.

**Comment by phet-steele** [comment]
@jessegreenberg spot check looks good.


> If this version passes testing, a PhET brand 2.3 version will go out with the same SHAs.

Hopefully you meant "...go out [for RC Testing]..."! We still need LoL testing anyway.

**Comment by jessegreenberg** [comment]
> Hopefully you meant "...go out [for RC Testing]..."!

Indeed! RC for 2.3 coming up.

**Comment by jessegreenberg** [comment]
Thanks for the testing @phet-steele!  Closing this issue,  RC for 2.3.0 created in #57
