### ISSUE TITLE
RC Test: Energy Skate Park 1.1.0-rc.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#544]
@ariel-phet, @arouinfar, @KatieWoe energy-skate-park/1.1.0-rc.1 is ready for RC testing. Please document issues in https://github.com/phetsims/energy-skate-park/issues and link to this issue.

This sim also includes the zoom feature, so please test that feature in this sim as part of this RC. A description of testing this feature is in the QA book.

This test is starting with 1.1 because 1.0 was published as a prototype.

Assigning to @ariel-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/energy-skate-park/1.1.0-rc.1/phet/energy-skate-park_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/energy-skate-park/1.1.0-rc.1/phet/energy-skate-park_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/energy-skate-park/1.1.0-rc.1/phet/xhtml/energy-skate-park_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1fI_GO1ubwEChSYnapz8QoNbVrnI-QYXoyLxOznpcbg0/edit#gid=1666247280)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by zepumph** [comment]
This RC was patched as part of an MR over in https://github.com/phetsims/chipper/issues/979 and will have a new RC version published on phet-dev shortly (no steps needed for testing here necessarily).

**Comment by KatieWoe** [comment]
QA is done. Testing on the app will be done during next round.
