### ISSUE TITLE
Maintenance Release: minified intialization script

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#546]
Fixed and tracked in https://github.com/phetsims/chipper/issues/979#issuecomment-686674583. Tagging @jbphet, @jonathanolson, @ariel-phet.

 Here are the only links to test:

Release Candidate links

molecules-and-light 1.5 (https://github.com/phetsims/chipper/issues/979)

- [x] [molecules-and-light 1.5.5-rc.2](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.5-rc.2/phet/molecules-and-light_en_phet.html)

natural-selection 1.1 (https://github.com/phetsims/chipper/issues/979)

- [x] [natural-selection 1.1.1-rc.1](https://phet-dev.colorado.edu/html/natural-selection/1.1.1-rc.1/phet/natural-selection_en_phet.html)

states-of-matter 1.2 (https://github.com/phetsims/chipper/issues/979)

- [x] [states-of-matter 1.2.1-rc.1](https://phet-dev.colorado.edu/html/states-of-matter/1.2.1-rc.1/phet/states-of-matter_en_phet.html)
- [x] [states-of-matter 1.2.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/states-of-matter/1.2.1-rc.1/phet-io/states-of-matter_all_phet-io.html?phetioStandalone)
- [x] [states-of-matter 1.2.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/states-of-matter/1.2.1-rc.1/phet-io/wrappers/studio)

Please play around with each link for a minute or so (or whatever is normal for MRs) I have checked in each version above and see that the bug itself has been fixed, this issue is just a sanity check. These published sims will not be translatable until this is pushed. @ariel-phet please assign and prioritize

**Comment by KatieWoe** [comment]
Checked on a few different platforms. Win 10 Chrome, Firefox, and Mac 10.15 Safari.

**Comment by zepumph** [comment]
Thanks! Closing
