### ISSUE TITLE
PhET-iO Testing for the new iframe size feature

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#548]
From https://github.com/phetsims/studio/issues/167

> It would be nice to test this change in isolation before the next RC or Dev test.  To test, try on 2-3 browsers on at least 2 OSes.  I published https://phet-dev.colorado.edu/html/gravity-and-orbits/1.2.0-dev.15/phet-io/ for this test.  Run the Wrapper Index page of a sim and test that "Launch Template" launches a fullscreen iframe without any trouble. Also test that studio => launch launches a fullscreen iframe without any trouble.  Download the HTML and edit it as prescribed in the comments to make it have a fixed size iframe. 

I walked through this test with @KatieWoe on one platform, and it looked good.  I think it's sufficient to try 2-3 browsers on at least 2 OSes total.

**Comment by KatieWoe** [comment]
Chrome on Win 10 looked good.

**Comment by muedli** [comment]
Looking good on macOS + FF, macOS + Safari, and macOS + Chrome.

**Comment by samreid** [comment]
That sounds great, and sufficiently tested, thanks!  Closing.
