### ISSUE TITLE
iPadOS 14

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/QA#549]
Testing the beta iPadOS 14 and how sims work with it.

**Comment by ariel-phet** [comment]
@KatieWoe I suggest not having this test go too long if nothing is obviously wrong (preferably less than a day)

Definitely good to test:

- pan and zoom (for instance on Molecules and Light published version)
- a recently published sim (like Natural Selection)
- a sim that uses WebGl (like charges and fields)

**Comment by KatieWoe** [comment]
Everything else seems to be alright. I also did a brief check on the app. Closing
