### ISSUE TITLE
changes to how QA is testing data stream wrappers

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#553]
In https://github.com/phetsims/natural-selection/issues/240#issuecomment-698508288:

> From today's PhET-iO meeting, we feel like some changes should be made to how QA is testing data stream wrappers:
> 
> * Please do not test iPad or Chromebook on the Data: colorized or Data: JSON wrappers.
* Please test Data: colorized and Data: JSON very lightly, only confirming that the data stream prints as expected to the console on a couple device/browser combos.
* Please test thoroughly the `data: textarea` wrapper on all devices to make sure that the cross frame messages for data stream support are running correctly. This shouldn't have performance trouble on chromebook or iPad.
> 
> Assigning to @KatieWoe for questions, and to update the QA book as needed.

**Comment by KatieWoe** [comment]
Update made, closing
