### ISSUE TITLE
Charges and Fields Safari 14 patches

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#559]
The Charges and Fields workaround has been applied to two branches:

1.0: https://phet-dev.colorado.edu/html/charges-and-fields/1.0.48-rc.1/charges-and-fields_all.html
1.0-phetio: https://phet-dev.colorado.edu/html/charges-and-fields/1.0.20-rc.3/wrappers/index/

The applied patch has Safari always use the "mobile" WebGL codepath for the voltage display in the sim, instead of ever using the "desktop" version.

@ariel-phet what testing would you recommend for this type of patch?

**Comment by ariel-phet** [comment]
@jonathanolson it would be good to make a QA issue. We should certainly have QA test on iPad, and desktop safari fairly heavily, and then just do a few spot checks on other main platforms.

**Comment by ariel-phet** [comment]
@KatieWoe currently the live version of Charges and Fields is broken on Safari 14.0 so this would be a good spot check to complete in the near future (I think checking on just a few platforms will be fine, first checking on the iPad and do a short regression test to make sure nothing is obviously broken, and the likely Windows Chrome, Latest Mac Safari, and Chromebook)

**Comment by KatieWoe** [comment]
@jonathanolson should zooming be enabled?

**Comment by KatieWoe** [comment]
Instance proxies does not seem to work. There is no sim in the iframe and no options to select. Am I doing something wrong, or is there an issue? @jonathanolson

**Comment by samreid** [comment]
It looks like an incorrect path for the iframe URL.  I estimate it could take 1-2 hours to identify and resolve (if that is the only problem).  Also, I should mention I am not certain that is a good use of time since this is a very stale version of phet-io to begin with.

**Comment by jonathanolson** [comment]
I don't know many details about how to test or look into that. It was listed as a maintained phet-io version (via the website database), perhaps we can use the previous release as a guide (to see if things worked there?)

**Comment by KatieWoe** [comment]
What should I do regarding testing?

**Comment by KatieWoe** [comment]
Tested PhET brand and what little I could on PhET-iO Brand on Mac and iPad Safari. Are we waiting until dev meeting to decide on what to do for phet-io?

**Comment by zepumph** [comment]
@samreid and I made https://github.com/phetsims/perennial/issues/196 for investigating the general issue of phet-dev paths being incorrect for phet-io, chipper 1.0 sims. 

>Are we waiting until dev meeting to decide on what to do for phet-io?

I think we will go ahead with an attempt to fix the build over in https://github.com/phetsims/perennial/issues/196

Unmarking for meetings, for @jonathanolson and @samreid and I to take on.

**Comment by KatieWoe** [comment]
QA is done aside from the phet-io issues.

**Comment by zepumph** [comment]
@KatieWoe, you can test the phet-io instance proxy versions by adding `&launchLocalVersion`, like https://phet-dev.colorado.edu/html/charges-and-fields/1.0.20-phetiorc.4/wrappers/instance-proxies/instance-proxies.html?sim=charges-and-fields&launchLocalVersion (new version since https://github.com/phetsims/perennial/issues/196, or https://phet-dev.colorado.edu/html/charges-and-fields/1.0.20-rc.3/wrappers/instance-proxies/instance-proxies.html?sim=charges-and-fields&launchLocalVersion. Either one should work correctly and the same.

You can now complete this QA.

**Comment by jonathanolson** [comment]
Testing for the phet-io-specific parts would be great, I can then deploy afterward.

**Comment by KatieWoe** [comment]
Tested first link. Making changes works fine and voltage shows up on Mac Safari. Wasn't able to launch. From Slack:
>  I think it is a path problem, and it should work in production.
 
I think this means testing is done.

**Comment by zepumph** [comment]
@jonathanolson please let me know when the phet-io version is published to production and I'll confirm launch still works.

**Comment by jonathanolson** [comment]
phet-io version is published (it gave the link https://phet-io.colorado.edu/sims/charges-and-fields/1.0.20/, but no clue if that's accurate). Let me know how it looks?

**Comment by KatieWoe** [comment]
@jonathanolson that link gives a 404 error

**Comment by zepumph** [comment]
It is chipper 1.0, so the link is https://phet-io.colorado.edu/sims/charges-and-fields/1.0.20-phetio/wrappers/index.

**Comment by zepumph** [comment]
Looks like studio launch is working well there. Thanks @jonathanolson and @KatieWoe! I'm ready to close.

**Comment by KatieWoe** [comment]
Looks good to me too!

**Comment by jonathanolson** [comment]
Thanks!
