### ISSUE TITLE
Dev test: Capacitor Lab: Basics 1.5.0-dev.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#56]
@ariel-phet and @arouinfar, Capacitor Lab: Basics 1.5.0-dev.1 (the release will be 1.5.0 due to 1.4-phetio versions) is ready for general dev testing.

URL: https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-dev.1/capacitor-lab-basics_en.html

Please test the following platforms:

- [x] iPad2
- [x] Mac Safari
- [x] Windows Chrome
- [x] Chromebook

**Comment by ariel-phet** [comment]
@phet-steele also high priority, but #53 comes first

**Comment by phet-steele** [comment]
@jonathanolson we are done. If you feel this is ready for rc (if https://github.com/phetsims/capacitor-lab-basics/issues/197 doesn't become too crazy), go for it.

**Comment by jonathanolson** [comment]
Thanks! Will set up another test when things are verified as looking good.
