### ISSUE TITLE
Updates to PhET-iO testing for QA

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#561]
From today's phet-io meeting, we would like to alter the way that QA tests PhET-iO sims in a variety of ways. I will outline the changes here, and I will leave it up to @KatieWoe to make sure that things end up in the QA book and test matrices as desired. 

1. The following only needed to be tested on one platform for each test. Ideally this platform would rotate so that after N sim tests, we have tested all N platforms (i.e. windows/firefox this test, mac/safari next test). Each of these are divided further into the amount of time the phet-io team thinks they need to be tested, along with the rationale.
	
	* **Short and easy**: these act mostly as a spot check. In general things don't change often here, and so confirming functionality works on once platform is enough
		* Login Wrapper Test
		* Data: Colorized Wrapper Test
		* Data: JSON Wrapper Test
		* Multi - Wrapper Test
		* Wrapper index links/doc (not template)
	
	* **Regular testing**: Test in the same way that you would for the respective test (dev/rc), but you don't need to do it for every platform.
		* State wrapper with `?phetioDebug`
		* Studio with `?phetioDebug`
		* Studio Client requests
		* Wrapper index launching template
		* Diff wrapper

2. The platforms and ways we test Studio is changing a bit:
	* Studio only needs a full test on Chrome. All other browsers (including chromeOS) don't need to be tested.
	* Make sure that for a Studio test, you always conduct the following test 2 times (or more if you feel it appropriate):
		1. Customize the sim
		2. Download the sim to an HTML file
		3. Host that file somewhere locally on a server (see Appendix A)
		4. Test that this customized version of the sim on all supported phet-io devices. (This will be easy enough if the file hosted on a server on the computer you made the customized sim with. Alternatively you could pass that sim version around to all devices, but that is not recommended).

3. Clarification on time spent on certain wrappers
	* In general, the most important things in testing phet-io is to test the features of PhET-iO (coming from the sim). Testing the wrappers is secondary. This differentiation is a bit nuanced. An example would be that testing that state is set correctly on a sim is more important than testing that a button in the state wrapper does what is is supposed to. If this point doesn't make total sense that is ok, it is a bit of a moving target, and can help to think of the wrapper suite (everything but studio) as tools to expose PhET-iO features. Finding problems with the tool is not as important as finding a problem with the PhET-iO feature that its exposing. This is because the features will be used by the whole breadth of learners for a PhET-iO product, whereas the "tool" will only be used by our client to directly understand PhET-iO and create their product.
	* @KatieWoe said that there is a lot of time spent on the record wrapper. In general, the important pieces of the record/playback feature are also implemented in the mirror-inputs wrapper. Mirror inputs is, in general, easier to test because it is in real time, and can be better to track if the playback sim gets into an undesirable state (since it is right there to compare the source to). There should be more testing done on the mirror-inputs wrapper to make sure that record and playback work for all input methods (mouse/touch/keyboard), with all or most components in the sim, etc. The record and playback wrappers should still be tested to make sure that the process of recording to a log, and using the playback wrapper to play the data log back works, but this is more like testing that the wrappers work instead of testing the features.
	* The "launch" feature of studio runs on PhET-iO State, and it is easier to test that PhET-iO feature in the state wrapper. The state wrapper just got a face lift, and you should test this feature substantially. In addition to how you have been testing the wrapper, here are some important ways to test the state feature (via the state wrapper)
	  * Use the "launch" button at the bottom of the screen to set a state onto a fresh copy of the sim (same as studio launch but easier).
	  * Set the rate of state setting to 0, and adjust both sims so that they are in very different states, then press the "Set State Now" button.
	  * Determine the minimum set state "rate" in which the sim's performance becomes unusable. As you test more sims this way, it will be more clear when a setting the state of a sim is potentially a performance problem.

4. We know that sometimes QA gets time crunched, and some testing has to be dropped for a deadline. When this occurs we have a couple a heuristics to guide you in culling tests:
	* Prefer dropping extra platform testing to dropping tests. In general a thorough test on one platform is preferred to less thorough on multiple.
	* Prefer testing PhET-iO features to testing the wrappers.
		* Features:
			* record/playback
			* PhET-iO state 
			* data-stream
			* customization (the logic behind studio controls that change the sim)

5. If we make significant changes to a particular wrapper or feature, we will call that out for separate testing, or additional testing coverage during the next dev or RC test.

Appendix A: Hosting a local server
	We feel like this will greatly increase productivity when it comes to passing around files between devices. Follow step (4) in https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md#checking-out-the-code-and-running-it-in-development-mode. And feel free to reach out to a dev if this doesn't make sense. (KW perhaps we should talk before this ends up in the QA book).

Tagging @ariel-phet @samreid @kathy-phet as members of the discussion this morning.

**Comment by KatieWoe** [comment]
Commit above makes change to QA book. RC template also altered. @zepumph can this be closed?

**Comment by zepumph** [comment]
>RC template also altered.

By what commit? I don't see the changes in https://github.com/phetsims/QA/commits/master/issue-templates/rc-test-template.md.

My impression was that everything above was a change to QA process, yet I only see 1 sentence change in the commit. @KatieWoe I think it would be best if this was captured in a central place rather than a github issue.

**Comment by zepumph** [comment]
Ahh excellent, I found https://docs.google.com/spreadsheets/d/1o5txil6dVHk1BfHA3fT5LIQc19JBSOg0v-BYBQe9A7A/edit#gid=1993524520 and reviewed it.

In general it looks really good, I just have a couple of thoughts.

>Is phet-io.js in lib? Is it minified?

* Could you make this "Is phet-io.js in lib/? Is it minified and not password protected?"

>Then click here for playback

* The playback wrapper deployed with each sim should be used instead of https://phet-io.colorado.edu/metacog/playback/. For example: https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.0-rc.3/phet-io/wrappers/playback/

* Do you think we should add a new column for "studio with ?phetioDebug" (and one for state with ?phetioDebug). This would just have a single block for all devices, signifying that you only need to test it on one device? This may be more clear than hiding it away in the QA book.

* From section (1) above, the diff wrapper only needs one platform. You can combine all the cells in the column

**Other thoughts**

* I don't see a section in the matrix or template about testing client requests on one platform.

* I don't feel like some of the nuance in (3) was captured anywhere. 
  * Mirror inputs: Perhaps we can add something to https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#mirror-inputs-wrapper-test that talks about how this is the same feature as record/playback, but is easier to test accuracy, and should be tested more thoroughly than record/playback. Right now, the description for record/playback is much more extensive.
  * State wrapper: Same as mirror inputs, but about how this is the same feature as studio launch, but easier to test, and should be tested more thoroughly.

* I'm not sure how best to capture (4). Any thoughts? Probably in a more general PhET-iO section of the QA book?

* I tried to document step (5) in the above commits to issue templates. What do you think?

**Comment by KatieWoe** [comment]
Implemented some of the above suggestions. Mostly in the test matrix.

**Comment by zepumph** [comment]
Let me know when this is ready for review.

**Comment by KatieWoe** [comment]
I think it's probably done? I think it can be closed unless there's more you wanted more?

**Comment by zepumph** [comment]
All the changes are looking really good. I glanced through the matrix and saw many updates from the first half of https://github.com/phetsims/QA/issues/561#issuecomment-708052096. I didn't hear back on (4) or (5), but feel like we are at a place of diminishing returns. I'll let @KatieWoe decide what she thinks is important to document for QA.
