### ISSUE TITLE
Update QA doc for new phettest location

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#566]
From https://github.com/phetsims/special-ops/issues/170, phettest now lives on bayes. We should update QA doc accordingly.

**Comment by zepumph** [comment]
@KatieWoe what do you think about the above? Any other thoughts about updating QA process to the new phettest?

**Comment by KatieWoe** [comment]
Quick clarifying question. Will the old version of phettest be available, or is the bayes version replacing the old version?

**Comment by zepumph** [comment]
Eventually we will get rid of the other one. But I'll give notice.

**Comment by KatieWoe** [comment]
I think this can be closed for now. @zepumph, do you agree?
