### ISSUE TITLE
Dev Test: Desktop App

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#569]
The PhET Desktop App is available for testing. It is available [here](https://phet-dev.colorado.edu/weddell/dist/qa/): 

- [MacOS](https://phet-dev.colorado.edu/weddell/dist/qa/phet-mac-app.dmg)
- [Windows](https://phet-dev.colorado.edu/weddell/dist/qa/phet-windows-app.exe)

The desktop app requires a Java JDK to be installed (found [here](https://www.oracle.com/java/technologies/javase-jdk15-downloads.html#license-lightbox)). From this page install, the latest version (Java SE Development Kit 15.0.1) of the Java JDK for your tested platform as described below:
- Windows: Windows x64 Installer
- MacOS: macOS Installer

**General**

QA, please do a dev-test of the app. Please complete a general test to make sure that all sims are launching, resources are in the correct locale, and that all other functions of the app are working properly (menu items, shortcuts, filters, launching the app, installation, etc). Issues can be created in the [Weddell](https://github.com/phetsims/weddell/issues) repo.

**Locale Specific**

This version of the app has been built for multi-locales. These locales can be changed via the drop-down menus near the toolbar at the top of the app's window. The expected behavior for selecting locales is as follows:
1. Click a locale from the drop-down menu
2. App should refresh and the homepage should be translated.
3. Sims should open in the specified locale

Additionally, the app should open in the locale chosen before it was closed. For example, select "Spanish" then close the app. The next time the app is opened, it should be in "Spanish". Other functionality should remain the same.

Please reach out if I can be of any assistance. Assigning to @oliver-phet or @ariel-phet for any added input.

**Comment by brooklynlash** [comment]
Just as a heads-up: looks as if the installer links are switched: if I press "Windows" the .dmg is downloaded and if I press "MacOS" the .exe file is downloaded

**Comment by KatieWoe** [comment]
Fixed it.

**Comment by ariel-phet** [comment]
Nothing to add, it will be good to get a solid shake down!

**Comment by oliver-phet** [comment]
@Denz1994 Collision Lab (Flash) is giving me this dialog: 
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/5090275/98021734-e7378080-1dc1-11eb-8b03-357d16f08453.png">

I don't think this is an issue with the app, but I'm not entirely sure why it is notifying the user of a new version (we've only published a prototype). Note, I don't get a similar dialog for Density (which also has an HTML5 prototype).

Everything else (switching locales, etc.) works seamlessly.

**Comment by KatieWoe** [comment]
QA is done.

**Comment by Denz1994** [comment]
Closing due to opening new dev issue.
