### ISSUE TITLE
RC Test Forces and Motion: Basics  2.3.0-rc.3

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#57]
@ariel-phet @phet-steele, Forces and Motion: Basics 2.3.0-rc.3 is ready for RC testing.

**[Link to sim](https://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-rc.3/forces-and-motion-basics_en.html)**

**[Link to iFrame](https://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-rc.3/forces-and-motion-basics_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1U2-hwtOCMVTnnWaviONSJUNEqseKB-d_1Sc_ttZRILU/edit#gid=1900058392)**

**Issues to Verify**
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.
- [x] phetsims/forces-and-motion-basics#245 (this was verified in #54, but changes should be applied to this branch too)

**Please also verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any new issues are found, please note them in https://github.com/phetsims/forces-and-motion-basics/issues and reference this issue.

@ariel-phet could you please prioritize?

**Comment by phet-steele** [comment]
On hold until #58 is done and both GEE and CLB are published.

**Comment by phet-steele** [comment]
Briefly top priority until GEE is back.

**Comment by phet-steele** [comment]
Off to @jessegreenberg.

**Comment by jessegreenberg** [comment]
RC.4 was made in #77, closing this issue.

Thanks very much @phet-steele and team!
