### ISSUE TITLE
RC-Lite test: Gravity and Orbits 1.3.0-rc.2 with PhET-iO

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#576]
@ariel-phet, @arouinfar, @kathy-phet, @KatieWoe, gravity-and-orbits/1.3.0-rc.2 is ready for RC-lite testing.  This is for a client, and is one of their top priority projects.  Document issues in https://github.com/phetsims/gravity-and-orbits/issues and link to this issue.

Assigning to @ariel-phet for prioritization.

UPDATE: The prior issue https://github.com/phetsims/QA/issues/567 was top-priority, I'll mark this to match until I hear otherwise.

UPDATE: I see there is already another top priority, so I'll mark this as high.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

This is an RC-lite test for the PhET-iO version, which will be delivered to the client once testing has passed.  Prior
testing was completed in https://github.com/phetsims/QA/issues/519

<h3>Issues to Verify</h3>

- [x] [Long strings leave artifacts behind on To Scale Screen](https://github.com/phetsims/gravity-and-orbits/issues/358)
This is not a blocking issue, but we just want to check the status in this version.

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

Links will be provided once the version has been built.  There are still some blocks-publication or blocks-sim-publication
issues that need to be addressed first.

- **[Simulation](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.3.0-rc.2/phet/gravity-and-orbits_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.3.0-rc.2/phet/gravity-and-orbits_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.3.0-rc.2/phet/xhtml/gravity-and-orbits_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1U61MmzaK2YR1MvtvBo1vYZ4zkEpwNroxhbtdhOgNEPs/edit#gid=1267274178)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>PhET-iO RC Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.
- For an update or maintenance release please check the backwards compatibility of the playback wrapper.
[Here's the link to the previous wrapper.](link)
- Load the login wrapper just to make sure it works. Do so by adding this link from the sim deployed root:
  ```
  /wrappers/login/?wrapper=record&validationRule=validateDigits&&numberOfDigits=5&promptText=ENTER_A_5_DIGIT_NUMBER
  ```
  Further instructions in QA Book
- Conduct a recording test to Metacog, further instructions in the QA Book. Do this for iPadOS + Safari and one other random platform.
- Conduct a memory test on the stand alone sim wrapper (rc.1).
- Test one platform combination with `?phetioDebug` on the Studio and State wrapper.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>Issues to Verify</h3>

- [x] [Measuring Tape does not move in State wrapper](https://github.com/phetsims/gravity-and-orbits/issues/362)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.3.0-rc.2/phet-io)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1MiLr45_vxmzBlu88343uG3OV-_Pb7qRBAMRTIZKVPhE/edit#gid=131282679)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Heads up testers, I just noticed that testing matrix needed to be updated. If you've been testing with the old matrix, please add tests to the updated matrix.

**Comment by KatieWoe** [comment]
I'm calling an end to QA here.

**Comment by samreid** [comment]
Thanks, I reviewed the discovered issues and will continue there, closing.

**Comment by samreid** [comment]
@ariel-phet and I discussed on slack and determined this issue should remain open and "ready for next steps" while we determine whether to publish a production version.  There is discussion on this topic in https://github.com/phetsims/special-ops/issues/176.

**Comment by KatieWoe** [comment]
@samreid The QA credits should add Logan Bray, Brooklyn Lash, Devon Quispe, and Kathryn Woessner

**Comment by samreid** [comment]
I updated QA credits in master and in the branch.

**Comment by samreid** [comment]
As determined in https://github.com/phetsims/special-ops/issues/176, @kathy-phet will share the RC with the client and we will move forward with a milestone for publishing the full version of gravity and orbits in https://github.com/phetsims/gravity-and-orbits/milestone/3, closing.
