### ISSUE TITLE
RC Test: waves-intro/1.1.0-rc.3

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#580]
@ariel-phet @emily-phet @kathy-phet @arouinfar @KatieWoe, waves-intro/1.1.0-rc.3 is ready for RC testing. Document issues in https://github.com/phetsims/wave-interference/issues and link to this
issue.  

Please reach out to @samreid when ready for testing and I'll publish a fresh version.

Regarding priority @emily-phet said:

> this sim does not have a hard deadline for publication. Please weave it into the QA queue as it makes sense to you, given the other priorities.

Dev testing completed in https://github.com/phetsims/QA/issues/511

Assigning to @ariel-phet for prioritization.

See also https://github.com/phetsims/wave-interference/issues/509

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>Issues to Verify</h3>

https://github.com/phetsims/wave-interference/issues/450

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

Please reach out to @samreid when ready for testing and I'll publish a fresh version.

- **[Simulation](https://phet-dev.colorado.edu/html/waves-intro/1.1.0-rc.3/phet/waves-intro_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/waves-intro/1.1.0-rc.3/phet/waves-intro_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/waves-intro/1.1.0-rc.3/phet/xhtml/waves-intro_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1C-tenj9bMA_fVjWR56KcQCNT44xNlVxjf4I0xWtTCl4/edit#gid=2074960390)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.

<h3>Focus and Special Instructions</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself (but not with a screen reader).

<h3>Issues to Verify</h3>

None

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

Please reach out to @samreid when ready for testing and I'll publish a fresh version.

- **[Simulation](https://phet-dev.colorado.edu/html/waves-intro/1.1.0-rc.3/phet/waves-intro_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1C-tenj9bMA_fVjWR56KcQCNT44xNlVxjf4I0xWtTCl4/edit#gid=2074960390)**

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<h3>Final Requests</h3>

- [ ] If this sim is in [this list](https://github.com/phetsims/perennial/blob/master/data/accessibility), make an
issue in [website](https://github.com/phetsims/website) to ask if PhET research page links need updating. Please assign
to @terracoda and @emily-phet.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
@samreid since this is being added to the pipeline, please add the correct sim links, issues, etc to the rc test issue.

**Comment by samreid** [comment]
* There are no phet-brand blocks-publication issues
* CT is clear for Waves Intro
* There are no open milestone issues
* There are no sim-specific issues (aside from ready-for-qa issues or deferred/paused issues)

I'll publish an RC.

**Comment by ariel-phet** [comment]
Moving to current top priority

**Comment by KatieWoe** [comment]
Memory test looks good

**Comment by KatieWoe** [comment]
Sim crashed and reloaded on iPadOS 14.3 Safari. Sim had been running for several minutes at least. Was on Sound screen switching to particle view. @samreid let me know if you want a full issue for this.

**Comment by samreid** [comment]
Yes, please.  Even if we don't address it, it would be good to know more, like:
* Which hardware version
* Does it happen on the published version
* Can the problem be easily reproduced?

**Comment by KatieWoe** [comment]
Closing due to https://github.com/phetsims/QA/issues/603
