### ISSUE TITLE
Dev Test 2: PhET Desktop App

### ISSUE THREAD

**Issue by Denz1994** [phetsims/QA#583]
The PhET Desktop App is available for testing once again. It is available [here](https://phet-dev.colorado.edu/weddell/dist/latest/2020-11-9/):

- [MacOS](https://phet-dev.colorado.edu/weddell/dist/latest/2020-11-9/phet-mac-app.dmg)
- [Windows](https://phet-dev.colorado.edu/weddell/dist/latest/2020-11-9/phet-windows-app.exe)

The desktop app requires Java JDK SE 8 to be installed ([found here](https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html)). From this page install,  JDK for your tested platform as described below:

Windows: Windows x64 Installer
MacOS: macOS Installer

**General**

This is a second round of testing with flash content (sims, plugin, etc.) stripped out. This test is focused on verifying previously opened issues (detailed below) along with making sure java sims are working with the recommended JDK SE 8.

**Issues for Verification:**
- [Changing locale in sim changes menu locale, not sim](https://github.com/phetsims/weddell/issues/52)
- [Zoom keyboard controls are inconsistent between browsers, sims, and app](https://github.com/phetsims/weddell/issues/51)
- [Greenhouse Effect simulation doesn't seem to be displaying properly](https://github.com/phetsims/weddell/issues/47)
- [Gene Machine: The Lac Operon" does not launch on Mac app version](https://github.com/phetsims/weddell/issues/46)

Locale Specific:

This version includes a Spanish locale but no specific testing is needed outside of what may come from the issues above.

Please reach out if I can be of any assistance. Assigning to @ariel-phet for prioritization.

**Comment by Denz1994** [comment]
Moving into active tests queue as noted by @ariel-phet. I'm not sure how this priority matches up to other tests.

**Comment by KatieWoe** [comment]
- [ ] MacOS 11
- [ ] Win 10

**Comment by KatieWoe** [comment]
Is there no way to see flash sims in this version? I thought there was in version 1 but I don't see it here. Or am I imagining that?

**Comment by KatieWoe** [comment]
Am I right in thinking the ESP shouldn't be there? Since this was made before it was published.

**Comment by Denz1994** [comment]
>  Is there no way to see flash sims in this version? I thought there was in version 1 but I don't see it here. Or am I imagining that?

This is a Java/Html5 only version so flash content should not be included.

> Am I right in thinking the ESP shouldn't be there? Since this was made before it was published.

That is correct. Running `grunt get-assets` will update the latest sims along with additional translations. However, that has to be done before the app is built.

**Comment by KatieWoe** [comment]
QA is done
