### ISSUE TITLE
Dev Test: Circuit Construction Kit: DC 1.2.0-dev.10

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#587]
@ariel-phet, @arouinfar, @KatieWoe circuit-construction-kit-dc/1.2.0-dev.10 is ready for dev testing. We would like this
dev version to be published on the main site by Jan 30, 2021. Also, keep in mind that this is a complex "playground" sim
that will take longer to test, and bugs found will take longer to correct or may require more dev tests than usual. 
Also, testing this is a prelude to the AC version which is coming up starting Feb 1, 2021. Document issues in 
https://github.com/phetsims/circuit-construction-kit-common/issues and link to this issue.

There is no phet-io or a11y in this version, but please test that you can use the delete key to delete a selected 
circuit element.

The main new features in this version are listed in https://github.com/phetsims/circuit-construction-kit-common/issues?q=is%3Aissue+milestone%3A%22DC+w%2F+realistic+bulb+%2B+Dog+sound+effects%22+

* Dog barks when voltage threshold is exceeded
* There is a non-ohmic realistic light bulb

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers (IE dropped)
- [x] Latest Chrome OS, Chrome

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.0-dev.10/phet/circuit-construction-kit-dc_all_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](link).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by samreid** [comment]
On slack, @ariel-phet said it's a good time to create a dev version, and that this test can now go into QA.

**Comment by samreid** [comment]
@arouinfar and I worked on fine tuning some parts, then published https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.0-dev.10/phet/circuit-construction-kit-dc_en_phet.html.  I'll update the links above.  Also, @arouinfar reminded me that "virtual-lab" should be published at the same time.  "virtual-lab" only requires a quick spot check--it is just the lab screen with a missing non-contact ammeter.  I published a version here: https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.2.0-dev.1/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html

**Comment by KatieWoe** [comment]
Memory test:
<img width="426" alt="cckmemtest" src="https://user-images.githubusercontent.com/41024075/103811043-80c91b80-5019-11eb-8cdd-7481cd4cc707.png">

**Comment by KatieWoe** [comment]
iPad testing was cut a bit short due to https://github.com/phetsims/circuit-construction-kit-common/issues/651 making testing difficult.

**Comment by KatieWoe** [comment]
Taking a screenshot seemed to take awhile on ChromeOS

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
> iPad testing was cut a bit short due to phetsims/circuit-construction-kit-common#651 making testing difficult.

Should we improve iPad testing coverage by launching with ?screens=1 then again with ?screens=2 in order to circumvent this problem?

**Comment by KatieWoe** [comment]
I'm not too worried, as I wasn't seeing anything else. I didn't spend as much time on it as on the other platforms, but I'm not overly worried that we missed anything. If you want extra testing we can do that, but I'm not worried.

**Comment by samreid** [comment]
No worries, I don't think additional iPad testing is needed. Leaving self-assigned to wrap up outstanding issues and prepare RC1

**Comment by samreid** [comment]
Open issues are tracked elsewhere, and we aren't quite ready for next test, closing.
