### ISSUE TITLE
Dev Test: Virtual Workshop

### ISSUE THREAD

**Issue by chrisklus** [phetsims/QA#589]
@amanda-phet, @kathy-phet, @ariel-phet, @mattpen, @KatieWoe the Virtual Workshop is ready for dev testing. This will be shared with a client on 12/30. Please document issues in https://github.com/phetsims/website-meteor/issues and link to this issue.

Assigning @ariel-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Try to include browser version numbers

<h3>Focus and Special Instructions</h3>

Please make sure all links work as expected, the page navigation works appropriately in both desktop and mobile view (the column on the left side only, not the top nav bar), and that the responsive layout handles the content without looking buggy. Sometimes the animations can be slow to respond as the page is loading, so please look out for performance issues too. 

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari
- [x] Latest iOS, Safari
- [x] Windows 10, all browsers (IE dropped)
- [x] Latest Chrome OS, Chrome

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[Virtual Workshop](https://ox-dev.colorado.edu/en/teaching-resources/virtual-workshop/math)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by amanda-phet** [comment]
Since the QA tests in progress is up to 4, it might not be possible to get to this before the end of 2020. 

@ariel-phet suggested that some of us bang on the page for a bit so that we can feel ok publishing it before the grant deadline, but do a more comprehensive QA test once they finish up some other in-progress testing.

**Comment by ariel-phet** [comment]
Speaking with @kathy-phet the plan will be to do a lighter test on this page, and get it published on the website. When there is more space for QA we will do a more thorough test before announcing on social media and such.

@oliver-phet @amanda-phet @DianaTavares please test drive the page for something around 30 minutes of testing, I will do the same on Windows (and maybe my phone)

@phet-steele could you also take a test drive (please limit your test to no more than 1 hour)

**Comment by ariel-phet** [comment]
@chrisklus testing for this initial round is complete.

I suggest triaging with @amanda-phet for the first publication (where we will make the workshop live on our site, but not yet advertise to the public).

**Comment by amanda-phet** [comment]
@ariel-phet did you notice no issues on windows? I know @chrisklus and @kathy-phet discussed a severe issue that came up, but I don't see an issue about it (I'm sure @chrisklus can make it, but I wondered if you were involved in the discussion at all).

**Comment by chrisklus** [comment]
All issues that came from this dev test specific to the virtual workshop have been completed. I'll open a new QA issue when ready.
