### ISSUE TITLE
Rosetta Dev Test for checkForValidSession-rewrite

### ISSUE THREAD

**Issue by muedli** [phetsims/QA#598]
@KatieWoe, please only have QA do this if there isn't anything else to do or if someone is bored with sim testing.

### **Don't use the production website!**

1. Head over to https://ox-dev.colorado.edu/translate.
2. Try logging in with all different kinds of accounts. Please try your personal PhET website account and the QA accounts in the credentials sheet. (You should only be able to log in if you're a PhET team member or a trusted translator.)
3. Make sure you don't see a 503 status code or any buggy behavior with logging in like the page reloading suddenly.
4. Dev test the translation utility. Just mess around with it and see what bugs you can find. (Your translations won't appear on Ox-Dev. I have that feature disabled.)
5. If anyone does any testing, please write what time you did your testing in a comment.

Thanks!

**Comment by KatieWoe** [comment]
At 4:40 pm on 1/20/2021. Tested a bit on Win 10 Chrome. Upon logging in, two buttons are cut off and unreadable.
<img width="484" alt="whatarethesebuttons" src="https://user-images.githubusercontent.com/41024075/105254458-e56a9700-5b3e-11eb-8f91-03228c790f23.png">

**Comment by muedli** [comment]
I'm fairly confident we're not seeing any issues from the rewrite. Closing.
