### ISSUE TITLE
RC Test: Forces and Motion Basics 2.3.0-phetiorc.1

### ISSUE THREAD

**Issue by phet-steele** [phetsims/QA#6]
@samreid @jessegreenberg  so they know this is in the queue.

This RC is from the same shas as https://github.com/phetsims/tasks/issues/868, so it should be done after testing the phet features. Here is the link to index.

[Root Directory](http://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-phetiorc.1/)

[Testing Matrix](https://docs.google.com/spreadsheets/d/1u6QGleGnexfDMvASBiGq8daSHfcTge6fRvqDoLIzoJw/edit#gid=2)

If any new issues are found, please note them in https://github.com/phetsims/forces-and-motion-basics/issues/227 and reference this issue.  

Parent issue for the design changes and implementation: https://github.com/phetsims/forces-and-motion-basics/issues/220

Here is the list of all the changes that have been added 

>- All changes are in the "Net Force" screen
>- NetForceScreenView includes two new ```CartStopperNodes``` placed at a location which will stop movement of the cart.
>- The cart can move about twice as far along the screen since the stoppers are placed farther than the previous version allowed the cart to move.
>- The pullers stand up when the game is over
>- The speedometer was added to the center of the cart, showing speed of the moving cart
>- A "Speed" checkbox was added to the control panel, which toggles visibility of a speedometer

**Comment by jonathanolson** [comment]
It looks like this RC is using SHAs that don't include all of the necessary patches for https://github.com/phetsims/scenery-phet/issues/312, specifically it references https://github.com/phetsims/scenery-phet/commit/12053009b222af945f6a2268868ada9ad8fa3ef8 in the dependencies.json, which is missing the fix https://github.com/phetsims/scenery-phet/commit/727d5bd7ac8d93a1c6e8b78b27c9fb6a8a4e783d.

@samreid and @jessegreenberg, can this be cherry-picked to a "forces-and-motion-basics-2.3-phetio" branch in scenery-phet, and then have an RC with that fix included?

@phet-steele can you screen other RCs to make sure that they include that commit?

Also, can someone check to see if the following email was received (I sent it out, but saw no replies):
![maintenance-email](https://user-images.githubusercontent.com/480878/27585252-a915e038-5af8-11e7-9596-fac6b2a97685.PNG)

**Comment by jessegreenberg** [comment]
> can this be cherry-picked to a "forces-and-motion-basics-2.3-phetio" branch in scenery-phet, and then have an RC with that fix included?

It could, but cherry picking to a new branch might not be necessary.  Could we just update the scenery-phet SHA in forces-and-motion-basics ```2.3-phetio``` to https://github.com/phetsims/scenery-phet/commit/727d5bd7ac8d93a1c6e8b78b27c9fb6a8a4e783d?

@jonathanolson, Yes, I received the email Fri, Jun 23, 2017.

**Comment by jessegreenberg** [comment]
I am going to give this a shot, but might ask for some help if I run into trouble.  @phet-steele please halt testing for this issue due to the above comments.

**Comment by jonathanolson** [comment]
Yes, could update the SHA directly to that, as it's the very next commit.

**Comment by jessegreenberg** [comment]
A new RC with the update to scenery-phet has been made in #12, closing this issue.

**Comment by jessegreenberg** [comment]
Actually, @jonathanolson had a request for @phet-steele as part of this issue, leaving open.

> @phet-steele can you screen other RCs to make sure that they include that commit?

**Comment by phet-steele** [comment]
> @phet-steele can you screen other RCs to make sure that they include that commit?

@jonathanolson I checked #11, #12, #13, and #14 and they have the fix.
