### ISSUE TITLE
RC test Projectile Motion 1.0.2-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#60]
A maintenance release has been done for projectile motion, and the changes are significant enough that a basic RC test should be performed.

link: https://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.2-rc.1/projectile-motion_en.html

Issues that should be verified:

- [x] https://github.com/phetsims/projectile-motion/issues/152
- [x]  https://github.com/phetsims/projectile-motion/issues/155
- [x]  https://github.com/phetsims/projectile-motion/issues/158
- [x]  https://github.com/phetsims/projectile-motion/issues/159 (nothing was actually changed for this one, but the sim should be checked in the LoL environment to make sure that it doesn't have the problem described in the related issue, see https://github.com/phetsims/joist/issues/450).
- [x]  https://github.com/phetsims/joist/issues/449

**Comment by jbphet** [comment]
Assigned to @ariel-phet to prioritize.

**Comment by jbphet** [comment]
One other comment - since a change was made to the rendering of the trajectory, the sim should be retested on iPad 2 to verify that there wasn't a significant performance decrease.

**Comment by phet-steele** [comment]
@jbphet this is good to go after addressing https://github.com/phetsims/projectile-motion/issues/152#issuecomment-341166508. Please comment when this is published, too.
