### ISSUE TITLE
Create new desktop app testing methods

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/qa#602]
Since the installer builder is now going to be the desktop app, with many major changes. This means that we need to methods and procedures to doing these tests.
Things that may/may not be needed:
- Test template, as tests will likely be less frequent and possibly on request
- Alterations/rewrite of QA book section.

New/Changed Aspects:
- How many sims/what sims should be tested
- What non sim aspects should be tested (locale, zooming, etc.)
- Should old versions be kept
- How often should routine tests be done (likely depends in part on how often builds happen)
- How many/what platforms should be done
- How will these builds be accessed to test

**Comment by muedli** [comment]
@KatieWoe, I recently installed Ubuntu (the most common Linux distribution) on my Linux laptop. If we ever need non-VM Linux testing for the Desktop app, I can do it.

**Comment by KatieWoe** [comment]
Great! At the moment, if I recall correctly, they may be having trouble getting a Linux distribution made, so no need at the moment.

**Comment by KatieWoe** [comment]
Most things here have been worked out. A test template will be made for https://github.com/phetsims/qa/issues/1143
