### ISSUE TITLE
RC Spot Check Test: waves-intro/1.1.0-rc.4

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#603]
I haven't made a spot test issue recently, so I'll endeavor to be succinct.  This issue is the same as https://github.com/phetsims/QA/issues/580 except we have addressed the following issues which require spot testing:

I cherry picked the fixes for
- [x] https://github.com/phetsims/wave-interference/issues/510
- [x] https://github.com/phetsims/wave-interference/issues/516
- [x] https://github.com/phetsims/wave-interference/issues/513

I published https://phet-dev.colorado.edu/html/waves-intro/1.1.0-rc.4/phet/waves-intro_all_phet.html for testing and we can move forward with it unless we determine https://github.com/phetsims/wave-interference/issues/512 is blocking.

@KatieWoe should I use the full template for this?  Do you need any additional information?

**Comment by KatieWoe** [comment]
@samreid this should be enough.

**Comment by KatieWoe** [comment]
- [ ] Win 10 Chrome
- [ ] Win 10 Firefox
- [ ] Mac 11 Safari
- [ ] iPadOS Safari
- [ ] ChromeOS

**Comment by jessegreenberg** [comment]
@samreid @KatieWoe wavesi-intro 1.1 scenery SHAs received a patch for phetsims/phet-android-app#155.

If possible, you may wish to verify this sim works well in the PhET Android app as part of this test.

**Comment by liam-mulhall** [comment]
https://github.com/phetsims/wave-interference/issues/513 looks to be fixed. https://github.com/phetsims/wave-interference/issues/516 looks to be fixed. https://github.com/phetsims/wave-interference/issues/510 looks to be fixed. All on macOS 11.2 + Safari 14.0.3.

**Comment by brooklynlash** [comment]
Issues [#513](https://github.com/phetsims/wave-interference/issues/513), [#516](https://github.com/phetsims/wave-interference/issues/516), [#510](https://github.com/phetsims/wave-interference/issues/510) all seem to be fixed on Win10 Chrome and Firefox

**Comment by kathy-phet** [comment]
@KatieWoe - Can you review to see if this spot-check has had enough testing to be called done. Looks like issues have been checked on a few platforms. Thanks!

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
It seems like all issues were resolved and no new issues discovered during RC.4.  Therefore, I'll publish the simulation, tracking that work in https://github.com/phetsims/wave-interference/issues/509
