### ISSUE TITLE
RC Test: Circuit Construction Kit: DC & DC "Virtual Lab" 1.2.0-rc.1

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#605]
@arouinfar @kathy-phet @KatieWoe, circuit-construction-kit-dc/1.2.0-rc.1 and circuit-construction-kit-dc-virtual-lab/1.2.0-rc.1 are ready for RC testing.

@kathy-phet said:

> Teachers are head-over-heals for this non-ohmic bulb and if we get it out soon, it would be used immediately. So this is a priority and I'd like to see it move to rc quickly if possible.
> [...] This is higher priority than GAO.

Document issues in https://github.com/phetsims/circuit-construction-kit-common/issues and link to this
issue.

Prior dev testing completed in https://github.com/phetsims/QA/issues/587
The publication issue is https://github.com/phetsims/circuit-construction-kit-common/issues/616

Assigning to @kathy-phet or @KatieWoe for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>Issues to Verify</h3>

- [x] [Switching screens makes interacting with carousel difficult/impossible](https://github.com/phetsims/circuit-construction-kit-common/issues/651)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

CCK DC
- **[Simulation](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.0-rc.1/phet/circuit-construction-kit-dc_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.0-rc.1/phet/circuit-construction-kit-dc_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.0-rc.1/phet/xhtml/circuit-construction-kit-dc_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1r-sCXtSDX_AL4XS0toiAjj0pY1b8CIF7XmigrtSDkvY/edit#gid=454021965)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

CCK DC Virtual Lab (just needs a spot check, since it is 99% same as CCK DC)
- **[Simulation](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.2.0-rc.1/phet/circuit-construction-kit-dc-virtual-lab_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.2.0-rc.1/phet/circuit-construction-kit-dc-virtual-lab_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.2.0-rc.1/phet/xhtml/circuit-construction-kit-dc-virtual-lab_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1r-sCXtSDX_AL4XS0toiAjj0pY1b8CIF7XmigrtSDkvY/edit#gid=454021965)**
- **[Legends of Learning Harness](https://developers.legendsoflearning.com/public-harness/index.html?startPayload=%7B%22languageCode%22%3A%22en%22%7D)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the a11y feature doesn't negatively affect the sim in any way.
- You should be able to use the delete key to delete a selected circuit element
- Keyboard navigation is not supported
- Screen readers are not supported

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<h3>Final Requests</h3>

- [ ] If this sim is in [this list](https://github.com/phetsims/perennial/blob/master/data/accessibility), make an
issue in [website](https://github.com/phetsims/website) to ask if PhET research page links need updating. Please assign
to @terracoda and @emily-phet.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by samreid** [comment]
I set priority to "high" and moved it above "Gravity and Orbits" in the Project Board, please adjust as necessary.

**Comment by samreid** [comment]
@jessegreenberg said there is a joist bug that affects the screen.  We would likely invalidate this RC and take new SHAs once that's corrected.

**Comment by jessegreenberg** [comment]
Sorry @samreid, the regression identified in https://github.com/phetsims/joist/issues/658#issuecomment-772811567 made it to this RC. This reverting commit in joist should be cherry-picked into the joist code for this RC. https://github.com/phetsims/joist/commit/d0be22a46c325481ea2cb3bca6bb5d3c02f1a704

**Comment by samreid** [comment]
> We would likely invalidate this RC and take new SHAs once that's corrected.

@KatieWoe if you have a chance to start testing before I publish new versions, I think that's OK.  Let's just consider https://github.com/phetsims/joist/commit/d0be22a46c325481ea2cb3bca6bb5d3c02f1a704 as something to be cherry-picked before publication.

**Comment by KatieWoe** [comment]
Noting that this sim should be added to the LoL spreadsheet when it is ready.

**Comment by arouinfar** [comment]
These sims have already been delivered to LoL. Since the client uses the "latest" version of the sim, they won't need to manually update anything. The changes are not significant enough to warrant new icons/descriptions.

**Comment by KatieWoe** [comment]
QA is done.

**Comment by jessegreenberg** [comment]
@samreid @KatieWoe CCK DC and CCK DC Virtual Lab 1.2 scenery SHAs received a patch for phetsims/phet-android-app#155.

If possible, you may wish to verify this sim works well in the PhET Android app as part of this test or the next one if there is one.

**Comment by samreid** [comment]
Thanks, I reviewed the opened issues and will continue there.  Nice discoveries and thanks!
