### ISSUE TITLE
Maintenance Release: Removing references to window.speechSynthesis in Android 

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#608]
The issue is identified in https://github.com/phetsims/phet-android-app/issues/155 and fixing commits are referenced there. The bug was that sims were not able to run in the PhET android app because they were trying to use a window object that is unavailable on that platform.  MR process identified these as being the only sims (outside of existing RC's) that had this bug:

**Release Candidate links**

faradays-law 1.4 (https://github.com/phetsims/phet-android-app/issues/155)
- [ ] [faradays-law 1.4.1-rc.1](https://phet-dev.colorado.edu/html/faradays-law/1.4.1-rc.1/phet/faradays-law_en_phet.html)

number-line-operations 1.0 (https://github.com/phetsims/phet-android-app/issues/155)
- [ ] [number-line-operations 1.0.1-rc.1](https://phet-dev.colorado.edu/html/number-line-operations/1.0.1-rc.1/phet/number-line-operations_en_phet.html)

Please play around with each sim for a few minutes to make sure all is well. Then if possible please make sure that the sim is running in the PhET Android app. 

Assigning to @KatieWoe and @kathy-phet to prioritize.

**Comment by KatieWoe** [comment]
Maintenance checks done on non-android platforms today. Hopefully testing for non-published sims on the android app will be set up tomorrow, so those checks can be done.

**Comment by mattpen** [comment]
Here is the debug version of the Android App: https://play.google.com/apps/test/RQWzILOtqlk/ahAIsfLry2xmGH3JMFzPv3YRwflGr8L2yW8suxJj_srKJ2d80l4S4R0x-d4FTmsSVS07xQyf5V0XuR3os0nA9PGEoc

To install this version, click that link on an Android device.  That will take you to the play store, but it will say you need to enable instant app sharing in the Play Store settings.  As described in [Google's documentation](https://support.google.com/googleplay/android-developer/answer/9844679?visit_id=637493561223338995-1106083195&rd=1), to access this setting you have to tap "Play Store Version" 7 times.  You might need to exit the Play Store settings and reopen them after this step in order to see the Instant App setting.

**Comment by KatieWoe** [comment]
Things seemed ok on the Android tablet and the sims opened alright. But I noticed that the keyboard nav on Faraday's Law didn't work properly on the ChromeOS device. Tabbing worked alright, but any other keyboard command, such as space to pick up the magnet, or the arrow keys to switch number of loops, did not work.

**Comment by zepumph** [comment]
This is not in my wheel house.

**Comment by KatieWoe** [comment]
Sorry, mis-clicked

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe. Can you please try on the published version on ChromeOS? It would be good to find out if something about my change broke the sim or something else in this version is broken.

https://phet.colorado.edu/sims/html/faradays-law/latest/faradays-law_en.html

**Comment by KatieWoe** [comment]
The problem is the published version won't load on the app.

**Comment by jessegreenberg** [comment]
@KatieWoe and I met to discuss the problem. What seems to be happening is that keyboard interactions are sometimes going to the app wrapper rather than the sim.  We were wondering if the test harness in https://github.com/phetsims/QA/issues/608#issuecomment-782266620 could be interferring with keyboard input in some way, @mattpen does that seem possible? 

@KatieWoe said that the problem was not happening in the published version of john-travoltage. So it is either a new issue in PhET code or something related to the app, but it seems pretty unlikely that changes for this issue would have caused this problem.

**Comment by jessegreenberg** [comment]
I think I am going to go ahead and deploy these two to production, as the issue has been verified as fixed and is unlikely to be related to what @KatieWoe reported above.  If the issue is still in the published sim we will create a new issue to investigate.

**Comment by jessegreenberg** [comment]
Production links were deployed, I quickly checked each and they look OK.
- [faradays-law 1.4.1](https://phet.colorado.edu/sims/html/faradays-law/1.4.1/faradays-law_en.html)
- [number-line-operations 1.0.1](https://phet.colorado.edu/sims/html/number-line-operations/1.0.1/number-line-operations_en.html)

@KatieWoe would you mind trying keyboard navigation in this version of faradays-law and seeing if the problem is still there?

**Comment by KatieWoe** [comment]
I think I need to wait for these versions to go to the app. I'll check on this tomorrow

**Comment by KatieWoe** [comment]
I am still seeing this issue in the app. I explored a bit further, and keyboard nav seems to work in chrome on the ChromeOS device. I also tested a few more sims, and this may be a bit more general. I tried Gravity Force Lab and saw that I wasn't able to use space to pick up the ruler.

**Comment by mattpen** [comment]
> What seems to be happening is that keyboard interactions are sometimes going to the app wrapper rather than the sim. We were wondering if the test harness in #608 (comment) could be interfering with keyboard input in some way, @mattpen does that seem possible?

It's possible that the app could be intercepting the keyboard input.  The "test harness" is just a webview in the app that points at phet-dev, and has the same configuration as the webview that is used to play sim files directly (just over file protocol instead of http). @jessegreenberg - do you have an android device for testing sims?

**Comment by jessegreenberg** [comment]
@mattpen and I talked over slack and then made https://github.com/phetsims/phet-android-app/issues/156. It looks like there may be a few issues related to alternative input to work on. But they are not related to this fix, so this issue is done. Thanks for the checks @KatieWoe and others.
