### ISSUE TITLE
RC Test: Circuit Construction Kit: DC & DC "Virtual Lab" 1.2.0-rc.2

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#610]
RC1 completed in https://github.com/phetsims/QA/issues/605.  The issues to be confirmed are listed as "ready for qa" in https://github.com/phetsims/circuit-construction-kit-common/milestone/1, I will list them below as a record.  When an issue has been confirmed, it can be closed.  When all issues are closed, the sim is ready for production.

The deploy links are:
https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.0-rc.2/phet/circuit-construction-kit-dc_en_phet.html
https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.2.0-rc.2/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html

I placed this directly in "Active Tests" since it had a high priority in RC1, and the Active Tests (max 5) only had 4 things in it at the moment.  Priority should be assigned by @kathy-phet and/or @KatieWoe, but I think this will be a very quick spot check.

**Comment by samreid** [comment]
I listed the issues above.  I briefly spot checked each one except for Android https://github.com/phetsims/circuit-construction-kit-common/issues/670 and I only looked at one of the screenshots in https://github.com/phetsims/circuit-construction-kit-common/issues/665

**Comment by KatieWoe** [comment]
Issues:
- [ ] https://github.com/phetsims/circuit-construction-kit-common/issues/665
- [ ] https://github.com/phetsims/circuit-construction-kit-common/issues/658
- [ ] https://github.com/phetsims/circuit-construction-kit-common/issues/660
- [ ] https://github.com/phetsims/circuit-construction-kit-common/issues/662
- [ ] https://github.com/phetsims/circuit-construction-kit-common/issues/663
- [ ] https://github.com/phetsims/circuit-construction-kit-common/issues/664
- [ ] https://github.com/phetsims/circuit-construction-kit-common/issues/668
- [ ] https://github.com/phetsims/circuit-construction-kit-common/issues/669
- [ ] https://github.com/phetsims/circuit-construction-kit-common/issues/670

**Comment by KatieWoe** [comment]
Platforms:
- [ ] Win 10 Chrome (Time = )
- [ ] Win 10 Firefox (Time = )
- [ ] MacOS 11 Safari (Time = )
- [ ] iPadOS 14 Safari (Time = )
- [ ] ChromeOS (Time = )

**Comment by samreid** [comment]
I think it could be sufficient to test each of the issues one on platform each (as long as you test on a platform that exhibited the problem in RC.1).

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
@arouinfar can you please review the issues and let me know if they should block publication?

**Comment by KatieWoe** [comment]
BTW checked RC on android app on tablet, and it seems to work there.

**Comment by arouinfar** [comment]
The only potentially blocking issue is https://github.com/phetsims/circuit-construction-kit-common/issues/673, but I can't make a call without being able to judge the severity of the issue.

**Comment by samreid** [comment]
We determined that https://github.com/phetsims/circuit-construction-kit-common/issues/673 is non-blocking, so I'll close this issue and work towards publishing a production version.

**Comment by samreid** [comment]
Perhaps I'll use this issue for the publication steps before moving it to the "published" column.

**Comment by samreid** [comment]
I asked @KatieWoe on slack if the QA credits are up-to-date.

**Comment by samreid** [comment]
@KatieWoe reported: 

> add Brooklyn Lash, Megan Lai, Matthew Moore, and Devon Quispe

**Comment by samreid** [comment]
> Deployed: https://phet.colorado.edu/sims/html/circuit-construction-kit-dc/latest/circuit-construction-kit-dc_en.html
Please wait for the build-server to complete the deployment, and then test!
After testing, let the simulation lead know it has been deployed, so they can edit metadata on the website

**Comment by samreid** [comment]
I published the 1.2 versions of the sims.  @arouinfar do we need to update metadata on the website?  

@oliver-phet and @arouinfar discussed that we may need to reach out to clients or people that have written in to phethelp.  Please feel free to open a separate issue as appropriate.

**Comment by arouinfar** [comment]
@samreid I've updated the Teacher Tips and website metadata. Announcement email will be tracked in https://github.com/phetsims/tasks/issues/1078, closing.
