### ISSUE TITLE
Procure an Apple M1 test device for QA.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#611]
From 2/18/2021 dev meeting:

Apple is switching from Intel to ARM processors for Macs.  The M1 is their first ARM processor, introduced in November 2020 for the Mac Mini and MacBook Air, and now available for the MacBook Pro.   

@kathy-phet would like to proceed with procuring an M1 test device for QA.  @samreid noted that the M1 MacBook Air starts at $899 without AppleCare.

UPDATE by @samreid: Changed to @kathy-phet

**Comment by mattpen** [comment]
I have an M1 device as my main development machine and can do spot checks if needed.

**Comment by oliver-phet** [comment]
Sorry I missed the discussion in dev meeting. I'm wondering if it first makes sense to have @mattpen do a few sim spot checks to see if there are any noticeable differences for our sims? According to Google Analytics we have had exactly 0 non-Intel and PPC Mac sessions on our website since Nov 1, 2020.

@pixelzoom was the decision in dev meeting to add this as a new platform on all future testing matrices or just to do a check of existing sims on M1 to discern any differences?

**Comment by kathy-phet** [comment]
If we add this as a new platform, I would work with Katie to see what we can drop. It's interesting, and surprising, that we have 0 sessions on Google Analytics? Especially since Matt uses one. Hmmm....

**Comment by mattpen** [comment]
I briefly tested Gas Properties, BASE, and Build a Molecule and didn't notice any glaring bugs.  I haven't been using this device very long, it's possible I haven't tested a sim on it before today.

**Comment by mattpen** [comment]
Is there some kind of checklist I should run through for some sims?

**Comment by pixelzoom** [comment]
I also find it surprising that there are zero M1 sessions. Apple has been aggressively selling M1 Macs since November 2020.  It's more likely that analytics are not identifying M1 sessions. Regardless, M1 is Apple's new direction for Mac, so shouldn't PhET be testing on M1 ?

**Comment by pixelzoom** [comment]
@mattpen asked:
> Is there some kind of checklist I should run through for some sims?

You could fuzz test all sims in your local copy of aqua.  Go to phetmarks, select Repository=aqua, Mode="Fuzz test PhET Sims (Fast Build)", then press the Launch button.

**Comment by mattpen** [comment]
I've never used aqua or phetmarks.  Is there some documentation on how to run that?

**Comment by pixelzoom** [comment]
Assuming you have all of the active-repos checked out in your working copy....  Point your browser at your copy of the phetmarks repo.  The default index.html should display an interface that looks like this:

<img width="1083" alt="screenshot_872" src="https://user-images.githubusercontent.com/3046552/108448593-44472d00-721f-11eb-9a44-04235bbc6087.png">

Select Repository=aqua, Mode="Fuzz test PhET Sims (Fast Build)", then press the Launch button.  aqua will then automatically cycle through testing of all sims.   You'll see something like this as its doing that:

<img width="1083" alt="screenshot_873" src="https://user-images.githubusercontent.com/3046552/108448683-6e005400-721f-11eb-8cd5-092f8c7c49a5.png">

Anything other than a green rectangle means something went wrong, and problems will be reported in the panel to the right. Report any such problems in an issue.

**Comment by samreid** [comment]
If you don't have all the repos checked out, you can visit https://bayes.colorado.edu/dev/phettest/phetmarks

**Comment by pixelzoom** [comment]
How would visiting phetmarks on bayes help to test M1 ?

**Comment by pixelzoom** [comment]
Oh, I see. I guess that still runs that sims in your local browser. (For some reason, I can't login to bayes to run phetmarks via that URL.)

**Comment by mattpen** [comment]
I ran the aqua fuzz test on bayes.

Some of the sims failed (buoyancy, density, fluid-pressure-and-flow, fractions-equality, interaction-dashboard, make-a-ten), but I didn't see any error so I hit "Rerun Failed Sims".

On the second pass, the only one that failed was buoyancy:

```
buoyancy
Uncaught Error: Assertion failed: Cubic start should be finite: Vector2(-Infinity, 0)
Error: Assertion failed: Cubic start should be finite: Vector2(-Infinity, 0)
    at window.assertions.assertFunction (https://bayes.colorado.edu/dev/phettest/assert/js/assert.js:25:13)
    at Cubic.invalidate (https://bayes.colorado.edu/dev/phettest/kite/js/segments/Cubic.js:308:15)
    at new Cubic (https://bayes.colorado.edu/dev/phettest/kite/js/segments/Cubic.js:55:10)
    at Function.fillCrossSectionVertexArray (https://bayes.colorado.edu/dev/phettest/density-buoyancy-common/js/buoyancy/model/BoatDesign.js:289:19)
    at https://bayes.colorado.edu/dev/phettest/density-buoyancy-common/js/buoyancy/view/BoatView.js:79:18
    at listener (https://bayes.colorado.edu/dev/phettest/axon/js/Multilink.js:46:20)
    at TinyEmitter.emit (https://bayes.colorado.edu/dev/phettest/axon/js/TinyEmitter.js:86:18)
    at InterpolatedProperty._notifyListeners (https://bayes.colorado.edu/dev/phettest/axon/js/Property.js:294:25)
    at InterpolatedProperty.set (https://bayes.colorado.edu/dev/phettest/axon/js/Property.js:191:14)
    at InterpolatedProperty.set value [as value] (https://bayes.colorado.edu/dev/phettest/axon/js/Property.js:364:32)
buoyancy
Uncaught Error: Assertion failed: reentry detected, value=-0.1226539950370789, oldValue=-0.11889159250259403
Error: Assertion failed: reentry detected, value=-0.1226539950370789, oldValue=-0.11889159250259403
    at window.assertions.assertFunction (https://bayes.colorado.edu/dev/phettest/assert/js/assert.js:25:13)
    at InterpolatedProperty._notifyListeners (https://bayes.colorado.edu/dev/phettest/axon/js/Property.js:291:15)
    at InterpolatedProperty.set (https://bayes.colorado.edu/dev/phettest/axon/js/Property.js:191:14)
    at InterpolatedProperty.set value [as value] (https://bayes.colorado.edu/dev/phettest/axon/js/Property.js:364:32)
    at InterpolatedProperty.setRatio (https://bayes.colorado.edu/dev/phettest/density-buoyancy-common/js/common/model/InterpolatedProperty.js:58:16)
    at Boat.step (https://bayes.colorado.edu/dev/phettest/density-buoyancy-common/js/buoyancy/model/Boat.js:102:44)
    at https://bayes.colorado.edu/dev/phettest/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:304:12
    at Proxy.forEach ()
    at BuoyancyApplicationsModel.step (https://bayes.colorado.edu/dev/phettest/density-buoyancy-common/js/common/model/DensityBuoyancyModel.js:303:17)
    at https://bayes.colorado.edu/dev/phettest/joist/js/Sim.js:282:22
```

Should I open an issue in the buoyancy repo, or is this a known problem?

**Comment by samreid** [comment]
It looks like that problem is described in https://github.com/phetsims/buoyancy/issues/7

**Comment by KatieWoe** [comment]
Some of the mentioned sims have been having problems in CT, and so may already have an issue in their sim repo

**Comment by oliver-phet** [comment]
After more investigation with @mattpen, the reason we aren't seeing analytics sessions on M1 macs is because the user agent on M1 is still listed as "intel": `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36`

So, it seems we currently can't determine how many users are running PhET on M1 macs.

**Comment by pixelzoom** [comment]
From [this WebKit bug report](https://bugs.webkit.org/show_bug.cgi?id=216593), it sounds like this is a known problem:
> The world apparently isn't ready for macOS 11.0 in User Agents. Because of the depressing UA sniffing code on the web, let's just report our current shipping release until things settle down.

I'm not at all familiar with what information you're collecting for sessions. But [this link](https://news.ycombinator.com/item?id=23910280) has a few interesting tidbits:

* Apple may be using this (bogus) user-agent to avoid problems with "Sites that try to detect mobile by looking at ARM in user-agent string".

* You might be able to identify an M1 Mac "by looking at the webgl fingerprint, since the iGPU inside the A12Z is different than the ones used in Intel macs."

**Comment by veillette** [comment]
In geometric Optics, @sarchang identified a problem that is specific to her M1 laptop : https://github.com/phetsims/geometric-optics/issues/68.

**Comment by oliver-phet** [comment]
Thanks for reporting @veillette! I'll work with @KatieWoe to get our QA team an M1 device.

**Comment by KatieWoe** [comment]
Update: There are testers with this device. I'm leaving this open until there is one in the QA office.

**Comment by oliver-phet** [comment]
@KatieWoe can this be closed? I know @Nancy-Salpepi has an M1 device.

**Comment by KatieWoe** [comment]
Yes I believe it can. Thanks
