### ISSUE TITLE
Test for scratchy or distorted sound on iPad and Mac+Safari

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#613]
A while back an issue was reported on iPad 2 devices where the sound could sometimes sound "scratchy" or "distorted", see https://github.com/phetsims/tambo/issues/33.  A fix was put into place but never fully verified, and the original issue has sat idle for a while.  Since that time, we have stopped supporting iPad 2, so this may be a complete non-issue at this point.  So, some testing should be done of the current audio and we should figure out if this issue requires any further attention.

Please test sound generation on the published versions of the following sims on several different iPads and see if distorted sound is ever experienced.  If it is, record the platform information in this issue and I'll follow up.  Also, if such a condition is found, please see if it also exists on the master version.

Sims:
- Friction
- Gravity Force Labs
- John Travoltage
- Resistance in a Wire

**Comment by liam-mulhall** [comment]
I'm hearing the scratchiness in Friction when I turn on enhanced sound on my iPad Pro.

**Comment by liam-mulhall** [comment]
### Testing on MacBook Air

I'm hearing a _tiny tiny_ amount of scratchiness in...
* Friction
* RIAW

**Comment by liam-mulhall** [comment]
Unless other people want to do more testing, I think we can throw it back to @jbphet, @KatieWoe.

**Comment by liam-mulhall** [comment]
@jbphet, though there is a tiny amount of scratchiness, I don't think it sounds that bad. I remember when we first encountered this issue, and the scratchiness is a lot better now.

**Comment by jbphet** [comment]
I just spoke with @KatieWoe, and we decided that this can be closed.  It sounds like the scratchiness is minimal, and not disruptive to the use of the sim.  This is what I expected, since I think iPad 2 devices just didn't have the processing power to maintain both the visual and the audio threads, but we no longer support that device.
