### ISSUE TITLE
Maintenance Release: Fixing alerts after Chrome update

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#614]
This is a batch of maintenance releases for the issue identified in phetsims/utterance-queue#16. A change to Chrome made it so that all alerts stopped being spoken after about 5 alerts. Please spend 30-60 seconds with each link making sure that nothing is obviously broken. Then for the PhET brand links can you please check to make sure that screen reader alerts are coming through consistently on JAWS in Chrome and VoiceOver in Safari? Thanks! Let me know if you have any questions.

Assigning to @KatieWoe and @kathy-phet to prioritize.

gravity-force-lab 2.2 (https://github.com/phetsims/utterance-queue/issues/16)

- [x] [gravity-force-lab 2.2.2-rc.1](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.2-rc.1/phet/gravity-force-lab_en_phet.html)
- [x] [gravity-force-lab 2.2.2-rc.1 phet-io](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.2-rc.1/phet-io/gravity-force-lab_all_phet-io.html?phetioStandalone)
- [x] [gravity-force-lab 2.2.2-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.2-rc.1/phet-io/wrappers/studio)

gravity-force-lab-basics 1.0 (phetsims/utterance-queue#16)

- [x] [gravity-force-lab-basics 1.0.2-rc.1](https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.0.2-rc.1/phet/gravity-force-lab-basics_en_phet.html)

molarity 1.5 (https://github.com/phetsims/utterance-queue/issues/16)

- [x] [molarity 1.5.2-rc.1](https://phet-dev.colorado.edu/html/molarity/1.5.2-rc.1/phet/molarity_en_phet.html)

molecules-and-light 1.5 (https://github.com/phetsims/utterance-queue/issues/16)

- [x] [molecules-and-light 1.5.8-rc.1](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.8-rc.1/phet/molecules-and-light_en_phet.html)

ohms-law 1.4 (phetsims/utterance-queue#16)

- [x] [ohms-law 1.4.9-rc.1](https://phet-dev.colorado.edu/html/ohms-law/1.4.9-rc.1/phet/ohms-law_en_phet.html)

**Comment by jessegreenberg** [comment]
Also just notifying @emily-phet and @terracoda so you are aware of this request.

**Comment by KatieWoe** [comment]
Alerts seem ok on all sims with Win 10 Chrome + Jaws. I did notice that on Molecules and light, it seemed a bit more difficult to switch between light sources.

**Comment by terracoda** [comment]
Interesting Chrome has sonification on sliders when VO is enabled for that browser. I was just exploring GFL regular. Alerts worked great.

I tested GFL regular on Safari & VO on Mac OS High Sierra 10.13.6. It's never sounded so good! Responses did not conk out at all!

**Comment by jessegreenberg** [comment]
Great, thanks for spot checking @terracoda.

@KatieWoe I just tried the radio buttons with MAL with JAWS. I think what is happening is https://github.com/phetsims/a11y-research/issues/54#issuecomment-325709023, JAWS reads through radio buttons rather than automatically select them with arrow keys. But @KatieWoe if you think it is something else let me know.

**Comment by terracoda** [comment]
Unrelated to @KatieWoe's commented since I am spot checking VO & Chrome on MacOS, but for the record I didn't seem to have any trouble with the radio buttons. I did notice, however, that in Chrome VO says "bullet" 3 times whereas in Safari says "bullet" 2 times on lists of radio buttons.

Maybe we should find some time to make to make a decision on some of the investigation that has been done on the styling of bulleted lists in https://github.com/phetsims/a11y-research/issues/158

Responses are awesome for me in Chrome and Safari suing VO.

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe - new issues and comments are unrelated to this change so I am going to proceed with the redeploy.

**Comment by jessegreenberg** [comment]
This can be closed, will track deploy to production in https://github.com/phetsims/utterance-queue/issues/16.
