### ISSUE TITLE
Dev test: Capacitor Lab: Basics 1.8.0-dev.5

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#616]
@arouinfar, @kathy-phet, capacitor-lab-basics/1.8.0-dev.5 is ready for dev testing. Document issues in https://github.com/phetsims/capacitor-lab-basics/issues and link to this
issue.

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>General Dev Test Platforms</h3>

- [ ] Latest macOS, Chrome and Safari (Time = 9 hr)
- [ ] Latest iOS, Safari (Time = 1)
- [ ] Windows 10, all browsers (IE dropped) (Time = 29.5 hr )
- [ ] Latest Chrome OS, Chrome (Time = )

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.8.0-dev.5/phet/capacitor-lab-basics_en_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by jonathanolson** [comment]
@KatieWoe since we're seeing a number of regressions, can we test through previous known issues?

**Comment by KatieWoe** [comment]
Yeah, that sounds like a good idea. Let me know any specific ones you have in mind

**Comment by kathy-phet** [comment]
Katie, it looks like issues that were fixed on the previous rc branch were not fixed in master, so looking at the issues that were linked to the previous rc versions that went through QA would be best. (so pull up those QA tests). I would focus on the review of those issues, and after that is done, let's call it and we can fix anything that was found as not fixed on master.

**Comment by KatieWoe** [comment]
QA has covered this pretty well. Calling it now, but others may still check in until the repo fills in more

**Comment by jonathanolson** [comment]
Thank you!
