### ISSUE TITLE
Create "RC-Research" test

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#618]
From https://github.com/phetsims/molecule-polarity/issues/87#issuecomment-790759108:

 "RC-Research":
 
 * The sim will be reviewed by QA, preferrably on the platform(s) that will be used by the researcher.
* A test martix will be created.
* A QA issue will be created and labeled "RC-Research".
* The QA issue will be specific about what to focus on. Focus will be tailored to the needs of the research study.  (Specific features, PhET-iO data stream, specific screens,...)
* Test coverage will be somewhere below "RC-Lite" testing, as time permits.
* Additionally, the simulation team and the researcher may be asked to test.

**Comment by pixelzoom** [comment]
Handling this in #619, closing.
