### ISSUE TITLE
Flesh out the definitions of QA test types

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#619]
I pulled this out of #618, since it's a bit of an extra task:

> In addition, the phet-io design meeting team felt like https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#rc-test-types didn't quite cover what different tests entail. For example, we thought "RC-Lite" was actually just a dev test. That should likely be updated.

I will discuss with @KatieWoe and flesh out the definitions.

**Comment by pixelzoom** [comment]
The definitions that I'm familar with, and that I see in https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#rc-test-types, include:

* Dev
* RC
* RC-Lite
* RC-Research (see #618)

"Spot Check" is identified in https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#rc-test-types as a test type. But it looks to me like it's an additional label that is applied to the above test types when there's a short list of things to be tested.

**Comment by pixelzoom** [comment]
The test types that I'm aware of include:

* Dev
* RC
* RC-Lite
* RC-Research, see #618

The [section in the QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#rc-test-types) says:

> **RC Test Types**
> 
> There are three types of rc test types. The first is a full RC, which will not have any extra labels and should follow all instructions. Second is the RC-Lite which will have fewer devices/platforms for a faster test. Third is a Spot Check which focuses mostly on issue confirmations.

I don't see "Dev" test described in the QA Book. 

"Spot Check" is identified as a test type. But it looks to me like it's an additional label that is applied to the above test types when there's a short list of things to be tested.  For example, https://github.com/phetsims/QA/issues/603 is labeled as both "QA:rc-test" and "QA:spot-check".

**Comment by KatieWoe** [comment]
Dev is described in QA Book here: https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#41-development-dev-testing
Spot Checks are the lowest level of RC, in which focus is put on testing previous issues, and deeper testing associated with other rc types isn't focused on. The label discrepancy is due to this being done before other RC types were decided on, and should be addressed.

**Comment by pixelzoom** [comment]
From #618, "RC-Research" is defined as:

* The sim will be reviewed by QA, preferrably on the platform(s) that will be used by the researcher.
* A test martix will be created.
* A QA issue will be created and labeled "RC-Research".
* The QA issue will be specific about what to focus on. Focus will be tailored to the needs of the research study.  (Specific features, PhET-iO data stream, specific screens,...)
* Test coverage will be somewhere below "RC-Lite" testing, as time permits.
* Additionally, the simulation team and the researcher may be asked to test.

**Comment by KatieWoe** [comment]
QA:spot-check has been renamed QA:rc-spot-check

**Comment by KatieWoe** [comment]
QA book updated and new template made in above commits. Since it sounds like what is testing will be fairly variable by test I included a general checklist in the issue template, which is easier to edit than a Google sheet test matrix. @pixelzoom feel free to look over. Otherwise I think this can be closed.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe. I took at look at https://github.com/phetsims/QA/commit/35278f0b8cfa2e3fcac581d492b4a89046b4579f.  That's a step in the right direction, but this issue is not ready to close.  The goal is to specify each test type  with the level of details shown for "RC-Research" in https://github.com/phetsims/QA/issues/619#issuecomment-791065038, so that we're all clear about what the expectations are for each test type, and to put that info in the "RC Test Types" section of the QA book.  Would you like to take a stab at that, or would you prefer that I do that?

**Comment by KatieWoe** [comment]
I'll take a look

**Comment by zepumph** [comment]
From the discussion during status meeting today:

>Clarification: QA testing levels: 
  Dev: Deep testing on limited platforms
  RC-full: Deep testing across more platforms 
  RC-lite: Identical to “Dev” test but on an RC Branch 
         Less testing, due to time constraints or just less need for testing. 
  RC-research: Light testing
  RC-spot check: Limited testing on targeted issue fix verification 
       MK: Is this the timeline to expect in a “spot check”? https://github.com/phetsims/QA/issues/617#issuecomment-790861771 
       KW: That is a long for a spot check, we are tracking time to try to determine spots like this that need adjustment. 
  MK: How do you determine what RC test is for you?
       CM: it is a process, like in https://github.com/phetsims/natural-selection/issues/208

**Comment by pixelzoom** [comment]
I asked:
> Would you like to take a stab at that, or would you prefer that I do that?

@KatieWoe said:
> I'll take a look

I'm going to unassign myself until @KatieWoe has made a first pass.  Assign back to me when ready, and I'll be happy to review.

**Comment by KatieWoe** [comment]
The commit above was made awhile ago.

**Comment by KatieWoe** [comment]
Let me know if you wanted more @pixelzoom

**Comment by pixelzoom** [comment]
OK, thanks @KatieWoe.  Labeling as "ready-for-review".

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/QA/issues/619#issuecomment-793105301, I said:
> I took at look at https://github.com/phetsims/QA/commit/35278f0b8cfa2e3fcac581d492b4a89046b4579f.  That's a step in the right direction, but this issue is not ready to close.  The goal is to specify each test type  with the level of detail shown for "RC-Research" in https://github.com/phetsims/QA/issues/619#issuecomment-791065038, so that we're all clear about what the expectations are for each test type, and to put that info in the "RC Test Types" section of the QA book. 

So I was expecting to see a more detailed description of each test type, not the one-liners that appear in https://github.com/phetsims/QA/commit/0b94f465816eb2df71c62b6f6bf94bf6ab9299ec. But I guess the one-liners will do for now, and PhET can revisit if there's still any confusion about the expectations for each test type.

If that's OK with you @KatieWoe, then feel free to close.
