### ISSUE TITLE
RC (maintenance) test for Pendulum Lab 1.0.1-rc.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#62]
@arouinfar and @ariel-phet , Pendulum Lab 1.0.1-rc.1 is ready for maintenance testing for https://github.com/phetsims/pendulum-lab/issues/197.

**[Link to sim](https://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.1-rc.1/pendulum-lab_en.html)**

**Issues to Verify**
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/pendulum-lab/issues/196
- [x] https://github.com/phetsims/pendulum-lab/issues/195
- [x] https://github.com/phetsims/joist/issues/447
- [x] https://github.com/phetsims/joist/issues/449
- [x] https://github.com/phetsims/pendulum-lab/issues/187 (should stay fixed, with a different approach)

Presumably just test the above 5 issues as required, plus a brief (1min?) verification to make sure nothing major is broken.

**Comment by jonathanolson** [comment]
https://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.1-rc.2/pendulum-lab_en.html includes the fix for 180-degree angles (noted at bottom of https://github.com/phetsims/pendulum-lab/issues/195).

Let me know if it's OK to test in this issue, or if I should create another one. There should not be any other differences with this and rc.1.

**Comment by phet-steele** [comment]
@jonathanolson the fix in https://github.com/phetsims/pendulum-lab/issues/195 is fine. You can publish this.

**Comment by jonathanolson** [comment]
Publishing, closing.
