### ISSUE TITLE
Dev Test: Virtual Workshop

### ISSUE THREAD

**Issue by chrisklus** [phetsims/QA#622]
@amanda-phet, @kathy-phet, @mattpen, @KatieWoe the Virtual Workshop is ready for another round of dev testing. Please document issues in https://github.com/phetsims/website-meteor/issues and link to this issue.

Assigning @kathy-phet for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Try to include browser version numbers

<h3>Focus and Special Instructions</h3>

Please make sure all links work as expected, the page navigation works appropriately in both desktop and mobile view (the column on the left side only, not the top nav bar), and that the responsive layout handles the content without looking buggy. Sometimes the animations can be slow to respond as the page is loading, however, please look out for performance issues once loading is complete. If loading takes excessive time on a device + browser, please let me know.

There have been updates to the left-column navigation. Please report any buggy-looking behavior, or ask me (@chrisklus) on slack if unsure.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Chrome and Safari (Time = 4.5 hrs )
- [x] NVDA (Time = 1.5 hours)
- [x] JAWS (Time = 1.5 hours)
- [x] Latest iOS, Safari (Time = 2 hrs)
- [ ] Windows 10, all browsers (IE dropped) (Time = 11.75hrs )
- [x] Latest Chrome OS, Chrome (Time = .75 hours)

<h3>Link(s)</h3>

- **[Virtual Workshop](https://ox-dev.colorado.edu/en/teaching-resources/virtual-workshop/math)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
QA is done

**Comment by chrisklus** [comment]
A new test has been opened, closing.
