### ISSUE TITLE
RC-Research Test: Build An Atom 1.7.0-rc.2

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#624]
@kathy-phet @samreid @KatieWoe, we are ready for the RC research test for Build an Atom. This is the first test, but there were errors while building the sim, thus we are starting at rc.2 This is, as far as I know, the first rc-research test that has been done. We will be using PhET-iO recording to the Metacog backend for this study. With that in mind, please test the following:

* Do a full test of Metacog recording
* Please lightly test the mirror inputs and state wrappers
* ensure that `?showStableUnstableCheckbox=false` query parameter works as expected. It should hide the unstable checkbox.
* We **only need to test the first screen**
* Use https://phet-dev.colorado.edu/html/build-an-atom/1.7.0-rc.2/phet-io/wrappers/login/?wrapper=record&localFile&showStableUnstableCheckbox=false&validationRule=validateDigits&numberOfDigits=8&screens=1&phetioEmitStates=true&phetioEmitStatesInterval=60 to conduct much of your testing, either entering an 8 digit number, or "phettest" to login. You can also use this link for localFile record and playback.
* Conduct whatever base-level of sim testing is needing. A couple platforms, a bit of playing around with the sim. Again you can use the above link to test

[Sim link](https://phet-dev.colorado.edu/html/build-an-atom/1.7.0-rc.2/phet-io/build-an-atom_all_phet-io.html?postMessageOnError&phetioStandalone)
[Wrapper Index](https://phet-dev.colorado.edu/html/build-an-atom/1.7.0-rc.2/phet-io/)

- [x]  Latest macOS, Safari only (Time = 1). Max 2 hours.
- [x]  Windows 10, Chrome only (Time = 1). Max 2 hours. 

There is not yet an rc-research label, otherwise I would add it.

Over to @kathy-phet and @KatieWoe to prioritize.

**Comment by KatieWoe** [comment]
QA is done

**Comment by zepumph** [comment]
Thanks!
