### ISSUE TITLE
RC-Research Test: Molecule Polarity 1.1.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#627]
For https://github.com/phetsims/molecule-polarity/issues/87

@KatieWoe, @kathy-phet, @arouinfar, molecule-polarity/1.1.0-rc.1 is ready for RC-Research testing. 

This test will involve the PhET-iO version only.  A link to an RC version will be delivered to the researcher collaborator by 4/2/21.

Document issues in https://github.com/phetsims/molecule-polarity/issues and link to this
issue.

Assigning to @kathy-phet and @KatieWoe for prioritization.

---

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

What to Test:
- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.

What NOT to test:
- Pan and zoom has been disabled in this RC branch, see https://github.com/phetsims/molecule-polarity/issues/103.

Tips for creating issues:
- When making an issue, check to see if it was in a previously published version.
- Try to include version numbers for browsers.
- If there is a console available, check for errors and include them in the Problem Description.

<h3>Platforms and Browsers to Be Tested</h3>

We do not know what platforms will be used for the research study, so use this default list:

- [x] Windows 10 + Latest Chrome (Time = 3.5 hr)
- [x] Windows 10 + Latest Firefox (Time = .5)
- [x] macOS + Safari (Time = .5)
- [x] macOS + Chrome (Time = .5)
- [x] iOS + Safari (Time = .5)
- [ ] ChromeOS + Chrome (Time = )

</details>

<details>
<summary><b>PhET-iO RC Test</b></summary>

<h3>What to Test</h3>

From https://github.com/phetsims/molecule-polarity/issues/87, "saving state is of primary importance" for this research study. 

In addition to the **What to Test** section from **General RC Test** above:

- Test the Wrapper Index.
- Test the Standalone sim.
- Test the State Wrapper.
- Conduct a recording test to Metacog, further instructions in the QA Book.

<h3>Link(s)</h3>

- Wrapper Index: https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.1/phet-io

- Record Wrapper link:
https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.1/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&numberOfDigits=8&phetioEmitStates=true&phetioEmitStatesInterval=60

- Record to a local file:
https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.1/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&numberOfDigits=8&phetioEmitStates=true&phetioEmitStatesInterval=60&localFile

- Metacog recording (_You need to add usual Metacog-testing query parameters._):
https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.1/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&numberOfDigits=8&phetioEmitStates=true&phetioEmitStatesInterval=60

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Calling it here. QA is done.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe and QA team.  We will need one more RC, an rc-spot-check.  I'll leave this issue open and assigned to me until we receive feedback from the research collaborator (deadline Monday 3/29 @ 9:00AM MDT).

**Comment by pixelzoom** [comment]
1.1.0-rc.2 was publish and is being tested in https://github.com/phetsims/QA/issues/631.

Closing.
