### ISSUE TITLE
Dev test for Capacitor Lab: Basics 1.5.0-dev.2

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#63]
Test URL: https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-dev.2/capacitor-lab-basics_en.html

Please test:

- [x] Performance on platforms that would have the worst performance
- [x] https://github.com/phetsims/capacitor-lab-basics/issues/202
- [x] https://github.com/phetsims/capacitor-lab-basics/issues/201
- [x] https://github.com/phetsims/capacitor-lab-basics/issues/198
- [x] https://github.com/phetsims/capacitor-lab-basics/issues/197
- [x] https://github.com/phetsims/capacitor-lab-basics/issues/196
- [x] https://github.com/phetsims/capacitor-lab-basics/issues/195
- [x] General tests for how the voltmeter probes work. A lot was tweaked with them.
- [x] General tests for how the switch works. A lot was also tweaked with them.

**Comment by phet-steele** [comment]
This is done with dev.

**Comment by jonathanolson** [comment]
Thanks!
