### ISSUE TITLE
Platform testing for pointer capture changes

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#630]
For https://github.com/phetsims/scenery/issues/1186, it would help to have master tested on our supported platforms (briefly), to:

1. Make sure there are no glaring input issues with mouse/touch across our main platforms.
2. Ensure there don't seem to be regressions for drags that go outside of the window OR iframe (2 separate cases).
3. That the issue seems generally resolved, or cases where it isn't (I'm aware it's still possible to occasionally trigger this behavior in Safari).

**Comment by KatieWoe** [comment]
- [ ] Win 10 Chrome
- [ ] Win 10 Firefox
- [ ] MacOS 11 Chrome
- [ ] MacOS 11 Safari
- [ ] ChromeOS Chrome
- [ ] iPadOS Safari

**Comment by jonathanolson** [comment]
Also, this is marked as blocking-publication (for priority purposes), we'll presumably want to have this finished before creating an RC branch.

**Comment by KatieWoe** [comment]
Talked with @jonathanolson. At least with friction on master the fix doesn't seem to work as expected. Test on hold. @jonathanolson please let me know when this is ready to go again.

**Comment by jonathanolson** [comment]
Scenery commit should handle this, it seems SimpleDragHandler wasn't set up well for this in common code. (pull scenery, and it should work)

**Comment by KatieWoe** [comment]
Kicked off builds for Friction, Molecule Shapes, Energy Forms and Changes, and Make a 10 off of master.

**Comment by KatieWoe** [comment]
On Win 10 Chrome, Friction, EFAC, and Make 10 behaved as expected. Molecule Shapes does not drop dragged objects when released outside iframe, which indicates there may still be an issue. @jonathanolson I'll keep testing other platforms unless you want another pause.
![moleculeshapesnodropchrome](https://user-images.githubusercontent.com/41024075/113196102-581f7f00-9220-11eb-9086-c6f6e815767b.gif)

**Comment by KatieWoe** [comment]
QA is done. Looks ok

**Comment by jonathanolson** [comment]
Thanks!
