### ISSUE TITLE
RC-Research Test: Molecule Polarity 1.1.0-rc.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#631]
For https://github.com/phetsims/molecule-polarity/issues/87

@KatieWoe, @kathy-phet, @arouinfar, molecule-polarity/1.1.0-rc.2 is ready for RC-spot-check testing.   See "Issues to Verify" for the issues to be spot checked.

This test will involve the PhET-iO version only.  A link to an RC version will be delivered to the researcher collaborator by 4/2/21.

Document issues in https://github.com/phetsims/molecule-polarity/issues and link to this
issue.

Assigning to @kathy-phet and @KatieWoe for prioritization.

---

<details>
<summary><b>PhET-iO RC Test</b></summary>

<h3>What to Test</h3>

This is a spot check, and required very limited/specific testing.  See instruction in the individual issues listed in "Issues to Verify" for what needs to be tested.

<h3>Platforms and Browsers to Be Tested</h3>

See instructions in the individual issues listed in "Issues to Verify".

<h3>Issues to Verify</h3>

- [x] https://github.com/phetsims/molecule-polarity/issues/106
- [x] https://github.com/phetsims/molecule-polarity/issues/107
- [x] https://github.com/phetsims/molecule-polarity/issues/109

See the last comment in each of these issues for instructions on what and how to test.

These issues are labeled "status:ready-for-qa". Check these issues off and close them if they are fixed. Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue.

<h3>Link(s)</h3>

- Wrapper Index: https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.2/phet-io

- Record Wrapper link:
https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.2/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&numberOfDigits=8&phetioEmitStates=true&phetioEmitStatesInterval=60

- Record to a local file:
https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.2/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&numberOfDigits=8&phetioEmitStates=true&phetioEmitStatesInterval=60&localFile

- Metacog recording (_You need to add usual Metacog-testing query parameters._):
https://phet-dev.colorado.edu/html/molecule-polarity/1.1.0-rc.2/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&numberOfDigits=8&phetioEmitStates=true&phetioEmitStatesInterval=60

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
- [ ] Win 10 Chrome (Time = )
- [ ] Win 10 Firefox (Time = )
- [ ] MacOS 11 Safari (Time = )
- [ ] MacOS 11 Chrome (Time = )
- [ ] iPadOS (Time = )
- [ ] ChromeOS (Time = )

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
Thank you @KatieWoe and QA team for the quick turnaround.

#113 does not need to be addressed for https://github.com/phetsims/molecule-polarity/issues/87.  So the QA cycle is complete, and we're ready to deliver this RC version to the research collaborator. 

Closing.
