### ISSUE TITLE
Dev test: Desktop app 1.0.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#632]
The PhET Desktop App is available for testing. It is available [here](https://phet-dev.colorado.edu/weddell/dist/2021-03-26/): 

- [MacOS](https://phet-dev.colorado.edu/weddell/dist/2021-03-26/phet-mac-app.dmg)
- [Windows](https://phet-dev.colorado.edu/weddell/dist/2021-03-26/phet-windows-app.exe)

The desktop app requires a Java JDK to be installed (found [here](https://www.oracle.com/java/technologies/javase-jdk15-downloads.html#license-lightbox)). From this page install, the latest version (Java SE Development Kit 15.0.1) of the Java JDK for your tested platform as described below:
- Windows: Windows x64 Installer
- MacOS: macOS Installer

**General**

QA, please do a dev-test of the app. Please complete a general test to make sure that all sims are launching, resources are in the correct locale, and that all other functions of the app are working properly (menu items, shortcuts, filters, launching the app, installation, etc). Issues can be created in the [Weddell](https://github.com/phetsims/weddell/issues) repo.

**Locale Specific**

This version of the app has been built for multiple locales. These locales can be changed via the drop-down menus near the toolbar at the top of the app's window. The expected behavior for selecting locales is as follows:
1. Click a locale from the drop-down menu
2. App should refresh and the homepage should be translated.
3. Sims should open in the specified locale

Additionally, the app should open in the locale chosen before it was closed. For example, select "Spanish" then close the app. The next time the app is opened, it should be in "Spanish". Other functionality should remain the same.

Assigning to @kathy-phet and @KatieWoe for prioritization.

**Comment by KatieWoe** [comment]
- [ ] Mac (Time = )
- [ ] Windows (Time = )

**Comment by KatieWoe** [comment]
@kathy-phet and I decided to end QA on this for now until the Mac version can be tested as well.

**Comment by jbphet** [comment]
Sounds good.  I'll get the Mac version working and we'll give this another shot.  Closing.

**Comment by jbphet** [comment]
Okay, I did some investigation, and I think the original build was actually good, but something went wrong with getting the file transferred to the phet-dev server.  I have re-transferred the DMG file, and fixed some permissions issues, and just downloaded it onto a Mac that I have access to, and it seems to have worked fine.  I'm going to re-open this issue, and testing can continue.

@KatieWoe - Note that this is not a new build, so any testing that was done on the Windows version is still applicable.

**Comment by KatieWoe** [comment]
QA is done
