### ISSUE TITLE
RC-Research Test: Molecule Shapes 1.3.0-rc.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#635]
@arouinfar, @kathy-phet, molecule-shapes/1.3.0-rc.1 is ready for RC Research testing. April 4th deadline for providing links. 

This test will **involve the PhET-iO version only**. A link to an RC version will be delivered to the researcher collaborator asap (so test today if possible!). 

Document issues in https://github.com/phetsims/molecule-shapes/issues and link to this issue.

Bits to consider in testing is that running it with `?webgl=false` might be good to hit, and the global options. @arouinfar what else would be used in the study?

Assigning to @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General RC-research Test</b></summary>

<h3>What to Test</h3>

For the research study: https://github.com/phetsims/special-ops/issues/190

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Platforms and Browsers to Be Tested</h3>

[ideally test the platforms that are relevant to the research study, otherwise use this default list]
- [ ] Windows 10 + Latest Chrome (Time = )
- [ ] Windows 10 + Latest Firefox (Time = )
- [ ] macOS + Safari (Time = )
- [ ] macOS + Chrome (Time = )
- [ ] iOS + Safari (Time = )
- [ ] ChromeOS + Chrome (Time = )

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/molecule-shapes/1.3.0-rc.1/phet/molecule-shapes_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/molecule-shapes/1.3.0-rc.1/phet/molecule-shapes_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/molecule-shapes/1.3.0-rc.1/phet/xhtml/molecule-shapes_all.xhtml)**

<hr>

</details>

<details>
<summary><b>PhET-iO RC-research Test</b></summary>

<h3>What to Test</h3>

In addition to the What to Test section from General RC Test above:

Test the Wrapper Index.
Test the Standalone sim.
Test the State Wrapper.
Conduct a recording test to Metacog, further instructions in the QA Book.

<h3>Link(s)</h3>

Wrapper Index: https://phet-dev.colorado.edu/html/molecule-shapes/1.3.0-rc.1/phet-io

Record Wrapper link:
https://phet-dev.colorado.edu/html/molecule-shapes/1.3.0-rc.1/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&numberOfDigits=8&phetioEmitStates=true&phetioEmitStatesInterval=60

Record to a local file:
https://phet-dev.colorado.edu/html/molecule-shapes/1.3.0-rc.1/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&numberOfDigits=8&phetioEmitStates=true&phetioEmitStatesInterval=60&localFile

Metacog recording (You need to add usual Metacog-testing query parameters.):
https://phet-dev.colorado.edu/html/molecule-shapes/1.3.0-rc.1/phet-io/wrappers/login/?wrapper=record&validationRule=validateDigits&numberOfDigits=8&phetioEmitStates=true&phetioEmitStatesInterval=60

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by arouinfar** [comment]
>  @arouinfar what else would be used in the study?

@KatieWoe this research partner is the same as #624 and #627, so it seems appropriate to focus your testing similarly.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/special-ops/issues/190#issuecomment-812750239 and below, a query parameter was added with specific customizations for this research, please add `?research` to the link that you are testing, like 

https://github.com/phetsims/special-ops/issues/190#issuecomment-812750239

And ensure that these customizations work (from https://github.com/phetsims/special-ops/issues/190#issue-817434899):
>His desired customizations:
Model Screen: This one is tricky. We would prefer to limit the number of electron pairs (whether binding or lone) **to 4**. That is, not to allow learners to create molecules like XY5, XY6, etc.
Real molecules Screen: Please leave in only **H2O, CO2, NH3, BF3, NH3, CH4.**

**Comment by liam-mulhall** [comment]
@jonathanolson, the customizations that @zepumph mentioned seem to be working on macOS + Safari. I didn't see any glaring issues when testing. I checked every wrapper and did a lot of recordings.

**Comment by kathy-phet** [comment]
Thank you!!

**Comment by kathy-phet** [comment]
I delivered the links to Ido. Thank you QA. Closing!
