### ISSUE TITLE
Dev Test: Apps for Schools page

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#637]
QA, please complete a dev test of the [Apps for Schools page](https://ox-dev.colorado.edu/en/apps-for-schools).  Please test all supported platforms evaluating layout and format in general and behavior of the FAQ expandable sections.

Additionally, please check that the content is accessible with keyboard navigation and our supported screen reader platforms.

**Comment by KatieWoe** [comment]
Win 10 Chrome (Time = )
Win 10 Firefox (Time = )
Mac 11 Safari (Time = )
Mac 11 Chrome (Time = )
iPadOS (Time = )
ChromeOS (Time = )

**Comment by KatieWoe** [comment]
QA is done

**Comment by mattpen** [comment]
Thanks for the help QA, and @KatieWoe.  I'm going to close this as everything here is covered in other issues.
