### ISSUE TITLE
RC Spot Check: Virtual Workshop 1.1

### ISSUE THREAD

**Issue by chrisklus** [phetsims/QA#638]
@amanda-phet, @kathy-phet, @mattpen, @KatieWoe the Virtual Workshop is ready for an RC spot check. Please document issues in https://github.com/phetsims/website-meteor/issues and link to this issue.

Assigning @kathy-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

See issues to verify

<h3>Issues to Verify</h3>

Please see https://github.com/phetsims/website-meteor/issues/250 for this section.

These issues should have the "status:ready-for-qa" label. Check these issues off and comment if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[Virtual Workshop](https://ox-dev.colorado.edu/en/teaching-resources/virtual-workshop/math)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Win 10 Chrome (Time = )
Win 10 Firefox (Time = )
Mac 11 Safari (Time = )
Mac 11 Chrome (Time = )
iPadOS (Time = )
ChromeOS (Time = )

**Comment by KatieWoe** [comment]
QA is done. Some tests not checked off and closed if not fixed or clarification needed

**Comment by chrisklus** [comment]
1.1 has been published, thanks! closing.
