### ISSUE TITLE
RC Spot Check: Number Line: Integers 1.1.0-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#639]
@KatieWoe, @kathy-phet, and @amanda-phet - number-line-integers/1.1.0-rc.2 is ready for RC testing.  This release is
phet brand only.  This is the 2nd RC on this release branch, and the testing for the first one found two issues, both of
which have been resolved.  I have therefore set this issue up as a spot check where the two issues should be verified, and
some other basic sanity testing done.

Assigning to @KatieWoe and @kathy-phet for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md)
  for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
  spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
  there is a problem.

<h3>Focus and Special Instructions</h3>

The focus for this testing should be on verifying that the issues found during testing of the most recent RC have been
adequately addressed.

<h3>Issues to Verify</h3>

- [x] [CT should not be in this situation if controller is always locked to a point](https://github.com/phetsims/number-line-integers/issues/106)
  - Though this issue was initially caught by CT, there are two sets of descriptions in the issue for how to duplicate
    the problem manually, and these should be tested as well as doing fuzz testing.
- [x] [Longer strings go out of bounds](https://github.com/phetsims/number-line-integers/issues/107)

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/number-line-integers/1.1.0-rc.2/phet/number-line-integers_en_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/number-line-integers/1.1.0-rc.2/phet/number-line-integers_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/number-line-integers/1.1.0-rc.2/phet/xhtml/number-line-integers_all.xhtml)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Please mark testing time in the above comment

**Comment by KatieWoe** [comment]
Spot check looks good. @jbphet let me know if you want more device coverage, otherwise I think this one is done

**Comment by jbphet** [comment]
Cool, thanks.  Moving forward with publication.
