### ISSUE TITLE
RC test for Capacitor Lab: Basics 1.5.0-rc.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#64]
@arouinfar and @ariel-phet, Capacitor Lab: Basics 1.5.0-rc.1 is ready for RC testing.

**[Link to sim](https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-rc.1/capacitor-lab-basics_en.html)**

**[Link to iFrame](https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-rc.1/capacitor-lab-basics_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1E_HoXYhttDYPm5HT01e54N6S9m9T1XqUk-w2kIKfngI/edit#gid=2)**

**Please also verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any new issues are found, please note them in https://github.com/phetsims/capacitor-lab-basics/issues and reference this issue.  

 
**(Other potentially useful items)**  

Sim-specific query parameters useful for testing:  
• `?showDebugAreas` - Overlays the zones used for testing whether a probe is over a wire/capacitor/etc.

Sim-specific terminology:  
• switch - The switches at the top and bottom. Have "connection points" at each end and a "hinge" where it connects to the capacitor
• battery / capacitor (with plates) / wire / voltmeter / circuit as self-explanatory terms

Note that this sim is backed by a 3D model coordinate system, which is then displayed in a rotated orthographic projection.

**Comment by jonathanolson** [comment]
@phet-steele, let me know if there is a way to create the text matrix (last time I tried it ended up with incorrect permissions, so I wasn't proactive about it here).

**Comment by ariel-phet** [comment]
@phet-steele current top testing priority!

**Comment by phet-steele** [comment]
Moving forward without testing iPad Air 2 iOS 10.3.3 (platform currently unavailable). @jonathanolson testing this rc is done.

**Comment by jonathanolson** [comment]
Thanks!
