### ISSUE TITLE
Dev Test: Capacitor Lab Basics: 1.8.0-dev.6

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#640]
@arouinfar, @kathy-phet, capacitor-lab-basics/1.8.0-dev.6 is ready for dev testing. Document issues in https://github.com/phetsims/capacitor-lab-basics/issues and link to this
issue.

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>What to Verify</h3>

- [x] Verify https://github.com/phetsims/capacitor-lab-basics/issues/256

<h3>General Dev Test Platforms</h3>

Required: 
- [ ] Latest macOS, Safari (Time = .5)
- [x] Windows 10, Chrome (Time =  3.3 hours )
- [ ] Windows 10, Firefox (Time = 3 hours )
- [x] Latest iOS, Safari (Time = 1)

Light testing, or optionally skip if time crunch: 
- [ ] Latest macOS, Chrome (Time = )
- [ ] Latest Chrome OS, Chrome (Time = )

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.8.0-dev.6/phet/capacitor-lab-basics_en_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
QA is done

**Comment by arouinfar** [comment]
Nice find @KatieWoe. 

It basically looks like the current arrows will not reappear on the light bulb side of the circuit if you turn them off and then back on while paused. The arrows will appear again when the model is stepped forward. I think this is a really minor issue so unless there is a nearly effortless solution to this, I'm fine as closing as wontfix @jonathanolson.

**Comment by jonathanolson** [comment]
Thank you!
