### ISSUE TITLE
Maintenance testing for out-of-iframe interaction

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#642]
For https://github.com/phetsims/scenery/issues/1199, I've applied scenery patches for input handling so that we detect when a pointer (mouse/touch) has "lost capture" (which seems to happen when re-entering the iframe in Chrome after release, or immediately on release on Safari, etc.)

I think it would be appropriate for every sim to test:

- General input behavior, make sure the sim isn't horribly broken (try dragging the main draggable parts of the sim, sometimes dragging out of the iframe)
- Test with the iframe to make sure that the patched behavior is fixed -- NOTE that this mainly means "the drag isn't still acting like the moving mouse is still dragging it" after the mouse has been released. Some sims seem to still have highlighting on the dragged item (since they didn't have full support for interruption baked in). See https://github.com/phetsims/scenery/issues/1199 for more information on what is expected/desired.
- For phet-io sims: Studio/instances proxies should load, and then customize something in it.
- For phet-io sims: Go to mirror-inputs and test out the case this MR is for, since it is recording in iframes, the downstream sim should stay in sync because of the new input events.

If there are any questions, let me know!

area-model-algebra 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [area-model-algebra 1.2.2-rc.1](https://phet-dev.colorado.edu/html/area-model-algebra/1.2.2-rc.1/phet/area-model-algebra_en_iframe_phet.html)

area-model-decimals 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [area-model-decimals 1.2.2-rc.1](https://phet-dev.colorado.edu/html/area-model-decimals/1.2.2-rc.1/phet/area-model-decimals_en_iframe_phet.html)

area-model-introduction 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [area-model-introduction 1.2.2-rc.1](https://phet-dev.colorado.edu/html/area-model-introduction/1.2.2-rc.1/phet/area-model-introduction_en_iframe_phet.html)

area-model-multiplication 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [area-model-multiplication 1.2.2-rc.2](https://phet-dev.colorado.edu/html/area-model-multiplication/1.2.2-rc.2/phet/area-model-multiplication_en_iframe_phet.html)

atomic-interactions 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [atomic-interactions 1.2.1-rc.1](https://phet-dev.colorado.edu/html/atomic-interactions/1.2.1-rc.1/phet/atomic-interactions_en_iframe_phet.html)

balancing-act 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [balancing-act 1.2.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/balancing-act/1.2.4-rc.1/phet-io/balancing-act_all_phet-io.html?phetioStandalone)
- [x] [balancing-act 1.2.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/balancing-act/1.2.4-rc.1/phet-io/wrappers/studio)

balancing-chemical-equations 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [balancing-chemical-equations 1.2.11-rc.1](https://phet-dev.colorado.edu/html/balancing-chemical-equations/1.2.11-rc.1/phet/balancing-chemical-equations_en_iframe_phet.html)

balloons-and-static-electricity 1.4 (https://github.com/phetsims/scenery/issues/1199)

- [x] [balloons-and-static-electricity 1.4.15-rc.1](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.4.15-rc.1/phet/balloons-and-static-electricity_en_iframe_phet.html)

blackbody-spectrum 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [blackbody-spectrum 1.0.8-rc.1](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.8-rc.1/phet/blackbody-spectrum_en_iframe_phet.html)

build-a-fraction 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [build-a-fraction 1.0.13-rc.1](https://phet-dev.colorado.edu/html/build-a-fraction/1.0.13-rc.1/phet/build-a-fraction_en_iframe_phet.html)

build-a-molecule 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [build-a-molecule 1.0.3-rc.1](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.3-rc.1/phet/build-a-molecule_en_iframe_phet.html)

build-an-atom 1.6 (https://github.com/phetsims/scenery/issues/1199)

- [x] [build-an-atom 1.6.16-rc.1](https://phet-dev.colorado.edu/html/build-an-atom/1.6.16-rc.1/build-an-atom_en-iframe.html)

capacitor-lab-basics 1.6 (https://github.com/phetsims/scenery/issues/1199)

- [x] [capacitor-lab-basics 1.6.20-rc.1](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.20-rc.1/phet/capacitor-lab-basics_en_iframe_phet.html)
- [ ] [**capacitor-lab-basics 1.6.20-rc.1 phet-io**](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.20-rc.1/phet-io/capacitor-lab-basics_all_phet-io.html?phetioStandalone)
- [ ] [**capacitor-lab-basics 1.6.20-rc.1 phet-io Instance Proxies**](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.20-rc.1/phet-io/wrappers/instance-proxies/instance-proxies.html?sim=capacitor-lab-basics&relativeSimPath)

circuit-construction-kit-dc 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [circuit-construction-kit-dc 1.2.3-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.3-rc.1/phet/circuit-construction-kit-dc_en_iframe_phet.html)

circuit-construction-kit-dc-virtual-lab 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [circuit-construction-kit-dc-virtual-lab 1.2.3-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.2.3-rc.1/phet/circuit-construction-kit-dc-virtual-lab_en_iframe_phet.html)

collision-lab 1.1 (https://github.com/phetsims/scenery/issues/1199)

- [x] [collision-lab 1.1.1-rc.1](https://phet-dev.colorado.edu/html/collision-lab/1.1.1-rc.1/phet/collision-lab_en_iframe_phet.html)

coulombs-law 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [coulombs-law 1.0.10-rc.1](https://phet-dev.colorado.edu/html/coulombs-law/1.0.10-rc.1/phet/coulombs-law_en_iframe_phet.html)

curve-fitting 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [curve-fitting 1.0.1-rc.1](https://phet-dev.colorado.edu/html/curve-fitting/1.0.1-rc.1/phet/curve-fitting_en_iframe_phet.html)

diffusion 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [diffusion 1.0.5-rc.1](https://phet-dev.colorado.edu/html/diffusion/1.0.5-rc.1/phet/diffusion_en_iframe_phet.html)

energy-forms-and-changes 1.4 (https://github.com/phetsims/scenery/issues/1199)

- [x] [energy-forms-and-changes 1.4.1-rc.1](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.1-rc.1/phet/energy-forms-and-changes_en_iframe_phet.html)
- [x] [energy-forms-and-changes 1.4.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.1-rc.1/phet-io/energy-forms-and-changes_all_phet-io.html?phetioStandalone)
- [x] [energy-forms-and-changes 1.4.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.1-rc.1/phet-io/wrappers/studio)

energy-skate-park 1.1 (https://github.com/phetsims/scenery/issues/1199)

- [x] [energy-skate-park 1.1.2-rc.1](https://phet-dev.colorado.edu/html/energy-skate-park/1.1.2-rc.1/phet/energy-skate-park_en_iframe_phet.html)

equality-explorer 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [equality-explorer 1.0.13-rc.2](https://phet-dev.colorado.edu/html/equality-explorer/1.0.13-rc.2/phet/equality-explorer_en_iframe_phet.html)

equality-explorer-basics 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [equality-explorer-basics 1.0.13-rc.1](https://phet-dev.colorado.edu/html/equality-explorer-basics/1.0.13-rc.1/phet/equality-explorer-basics_en_iframe_phet.html)

equality-explorer-two-variables 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [equality-explorer-two-variables 1.0.13-rc.1](https://phet-dev.colorado.edu/html/equality-explorer-two-variables/1.0.13-rc.1/phet/equality-explorer-two-variables_en_iframe_phet.html)

expression-exchange 1.1 (https://github.com/phetsims/scenery/issues/1199)

- [x] [expression-exchange 1.1.15-rc.1](https://phet-dev.colorado.edu/html/expression-exchange/1.1.15-rc.1/expression-exchange_en-iframe.html)

faradays-law 1.4 (https://github.com/phetsims/scenery/issues/1199)

- [x] [faradays-law 1.4.2-rc.1](https://phet-dev.colorado.edu/html/faradays-law/1.4.2-rc.1/phet/faradays-law_en_iframe_phet.html)

forces-and-motion-basics 2.3 (https://github.com/phetsims/scenery/issues/1199)

- [x] [forces-and-motion-basics 2.3.17-rc.1](https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.3.17-rc.1/forces-and-motion-basics_en-iframe.html)

fraction-matcher 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [fraction-matcher 1.2.2-rc.3](https://phet-dev.colorado.edu/html/fraction-matcher/1.2.2-rc.3/phet/fraction-matcher_en_iframe_phet.html)

fractions-equality 1.1 (https://github.com/phetsims/scenery/issues/1199)

- [x] [fractions-equality 1.1.2-rc.1](https://phet-dev.colorado.edu/html/fractions-equality/1.1.2-rc.1/phet/fractions-equality_en_iframe_phet.html)

fractions-intro 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [fractions-intro 1.0.13-rc.1](https://phet-dev.colorado.edu/html/fractions-intro/1.0.13-rc.1/phet/fractions-intro_en_iframe_phet.html)

fractions-mixed-numbers 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [fractions-mixed-numbers 1.0.13-rc.1](https://phet-dev.colorado.edu/html/fractions-mixed-numbers/1.0.13-rc.1/phet/fractions-mixed-numbers_en_iframe_phet.html)

friction 1.5 (https://github.com/phetsims/scenery/issues/1199)

- [x] [friction 1.5.11-rc.1](https://phet-dev.colorado.edu/html/friction/1.5.11-rc.1/phet/friction_en_iframe_phet.html)

gas-properties 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [gas-properties 1.0.5-rc.1](https://phet-dev.colorado.edu/html/gas-properties/1.0.5-rc.1/phet/gas-properties_en_iframe_phet.html)

gases-intro 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [gases-intro 1.0.6-rc.1](https://phet-dev.colorado.edu/html/gases-intro/1.0.6-rc.1/phet/gases-intro_en_iframe_phet.html)

gene-expression-essentials 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [gene-expression-essentials 1.0.17-rc.1](https://phet-dev.colorado.edu/html/gene-expression-essentials/1.0.17-rc.1/gene-expression-essentials_en.html)

graphing-lines 1.3 (https://github.com/phetsims/scenery/issues/1199)

- [x] [graphing-lines 1.3.11-rc.1](https://phet-dev.colorado.edu/html/graphing-lines/1.3.11-rc.1/phet/graphing-lines_en_iframe_phet.html)

graphing-quadratics 1.1 (https://github.com/phetsims/scenery/issues/1199)

- [x] [graphing-quadratics 1.1.6-rc.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.6-rc.1/phet/graphing-quadratics_en_iframe_phet.html)
- [x] [graphing-quadratics 1.1.6-rc.1 phet-io](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.6-rc.1/phet-io/graphing-quadratics_all_phet-io.html?phetioStandalone)
- [x] [graphing-quadratics 1.1.6-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.6-rc.1/phet-io/wrappers/studio)

graphing-slope-intercept 1.1 (https://github.com/phetsims/scenery/issues/1199)

- [x] [graphing-slope-intercept 1.1.10-rc.1](https://phet-dev.colorado.edu/html/graphing-slope-intercept/1.1.10-rc.1/phet/graphing-slope-intercept_en_iframe_phet.html)

gravity-and-orbits 1.4 (https://github.com/phetsims/scenery/issues/1199)

- [x] [gravity-and-orbits 1.4.1-rc.1](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.4.1-rc.1/phet/gravity-and-orbits_en_iframe_phet.html)
- [x] [gravity-and-orbits 1.4.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.4.1-rc.1/phet-io/gravity-and-orbits_all_phet-io.html?phetioStandalone)
- [x] [gravity-and-orbits 1.4.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.4.1-rc.1/phet-io/wrappers/studio)

gravity-force-lab 2.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [gravity-force-lab 2.2.3-rc.1](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.3-rc.1/phet/gravity-force-lab_en_iframe_phet.html)
- [x] [gravity-force-lab 2.2.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.3-rc.1/phet-io/gravity-force-lab_all_phet-io.html?phetioStandalone)
- [x] [gravity-force-lab 2.2.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.3-rc.1/phet-io/wrappers/studio)

gravity-force-lab-basics 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [gravity-force-lab-basics 1.0.3-rc.1](https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.0.3-rc.1/phet/gravity-force-lab-basics_en_iframe_phet.html)

isotopes-and-atomic-mass 1.1 (https://github.com/phetsims/scenery/issues/1199)

- [x] [isotopes-and-atomic-mass 1.1.10-rc.1](https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.10-rc.1/phet/isotopes-and-atomic-mass_en_iframe_phet.html)

john-travoltage 1.5 (https://github.com/phetsims/scenery/issues/1199)

- [x] [john-travoltage 1.5.13-rc.1](https://phet-dev.colorado.edu/html/john-travoltage/1.5.13-rc.1/phet/john-travoltage_en_iframe_phet.html)

masses-and-springs 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [masses-and-springs 1.0.11-rc.1](https://phet-dev.colorado.edu/html/masses-and-springs/1.0.11-rc.1/phet/masses-and-springs_en_iframe_phet.html)

masses-and-springs-basics 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [masses-and-springs-basics 1.0.10-rc.1](https://phet-dev.colorado.edu/html/masses-and-springs-basics/1.0.10-rc.1/phet/masses-and-springs-basics_en_iframe_phet.html)

molarity 1.4 (https://github.com/phetsims/scenery/issues/1199, https://github.com/phetsims/phet-io/issues/1742)

- [x] [molarity 1.4.13-rc.1 phet-io](https://phet-dev.colorado.edu/html/molarity/1.4.13-rc.1/phet-io/molarity_all_phet-io.html?phetioStandalone)
- [x] [molarity 1.4.13-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molarity/1.4.13-rc.1/phet-io/wrappers/studio/studio.html?sim=molarity&relativeSimPath))

molarity 1.5 (https://github.com/phetsims/scenery/issues/1199)

- [x] [molarity 1.5.3-rc.1](https://phet-dev.colorado.edu/html/molarity/1.5.3-rc.1/phet/molarity_en_iframe_phet.html)

molecule-polarity 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [molecule-polarity 1.0.16-rc.1](https://phet-dev.colorado.edu/html/molecule-polarity/1.0.16-rc.1/molecule-polarity_en.html)

molecule-shapes 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [molecule-shapes 1.2.9-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes/1.2.9-rc.1/phet/molecule-shapes_en_iframe_phet.html)

molecule-shapes-basics 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [molecule-shapes-basics 1.2.9-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.9-rc.1/phet/molecule-shapes-basics_en_iframe_phet.html)

molecules-and-light 1.5 (https://github.com/phetsims/scenery/issues/1199)

- [x] [molecules-and-light 1.5.9-rc.1](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.9-rc.1/phet/molecules-and-light_en_iframe_phet.html)

natural-selection 1.1 (https://github.com/phetsims/scenery/issues/1199)

- [x] [natural-selection 1.1.2-rc.1](https://phet-dev.colorado.edu/html/natural-selection/1.1.2-rc.1/phet/natural-selection_en_iframe_phet.html)

natural-selection 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [natural-selection 1.2.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/natural-selection/1.2.1-rc.1/phet-io/natural-selection_all_phet-io.html?phetioStandalone)
- [x] [natural-selection 1.2.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/natural-selection/1.2.1-rc.1/phet-io/wrappers/studio)

number-line-integers 1.1 (https://github.com/phetsims/scenery/issues/1199)

- [x] [number-line-integers 1.1.1-rc.1](https://phet-dev.colorado.edu/html/number-line-integers/1.1.1-rc.1/phet/number-line-integers_en_iframe_phet.html)

number-line-operations 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [number-line-operations 1.0.2-rc.1](https://phet-dev.colorado.edu/html/number-line-operations/1.0.2-rc.1/phet/number-line-operations_en_iframe_phet.html)

ohms-law 1.4 (https://github.com/phetsims/scenery/issues/1199)

- [x] [ohms-law 1.4.10-rc.1](https://phet-dev.colorado.edu/html/ohms-law/1.4.10-rc.1/phet/ohms-law_en_iframe_phet.html)

pendulum-lab 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [pendulum-lab 1.0.16-rc.1](https://phet-dev.colorado.edu/html/pendulum-lab/1.0.16-rc.1/pendulum-lab_en.html)

ph-scale 1.3 (https://github.com/phetsims/scenery/issues/1199)

- [x] [ph-scale 1.3.5-rc.1](https://phet-dev.colorado.edu/html/ph-scale/1.3.5-rc.1/phet/ph-scale_en_iframe_phet.html)

ph-scale-basics 1.3 (https://github.com/phetsims/scenery/issues/1199)

- [x] [ph-scale-basics 1.3.5-rc.1](https://phet-dev.colorado.edu/html/ph-scale-basics/1.3.5-rc.1/phet/ph-scale-basics_en_iframe_phet.html)

projectile-motion 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [projectile-motion 1.0.16-rc.1](https://phet-dev.colorado.edu/html/projectile-motion/1.0.16-rc.1/projectile-motion_en.html)

ratio-and-proportion 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [ratio-and-proportion 1.0.1-rc.1](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.1-rc.1/phet/ratio-and-proportion_en_iframe_phet.html)

reactants-products-and-leftovers 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [reactants-products-and-leftovers 1.2.12-rc.1](https://phet-dev.colorado.edu/html/reactants-products-and-leftovers/1.2.12-rc.1/phet/reactants-products-and-leftovers_en_iframe_phet.html)

resistance-in-a-wire 1.3-phetio (https://github.com/phetsims/scenery/issues/1199)

- [ ] [**resistance-in-a-wire 1.3.13-rc.1 phet-io**](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.3.13-phetiorc.1/resistance-in-a-wire_en-phetio.html?phetioStandalone)
- [ ] [**resistance-in-a-wire 1.3.13-rc.1 phet-io Instance Proxies**](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.3.13-phetiorc.1/wrappers/instance-proxies/instance-proxies.html?sim=resistance-in-a-wire&relativeSimPath)

resistance-in-a-wire 1.6 (https://github.com/phetsims/scenery/issues/1199)

- [x] [resistance-in-a-wire 1.6.11-rc.1](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.11-rc.1/phet/resistance-in-a-wire_en_iframe_phet.html)

rutherford-scattering 1.1 (https://github.com/phetsims/scenery/issues/1199)

- [x] [rutherford-scattering 1.1.10-rc.1](https://phet-dev.colorado.edu/html/rutherford-scattering/1.1.10-rc.1/phet/rutherford-scattering_en_iframe_phet.html)

states-of-matter 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [states-of-matter 1.2.2-rc.1](https://phet-dev.colorado.edu/html/states-of-matter/1.2.2-rc.1/phet/states-of-matter_en_iframe_phet.html)
- [x] [states-of-matter 1.2.2-rc.1 phet-io](https://phet-dev.colorado.edu/html/states-of-matter/1.2.2-rc.1/phet-io/states-of-matter_all_phet-io.html?phetioStandalone)
- [x] [states-of-matter 1.2.2-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/states-of-matter/1.2.2-rc.1/phet-io/wrappers/studio)

states-of-matter-basics 1.2 (https://github.com/phetsims/scenery/issues/1199)

- [x] [states-of-matter-basics 1.2.1-rc.1](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.1-rc.1/phet/states-of-matter-basics_en_iframe_phet.html)
- [x] [states-of-matter-basics 1.2.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.1-rc.1/phet-io/states-of-matter-basics_all_phet-io.html?phetioStandalone)
- [x] [states-of-matter-basics 1.2.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.1-rc.1/phet-io/wrappers/studio)

vector-addition 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [vector-addition 1.0.1-rc.1](https://phet-dev.colorado.edu/html/vector-addition/1.0.1-rc.1/phet/vector-addition_en_iframe_phet.html)

vector-addition-equations 1.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [vector-addition-equations 1.0.1-rc.1](https://phet-dev.colorado.edu/html/vector-addition-equations/1.0.1-rc.1/phet/vector-addition-equations_en_iframe_phet.html)

wave-interference 2.0 (https://github.com/phetsims/scenery/issues/1199)

- [x] [wave-interference 2.0.3-rc.1](https://phet-dev.colorado.edu/html/wave-interference/2.0.3-rc.1/phet/wave-interference_en_iframe_phet.html)

waves-intro 1.1 (https://github.com/phetsims/scenery/issues/1199)

- [x] [waves-intro 1.1.1-rc.1](https://phet-dev.colorado.edu/html/waves-intro/1.1.1-rc.1/phet/waves-intro_en_iframe_phet.html)

**Comment by KatieWoe** [comment]
In Area Model Algebra I saw this problem still present if holding down the number picker.
![dragoutpicker](https://user-images.githubusercontent.com/41024075/116320259-2218e080-a775-11eb-903e-1b8a8df4a75e.gif)

**Comment by KatieWoe** [comment]
Devices/Platforms:
Win 10 Chrome (4 sims)

**Comment by jonathanolson** [comment]
> In Area Model Algebra I saw this problem still present if holding down the number picker.

It looks like that NumberPicker (https://github.com/phetsims/scenery-phet/blob/38ec061a5ea269c5a58b7dbf271a6e2ff38c53f5/js/NumberPicker.js) used ButtonListener using a version of DownUpListener (https://github.com/phetsims/scenery/blob/425923b10754e1fec8b05976ae1f25e96f7ec0d7/js/input/DownUpListener.js) that doesn't handle interruption.

@kathy-phet does this look like something that should also be patched?

**Comment by kathy-phet** [comment]
@jonathanolson - How much work/hours is it to patch this for Area Model?

**Comment by jonathanolson** [comment]
> @jonathanolson - How much work/hours is it to patch this for Area Model?

Probably not too much work, but I'm guessing this could be something that might happen in other sims.

**Comment by kathy-phet** [comment]
Let's see what bugs come up after all the testing is done, and then we can make a decision.

**Comment by kathy-phet** [comment]
@KatieWoe - Can you make an issue for the bug you found above?

**Comment by KatieWoe** [comment]
I can, but I'm not sure where to put it. @jonathanolson asked me to put it here. @jonathanolson what repo should an actual issue go in?

**Comment by KatieWoe** [comment]
It does also happen on other sims. Saw it in Balancing Chemical Equations

**Comment by kathy-phet** [comment]
@KatieWoe - If this is all the same problem, we need an issue where we can start documenting the occurrences of this bug, in which sims, and with which component(s) within those sims. Put it in scenery for now and JO can move it if he wants. Thanks.

**Comment by phet-steele** [comment]
@jonathanolson the latest public release of natural-selection is 1.3, but this issue has us testing 1.1. We should be patching 1.3, right?

**Comment by jonathanolson** [comment]
> We should be patching 1.3, right?

I verified earlier that natural-selection 1.3 is new enough where it shouldn't need any of the patches.

**Comment by KatieWoe** [comment]
I'm seeing something very strange. It doesn't seem problematic, so I'll only create an issue if you think it needs one @jonathanolson.
Expression exchange on Win 10 ChromeOS seems to behave like other browsers, in that the object keeps following the mouse after it has left the iframe. I was under the impression that this wasn't possible in chrome, which is why we were using the solution we were.
![chromefollowsout](https://user-images.githubusercontent.com/41024075/117182970-3b80e480-ad94-11eb-9502-966c19828951.gif)

**Comment by KatieWoe** [comment]
Not sure if we want this kind of thing fixed. If we do, let me know and I'll make an issue @jonathanolson 
![shouldfix](https://user-images.githubusercontent.com/41024075/117356592-275ee500-ae71-11eb-9be8-afc889632af3.gif)

**Comment by KatieWoe** [comment]
QA is done

**Comment by KatieWoe** [comment]
**No home screen:**
**Does:**
Balancing Act
Capacitor Lab Basics
Energy Forms and Changes
Graphing Quadratics
Gravity and Orbits
Natural Selection
**Doesn't:**
States of Matter (doesn't load, has console error)
States of Matter Basics (doesn't load, has console error)
**Don't know:**
Gravity Force Lab (doesn't load, has console error)
Molarity (doesn't load, has console error)
Resistance in a Wire

**Initial screen is 2:**
**Does:**
Balancing Act
Capacitor Lab Basics
Energy Forms and Changes
Graphing Quadratics
Gravity and Orbits
Natural Selection
States of Matter
States of Matter Basics
**Doesn't:**
**Don't know:**
Gravity Force Lab (Doesn't load, shows error in console)
Molarity (Doesn't load, shows error in console)
Resistance in a Wire

**Comment by jonathanolson** [comment]
Thanks! I'll hopefully have improved batches soon.

**Comment by jonathanolson** [comment]
> Expression exchange on Win 10 ChromeOS seems to behave like other browsers, in that the object keeps following the mouse after it has left the iframe. I was under the impression that this wasn't possible in chrome, which is why we were using the solution we were.

It wasn't using preventDefault for certain things, we now HAVE to do so to support things like a11y.

**Comment by kathy-phet** [comment]
https://github.com/phetsims/QA/issues/642#issuecomment-833811211  
We will not bother to maintenance this small studio issue. The instructional designer can just avoid it pretty easily.
