### ISSUE TITLE
Dev Test: Voicing and Preferences

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#645]
@terracoda @KatieWoe We are ready for a dev test of the Voicing feature with the Preferences dialog. Voicing is a new accessibility feature that is being developed and this is the first time it is going through quality assurance testing. We wrote up an introduction to the feature and what to look for while testing at 

https://github.com/phetsims/QA/blob/master/documentation/qa-book.md#voicing-and-interactive-highlights

Please read that section before any testing.

Voicing uses [Speech Synthesis](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis), so please test this sim on all of PhET's supported platforms to look for any differences with that technology.

If you have any questions about the feature while testing please let me know! For things that are confusing we will add to or modify the section in the QA book.

**Link to sim**: https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-preferences.4/phet/john-travoltage_en_phet.html

Please put any issues in find in https://github.com/phetsims/john-travoltage/issues

Assigning to @kathy-phet to prioritize and @KatieWoe.

**Comment by KatieWoe** [comment]
- [ ] Win 10 Chrome (Time = )
- [ ] Win 10 Firefox (Time = )
- [ ] MacOS Chrome (Time = )
- [ ] MacOS Safari (Time = )
- [ ] ChromeOS (Time = )
- [ ] iPadOS (Time = )

- [ ] Win 10 Chrome w/Jaws, no voicing (Time = )
- [ ] Win 10 Firefox w/NVDA, no voicing (Time = )
- [ ] MacOS Safari w/VO, no voicing (Time = )
- [ ] iPadOS w/VO, no voicing (Time = )

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe that sounds like an issue. The Preferences dialog should still be screen reader accessible when Voicing is off.

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Thanks very much QA team!
