### ISSUE TITLE
CCK: AC 1.0.0-dev.15 dev-lite test

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#646]
@kathy-phet requested preliminary dev testing on CCK-AC as part of https://github.com/phetsims/circuit-construction-kit-common/issues/692

I noticed @liam-mulhall already identified some issues on master, which I will reference below.

I sanity tested and published:
https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.15/phet/circuit-construction-kit-ac_en_phet.html

- [x] Tester 1 (Tester = KW , Platform = Mac and Dell Safari and Chrome, Time = 1 hrs{max 2 hours}
- [ ] Tester 2 (Tester = , Platform = , Time = {max 2 hours}

**Comment by KatieWoe** [comment]
- [] Tester 1 (Tester = , Platform = , Time = {max 2 hours}
- [] Tester 2 (Tester = , Platform = , Time = {max 2 hours}

**Comment by KatieWoe** [comment]
I noticed that the connection point to the inductor looks a bit off. @arouinfar should this be an issue?
<img width="457" alt="inductorodd" src="https://user-images.githubusercontent.com/41024075/117078922-03c45f00-acf8-11eb-871d-e10edac6288a.png">

**Comment by KatieWoe** [comment]
QA is done with lite test

**Comment by samreid** [comment]
Thanks, I'll close the issue and create a placeholder for a future dev test.
