### ISSUE TITLE
RC test Resistance in a Wire 1.3.0-phetiorc.4

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#65]
@emily-phet @terracoda @ariel-phet @phet-steele @zepumph, Resistance in a Wire 1.3.0-phetiorc.4 is ready for RC testing.

[Root Directory](https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.3.0-phetiorc.4)

A full RC should not be required, please verify that the following issues found in the previous RC have been resolved:
- [x] Keyboard navigation not enabled in this version
  - [x] https://github.com/phetsims/phet-io/issues/995 is not a problem for this sim
  - [x] https://github.com/phetsims/resistance-in-a-wire/issues/107 is not a problem for this sim
- [x] https://github.com/phetsims/resistance-in-a-wire/issues/110
- [x] https://github.com/phetsims/resistance-in-a-wire/issues/112
- [x] https://github.com/phetsims/resistance-in-a-wire/issues/108
- [x] https://github.com/phetsims/phet-io/issues/1236

If any new issues are found, please note them in https://github.com/phetsims/resistance-in-a-wire/issues and reference this issue.

Assigning to @ariel-phet to prioritize.

**Comment by ariel-phet** [comment]
@phet-steele this test would be ideal to finish today, but at worst by EOB Thursday.

**Comment by phet-steele** [comment]
@jessegreenberg @ariel-phet spot testing done.
