### ISSUE TITLE
Dev Test: pH Scale 1.5.0-dev.2

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#650]
@pixelzoom, @kathy-phet, @samreid, ph-scale/1.5.0-dev.2 is ready for dev testing. 

This will eventually be published for PhET-iO, but while PhET-iO API tracking common code is blocking publication, it would be good to hammer out any bugs in the PhET-iO wrappers and general feature set. This means that the majority of the testing here should be within PhET-iO wrappers to help make the publication process more seamless when it is time (current goal is 6/30 publication).

Document issues in https://github.com/phetsims/ph-scale/issues unless they seem obvious to be an issue with a wrapper/or studio, in which case phet-io-wrappers/ or studio/ directly is fine too. Please link to this
issue. 

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>PhET-iO Dev Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time = 3)
- [x] Latest iOS, Safari (Time = 5)
- [x] Windows 10, Chrome (Time = 8)
- [x] Windows 10, Firefox (Time = 7.5)
- [x] Latest Chrome OS, Chrome (Time = 4)

<h3>Focus and Special Instructions</h3>

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/ph-scale/1.5.0-dev.2/phet-io/)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by zepumph** [comment]
For right now, please ignore the Diff wrapper. I don't think that there are any old version that won't be buggy at this time. For example. That said, would you please create an issue in phet-io-wrappers about how when you use this URL, and try to compare breaking changes, it throws an error.

https://phet-dev.colorado.edu/html/ph-scale/1.5.0-dev.2/phet-io/wrappers/diff/?oldSimURL=https://phet-dev.colorado.edu/html/ph-scale/1.4.0-rc.1/phet-io/

Thanks!

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
@kathy-phet Since @zepumph is on vacation, can you clarify what the next steps are for this issue?

**Comment by samreid** [comment]
Now that the blocks-publication issues have settled down significantly, let's run another dev test.  Of the remaining blocks-publication issues: 2 don't apply to ph-scale: ( https://github.com/phetsims/scenery-phet/issues/540 and https://github.com/phetsims/phet-io/issues/1748), 3 are ready for QA testing in the next dev version and 2 are ready for review.  @pixelzoom can you take the lead on setting up 1.5.0-dev.3?  If it goes smoothly, it can go straight into RC.

**Comment by pixelzoom** [comment]
I have not received any direction from @kathy-phet to proceed with ph-scale testing.  So I currently have no plans to work on ph-scale, and I'm focusing on Fourier.

**Comment by pixelzoom** [comment]
The next step is to be decided in https://github.com/phetsims/QA/issues/654.

Closing.
