### ISSUE TITLE
PhET-IO: Test Compression and Computed States in Studio

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#651]
Copied from https://github.com/phetsims/studio/issues/216#issuecomment-848916591 on May 26 at 10:36am:

After co-review, this issue should be tested by QA.  The main changes for this issue are:

* We are now using a compression library to save and load the state.
* We are now trying to compute the state = initial state + changed state instead of always storing the initial state, changed state and full state.

Things to test:

0. Choose about 10 phet-io sims (including ph-scale, natural-selection and gravity-and-orbits), cycling across at least these platforms: iPad, Chromebook, Windows Edge and Mac Firefox and some Chrome
1. Launch a phet-io sim unbuilt in studio.  Customize the sim and try Preview Sim & Save.  Refresh studio and try "Load".  Does this work properly? On Save, does the console print "state could not be computed as initialState + changedState, storing." (bad) or "full state was computable as initialState + changedState, omitting." (good)?  For each sim, record whether it had the good or bad state output. Try with both "Production" and "Development" and make sure the "Development" outputs a lot of text to the console and "Production" does not.
2. Same tests as (1) but with a built sim.  Also, launch the save file by double clicking on it.  Does it correctly launch with your configuration?  Try launching the built save file with ?decompress.  Does it output a large decompressed configuration object to the console?

For a few cases (not necessarily all 10), manually delete some of the numbers from the compressed array, then try to load the save file in Studio or as a standalone (for built tests) and make sure it shows a sensible alert message.

UPDATE: Here are some sims to test:

energy-forms-and-changes
graphing-quadratics
gravity-and-orbits
gravity-force-lab
natural-selection
states-of-matter
ph-scale
beers-law-lab

For all sims listed in https://github.com/phetsims/perennial/blob/3848220a1f1400f87300521db8adcb3ea308acb5/data/phet-io, can we test if they have the good computed state?

**Comment by samreid** [comment]
There is a problem loading lodash and parsing the template string--not sure why it didn't show up on my side, but I'm looking into it.

**Comment by samreid** [comment]
@KatieWoe and I discovered this problem when running incognito on phettest:

```
lodash-4.17.4.min.js:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
phet-io.js:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
pako_inflate-2.0.3.min.js:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
lodash-4.17.4.min.js:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
natural-selection-custom-wrapper (57).html:70 Uncaught ReferenceError: phetio is not defined
    at file:///Users/samreid/Downloads/natural-selection-custom-wrapper%20(57).html:70:22
```

We think this is because it forgets authentication and returns a 401.  This is not a problem for published RC or production versions because their contrib files are public (unlike files served on phettest, which requires a password).

**Comment by KatieWoe** [comment]
- [ ] energy-forms-and-changes (Device and Platform = )
- [ ] graphing-quadratics (Device and Platform = )
- [ ] gravity-and-orbits (Device and Platform = )
- [ ] gravity-force-lab (Device and Platform = )
- [ ] natural-selection (Device and Platform = )
- [ ] states-of-matter (Device and Platform = )
- [ ] ph-scale (Device and Platform = )
- [ ] beers-law-lab (Device and Platform = )

**Comment by samreid** [comment]
It seems like this issue has enough coverage that it no longer needs to block publication.  We discovered that some sims have bad computed state on master, and hence we need to output the full state in addition to the initial and delta sometimes.

**Comment by samreid** [comment]
I'm not sure whether more work in this issue is warranted.  Perhaps we should close this and continue in #654?  @KatieWoe what do you recommend?

**Comment by KatieWoe** [comment]
I'm alright with that. We didn't get all of the sims we talked about, but if you think this enough, we can move forward.

**Comment by KatieWoe** [comment]
With States of Matter on Firefox I saw some console errors in studio, but it seemed to work.
<img width="957" alt="statemattererror" src="https://user-images.githubusercontent.com/41024075/120709262-da732c00-c479-11eb-8ec8-9db7ab301ef0.png">

**Comment by KatieWoe** [comment]
I seem to be having trouble opening saved htmls, whether they came from built or unbuilt versions.
<img width="1630" alt="Screen Shot 2021-06-03 at 4 40 44 PM" src="https://user-images.githubusercontent.com/41024075/120722115-6d1cc680-c48c-11eb-80f9-7992fc26fc5a.png">

**Comment by samreid** [comment]
Perhaps it is related to the phettest credentials problem we saw recently.  Perhaps test a dev version like the one in https://github.com/phetsims/QA/issues/654 ?

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
Thanks, closing.
