### ISSUE TITLE
RC Test: gravity-and-orbits/1.5.0-rc.1, to test phet-io infrastructure changes

### ISSUE THREAD

**Issue by samreid** [phetsims/qa#657]
Placeholder for upcoming RC test now that dev lite is complete in https://github.com/phetsims/QA/issues/654.

UPDATE:

@arouinfar @kathy-phet @KatieWoe, gravity-and-orbits/1.5.0-rc.1 is ready for RC testing. This is the first RC for the 
"upgradeable" batch of PhET-iO sims. Document issues in https://github.com/phetsims/gravity-and-orbits/issues/ and 
link to this issue.

Dev-lite testing completed in https://github.com/phetsims/QA/issues/660

Assigning to @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md)
for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if
there is a problem.

<h3>Focus and Special Instructions</h3>

The PhET brand simulation is hopefully not too different from the last PhET brand publication.  Most of the known changes were in PhET-iO.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-rc.1/phet/gravity-and-orbits_all_phet.html)**
- **[iFrame](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-rc.1/phet/gravity-and-orbits_all_iframe_phet.html)**
- **[XHTML](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-rc.1/phet/xhtml/gravity-and-orbits_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1U61MmzaK2YR1MvtvBo1vYZ4zkEpwNroxhbtdhOgNEPs/edit#gid=1919873480)**

<hr>

</details>

<details>
<summary><b>PhET-iO RC Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.
- For an update or maintenance release please check the backwards compatibility of the playback wrapper.
[Here's the link to the previous wrapper.](link)
- Load the login wrapper just to make sure it works. Do so by adding this link from the sim deployed root: 
  ```
  /wrappers/login/?wrapper=record&validationRule=validateDigits&&numberOfDigits=5&promptText=ENTER_A_5_DIGIT_NUMBER
  ```   
  Further instructions in QA Book
- Conduct a recording test to Metacog, further instructions in the QA Book. Do this for iPadOS + Safari and one other random platform.
- Conduct a memory test on the stand alone sim wrapper (rc.1).
- Test one platform combination with `?phetioDebug` on the Studio and State wrapper.
- If Pan/Zoom is supported, make sure that it works when set with PhET-iO State.
- If filled in by issue creator, please test the diff wrapper against https://phet-io.colorado.edu/sims/gravity-and-orbits/1.4/
- Test that the sim works offline:
  * Go to https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-rc.1/phet-io/gravity-and-orbits-phet-io-1.5.0-rc.1.zip
  * download it
  * unzip it to a spot locally
  * Open `index.html` by double clicking it on your desktop or in a finder-view.
  * It should look like the standalone version of the sim in PhET-iO brand.

<h3>Focus and Special Instructions</h3>

This test is primarily to regression test recent changes to PhET-iO, particularly around studio and save/load and API files.

<h3>Additional checks</h3>

- [x] Please use the diff wrapper to compare against prior version: https://phet-io.colorado.edu/sims/gravity-and-orbits/1.4/

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-rc.1/phet-io/)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1MiLr45_vxmzBlu88343uG3OV-_Pb7qRBAMRTIZKVPhE/edit#gid=480995298)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by samreid** [comment]
Please be aware of https://github.com/phetsims/phet-io-wrappers/issues/405#issuecomment-844208633 which may impact how the diff wrapper can be tested.

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
I opened a milestone for tracking work that should be done for this release (in this branch with cherry picks).  Closing and will continue in https://github.com/phetsims/gravity-and-orbits/milestone/4.  I'll also create a new note to indicate upcoming testing for rc.2.

**Comment by samreid** [comment]
I opened a milestone for tracking work that should be done for this release (in this branch with cherry picks).  Closing and will continue in https://github.com/phetsims/gravity-and-orbits/milestone/4.  I'll also create a new note to indicate upcoming testing for rc.2.

**Comment by pixelzoom** [comment]
Reopening.  There are still problems being found with this RC, like https://github.com/phetsims/joist/issues/725.

**Comment by samreid** [comment]
I created sim-specific issues for the 1.5 milestone for the new issues as appropriate.  Closing, but please let me know if further issues are discovered.
