### ISSUE TITLE
Submit translations on Ox-Dev

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/qa#658]
## Background

In https://github.com/phetsims/rosetta/issues/262, we discussed an issue where the translations of certain translators weren't being correctly submitted. We're not sure why it's happening for some translators and not others. We think it might be platform-specific.

## Before the Test

I need to:

- [x] make sure phet-server-dev (Ox-Dev) is running the same version of Rosetta as phet-server,
  * `d37d0da36df42a81cb5dc2020425c12342261af4` (phet-server-dev)
  * `d37d0da36df42a81cb5dc2020425c12342261af4` (phet-server)
- [x] make sure phet-server-dev/Rosetta's Babel branch is the `tests` branch, and
- [x] let QA know when this test is ready.

## Instructions for QA

For those of you with Windows 10 (preferably version 2004) and Chrome (latest), please do the following:

1. Go to https://ox-dev.colorado.edu/translate/.
2. Log in with one of the QA translator accounts. (If you have access to level 3 credentials you should be able to do this. If you have questions, ping me or @KatieWoe.)
3. Change as many strings as you want (they can be anything, none of this will be public) and submit a translation for the following:

### Build a Molecule

- [x] locale = ca (Catalan) Day/time = 7/8/2021 2:53 pm
- [x] locale = ko (Korean) Day/time = 7/12/2021 10:33 am

### Collision Lab

- [x] locale = ca (Catalan)
- [x] locale = ko (Korean)
- [x] day/time = 7/12/2021 9:48 am

### Energy Skate Park

- [x] locale = ca (Catalan)
- [x] locale = ko (Korean)
- [x] day/time = 7/12/2021 10:04 am

### Number Line: Integers

- [x] locale = ca (Catalan)
- [x] locale = ko (Korean)
- [x] day/time = 7/12/2021 10:17 am

### Number Line: Operations

- [x] locale = ca (Catalan)
- [x] locale = ko (Korean)
- [x] day/time = 7/12/2021 10:26 am

**Comment by KatieWoe** [comment]
@liam-mulhall I believe this is done
