### ISSUE TITLE
Dev-lite test: Natural Selection 1.4.0-dev.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/QA#659]
@amanda-phet, @kathy-phet, @KatieWoe, @samreid natural-selection/1.4.0-dev.1 is ready for light dev testing. Document issues in https://github.com/phetsims/natural-selection/issues and link to this issue.

This test is primarily to regression test recent changes to PhET-iO.  Please consult with @samreid about what specifically needs to be tested.

Links:
[1.4.0-dev.1, brand=phet-io](https://phet-dev.colorado.edu/html/natural-selection/1.4.0-dev.1/phet-io/)
[1.4.0-dev.1, brand=phet](https://phet-dev.colorado.edu/html/natural-selection/1.4.0-dev.1/phet/natural-selection_en_phet.html)

Assigning @kathy-phet and @KatieWoe for prioritization.

This test is for phet-io. Platform coverage is not important for this test. Testing should be around 4 hours max.

- [x] Tester 1 (Tester = Clifford, Platform = Firefox 89.0.1, Time = 2 {max 2 hours}
- [x] Tester 2 (Tester = Logan , Platform = Chrome 91.0.4472.101, Time = 1 {max 2 hours}
- [x] Tester 3 (Tester = LM , Platform = macOS + Chrome 91.0.4472.101, Time = 1 {max 2 hours}

What to Test
- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers

**Comment by KatieWoe** [comment]
QA is done. Testing mostly found things fixed for GAO. Testing was relatively light for dev-lite

**Comment by pixelzoom** [comment]
Thanks @KatieWoe.

No issues to address, so closing.
