### ISSUE TITLE
Dev-lite test: gravity-and-orbits/1.5.0-dev.8

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#660]
@arouinfar, @kathy-phet, @KatieWoe gravity-and-orbits/1.5.0-dev.8 is ready for light dev testing. Document issues in https://github.com/phetsims/gravity-and-orbits/issues and link to this issue.

This test is primarily to regression test recent changes to PhET-iO, particularly around studio and save/load and API files.  Most of the testing time should be spent in phet-io, not in the phet-brand sim.

Links:
[1.5.0-dev.8, brand=phet](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-dev.8/phet/gravity-and-orbits_en_phet.html)
[1.5.0-dev.8, brand=phet-io](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-dev.8/phet-io/)

Assigning @kathy-phet and @KatieWoe for prioritization.  Note that we had another dev-lite test for gravity and orbits about 2 weeks ago in https://github.com/phetsims/QA/issues/654.

This test is for phet-io. Platform coverage is not important for this test, but I recommend at least one platform be Firefox. Testing should be around 4 hours max.

- [x] Tester 1 (Tester = Clifford, Platform = Firefox 89.0.1, Time = 2{max 2 hours}
- [x] Tester 2 (Tester = Brooklyn , Platform = Chrome , Time = 1{max 2 hours}

What to Test
- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- PhET-iO features

Please verify the issues linked below, close if they seem OK:

**Comment by samreid** [comment]
I published dev.8 with a fix for https://github.com/phetsims/studio/issues/226, remaining testing can be done in dev.8.

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
In discussion with @KatieWoe, we decided to wait until NS Dev Lite #659 is complete before making a GAO RC.  So I'll close this issue and open a placeholder issue or card.
