### ISSUE TITLE
Conduct a memory test on Number Play

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/QA#661]
It would be nice to do a quick memory test on Number Play to see if there are any memory leaks. 

https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.20/phet/number-play_en_phet.html

**Comment by phet-steele** [comment]
@amanda-phet after just one minute of `?fuzzMouse`, I got a heap snapshot of about 220 mb. I think this is way above our memory limit, right? Tested this on Win 10 Chrome

**Comment by KatieWoe** [comment]
Yes. I just did a test until the panel crashed. In general, the goal is to keep memory under 100 MB, and if it does go above it should at least be steady.
Start 21.6 MB
1 min 182
2 min 297
3 min 425
4 min memory panel crashes

**Comment by amanda-phet** [comment]
Thank you @phet-steele and @KatieWoe !
