### ISSUE TITLE
Dev test: pH Scale: Basics 1.5.0-dev.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#666]
@KatieWoe, @kathy-phet, @arouinfar, ph-scale-basics/1.5.0-dev.1 is ready for light dev testing. Because this sim is essentially the first screen from ph-scale, document issues in https://github.com/phetsims/ph-scale/issues and link to this issue.

Assigning @kathy-phet and @KatieWoe for prioritization.

Please do [Dev test: pH Scale 1.5.0-dev.3](https://github.com/phetsims/qa/issues/665) before doing this issue. This sim is identical to the first screen in pH Scale, with one difference: the beaker does not automatically fill with solute when the sim starts.  So after testing pH Scale 1.5.0-dev.3, you can quickly spot check this dev version.  Also spend do a little PhET-iO spot checking, to verify that nothing big/obvious is broken.

Links:
* [1.5.0-dev.1, brand=phet](https://phet-dev.colorado.edu/html/ph-scale-basics/1.5.0-dev.1/phet/ph-scale-basics_all_phet.html)
* [1.5.0-dev.1, brand=phet-io](https://phet-dev.colorado.edu/html/ph-scale-basics/1.5.0-dev.1/phet-io/)

Platform coverage is not important for this test. Testing should be around 4 hours max.

- [x] Tester 1 (Tester = Clifford, Platform = Google Chrome Version 91.0.4472.124, Time = 2 {max 2 hours}
- [x] Tester 2 (Tester = Clifford, Platform = Firefox 89.0.2, Time = 2 {max 2 hours}

What to Test
- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
Thanks @KatieWoe and QA team. 

Assigning to @kathy-phet and @arouinfar for instructions on next steps.

**Comment by arouinfar** [comment]
Looks like there aren't any issues to address from the dev test and there aren't any relevant publication-blocking issues, so we can proceed with RC testing.

**Comment by pixelzoom** [comment]
I'm proceeding with a full RC test, per @arouinfar.  See https://github.com/phetsims/qa/issues/665#issuecomment-879283222.

**Comment by pixelzoom** [comment]
1.5.0-rc.1 has been published. Closing.
