### ISSUE TITLE
Dev test: Geometric Optics 1.0.0-dev.1

### ISSUE THREAD

**Issue by sarchang** [phetsims/qa#667]
geometric-optics/1.0.0-dev.1 is ready for dev testing. Add issues in https://github.com/phetsims/geometric-optics/issues as they arise.

Here's the link: [geometric-optics/1.0.0-dev.1](https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-dev.1/phet/geometric-optics_en_phet.html)

Hopefully the QA team can work on this a bit before the end of the week to find any critical bugs because I will be using this version to conduct interviews next week. Thanks!

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>Focus and Special Instructions</h3>

<h3>General Dev Test Platforms</h3>

- [ ] Latest macOS, Safari (Time = )
- [x] Windows 10, Chrome (Time = 10 hrs)
- [ ] Windows 10, Firefox (Time = 2hrs)
- [ ] Latest iOS, Safari (Time = )

Light testing, or optionally skip if time crunch: 
- [ ] Latest macOS, Chrome (Time = )
- [ ] Latest Chrome OS, Chrome (Time = )

**Comment by KatieWoe** [comment]
From Slack:
>Martin Veillette:house_with_garden:  6:30 AM
Thanks @KatieWoe for finding all the bugs. You can stop for now. We will release a new dev version next week for you to test.

Ending test here. @veillette please close this issue when ready.

**Comment by veillette** [comment]
Thanks @KatieWoe and your team for all the work.
Closing
