### ISSUE TITLE
RC Spot Check - Gravity and Orbits 1.5.0-rc.2

### ISSUE THREAD

**Issue by samreid** [phetsims/qa#671]
Gravity and Orbits 1.5.0-rc.2 has had issues fixed since RC.1 and is ready for QA testing.  The links produced by the deploy task are:

https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-rc.2/phet/gravity-and-orbits_en_phet.html
https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.0-rc.2/phet-io/

The issues to be verified are listed in https://github.com/phetsims/gravity-and-orbits/milestone/4.  Feel free to copy them here if you wish.  There are currently 11 open issues.  Each issue describes how it can be verified.  Most verifications just require 1 platform.  Aside from verifying the milestone issues, please just test for 5 minutes or so to see if anything else has been disturbed.

UPDATE: As mentioned in https://github.com/phetsims/gravity-and-orbits/issues/393#issuecomment-879335836

> Thanks!  For issues like these, I recommend closing when they have been confirmed fixed in RC.2.  Then when the milestone list https://github.com/phetsims/gravity-and-orbits/milestone/4 is empty, we are ready to publish.  Sound OK?

Issues:
- [x] https://github.com/phetsims/gravity-and-orbits/issues/400
- [x] https://github.com/phetsims/gravity-and-orbits/issues/402
- [x] https://github.com/phetsims/gravity-and-orbits/issues/398
- [x] https://github.com/phetsims/gravity-and-orbits/issues/394
- [x] https://github.com/phetsims/gravity-and-orbits/issues/395
- [x] https://github.com/phetsims/gravity-and-orbits/issues/391
- [x] https://github.com/phetsims/gravity-and-orbits/issues/389
- [x] https://github.com/phetsims/gravity-and-orbits/issues/393
- [x] https://github.com/phetsims/gravity-and-orbits/issues/399
- [x] https://github.com/phetsims/gravity-and-orbits/issues/403
- [x] https://github.com/phetsims/gravity-and-orbits/issues/404

**Comment by KatieWoe** [comment]
Looks like qa is done with spot check.

**Comment by samreid** [comment]
1.5 has been published, closing.
