### ISSUE TITLE
Dev test - Fourier: Making Waves 1.0.0-dev.#

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#673]
For https://github.com/phetsims/fourier-making-waves/issues/102.

_NOTE: Publication of this dev version is deferred. When QA is ready to begin testing, notify @pixelzoom and he will publish._

@KatieWoe, @arouinfar, @kathy-phet, fourier-making-waves/1.0.0-dev.# is ready for light dev testing. 
Document issues in https://github.com/phetsims/fourier-making-waves/issues and link to this issue. 

[Link](linkhere)

Assigning @kathy-phet and @KatieWoe for prioritization.

This test is for (select all that apply) [general, a11y, and phet-io]. Platform coverage is not important for this test. Testing should be around 4 hours max.

- [ ] Tester 1 (Tester = , Platform = , Time = {max 2 hours}
- [ ] Tester 2 (Tester = , Platform = , Time = {max 2 hours}

What to Test
- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers

**Comment by kathy-phet** [comment]
Removed from the QA pipeline project. Marked as deferred.

**Comment by pixelzoom** [comment]
Closing this issue. I'll create a new one when it's time to dev test.
