### ISSUE TITLE
Dev test: Molecule Polarity 1.2.0-dev.3

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#680]
@KatieWoe, @kathy-phet, @arouinfar molecule-polarity/1.2.0-dev.3 is ready for dev testing.

This is a full dev test of PhET and PhET-iO brands.

Document issues in https://github.com/phetsims/molecule-polarity/issues and link to this issue.

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time = 3hr )
- [x] Windows 10, Chrome (Time = 2hr)
- [x] Windows 10, Firefox (Time = 2.5 hr)
- [x] Latest iOS, Safari (Time = 4 hr)

Light testing, or optionally skip if time crunch: 
- [ ] Latest macOS, Chrome (Time = )
- [ ] Latest Chrome OS, Chrome (Time = 2hr)

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/molecule-polarity/1.2.0-dev.3/phet/molecule-polarity_all_phet.html)**

<hr>

</details>

<details>
<summary><b>PhET-iO Dev Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time = 4hrs )
- [x] Latest iOS, Safari (Time = 1 hr)
- [x] Windows 10, Chrome (Time = 9 hr)
- [x] Windows 10, Firefox (Time = 6 hr)
- [ ] Latest Chrome OS, Chrome (Time = 4hr)

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/molecule-polarity/1.2.0-dev.3/phet-io/)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Calling an end to QA

**Comment by pixelzoom** [comment]
Thanks @KatieWoe and QA team.  I'll leave this issue open until issues have been addressed and the 1.2 release branch has been created.

**Comment by pixelzoom** [comment]
All issues have been addressed. 1.2 release branch has been created. Closing.
