### ISSUE TITLE
Dev Test: Website Sim Pages

### ISSUE THREAD

**Issue by mattpen** [phetsims/qa#682]
@amanda-phet, @chrisklus, @oliver-phet, @arouinfar, @kathy-phet, @mattpen The website sim pages are ready for dev testing. We are hoping to have this published by September 1. Document issues in https://github.com/phetsims/website-meteor/issues and link to this issue. [If the test is delayed until QA is more open, state that here.]

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button and link.
- Try to break the sim pages.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.

<h3>Focus and Special Instructions</h3>

- The pages that should be tested are the simulation info pages (available at https://ox-dev.colorado.edu/en/simulations/filter).  The filter page itself does not need to be tested.
- Check at least one HTML sim, one Java sim, one Flash sim, and one Cheerpj sim.
- Check HTML sim pages for sims with 1, 2, and 3 alternate screenshots.
- Check pages for sims with and without inclusive features.
- Check all tabs on each page (About, Teaching Resources, Activities, Translations, Credits)
- The header and footer (starting with the social media icons at the bottom of the page) do **NOT** need to be tested.
- Test the pages both while signed in and out to make sure the sign-in blockers are working as expected on the teaching resources tab.
- Test the pages in at least 3 locales, one of which should be RTL (https://ox-dev.colorado.edu/ar_SA/simulations/filter)

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time = 4hrs )
- [x] Windows 10, Chrome (Time = 4 hrs)
- [x] Windows 10, Firefox (Time = 1.25)
- [x] Latest iOS (phone size), Safari (Time = 1.75 )

Light testing, or optionally skip if time crunch: 
- [x] Latest macOS, Chrome (Time = 1hr)
- [x] Latest Chrome OS, Chrome (Time = .5)
- [x] Latest Android (phone), Chrome (Time = 2 hr)
- [x] Latest iOS (tablet size), Safari (Time = .75)

<h3>Issues to Verify</h3>

- [x] [Translated sim flow](https://github.com/phetsims/website/issues/1215)
- [x] [Legacy routing changes](https://github.com/phetsims/website-meteor/issues/260)

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

Test any sims linked from https://ox-dev.colorado.edu/en/simulations/filter (or other locales)

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) Dev Test</b></summary>

<h3>What to Test</h3>

- Make sure all text can be accessed with screen readers
- Make sure all buttons and links can be accessed with keyboard nav and screen readers
- Make sure all non-decorative images have appropriate alt text and decorative images have null alt text.

<h3>Link(s)</h3>

Same as above.

<h3>Screen Readers</h3>

These web pages support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to screen readers. If you simply need a refresher on screen readers, please consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have all of the information you need as well as a link to a screen reader tutorial made by Jesse.

<h3>Platforms and Screen Readers to Be Tested</h3>

- [x] Windows 10 + Latest Chrome + Latest JAWS
- [x] Windows 10 + Latest Firefox + Latest NVDA
- [x] macOS + Safari + VoiceOver
- [x] iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in [this Google Document](https://drive.google.com/open?id=12kTs-g-iKEIH1dyG7Q41_W_oNL4gUKbkW-IQgZjMUBw). If you find a screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

These web pages support keyboard navigation. Please make sure they work as intended on all platforms with and without a screen reader.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by mattpen** [comment]
There were several issues discovered while preparing for the dev test that need to be addressed before progressing with a test.  Let's hold off on the test until I get these cleaned up.

**Comment by mattpen** [comment]
I've done a brief evaluation and fixed some obvious bugs in the RTL, windows, keyboard nav, and VoiceOver use cases.  I'll do a quick check of the sim pages with NVDA and JAWS tonight and then the dev test can proceed starting tomorrow (8/5).

**Comment by mattpen** [comment]
I've reviewed with NVDA and Jaws as well (fixing some major navigation bugs).  @kathy-phet @KatieWoe this should be ready for the QA Dev test now!

**Comment by KatieWoe** [comment]
Calling QA here

**Comment by mattpen** [comment]
@KatieWoe - Can someone from QA please run this test on Chrome OS and iPad?  It looks like those were left out, but I don't understand why.

**Comment by KatieWoe** [comment]
Both look ok
