### ISSUE TITLE
Test master version of Balancing Act on multiple platforms, check for strobing text

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#686]
The parent issue for this is https://github.com/phetsims/balancing-act/issues/16.  In that issue, which is from a long time ago, I fixed a problem where rotating text looked bad on some platforms.  The fix was to "rasterize" the text, which means to turn it into an image before displaying it.  @samreid recently came across some items marked as TODO in the code about potentially removing the rasterized text in the future when browser support for rotating text improves.  Well, the future is here, so I thought I'd try using regular, non-rasterized text to see if it works well now.  I made the change, then tested on Chrome and Firefox, and it looked fine.

QA team: Please test the master version of Balancing Act on multiple platforms, comparing it against the currently published version, and looking for any "strobing" with rotating text, which basically means it jumps around and looks bad.  I've found the best way to test this is to set up a situation with lots of text that can rotate and then move things around so that the motion of the text is relatively slow.  I've got a screenshot of such a situation below, where if one moves the 5 kg brick around, the plank rotates fairly slowly.

Rotating text can be found on the labels for things that can be put on the plank, on the ruler, and on the "Marks".

This testing should be pretty focused on the rotating text, please don't spend much time on anything else.

![image](https://user-images.githubusercontent.com/3082831/127917026-960ec75b-4185-48a7-ac59-17cedd2615c2.png)

Platforms:

- [x] Win 10 Chrome
- [x] Win 10 Firefox
- [x] MacOS 11 Safari
- [x] MacOS 11 Chrome
- [x] ChromeOS
- [x] iPadOS 14

**Comment by KatieWoe** [comment]
On Win 10 the text overall looks better, but I didn't see any jittering in the published sim itself.

**Comment by Nancy-Salpepi** [comment]
The text itself looks good with Mac 11 chrome/safari. I noticed some movement in the top portion and bottom border of the ruler itself when using Mac11 + safari--almost like a wave moving through. 

https://drive.google.com/file/d/1IqMX4D0Im8OoWv3-oILWETZoUCKCPEdA/view?usp=sharing

**Comment by samreid** [comment]
It looks like the wave is caused by "aliasing", for example, see the top image on the Bresenham antialias Algorithm page:

https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm

I'm not sure what can be done about it.

**Comment by jbphet** [comment]
@KatieWoe said:

> ...I didn't see any jittering in the published sim itself.

You won't.  It had the workaround in place, i.e. the rasterized text, so the jittering doesn't occur there.  You may, however, notice that the new text is slightly more crisp than the text in the published sim, especially on high-resolution displays.

**Comment by KatieWoe** [comment]
Text jiggles around on ChromeOS on master

**Comment by KatieWoe** [comment]
QA is done

**Comment by jbphet** [comment]
> Text jiggles around on ChromeOS on master

@KatieWoe - In your opinion, is this bad enough versus the published version that I should revert back to the workaround (the rasterized text)?

**Comment by KatieWoe** [comment]
I'm really not sure. It was noticeable, but I probably wouldn't have made note unless it was what I was looking for. I'm not sure how bad it would have to be to revert.

**Comment by samreid** [comment]
Would it help to record a video on ChromeOS?

**Comment by jbphet** [comment]
@KatieWoe said:

> I'm not sure how bad it would have to be to revert.

Not bad, I'd just roll back to a point before I removed it.  Of course, I'd prefer not to, and it would be nice to get rid of the workaround, but not if it has a noticeable negative impact on the user experience.

@samreid said:
 
> Would it help to record a video of the ChromeOS behavior?

Yes.  Either that or, if it's possible to set up a Zoom call from the ChromeOS device, we could set up a time and do that.  Or, if @KatieWoe is comfortable making a recommendation either way, that would be cool too.  If it falls to me to make a decision, I'll need to see what it looks like.

**Comment by KatieWoe** [comment]
Here are some images from the chrome book. It is up to date, but it is one of our lower performing devices.

https://user-images.githubusercontent.com/41024075/128395836-f60b7bc3-0d38-42ef-b5a1-ed42f0f9c720.MOV

![Screenshot 2021-08-05 11 24 00 AM](https://user-images.githubusercontent.com/41024075/128395842-2d9bcbc5-462a-4f73-a274-ee5575ada32d.png)

**Comment by jbphet** [comment]
My conclusion after reading through the comments and looking at the recordings and trying it out myself is that the strobing and aliasing still exist, and I should leave the workaround in place, at least for now.  Thanks to the QA team for testing this.  Closing.
