### ISSUE TITLE
Dev test: Balloons and Static Electricity 1.5.0-dev.35

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#689]
Dev test - Balloons and Static Electricity 1.5.0-dev.35

@emily-phet and @kathy-phet - balloons-and-static-electricity/1.0.0-dev.35 is ready for dev testing. Document issues in https://github.com/phetsims/balloons-and-static-electricity/issues and link to this issue.

This dev test is in preparation for redeploying this sim from master with a host of new features, such as sound, keyboard nav, pan & zoom, the preferences menu, and some improvements to description.  The sim should be tested on multiple platforms and, if all looks good, this will move into RC testing.

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>Focus and Special Instructions</h3>

This sim is about to be re-released from master, and the main new features are:
- sound
- pan and zoom
- preferences menu

There have also been some improvements to how descriptions work, and the mobile a11y is considered to be in a "prototype state".

Please focus the testing on these features with the appropriate level of scrutiny.  The main three features listed above should be tested pretty thoroughly.  Description and mobile a11y should be lightly tested and only really bad issues should be logged, since these are known to be partial implementations.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time = 3 hrs)
- [x] Windows 10, Chrome (Time = 3 hrs)
- [x] Windows 10, Firefox (Time = 2 hrs)
- [x] Latest iOS, Safari (Time = 2 hrs)

Light testing, or optionally skip if time crunch:
- [x] Latest macOS, Chrome (Time = 2 hrs)
- [x] Latest Chrome OS, Chrome (Time = 1 hrs)

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.35/phet/balloons-and-static-electricity_all_phet.html)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) Dev Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the accessibility-related feature that is being tested doesn't negatively affect the sim in any way. Here is a list of features to supported in this test: 
    - Alternative Input
    - Interactive Description
    - Sound and Sonification
    - Pan and Zoom
- Load the a11y view and make sure that interacting with all elements in the simulation updates the appropriate descriptions in the PDOM.

<h3>Focus and Special Instructions</h3>

The focus should be on basic operation of the sim to make sure that no regressions were introduced, then on:
- sound
- pan & zoom
- preferences menu
- alternative input

Description should also be tested, and issues should be logged, but note that the developers are aware that there are some problems here and will likely only fix the most egregious issues.

<h3>Issues to Verify</h3>

- [x] [Implement sound design](https://github.com/phetsims/balloons-and-static-electricity/issues/479)

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[a11y View](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.35/phet/balloons-and-static-electricity_a11y_view.html)**
- **[Simulation](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.35/phet/balloons-and-static-electricity_all_phet.html)**

<h3>Screen Readers</h3>

This sim supports screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to them.
If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have all of
the information you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view
before opening the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as
intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- [x] Windows 10 + Latest Chrome + Latest JAWS (Time = .25 {broken})
- [x] Windows 10 + Latest Firefox + Latest NVDA (Time = 3.5)
- [x] macOS + Safari + VoiceOver (Time = 3 hr)
- [x] iOS + Safari + VoiceOver (Time = )

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[this Google Document](https://drive.google.com/open?id=12kTs-g-iKEIH1dyG7Q41_W_oNL4gUKbkW-IQgZjMUBw). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<h3>Final Requests</h3>

- Please note that it is _not_ necessary to test Talkback on this release.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Memory test results:
<img width="362" alt="mem" src="https://user-images.githubusercontent.com/41024075/129981480-046af6ed-f0c0-4b04-94c5-ed50d8bd52c3.png">

**Comment by KatieWoe** [comment]
From Jesse:
>Well I don’t think BASE is currently expected to work with iOS VO. When we publish it next we will not mark it as supporting mobile accessibility. But still curious to know what isn’t working well.

**Comment by KatieWoe** [comment]
Stopping Jaws testing due to https://github.com/phetsims/balloons-and-static-electricity/issues/532. Can't test much well while it is an issue.

**Comment by KatieWoe** [comment]
Calling QA here. @stemilymill is finishing NVDA, but says it looks ok so far

**Comment by jbphet** [comment]
Thanks QA team!  I'll close this issue and we will work on addressing the issues listed above.
