### ISSUE TITLE
RC test: Capacitor Lab Basics: 1.5.0-rc.2

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#69]
@arouinfar and @ariel-phet, Capacitor Lab: Basics 1.5.0-rc.2 is ready for RC testing (minor spot-checks for issues only).

**[Link to sim](https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-rc.2/capacitor-lab-basics_en.html)**

**[Link to iFrame](https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-rc.2/capacitor-lab-basics_en-iframe.html)**

**Issues to Verify**
(*all should be marked "status:fixed-pending-testing"*)  
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/capacitor-lab-basics/issues/214
- [x] https://github.com/phetsims/capacitor-lab-basics/issues/212

If any new issues are found, please note them in https://github.com/phetsims/capacitor-lab-basics/issues and reference this issue.

**Comment by ariel-phet** [comment]
On par with #66

**Comment by phet-steele** [comment]
![greenlight](https://user-images.githubusercontent.com/5863899/32793777-1fb34d18-c924-11e7-9b0d-4899e365ba61.png)

**Comment by jonathanolson** [comment]
Thanks!
