### ISSUE TITLE
How does PhET test performance on Chromebooks?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#694]
A question about Chromebooks, performance, and QA testing…. Mainly for @kathy and @KatieWoe, but anyone else feel free to chime in.   

I'm going to purchase a Chromebook for testing, and (on Slack) I asked what schools are using. @kathy-phet replied with BVSD's "Chromebook Specifications" document.  That document specifies devices for each graduating class of students, and the devices are upgraded for each graduating class. For example, the High School class of 2025 has a more powerful machine than the class of 2021.  

This made me wonder about how PhET is testing sim performance on Chromebooks. Performance of Fourier definitely needs to be tuned/optimized for Chromebook, and I'll be doing that immediately.  But I’d like to know that I’m optimizing for a realistic reference platform. And I’d like to know what that reference platform is so that I can purchase a similar test device. 

So some questions:

(1) How is QA determining if sim performance is acceptable on Chromebooks? 

(2) What is PhET's reference device for Chromebook performance? 

(3) Does PhET adjust the reference device each year (purchase newer Chromebooks), to account for the fact that student are upgrading?  Are you regularly raising the performance bar, or are you still expecting sims  to run smoothly on an old devices?

High priority because I'm about to start optimizing Fourier.

**Comment by KatieWoe** [comment]
Q1: It varies a bit by sim, but we have three different level. If there are no performance issues and the sim runs smoothly with no lag it is good. If there is some lag, but it doesn't interfere with usability or learning, it is considered ok and noted in the test matrix, but we don't make an issue. If the lag is bad enough that it impedes usage of the sim or the sim is crashing, it is considered poor and an issue is made. Different sims have different lag threshoholds before they become unusable (moving parts like ESP make sims unusable before sims like Numberline, where you put an object down and the sim stays in one state)

Q2: We have a number of chromebooks, but the lowest performing, still updating, one is an ASUS C300S

Q3: Cromebooks will stop being supported by Google after ~5 years, although sometimes they last longer. When a chromebook stops updating, that is when we get an upgraded device.

**Comment by pixelzoom** [comment]
Thanks @KatieWoe, that's very helpful.  

Closing.
