### ISSUE TITLE
Dev-lite Test: Number Play 1.0.0-dev.22

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/qa#696]
@chrisklus , @kathy-phet , number-play/1.0.0-dev.22 is ready for light dev testing. Document issues in https://github.com/phetsims/number-play/issues and link to this issue. 

One known bug is in https://github.com/phetsims/number-play/issues/39 that would be good to learn more about. 

https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.22/phet/number-play_en_phet.html?screens=1,2,3 (just the first three screens at this time) 

Assigning @kathy-phet and @KatieWoe for prioritization.

This test is for general. Platform coverage is not important for this test, but iPads should be looked at. Testing should be around 4 hours max.

- [x] Tester 1 (Tester = NS, Platform = Mac11 + chrome, Time =  2hrs {max 2 hours}
- [x] Tester 2 (Tester = KW, Platform = iPad + Win 10, Time = 1{max 2 hours}

What to Test
- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers

**Comment by amanda-phet** [comment]
Other things to note: 
- Backgrounds/controls of the paper ones and the objects are in flux, so try not to focus on that design at this time
- The size of the object accordion box can change in some situations, and is going to be fixed when the backgrounds change

**Comment by KatieWoe** [comment]
QA is done

**Comment by amanda-phet** [comment]
Thanks everyone!
