### ISSUE TITLE
Android App: Test app in low and no network conditions

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#7]
@phet-steele - The latest android beta version on the Play Store has fixes for exceptions raised during updates in poor network conditions.  Could you please schedule a test to verify that the app works in low and no connectivity situations?

**Comment by phet-steele** [comment]
Current beta is working well in these conditions. Will check the soon to be new beta, too, then close.

**Comment by phet-steele** [comment]
Beta 17 (I think?) is working great!
