### ISSUE TITLE
QA test for registration/edit-profile/school-admin pages

### ISSUE THREAD

**Issue by mattpen** [phetsims/QA#70]
@phet-steele - Can you please do a QA test on the new pages for the registration changes.  These pages should be mobile friendly.

These are the pages that need to be tested.
https://ox-dev.colorado.edu/en/register (Need to be signed out)
https://ox-dev.colorado.edu/en/edit-profile (Need to be signed in)
https://ox-dev.colorado.edu/admin/schools (Need to be signed in as admin)
https://ox-dev.colorado.edu/admin/organizations (Need to be signed in as admin)

Can you please open new issues in https://github.com/phetsims/website-meteor/issues as needed and attach them here.

**Comment by ariel-phet** [comment]
on par with #68

**Comment by phet-steele** [comment]
@mattpen please remove the on-hold label when ox-dev is stable again so we know when we can continue testing.

**Comment by mattpen** [comment]
@phet-steele - ox-dev is now stable again, please resume testing.

**Comment by mattpen** [comment]
@phet-steele - Is QA complete for this task?  There are currently no open issues.

**Comment by phet-steele** [comment]
> Is QA complete for this task?

You bet!
