### ISSUE TITLE
Website: light regression testing

### ISSUE THREAD

**Issue by mattpen** [phetsims/qa#703]
Let's conduct a brief test of all website pages, to make sure there are no regressions due to the major deploy of the sim pages.  An example of an issue that popped up due to regression is the lack of triangles in the old style accordion content: https://github.com/phetsims/website/issues/1244. Look for bad layout, missing images, text or icons, and other strangeness.

Open any issues found in the website repo https://github.com/phetsims/website/issues, link to this issue, and assign to @mattpen.

Assigning @kathy-phet and @KatieWoe for prioritization.

What to Test
- Test the pages at each link in the main navigation menu
- Test the pages at each link in the footer
- Test the search function 
- Test these pages in en and ar_SA.

**Comment by KatieWoe** [comment]
- [ ] Win 10 Chrome (Time = ) (Tester = )
- [ ] Win 10 Firefox (Time = ) (Tester = )
- [ ] Mac 11 Chrome (Time = ) (Tester = )
- [ ] Mac 11 Safari (Time = ) (Tester = )
- [ ] ChromeOS (Time = ) (Tester = )
- [ ] iPadOS (Time = ) (Tester = )
- [ ] iPhone (Time = ) (Tester = )
- [ ] Android (Time = ) (Tester = )

**Comment by KatieWoe** [comment]
Time estimate from Slack:
>So, just a quick review of all the top-level pages on the website.  It’s probably 30 pages or so.  2 minutes per page or so should be sufficient.

**Comment by mattpen** [comment]
Thanks @KatieWoe @Nancy-Salpepi
