### ISSUE TITLE
Identify public links that go to phet-dev server

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/qa#709]
Over in https://github.com/phetsims/phet-io/issues/1591, we are discussing an issue that needs some QA time. 

Please have a look through this issue, and start a google sheet that documents links from a11y research papers. Those research papers can be found here: 
https://phet.colorado.edu/en/accessibility/research

Spreadsheet can have columns of 
Publication Year 
Author
Title 
Journal 
Links from paper 

You may find the links in the body of the text, or in the references, so you may need to look around for them. 

Thanks! This can be a back-burner task.

**Comment by zepumph** [comment]
I think that @emily-phet's comment over in that phet-io issue is a great starting point:

>I would guess we have on the order of 12-25 public links to phet-io wrappers for sonification, and maybe 0-2 for haptics.
The sonification wrappers would be linked in papers, on the PhET website, though the majority are probably embedded as part of the Coursera MOOC Brianna led the creation of. Editing links in the Coursera platform is non-trivial, though doable if absolutely necessary.
We do need these to remain publicly accessible, though in some cases we do have the ability to edit the links (potentially in publications, definitely on the PhET website, and on the Coursera MOOC platform).

Feel free to reach out if you don't know how to access this stuff.

**Comment by emily-phet** [comment]
We could reach out directly to Brianna, who may have a list of sim links she used in the course. I know she had one at some point, because she was working with JB to get examples of specific sound arrangements, she may still have that.

**Comment by KatieWoe** [comment]
This matrix has the links for the papers on the website. Record data here. Some entries had multiple links, so entries are separated by lines. Let me know if you have questions.

**Comment by zepumph** [comment]
I see, I didn't know this was complete. I'll pick things up over in https://github.com/phetsims/phet-io/issues/1591. Thanks QA!
