### ISSUE TITLE
RC test: Projectile Motion 1.0.2-rc.2

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#71]
A second RC has been published for the 1.0.2 maintenance release.  For detailed info about this maintenance release, please see https://github.com/phetsims/projectile-motion/issues/160.

link: https://www.colorado.edu/physics/phet/dev/html/projectile-motion/1.0.2-rc.2/projectile-motion_en.html

The only intended change for this RC versus the previous one is to incorporate some additional fixes for LoL behavior.  So, other than sanity testing, the only issue that needs to be verified is:

- [x] https://github.com/phetsims/joist/issues/458

Assigning to @ariel-phet to prioritize.

**Comment by ariel-phet** [comment]
@phet-steele marking medium, but should be quick so would be good to get to this week

**Comment by phet-steele** [comment]
Good to go @jbphet.

**Comment by jbphet** [comment]
Thanks team.  Closing.
