### ISSUE TITLE
Maintenance testing for sound fixes

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/qa#713]
Patches have been applied for https://github.com/phetsims/tambo/issues/151. I believe @jbphet has more details about how we should test this, but we'll want to AT LEAST make sure the sims load on a macOS Catalina + Safari 15, and do a 5-10 second test each to make sure there is nothing horribly broken.

Additionally, it would probably be good to make sure that all sims NOT on this list (in production) load with macOS Catalina + Safari 15.

atomic-interactions 1.2 (https://github.com/phetsims/tambo/issues/151)

- [x] [atomic-interactions 1.2.3-rc.1](https://phet-dev.colorado.edu/html/atomic-interactions/1.2.3-rc.1/phet/atomic-interactions_en_phet.html)

build-a-molecule 1.0 (https://github.com/phetsims/tambo/issues/151)

- [x] [build-a-molecule 1.0.5-rc.1](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.5-rc.1/phet/build-a-molecule_en_phet.html)

circuit-construction-kit-dc 1.2 (https://github.com/phetsims/tambo/issues/151)

- [x] [circuit-construction-kit-dc 1.2.5-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.5-rc.1/phet/circuit-construction-kit-dc_en_phet.html)

circuit-construction-kit-dc-virtual-lab 1.2 (https://github.com/phetsims/tambo/issues/151)

- [x] [circuit-construction-kit-dc-virtual-lab 1.2.5-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.2.5-rc.1/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html)

collision-lab 1.1 (https://github.com/phetsims/tambo/issues/151)

- [x] [collision-lab 1.1.4-rc.1](https://phet-dev.colorado.edu/html/collision-lab/1.1.4-rc.1/phet/collision-lab_en_phet.html)

energy-forms-and-changes 1.4 (https://github.com/phetsims/tambo/issues/151)

- [x] [energy-forms-and-changes 1.4.3-rc.1](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.3-rc.1/phet/energy-forms-and-changes_en_phet.html)
- [x] [energy-forms-and-changes 1.4.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.3-rc.1/phet-io/energy-forms-and-changes_all_phet-io.html?phetioStandalone)
- [x] [energy-forms-and-changes 1.4.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.3-rc.1/phet-io/wrappers/studio)

energy-skate-park 1.1 (https://github.com/phetsims/tambo/issues/151)

- [x] [energy-skate-park 1.1.4-rc.1](https://phet-dev.colorado.edu/html/energy-skate-park/1.1.4-rc.1/phet/energy-skate-park_en_phet.html)

faradays-law 1.4 (https://github.com/phetsims/tambo/issues/151)

- [x] [faradays-law 1.4.4-rc.1](https://phet-dev.colorado.edu/html/faradays-law/1.4.4-rc.1/phet/faradays-law_en_phet.html)

graphing-quadratics 1.2 (https://github.com/phetsims/tambo/issues/151)

- [x] [graphing-quadratics 1.2.2-rc.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.2-rc.1/phet/graphing-quadratics_en_phet.html)
- [x] [graphing-quadratics 1.2.2-rc.1 phet-io](https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.2-rc.1/phet-io/graphing-quadratics_all_phet-io.html?phetioStandalone)
- [x] [graphing-quadratics 1.2.2-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.2-rc.1/phet-io/wrappers/studio)

gravity-and-orbits 1.4 (https://github.com/phetsims/tambo/issues/151)

- [x] [gravity-and-orbits 1.4.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.4.3-rc.1/phet-io/gravity-and-orbits_all_phet-io.html?phetioStandalone)
- [x] [gravity-and-orbits 1.4.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.4.3-rc.1/phet-io/wrappers/studio)

gravity-and-orbits 1.5 (https://github.com/phetsims/tambo/issues/151)

- [x] [gravity-and-orbits 1.5.2-rc.1](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.2-rc.1/phet/gravity-and-orbits_en_phet.html)
- [x] [gravity-and-orbits 1.5.2-rc.1 phet-io](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.2-rc.1/phet-io/gravity-and-orbits_all_phet-io.html?phetioStandalone)
- [x] [gravity-and-orbits 1.5.2-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.2-rc.1/phet-io/wrappers/studio)

greenhouse-effect 1.0 (https://github.com/phetsims/tambo/issues/151)

- [x] [greenhouse-effect 1.0.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.1-rc.1/phet-io/greenhouse-effect_all_phet-io.html?phetioStandalone)
- [x] [greenhouse-effect 1.0.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.1-rc.1/phet-io/wrappers/studio)

john-travoltage 1.6 (https://github.com/phetsims/tambo/issues/151)

- [x] [john-travoltage 1.6.1-rc.1](https://phet-dev.colorado.edu/html/john-travoltage/1.6.1-rc.1/phet/john-travoltage_en_phet.html)

molecule-polarity 1.2 (https://github.com/phetsims/tambo/issues/151)

- [x] [molecule-polarity 1.2.2-rc.1](https://phet-dev.colorado.edu/html/molecule-polarity/1.2.2-rc.1/phet/molecule-polarity_en_phet.html)
- [x] [molecule-polarity 1.2.2-rc.1 phet-io](https://phet-dev.colorado.edu/html/molecule-polarity/1.2.2-rc.1/phet-io/molecule-polarity_all_phet-io.html?phetioStandalone)
- [x] [molecule-polarity 1.2.2-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-polarity/1.2.2-rc.1/phet-io/wrappers/studio)

molecules-and-light 1.5 (https://github.com/phetsims/tambo/issues/151)

- [x] [molecules-and-light 1.5.11-rc.1](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.11-rc.1/phet/molecules-and-light_en_phet.html)

natural-selection 1.2 (https://github.com/phetsims/tambo/issues/151)

- [x] [natural-selection 1.2.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/natural-selection/1.2.3-rc.1/phet-io/natural-selection_all_phet-io.html?phetioStandalone)
- [x] [natural-selection 1.2.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/natural-selection/1.2.3-rc.1/phet-io/wrappers/studio)

natural-selection 1.3 (https://github.com/phetsims/tambo/issues/151)

- [x] [natural-selection 1.3.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/natural-selection/1.3.3-rc.1/phet-io/natural-selection_all_phet-io.html?phetioStandalone)
- [x] [natural-selection 1.3.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/natural-selection/1.3.3-rc.1/phet-io/wrappers/studio)

natural-selection 1.4 (https://github.com/phetsims/tambo/issues/151)

- [x] [natural-selection 1.4.2-rc.1](https://phet-dev.colorado.edu/html/natural-selection/1.4.2-rc.1/phet/natural-selection_en_phet.html)
- [x] [natural-selection 1.4.2-rc.1 phet-io](https://phet-dev.colorado.edu/html/natural-selection/1.4.2-rc.1/phet-io/natural-selection_all_phet-io.html?phetioStandalone)
- [x] [natural-selection 1.4.2-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/natural-selection/1.4.2-rc.1/phet-io/wrappers/studio)

number-line-distance 1.0 (https://github.com/phetsims/tambo/issues/151)

- [x] [number-line-distance 1.0.1-rc.1](https://phet-dev.colorado.edu/html/number-line-distance/1.0.1-rc.1/phet/number-line-distance_en_phet.html)

number-line-integers 1.1 (https://github.com/phetsims/tambo/issues/151)

- [x] [number-line-integers 1.1.3-rc.1](https://phet-dev.colorado.edu/html/number-line-integers/1.1.3-rc.1/phet/number-line-integers_en_phet.html)

number-line-operations 1.0 (https://github.com/phetsims/tambo/issues/151)

- [x] [number-line-operations 1.0.4-rc.1](https://phet-dev.colorado.edu/html/number-line-operations/1.0.4-rc.1/phet/number-line-operations_en_phet.html)

ph-scale 1.5 (https://github.com/phetsims/tambo/issues/151)

- [x] [ph-scale 1.5.2-rc.1](https://phet-dev.colorado.edu/html/ph-scale/1.5.2-rc.1/phet/ph-scale_en_phet.html)
- [x] [ph-scale 1.5.2-rc.1 phet-io](https://phet-dev.colorado.edu/html/ph-scale/1.5.2-rc.1/phet-io/ph-scale_all_phet-io.html?phetioStandalone)
- [x] [ph-scale 1.5.2-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/ph-scale/1.5.2-rc.1/phet-io/wrappers/studio)

ph-scale-basics 1.5 (https://github.com/phetsims/tambo/issues/151)

- [x] [ph-scale-basics 1.5.2-rc.1](https://phet-dev.colorado.edu/html/ph-scale-basics/1.5.2-rc.1/phet/ph-scale-basics_en_phet.html)
- [x] [ph-scale-basics 1.5.2-rc.1 phet-io](https://phet-dev.colorado.edu/html/ph-scale-basics/1.5.2-rc.1/phet-io/ph-scale-basics_all_phet-io.html?phetioStandalone)
- [x] [ph-scale-basics 1.5.2-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/ph-scale-basics/1.5.2-rc.1/phet-io/wrappers/studio)

ratio-and-proportion 1.0 (https://github.com/phetsims/tambo/issues/151)

- [x] [ratio-and-proportion 1.0.3-rc.1](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.3-rc.1/phet/ratio-and-proportion_en_phet.html)

states-of-matter 1.2 (https://github.com/phetsims/tambo/issues/151)

- [x] [states-of-matter 1.2.4-rc.1](https://phet-dev.colorado.edu/html/states-of-matter/1.2.4-rc.1/phet/states-of-matter_en_phet.html)
- [x] [states-of-matter 1.2.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/states-of-matter/1.2.4-rc.1/phet-io/states-of-matter_all_phet-io.html?phetioStandalone)
- [x] [states-of-matter 1.2.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/states-of-matter/1.2.4-rc.1/phet-io/wrappers/studio)

states-of-matter-basics 1.2 (https://github.com/phetsims/tambo/issues/151)

- [x] [states-of-matter-basics 1.2.3-rc.1](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.3-rc.1/phet/states-of-matter-basics_en_phet.html)
- [x] [states-of-matter-basics 1.2.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.3-rc.1/phet-io/states-of-matter-basics_all_phet-io.html?phetioStandalone)
- [x] [states-of-matter-basics 1.2.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.3-rc.1/phet-io/wrappers/studio)

waves-intro 1.1 (https://github.com/phetsims/tambo/issues/151)

- [x] [waves-intro 1.1.3-rc.1](https://phet-dev.colorado.edu/html/waves-intro/1.1.3-rc.1/phet/waves-intro_en_phet.html)

**Comment by KatieWoe** [comment]
All sims broken on the website seem to be represented here.

**Comment by Nancy-Salpepi** [comment]
Using Mac with iOS Catalina and Safari 15:
Tested all of the sims above and all loaded quickly. Quick check of each sim didn't reveal any issues (aside from lack of sound). I'd thought I would also note that Voicing still works on John Travoltage.
I haven't check any of the sims in production yet.
