### ISSUE TITLE
Dev test: molecule-shapes 1.4.0-dev.1

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/qa#715]
@arouinfar, @kathy-phet, molecule-shapes/1.4.0-dev.1 is ready for dev testing. Document issues in https://github.com/phetsims/molecule-shapes/issues and link to this
issue.

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time = 1.5 hr)
- [x] Windows 10, Chrome (Time = 1.5)
- [x] Windows 10, Firefox (Time = 1.5 hr)
- [x] Latest iOS, Safari (Time = 1.5 hr)

Light testing, or optionally skip if time crunch: 
- [x] Latest macOS, Chrome (Time =1 hr )
- [x] Latest Chrome OS, Chrome (Time = 1.25)

<h3>Issues to Verify</h3>

- [x] [webgl warning obscured by navbar](https://github.com/phetsims/molecule-shapes/issues/169)

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/molecule-shapes/1.4.0-dev.1/phet/molecule-shapes_all_phet.html)**

<hr>

</details>

<details>
<summary><b>PhET-iO Dev Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time =2.5 hr )
- [x] Latest iOS, Safari (Time = 1 hr)
- [x] Windows 10, Chrome (Time = 1.25 hr)
- [x] Windows 10, Firefox (Time = 2 hr)
- [x] Latest Chrome OS, Chrome (Time = 2hr )

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/molecule-shapes/1.4.0-dev.1/phet-io/)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Calling QA here

**Comment by jonathanolson** [comment]
Thanks!
