### ISSUE TITLE
Maintenance release testing for _all.html

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/QA#72]
Main issue is https://github.com/phetsims/chipper/issues/563 (for Chipper 2.0)

For the actual maintenance release, can I first get quick checks to make sure the following sims were not broken (RCs for the maintenance release, ~10-30 seconds of testing each)

- [x] https://www.colorado.edu/physics/phet/dev/html/acid-base-solutions/1.2.11-rc.1/acid-base-solutions_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/area-builder/1.1.6-rc.1/area-builder_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/arithmetic/1.0.10-rc.1/arithmetic_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/atomic-interactions/1.0.4-rc.1/atomic-interactions_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/balancing-act/1.1.10-rc.1/balancing-act_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/balancing-chemical-equations/1.1.10-rc.1/balancing-chemical-equations_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.4-rc.1/beers-law-lab_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/bending-light/1.1.7-rc.1/bending-light_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/charges-and-fields/1.0.4-rc.1/charges-and-fields_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/color-vision/1.1.10-rc.1/color-vision_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/concentration/1.3.6-rc.1/concentration_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/energy-skate-park-basics/1.1.6-rc.1/energy-skate-park-basics_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/faradays-law/1.1.10-rc.1/faradays-law_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.1.5-rc.1/forces-and-motion-basics_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/fraction-matcher/1.1.8-rc.1/fraction-matcher_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/friction/1.3.4-rc.1/friction_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/function-builder/1.0.9-rc.1/function-builder_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/hookes-law/1.0.10-rc.1/hookes-law_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/isotopes-and-atomic-mass/1.0.9-rc.1/isotopes-and-atomic-mass_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/least-squares-regression/1.1.7-rc.1/least-squares-regression_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.11-rc.1/molecule-shapes_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/molecule-shapes-basics/1.1.9-rc.1/molecule-shapes-basics_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/molecules-and-light/1.1.16-rc.1/molecules-and-light_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/neuron/1.1.4-rc.1/neuron_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/ohms-law/1.3.8-rc.1/ohms-law_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/ph-scale/1.2.11-rc.1/ph-scale_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/ph-scale-basics/1.2.11-rc.1/ph-scale-basics_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/reactants-products-and-leftovers/1.1.10-rc.1/reactants-products-and-leftovers_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.2.9-rc.1/resistance-in-a-wire_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.0.7-rc.1/rutherford-scattering_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/trig-tour/1.0.9-rc.1/trig-tour_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/under-pressure/1.1.5-rc.1/under-pressure_en.html
- [x] https://www.colorado.edu/physics/phet/dev/html/wave-on-a-string/1.1.9-rc.1/wave-on-a-string_en.html
- [x] Additionally, can all of the files at https://www.colorado.edu/physics/phet/dev/olsonjb/all-versions/ be checked?

It includes _en.html and _all.html files for all live production sims. I would load each file up and check `phet.chipper.strings` in the console. For _en.html files, it should have basically only the "en" locale (ignore the get function), and for _all.html files it should have all locales included.

- [x] Additionally, can you spot-check all of the _all.html files for multiple locales, using query parameters like `?locale=en`, `?locale=fr` and such to ensure that at least English and 1-2 other locales run for each _all.html?

**Comment by jonathanolson** [comment]
Ack, one second. Looks like build-server failed for least-squares-regression, molecule-shapes and molecule-shapes-basics (looks like a chronological failure). @mattpen can you look into that? I'll re-send deployments.

**Comment by jonathanolson** [comment]
molecules-and-light also failed build-server, but didn't send a failure email (probably due to its chipper SHA)

**Comment by jonathanolson** [comment]
Ok, the 4 RCs that failed above have been successfully re-deployed. Should be ready again for testing.

**Comment by ariel-phet** [comment]
@phet-steele #70 needs to come first, but it would be good to mix in some of this spot checking early to see if there are any major issues

**Comment by CWilson4960** [comment]
@jonathanolson Resistance in a Wire was recently published, new branch. The changes in this issue should be done on that new branch.

**Comment by jonathanolson** [comment]
I'll double-check RIAW, but it should be new enough that it would include the feature.

**Comment by phet-steele** [comment]
@jonathanolson this was a dooozy! Spot checking `?locale=` never failed when doing `en` and two other random locales. Spending 30 seconds on each RC revealed no new issues.

**Comment by jonathanolson** [comment]
Thanks! Maintenance releases finished (deployed to production)
