### ISSUE TITLE
Dev test: Normal Modes 1.0.0-dev.5

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#724]
@KatieWoe, @kathy-phet, @DianaTavares, normal-modes/1.0.0-dev.5 is ready for light dev testing. 

This test is the beginning of the QA process for an eventual "prototype" release. 

Document issues in https://github.com/phetsims/normal-modes/issues and link to this issue. 

[Link to 1.0.0-dev.5]( https://phet-dev.colorado.edu/html/normal-modes/1.0.0-dev.5/phet/normal-modes_en_phet.html)

Assigning @kathy-phet and @KatieWoe for prioritization.

This test is for general. Platform coverage is not important for this test. Testing should be around 4 hours max.

In addition to the QA team, members of the Normal Modes team will be testing this version, and they are assigned to this issue.  Please check yourself off in the list below when you have finished testing.

- [x] Tester 1 (Tester = NS , Platform = MacOS 12 + safari 15, Time = 2 hrs)
- [x] Tester 2 (Tester = KW, Platform = Win 11 Chrome, Time = 2{max 2 hours}
- [x] @DianaTavares 
- [x] @arouinfar (macOS 10.15.7 & Chrome 95.0.4638.54, ~1.25 hrs)
- [x] @ariel-phet  (Windows 10 desktop with Chrome, ~1 hour)
- [x] @pixelzoom 

What to Test
- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Include OS + browser version numbers in issues.

**Comment by DianaTavares** [comment]
I played with the sim, clicking in all the buttons, and the user can do crazy things, but the same happens with the flash sim. The masses can move anywhere and super fast. But the sim works and can be used as a prototype.

I leave it going crazy for several minutes and the sim never breaks. The masses can go outside the screen, but they come back. I don't find a big issue to stop the sim from going as a prototype. 

I did the design for the second screen if you want it to include it:

![image](https://user-images.githubusercontent.com/26031501/137764640-0b15a584-786e-476f-9f4f-26a9f694e23d.png)

**Comment by ariel-phet** [comment]
Worked with @pixelzoom on a couple of quick refinements, I am going to pause dev testing for now since it will likely make most sense to test a new dev version with the refinements baked in.

**Comment by pixelzoom** [comment]
In Slack, @KatieWoe said:
> The pipeline should be clear enough for https://github.com/phetsims/qa/issues/724 now. 

So I've published a new dev version, 1.0.0-dev.5.

Assigning @ariel-phet again, because this version contains the changes that he requested for the prototype.

**Comment by ariel-phet** [comment]
Tested https://phet-dev.colorado.edu/html/normal-modes/1.0.0-dev.5/phet/normal-modes_en_phet.html mainly for physics and correctness  (looks like QA is catching good usability and such bugs).

I think for the purposes of a prototype it is in good shape. Just as a note, I think to truly take this sim to the finish line one day, the top priorities would be:
1. Constraints on the horizontal initial displacement of masses on the 1d screen
2. Work on the "Normal Modes Amplitudes" matrix on the 2-d screen in terms of labelling, communicating that the matrix buttons are selectable, and that both horizontal and vertical modes can be present and read out
3. Tuning of amplitudes and readouts of the 2d case
4. Some general pixel polishing/alignments (pretty minor overall)

**Comment by KatieWoe** [comment]
QA is done

**Comment by kathy-phet** [comment]
Don’t wait for me on this one. Just proceed off everyone else’s testing.

**Comment by KatieWoe** [comment]
I did a quick memory test and things look good:
<img width="350" alt="memtest" src="https://user-images.githubusercontent.com/41024075/140167716-be6a9c9c-a70a-40aa-ae45-5b99c62f3e63.png">

**Comment by pixelzoom** [comment]
Thanks QA and sim team. Onward to RC testing...
