### ISSUE TITLE
Dev Test: Science Workshop OAS

### ISSUE THREAD

**Issue by chrisklus** [phetsims/qa#726]
@DianaTavares, @kathy-phet, @KatieWoe, the "Science Workshop for the Caribbean" is ready for dev testing. The plan is for this to be used for a workshop starting on Wednesday 10/20, so we are attempting to publish it by tomorrow night (10/19). This is not going to be linked publicly on the website, as it is only going to be used for a conference. Please document issues in https://github.com/phetsims/website-meteor/issues and link to this issue.

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

This workshop runs off of the same framework as the math workshop, so the issues found from the page during the strings test (https://github.com/phetsims/qa/issues/720) already apply, and do not need to be duplicated. Please conduct a general test of this page, but with the given time constraints, the primary focus should be to catch any major usability problems. Please also check that the links make sense, and that the content they link to is viewable to the public, but not editable (for google docs and forms).

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time = 4 )
- [ ] Windows 10, Chrome (Time = 2)
- [ ] Windows 10, Firefox (Time = 2)
- [ ] Latest iOS, Safari (Time = 4)
- [x] Win 11 Chrome (Time = 3)

Light testing, or optionally skip if time crunch: 
- [x] Latest macOS, Chrome (Time = 2 hr )
- [ ] Latest Chrome OS, Chrome (Time = 1hr )

<h3>Link(s)</h3>

- **[Website](https://ox-dev.colorado.edu/en/teaching-resources/virtual-workshop/science-oas)**

**Comment by KatieWoe** [comment]
QA has tested most of the things I think it can tonight

**Comment by KatieWoe** [comment]
Closing for @chrisklus
