### ISSUE TITLE
RC Spot Check Resistance and a Wire 1.4.0-rc.2

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#73]
Resistance in a Wire 1.4.0-rc.2 is ready for an RC spot check. Differences from the last RC include updates to the look of the keyboard help dialog, and a patch to fix https://github.com/phetsims/john-travoltage/issues/252. 

**Link to sim:** https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.4.0-rc.2/resistance-in-a-wire_en.html

**Link to iframe:** https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.4.0-rc.2/resistance-in-a-wire_en-iframe.html (in case it is required)

@phet-steele could you please spot check this version or and verify that the following issue is fixed?

- [x] https://github.com/phetsims/john-travoltage/issues/252

Unless anything else is found, this sim can be redeployed once that is complete. Also assigning to @ariel-phet so he is aware and to assign priority.

**Comment by phet-steele** [comment]
Testing done @jessegreenberg.

**Comment by jessegreenberg** [comment]
Thank you @phet-steele! Will cherry-pick changes for https://github.com/phetsims/resistance-in-a-wire/issues/119 and https://github.com/phetsims/resistance-in-a-wire/issues/118.
