### ISSUE TITLE
Dev test: Equality Explorer 1.1.0-dev.4

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#732]
@KatieWoe @kathy-phet @amanda-phet, equality-explorer/1.1.0-dev.4 is ready for light dev testing. 

Document issues in https://github.com/phetsims/equality-explorer/issues and link to this issue.

This is a dev-lite test, which will be followed by a full RC test cycle.  The goal is to republish the sim with these new features, which should be specifically tested:

- [x] https://github.com/phetsims/equality-explorer/issues/164
- [x] https://github.com/phetsims/equality-explorer/issues/165

[Link to 1.1.0-dev.4](https://phet-dev.colorado.edu/html/equality-explorer/1.1.0-dev.4/phet/equality-explorer_all_phet.html)

Assigning @kathy-phet and @KatieWoe for prioritization.

This test is for general. Platform coverage is not important for this test. Testing should be around 4 hours max.

- [x] Tester 1 (Tester =NS , Platform =MacOS12 + Safari 15 , Time = 2hrs)
- [x] Tester 2 (Tester = KW, Platform = Win 11 Chrome, Time = 2{max 2 hours}

What to Test
- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Include OS + browser version numbers in issues.

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
Since QA is done, I'm assuming this should be assigned to me, so I've self assigned. 

phetsims/equality-explorer#169 and phetsims/equality-explorer#171 are awaiting review. Then we can proceed with RC testing.  So I'll close this issue.
