### ISSUE TITLE
RC test: Normal Modes 1.0.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#733]
@KatieWoe @kathy-phet @arouinfar @ariel-phet, normal-modes/1.0.0-rc.1 is ready for prototype testing. This simulation will be put on the website as a prototype and will likely have more bugs than a publication-ready simulation. 

Document issues in https://github.com/phetsims/normal-modes/issues and link to this issue. **Issues should focus on base usability and pedagogy.**

Assigning to @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Play with the simulation normally.
- Make sure you can't lose anything.
- Complete the test matrix.
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- Focus on pedagogy issues and bugs that break the sim. 
- If you find bugs beyond pedagogy/breaking, still document these bugs as github issues.
- If a11y aspects are present, test them, but with an eye for "normal use".

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/normal-modes/1.0.0-rc.1/phet/normal-modes_all_phet.html)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1ZHTkbzJbfbV8qfY4DBuQj7bLL2MH7UOMZDY8e2RThfg/edit#gid=282281581)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/doc/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by ariel-phet** [comment]
I looked over all the implemented changes, everything is looking nice, looking forward to QA's run through the sim

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/normal-modes/issues/79 we found that this sim does not support mutlitouch, and behaves very badly.  I also learned that dev-lite testing does not include multitouch, and was therefore seems like an inappropriate choice to have made for testing this prototype in https://github.com/phetsims/qa/issues/724.

@KatieWoe does RC-lite testing include multitouch testing?

**Comment by KatieWoe** [comment]
@pixelzoom It depends on what is requested for the RC-lite. In this case, since it is for a prototype, we are using the test matrix linked in the issue and an iPad is included.

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
Thanks QA team. We'll need another RC spot-check, and I'll get that going.

Closing.
