### ISSUE TITLE
Dev Test: Circuit Construction Kit: AC 1.0.0-dev.48

### ISSUE THREAD

**Issue by samreid** [phetsims/qa#736]
@KatieWoe, @arouinfar, @ariel-phet, @kathy-phet, simulation-name/1.0.0-dev.48 is ready for dev testing. I'm not aware of any deadlines or clients for this version. Document issues in https://github.com/phetsims/circuit-construction-kit-common/issues and link to this issue. This is a general dev test to find any bugs, including but not limited to user experience, model correctness, etc.

This version also contains a prototype phet-io harness to help us share buggy states.  You can access it by launching:
https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.48/phet-io/circuit-construction-kit-ac_all_phet-io.html?postMessageOnError&phetioStandalone&&phetioDevSaveLoad

To save a state, press SHIFT+1, SHIFT+2 etc. to save in those slots.  A saved state is also outputted to the console.
A saved state can be restored in that same browser with CTRL+1, CTRL+2, etc.  We are not testing any PhET-iO features
in this sim, but we are just using PhET-iO as a way to get buggy states.  Since the phet-io states are not meant to be
public, please put them in special-ops issues.

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- I'm not aware of any sound in the AC version.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>Focus and Special Instructions</h3>

If you can find a way to reproduce "current flowing when circuit is paused" for https://github.com/phetsims/circuit-construction-kit-common/issues/770, or determine if that is no longer happening, that would be great.

We would also appreciate testing the signed nature of the ammeter probe.  Enable it in the options menu: https://github.com/phetsims/circuit-construction-kit-common/issues/606

At the time of writing, we also had these open issues which are up for discussion with the design team:
https://github.com/phetsims/circuit-construction-kit-common/issues/772#issuecomment-963756821
https://github.com/phetsims/circuit-construction-kit-common/issues/758#issuecomment-962795174

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time = 4.5 )
- [x] Windows 10, Chrome (Time = 6.5)
- [ ] Windows 10, Firefox (Time = 4.0)
- [ ] Latest iOS, Safari (Time = 1.5)

Light testing, or optionally skip if time crunch: 
- [ ] Latest macOS, Chrome (Time = )
- [ ] Latest Chrome OS, Chrome (Time = )

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.48/phet/circuit-construction-kit-ac_all_phet.html)**
- **[Virtual Lab](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.0-dev.1/phet/circuit-construction-kit-ac-virtual-lab_all_phet.html)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) Dev Test</b></summary>

<h3>What to Test</h3>

- Deletion of selected circuit elements with the delete key

<h3>Focus and Special Instructions</h3>

- Please test deletion of selected circuit elements with the delete key

<h3>Link(s)</h3>

Use same links as above

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
I did a quick memory test to see if there were any leaks. @samreid do these results look ok?
<img width="344" alt="memtest" src="https://user-images.githubusercontent.com/41024075/141001192-892fc4be-1001-4d43-9811-3ac14e4080c2.png">

**Comment by samreid** [comment]
That looks like trouble, thanks!  I'll open an issue for investigation.  At the moment, this is not worrisome enough to pause testing (but I'll let you know if I discover otherwise).

**Comment by kathy-phet** [comment]
@samreid - Should we end this test now and let you fix these issues, then send it back through for another dev test? This seems like a nice collection and there has been ~8 hours of testing. 

@KatieWoe - Maybe just having someone bang on it for an hour on iOS would help make sure we don't have a special iOS problem.

**Comment by samreid** [comment]
> @KatieWoe - Maybe just having someone bang on it for an hour on iOS would help make sure we don't have a special iOS problem.

That sounds good, can we do the same for chromebook?  Are we testing on android at this time?

> @samreid - Should we end this test now and let you fix these issues, then send it back through for another dev test? This seems like a nice collection and there has been ~8 hours of testing.

Another dev test sounds good. I don't know how to judge whether we should end this dev test now.  How much longer would it take if we didn't stop it now?  How much of the sim has been explored?  Whether QA needs to get to other tasks could also be a determining factor.

**Comment by kathy-phet** [comment]
These bugs are substantial enough to cause other potential bugs when fixed. So let's put the time in the next dev, after these bugs are fixed, since this will need to do another full dev test.

**Comment by kathy-phet** [comment]
So just a hour or so more on iOS please.

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
Thanks, all discovered issues have been closed or assigned to the milestone.  We aren't quite ready to schedule the next dev test, but perhaps I'll make a placeholder card.  Closing.
