### ISSUE TITLE
RC Spot Check Resistance in a Wire 1.4.0-rc.3

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#74]
Resistance in a Wire 1.4.0-rc.3 is ready for an RC spot check. This RC includes fixes for two issues, listed below.

Link to sim: https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.4.0-rc.3/resistance-in-a-wire_en.html

Link to iframe: https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.4.0-rc.3/resistance-in-a-wire_en-iframe.html (in case it is required)

@phet-steele could you please spot check this version and verify that the following issue is fixed? They have already been verified as fixed in master.
- [x] phetsims/resistance-in-a-wire#118
- [x] phetsims/resistance-in-a-wire#119

**Comment by phet-steele** [comment]
Do it.

**Comment by jessegreenberg** [comment]
Thanks @phet-steele! Done!
