### ISSUE TITLE
Dev Test: gravity-and-orbits/1.6.0-dev.1/phet-io with TypeScript

### ISSUE THREAD

**Issue by samreid** [phetsims/qa#744]
@KatieWoe, gravity-and-orbits/1.6.0-dev.1/phet-io/ is ready for dev testing. This is an internal test to see how PhET-iO
is going with TypeScript. Document issues in https://github.com/phetsims/gravity-and-orbits/issues and link to this
issue.  If other QA tasks come into the queue, this can be deprioritized.  We will not be making an RC from this, so perhaps it is more of a "lite" test.

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>PhET-iO Dev Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.

<h3>General Dev Test Platforms</h3>

- [x] Windows 10, Chrome (Time = 4.75)
- [x] Win 10/11 Firefox (Time = 3.5)
- [x] MacOS Safari (Time = 3 hr )
- [x] Latest iOS, Safari (Time = 2)
- [x] Latest Chrome OS, Chrome (Time = 2)

<h3>Focus and Special Instructions</h3>

This is just to spot check that TypeScript is running OK in PhET-iO.

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.0-dev.1/phet-io/)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

Tagging for https://github.com/phetsims/gravity-and-orbits/issues/411

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
Thanks, closing.
