### ISSUE TITLE
Dev Lite: Circuit Construction Kit: AC 1.0.0-dev.53

### ISSUE THREAD

**Issue by samreid** [phetsims/qa#747]
@kathy-phet @arouinfar @KatieWoe @markgammon, circuit-construction-kit-ac/1.0.0-dev.53 (and virtual lab) is ready for light dev testing. Document issues in https://github.com/phetsims/circuit-construction-kit-common/issues and link to this issue. We are working to get CCK AC published as quickly as possible, so this is probably high priority.

We previously had one dev test in https://github.com/phetsims/qa/issues/736

[AC](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-dev.53/phet/circuit-construction-kit-ac_en_phet.html)
[Virtual Lab](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.0-dev.3/phet/circuit-construction-kit-ac-virtual-lab_en_phet.html)

Assigning @kathy-phet and @KatieWoe for prioritization.

This test is for (select all that apply) [general]. Platform coverage is not important for this test. Testing should be around 4 hours max.  @kathy-phet said:

> The next test should be a time-limited "dev lite" I think, where we give it 1 day to test and then move on to RC assuming no show stoppers show up.

- [x] Tester 1 (Tester = E2, Platform = Win10 Chrome, Time = 1.5 {max 2 hours}
- [x] Tester 2 (Tester = KW, Platform = Win 11 Chrome and iPadOS 15, Time = 2{max 2 hours}
- [x] Tester 3 (Tester = NS , Platform = macOS 12 + Chrome , Time = 1.5 {max 2 hours}

What to Test
- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Include OS + browser version numbers in issues.

- [x] For https://github.com/phetsims/circuit-construction-kit-common/issues/784, do you see any sign errors?
- [x] Please test https://github.com/phetsims/circuit-construction-kit-common/issues/782
- [x] Please test https://github.com/phetsims/circuit-construction-kit-common/issues/776

Also, this version is using a new transpiler as part of https://github.com/phetsims/chipper/issues/1156, so please keep your eyes peeled for any unusual behavior.

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
@ariel-phet requested testing on a chromebook before we begin RC testing.

**Comment by KatieWoe** [comment]
I tested a few circuits on our lowest performing chromebook and performance seemed ok.

**Comment by samreid** [comment]
Thanks, I'll create an RC test soon.  Closing.
