### ISSUE TITLE
RC.1 Test: Circuit Construction Kit AC and AC Virtual Lab

### ISSUE THREAD

**Issue by samreid** [phetsims/qa#748]
@arouinfar @KatieWoe @markgammon @kathy-phet, circuit-construction-kit-ac/1.0.0-rc.1 and circuit-construction-kit-ac-virtual-lab/1.0.0-rc.1 are 
ready for RC testing. This has been a high priority sim for a long time and I expect it will be tested at high priority.
Document issues in https://github.com/phetsims/circuit-construction-kit-common/issues and link to this
issue.

We previously had one dev test and one dev-lite test.

I'll assign priority and pipeline based on my understanding, and assigning to @kathy-phet and @KatieWoe for any adjustments.

<details>
<summary><b>General RC Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.  The last memory check was completed in https://github.com/phetsims/circuit-construction-kit-common/issues/775
- When making an issue, check to see if it was in a previously published version.
- Try to include version numbers for browsers.
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if there is a problem.

<h3>Focus and Special Instructions</h3>

[Provide further instructions here. If you have any further tests you want done or specific platforms you want tested,
list them here. Any behaviors you want QA to pay special attention to should be listed here.]

<h3>Issues to Verify</h3>

- [ ] [Current Sign](https://github.com/phetsims/circuit-construction-kit-common/issues/606) Please turn on the "signed ammeters" option
in the options menu and check that the ammeters show signs that correspond to the signs on the current chart, and that
the values seem physically correct.

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

- **[AC Simulation](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-rc.1/phet/circuit-construction-kit-ac_all_phet.html)**
- **[AC iFrame](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-rc.1/phet/circuit-construction-kit-ac_all_iframe_phet.html)**
- **[AC XHTML](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-rc.1/phet/xhtml/circuit-construction-kit-ac_all.xhtml)**
- **[AC VL Simulation](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.0-rc.1/phet/circuit-construction-kit-ac-virtual-lab_all_phet.html)**
- **[AC VL iFrame](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.0-rc.1/phet/circuit-construction-kit-ac-virtual-lab_all_iframe_phet.html)**
- **[AC VL XHTML](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.0-rc.1/phet/xhtml/circuit-construction-kit-ac-virtual-lab_all.xhtml)**
- **[Test Matrix](https://docs.google.com/spreadsheets/d/1rgUnAGN8eu4viGD9MZBTFt67vg4zWCQXYB1ZyrjHJVc/edit#gid=178001090)**

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) RC Test</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found below.
- Make sure the accessibility-related feature that is being tested doesn't negatively affect the sim in any way. Here is a list of features to supported in this test: 
  - Alternative Input (delete key for deleting selected circuit elements)
  - Interactive Description (not applicable)
  - Sound and Sonification (dog bark)
  - Pan and Zoom
  - Mobile Description (not applicable)
  - Voicing (not applicable)
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (not applicable).
  - Test all forms of input with a screen reader (not applicable).

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Base sim memory test:
<img width="345" alt="basicmem" src="https://user-images.githubusercontent.com/41024075/144678561-50e12f11-6061-4588-84e0-088212becf59.png">
Virtual Lab memory test:
<img width="347" alt="vlmem" src="https://user-images.githubusercontent.com/41024075/144678601-6d76e98e-b17b-496a-aff4-c83a1f2c3c27.png">

**Comment by KatieWoe** [comment]
Performance note, things did lag a bit on the Android app, but it was still useable.

**Comment by Nancy-Salpepi** [comment]
Another performance note: Movement (eg. flow of electrons, stopwatch) is definitely slower with the Chromebook, but the sim never crashed.

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
@arouinfar and I discussed the discovered issues, and marked them for the milestone as appropriate.  https://github.com/phetsims/circuit-construction-kit-common/milestone/2. We will need an RC.2 at least.  Closing.
