### ISSUE TITLE
PhET Desktop App Test: New Sims

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/qa#750]
# Background

The last time the app was built was several months ago. The app available for download on the website is lacking the sims that have been published since then. In https://github.com/phetsims/weddell/issues/80, @oliver-phet told us that a user requested an updated version of the PhET app with new sims.

# Instructions

Technically, these app files are release candidates (hence the label), but this will probably be more like a dev test.

The new PhET app files will be in a folder here: https://bayes.colorado.edu/dev/weddell/dist/.

1. Delete the old PhET app.
2. Download the new PhET app file.
3. Install the new PhET app.
4. Make sure recently published sims like Fourier made it into this version of the app.
5. Make sure all locales are available for the app.

Please also do a general dev test to make sure things are working correctly. If you find an issue, please create a GitHub issue here: https://github.com/phetsims/weddell/issues.

# Checklist

- [x] ~1 hour on Windows 10 (and a bit of time on 11?)
- [x] ~1 hour on macOS

**Comment by liam-mulhall** [comment]
The app files aren't on Bayes yet. I will comment when they are there.

**Comment by liam-mulhall** [comment]
The app files are up: https://bayes.colorado.edu/dev/weddell/dist/2021-12-08/.

**Comment by KatieWoe** [comment]
QA is done

**Comment by liam-mulhall** [comment]
The new version of the app is now published. Closing this issue. Thanks, QA!
