### ISSUE TITLE
RC.3 Circuit Construction Kit AC & AC: Virtual Lab

### ISSUE THREAD

**Issue by samreid** [phetsims/qa#753]
@KatieWoe @arouinfar @ariel-phet @kathy-phet circuit-construction-kit-ac/1.0.0-rc.3 and circuit-construction-kit-ac-virtual-lab/1.0.0-rc.3 are ready for RC testing.  This has been a high priority sim.  Document issues in https://github.com/phetsims/circuit-construction-kit-common/issues and link to this issue.

This is a minor spot check to confirm one issue discovered in rc.2.  None of the code changes seem platform specific.  So just testing on 1 browser sounds good.

Assigning to @kathy-phet and @KatieWoe for prioritization.

<details>

<h3>Focus and Special Instructions</h3>

<h3>Issues to Verify</h3>

- [x] [Should meter tool labels disappear when all tools are in the play area? (note this points to an issue comment)](https://github.com/phetsims/circuit-construction-kit-common/issues/796#issuecomment-991272450)

These issues should have the "status:ready-for-qa" label. Check these issues off and close them if they are fixed.
Otherwise, post a comment in the issue saying that it wasn't fixed and link back to this issue. If the label is
"status:ready-for-review" or "status:fixed-pending-deploy" then assign back to the developer when done, even if fixed.

<h3>Link(s)</h3>

Deployed: 
- **[AC](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.0-rc.3/phet/circuit-construction-kit-ac_all_phet.html)**
- **[AC Virtual Lab](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.0-rc.3/phet/circuit-construction-kit-ac-virtual-lab_all_phet.html)**

- [x] Tester = NS, Platform = macOS12.0.1 + chrome , Time = .5
- [ ] Tester = ??, Platform = ??  , Time = ??

I do not believe the XHTML, iframe, etc. need to be double-checked in this version.  If it is procedure or policy to do so, please do so.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>
  
  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 
  
  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>
  
  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>
  
  We typically assign the developer who opened the issue in the QA repository.

  </details>
  
  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>
  
  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by jessegreenberg** [comment]
Hello! This branch was recently patched for https://github.com/phetsims/scenery/issues/1309. Before a final publication, can we please spot check one more RC to verify that that fix is working in this build? Let me know if you have any questions.

**Comment by samreid** [comment]
I tested https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.0-rc.3/phet/xhtml/circuit-construction-kit-ac-virtual-lab_all.xhtml and the sim did not crash when opening the about dialog.  Is that expected?

**Comment by KatieWoe** [comment]
Yes. The sim should not crash.

**Comment by samreid** [comment]
From slack:


Sam Reid:house_with_garden:  13 minutes ago
I tested https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.0-rc.3/phet/xhtml/circuit-construction-kit-ac-virtual-lab_all.xhtml and the sim did not crash when opening the about dialog.  Is that expected?




Jesse Greenberg  6 minutes ago
OK, yes it is possible that CCK did not have this problem yet.

Sam Reid:house_with_garden:  5 minutes ago
Should we still RC the scenery change?

Jesse Greenberg  < 1 minute ago
I think so, if possible. I wanted to eagerly patch published sims with interactive description even if they didn't exhibit this bug. Without this patch, if a <br> is ever added through a maintenance release to AboutDialog strings (or any other strings) that are used in the PDOM it would crash in XHTML. (edited) 

Sam Reid:house_with_garden:  < 1 minute ago
Sure, I have another RC due to credits changes, so I’ll include spot check for that.

Jesse Greenberg  < 1 minute ago
OK, thank you!

**Comment by samreid** [comment]
I'll be creating RC.4 to spot check credits and XHTML about dialog changes, so I think testing RC.3 can be stopped.
