### ISSUE TITLE
Maintenance testing for XHTML fix

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/qa#755]
Patches have been applied for https://github.com/phetsims/scenery/issues/1309. This is to spot check that the patches were applied correctly and that nothing is broken by the fix.

To verify the fix, please open the About dialog in the XHTML version of the sim and make sure the sim doesn't crash. In addition, please play with each sim for 30-60 seconds to make sure nothing else is broken. I added links to the XHTML versions where appropriate. Please let me know if you have any other questions! Assigning to @KatieWoe and @kathy-phet to prioritize.

Release Candidate links

balloons-and-static-electricity 1.5 (https://github.com/phetsims/scenery/issues/1309)

- [x] [balloons-and-static-electricity 1.5.1-rc.1](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.1-rc.1/phet/balloons-and-static-electricity_en_phet.html)
- [x] [balloons-and-static-electricity 1.5.1-rc.1 XHTML](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.1-rc.1/phet/xhtml/balloons-and-static-electricity_all.xhtml)

circuit-construction-kit-dc 1.2 (https://github.com/phetsims/scenery/issues/1309)

- [x] [circuit-construction-kit-dc 1.2.6-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.6-rc.1/phet/circuit-construction-kit-dc_en_phet.html)
- [x] [circuit-construction-kit-dc 1.2.6-rc.1 XHTML](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.6-rc.1/phet/circuit-construction-kit-dc_en_phet.html)

circuit-construction-kit-dc-virtual-lab 1.2 (https://github.com/phetsims/scenery/issues/1309)

- [x] [circuit-construction-kit-dc-virtual-lab 1.2.6-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.2.6-rc.1/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html)
- [x] [circuit-construction-kit-dc-virtual-lab 1.2.6-rc.1 XHTML](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.2.6-rc.1/phet/xhtml/circuit-construction-kit-dc-virtual-lab_all.xhtml)

coulombs-law 1.0 (https://github.com/phetsims/scenery/issues/1309)

- [x] [coulombs-law 1.0.12-rc.1](https://phet-dev.colorado.edu/html/coulombs-law/1.0.12-rc.1/phet/coulombs-law_en_phet.html)
- [x] [coulombs-law 1.0.12-rc.1 XHTML](https://phet-dev.colorado.edu/html/coulombs-law/1.0.12-rc.1/phet/xhtml/coulombs-law_all.xhtml)

faradays-law 1.4 (https://github.com/phetsims/scenery/issues/1309)

- [x] [faradays-law 1.4.5-rc.1](https://phet-dev.colorado.edu/html/faradays-law/1.4.5-rc.1/phet/faradays-law_en_phet.html)
- [x] [faradays-law 1.4.5-rc.1 XHTML](https://phet-dev.colorado.edu/html/faradays-law/1.4.5-rc.1/phet/xhtml/faradays-law_all.xhtml)

fourier-making-waves 1.0 (https://github.com/phetsims/scenery/issues/1309)

- [x] [fourier-making-waves 1.0.3-rc.1](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.3-rc.1/phet/fourier-making-waves_en_phet.html)
- [x] [fourier-making-waves 1.0.3-rc.1 XHTML](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.3-rc.1/phet/xhtml/fourier-making-waves_all.xhtml)

friction 1.5 (https://github.com/phetsims/scenery/issues/1309)

- [x] [friction 1.5.13-rc.1](https://phet-dev.colorado.edu/html/friction/1.5.13-rc.1/phet/friction_en_phet.html)
- [x] [friction 1.5.13-rc.1 XHTML](https://phet-dev.colorado.edu/html/friction/1.5.13-rc.1/phet/xhtml/friction_all.xhtml)

gravity-force-lab 2.2 (https://github.com/phetsims/scenery/issues/1309)

- [x] [gravity-force-lab 2.2.5-rc.1](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.5-rc.1/phet/gravity-force-lab_en_phet.html)
- [x] [gravity-force-lab 2.2.5-rc.1 XHTML](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.5-rc.1/phet/xhtml/gravity-force-lab_all.xhtml)
- [x] [gravity-force-lab 2.2.5-rc.1 phet-io](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.5-rc.1/phet-io/gravity-force-lab_all_phet-io.html?phetioStandalone)
- [x] [gravity-force-lab 2.2.5-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.5-rc.1/phet-io/wrappers/studio)

gravity-force-lab-basics 1.1 (https://github.com/phetsims/scenery/issues/1309)

- [x] [gravity-force-lab-basics 1.1.1-rc.1](https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.1-rc.1/phet/gravity-force-lab-basics_en_phet.html)
- [x] [gravity-force-lab-basics 1.1.1-rc.1 XHTML](https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.1-rc.1/phet/xhtml/gravity-force-lab-basics_all.xhtml)

greenhouse-effect 1.0 (https://github.com/phetsims/scenery/issues/1309)

- [x] [greenhouse-effect 1.0.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.3-rc.1/phet-io/greenhouse-effect_all_phet-io.html?phetioStandalone)
- [x] [greenhouse-effect 1.0.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.3-rc.1/phet-io/wrappers/studio)

john-travoltage 1.4-phetio (https://github.com/phetsims/scenery/issues/1309)

- [x] [john-travoltage 1.4.19-rc.1 phet-io](https://phet-dev.colorado.edu/html/john-travoltage/1.4.19-phetiorc.1/john-travoltage_en-phetio.html?phetioStandalone)
- [x] [john-travoltage 1.4.19-rc.1 phet-io Instance Proxies](https://phet-dev.colorado.edu/html/john-travoltage/1.4.19-phetiorc.1/wrappers/instance-proxies/instance-proxies.html?sim=john-travoltage&relativeSimPath)

john-travoltage 1.6 (https://github.com/phetsims/scenery/issues/1309)

- [x] [john-travoltage 1.6.2-rc.1](https://phet-dev.colorado.edu/html/john-travoltage/1.6.2-rc.1/phet/john-travoltage_en_phet.html)
- [x] [john-travoltage 1.6.2-rc.1 XHTML](https://phet-dev.colorado.edu/html/john-travoltage/1.6.2-rc.1/phet/xhtml/john-travoltage_all.xhtml)

molarity 1.4 (https://github.com/phetsims/scenery/issues/1309)

- [x] [molarity 1.4.15-rc.1 phet-io](https://phet-dev.colorado.edu/html/molarity/1.4.15-rc.1/phet-io/molarity_all_phet-io.html?phetioStandalone)
- [x] [molarity 1.4.15-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molarity/1.4.15-rc.1/phet-io/wrappers/studio/studio.html?sim=molarity&relativeSimPath)

molarity 1.5 (https://github.com/phetsims/scenery/issues/1309)

- [x] [molarity 1.5.5-rc.1](https://phet-dev.colorado.edu/html/molarity/1.5.5-rc.1/phet/molarity_en_phet.html)
- [x] [molarity 1.5.5-rc.1 XHTML](https://phet-dev.colorado.edu/html/molarity/1.5.5-rc.1/phet/xhtml/molarity_all.xhtml)

molecules-and-light 1.5 (https://github.com/phetsims/scenery/issues/1309)

- [x] [molecules-and-light 1.5.12-rc.2](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.12-rc.2/phet/molecules-and-light_en_phet.html)
- [x] [molecules-and-light 1.5.12-rc.2 XHTML](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.12-rc.2/phet/xhtml/molecules-and-light_all.xhtml)

ohms-law 1.4 (https://github.com/phetsims/scenery/issues/1309)

- [x] [ohms-law 1.4.12-rc.1](https://phet-dev.colorado.edu/html/ohms-law/1.4.12-rc.1/phet/ohms-law_en_phet.html)
- [x] [ohms-law 1.4.12-rc.1 XHTML](https://phet-dev.colorado.edu/html/ohms-law/1.4.12-rc.1/phet/xhtml/ohms-law_all.xhtml)

ratio-and-proportion 1.0 (https://github.com/phetsims/scenery/issues/1309)

- [x] [ratio-and-proportion 1.0.4-rc.1](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.4-rc.1/phet/ratio-and-proportion_en_phet.html)
- [x] [ratio-and-proportion 1.0.4-rc.1 XHTML](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.4-rc.1/phet/xhtml/ratio-and-proportion_all.xhtml)

resistance-in-a-wire 1.6 (https://github.com/phetsims/scenery/issues/1309)

- [x] [resistance-in-a-wire 1.6.13-rc.1](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.13-rc.1/phet/resistance-in-a-wire_en_phet.html)
- [x] [resistance-in-a-wire 1.6.13-rc.1 XHTML](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.13-rc.1/phet/xhtml/resistance-in-a-wire_all.xhtml)

waves-intro 1.1 (https://github.com/phetsims/scenery/issues/1309)

- [x] [waves-intro 1.1.5-rc.1](https://phet-dev.colorado.edu/html/waves-intro/1.1.5-rc.1/phet/waves-intro_en_phet.html)
- [x] [waves-intro 1.1.5-rc.1 XHTML](https://phet-dev.colorado.edu/html/waves-intro/1.1.5-rc.1/phet/xhtml/waves-intro_all.xhtml)

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Excellent, thanks @KatieWoe - Ill proceed with production deploys in https://github.com/phetsims/scenery/issues/1309. Closing.
