### ISSUE TITLE
dev test: Number Play 1.0.0-dev.35 - Game screen

### ISSUE THREAD

**Issue by chrisklus** [phetsims/qa#761]
@amanda-phet, @kathy-phet, @KatieWoe number-play/1.0.0-dev.35 Game screen is ready for dev testing. This will be part of a prototype release that is scheduled for the end of January. Please document issues in https://github.com/phetsims/number-play/issues and link to this issue.

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>Focus and Special Instructions</h3>

The objects in the play areas in the Counting game (dogs, cupcakes, beach balls, apples) are from code that is actively being worked on and still have known problems. This is the only part of the screen that issues do not need to be made for. Everything else about the screen should be fully tested. For faster iteration through the levels, this game uses the standard `showAnswers` query parameter.

Two public query parameters are included with this game and should be tested: `subitizerTimeVisible` and `gameLevels`. Details about their usage are in [NumberPlayQueryParameter.js](https://github.com/phetsims/number-play/blob/master/js/common/NumberPlayQueryParameters.ts).

For any questions about the game behavior, please reach out to @chrisklus or @Luisav1 on Slack.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time =  2.5)
- [x] Windows 10, Chrome (Time = 3)
- [x] Windows 10, Firefox (Time = 2 hrs)
- [x] Latest iOS, Safari (Time = 1.5 )
- [x] Win 11 Chrome (Time = 2.5)

Light testing, or optionally skip if time crunch: 
- [x] Latest macOS, Chrome (Time = 1)
- [ ] Latest Chrome OS, Chrome (Time = )

These issues should have either use the labels "status:ready-for-qa" or "status:ready-for-review." If it is ready for
QA then close the issue if fixed. If ready for review then leave open and assign back to the developer.

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.35/phet/number-play_all_phet.html?screens=4)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
QA is done

**Comment by chrisklus** [comment]
Awesome, thanks so much yall!

**Comment by chrisklus** [comment]
All issues have been fixed, closing.
