### ISSUE TITLE
Website: Prototype changes for Sim Pages and Filter Pages

### ISSUE THREAD

**Issue by mattpen** [phetsims/qa#764]
@KatieWoe the website sim pages and filter page could use some light testing regarding changes to highlight prototype sims. Document issues in https://github.com/phetsims/website-meteor/issues and link to this
issue.  Changes are described in https://github.com/phetsims/website-meteor/issues/409

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>Test Summary</b></summary>

<h3>What to Test</h3>

- Check all prototype sim pages, including prototype pages ([geometric optics](https://ox-dev.colorado.edu/en/simulations/geometric-optics), [normal modes](https://ox-dev.colorado.edu/en/simulations/normal-modes), [greenhouse effect](https://ox-dev.colorado.edu/en/simulations/greenhouse-effect)) 
- Check an HTML sim, a Flash sim, and a cheerpj sim that aren't listed in the previous bullet to confirm that they aren't marked as prototype pages.
- On the pages check, make sure all content is visible and accessible on all tabs on each prototype page.
- Make sure the main play link is checked and that the links in the Translation table are checked.  
    - Java sims with cheerpj or prototype versions should launch a dialog when these links are checked with all of the run options.
- Check the filter page and make sure that all Compatibility filters work as expected.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time = 3 hrs )
- [x] Windows 10/11, Chrome (Time = 4.5)
- [x] Windows 10/11, Firefox (Time = 2.75)
- [x] Latest iOS, Safari (Time = 1)

Light testing, or optionally skip if time crunch: 
- [x] Latest macOS, Chrome (Time = .5 )
- [ ] Latest Chrome OS, Chrome (Time = )

<h3>Link(s)</h3>

- [geometric optics](https://ox-dev.colorado.edu/en/simulations/geometric-optics)
- [normal modes](https://ox-dev.colorado.edu/en/simulations/normal-modes)
- [greenhouse effect](https://ox-dev.colorado.edu/en/simulations/greenhouse-effect)
- Test the filter page results linked from the Simulation menu in the persistent nav (Translated Sims can be skipped).
<img src="https://user-images.githubusercontent.com/11747676/150199631-e07fab88-bf14-43cd-83b3-9094adf1aa4f.png" height=200/>

<hr>

</details>

<details>
<summary><b>Accessibility (a11y) Test</b></summary>

<h3>What to Test</h3>

- Make sure all the new prototype-related content listed above is accessible with screen readers and/or keyboard navigation

<h3>Screen Readers</h3>

The website supports screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to screen
readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have all of
the information you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view
before opening the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as
intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- [x] Windows 10 + Latest Chrome + Latest JAWS
- [x] Windows 10 + Latest Firefox + Latest NVDA
- [x] macOS + Safari + VoiceOver
- [x] iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[this Google Document](https://drive.google.com/open?id=12kTs-g-iKEIH1dyG7Q41_W_oNL4gUKbkW-IQgZjMUBw). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This website supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
QA is done

**Comment by mattpen** [comment]
These changes were deployed, test is complete
