### ISSUE TITLE
QA should get some devices that will support testing of haptics

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#765]
There are two initiatives right now that are creating Android-based apps that make use of vibratory haptics.  The first is the "Haptics Playground", which is being developed in [the quake repository](https://github.com/phetsims/quake).  The other is an app that will contain the Quadrilaterals simulation and will allow the use of haptics and speech-to-text capabilities, and for which there is not yet a repo.

The primary test device so far for the Haptics Playground is a Samsung Tab S7, model SM-T870.  QA should probably get at least one of these, and possibly one or more other Android devices that support vibration.  See the table in https://github.com/phetsims/quake/issues/4 for more information on what devices may work.

This should probably be funded under the a11y grants, but I'm not entirely sure.

Assigning to @oliver-phet and @KatieWoe to start the discussion of how these should be paid for, what we should get, and who should get them.  My estimate is that the development team will start to need some testing of these apps in about a month.

Tagging @jessegreenberg and @BLFiedler so that they are aware of this, since they are both working on the Quadrilaterals sim and the research that we hope to support with it.

**Comment by oliver-phet** [comment]
@KatieWoe Does QA already have any supported device? If not, what Android device might be most useful for QA beyond  haptics testing?

**Comment by KatieWoe** [comment]
I don't believe we do. We have an Android tablet, but I believe that it doesn't support haptics from when we last checked. I would need to do some research into Android devices to list a specific model, but a tablet that supports the latest available OS would be best. The current tablet only supports Android 8.1

**Comment by stemilymill** [comment]
My phone (samsung galaxy s21 ultra) seems to work with the patterns on http://www.hapticsjs.org/

**Comment by jbphet** [comment]
@KatieWoe said:

>  I would need to do some research into Android devices to list a specific model...

Perhaps, but as I mentioned in the opening comment, there is a list of devices that should work list in https://github.com/phetsims/quake/issues/4.

**Comment by oliver-phet** [comment]
Doing some issue hygiene - is there still an active need for haptics devices?

**Comment by KatieWoe** [comment]
We've had to do testing for it once so far. If this is going to be a frequent feature that comes through testing I think QA should have something. But if it is going to remain rare I'm not sure. @jbphet what do you see going forward?

**Comment by brettfiedler** [comment]
From the Inclusive Design team side - there are no current plans for haptics development that would call for a haptics-capable device in QA. That may change in the future with any changes in funding, of course. For the two cases this issue was opened for: Quadrilateral haptics was indefinitely postponed pending collaborator interest or future funding. Haptics Playground is stable enough as a tool for use prototyping with compatible devices. It also isn't seeing active development for the foreseeable future.

**Comment by KatieWoe** [comment]
In that case, I don't think QA needs such a device at this time. Closing
