### ISSUE TITLE
Dev test: Function Builder: Basics 1.2.0-dev.2

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#767]
@amanda-phet @kathy-phet @KatieWoe _Function Builder: Basics_ 1.2.0-dev.2 is ready for dev testing. 

The motivation for this release is Legends of Learning support. There are no PhET-iO or A11y features. A full dev test is required.  

Note that _Function Builder: Basics_ is related to _Function Builder_. _Function Builder_ dev test https://github.com/phetsims/qa/issues/766 should be done at the same time. The _Patterns_ screen is identical in both sims. But while both sims have a _Mystery_ screen, _Function Builder: Basics_ is different; instead of numeric cards and functions, it uses pattern (image) cards and functions.

Document issues in https://github.com/phetsims/function-builder/issues (not function-builder-basics) and link to this issue.

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time = 1 hr)
- [x] Windows 10/11, Chrome (Time = .75)
- [ ] Windows 10, Firefox (Time = )
- [x] Latest iOS, Safari (Time = 1)

Light testing, or optionally skip if time crunch: 
- [x] Latest macOS, Chrome (Time = .75 hrs)
- [ ] Latest Chrome OS, Chrome (Time = )

<h3>Link(s)</h3>

- **[Simulation - 1.2.0-dev.2](https://phet-dev.colorado.edu/html/function-builder-basics/1.2.0-dev.2/phet/function-builder-basics_all_phet.html)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by pixelzoom** [comment]
Higher priority issues were added to the QA queue, and the dev version (1.2.0-dev.1) is now too old.  So please contact me when QA is ready to proceed, and I'll publish a fresh dev version.

**Comment by pixelzoom** [comment]
@KatieWoe 1.2.0-dev.2 is now ready for testing. I've adjusted the issue title and links accordingly.

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
Status summarized in https://github.com/phetsims/function-builder/issues/139#issuecomment-1042401347.  Per @kathy-phet in https://github.com/phetsims/function-builder/issues/139#issuecomment-1036801766, we'll be doing another dev test after blocking issues are resolved.

Closing.
