### ISSUE TITLE
RC Test Forces and Motion Basics 2.3.0-rc.5

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#77]
@ariel-phet @phet-steele, Forces and Motion: Basics 2.3.0-rc.5 is ready for a spot check for RC testing.

**[Link to sim](https://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-rc.5/forces-and-motion-basics_en.html)**

**[Link to iFrame](https://www.colorado.edu/physics/phet/dev/html/forces-and-motion-basics/2.3.0-rc.5/forces-and-motion-basics_en-iframe.html)**

**Issues to Verify**
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.
- [x] phetsims/forces-and-motion-basics#252
- [x] phetsims/forces-and-motion-basics#250

If any new issues are found, please note them in https://github.com/phetsims/forces-and-motion-basics/issues and reference this issue.

**Comment by jessegreenberg** [comment]
During deploy-rc I received an error notification from build-server, and want to  check in with @mattpen before reassigning for testing.

Sim and iframe test made it to spot but dependencies.json is missing, and maybe other things are missing too.

**Comment by jessegreenberg** [comment]
I just want to verify that  this built version is OK, or determine if we need a new build for rc testing and then deploy-production.

@jonathanolson also recommended to check build server logs and said there were steps in sim_deployment.md.

**Comment by jessegreenberg** [comment]
@mattpen fixed the problem and asked me to rebuild. Everything looks great. Ill update issue title and links since I updated rc version number for new build.

**Comment by jessegreenberg** [comment]
Thanks for the help @mattpen, assigning to @phet-steele.

**Comment by phet-steele** [comment]
@jessegreenberg you can go ahead and release this version. @arouinfar please notify LoL.

**Comment by jessegreenberg** [comment]
Thanks @phet-steele FAMB 2.3.0 deployed with LoL support:
https://phet.colorado.edu/sims/html/forces-and-motion-basics/latest/forces-and-motion-basics_en.html

Next need to deploy 2.3-phet-io.

**Comment by jessegreenberg** [comment]
2.3-phetio has been deployed. Thanks for the testing @phet-steele and team, great to have this done :)
