### ISSUE TITLE
Maintenance spot check for build fix

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/qa#770]
For the maintenance release https://github.com/phetsims/chipper/issues/1189.

I'd appreciate a 5-15 second test per sim below, to make sure nothing is horribly broken (and some sims had client guide updates that I had to fix, checking that the client guides load on phet-io sims would be helpful).

The patch should be fixing something that deals with how the simulations are built, so this should cause no changes to the actual simulations themselves.

atomic-interactions 1.2 (https://github.com/phetsims/chipper/issues/1189)

- [x] [atomic-interactions 1.2.4-rc.1](https://phet-dev.colorado.edu/html/atomic-interactions/1.2.4-rc.1/phet/atomic-interactions_en_phet.html)

balancing-act 1.2 (https://github.com/phetsims/chipper/issues/1189)

- [x] [balancing-act 1.2.9-rc.1 phet-io](https://phet-dev.colorado.edu/html/balancing-act/1.2.9-rc.1/phet-io/balancing-act_all_phet-io.html?phetioStandalone)
- [ ] [balancing-act 1.2.9-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/balancing-act/1.2.9-rc.1/phet-io/wrappers/studio)

build-a-molecule 1.0 (https://github.com/phetsims/chipper/issues/1189)

- [x] [build-a-molecule 1.0.6-rc.1](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.6-rc.1/phet/build-a-molecule_en_phet.html)

circuit-construction-kit-ac 1.0 (https://github.com/phetsims/chipper/issues/1189)

- [x] [circuit-construction-kit-ac 1.0.1-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.1-rc.1/phet/circuit-construction-kit-ac_en_phet.html)

circuit-construction-kit-ac-virtual-lab 1.0 (https://github.com/phetsims/chipper/issues/1189)

- [x] [circuit-construction-kit-ac-virtual-lab 1.0.1-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.1-rc.1/phet/circuit-construction-kit-ac-virtual-lab_en_phet.html)

circuit-construction-kit-dc 1.2 (https://github.com/phetsims/chipper/issues/1189)

- [x] [circuit-construction-kit-dc 1.2.7-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.2.7-rc.1/phet/circuit-construction-kit-dc_en_phet.html)

circuit-construction-kit-dc-virtual-lab 1.2 (https://github.com/phetsims/chipper/issues/1189)

- [x] [circuit-construction-kit-dc-virtual-lab 1.2.7-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.2.7-rc.1/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html)

collision-lab 1.1 (https://github.com/phetsims/chipper/issues/1189)

- [x] [collision-lab 1.1.5-rc.1](https://phet-dev.colorado.edu/html/collision-lab/1.1.5-rc.1/phet/collision-lab_en_phet.html)

density 1.0 (https://github.com/phetsims/chipper/issues/1189)

- [x] [density 1.0.1-rc.1](https://phet-dev.colorado.edu/html/density/1.0.1-rc.1/phet/density_en_phet.html)
- [x] [density 1.0.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/density/1.0.1-rc.1/phet-io/density_all_phet-io.html?phetioStandalone)
- [x] [density 1.0.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/density/1.0.1-rc.1/phet-io/wrappers/studio)

energy-forms-and-changes 1.4 (https://github.com/phetsims/chipper/issues/1189)

- [x] [energy-forms-and-changes 1.4.4-rc.1](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.4-rc.1/phet/energy-forms-and-changes_en_phet.html)
- [x] [energy-forms-and-changes 1.4.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.4-rc.1/phet-io/energy-forms-and-changes_all_phet-io.html?phetioStandalone)
- [x] [energy-forms-and-changes 1.4.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/energy-forms-and-changes/1.4.4-rc.1/phet-io/wrappers/studio)

energy-skate-park 1.1 (https://github.com/phetsims/chipper/issues/1189)

- [x] [energy-skate-park 1.1.5-rc.1](https://phet-dev.colorado.edu/html/energy-skate-park/1.1.5-rc.1/phet/energy-skate-park_en_phet.html)

equality-explorer 1.1 (https://github.com/phetsims/chipper/issues/1189)

- [x] [equality-explorer 1.1.1-rc.1](https://phet-dev.colorado.edu/html/equality-explorer/1.1.1-rc.1/phet/equality-explorer_en_phet.html)

faradays-law 1.4 (https://github.com/phetsims/chipper/issues/1189)

- [x] [faradays-law 1.4.6-rc.1](https://phet-dev.colorado.edu/html/faradays-law/1.4.6-rc.1/phet/faradays-law_en_phet.html)

graphing-quadratics 1.1 (https://github.com/phetsims/chipper/issues/1189)

- [x] [graphing-quadratics 1.1.8-rc.1 phet-io](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.8-rc.1/phet-io/graphing-quadratics_all_phet-io.html?phetioStandalone)
- [x] [graphing-quadratics 1.1.8-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/graphing-quadratics/1.1.8-rc.1/phet-io/wrappers/studio)

graphing-quadratics 1.2 (https://github.com/phetsims/chipper/issues/1189)

- [x] [graphing-quadratics 1.2.3-rc.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.3-rc.1/phet/graphing-quadratics_en_phet.html)
- [x] [graphing-quadratics 1.2.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.3-rc.1/phet-io/graphing-quadratics_all_phet-io.html?phetioStandalone)
- [x] [graphing-quadratics 1.2.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/graphing-quadratics/1.2.3-rc.1/phet-io/wrappers/studio)

gravity-and-orbits 1.4 (https://github.com/phetsims/chipper/issues/1189)

- [x] [gravity-and-orbits 1.4.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.4.4-rc.1/phet-io/gravity-and-orbits_all_phet-io.html?phetioStandalone)
- [x] [gravity-and-orbits 1.4.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.4.4-rc.1/phet-io/wrappers/studio)

gravity-and-orbits 1.5 (https://github.com/phetsims/chipper/issues/1189)

- [x] [gravity-and-orbits 1.5.3-rc.1](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.3-rc.1/phet/gravity-and-orbits_en_phet.html)
- [x] [gravity-and-orbits 1.5.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.3-rc.1/phet-io/gravity-and-orbits_all_phet-io.html?phetioStandalone)
- [x] [gravity-and-orbits 1.5.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.5.3-rc.1/phet-io/wrappers/studio)

gravity-force-lab 2.2 (https://github.com/phetsims/chipper/issues/1189)

- [x] [gravity-force-lab 2.2.6-rc.1](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.6-rc.1/phet/gravity-force-lab_en_phet.html)
- [x] [gravity-force-lab 2.2.6-rc.1 phet-io](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.6-rc.1/phet-io/gravity-force-lab_all_phet-io.html?phetioStandalone)
- [x] [gravity-force-lab 2.2.6-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/gravity-force-lab/2.2.6-rc.1/phet-io/wrappers/studio)

gravity-force-lab-basics 1.1 (https://github.com/phetsims/chipper/issues/1189)

- [x] [gravity-force-lab-basics 1.1.2-rc.1](https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.2-rc.1/phet/gravity-force-lab-basics_en_phet.html)

john-travoltage 1.6 (https://github.com/phetsims/chipper/issues/1189)

- [x] [john-travoltage 1.6.3-rc.1](https://phet-dev.colorado.edu/html/john-travoltage/1.6.3-rc.1/phet/john-travoltage_en_phet.html)

molarity 1.4 (https://github.com/phetsims/chipper/issues/1189)

- [x] [molarity 1.4.16-rc.1 phet-io](https://phet-dev.colorado.edu/html/molarity/1.4.16-rc.1/phet-io/molarity_all_phet-io.html?phetioStandalone)
- [x] [molarity 1.4.16-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molarity/1.4.16-rc.1/phet-io/wrappers/studio/studio.html?sim=molarity&relativeSimPath)

molarity 1.5 (https://github.com/phetsims/chipper/issues/1189)

- [x] [molarity 1.5.6-rc.1](https://phet-dev.colorado.edu/html/molarity/1.5.6-rc.1/phet/molarity_en_phet.html)

molecule-polarity 1.2 (https://github.com/phetsims/chipper/issues/1189)

- [x] [molecule-polarity 1.2.3-rc.1](https://phet-dev.colorado.edu/html/molecule-polarity/1.2.3-rc.1/phet/molecule-polarity_en_phet.html)
- [x] [molecule-polarity 1.2.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/molecule-polarity/1.2.3-rc.1/phet-io/molecule-polarity_all_phet-io.html?phetioStandalone)
- [x] [molecule-polarity 1.2.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-polarity/1.2.3-rc.1/phet-io/wrappers/studio)

molecules-and-light 1.5 (https://github.com/phetsims/chipper/issues/1189)

- [x] [molecules-and-light 1.5.13-rc.1](https://phet-dev.colorado.edu/html/molecules-and-light/1.5.13-rc.1/phet/molecules-and-light_en_phet.html)

natural-selection 1.2 (https://github.com/phetsims/chipper/issues/1189)

- [x] [natural-selection 1.2.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/natural-selection/1.2.4-rc.1/phet-io/natural-selection_all_phet-io.html?phetioStandalone)
- [x] [natural-selection 1.2.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/natural-selection/1.2.4-rc.1/phet-io/wrappers/studio)

natural-selection 1.3 (https://github.com/phetsims/chipper/issues/1189)

- [x] [natural-selection 1.3.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/natural-selection/1.3.4-rc.1/phet-io/natural-selection_all_phet-io.html?phetioStandalone)
- [x] [natural-selection 1.3.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/natural-selection/1.3.4-rc.1/phet-io/wrappers/studio)

natural-selection 1.4 (https://github.com/phetsims/chipper/issues/1189)

- [x] [natural-selection 1.4.3-rc.1](https://phet-dev.colorado.edu/html/natural-selection/1.4.3-rc.1/phet/natural-selection_en_phet.html)
- [x] [natural-selection 1.4.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/natural-selection/1.4.3-rc.1/phet-io/natural-selection_all_phet-io.html?phetioStandalone)
- [x] [natural-selection 1.4.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/natural-selection/1.4.3-rc.1/phet-io/wrappers/studio)

number-line-distance 1.0 (https://github.com/phetsims/chipper/issues/1189)

- [x] [number-line-distance 1.0.2-rc.1](https://phet-dev.colorado.edu/html/number-line-distance/1.0.2-rc.1/phet/number-line-distance_en_phet.html)

number-line-integers 1.1 (https://github.com/phetsims/chipper/issues/1189)

- [x] [number-line-integers 1.1.4-rc.1](https://phet-dev.colorado.edu/html/number-line-integers/1.1.4-rc.1/phet/number-line-integers_en_phet.html)

number-line-operations 1.0 (https://github.com/phetsims/chipper/issues/1189)

- [x] [number-line-operations 1.0.5-rc.1](https://phet-dev.colorado.edu/html/number-line-operations/1.0.5-rc.1/phet/number-line-operations_en_phet.html)

ph-scale 1.5 (https://github.com/phetsims/chipper/issues/1189)

- [x] [ph-scale 1.5.3-rc.1](https://phet-dev.colorado.edu/html/ph-scale/1.5.3-rc.1/phet/ph-scale_en_phet.html)
- [x] [ph-scale 1.5.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/ph-scale/1.5.3-rc.1/phet-io/ph-scale_all_phet-io.html?phetioStandalone)
- [x] [ph-scale 1.5.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/ph-scale/1.5.3-rc.1/phet-io/wrappers/studio)

ph-scale-basics 1.5 (https://github.com/phetsims/chipper/issues/1189)

- [x] [ph-scale-basics 1.5.3-rc.1](https://phet-dev.colorado.edu/html/ph-scale-basics/1.5.3-rc.1/phet/ph-scale-basics_en_phet.html)
- [x] [ph-scale-basics 1.5.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/ph-scale-basics/1.5.3-rc.1/phet-io/ph-scale-basics_all_phet-io.html?phetioStandalone)
- [x] [ph-scale-basics 1.5.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/ph-scale-basics/1.5.3-rc.1/phet-io/wrappers/studio)

ratio-and-proportion 1.0 (https://github.com/phetsims/chipper/issues/1189)

- [x] [ratio-and-proportion 1.0.5-rc.1](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.5-rc.1/phet/ratio-and-proportion_en_phet.html)

states-of-matter 1.2 (https://github.com/phetsims/chipper/issues/1189)

- [x] [states-of-matter 1.2.5-rc.1](https://phet-dev.colorado.edu/html/states-of-matter/1.2.5-rc.1/phet/states-of-matter_en_phet.html)
- [x] [states-of-matter 1.2.5-rc.1 phet-io](https://phet-dev.colorado.edu/html/states-of-matter/1.2.5-rc.1/phet-io/states-of-matter_all_phet-io.html?phetioStandalone)
- [x] [states-of-matter 1.2.5-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/states-of-matter/1.2.5-rc.1/phet-io/wrappers/studio)

states-of-matter-basics 1.2 (https://github.com/phetsims/chipper/issues/1189)

- [x] [states-of-matter-basics 1.2.4-rc.1](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.4-rc.1/phet/states-of-matter-basics_en_phet.html)
- [x] [states-of-matter-basics 1.2.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.4-rc.1/phet-io/states-of-matter-basics_all_phet-io.html?phetioStandalone)
- [x] [states-of-matter-basics 1.2.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/states-of-matter-basics/1.2.4-rc.1/phet-io/wrappers/studio)

vector-addition 1.0 (https://github.com/phetsims/chipper/issues/1189)

- [x] [vector-addition 1.0.3-rc.1](https://phet-dev.colorado.edu/html/vector-addition/1.0.3-rc.1/phet/vector-addition_en_phet.html)

vector-addition-equations 1.0 (https://github.com/phetsims/chipper/issues/1189)

- [x] [vector-addition-equations 1.0.3-rc.1](https://phet-dev.colorado.edu/html/vector-addition-equations/1.0.3-rc.1/phet/vector-addition-equations_en_phet.html)

waves-intro 1.1 (https://github.com/phetsims/chipper/issues/1189)

- [x] [waves-intro 1.1.6-rc.1](https://phet-dev.colorado.edu/html/waves-intro/1.1.6-rc.1/phet/waves-intro_en_phet.html)

**Comment by KatieWoe** [comment]
QA is done

**Comment by jonathanolson** [comment]
Thanks!
