### ISSUE TITLE
dev test: Number Play 1.0.0-dev.45 - screens 1-3

### ISSUE THREAD

**Issue by chrisklus** [phetsims/qa#771]
@amanda-phet, @kathy-phet, @KatieWoe number-play/1.0.0-dev.40 (screens 1-3) is ready for dev testing. This will be part of a prototype release that is scheduled end of next week. Please do not test the game screen, as it was recently tested and I haven't quite wrapped up the fixes over there. Please document issues in https://github.com/phetsims/number-play/issues and link to this issue.

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>Focus and Special Instructions</h3>

There are two public query parameters applicable to this dev test: `countAloud` and `secondLocale`. Please include those in this test. The only other locale that will currently work with `secondLocale` is `es`. When a valid locale is added, a switch will be added on all three screens that can toggle the locale of the written numbers, "compare statement", and the spoken speech. Please note that the strings for the labels of that switch are currently hard coded and will not necessarily represent the locale that was loaded.

The other focus is the play areas (the lower two accordion boxes on all three screens). We would like to know if and how the number of objects in the play area can get out of sync with the total number (in the Total accordion box). Please see the issue in "Issues to Verify" for more information and known bugs.

For any questions, please reach out to me (@chrisklus) on Slack.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time = 3hrs)
- [x] Windows 10, Chrome (Time = 2)
- [x] Windows 10, Firefox (Time = 2.25hrs)
- [x] Latest iOS, Safari (Time = 2)
- [x] Win 11 Chrome (Time = 3)

Light testing, or optionally skip if time crunch: 
- [x] Latest macOS, Chrome (Time = 1.5hrs)
- [x] Latest Chrome OS, Chrome (Time = 1)

<h3>Issues to Verify</h3>

- [x] [Play areas can get out of sync with the total](https://github.com/phetsims/number-play/issues/124)

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/number-play/1.0.0-dev.45/phet/number-play_all_phet.html?screens=1,2,3)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by chrisklus** [comment]
Ready to continue testing

**Comment by KatieWoe** [comment]
QA is done

**Comment by kathy-phet** [comment]
Thanks, QA!

**Comment by chrisklus** [comment]
Another test was opened in https://github.com/phetsims/qa/issues/797#issuecomment-1100453733, closing.
