### ISSUE TITLE
Dev test: Circuit Construction Kit: DC PhET-iO

### ISSUE THREAD

**Issue by samreid** [phetsims/qa#772]
@arouinfar, @kathy-phet, @KatieWoe, circuit-construction-kit-dc/1.3.0-dev.14/phet-io/ is ready for dev testing. We will
share this with a client and working toward full publication this quarter. Document issues in https://github.com/phetsims/circuit-construction-kit-common/issues and link to this
issue. I put it at the bottom of Active Tests in the QA pipeline, but please reprioritize as appropriate.

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>General Dev Test</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<h3>Focus and Special Instructions</h3>

This test is mainly for PhET-iO.  Most of the testing can be done there, but I recommend at least spot checks to make
sure there are no regressions or unexpected behaviors in the PhET-brand version.

<h3>General Dev Test Platforms</h3>
  
  Please include (non-screen reader) a11y testing in these records if applicable.

- [x] Latest macOS, Safari (Time = .75 hrs)
- [x] Windows 10, Chrome (Time = 1 hr)
- [ ] Windows 10, Firefox (Time = 1)
- [x] Latest iOS, Safari (Time = .75 hrs)
- [x] Windows 11, Chrome (Time = 1)

Light testing, or optionally skip if time crunch: 
- [x] Latest macOS, Chrome (Time = .75)
- [ ] Latest Chrome OS, Chrome (Time = .25)

<h3>Link(s)</h3>

- **[Simulation](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.14/phet/circuit-construction-kit-dc_all_phet.html)**

<hr>

</details>

<details>
<summary><b>PhET-iO Dev Test</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
sure the simulation loads without crashing or throwing errors.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time =6 hrs)
- [x] Latest iOS, Safari (Time = 2 hrs)
- [x] Windows 10, Chrome (Time = 6)
- [x] Windows 10/11, Firefox (Time = 3)
- [x] Windows 11, Chrome (Time = 1)
- [x] Latest Chrome OS, Chrome (Time = 1.5)

<h3>Focus and Special Instructions</h3>

This is an initial release for PhET-iO support in Circuit Construction Kit.  All major PhET-iO features should be working.
The studio tree should seem reasonable.  Some issues we addressed for this milestone are listed in:
https://github.com/phetsims/circuit-construction-kit-common/milestone/4

Some issues we moved to a later milestone are:
https://github.com/phetsims/circuit-construction-kit-common/milestone/5

<h3>Link(s)</h3>

- **[Wrapper Index](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-dev.14/phet-io/)**

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by samreid** [comment]
Also, it doesn't seem that @arouinfar has identified Featured vs All, so you may need to select "All" in studio for much of the testing.

**Comment by KatieWoe** [comment]
Memory test for PhET-iO:
<img width="347" alt="memtest" src="https://user-images.githubusercontent.com/41024075/152599580-02a01afc-6caf-4df0-84f7-5ceba16b0e03.png">

**Comment by KatieWoe** [comment]
QA is done

**Comment by samreid** [comment]
Issues triaged and addressed, thanks everyone!  I'll create another dev version soon.  Closing.
