### ISSUE TITLE
Website: test new backend (phet-server2)

### ISSUE THREAD

**Issue by mattpen** [phetsims/qa#773]
The new backend server is ready and needs some tests to ensure everything is working correctly.  [ox-dev](https://ox-dev.colorado.edu/) is currently being served with phet-server2 as the backend for testing.  There are minimal or no code changes involved in this change, we just want to make sure everything is in an operational state. Document issues in https://github.com/phetsims/website/issues and link to this
issue. 

Assigning @kathy-phet and @KatieWoe for prioritization.

<details>
<summary><b>Test Summary</b></summary>

<h3>What to Test</h3>

- Starting from the home page at https://ox-dev.colorado.edu/, we should test that all pages are working correctly on the entire site.  Basically test that every link in the header/navigation, footer, and throughout the main page content are working correctly.
- Some functionality is known to now be working and this is ok for the dev test.  This includes:
    - Activity creation/edit - if you add or edit the linked files it probably will not work correctly.
    - Translation - rosetta is still being installed
- Things to skip: 
    - Admin pages - these are probably working but do NOT need to be tested, we can fix these after the production switch as needed. This includes anything linked from the "Administration" drop down in the user menu.
    - Simulations - the sims themselves aren't actually changing and don't need to be tested

#### EDIT:

- Some links in this test will point to https://phet.colorado.edu instead of ox-dev.  If you find a link like this, just replace phet with ox-dev in the address bar and it should work.

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time = 3 hrs)
- [x] Windows 10/11, Chrome (Time = 4)
- [x] Windows 10/11, Firefox (Time = 4)
- [x] Latest iOS, Safari (Time = 2.5)

<h3>Link(s)</h3>

- https://ox-dev.colorado.edu, and all links within

</details>

<hr>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
QA is done

**Comment by mattpen** [comment]
Thanks @KatieWoe!
