### ISSUE TITLE
Streamline the QA templates.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#776]
In 2/17/22 QA meeting, we discussed how QA templates can improved to streamline the proceed of filling them in, while still providing the info that QA needs. @pixelzoom and @KatieWoe will work together on streamlining the QA issue templates. 

Suggestions include:

* Move stuff to the top that developers need to fill in.
* Provide links to: top-level deploy directory, all.html, wrapper index.
* 1 section for "Issues to Verify"
* 1 section for "Focus and Special Instructions"
* Consider whether some things can be moved to the QA Book
* Checklist for what features are included (phet-io, alt input, UI sound, ...)

Potential changes to build tools:

* Make the `grunt` task print links that are needed to fill in the templates.
* Include links in "Build succeeded" email from build server.

**Comment by pixelzoom** [comment]
@KatieWoe and I worked on revising rc-test-template-NEW.md.  We did this by editing a new copy at https://github.com/phetsims/qa/blob/master/issue-templates/rc-test-template-NEW.md.  We're pretty happy with this, and will previw it at 3/3/2022 dev meeting.  Then @KatieWoe will propagate similar changes to all of the issue templates.

**Comment by pixelzoom** [comment]
3/3/2022 dev meeting.

@KatieWoe and I presented the new RC Test template to developers. They had some good feedback, which we incorporated in real time.  I verified that the links in the template are accurate.  So this pattern is ready to incorporate into other templates.

**Comment by pixelzoom** [comment]
Slack:

[Kathryn Woessner](https://app.slack.com/team/UBLN0PWJU)  [4:44 PM](https://phetsims.slack.com/archives/DBQK9V6LF/p1646351062088989)
Kathy pointed out https://github.com/bdougie/variables-in-markdown/blob/master/README.md, which might make it easier for developers to fill out the links in the template. Let me know if it's a good idea.




[Chris Malley](https://app.slack.com/team/U6EMFARV2)  [4:53 PM](https://phetsims.slack.com/archives/DBQK9V6LF/p1646351609669339)
Interesting… But I think we should stick with {{TOKEN}}  for now because:

* There’s no need to automate this via a GitHub action, that would be overkill. 
* There are only 2 variables to search-and-replace, {{SIM}} and {{VERSION}}, and 1 {{GITHUB_ISSUE_LINK}} that indicates where to paste issue links.
* PhET developers are very familiar with how to find and replace {{TOKEN}} placeholders. They are used throughout PhET code, templates, and translated strings.
* If we need to switch in the future, it should be relatively easy to modify the QA templates.

**Comment by pixelzoom** [comment]
@KatieWoe what's the status of this issue?  I see a few "NEW" templates in qa/issue-templates/.   Do they need to be reviewed, or can they be merged into the official templates?

**Comment by KatieWoe** [comment]
Things are looking good with these changes. Closing

**Comment by pixelzoom** [comment]
Reopening.  We still have NEW.md and old template files. @KatieWoe would you like me to merge them?

**Comment by KatieWoe** [comment]
If you have a fast way to do it, that's fine. Otherwise I can do it when there's a lull in testing.

**Comment by pixelzoom** [comment]
I merge the NEW.md files into the "official" .md files for the issue templates.  @KatieWoe please review. If it looks OK, please close.

**Comment by KatieWoe** [comment]
Everything looks good! Thanks @pixelzoom
