### ISSUE TITLE
QA coordination with PhET-iO batch sim release

### ISSUE THREAD

**Issue by zepumph** [phetsims/qa#777]
It was decided to re-release a whole batch of PhET-iO simulations after the quarter to leave space for TypeScript conversion over the next month. https://github.com/orgs/phetsims/projects/44 was created to organize this work. There are currently 14 simulations that are to go out during that publication. The goal of this issue is to make sure that QA is aware and prepared for this.

Here is the current timeline
* TypeScript conversion and other potentially disrupting work stops by 3/28.
* Choice dev tests (specifics still up in the air) are created for testing that week as master solidified.
* RCs are created on 4/1.

@KatieWoe, how does this sound to you?

**Comment by KatieWoe** [comment]
Thank you for letting me know. Are these re-releases only for adding typescript? Will they be full rc, or lighter?

**Comment by zepumph** [comment]
The release is to pick up many changes, mostly PhET-iO features, mostly about studio, and mostly all documented in https://github.com/orgs/phetsims/projects/44.

I believe the thought was a full release, so likely full RC tests, that said, they will all have the same common code shas, so as we find bugs, we will be able to apply fixes to all of them.

**Comment by kathy-phet** [comment]
Hi QA team! This is the list of PhET-iO sims that we will want to move through QA over the course of Quarter 2. Some other sims will be mixed in as well, but I was hoping you could work together to roughly estimate the testing hours you think each of these will take, once any emergent major issues are found in the initial test sims. So based off sort of "smooth testing" for each of these sims:
phet and phet-io brands:
(test sim through) Gravity And Orbits (SR, AR)
(test sim through) Friction (MK, AR)
(if ready) Geometric Optics (CM, AR)
(if ready) Geometric Optics: Basics (CM, AR)
pH Scale (CM, AR)
pH Scale: Basics (CM, AR)
Density (JO, AR)
Molecule Polarity (CM, AR)
Molecule Shapes (JO, AR)
Molecule Shapes: Basics (JO, AR)
Graphing Quadratics (CM, AM)
Natural Selection (CM, AM)
Circuit Construction Kit DC (SR, AR)
Circuit Construction Kit DC - Virtual Lab (SR, AR)

**Comment by zepumph** [comment]
Hello QA! We have pushed this back ~1 month to get some more PhET-iO common code work complete first. There will likely be dev versions sent to you in the interim.

**Comment by zepumph** [comment]
This has been fully communicated. Closing
