### ISSUE TITLE
Regression test PhET splash screen

### ISSUE THREAD

**Issue by zepumph** [phetsims/qa#778]
Over in https://github.com/phetsims/joist/issues/781 we had to update it so that the black wasn't the background, but instead was a div that was on top of everything else (in z order), hiding the sim etc if anything was shown before the splash screen went away.

The splash screen is the black screen + logo + loading bar that we have a startup.

Basically I want to make sure that all devices are still working as expected.

Here are the links to test on each device:

* [a PhET branded splash screen](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.7/phet/ratio-and-proportion_all_phet.html)
* [a PhET-iO branded splash screen](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.7/phet-io/ratio-and-proportion_all_phet-io.html?postMessageOnError&phetioStandalone)
* [a PhET branded splash screen with voicing initially enabled to make sure the toolbar animation doesn't change anything (I don't know why it would have)](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.7/phet/ratio-and-proportion_all_phet.html?voicingInitiallyEnabled)
* [PhET-iO Studio](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.7/phet-io/wrappers/studio/)
* [iframe test](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.7/phet/ratio-and-proportion_en_iframe_phet.html)

In addition to testing a few loads on each device, please make sure to do the following as thoroughly as you see fit.
* On IPad and other devices where it applies, rotate the screen while loading to make sure the logo is still centered
* Change the window size while loading to make sure the logo is still centered.
* If you think of something else, write it down here!

Thanks,
Michael

---
Platforms:
- [x] MacOS 10.13 Safari
- [x] MacOS 10.13 Chrome
- [x] MacOS 10.14 Safari
- [x] MacOS 10.14 Chrome
- [x] MacOS 10.15 Safari
- [x] MacOS 10.15 Chrome
- [x] MacOS 11 Safari
- [x] MacOS 11 Chrome
- [x] MacOS 12 Safari
- [x] MacOS 12 Chrome
---
- [x] Windows 10 Chrome
- [x] Windows 10 Firefox
- [x] Windows 11 Chrome
- [x] Windows 11 Firefox
---
- [x] iPadOS 13 Safari
- [x] iPadOS 14 Safari
- [x] iPadOS 15 Safari
---
- [x] ChromeOS

**Comment by KatieWoe** [comment]
With Win 11 Firefox, the studio loading screen jumps around a bit. @zepumph let me know if you think this needs an issue.
![shiftingload](https://user-images.githubusercontent.com/41024075/155815514-1c6d7f14-abb3-495c-ad58-8e428b54e080.gif)

**Comment by Nancy-Salpepi** [comment]
I still see what I originally reported in https://github.com/phetsims/phet-io/issues/1835 with MacOS 12.2.1 and Safari 15.3. (but not chrome).

Steps:
1. Generate html from Studio
2. Save and Open with Safari
* If you then reload the page, you won't see the flash
* If you press 'Preview Sim' from studio, you won't see the flash

* Oddly enough, I was able to produce this issue using MacOS 10.15.7 + chrome but not with safari.

https://user-images.githubusercontent.com/87318828/155888454-0db22941-f08b-4d7b-af28-a69fdf33bd28.mp4

**Comment by zepumph** [comment]
RE: https://github.com/phetsims/qa/issues/778#issuecomment-1051349638:

@KatieWoe, I just want to confirm here, this behavior is in the version I gave you, but not in other/published versions?

**Comment by KatieWoe** [comment]
I looked at https://phet-dev.colorado.edu/html/natural-selection/1.4.3/phet-io/wrappers/studio/ and saw it there, but not quite as often.

**Comment by KatieWoe** [comment]
QA is done

**Comment by zepumph** [comment]
>but not quite as often.

Ok thanks! The fact that it still occurs there makes me feel alright about it. Looks like everything else is in side issues. I'm going to close this.
