### ISSUE TITLE
Replace dev:a11y and design:a11y labels with feature-specific labels

### ISSUE THREAD

**Issue by zepumph** [phetsims/qa#779]
Over in https://github.com/phetsims/special-ops/issues/213 we have made many label changes favoring feature names for the word `a11y`. We now have `voicing`, `sound`, `alt-input`, and `description` (`design:` and `dev:` for each). 

QA has already been helping convert these over, but I realized I never made an issue.

See https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aphetsims+label%3Adesign%3Aa11y+ (16)

See https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aphetsims+label%3Adev%3Aa11y+ ~(127)~ (47)

If any are confusing or hard, feel free to leave them. If in doubt feel free to ask me too.

Thanks!

**Comment by zepumph** [comment]
We are really close on this one. All `a11y` labels are gone except dev:a11y, which has just 47 left. If you could do another push on this when you're bored that would be awesome. Thanks!

**Comment by Nancy-Salpepi** [comment]
@zepumph I see new issues opened with the label dev:ally in June/July 2022. Perhaps a general reminder is needed somewhere?

**Comment by zepumph** [comment]
There are 47 labels left! We are close. I'll keep cranking away.

**Comment by zepumph** [comment]
dev:a11y usages have been changed. I just deleted the label. Thanks all!
