### ISSUE TITLE
Data entry / research for Bett Conference in London March 22

### ISSUE THREAD

**Issue by JacquiHayes** [phetsims/qa#780]
The Bett conference is one of the largest Ed Tech conferences in the world, and we are looking for potential partners who would like to or already integrate PhET into their educational product.

The task is to go through the list of exhibitors and enter the information into a google sheet.

Go to this website:
https://uk.bettshow.com/bett-suppliers-list-library-redirect

Use the filters at the top to filter the exhibitors.

Bett Product categories:
- Interactive whiteboards 
- Educational/Instructional Software
- Learning Materials 

Then enter the results into the sheet here (one example is already done):
https://docs.google.com/spreadsheets/d/12caPNKkBrqsBrmtyjj_apX-ZjClJ2rPLatpc3b6rvYk/edit#gid=38274592

Since the conference is March 22, it is necessary to have the list done by March 16 (~2 weeks)

**Comment by KatieWoe** [comment]
QA should be done. Let me know if you need anything else on this.
