### ISSUE TITLE
Test flight latest iOS build (1079)

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/qa#783]
The iOS App 1.3.3 (build 1079) is processing on App Store Connect. @KatieWoe, @kathy-phet please prioritize testing of this build.

Issues to verify:

- [x] https://github.com/phetsims/phet-ios-app/issues/602
- [x] It would also be good to open a few translated sims to ensure the app updates translations, as expected. https://github.com/phetsims/phet-ios-app/issues/487#issuecomment-536130460.

Here's the last issue, if helpful. https://github.com/phetsims/qa/issues/712

**Comment by KatieWoe** [comment]
Noting that this test flight does have the debug sections. It is useful for testing, but should not be included when the app is published.

**Comment by KatieWoe** [comment]
Did a quick ~5 min check on iOS 14 and iOS 13. Things looked ok there.

**Comment by KatieWoe** [comment]
QA is done. However, https://github.com/phetsims/phet-ios-app/issues/487 was behaving pretty oddly. @oliver-phet it might be a good idea for us to pair to try and figure this out. Also, there wasn't translation testing beyond https://github.com/phetsims/phet-ios-app/issues/487 I believe, so let me know if that is needed/useful and we can take another look
