### ISSUE TITLE
Update QA Book about input-based playback

### ISSUE THREAD

**Issue by zepumph** [phetsims/qa#786]
@KatieWoe today during PhET-iO meeting we decided to remove support for our current playback strategy. This means that you no longer need to test it either! See https://github.com/phetsims/phet-io/issues/1854 for details.

We still support the data stream, and recording the Metacog, but now we no longer support the playback wrapper. 

It isn't totally clear that we no longer want to test the full cycle. So my guess is that you still will want to record to metacog and retrieve that data, but you don't need to run it in the playback wrapper. Perhaps someday soon we will have an analyzer tool for you to pass the data stream into that tells you it is correct. Let me know if you have any questions.

**Comment by KatieWoe** [comment]
Clarification conversation from Slack:

>[Kathryn Woessner] [4:48 PM]
Quick clarification for https://github.com/phetsims/qa/issues/786. We no longer test playback, but we do test that metacog can record. Does that apply to the record wrapper as well? Or is it also discontinued?
[Michael Kauzmann] [4:48 PM]
The record wrapper is still supported.
[Kathryn Woessner] [4:49 PM]
Ok, thanks. That's what I thought, but wanted to make sure
[Michael Kauzmann] [4:49 PM]
It is just our current process of going from data stream -> a sim playing it back.
[Kathryn Woessner] [4:50 PM]
Is there a new way you want us to check the created log files? Open them somehow etc?
[Michael Kauzmann] [4:50 PM]
I think we will get there at some point, but for now we are sorta in a weird state where. . . .noo?
[4:51]
Perhaps just make sure it is the size-ish that you would expect. Like if you recorded for an hour (don't do that, your life is too valuable), then it should be many many MBs, but a few seconds would be smaller.
[4:52]
Honestly, the playback wrapper on master should still work for a cursory check that there are events in the data stream, ya know?
[4:52]
But we aren't going to work on bugs/slowness/playback issues that you might find.
[4:53]
In the future we will likely have a tool that can tell you yay or nay on any given data stream, but we aren't quite there yet.
[Kathryn Woessner] [4:55 PM]
Thanks

**Comment by KatieWoe** [comment]
Input and Playback Wrapper is also gone
