### ISSUE TITLE
A couple thoughts about the QA test template

### ISSUE THREAD

**Issue by zepumph** [phetsims/qa#792]
Hey! I just made my first QA issue with the new dev test template (#791), and it was AWESOME. Thanks for the hard work there. I have two thoughts about potential improvements.

1. In the top comment section geared towards the dev, it could be really nice to have a line that is the template for the title of the issue, like:

>* Name the issue like "Dev Test: {{SIM}} {{VERSION}}"

This way, when we fill in all the other templates (with find/replace), this is filled in too, and we can just copy paste this. I mainly like this idea because I feel like everyone does the titles differently, and I never know exactly how QA wants to see them. 

2. I see this line here: `Please include (non-screen reader) a11y testing in these records if applicable.` I'm not really sure what `a11y` means anymore, because we have been trying to remove that notions from the features that the a11y team has been creating over the last few years. Do you mean specific features, or do you mean a11y-team-specific testing in some way? 

Thanks again for all you hard work!

**Comment by KatieWoe** [comment]
For 2, we mean things like keyboard navigation should be tested during this stage. This is a note for QA reminding them to include these features in testing rather than put them off, and that checking those boxes means everything has been tested on that platform except screen readers.

**Comment by zepumph** [comment]
Can we be explicit then, like "all time minus screen-reader testing." There is a trend amongst the team to try to remove `a11y` from the project vernacular. Features are features, and there are lots of them (some of them the a11y-team made). This is the same sentiment that I'm sure you are aware of that caused the new templates to just have a bunch of feature checkboxes at the top. 

What do you think?

**Comment by KatieWoe** [comment]
Changes for Number 2 made above

**Comment by pixelzoom** [comment]
I see that you've added an <h1> tag to all of the templates, like:

> <h1>RC Spot Check Test: {{SIM}} {{VERSION}}</h1>

This feels unnecessary and redundant.  The name of the sim and version are already in the issue title, and the issue label identifies the type of test.   If you want to provide a template for the issue title that we can cut-&-paste, that would be fine. But duplication like this is exactly what we were trying to eliminate.

**Comment by KatieWoe** [comment]
Undone. If you guys decide what you want the first request to look like, let me know and I'll implement it. Until then, closing.

**Comment by pixelzoom** [comment]
Let's get a cut-&-paste title into the template.  

@KatieWoe do you want the title to include what type of test it is? 

This could be as easy at converting this:

`<h1>RC Spot Check Test: {{SIM}} {{VERSION}}</h1>`

to an instruction in the "DEVELOPERS" comment:

`use this title: RC Spot Check Test: {{SIM}} {{VERSION}}`

**Comment by KatieWoe** [comment]
I don't mind either way. I do want it to say RC, RC Spot Check, etc. But sim and version I'm willing to do whatever works best for everyone. But I'm not sure what that is and don't want to make a decision that not everyone agrees with

**Comment by pixelzoom** [comment]
@KatieWoe said:
> Undone (didn't link to this issue).  ...

I linked them above.

**Comment by pixelzoom** [comment]
Why do you need an `<h1>` head that says "RC Spot Check" it the issue title is "RC Spot Check: Geometric Optics 1.1.0-rc.3" ?

**Comment by KatieWoe** [comment]
It's easier to see at a glance and less likely to be changed or omitted.

**Comment by pixelzoom** [comment]
@KatieWoe and I discussed on Zoom.

She would like a header on the body of the issue, because her eye goes to the body, not the title.

In the above commits, I've added a title template (what @zepumph requested in 1. above) to the "DEVELOPER" comment block.  For example:

```
<!---
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

DEVELOPERS: 

* title for this issue = Dev-Lite Test: {{SIM}} {{VERSION}}
* Fill in the {{SIM}}, {{VERSION}}, and {{GITHUB_ISSUE_LINK}} placeholders.
* Delete things that are not relevant, e.g. PhET-iO links for non-PhET-iO tests.

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
-->
```

The title prefix matches the `<h1>` in the issue body.  So for the example above, the `<h1>` is:

`<h1>Dev-Lite Test</h1>`

Here are the titles for the 7 templates:

<img width="716" alt="screenshot_1643" src="https://user-images.githubusercontent.com/3046552/161829831-03972a46-fdac-4e7c-88fe-809859a1b5e9.png">

@KatieWoe please review, and feel free to close. Also feel free to change the titles or `<h1>` tags, but please make sure that they match.

**Comment by pixelzoom** [comment]
@KatieWoe can this issue be closed?
