### ISSUE TITLE
Dev Test: Geometric Optics 1.2.0-dev.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#798]
<h1>Dev Test</h1>

**Mentions**: @arouinfar @kathy-phet @ariel-phet 

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/geometric-optics/issues)
- [phet top level directory](https://phet-dev.colorado.edu/html/geometric-optics/1.2.0-dev.1)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/geometric-optics/1.2.0-dev.1/phet/geometric-optics_all_phet.html)
- [phet-io wrapper index](https://phet-dev.colorado.edu/html/geometric-optics/1.2.0-dev.1/phet-io?phetioDebug)

<h3>Test Matrix</h3>

Please include all (non-screen reader) feature testing in these records if applicable.

- [x] Latest macOS, Safari (Time = .5)
- [ ] Windows 10, Chrome (Time = 1)
- [x] Windows 10, Firefox (Time = .5)
- [x] Latest iOS, Safari (Time = 1)
- [x] Windows 11, Chrome (Time = 3)

Light testing, or optionally skip if time crunch:

- [ ] Latest macOS, Chrome (Time = )
- [ ] Latest Chrome OS, Chrome (Time = )

If PhET-iO is being tested:

- [x] Latest macOS, Safari (Time = 1)
- [ ] Windows 10, Chrome (Time = 1)
- [x] Windows 10, Firefox (Time = 1.5)
- [x] Latest iOS, Safari (Time = .75)
- [x] Windows 11, Chrome (Time = 2)

<h3>Features included</h3>

- [x] PhET-iO
- [x] Alternative Input
- [x] UI Sound
- Sonification
- Description
- Voicing

<h3>Focus and Special Instructions</h3>

The focus of this dev test is PhET-iO, and this is the first PhET-iO testing for this sim.

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<hr>

</details>

<details>
<summary><b>PhET-iO features</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
  sure the simulation loads without crashing or throwing errors.

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Interactive Description
  - Sound and Sonification
  - Pan and Zoom
  - Mobile Description
  - Voicing
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[this Google Document](https://drive.google.com/open?id=12kTs-g-iKEIH1dyG7Q41_W_oNL4gUKbkW-IQgZjMUBw). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
On hold for Studio bug

**Comment by pixelzoom** [comment]
@KatieWoe let’s proceed with QA, using ?phetioDebug with Studio.  We think that will allow useful testing to continue.   Be aware that there are blocking PhET-iO issues that are in various states of “in progress”, and you’re likely to encounter them.  Create sim-specific issues, and I’ll triage them as needed.

**Comment by KatieWoe** [comment]
Performance in the textarea and state wrappers on iPad were fairly poor.

**Comment by KatieWoe** [comment]
In studio there are two links (PhET-iO Guide, and Examples) that don't lead to anything. Is that intended?

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
@KatieWoe I see memory tests for GO:Basics in https://github.com/phetsims/qa/issues/799#issuecomment-1101828131, but no memory test for GO here.   GO should have at least a brand=phet-io memory test.   For reference, my brand=phet-io memory test was done in https://github.com/phetsims/geometric-optics/issues/373.

**Comment by pixelzoom** [comment]
All issues have been addressed or are being tracked in other issues. This sim is in good shape, ready for RC testing.

@KatieWoe if the PhET-iO memory test looks OK, you can close this issue.

**Comment by KatieWoe** [comment]
PhET-iO memory test:
<img width="341" alt="mem" src="https://user-images.githubusercontent.com/41024075/165367575-5cb20967-e43e-4586-b809-c8f93cc41375.png">
