### ISSUE TITLE
Installer Builder: Test all.html features

### ISSUE THREAD

**Issue by zepumph** [phetsims/QA#80]
The all.html appears to be working well in the installer, though I think that @phet-steele should get his hands on it before we call it good.

Notes about testing:
The changes I have made seem to be isolated to how we handle the html sims, but bugs could have crept in. 
- [x] Please verify that the normal testing that takes place on a weekly basis is successful for the installers below.
- [x]  Work any links to html5 simulations very hard.

parent issue:
https://github.com/phetsims/installer-builder/issues/54

link to installers: 
https://www.colorado.edu/physics/phet/dev/installer-testing/2017-12-13/

@ariel-phet please assign and prioritize.

**Comment by phet-steele** [comment]
@zepumph going to close this in favor of the next iteration.
