### ISSUE TITLE
Dev Test: Android App 2.0.5

### ISSUE THREAD

**Issue by mattpen** [phetsims/qa#800]
<h1>Dev Test</h1>

**Mentions**: @oliver-phet @kathy-phet 

<h3>App links</h3>

- [github repository for issues](https://github.com/phetsims/phet-android-app/issues)
- [play store entry](https://play.google.com/store/apps/details?id=edu.colorado.phet.androidApp)
  - This app will show version 2.0.4 if you are viewing the page with an account that is not listed in PhET's internal testers.  Contact @oliver-phet or @mattpen to add new google accounts to the internal testers.  This should show a 2.0.5 Update available if you are logged in on an Android device with a PhET internal test account.

<h3>Test Matrix</h3>

Please include all (non-screen reader) feature testing in these records if applicable.

- [x] Android, Chromebook (Time = 4, Platform = Chromebook)
- [x] Android, Phone/Tablet (Time = 5, Platform = )
- [x] Android, any device + Talkback (lite testing only) (Time = .75, Platform = Samsung phone)

We currently support Android versions 5-12.

<h3>Focus and Special Instructions</h3>

Please conduct a general test of the app.  The app should work if upgrading from a previous version and also from a new install.  Please take note of any crashes.  We should test for regressions in the update step.  The simulations and translations available offline out of the box are up to date as of 4/18/22.  Any sim releases or translations released after that date should be captured once the app is running on a device with an internet connection.

<h3>Issues to Verify</h3>

There are no issues to verify with reproducible steps.  This is just a general test.

I've included the QA Only section of the dev test template below, although I'm not sure how relevant it will be.

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<hr>

</details>

<details>
<summary><b>PhET-iO features</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
  sure the simulation loads without crashing or throwing errors.

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Interactive Description
  - Sound and Sonification
  - Pan and Zoom
  - Mobile Description
  - Voicing
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[this Google Document](https://drive.google.com/open?id=12kTs-g-iKEIH1dyG7Q41_W_oNL4gUKbkW-IQgZjMUBw). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by mattpen** [comment]
Assigning @KatieWoe and @kathy-phet for priority.

**Comment by kathy-phet** [comment]
@KatieWoe - What devices do we have in house that we can use to test this app?

**Comment by KatieWoe** [comment]
In house we have An android tablet that runs android 8 and can't seem to go beyond that. The latest is 12, and according to Matt the earliest our users run is 9, so we should probably get updated devices. However, @mattpen also mentioned on Slack that he thinks this test will require Chromebooks rather than android devices, and not to start until that is determined and this issue is updated. If we do need newer androids, Emily said she has a phone on the latest android and can start testing while I work with Oliver to get something in house.

**Comment by mattpen** [comment]
>  according to Matt the earliest our users run is 9

I did some more digging and found that users could be using versions as early as 5 (Lollipop).

> However, @mattpen also mentioned on Slack that he thinks this test will require Chromebooks rather than android devices, and not to start until that is determined and this issue is updated. 

I recall that in the last test we tested Chromebooks and Android Phones.  I was suggesting that we don't need to test Android Tablets.  I updated the list, but it is still a little broad.

**Comment by kathy-phet** [comment]
Let's start on the Chromebooks we have and Android Phones.

**Comment by kathy-phet** [comment]
Also, it would be good to indicate which devices get tested ... so we have clarity when we look back at what was tested. @KatieWoe - Perhaps change this issue template to include device specs for testing to.

**Comment by stemilymill** [comment]
Note on Talkback testing:

I was able to navigate around the app using talkback with no problem, but not able to do anything *in the sims* with talkback

**Comment by mattpen** [comment]
> I was able to navigate around the app using talkback with no problem, but not able to do anything in the sims with talkback

That is the expected result! Thank you!

**Comment by KatieWoe** [comment]
QA is done

**Comment by ariel-phet** [comment]
I have one UX suggestion I will write in a separate issue, but things were running really beautifully on my phone

**Comment by mattpen** [comment]
This test is complete, superceded by https://github.com/phetsims/qa/issues/803
