### ISSUE TITLE
PhET Virtual Workshop Landing Page & Workshops

### ISSUE THREAD

**Issue by RVieyra** [phetsims/qa#802]
@KatieWoe, I'd like to ask for your team's support for QA review of the new Virtual Workshop content, located both here at this landing page https://phet.colorado.edu/en/teaching-resources/virtual-workshop/ and also for each of the 5 workshops (hyperlinked to the big buttons on the landing page).

This content is live, but it is not yet linked to the main web page. It will eventually replace the "Virtual Workshop: Mathematics."

Please review English. I will notify you when Spanish is ready, in case you need to look at that as well.

Please make issues in https://github.com/phetsims/website-meteor/issues and assign @solaolateju, @chrisklus and @mattpen.

Deadline: Published by May 30 (English & Spanish)

<h3>General Dev Test Platforms</h3>

- [x] Latest macOS, Safari (Time = 8)
- [ ] Windows 10, Chrome (Time = 3)
- [ ] Windows 10, Firefox (Time = 5)
- [x] Latest iOS, Safari (Time = 3.5)
- [x] Win 11 Chrome (Time = 5)

Light testing, or optionally skip if time crunch: 
- [ ] Latest macOS, Chrome (Time = 2)
- [ ] Latest Chrome OS, Chrome (Time = )

**Comment by KatieWoe** [comment]
QA is done

**Comment by RVieyra** [comment]
Thanks to all who have found and resolved many of these bugs!

For all content-related materials (text, PDFs, etc.), I confirm that what is now on ox-dev is ready for publication (after other technical-related issues are closed).

**Comment by RVieyra** [comment]
I believe we can close this particular issue. If not, please re-open. The remaining linked issues are separate issues, and are not high priority as I understand it.

**Comment by RVieyra** [comment]
Thank you to all!
