### ISSUE TITLE
Setup QA with new Metacog account for data recording and requests.

### ISSUE THREAD

**Issue by zepumph** [phetsims/qa#806]
@KatieWoe, the next time you need to do a metacog recording download, will you please reach out to me for an updated process? There is a new UI that will most likely be very helpful to your testing.

**Comment by zepumph** [comment]
I think it will be easiest to do this when you have a test to complete, and we can update documentation then as we discuss.

**Comment by samreid** [comment]
We no longer support Metacog as a data storage/retrieval service, closing.
