### ISSUE TITLE
Website: team-member related pages

### ISSUE THREAD

**Issue by mattpen** [phetsims/qa#812]
The admin page for managing Team Members and PhET Fellows has been ported to React and is available to test.  This also involved refactoring methods used in the Supporters admin so we should do a regression test for that page as well.

<h2>What To Test</h2>

1. https://ox-dev.colorado.edu/admin/team-members
  - Add a new team member of every type
  - Update a team member, testing every available field across types
  - Delete a team member
  - Changes for PhET Fellows can be seen at https://ox-dev.colorado.edu/en/phet-global/community
  - Changes for all other Team Member types can be seen at https://ox-dev.colorado.edu/en/about/team
2. https://ox-dev.colorado.edu/admin/supporters - regression test
  - Add a new supporter
  - Edit an existing supporter
  - Test rearranging order of supporters
  - Delete a supporter
  - Changes can be seen at https://ox-dev.colorado.edu/en/our-supporters
3. https://ox-dev.colorado.edu/en/about/team & https://ox-dev.colorado.edu/en/phet-global/community (PhET Fellows Section)
  - Test general layout and accessibillity of this page.
  - Test this page in all supported browsers:
    - [x] Latest macOS, Safari (Time = 3hrs )
    - [x] Windows 10/11, Chrome (Time = 3.5)
    - [x] Windows 10/11, Firefox (Time = .75)
    - [x] Latest iOS, Safari (Time = .75)
  - Test this page with supported screen readers:
    - [ ] Windows 10 + Latest Chrome + Latest JAWS (Time = 1.5)
    - [x] Windows 10 + Latest Firefox + Latest NVDA (Time = .5)
    - [x] macOS + Safari + VoiceOver (Time = 1 hr)
  - [This page](https://ox-dev.colorado.edu/en/about/team) is not localized and does not need to be tested in non-english locales. 
  -  https://ox-dev.colorado.edu/en/phet-global/community should be tested in English, one non-english RTL locale (e.g. ar_SA), and one non-english LTR locale (e.g. es)
  

Changes made while on ox-dev will not affect production.  We can copy the current state of team members and supporters from production to ox-dev at any time if needed in this test, just ping @mattpen.

Issues should be opened in https://github.com/phetsims/website-meteor and assigned to @mattpen.

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

  Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

  Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

  We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

  You should:

  1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
  2. Google it.
  3. Ask Katie.
  4. Ask a developer.
  5. Google it again.
  6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by mattpen** [comment]
Assigning to @KatieWoe for priority

**Comment by KatieWoe** [comment]
I was unable to create a new team member (Director) in the first test. Bellow is the console error.
<img width="960" alt="failerror" src="https://user-images.githubusercontent.com/41024075/173936641-f67150ff-0a41-4317-a459-8eaa4155ec59.png">

**Comment by mattpen** [comment]
I needed to run `GRANT USAGE, SELECT ON SEQUENCE team_member_id_seq to phet;` in the database.  I have a script to run these commands in production when we switch.  Creating new team members should work now.

**Comment by KatieWoe** [comment]
Part 1 Fully tested on Win 11 Chrome

**Comment by KatieWoe** [comment]
Does anyone know why there are so many duplicates on the supporters page? Is this a bug? They seem duplicated to the point that they both seem to be in the same place on the edit page (you can only move Alpha Productions down, not move the second one up).
<img width="960" alt="alpha" src="https://user-images.githubusercontent.com/41024075/174340871-6867b870-db3a-4cd5-ab99-b31e7407e611.png">

**Comment by mattpen** [comment]
That looks like a problem specific to ox-dev. I doubt this is a bug.

**Comment by KatieWoe** [comment]
Is there an easy fix? It does make testing a bit hard.

**Comment by mattpen** [comment]
Well, syncing is going to be difficult.  Part of this changeset included a mongo upgrade, which makes a database dump/restore difficult.  As long as you are on ox-dev, you can delete the duplicates.  Would that be ok - or is that a lot of work? (I'm aware of phetsims/website-meteor#473 and working on a fix today)

**Comment by KatieWoe** [comment]
I can do that, though we can't delete anything right now due to https://github.com/phetsims/website-meteor/issues/473

**Comment by Nancy-Salpepi** [comment]
Just an FYI- Amy is going to update her twitter handle. The link currently takes you to an account that no longer exists.

**Comment by KatieWoe** [comment]
QA is done

**Comment by mattpen** [comment]
This was deployed to production! Closing.
