### ISSUE TITLE
Dev Lite Test: Greenhouse Effect 1.1.0-dev.10

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#819]
<h1>Dev-Lite Test</h1>

This is a dev lite test of the *first screen only* for the Greenhouse Effect sim.  This test is being done to make sure
that this screen is ready for a set of interviews that will be focused on interactive descriptions.  This is the
second dev test for this purpose, and several issues have been addressed based on the first dev test.

**Mentions**: @KatieWoe, @arouinfar, @kathy-phet, and @jessegreenberg

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/greenhouse-effect/issues)
- [phet top level directory](https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.10)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-dev.10/phet/greenhouse-effect_all_phet.html)

<h3>Test Matrix</h3>

- [x] Tester 1 (Tester = NS , Platform = macOS 12.4 + safari + VO, Time = 2hrs {max 2 hours}
- [x] Tester 2 (Tester = KW, Platform = iPad Mobile VO, Time = .75 {max 2 hours}
- [x] Tester 2.5 (Tester = E2, Platform = Win10 Firefox + NVDA, Time = 1 {max 2 hours}

<h3>Features included</h3>

- [x] Alternative Input
- [x] UI Sound
- [x] Sonification
- [x] Description

<h3>Focus and Special Instructions</h3>

The focus for this testing should be on description and on any egregious bugs that could block interviews.

<h3>Issues to Verify</h3>

These issues should have the "status:ready-for-review" label. Unless an issue says to close after verifying, assign the
issue back to the developer.

- [x] https://github.com/phetsims/greenhouse-effect/issues/182
- [x] https://github.com/phetsims/greenhouse-effect/issues/169
- [x] https://github.com/phetsims/greenhouse-effect/issues/168
- [x] https://github.com/phetsims/greenhouse-effect/issues/176

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Interactive Description
  - Sound and Sonification
  - Pan and Zoom
  - Mobile Description
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[here](https://github.com/phetsims/qa/blob/master/documentation/accessibility-bugs.md). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel
controls. Please test magnification and make sure it is working as intended and well with the use cases of the
simulation. Due to the way screen readers handle user input, magnification is NOT expected to work while using a screen
reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by arouinfar** [comment]
@KatieWoe @Nancy-Salpepi @stemilymill 

When testing with a screen reader, please compare the responses to the Activity Log in the a11y view. In particular, when changing the greenhouse gas concentration with the slider, there is a set of responses like this: (numbered in order of how they should be heard)
```
1. More infrared radiation redirecting back to surface.
2. Surface temperature warming, now 286.1 Kelvin.
3. More infrared radiation emitting from surface.
```
It's important to know if all of these statements get heard, or if they get cut off before starting the repeated "Warming" or "Cooling" responses. 

The same goes when switching between the slider/date modes, and when switching between dates. In all of these cases, the greenhouse gas concentration changes, which should queue up several responsive descriptions. Things look good in the a11y view, but I want to make sure that what we see in the a11y view Activity Log matches what is said by screen readers.

**Comment by KatieWoe** [comment]
Calling QA here.

**Comment by jbphet** [comment]
Thanks @KatieWoe and team.  We will follow up on the individual issues.  Closing.
