### ISSUE TITLE
Dev Test: Density 1.1.0-dev.2

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/qa#820]
<h1>Dev Test</h1>

**Mentions**: @arouinfar, @kathy-phet

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/density/issues)
- [phet top level directory](https://phet-dev.colorado.edu/html/density/1.1.0-dev.2)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/density/1.1.0-dev.2/phet/density_all_phet.html)
- [phet-io wrapper index](https://phet-dev.colorado.edu/html/density/1.1.0-dev.2/phet-io)

<h3>Test Matrix</h3>

Please include all (non-screen reader) feature testing in these records if applicable.

- [ ] Latest macOS, Safari (Time = )
- [x] Windows 10, Chrome (Time = 2 )
- [ ] Windows 10/11, Firefox (Time = .5)
- [ ] Latest iOS, Safari (Time = )
- [x] Windows 11, Chrome (Time = 1)

Light testing, or optionally skip if time crunch:

- [ ] Latest macOS, Chrome (Time = )
- [ ] Latest Chrome OS, Chrome (Time = )

If PhET-iO is being tested:

- [x] Latest macOS, Safari (Time = 2.5)
- [ ] Windows 10, Chrome (Time = 3)
- [ ] Windows 10, Firefox (Time = 3.5)
- [x] Latest iOS, Safari (Time = .5)
- [x] Windows 11, Chrome (Time = 6)

<h3>Features included</h3>

- [x] PhET-iO
- Alternative Input
- UI Sound
- Sonification
- Description
- Voicing

<h3>Focus and Special Instructions</h3>

This release is part of the [PhET-iO batch release](https://github.com/orgs/phetsims/projects/44) milestone. 

Density makes use of the SetValue and GetValue as a way to exercise particular PhET-iO element customizations. @arouinfar can you elaborate on which PhET-iO element ids should be tested as a focus for these new features. 

Contact @samreid and @zepumph for specific PhET-iO testing instructions, including API migration.

According to @arouinfar, the PhET-iO client guides still have many pending updates, see https://github.com/phetsims/phet-io-sim-specific/issues/3.  So please skip the client guides for this dev test.

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<hr>

</details>

<details>
<summary><b>PhET-iO features</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
  sure the simulation loads without crashing or throwing errors.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Memory Test:
<img width="348" alt="memtestden" src="https://user-images.githubusercontent.com/41024075/179845572-69715fad-a208-4e88-a91b-16421feaff21.png">
PhET-iO Memory Test:
<img width="347" alt="iomemden" src="https://user-images.githubusercontent.com/41024075/179845605-8dcfa919-f793-4acd-b058-1b3f9da1a37a.png">

**Comment by arouinfar** [comment]
@KatieWoe @stemilymill @Nancy-Salpepi 

When testing the "Get Value" and "Set Value" functionality in Studio, it would be good to focus on the example customizations described in the [Examples](https://phet-dev.colorado.edu/html/density/1.1.0-dev.2/phet-io/doc/guides/examples.html) doc. The doc includes instructions for how to customize the mass, volume, material, density, etc.  The process differs a bit by screen, so please test out the recommendations for each individual screen. Please note that the doc itself predates the data entry capabilities of Studio, so I will be updating the language. However, the general information and the provided phetioIDs should be accurate. (Though https://github.com/phetsims/density/issues/135 already describes one known issue.)

Additionally, please test the `customColorProperty` on the Mystery screen to change the colors of the blocks (both with get/setValue and the color picker tool). You'll need to switch over to "All" Elements to find it in the tree, but I will open an issue to make it `phetioFeatured` so it will be easier to find in the future.

**Comment by KatieWoe** [comment]
I noticed artifacts and some lag when moving blocks in phet-io when the sim was in an iframe. Let me know if you want this in a specific issue.

https://user-images.githubusercontent.com/41024075/180887218-49790463-063a-41ca-a142-fd3b8459428b.MOV

**Comment by KatieWoe** [comment]
QA is done

**Comment by arouinfar** [comment]
If lag in the data stream wrapper is indicative of lag in a user-facing product, it could merit an issue, but I'll leave that up to @jonathanolson.

**Comment by zepumph** [comment]
@KatieWoe, RE: https://github.com/phetsims/qa/issues/820#issuecomment-1194735374, can you please take a look at a change over in https://github.com/phetsims/phet-io-wrappers/issues/450 to see if that helps.

**Comment by jonathanolson** [comment]
Fixed a memory leak above (looks like it may have existed for a while).

**Comment by jonathanolson** [comment]
Thanks!
