### ISSUE TITLE
Uploading Teacher Notes into MediaValet (Mastercard Foundation grant)

### ISSUE THREAD

**Issue by JacquiHayes** [phetsims/qa#827]
(Instructions are also here: https://docs.google.com/document/d/1BlWwg6thJtTgKYgxZ8FMD4_48NJmlUZp_7Wb_AILK8k/edit?pli=1#heading=h.b51ndt10u0w5)

**_Tracking_**

I’ve set up this spreadsheet with all the simulations relevant to the university level.
https://docs.google.com/spreadsheets/d/1EXHNSlCI8Cxug-avm7L2Qu-KrDcf2f8V/edit#gid=679020387

I’ve already uploaded the document for 2 simulations (Geometric Optics and Density) as a test. I marked this is in the final column. This sheet could also be used by your team for both the data and tracking each sim.

**_Creating the PDF_**

Use this template to create a cover page pdf.
https://docs.google.com/presentation/d/1S0skEFvA_oTXoJD9mLLMaQtA1mClQaOVgPL8sT6pidE/edit#slide=id.g147b0c0ee54_0_0

Please make sure that the PDF is clickable- so that the simulation URL goes to the simulation and the about url goes to the simulation about page.

Download the teacher notes PDF for each simulation.

Add the cover page pdf to the teacher notes pdf. (On a Mac I can combine pdfs by using Preview, but I’m not sure how to do this on a windows machine, sorry.)

Name this combined pdf: 
sim name_PhET Interactive Simulations

Save it on drive here: https://drive.google.com/drive/folders/14tDJu_U7QHq6rHi9TemcGGiz6nv9LelC

**_Uploading into MediaValet_**

Log into Media Valet:

URL: [mastercardfdn-elearning.mediavalet.com](http://mastercardfdn-elearning.mediavalet.com/)
For user name and password, ask nancy, katie or emily :)

**Add Categories**

Click “Add” next to each asset.
Then navigate the tree structure to map the PhET categories to the Media Valet categories:

Physics —> Course Content, Physical Sciences, Physics
Chemistry —> Course content, Physical Sciences, Chemistry
Biology —> Course content, Health Science, Biosciences, Biology
Mathematics simulations —> Course content, Mathematics, Mathematics (General)
Earth Science →Course content, Physical Sciences, Earth Science

NB: You can add multiple categories (eg physics and chemistry) to the same assets.

**Add Attributes**

Approved for external use: CC BY
Approved for External Use (Creative Commons LINK):[ https://creativecommons.org/licenses/by/4.0/](https://creativecommons.org/licenses/by/4.0/)
Institution (dropdown): PhET
Course Title: Simulation Name
Quality Matters Certification Status: Not applicable

Leave the rest blank.

**Add Keywords**

Add Keywords from the spreadsheet.

Also add these two keywords:
Interactive; Simulation

**Add Description**

Add the description about each simulation (take this from the metadata spreadsheet). Add the list of Sample Learning Goals to the description.

**Comment by KatieWoe** [comment]
Please record time here:
- [ ] Tester = , Time = 
- [ ] Tester = , Time = 
- [ ] Tester = , Time = 
- [ ] Tester = , Time =

**Comment by JacquiHayes** [comment]
Thanks Nancy!

I saw that as well and deleted some older tests that I did.

**Comment by Nancy-Salpepi** [comment]
Hi @JacquiHayes! Currently there aren't any teacher tips posted for Collision Lab on the website. Should I just post that sim as the cover page only?

**Comment by JacquiHayes** [comment]
Did you ask the designers whether the teacher tips are coming?

If not, then the cover page by itself is fine. Thanks!

Am Mi., 24. Aug. 2022 um 02:53 Uhr schrieb Nancy Salpepi <
***@***.***>:

**Comment by Nancy-Salpepi** [comment]
@JacquiHayes Collision Lab and Build a Molecule were uploaded without the Teacher Tips (unfortunately they weren't made yet). 
Let me know if you see any issues!

**Comment by JacquiHayes** [comment]
I logged in and it looks like all 63 relevant documents are there. Nice work!
