### ISSUE TITLE
Dev test: Gravity Force Lab: Basics 1.0.0-dev.13

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#83]
@ariel-phet @emily-phet @samreid @mbarlow12 Gravity Force Lab: Basics is ready for an initial dev test. Test is motivated by https://github.com/phetsims/gravity-force-lab-basics/issues/22, but this sim is ready for a dev test anyway.

This sim now includes phet-io instrumentation and keyboard navigation. Keyboard navigation is not meant to be tested with phet-io yet.

**Link to sim (with keyboard nav):** https://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.13/phet/gravity-force-lab-basics_all_phet.html?accessibility

**Link to phetio** https://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-dev.13/phet-io/wrappers/index/

@phet-steele could you please test phet brand on these platforms? (I am not sure what standard procedure is for phetio dev test)
 - [x] Chrome
 - [x] Mac Safari
 - [x] Firefox
 - [x] iPad2

Expected behavior for keyboard interaction:
- Tab/Shift tab to  navigation focusable elements
- Spacebar activates checkboxes
- Spacebar/Enter activates reset all button
- Up/Down arrow keys increment/decrement mass controls
-  Masses act like sliders
  - Arrow keys move masses 0.1 km
  - Page up/page down move masses 1 km
  - Home/End moves masses to min/max location

Helpful query params
- ?showGrid: masses are constrained to discrete locations for reproducible measurements, mass centers should always align with grid lines.

Let me know if you have any other questions. Assigning to @ariel-phet to prioritize this test.

UPDATE by @samreid: I changed the URL of the PhET-iO test to point to the wrappers/index

**Comment by phet-steele** [comment]
Updated to dev.13 to reflect fixes in https://github.com/phetsims/phet-io-wrappers/issues/44

**Comment by phet-steele** [comment]
@jessegreenberg @mbarlow12 testing is done. New dev version please!
