### ISSUE TITLE
Review and close stale automated-testing issues

### ISSUE THREAD

**Issue by samreid** [phetsims/qa#832]
We have 112 open issues labeled for automated testing: https://github.com/issues?q=is%3Aissue+user%3Aphetsims+label%3Atype%3Aautomated-testing+is%3Aopen

Can you please look through them and see which can be closed?

UPDATE: Or we can just look through the unassigned ones, and request that the assigned developers each look through their own issues?

**Comment by KatieWoe** [comment]
I'm ok with either. I'll start with unassigned ones.

**Comment by KatieWoe** [comment]
Unassigned issues have either been closed or reassigned for a second look.

**Comment by pixelzoom** [comment]
@KatieWoe please skip the repos that I'm responsible for.  CT issues are already well-triaged, and it's not a good use of my time to have to reply to every CT issue, reopen, unassign, etc.

**Comment by pixelzoom** [comment]
Ah, well... I didn't get to you in time, and you're done.  So I guess I'll reply to those issues.

**Comment by samreid** [comment]
@KatieWoe @Nancy-Salpepi @stemilymill and I discussed this at QA meeting, and decided this issue has served its purpose and can be closed, thanks!
