### ISSUE TITLE
Review usage and support of older MacOS

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/qa#834]
MacOS 13 will likely be coming out in the next month or two. We currently support MacOS 10.13, 10.14, 10.15, 11, and 12. These are spread through our different devices on many partitions and it can be hard to install the new OS while still being able to test the old ones. 10.13 and 10.14 are no longer maintained by Apple according to what I've been able to find, so I think it would be good to think about at least removing them. I suspect 10.15 will lose support when 13 is released. We should look again at usage and determine if these platforms can be dropped. We should also consider reexamining iPadOS 13 as the new releases approach.

**Comment by oliver-phet** [comment]
@KatieWoe MacOS 10.13 only represented 1.65% of MacOS users (.243% of all users) in the last 30 days. I'd say it's save to drop support of that platform -- though it may be best to wait until MacOS 13 is released.

**Comment by KatieWoe** [comment]
Coming back to this now that MacOS 13 and iPadOS 16 are out. This was mentioned in https://github.com/phetsims/chipper/issues/1323 and seems to have been deferred at the time. I strongly support dropping MacOS 10.13 and iPadOS 13.
I updated the device we used for 10.13 to 10.15 in order to make room for the new MacOS. While I can probably get another device on 10.13 if we really want to keep supporting it, it will probably be difficult. I also don't see the utility in it. It isn't supported by Apple, usage was low, and supporting 6 Mac OS's is pretty unwieldly for QA.
Putting this issue forward to discuss in design meeting on 11/10/22.

**Comment by kathy-phet** [comment]
mac OS 10.13 was released September 25, 2017. 
ipadOS 13 was released September 19, 2019.

**Comment by oliver-phet** [comment]
Seems appropriate to drop iOS 13!
iOS stats (last 30 days):


ios | 12 | 31881 | 3.55%
-- | -- | -- | --
ios | 13 | 7169 | 0.80%
ios | 14 | 53658 | 5.97%
ios | 15 | 301607 | 33.56%
ios | 16 | 504294 | 56.12%

**Comment by kathy-phet** [comment]
Yep - @KatieWoe and @oliver-phet - let's drop ios 13.
