### ISSUE TITLE
Get set up to test the Haptics Playground Android app

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#836]
We are currently working towards full publication of the Haptics Playground app (see https://github.com/phetsims/quake/issues/22) and would like to have QA do some testing on it prior to publication.  QA is probably not in a position at the moment to test this, since we need to have devices that support haptic vibration and we need to be able to load pre-publication versions of the app onto those devices.  This issue is to get us into a position where testing can begin as soon as the app is ready.

The things we need to investigate are:
- What hardware devices do we currently have available that support haptics, and do we need to buy anything?
- What testers do we need to add to the list of internal testers?
- Can QA currently load the app onto the available hardware using the shared account?

**Comment by KatieWoe** [comment]
There are two Android tablets in the office, but neither have haptics. @emily-phet has an Android phone that does have haptics, so she will need to be added to the list.

**Comment by KatieWoe** [comment]
@emily-phet, @jbphet mentioned looking into getting more devices for testing for better coverage. What are your thoughts on this?

**Comment by jbphet** [comment]
Here is link for the installing the latest test version: https://play.google.com/apps/internaltest/4701271652165855719.

**Comment by KatieWoe** [comment]
I was able to download and install the app with the link just fine.

**Comment by stemilymill** [comment]
I was also able to download and install the app

**Comment by jbphet** [comment]
I'm going to close this, since it seems like we're as set up as we're going to get, and will do the next steps in separate issues.
