### ISSUE TITLE
Figure out how to install alpha test version of Haptics Playground

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#840]
Through the Google Play Console, I have uploaded a version of Haptics Playground to what they refer to as an "Alpha Test Track".  I set up the same emails used for the "Internal Test" as testers.  I don't know exactly how the testers are supposed to install this version, since I've never done this before.  The version on my on S7 device seems to be up to date, but I don't know if that's because I did the debugging there or if something automatically updated it.  So, I think our next step here is for the testers to figure out how to get the latest version - which is v1.1.0 - on their test devices.

The first step would be to check if your previously installed version automatically updated.

If not, I would suggest going to the Play Store, making sure that you're signed in with the email that you provided me earlier, and searching for it there.  If you find it, install it.

If that **doesn't** work, try this URL: https://play.google.com/apps/internaltest/4701271652165855719, and then check to see if the version is 1.1.0 in the "Settings" screen.

Please report your learnings in this issue, and keep my posted over Slack on your progress.

**Comment by jbphet** [comment]
Once we know how to get this on the test devices, I'll set up a full QA test issue.

**Comment by stemilymill** [comment]
Going to the play store directly and through the link you posted above, the most recent version of the app available to me is 1.0.0. I don't know if it might take more time for the new test version to become available

**Comment by stemilymill** [comment]
I was able to download the new version using the link posted above, but not by searching the play store (as of 10/5/22 7:25 pm MT)
