### ISSUE TITLE
Stuttering for sim when in studio wrapper 

### ISSUE THREAD

**Issue by JaronDroder** [phetsims/qa#843]
### Test Device

Alien ware m15 r7

### Operating System

Windows 11
### Browser

Version 106.0.5249.119 

### Problem Description
Seen in https://github.com/phetsims/qa/issues/838

Stuttering in simulation when set to fast on the studio wrapper (not present in actual sim, just in the studio wrapper)

### Steps to Reproduce
1.Open the studio wrapper for the Gravity and Orbits Simulation
2.Select the model scene 
3.select the fast option in the bottom left hand corner 
4.Start the simulation, and there should be a stuttering as the earth progresses around the sun

### Visuals

![Phet training test](https://user-images.githubusercontent.com/115029534/196254067-13fea391-f704-4695-97ea-9f50de44cd97.gif)

**Comment by samreid** [comment]
I think part of this may be explained by https://github.com/phetsims/qa/issues/843, I'll make a note there.

**Comment by samreid** [comment]
#843 was removed and @zepumph and I published a dev version at https://bayes.colorado.edu/dev/html/gravity-and-orbits/1.7.0-dev.1/phet-io/wrappers/studio/.  @JaronDroder can you please compare that performance you observed in 1.6.0-rc.1 on the same computer?

**Comment by JaronDroder** [comment]
Just checked the new version and the problem's been fixed, thanks.

**Comment by JaronDroder** [comment]
Checked the issue on the same device and the new version seems to have corrected the problem on my end, thanks!
