### ISSUE TITLE
Prototype Test: Mean: Share and Balance 1.0.0-rc.1

### ISSUE THREAD

**Issue by marlitas** [phetsims/qa#848]
<h1>Prototype Test</h1>

**Mentions**: @kathy-phet, @amanda-phet, @samreid, @KatieWoe 

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/mean-share-and-balance/issues)
- [phet top level directory](https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-rc.1)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-rc.1/phet/mean-share-and-balance_all_phet.html)

<h3>Test Matricies</h3>

- [General Test Matrix](https://docs.google.com/spreadsheets/d/1iSUaKeuJBKnJvayZM3jUXMRknxdVt3p-CN0JsCD04YU/edit#gid=373109450)

<h3>Features included</h3>

- [x] Alternative Input
- UI Sound
- Sonification
- Description
- Voicing

<h3>Focus and Special Instructions</h3>

This our first RC test and everything is fair game.

<h3>Issues to Verify</h3>

No issues to verify.

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Play with the simulation normally.
- Make sure you can't lose anything.
- Complete the test matrix.
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- Focus on pedagogy issues and bugs that break the sim.
- If you find bugs beyond pedagogy/breaking, still document these bugs as github issues.
- If a11y aspects are present, test them, but with an eye for "normal use".

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

<h3>If a11y aspects are present, test them, but with an eye for "normal use".</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Interactive Description
  - Sound and Sonification
  - Pan and Zoom
  - Mobile Description
  - Voicing
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).
- If this sim is not in [this list](https://phet.colorado.edu/en/accessibility/prototypes) or up to date there, make an
  issue in [website](https://github.com/phetsims/website) to ask if PhET research page links need updating. Please
  assign to @terracoda and @emily-phet.

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[here](https://github.com/phetsims/qa/blob/master/documentation/accessibility-bugs.md). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel
controls. Please test magnfication and make sure it is working as intended and well with the use cases of the
simulation. Due to the way screen readers handle user input, magnification is NOT expected to work while using a screen
reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Memory Test:
<img width="346" alt="mem" src="https://user-images.githubusercontent.com/41024075/199333977-2884d7e9-161c-4e86-baaa-d397df6cfee6.png">

**Comment by KatieWoe** [comment]
QA is done

**Comment by marlitas** [comment]
All issues addressed. Closing

**Comment by marlitas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prototype RC Test](https://trello.com/c/yDkU4f9z/14-prototype-rc-test)
