### ISSUE TITLE
Dev Test: Capacitor Lab: Basics phet/phet-io

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#85]
Published here:
https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.6.0-dev.3/phet/capacitor-lab-basics_en_phet.html
https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.6.0-dev.3/phet-io/wrappers/index/

The development was done in https://github.com/phetsims/capacitor-lab-basics/issues/218 in preparation for an upcoming study by Stanford and also Visualizing Engagement usage by Diana.

The simulation has not been through a PhET-iO redesign--when we perform that, we expect the Instance Proxies to be refined/reduced.

Known issues:
* Some instance proxies number properties do not have correct range (the angle properties)
* There is no top-level user message when dragging the voltmeter out of the toolbox (though there is a nested user message), see https://github.com/phetsims/capacitor-lab-basics/issues/221

The Stanford study will focus on the data collection, so this QA step should make sure the data stream looks reasonable.  We will also need to test all other wrappers and the simulation itself so the simulation can be published as a new version of a phet-io simulation.  Here are @kathy-phet notes regarding testing:

> Yes, let’s do good testing on this and publish  as available. Although not necessarily final instrumentation.

> First round of testing should be sanity check. Then more obscure usage.

From the email thread it seems it could be used as early as the week of February 12, it would be nice to have it tested it well in advance in case trouble arises, and so we have time to create supporting wrappers.

Assigned to @ariel-phet for prioritization and assignment.

Wrappers Checklist:
- [x] Chrome, Windows
- [x] Firefox, Windows
- [x] Edge, Windows
- [x] Chrome, Mac
- [x] Firefox, Mac
- [x] Safari, Mac
- [x] Chrome, Chrome OS

**Comment by ariel-phet** [comment]
making co-top-priority with #83

**Comment by lmulhall-phet** [comment]
Looked at events colorized and JSON wrappers. Nothing to report. Also performed string tests. Nothing to report. Pointer areas look good. No bugs to report.

**Comment by samreid** [comment]
@phet-steele anything else to do here?

**Comment by samreid** [comment]
I don't think we'll have the PhET-iO redesign before RC, but we probably need https://github.com/phetsims/capacitor-lab-basics/issues/223 in the next version.  Closing and continuing in that issue.

**Comment by phet-steele** [comment]
If possible, it would be great if these two issues were also addressed:

> Known issues:
> 
> Some instance proxies number properties do not have correct range (the angle properties)

> There is no top-level user message when dragging the voltmeter out of the toolbox (though there is a nested user message), see phetsims/capacitor-lab-basics#221
