### ISSUE TITLE
Beta test: Haptics Playground 1.1.1 Android app

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#855]
The Android version of the Haptics Playground app is ready for beta testing.  The previous (alpha) test was completed, and a couple of the issues were addressed.  I have provided @KatieWoe with a Samsung Android tablet that supports haptic vibration, so she should be able to test on that device for this round of testing.

As was noted in the previous testing issue, this testing is intended to be fairly light since this is not expected to be a widely used app for PhET.  It is being published for potential use by the community of designers who are working to add multi-modal capabilities to educational apps.  The bottom line is that we're not looking for perfect behavior, but rather something that can be used by motivated designers.  Testing should focus on making sure that the app doesn't crash, that the primary functions appear to work correctly, and that there isn't anything that is terribly confusing about how the UI works.

Testers must be signed in with their pre-registered Google accounts, and can install the app from https://play.google.com/apps/internaltest/4701271652165855719.  Please contact @jbphet if other testers need to be added.

Issues should be logged at https://github.com/phetsims/quake/issues.

Issues to verify:

- [x] [Only 1 or 9 clicks available](https://github.com/phetsims/quake/issues/29)

Assigning to @KatieWoe and @kathy-phet for prioritization.

**Comment by KatieWoe** [comment]
I've noticed that, turning on sound, the sound may be off the first time something is played. This is either after first turned on, or not having been used for awhile. For instance, the first buzz of a set may not play or buzzes may run together. The actual haptics don't seem to be impacted.

**Comment by KatieWoe** [comment]
QA spot check is done. Checked on one device (the haptics capable tablet in the office). Check was fairly quick/light.

**Comment by jbphet** [comment]
> I've noticed that, turning on sound, the sound may be off the first time something is played. This is either after first turned on, or not having been used for awhile. For instance, the first buzz of a set may not play or buzzes may run together. The actual haptics don't seem to be impacted.

I've seem similar behavior on our sims on all manner of devices.  I think that devices often turn off the amplifier that drives the speakers in order to save power when they are not being used, and it takes a bit of time for it to come on when sound is produced after a long idle time.  If my supposition is correct here, there isn't much the code can do about it.

**Comment by jbphet** [comment]
Thanks for the testing QA team!  I'll close this issue and move forward with the next steps.
