### ISSUE TITLE
Performance comparison on Safari

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/qa#856]
As part of https://github.com/phetsims/geometric-optics-basics/issues/31, I applied the patch https://github.com/phetsims/scenery/commit/8ebb1eb3aae93a70a746f841818228f943581bb7. I'm somewhat concerned this could lower performance in Safari (on some sims?)

@KatieWoe would you be able to check how performance feels on a few performance-critical (already kind of slow) simulations (ideally on iPad Safari, or whatever Safari is particularly slow and in use)?

Ideally we'd compare the last built version of a sim compared to the master-built version of the sim (e.g. the phettest built version, after hitting the build button), for at least a few simulations. If there is no major performance regression, we're good!

If there is a performance regression, I'll be able to create built versions with/without the patch, so that we can test whether the patch causes the regression.

**Comment by Nancy-Salpepi** [comment]
I didn't notice any changes in performance. I was testing on an iPad 9th generation with iOS 16. I looked at the following sims: Energy Forms and Changes, Energy Skate Park, Gas Properties, Geometric Optics, Natural Selection, and Projectile Motion. 
@KatieWoe is also looking at this issue.

**Comment by KatieWoe** [comment]
I haven't seen any difference either. I focused on Geometric Optics and Geometric Optics Basics, and looked at both iOS 16 and iOS 14.

**Comment by kathy-phet** [comment]
@KatieWoe @Nancy-Salpepi - Thank you! 

@jonathanolson - We will leave both fixes in master then, and we will maintenance release the one fix you mentioned was easy to maintenance release! 

I'll close this issue.
