### ISSUE TITLE
"RC" Testing for Capacitor Lab Basics 1.6.1

### ISSUE THREAD

**Issue by samreid** [phetsims/QA#86]
There is an upcoming large-scale data-driven study for Capacitor Lab Basics, details are in 
https://github.com/phetsims/phet-io-wrappers/issues/49
and
https://github.com/phetsims/capacitor-lab-basics/issues/218

Dev testing already completed in #85 

Since then, @jonathanolson reworked the model to include the identity of things in contact with the probes in https://github.com/phetsims/capacitor-lab-basics/issues/223 .  As he noted, the model as it pertains to the voltmeter/voltages/probe contacts has been rewritten and will need to be thoroughly tested (on one platform).

Another change that would be good to check (one platform) is https://github.com/phetsims/capacitor-lab-basics/issues/221

Also, since chipper 2.0 is relatively new and PhET-iO parts have not been thoroughly vetted, I recommend this "RC" test actually be done on a "production" version in order to match the operating characteristics of a production PhET-iO deploy which will be used for the study.  I published a version and the wrappers/index link as well as an embedded metacog recorder link are described in this comment: (don't use this link to test) https://github.com/phetsims/phet-io-wrappers/issues/49#issuecomment-360278323.  So to clarify, this is kind of like an "RC" test, but I recommend we test something built with `grunt production`.  Also, I did not publish the phet-branded version because that would have overwritten the one on the public PhET-brand website.  If this test goes OK, then I think we should do a spot check on a real RC, then publish to both the PhET website and PhET-iO website.

I am not publishing the URLs here because they are not password protected (they need to be open for consistency with the upcoming study).

You can use the latter link in https://github.com/phetsims/phet-io-wrappers/issues/49#issuecomment-360853289 for recording data to metacog at the fixed size iframe.  After doing some trial recordings from different platforms, notify me and I can request the data from metacog to make sure it came out correctly.

@ariel-phet can you please review all my notes above and comment on whether it seems sensible--I know this is an unconventional approach, but hopefully will only need to be done once or twice as we are moving forward with chipper 2.0.  Also please prioritize, schedule, delegate.

**Comment by ariel-phet** [comment]
Lots hinging on this test....making top priority

**Comment by jonathanolson** [comment]
I published 1.6.2, which has the fix for the "Bar Graph" => "Bar Graphs" for the 1st screen (see https://github.com/phetsims/capacitor-lab-basics/issues/225).

**Comment by samreid** [comment]
This doesn't invalidate any tests already run, but new tests should be on 1.6.2.  I'll post URLs in a new private comment.

**Comment by jonathanolson** [comment]
Published 1.6.4 with fixes for battery voltage snapping (phetsims/capacitor-lab-basics#227) and current indicator arrows fixes (phetsims/capacitor-lab-basics#228). @samreid I updated the versions in the links, let me know if that is sufficient or if there is anything else in the links that needs to change.

URLs are at:
https://github.com/phetsims/phet-io-wrappers/issues/49#issuecomment-361349280

Presumably testing the snapping and current indicator visibility would be good for this, in addition to whatever other testing is relevant.

**Comment by jonathanolson** [comment]
Pushed 1.6.5 with a regression fix for the current indicator arrow. URLs are at: https://github.com/phetsims/phet-io-wrappers/issues/49#issuecomment-361741640

I'm looking into adjusting permissions to make it like 1.6.4.

**Comment by jonathanolson** [comment]
Adjusted permissions, 1.6.5 wrappers should be public.

**Comment by phet-steele** [comment]
Links were delivered this morning, nothing else for QA to do here. @samreid @jonathanolson I believe we wanted to move forward with phet brand?

**Comment by jonathanolson** [comment]
So, we should look into making a phet-branded RC (1.6.6-rc.1?) to look for a 1.6.6 phet-brand production deployment?

**Comment by samreid** [comment]
@jonathanolson that sounds correct to me.

**Comment by jonathanolson** [comment]
@phet-steele, https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.6.6-rc.1/phet/capacitor-lab-basics_en_phet.html is ready for testing. Let me know if you want a fresh issue/etc.

**Comment by phet-steele** [comment]
> is ready for testing. Let me know if you want a fresh issue/etc.

Yes please, for @ariel-phet's sake.

**Comment by phet-steele** [comment]
Okay....I made the testing issue in https://github.com/phetsims/QA/issues/94.
