### ISSUE TITLE
Dev test: Coulomb's Law 1.0.0-dev.13

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/QA#87]
@ariel-phet @emily-phet @jessegreenberg @arouinfar Coulomb's Law is ready for its initial dev testing. There is still some pixel polishing/scaling to be done (see https://github.com/phetsims/coulombs-law/issues/39), but that will not affect the functionality of the sim.

**Link to sim (with keyboard nav)**:  https://www.colorado.edu/physics/phet/dev/html/coulombs-law/1.0.0-dev.13/phet/coulombs-law_en_phet.html?accessibility

Platforms to test (@phet-steele no need at this point to test phet-io, I think):

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] iPad2 

Desired keyboard interaction:
- Tab/Shift tab to  navigation focusable elements
- Spacebar activates checkboxes
- Spacebar/Enter activates reset all button
- Left/Right arrow keys increment/decrement charge controls
-  Charges act like sliders
  - Arrow keys move charges 0.1 cm/1 pm
  - Page up/page down move charges 1 cm/10 pm
  - Home/End moves charges to min/max location
- Ruler moves freely with arrow keys
  - arrow keys move the ruler 0.2cm / 2pm
  - shift+arrow keys move the ruler 0.1cm / 1pm
  - ruler exhibits press-and-hold movement
    - short presses will increment the position by one of the above amount
    - holding an arrow key will continuously move the ruler after a brief pause

Helpful query params
- ?showGrid: charges are constrained to discrete locations for reproducible measurements, charge centers and ruler tick marks should always align with grid lines.

Let me know if you have any other questions. Assigning to @ariel-phet to prioritize this test.

**Comment by ariel-phet** [comment]
Next up after #84 is complete

**Comment by phet-steele** [comment]
Dev done.
