### ISSUE TITLE
Prototype Test: Greenhouse Effect 1.1.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#871]
<h1>Prototype Test</h1>

**Mentions**: @arouinfar, @kathy-phet, @katiewoe, and @jessegreenberg 

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/greenhouse-effect/issues)
- [phet top level directory](https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.0-rc.1/phet/greenhouse-effect_all_phet.html)

<h3>Test Matricies</h3>

- [General Test Matrix](https://docs.google.com/spreadsheets/d/1WPjDJAFPrEthYIG7pdSIhffPYVPfFWIbQOUFFVReyvU/edit#gid=704235393)

<h3>Features included</h3>

- [x] Alternative Input
- [x] UI Sound
- [x] Sonification
- [ ] Description (first screen only)

<h3>Focus and Special Instructions</h3>

This prototype adds two new screens that did not exist in the previous prototype, namely the "Photons" and "Layer
Model" screens.  The focus of this testing should be to verify that these two screens appear to behave correctly
and do not have any major behavioral issues.  The first screen has had some changes made to it as well, so it should
be regression tested.

In addition to the new screens, the following features have been added and should be tested:
- Sound design.
- Dynamic locales and layouts.
- The artwork has been updated, so please look for anything that is problematic in that area.
- The focus order has been updated, so please verify that it is reasonable.

<s>Description was implemented for the first screen in the previous prototype, but has not been completed for the second
nor the third, so please regression test it on the first screen and make sure that there isn't anything egregiously wrong
with it on the second and third screens, but gaps and omissions are expected on those screens.</s>
Edit: Screen reader testing will not be a part of this QA cycle, see https://github.com/phetsims/qa/issues/871#issuecomment-1374195707.

<h3>Issues to Verify</h3>

We've been doing verification of issues internally between the development and design teams, so there isn't anything to
list in this section for this round of testing.

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Play with the simulation normally.
- Make sure you can't lose anything.
- Complete the test matrix.
- Try to include version numbers for browsers
- If there is a console available, check for errors and include them in the Problem Description.
- Focus on pedagogy issues and bugs that break the sim.
- If you find bugs beyond pedagogy/breaking, still document these bugs as github issues.
- If a11y aspects are present, test them, but with an eye for "normal use".

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

<h3>If a11y aspects are present, test them, but with an eye for "normal use".</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Interactive Description
  - Sound and Sonification
  - Pan and Zoom
  - Mobile Description
  - Voicing
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).
- If this sim is not in [this list](https://phet.colorado.edu/en/accessibility/prototypes) or up to date there, make an
  issue in [website](https://github.com/phetsims/website) to ask if PhET research page links need updating. Please
  assign to @terracoda and @emily-phet.

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[here](https://github.com/phetsims/qa/blob/master/documentation/accessibility-bugs.md). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel
controls. Please test magnfication and make sure it is working as intended and well with the use cases of the
simulation. Due to the way screen readers handle user input, magnification is NOT expected to work while using a screen
reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Memory Test:
![greenmem](https://user-images.githubusercontent.com/41024075/209402340-a41b11a4-3cac-4250-97bc-2848b2e9f818.png)

**Comment by KatieWoe** [comment]
https://github.com/phetsims/ratio-and-proportion/issues/542 is an issue in this sim as well. Should I make a sim specific issue for it?

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/ratio-and-proportion/issues/542 Added alternative input support for sliders when using a number pad. It didn't seem important enough to me to maintenance release RCs or published sims, but I think it is a call for @kathy-phet or @arouinfar.

**Comment by arouinfar** [comment]
> Description was implemented for the first screen in the previous prototype, but has not been completed for the second
nor the third, so please regression test it on the first screen and make sure that there isn't anything egregiously wrong
with it on the second and third screens, but gaps and omissions are expected on those screens.

@jbphet the previous prototype does not support alt input or description. It looks like @Nancy-Salpepi discovered a possible regression in https://github.com/phetsims/greenhouse-effect/issues/254, but in general, I'm not sure how much time or effort we should put into testing screen reader behavior for the prototype. We agreed to leave `supportsInteractiveDescription: true` but not advertise the feature.

**Comment by arouinfar** [comment]
> in general, I'm not sure how much time or effort we should put into testing screen reader behavior for the prototype.

Discussed with @jbphet and we decided to proceed with screen reader testing as originally requested. We are unlikely to fix screen reader bugs for the prototype since we aren't advertising the feature. However, it's still important to know about the existing bugs.

**Comment by arouinfar** [comment]
@kathy-phet said:

>  Given the backlog in QA, I think we should forgo the screenreader testing ... this adds a lot to a test and we need to focus on moving things through that are important for the release. We can put it back in for a screen reader only focused test when there is more bandwidth for QA - before we pick GHE description up again.

@Nancy-Salpepi has let the QA channel know about this change, and I will update the test issue.

**Comment by KatieWoe** [comment]
Calling QA here

**Comment by stemilymill** [comment]
While testing on chromebook, I noticed some jerky animation due to low-performance device. Did not impact usability, but seemed like it should be mentioned.

here is a video https://photos.google.com/search/_tra_/photo/AF1QipO959Ux95b9MvWKr2Os_Nzeb0F7QT7D3VTkWR3i

sorry the video is not embedded here, I dont know why github isn't letting me add it

**Comment by jbphet** [comment]
Thanks QA team.  I'll follow up on the individual issues noted above.  Closing.
