### ISSUE TITLE
RC Test: pH Scale: Basics 1.6.0-rc.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#873]
<h1>RC Test</h1>

**Mentions**: @arouinfar @kathy-phet @KatieWoe 

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/ph-scale-basics/issues)
- [phet top level directory](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.0-rc.1)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.0-rc.1/phet/ph-scale-basics_all_phet.html)
- [phet-io wrapper index](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.0-rc.1/phet-io)
- [link to phet-io zip file](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.0-rc.1/phet-io/ph-scale-basics-phet-io-1.6.0-rc.1.zip)
- Previous phet-io version: https://phet-io.colorado.edu/sims/ph-scale-basics/1.5/

<h3>Test Matricies</h3>

- [General Test Matrix](https://docs.google.com/spreadsheets/d/1QP3_4PEghNvkaEF8hkGaojGnpCrnWeDEJl4wYJ072KE/edit#gid=1688983623)
- [PhET-iO Test Matrix](https://docs.google.com/spreadsheets/d/1LekmGeqrcPQwqcpS_RBXaIEzp8KteEXAfSJw7U2fMuI/edit#gid=660033448)

<h3>Features included</h3>

- [x] PhET-iO
- Alternative Input
- UI Sound
- Sonification
- Description
- Voicing

<h3>Focus and Special Instructions</h3>

This testing should be done in conjunction with https://github.com/phetsims/qa/issues/872 (RC Test: pH Scale 1.6.0-rc.1). _pH Scale: Basics_ is identical to the _Concentration_ screen of _pH Scale_, with one difference: The beaker does not autofill when the sim starts, or when changing solutes via the Solute combobox.

The focus of this release is PhET-iO. General sim features have changed very little, but PhET-iO instrumentation has been brought up to current conventions.

PhET-iO migration needs to be tested against the previous version (see link above). If you have questions about how to test migration, please contact @zepumph or @samreid.

<h3>Issues to Verify</h3>

This issue has the "status:ready-for-review" label. Please close after verifying.

- [x] https://github.com/phetsims/ph-scale/issues/265

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Test all query parameters on all platforms. (See [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md) for a list of query parameters.)
- Download HTML on Chrome and iOS.
- Make sure the iFrame version of the simulation is working as intended on all platforms.
- Make sure the XHTML version of the simulation is working as intended on all platforms.
- Complete the test matrix.
- Don't forget to make sure the sim works with Legends of Learning.
- Test the Game Up harness on at least one platform.
- Check [this](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0) LoL
  spreadsheet and notify AR or AM if it not there.
- If this is rc.1 please do a memory test.
- When making an issue, check to see if it was in a previously published version.
- Try to include version numbers for browsers.
- If there is a console available, check for errors and include them in the Problem Description.
- As an RC begins and ends, check the sim repo. If there is a maintenance issue, check it and notify developers if there is a problem.
- As the RC ends, please review the QA credits in the about dialog.  If the QA credits are complete and correct, please add a comment in the RC test issue indicating so.  If not, please open a new issue and specify what changes should be made.

<hr>

</details>

<details>
<summary><b>PhET-iO features</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
  sure the simulation loads without crashing or throwing errors.
- Load the login wrapper just to make sure it works. Do so by adding this link from the sim deployed root:
  ```
  /wrappers/login/?wrapper=record&validationRule=validateDigits&&numberOfDigits=5&promptText=ENTER_A_5_DIGIT_NUMBER
  ```   
  Further instructions in QA Book
- Conduct a recording test to Metacog, further instructions in the QA Book. Do this for iPadOS + Safari and one other
  random platform.
- Conduct a memory test on the stand alone sim wrapper (rc.1).
- Test one platform combination with `?phetioDebug=true` on the Studio and State wrapper.
- If Pan/Zoom is supported, make sure that it works when set with PhET-iO State.
- Test that the sim works offline:
  * Click the link to the phet-io zip file (at top of issue) to download the zip file.
  * Unzip it to a spot locally.
  * Open `index.html` by double clicking it on your desktop or in a Finder-view.
  * It should look like the standalone version of the sim in PhET-iO brand.

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Interactive Description
  - Sound and Sonification
  - Pan and Zoom
  - Mobile Description
  - Voicing
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).
- If this sim is not in [this list](https://phet.colorado.edu/en/accessibility/prototypes) or up to date there, make an
  issue in [website](https://github.com/phetsims/website) to ask if PhET research page links need updating. Please
  assign to @terracoda and @emily-phet.

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[here](https://github.com/phetsims/qa/blob/master/documentation/accessibility-bugs.md). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by liammulh** [comment]
@pixelzoom, @mattpen, I'm seeing 503s for the favicon.

Request Headers:
```
GET /favicon.ico HTTP/1.1
Host: phet-dev.colorado.edu
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0
Accept: image/avif,image/webp,*/*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Referer: https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.0-rc.1/phet/ph-scale-basics_all_phet.html
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
```

Response Headers:
```
HTTP/1.1 503 Backend fetch failed
Date: Wed, 18 Jan 2023 23:40:45 GMT
Server: Varnish
Content-Type: text/html; charset=utf-8
Retry-After: 5
X-Varnish: 3081711
Age: 0
Via: 1.1 varnish-v4
Content-Length: 284
Connection: close
```

Seemingly, it just isn't on the file system: https://phet-dev.colorado.edu/favicon.ico. Not sure if that's even worthy of a GitHub comment, but I think QA is supposed to be thorough.

**Comment by mattpen** [comment]
It should either be a 404 or it should be delivered, I'll go ahead and add one tomorrow.

**Comment by mattpen** [comment]
Actually, this seems more complicated.  https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.0-rc.1/phet-io/index.html is acutally pointing at https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.0-rc.1/phet-io/favicon.ico.  This seems like it needs to be fixed in phet-io, not just a missing resource on phet-dev.colorado.edu.

**Comment by Nancy-Salpepi** [comment]
@mattpen @pixelzoom the 503 error isn't specific to pH Scale and has been showing up in testing for a while. When I asked a developer, I was told to only worry about this error if it appears on phet.colorado.edu or phet-io.colorado.edu.

**Comment by pixelzoom** [comment]
@mattpen @liammulh This "503 error" problem should really be in its own GitHub issue, not in this QA issue. I'll be happy to relocated it.  Which repo is approprite for a GitHub issue?

**Comment by mattpen** [comment]
I dived a bit deeper this morning and opened an issue for the favicon error: https://github.com/phetsims/website/issues/1387

**Comment by pixelzoom** [comment]
@mattpen Thanks for creating https://github.com/phetsims/website/issues/1387.  In an effort to clean up the "noise" in this issue, I've moved relevant comments from this issue to that issue.  And I'm now going to delete them from this issue.

**Comment by pixelzoom** [comment]
I moved 5 comments in this issue to https://github.com/phetsims/website/issues/1387#issuecomment-1398790122.

**Comment by KatieWoe** [comment]
Memory test and PhET-iO Memory test:
<img width="347" alt="basemem" src="https://user-images.githubusercontent.com/41024075/213781322-ca876ccb-8e08-44c5-b6a9-e93e6174394d.png">
<img width="348" alt="baseiomem" src="https://user-images.githubusercontent.com/41024075/213781328-e94206d8-ba5a-4fbd-9066-da7de24666d0.png">

**Comment by KatieWoe** [comment]
QA is done

**Comment by pixelzoom** [comment]
100% of the issues found were related to PhET-iO migration or PhET-iO change requests.  We'll need another RC.
