### ISSUE TITLE
Dev Test: Quadrilateral 1.0.0-dev.73

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/qa#879]
<h1>Dev Test</h1>

**Mentions**: @BLFiedler @terracoda @emily-phet @kathy-phet @KatieWoe

This issue is for a dev test of the sim Quadrilateral. Please see "Focus and Special Instructions" for a description
of the sim and other info.

Assigning to @kathy-phet for prioritization. Last week we discussed preparing the dev test and then assessing how it
fits into other testing priorities when it is ready. It is ready! Let me know if we should discuss as a team now how to
prioritize this.

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/quadrilateral/issues)
- [phet top level directory](https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.73)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.73/phet/quadrilateral_all_phet.html)

<h3>Test Matrix</h3>

Please include all (non-screen reader) feature testing in these records if applicable.

- [x] Latest macOS, Safari (Time =4hrs)
- [ ] Windows 10, Chrome (Time = )
- [x] Windows 10/11, Firefox (Time = 2)
- [x] Latest iOS, Safari (Time =2.5hrs)
- [x] Windows 11, Chrome (Time = 3)

Light testing, or optionally skip if time crunch:

- [x] Latest macOS, Chrome (Time = 1.75hrs)
- [x] Latest Chrome OS, Chrome (Time = 1.5hrs)

<h3>Features included</h3>

- PhET-iO
- [x] Alternative Input
- [x] UI Sound
- [x] Sonification
- Description
- [x] Voicing

<h3>Focus and Special Instructions</h3>

The purpose of this dev test is to thoroughly exercise it as it gets closer to publication. The Inclusive Design
team would like this simulation published by the end of Q1 2023 and having a dev test complete in January is important
to reach that goal.

The Quadrilateral sim lets you explore quadrilateral shapes and shape properties. You should be able to find the
following shapes:

- Square
- Rectangle
- Rhombus
- Kite
- Isosceles Trapezoid
- Trapezoid
- Concave Quadrilateral
- Convex Quadrilateral
- Triangle
- Parallelogram
- Dart

Sounds will play representing shapes and shape properties. Shape properties are aspects of the geometry that define the
shape name, such as the number of equal angles, number of equal side lengths, number of parallel sides, and so on.
There are two sound designs. The first (default) layers sounds such that as you add more shape properties, more sounds
play. The second design just highlights one unique sound per detected shape.

There is a setting in the Preferences Dialog that lets you play the sounds forever. It may be useful in testing.

This sim supports Voicing, and the voiced content should accurately describe the shape and changes as vertices and
sides are moved.

Please see the Keyboard Shortcuts dialog for a list of supported keyboard commands.

Please note that this sim DOES NOT support Interactive Description or dynamic locales.

Potentially useful query parameters:
- ?showModelValues - Shows measurements of the shape. If something seems incorrect, looking at these values could be helpful.
- ?showDragAreas - Shows where Vertices are allowed to move in the play area. Vertices are constrained within the play area bounds and cannot move in a way that creates overlap with other sides/vertices or a crossed shape.
- ?reducedStepSize - Vertices move at smaller intervals allowing for very precise positioning.

As always, please reach out if you have any questions about the sim!

<h3>Issues to Verify</h3>

These issues should have the "status:ready-for-review" label. Unless an issue says to close after verifying, assign the
issue back to the developer.

- None

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<hr>

</details>

<details>
<summary><b>PhET-iO features</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
  sure the simulation loads without crashing or throwing errors.

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Interactive Description
  - Sound and Sonification
  - Pan and Zoom
  - Mobile Description
  - Voicing
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[here](https://github.com/phetsims/qa/blob/master/documentation/accessibility-bugs.md). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary>

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by Nancy-Salpepi** [comment]
For mac: Ignoring that Voicing still says "alt" even though 'Option' is shown. I can see that this was already fixed in master as part of https://github.com/phetsims/scenery-phet/issues/793

**Comment by jessegreenberg** [comment]
Thanks Nancy! The update to Voicing should be there in master but the change was made after dev.73 was built.

**Comment by jessegreenberg** [comment]
Hey QA team, sorry I forgot to note in the original issue. Could you do a check for any performance problems on the slowest device that PhET supports if you have time?

**Comment by Nancy-Salpepi** [comment]
FYI @jessegreenberg I didn't notice any major performance issues with the Chromebook. I believe the rest of the QA team is also going to take a look.

**Comment by KatieWoe** [comment]
I tested an iPadOS 14 device and it was running smoothly.

**Comment by Nancy-Salpepi** [comment]
Under Focus and Special Instructions, it  says 
>The first (default) layers sounds such that as you add more shape properties, more sounds
play. The second design just highlights one unique sound per detected shape.

For the second design I still hear a combination of sounds for each shape (which is different than the combo I hear for the default). Is that correct?

**Comment by BLFiedler** [comment]
Yes. The second sound design plays all tracks all the time, but raises one track's volume above the rest for each shape. There is no conceptual mapping for this sound design.

**Comment by BLFiedler** [comment]
Also, there is no connection between the two sound designs regarding track selection. There are necessarily more tracks in the non-default since there is no layering.

**Comment by KatieWoe** [comment]
Is it intentional that the "Voice helpful hints" box is read as "extra help" in voicing?

**Comment by jessegreenberg** [comment]
Good question, I promoted to an issue.

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Excellent, thank you team!! These are great things to fix and we appreciate the recommendations.

Can you please comment on how "thorough" this dev test was compared to usual? I think I heard this was to be a time-limited test. Knowing will just help plan for the next test.

**Comment by KatieWoe** [comment]
This was a fairly standard dev test. The plan was to find as many bugs as we could, then call it early. However, we didn't end up finding a lot so that calling early never happened.

**Comment by jessegreenberg** [comment]
OK, thanks @KatieWoe - thats good to hear. Closing.
