### ISSUE TITLE
RC Spot-Check Test: GA Maintenance Release

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/qa#882]
RC Spot-Check Test

Mentions: @KatieWoe @jonathanolson 
https://phet-dev.colorado.edu/html/friction/1.5.18-rc.1/phet/friction_en_phet.html
https://phet-dev.colorado.edu/html/friction/1.5.18-rc.1/phet/friction_en_phet.html?ga=UA-5033201-2&ga4=G-NT4RB93Q46
https://jonathanolson.net/phet/ga30-test.html?ga=UA-5033201-2&ga4=G-NT4RB93Q46

Making sure this is working as intended (loads on supported platforms)
Make sure stats are sent to GA across browsers - see 2 collect calls:
tid: G-4EVJVBSTB9
tid: UA-5033201-1

Simulation links

General Test:

 Tester = KW, Platform = Windows 11 (Chrome, Firefox, Edge), Time =
 Tester = ON, Platform = , Time =

**Comment by oliver-phet** [comment]
I'm seeing some possible indications that our new GA4 property is firing twice. 
https://phet-dev.colorado.edu/html/friction/1.5.18-rc.1/phet/friction_en_phet.html?ga=UA-5033201-2&ga4=G-NT4RB93Q46&SafariDuplicateTest
https://phet-dev.colorado.edu/html/friction/1.5.18-rc.1/phet/friction_en_phet.html?ga=UA-5033201-2&ga4=G-NT4RB93Q46&SafariDuplicateTest2
https://phet-dev.colorado.edu/html/friction/1.5.18-rc.1/phet/friction_en_phet.html?ga=UA-5033201-2&ga4=G-NT4RB93Q46&FirefoxDuplicateTest
https://phet-dev.colorado.edu/html/friction/1.5.18-rc.1/phet/friction_en_phet.html?ga=UA-5033201-2&ga4=G-NT4RB93Q46&FirefoxDuplicateTest2

**Comment by oliver-phet** [comment]
Also going to test these since our 3rd party UA is still "Connected" to our 3rd party GA4 - to see if that is the potential cause.
https://jonathanolson.net/phet/ga30-test.html?ga=UA-5033201-2&ga4=G-NT4RB93Q46&FirefoxDuplicateExternal
https://jonathanolson.net/phet/ga30-test.html?ga=UA-5033201-2&ga4=G-NT4RB93Q46&FirefoxDuplicateExternal2

**Comment by oliver-phet** [comment]
Ok - looks like a false alarm. All of the tests above showed 1 View in our new GA4 analytics 
<img width="641" alt="Screenshot 2023-01-14 at 8 31 23 PM" src="https://user-images.githubusercontent.com/5090275/212521603-f1840f4b-4fb5-45a3-82b4-b5d771be9458.png">

Also, both of the query parameter properties received 1 view for each test page.
<img width="676" alt="image" src="https://user-images.githubusercontent.com/5090275/212521808-94232be4-50f2-40c5-9ca9-e67ceb33e641.png">

The external test links (from jonathanolson.net) also registered 2 views in the PhET Third Party GA4 account, as expected:
<img width="747" alt="image" src="https://user-images.githubusercontent.com/5090275/212521894-7bbf7af1-0235-44d3-b708-140816ad1a77.png">

The only inconsistency are the views recorded to our new GA4 analytics property: 5 pages registered a single view (after filtering for any page that contains "Duplicate"). `SafariDuplicateTest` is missing. It was recorded on every other property (UA, both external query parameter properties). It may have just been a peculiar case, not sure.

@jonathanolson I think we're safe to deploy - hits are recording properly (mostly) and there aren't any duplicate hits.

**Comment by jonathanolson** [comment]
Ok thanks, will plan to move forward with the deployment! Got some other patches fixed up.

**Comment by jonathanolson** [comment]
Closing, thanks!
