### ISSUE TITLE
Should the thermometer be linked with ambiance sounds?

### ISSUE THREAD

**Issue by CliffordH123** [phetsims/qa#887]
Test device
ASUS ROG STRIX Windows 10 Pro

Operating System
Version	10.0.19044 Build 19044

Browser
Firefox/Chrome

Noticed on [phetsims/qa#885](https://github.com/phetsims/qa/issues/885) that the `surface thermometer` check box will also turn off the background music/ambiance track. This leaves only the noise of the photons bouncing around (in the case of the screens which have photons) or the low noise of the waves (for the wave screen). Seems like this is not the intention but wasn't sure.

Steps to reproduce:

1. Begin any of the various screens
2. Allow ambiance "music" and sound of wave/photons to being
3. Disable the surface thermometer and notice that "music" is off
![surface therm](https://user-images.githubusercontent.com/9455257/214147141-4effb746-7aca-4ce1-8465-b6c406af7b7e.PNG)
4. Re-enable surface thermometer and notice return of "music"

**Comment by arouinfar** [comment]
Thanks @CliffordH123 that is indeed the intended behavior. The more musical sound is mapped to the surface temperature. So long as `Surface Thermometer` or `Show Surface Temperature` (Waves Screen) is checked, the sound should be heard.
