### ISSUE TITLE
Dev Test: Beer's Law Lab 1.7.0-dev.8

### ISSUE THREAD

**Issue by matthew-blackman** [phetsims/qa#889]
<h1>Dev Test</h1>

**Mentions**: @Nancy-Salpepi @KatieWoe @kathy-phet @pixelzoom @stemilymill @zepumph @samreid @arouinfar 

Publication of this sim is being generally tracked in https://github.com/phetsims/beers-law-lab/issues/300

Note 1: Beer's Law Lab supports dynamic locale

Note 2: This sim does not support migration and this sim does not need to account for migration rules

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/beers-law-lab/issues)
- [phet top level directory](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-dev.8)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-dev.8/phet/beers-law-lab_all_phet.html)
- [phet-io wrapper index](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-dev.8/phet-io)
- [link to phet-io zip file](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-dev.8/phet-io/beers-law-lab-phet-io-1.7.0-dev.8.zip)

<h3>Test Matrix</h3>

Please include all (non-screen reader) feature testing in these records if applicable.

- [x] Latest macOS, Safari (Time = 1.5hrs)
- [ ] Windows 10, Chrome (Time = 1.25)
- [ ] Windows 10, Firefox (Time = )
- [x] Latest iOS, Safari (Time = 1.5hrs)
- [x] Windows 11, Chrome (Time = 2.5)

Light testing, or optionally skip if time crunch:

- [ ] Latest macOS, Chrome (Time = )
- [ ] Latest Chrome OS, Chrome (Time = )

If PhET-iO is being tested:

- [x] Latest macOS, Safari (Time = 2.75hrs)
- [ ] Windows 10, Chrome (Time = 1)
- [ ] Windows 10, Firefox (Time = 2)
- [x] Latest iOS, Safari (Time =.75hrs)
- [x] Windows 11, Chrome (Time = 4.5)

<h3>Features included</h3>

- [x] PhET-iO (but no migration)

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<hr>

</details>

<details>
<summary><b>PhET-iO features</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
  sure the simulation loads without crashing or throwing errors.

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Interactive Description
  - Sound and Sonification
  - Pan and Zoom
  - Mobile Description
  - Voicing
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[here](https://github.com/phetsims/qa/blob/master/documentation/accessibility-bugs.md). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by arouinfar** [comment]
PSA for QA: The dev version was published before examples.md was created, so it does not appear on the Wrapper Index Page and any link you find to it will appear broken. However, it now exists here:
https://github.com/phetsims/phet-io-sim-specific/blob/master/repos/beers-law-lab/examples.md

Please review it how you normally would.

**Comment by KatieWoe** [comment]
Memory test:
<img width="347" alt="beermem" src="https://user-images.githubusercontent.com/41024075/215601331-c1b0befa-9869-4f5b-a4e8-947fa6c83b61.png">
PhET-iO Memory test:
<img width="350" alt="beermemio" src="https://user-images.githubusercontent.com/41024075/215601375-faa3ff9f-7ca9-424e-b1b9-bf693b641e2f.png">

**Comment by pixelzoom** [comment]
@KatieWoe I do not see the heap size decreasing in the above snapshots. That's indicative of a slow memory leak, but I see that you did not create a GitHub issue. Could you please run a longer test, to verify that heap size does go down at some point?  And if does not go down, please create an issue.

**Comment by pixelzoom** [comment]
@samreid pointed out that:
> 8=>9 goes down in PhET brand
> 9 => 10 goes down in PhET-iO brand.

And actually 3 => 4 goes down in both brands.  So no need to test further.

**Comment by zepumph** [comment]
Is "going down" between snapshots the only metric for a lack of a memory leak? There are many sims with a plethora of dynamic elements (like Number Play cards, or potentially BLL particles), where snapshot one may have 10,000 particles in the running sim, and then snapshot two only has 5,000. I wouldn't want QA to get the idea that a decrease in heap size between those two snapshots eliminates the possibility of a slower memory leak. That said, it has never been clear to me what QA's role is specifically in identifying memory leaks, perhaps only the outrageous ones are worth their time.

**Comment by KatieWoe** [comment]
When I'm deciding to make an issue, I'm looking for the footprints too be under 100 MB, and to plateau in growth. Going down in between snapshots is generally a good metric for that. However, if it's growing otherwise I would still make an issue. In general, QA's roll is to do the measurements, and if I can clearly see a problem I make an issue. Otherwise, I leave the results of the test in a comment for the developer to look over, in case there is a problem that I missed.

**Comment by KatieWoe** [comment]
Calling QA here

**Comment by samreid** [comment]
Issues addressed, RCs published, we will continue in the RC test.
