### ISSUE TITLE
RC Test: Expression Exchange 1.1.0-rc.1

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#9]
(@amanda-phet, @ariel-phet) Expression Exchange 1.1.0-rc.1 is ready for RC testing.

**[Link to sim](http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.1.0-rc.1/expression-exchange_en.html)**

**[Link to iFrame](http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.1.0-rc.1/expression-exchange_en-iframe.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1zpwf-oEVo0Fun3YiBWMoNTuts2OOtB7CiNUbw3LWaoo/edit#gid=2)**

**Issues to Verify**
(*all should be marked "status:fixed-pending-testing"*)  
Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/expression-exchange/issues/95##
- [x] https://github.com/phetsims/expression-exchange/issues/106##
- [x] https://github.com/phetsims/expression-exchange/issues/118##
- [x] https://github.com/phetsims/expression-exchange/issues/119##

**Please also verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any new issues are found, please note them in https://github.com/phetsims/expression-exchange/issues and reference this issue.  

 **(Other potentially useful items)**  

Sim-specific query parameters useful for testing:  
• `?showRewardNodeEveryLevel` - shows the reward node on every level so that it can be seen and tested without having to play the entire game
• `?minimalGameLevels` - reduces the number of game levels from 8 to 2 so that the 'all levels completed' behavior can be more easily verified

Sim-specific terminology:  
• coin terms - the things that the user creates, drags around, and combines
• expressions - two or more coin terms combined together in a form that can be seen in a rectangle and moved around as one entity
• creator box - the areas at the bottom of many screens that allows the user to drag out coin terms into the play area

**Comment by phet-steele** [comment]
@jbphet this is done. Ready for rc.2
