### ISSUE TITLE
Maintenance release spot check: Removing "novelty" voices

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/qa#907]
Sims impacted by https://github.com/phetsims/utterance-queue/issues/93 are ready for a maintenance release spot check. Can you please make sure that the "novelty" voices can no longer be selected for Voicing from Preferences? Also, can you please make sure that changing voices and basic speech synthesis is still working correctly.

Sims to test:
- [x] https://phet-dev.colorado.edu/html/john-travoltage/1.6.11-rc.1/phet/john-travoltage_en_phet.html
- [x] https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.10-rc.1/phet/gravity-force-lab-basics_en_phet.html

@Nancy-Salpepi and I discussed this issue today and thought it could be a good backlog task.

**Comment by jessegreenberg** [comment]
@jonathanolson is starting a maintenance release that will put additional changes on these versions. Lets hold off on verifying this until the batch is done. Ill update links and comment on anything else to verify when that is done.

**Comment by samreid** [comment]
I added an on-hold label based on the previous remark.

**Comment by jessegreenberg** [comment]
@jonathanolson's maintenance release is finished so this is no longer on hold.

**Comment by Nancy-Salpepi** [comment]
Sorry @jessegreenberg: 
>However, I am seeing this issue: https://github.com/phetsims/friction/issues/326 now with Chrome 110.0.5481.177 and MacOS 13.2.1 (but not in published).

When I checked published I must have been in safari. The behavior is the same in published and in this rc for Chrome. 

>In addition, in chrome with Voicing toggled to off, if I press Reset All while a Quick Info Alert is being uttered, Voicing isn't interrupted.

This behavior is also the same in published and in the rc's.
