### ISSUE TITLE
Maintenance release spot check: Studio autoselect

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/qa#910]
@kathy-phet @samreid @arouinfar @Nancy-Salpepi https://github.com/phetsims/studio/issues/295 has been fixed. We started a maintenance release, and this issue is to spot check the fix. For each of the following sims, please
- Run studio and move your mouse to an instrumented UI component. Without moving the mouse, press "alt" and "ctrl" keys to autoselect studio items.
- In Windows, make sure that pressing alt works more than once, and focus does not move to the shishkebab in the chrome tools.
- Spot check the phet brand sim for ~30 seconds per sim to make sure nothing is broken.

- [x] Gravity and orbits 1.6
    - [x] https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.9-rc.1/phet/gravity-and-orbits_en_phet.html
    - [x] https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.9-rc.1/phet-io/
- [x] ph-scale 1.6
    - [x] https://phet-dev.colorado.edu/html/ph-scale/1.6.2-rc.1/phet/ph-scale_en_phet.html
    - [x] https://phet-dev.colorado.edu/html/ph-scale/1.6.2-rc.1/phet-io/
- [x] ph-scale-basics 1.6
    - [x] https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.2-rc.1/phet/ph-scale-basics_en_phet.html
    - [x] https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.2-rc.1/phet-io/
- [x] friction 1.6
    - [x] https://phet-dev.colorado.edu/html/friction/1.6.2-rc.3/phet/friction_en_phet.html
    - [x] https://phet-dev.colorado.edu/html/friction/1.6.2-rc.3/phet-io/
- [x] concentration 1.7
    - [x] https://phet-dev.colorado.edu/html/concentration/1.7.2-rc.1/phet/concentration_en_phet.html
    - [x] https://phet-dev.colorado.edu/html/concentration/1.7.2-rc.1/phet-io/
- [x] beers-law-lab 1.7
    - [x] https://phet-dev.colorado.edu/html/beers-law-lab/1.7.2-rc.1/phet/beers-law-lab_en_phet.html
    - [x] https://phet-dev.colorado.edu/html/beers-law-lab/1.7.2-rc.1/phet-io/
- [x] Circuit Construction Kit: DC 1.3
    - [x] https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-rc.2/phet/circuit-construction-kit-dc_en_phet.html
    - [x] https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.0-rc.2/phet-io/

Assigning to @kathy-phet to prioritize in the QA pipeline, this issue is second in the priority list for this iteration.

**Comment by Nancy-Salpepi** [comment]
all done @jessegreenberg and @samreid!

**Comment by jessegreenberg** [comment]
Excellent, thank you @Nancy-Salpepi. We will continue in https://github.com/phetsims/studio/issues/295.

**Comment by jessegreenberg** [comment]
Excellent, thank you @Nancy-Salpepi. We will continue in https://github.com/phetsims/studio/issues/295.
