### ISSUE TITLE
Dev test: Resistance in a Wire 1.5.0-dev.1

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/QA#92]
@emily-phet @terracoda Accessible Resistance in a Wire is ready for a dev test. This version includes keyboard navigation and auditory description. This task is mostly to test screen reader behavior, but please verify that the sim works correctly in general.

Before beginning, familiarize yourself with how a screen reader works. Here is a page with information about PhET's supported screen readers and documentation about how to use them:
[Screen reader intro](https://www.colorado.edu/physics/phet/dev/html/jg-tests/reader-intro.html)

**Link to sim:** https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.5.0-dev.1/phet/resistance-in-a-wire_en_phet.html

The above sim has descriptions that can be read with a screen reader. That content can be "seen" here:

**Link to a11y view**: https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.5.0-dev.1/phet/resistance-in-a-wire_a11y_view.html

While testing, please make sure that all descriptions and alerts accurately describe the state of the simulation. They should also always be readable with a screen reader using common navigation strategies.

PhET supports the following platforms for accessibility so please test these:
- [x] JAWS with latest Windows, latest Firefox
- [x] NVDA with latest Windows, latest Firefox
- [x] VoiceOver with latest macOS, latest Safari

JAWS might complain about Firefox Quantum. If that is the case, please test with https://www.mozilla.org/en-US/firefox/organizations/

Assigning to @phet-steele. @terracoda can you also please review this version? @ariel-phet can you please assign priority to this issue?

**Comment by terracoda** [comment]
@jessegreenberg, sounds awesome in Voice Over and Safari (Mac 10.13.2, Safari 11.02)

It all works great for me.
It is also easy to jump back and forth between PDOM and alerts to compare the state of the equation with the alerts.

The only description that I was  not expecting was this one where there are three explicit "much much larger than"'s. All three sliders are different,  and R is so huge it is off screen. I don't think have a better way to handle this edge case, so I think we have to go with "much much larger" across the equation phrase.

A user would not get a sense of any difference between between rho, L, and A, but they would get a sense that R is huge.
<img width="1055" alt="screen shot 2018-02-09 at 18 09 29" src="https://user-images.githubusercontent.com/1902116/36051781-ca4a1c94-0dc5-11e8-9e05-846a4c230226.png">

**Comment by terracoda** [comment]
Also, I get the added "a lot" at the appropriate times, I think.

**Comment by jessegreenberg** [comment]
Thanks @terracoda! Sorry I forgot to mention, we usually track progress in qa repository issues but create new bug reports in the sim repo. Ill create an issue in resistance-in-a-wire for the above bug and if you notice anything else please create an issue there.

**Comment by phet-steele** [comment]
This is done..finally. Screen readers are hard!

**Comment by jessegreenberg** [comment]
Excellent, thank you @phet-steele and team. Closing issue.
