### ISSUE TITLE
Dev Test: Calculus Grapher 1.0.0-dev.25

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#921]
<h1>Dev Test</h1>

**Mentions**: @amanda-phet @kathy-phet @KatieWoe @veillette @ariel-phet 

Our target date to begin this test is Monday 3/20/23.

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/calculus-grapher/issues)
- [phet top-level directory](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.25)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.25/phet/calculus-grapher_all_phet.html)
- [phet-io wrapper index](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.25/phet-io)

<h3>Test Matrix</h3>

Please include all (non-screen reader) feature testing in these records if applicable.

- [x] Latest macOS, Safari (Time = 3hrs)
- [x] Windows 10, Chrome (Time = 2hrs)
- [ ] Windows 10/11, Firefox (Time = 2)
- [ ] Latest iOS, Safari (Time = )
- [x] Windows 11, Chrome (Time = 6.25)
- [x] Latest Chrome OS, Chrome (Time = 2)

Light testing, or optionally skip if time crunch:

- [ ] Latest macOS, Chrome (Time = )

If PhET-iO is being tested:

- [x] Latest macOS, Safari (Time =4hrs)
- [ ] Windows 10, Chrome (Time = 1hr)
- [ ] Windows 10/11, Firefox (Time =3 )
- [x] Latest iOS, Safari (Time = 1.5)
- [x] Windows 11, Chrome (Time =3.5 )

<h3>Features included</h3>

- [x] PhET-iO
- [ ] <s> Alternative Input </s>
- [ ] <s> UI Sound </s>
- [ ] <s> Sonification </s>
- [ ] <s> Description </s>
- [ ] <s> Voicing </s>

<h3>Focus and Special Instructions</h3>

* Skim [model.md](https://github.com/phetsims/calculus-grapher/blob/master/doc/model.md) and [implementation-notes.md](https://github.com/phetsims/calculus-grapher/blob/master/doc/implementation-notes.md).
* Read the [Terminology](https://github.com/phetsims/calculus-grapher/blob/master/doc/implementation-notes.md#terminology) section of implementation-notes.md, and try to use that terminology when reporting issues.
* Exercise the 6 public query parameters that appear in [CalculusGrapherQueryParameters.ts] (https://github.com/phetsims/calculus-grapher/blob/master/js/common/CalculusGrapherQueryParameters.ts).
* Exercise the 5 preferences found in the Simulation tab of the Preferences dialog.
* Exercise "labeled lines", a feature that can be accessed only via PhET-iO.  See `model.tools.labeledLines` in Studio. Ask @pixelzoom @veillette or @amanda-phet if you have questions.
* Exercise "labeled points", a feature that can be accessed only via PhET-iO.  See `model.tools.labeledPoints` in Studio. Ask @pixelzoom @veillette or @amanda-phet if you have questions.
* Prior memory testing was done in https://github.com/phetsims/calculus-grapher/issues/265, if you'd like to compare results.
* There is one place where overlapping pointer areas are acceptable. See https://github.com/phetsims/calculus-grapher/issues/267#issuecomment-1459197100.
* Issue https://github.com/phetsims/calculus-grapher/issues/292 discusses a combination of QueryParameters that is useful for testing. 

<h3>Issues to Verify</h3>

none

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<hr>

</details>

<details>
<summary><b>PhET-iO features</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
  sure the simulation loads without crashing or throwing errors.

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Interactive Description
  - Sound and Sonification
  - Pan and Zoom
  - Mobile Description
  - Voicing
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[here](https://github.com/phetsims/qa/blob/master/documentation/accessibility-bugs.md). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by pixelzoom** [comment]
The dev version for this test was published on Sunday 3/20, and this issue was moved to "Active Tests" in the QA Pipeline.

@KatieWoe when this test is completed, please tell us who should be added to QA credits.  You can do that either via a comment in this issue, or in https://github.com/phetsims/calculus-grapher/issues/202.

**Comment by veillette** [comment]
Here is some terminology that can be useful for the curve manipulation modes.

| Left | Right |
| --------------- | --------------- |
| HILL | TRIANGLE |
| PEDESTAL  | PARABOLA |
| SINUSOID | FREEFORM |
| TILT| SHIFT |

![image](https://user-images.githubusercontent.com/7633344/226468592-361643bb-b600-4b6d-aed0-f0d6876ee38f.png)

**Comment by KatieWoe** [comment]
The sim seems to be quite laggy when using the Data: Textarea wrapper. Is this a concern/worth an issue?

**Comment by veillette** [comment]
> The sim seems to be quite laggy when using the Data: Textarea wrapper. Is this a concern/worth an issue?
You are probably trying to change the curve points. There is a lot of meta data associated with a curve since all points have  some metadata associated with them.

**Comment by KatieWoe** [comment]
Note on iPad performance. Performance of the sim was good for the most part. In some PhET-iO wrappers it has more lag such as in the State wrapper. I think this is alright, as discussed in https://github.com/phetsims/calculus-grapher/issues/313 but let me know if you want an issue.

**Comment by stemilymill** [comment]
Chromebook performance: sim performance is good, just very slight lag with the freeform tool

**Comment by KatieWoe** [comment]
Calling QA here

**Comment by pixelzoom** [comment]
Thanks QA team!  You found some great stuff.  Our plan is to finish addressing issues, then move on to RC testing.  So I think we can go ahead and close this issue.

**Comment by pixelzoom** [comment]
Thanks QA team!  You found some great stuff.  Our plan is to finish addressing issues, then move on to RC testing.  So I think we can go ahead and close this issue.
