### ISSUE TITLE
Website Test Lite: user services migration

### ISSUE THREAD

**Issue by mattpen** [phetsims/qa#922]
This is a follow up on https://github.com/phetsims/qa/issues/909. 

<h3>Relevant links</h3>

- [github repository for new issues](https://github.com/phetsims/website-direct/issues)

<h3>Test Matrix</h3>

Please include all (non-screen reader) feature testing in these records if applicable.

- [x] Latest macOS, Safari (Time =4hrs)
- [ ] Windows 10, Chrome (Time =)
- [ ] Windows 10/11, Firefox (Time =.5)
- [x] Latest iOS, Safari (Time =1)
- [x] Windows 11, Chrome (Time 7)

Light testing, or optionally skip if time crunch:

- [ ] Latest macOS, Chrome (Time = )
- [ ] Latest Chrome OS, Chrome (Time = )

If screen readers are being tested:

- [ ] Win 10/11 Chrome + Jaws (Time =)
- [ ] Win 10/11 Firefox + NVDA (Time =1)
- [ ] MacOS Safari + VO (Time =.5)
- [ ] iPadOS Mobile VO (Time = .5)

<h3>Features included</h3>

- [ ] Screen Reader Browsing
- [ ] Keyboard Input

<h3>Focus and Special Instructions</h3>

<h4> Issues to Confirm </h4>

Please evaluate whether the following issues have been fixed, and close the issues if they have.

- [x] https://github.com/phetsims/website-direct/issues/42
- [x] https://github.com/phetsims/website-direct/issues/50
- [x] https://github.com/phetsims/website-direct/issues/21
- [x] https://github.com/phetsims/website-direct/issues/22
- [x] https://github.com/phetsims/website-direct/issues/23
- [x] https://github.com/phetsims/website-direct/issues/24
- [x] https://github.com/phetsims/website-direct/issues/28
- [x] https://github.com/phetsims/website-direct/issues/39
- [x] https://github.com/phetsims/website-direct/issues/26
- [x] https://github.com/phetsims/website-direct/issues/19
- [x] https://github.com/phetsims/website-direct/issues/49
- [x] https://github.com/phetsims/website-direct/issues/46

<h4> General Testing </h4>

After completing the issues to confirm, pleae do some general testing on the following, to catch any regressions that may have arisen since the last test.  But I would say spend no more than 4-5 hours total on testing these.

What to test:

- [ ] Login
  - [ ] Using the user button in the persistent nav on any page
- [ ] [Registration](https://ox-dev.colorado.edu/en/register) and [Edit Profile](https://ox-dev.colorado.edu/en/edit-profile)
  - [ ] Test that all fields that are required are correctly reporting errors.
  - [ ] Test that all fields correct persist new data after registration/edit.
- [ ] [Password Reset](https://ox-dev.colorado.edu/en/reset-password-request)
- [ ] [Resend Email Confirmation](https://ox-dev.colorado.edu/en/resend-email-confirmation)

*** **Important!** *** These tests should all be completed with both (a) an account that is synced from the existing production database for phet.colorado.edu and (b) a new account created from scratch on https://ox-dev.colorado.edu.  I'll need to coordinate with the people testing this issue to establish some test accounts for (a).

Please test the above in English, and two other locales, one of which should be RTL, e.g. English `en`, Spanish `es`, and Arabic (Saudi Arabia) `ar_SA`,

**Comment by KatieWoe** [comment]
Calling QA here

**Comment by mattpen** [comment]
Looks great! Thanks @KatieWoe @Nancy-Salpepi @stemilymill!
