### ISSUE TITLE
Dev Test: Number Play 1.1.0-dev.10

### ISSUE THREAD

**Issue by chrisklus** [phetsims/qa#925]
<h1>Dev Test</h1>

**Mentions**: @amanda-phet @zepumph @chrisklus @Nancy-Salpepi @kathy-phet @KatieWoe 

This is the first dev test since 1.0 was published in spring of 2022, but please note that https://github.com/phetsims/qa/issues/917 has some overlap with Number Play. Thanks all!

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/number-play/issues)
- [phet top-level directory](https://phet-dev.colorado.edu/html/number-play/1.1.0-dev.10)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/number-play/1.1.0-dev.10/phet/number-play_all_phet.html)

<h3>Test Matrix</h3>

Please include all (non-screen reader) feature testing in these records if applicable.

- [x] Latest macOS, Safari (Time = 3.5hrs)
- [ ] Windows 10, Chrome (Time = 1.5)
- [x] Windows 10/11, Firefox (Time = 1.5)
- [x] Latest iOS, Safari (Time = 3.5)
- [x] Windows 11, Chrome (Time =4.5)

Light testing, or optionally skip if time crunch:

- [x] Latest macOS, Chrome (Time =1.75hrs)
- [x] Latest Chrome OS, Chrome (Time = 1hr)

<h3>Features included</h3>

- Speech Synthesis (not voicing, but still speaks to you).

<h3>Focus and Special Instructions</h3>

* Please test the locale settings and number speaking quite extensively, as we have made made changes here even since the number-compare dev.6 dev test.
* Please note that there are lots of great cases and examples of imperfection with ordering, layering, and hiding objects especially on the lab screen. Feel free to make GitHub issues for this kind of thing, but please don't spend an exorbitant amount of time here, as there is a good chance that, unless it poses serious concern pedagogically, that we do not have the bandwidth to fix it.
* The Lab screen is the exact same code as Number Compare except that this Lab screen doesn't have compare symbol cards.
* The Game screen has not changed much since 1.0 - the main change is that there is a reward node now.

<h3>Issues to Verify</h3>

These issues should have the "status:ready-for-review" label. Unless an issue says to close after verifying, assign the
issue back to the developer.

- [x] https://github.com/phetsims/number-compare/issues/32

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Interactive Description
  - Sound and Sonification
  - Pan and Zoom
  - Mobile Description
  - Voicing
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Calling testing here

**Comment by chrisklus** [comment]
Thanks you all!! I'm going to go ahead and close.
