### ISSUE TITLE
Test installers produced by updated installer builder

### ISSUE THREAD

**Issue by jbphet** [phetsims/QA#93]
The installer builder has been updated to use the _all.html files (see https://github.com/phetsims/installer-builder/issues/54).  The builds are currently succeeding, so it would be good for them to get some testing before starting to deploy these to the production sever.  The installers that should be tested are currently available at https://ox-dev.colorado.edu/en/offline-access.

**Comment by phet-steele** [comment]
@jbphet, the installer from 2/28/2018 is looking great. You have been notified that this can probably go live.
