### ISSUE TITLE
Dev Test: Density 1.1.0-dev.3

### ISSUE THREAD

**Issue by samreid** [phetsims/qa#930]
<h1>Dev Test</h1>

**Mentions**: @arouinfar, @DianaTavares

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/density/issues)
- [phet top-level directory](https://phet-dev.colorado.edu/html/density/1.1.0-dev.3)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/density/1.1.0-dev.3/phet/density_all_phet.html)
- [phet-io wrapper index](https://phet-dev.colorado.edu/html/density/1.1.0-dev.3/phet-io)

<h3>Test Matrix</h3>

Please include all (non-screen reader) feature testing in these records if applicable.

- [x] Latest macOS, Safari (Time = 1.75)
- [ ] Windows 10, Chrome (Time = )
- [x] Windows 10/11, Firefox (Time = 3)
- [x] Latest iOS, Safari (Time = 3)
- [x] Windows 11, Chrome (Time = 3)

Light testing, or optionally skip if time crunch:

- [x] Latest macOS, Chrome (Time = 1.25hrs)
- [ ] Latest Chrome OS, Chrome (Time = )

If PhET-iO is being tested:

- [x] Latest macOS, Safari (Time = 2.5hrs)
- [x] Windows 10, Chrome (Time = 2.5hrs)
- [x] Windows 10/11, Firefox (Time = 3)
- [x] Latest iOS, Safari (Time = 1hr)
- [x] Windows 11, Chrome (Time = 3)

<h3>Features included</h3>

- [x] PhET-iO
<s>-  Alternative Input
-  UI Sound
-  Sonification
-  Description
-  Voicing </s>

<h3>Focus and Special Instructions</h3>

<h3>Issues to Verify</h3>

These issues should have the "status:ready-for-review" label. Unless an issue says to close after verifying, assign the
issue back to the developer.

- [x] https://github.com/phetsims/density/issues/140
- [x] https://github.com/phetsims/density/issues/147

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<hr>

</details>

<details>
<summary><b>PhET-iO features</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
  sure the simulation loads without crashing or throwing errors.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by jonathanolson** [comment]
Dev version up, edited the issue to match.

**Comment by Nancy-Salpepi** [comment]
@arouinfar On the iPad with iOS 16.4.1 +safari, noting that the top of the scale looks very jagged. The sides of the blocks are also a bit jagged. I also see this in the published version. Let me know if you would like me to make an issue.

<details>
<summary>Pictures</summary>
<img width="188" alt="Screenshot 2023-04-25 at 3 54 27 PM" src="https://user-images.githubusercontent.com/87318828/234388843-a4564a63-554a-4c95-b449-8d83932fd797.png">
<img width="441" alt="Screenshot 2023-04-25 at 3 55 02 PM" src="https://user-images.githubusercontent.com/87318828/234388873-72681f7e-6093-427e-885f-c7aff3012142.png">

</details>

**Comment by Nancy-Salpepi** [comment]
@arouinfar I can’t autoselect the mass labels on the blocks to get to model.showMassesProperty. Should I be able to?

**Comment by KatieWoe** [comment]
Calling QA here

**Comment by arouinfar** [comment]
> On the iPad with iOS 16.4.1 +safari, noting that the top of the scale looks very jagged. The sides of the blocks are also a bit jagged. I also see this in the published version. Let me know if you would like me to make an issue.

I don't think this merits an issue. Looks like the typical Safari artifacts that we've seen in Density before.

> I  can’t autoselect the mass labels on the blocks to get to model.showMassesProperty. Should I be able to?

No, I don't think so. Thanks for checking!

> Calling QA here

Thanks QA!

**Comment by jonathanolson** [comment]
Thanks!
