### ISSUE TITLE
RC Test: Capacitor Lab: Basics 1.6.6-rc.1

### ISSUE THREAD

**Issue by phet-steele** [phetsims/QA#94]
@arouinfar, Capacitor Lab: Basics 1.6.6-rc.1 is ready for RC testing.

**[Link to sim](https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.6.6-rc.1/phet/capacitor-lab-basics_all_phet.html)**

**[Link to iFrame](https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.6.6-rc.1/phet/capacitor-lab-basics_all_iframe_phet.html)**

**[Test Matrix](https://docs.google.com/spreadsheets/d/1E_HoXYhttDYPm5HT01e54N6S9m9T1XqUk-w2kIKfngI/edit#gid=1103660702)**

**Issues to Verify**

Please test the following issues and check them off after addressing. If they are resolved, close them.  If not, they should be updated.

- [x] https://github.com/phetsims/capacitor-lab-basics/issues/227
- [x] https://github.com/phetsims/capacitor-lab-basics/issues/225
- [x] https://github.com/phetsims/capacitor-lab-basics/issues/223 this issue passes if probes behave correctly. No need to look in phet-io wrappers.

Note that https://github.com/phetsims/capacitor-lab-basics/issues/230 is still an issue, so performance may suffer in Firefox/Edge. @ariel-phet, depending on your thoughts on this issue, we can either release after a spot check with a fix or release after this RC (pending no issues)

**Please also verify**
- [x] stringTest=double (all strings doubled)
- [x] stringTest=long (exceptionally long strings)
- [x] stringTest=X (short strings)
- [x] stringTest=rtl (right-to-left)
- [x] stringTest=xss (test passes if sim does not redirect, OK if sim crashes or fails to fully start)
- [x] showPointerAreas (touchArea=red, mouseArea=blue)
- [x] Full screen test
- [x] Screenshot test

If any new issues are found, please note them in https://github.com/phetsims/capacitor-lab-basics/issues and reference this issue.  
 
**Other potentially useful items**  

Sim-specific query parameters useful for testing:  
• `?showDebugAreas` - shows the intersection bounds for probe measurements. 

@ariel-phet please assign and prioritize

**Comment by ariel-phet** [comment]
@phet-steele perfromance "as is" is unacceptable on Edge in the situation you showed me. However it seemed like changing the renderer to svg solved the performance issues. It seems the sim should be tested with SVG on edge and firefox, if no issues are found with using that solution, the SVG solution should be used.

**Comment by lmulhall-phet** [comment]
QA is done.

**Comment by jonathanolson** [comment]
> @phet-steele perfromance "as is" is unacceptable on Edge in the situation you showed me. However it seemed like changing the renderer to svg solved the performance issues. It seems the sim should be tested with SVG on edge and firefox, if no issues are found with using that solution, the SVG solution should be used.

Did you want me to push out this release, or wait for investigation to see if the SVG default would work on Edge for this sim?

**Comment by ariel-phet** [comment]
@jonathanolson no, we should not yet push out this release. I would like to at least investigate the Edge performance issue.

**Comment by ariel-phet** [comment]
Closing this issue for the moment, since we will likely do another RC or punt on the performance issues.
