### ISSUE TITLE
Regression test - meta keys on MacOS

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/qa#941]
I pushed a workaround for a macOS problem: https://github.com/phetsims/scenery/issues/1555 -  found during quadrilateral testing. Before I cherry-pick the change into release branches and continue with other maintenance releases, can you please do some regression and platform testing?

1) Can you please make sure that the issue is fixed?
2) Can you please do some rigorous testing with the command keys (left and right) and other keyboard shortcuts on macOS safari? Does anything break when using those or other keys?

Thank you!

**Comment by stemilymill** [comment]
This seems fixed on safari, but not on chrome or firefox. @Nancy-Salpepi sees the same thing.

**Comment by jessegreenberg** [comment]
Oh no! Sorry about that and thank you for noticing. I misunderstood and thought it was only happening in Safari. Please hold off on further testing, I will apply the fix to Mac and then reassign when ready.

**Comment by jessegreenberg** [comment]
It was straight forward to apply to mac instead of just Safari. @stemilymill @KatieWoe @Nancy-Salpepi this should be ready to test in master again.

**Comment by Nancy-Salpepi** [comment]
@jessegreenberg this is still broken for me with FF but working with safari and chrome.

**Comment by jessegreenberg** [comment]
I added key codes for FF. Can you confirm that is working @Nancy-Salpepi?

**Comment by Nancy-Salpepi** [comment]
Yes! Working now on FF.

**Comment by Nancy-Salpepi** [comment]
I did a fair amount of testing this morning on safari. I didn't see any issues with Quad, RAP, GO, and MSS.

**Comment by jessegreenberg** [comment]
Hey @KatieWoe, I noticed this was removed from the pipeline. Is testing for this complete?

**Comment by KatieWoe** [comment]
I think this is good for an "Issues to Verify" level

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe! Closing.
