### ISSUE TITLE
Maintenance Release:  Alt input fixes

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/qa#946]
This is a batch of maintenance releases for https://github.com/phetsims/tasks/issues/1123. 

For each sim listed here, please:
- Test for a minute or two with mouse and alt input, making sure nothing is obviously broken.
- If the sim supports hotkeys, please make sure that https://github.com/phetsims/scenery/issues/1555 is fixed.
- Please verify that https://github.com/phetsims/joist/issues/897 is fixed by using the test harness at https://bayes.colorado.edu/dev/html/jg-tests/test.html.

Please let me know if you have any questions!

Release Candidate links

balloons-and-static-electricity 1.5 (https://github.com/phetsims/tasks/issues/1123)

- [x] [balloons-and-static-electricity 1.5.11-rc.1](https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.11-rc.1/phet/balloons-and-static-electricity_en_phet.html)

center-and-variability 1.0 (https://github.com/phetsims/tasks/issues/1123)

- [x] [center-and-variability 1.0.11-rc.1](https://phet-dev.colorado.edu/html/center-and-variability/1.0.11-rc.1/phet/center-and-variability_en_phet.html)
- [x] [center-and-variability 1.0.11-rc.1 phet-io](https://phet-dev.colorado.edu/html/center-and-variability/1.0.11-rc.1/phet-io/center-and-variability_all_phet-io.html?phetioStandalone)
- [x] [center-and-variability 1.0.11-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/center-and-variability/1.0.11-rc.1/phet-io/wrappers/studio)

circuit-construction-kit-ac 1.0 (https://github.com/phetsims/tasks/issues/1123)

- [x] [circuit-construction-kit-ac 1.0.13-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac/1.0.13-rc.1/phet/circuit-construction-kit-ac_en_phet.html)

circuit-construction-kit-ac-virtual-lab 1.0 (https://github.com/phetsims/tasks/issues/1123)

- [x] [circuit-construction-kit-ac-virtual-lab 1.0.12-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-ac-virtual-lab/1.0.12-rc.1/phet/circuit-construction-kit-ac-virtual-lab_en_phet.html)

circuit-construction-kit-dc 1.3 (https://github.com/phetsims/tasks/issues/1123)

- [x] [circuit-construction-kit-dc 1.3.5-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.5-rc.1/phet/circuit-construction-kit-dc_en_phet.html)
- [x] [circuit-construction-kit-dc 1.3.5-rc.1 phet-io](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.5-rc.1/phet-io/circuit-construction-kit-dc_all_phet-io.html?phetioStandalone)
- [x] [circuit-construction-kit-dc 1.3.5-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.5-rc.1/phet-io/wrappers/studio)

circuit-construction-kit-dc-virtual-lab 1.3 (https://github.com/phetsims/tasks/issues/1123)

- [x] [circuit-construction-kit-dc-virtual-lab 1.3.3-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.3-rc.1/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html)
- [x] [circuit-construction-kit-dc-virtual-lab 1.3.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.3-rc.1/phet-io/circuit-construction-kit-dc-virtual-lab_all_phet-io.html?phetioStandalone)
- [x] [circuit-construction-kit-dc-virtual-lab 1.3.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.3-rc.1/phet-io/wrappers/studio)

coulombs-law 1.0 (https://github.com/phetsims/tasks/issues/1123)

- [x] [coulombs-law 1.0.22-rc.1](https://phet-dev.colorado.edu/html/coulombs-law/1.0.22-rc.1/phet/coulombs-law_en_phet.html)

fourier-making-waves 1.0 (https://github.com/phetsims/tasks/issues/1123)

- [x] [fourier-making-waves 1.0.14-rc.1](https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.14-rc.1/phet/fourier-making-waves_en_phet.html)

friction 1.6 (https://github.com/phetsims/tasks/issues/1123)

- [x] [friction 1.6.5-rc.1](https://phet-dev.colorado.edu/html/friction/1.6.5-rc.1/phet/friction_en_phet.html)
- [x] [friction 1.6.5-rc.1 phet-io](https://phet-dev.colorado.edu/html/friction/1.6.5-rc.1/phet-io/friction_all_phet-io.html?phetioStandalone)
- [x] [friction 1.6.5-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/friction/1.6.5-rc.1/phet-io/wrappers/studio)

geometric-optics 1.3 (https://github.com/phetsims/tasks/issues/1123)

- [x] [geometric-optics 1.3.0-rc.2](https://phet-dev.colorado.edu/html/geometric-optics/1.3.0-rc.2/phet/geometric-optics_en_phet.html)
- [x] [geometric-optics 1.3.0-rc.2 phet-io](https://phet-dev.colorado.edu/html/geometric-optics/1.3.0-rc.2/phet-io/geometric-optics_all_phet-io.html?phetioStandalone)
- [x] [geometric-optics 1.3.0-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/geometric-optics/1.3.0-rc.2/phet-io/wrappers/studio)

geometric-optics-basics 1.3 (https://github.com/phetsims/tasks/issues/1123)

- [x] [geometric-optics-basics 1.3.0-rc.2](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.0-rc.2/phet/geometric-optics-basics_en_phet.html)
- [x] [geometric-optics-basics 1.3.0-rc.2 phet-io](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.0-rc.2/phet-io/geometric-optics-basics_all_phet-io.html?phetioStandalone)
- [x] [geometric-optics-basics 1.3.0-rc.2 phet-io Studio](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.0-rc.2/phet-io/wrappers/studio)

gravity-force-lab-basics 1.1 (https://github.com/phetsims/tasks/issues/1123)

- [x] [gravity-force-lab-basics 1.1.12-rc.1](https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.12-rc.1/phet/gravity-force-lab-basics_en_phet.html)

greenhouse-effect 1.0 (https://github.com/phetsims/tasks/issues/1123)

- [x] [greenhouse-effect 1.0.12-rc.1 phet-io](https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.12-rc.1/phet-io/greenhouse-effect_all_phet-io.html?phetioStandalone)
- [x] [greenhouse-effect 1.0.12-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/greenhouse-effect/1.0.12-rc.1/phet-io/wrappers/studio)

greenhouse-effect 1.1 (https://github.com/phetsims/tasks/issues/1123)

- [x] [greenhouse-effect 1.1.5-rc.1](https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.5-rc.1/phet/greenhouse-effect_en_phet.html)

john-travoltage 1.6 (https://github.com/phetsims/tasks/issues/1123)

- [x] [john-travoltage 1.6.13-rc.1](https://phet-dev.colorado.edu/html/john-travoltage/1.6.13-rc.1/phet/john-travoltage_en_phet.html)

mean-share-and-balance 1.0 (https://github.com/phetsims/tasks/issues/1123)

- [x] [mean-share-and-balance 1.0.9-rc.1](https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.9-rc.1/phet/mean-share-and-balance_en_phet.html)

molarity 1.4 (https://github.com/phetsims/tasks/issues/1123)

- [x] [molarity 1.4.25-rc.1 phet-io](https://phet-dev.colorado.edu/html/molarity/1.4.25-rc.1/phet-io/molarity_all_phet-io.html?phetioStandalone)
- [x] [molarity 1.4.25-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molarity/1.4.25-rc.1/phet-io/wrappers/studio/studio.html?sim=molarity&relativeSimPath)

my-solar-system 1.2 (https://github.com/phetsims/tasks/issues/1123)

- [x] [my-solar-system 1.2.1-rc.1](https://phet-dev.colorado.edu/html/my-solar-system/1.2.1-rc.1/phet/my-solar-system_en_phet.html)

quadrilateral 1.0 (https://github.com/phetsims/tasks/issues/1123)
- [x] [quadrilateral 1.0.0-rc.1](https://phet-dev.colorado.edu/html/quadrilateral/1.0.1-rc.1/phet/quadrilateral_en_phet.html)

ohms-law 1.4 (https://github.com/phetsims/tasks/issues/1123)

- [x] [ohms-law 1.4.21-rc.1](https://phet-dev.colorado.edu/html/ohms-law/1.4.21-rc.1/phet/ohms-law_en_phet.html)

ratio-and-proportion 1.2 (https://github.com/phetsims/tasks/issues/1123)

- [x] [ratio-and-proportion 1.2.6-rc.1](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.6-rc.1/phet/ratio-and-proportion_en_phet.html)

resistance-in-a-wire 1.6 (https://github.com/phetsims/tasks/issues/1123)

- [x] [resistance-in-a-wire 1.6.22-rc.1](https://phet-dev.colorado.edu/html/resistance-in-a-wire/1.6.22-rc.1/phet/resistance-in-a-wire_en_phet.html)

**Comment by jessegreenberg** [comment]
The automated maintenance release process skipped geometric-optics 1.3, geometric-optics-basics 1.3, and quadrilateral 1.0 because they are not yet released. I added them after redeploying manually so they can be spot checked in this batch.

**Comment by KatieWoe** [comment]
The test page for the third point looked alright on Win 11 Chrome

**Comment by KatieWoe** [comment]
QA is done

**Comment by jessegreenberg** [comment]
Great thanks @KatieWoe and QA team. I have begun the process to deploy to production.
