### ISSUE TITLE
Maintenance Release: Alt input fixes

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/qa#949]
It was reported that sims in the maintenance release from https://github.com/phetsims/tasks/issues/1123 created an issue with loss of focus. The reason this happened is identified and described in https://github.com/phetsims/tasks/issues/1123#issuecomment-1564600089. Thankfully, only a few sims were impacted.

The fixing patch was applied and RC's were built. Can you please spot check each for a couple of minutes and make sure that the issue is fixed? To verify that these builds have the fix, make sure that focus is not lost when you use alt input to navigate the preferences dialog or PhET menu.

- [x] gravity-force-lab-basics 1.1 (https://phet-dev.colorado.edu/html/gravity-force-lab-basics/1.1.13-rc.1/phet/gravity-force-lab-basics_all_phet.html)
- [x] fourier-making-waves 1.0 (https://phet-dev.colorado.edu/html/fourier-making-waves/1.0.15-rc.1/phet/fourier-making-waves_all_phet.html)
- [x] john-travoltage 1.6 (https://phet-dev.colorado.edu/html/john-travoltage/1.6.14-rc.1/phet/john-travoltage_all_phet.html)

**Comment by KatieWoe** [comment]
Spot check looks good on Win 11 Chrome

**Comment by jessegreenberg** [comment]
Great, thanks @KatieWoe ! OK Ill publish these to production.
