### ISSUE TITLE
Dev Test: Molecule Polarity 1.3.0-dev.3

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/qa#952]
<h1>Dev Test</h1>

**Mentions**: @arouinfar @kathy-phet @KatieWoe 

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/molecule-polarity/issues)
- [phet top-level directory](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.0-dev.3)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.0-dev.3/phet/molecule-polarity_all_phet.html)
- [phet-io wrapper index](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.0-dev.3/phet-io)

<h3>Test Matrix</h3>

Please include all (non-screen reader) feature testing in these records if applicable.

- [x] Latest macOS, Safari (Time = 1.5)
- [x] Windows 10, Chrome (Time = 1)
- [x] Windows 10/11, Firefox (Time = 2)
- [x] Latest iOS, Safari (Time = 1)
- [x] Windows 11, Chrome (Time =3.5)

Light testing, or optionally skip if time crunch:

- [ ] Latest macOS, Chrome (Time = )
- [x] Latest Chrome OS, Chrome (Time = .75)

If PhET-iO is being tested:

- [x] Latest macOS, Safari (Time = 3)
- [x] Windows 10, Chrome (Time = 2.25)
- [x] Windows 10/11, Firefox (Time = 3)
- [x] Latest iOS, Safari (Time = 2.75)
- [x] Windows 11, Chrome (Time = 3)

<h3>Features included</h3>

- [x] PhET-iO
- [ ] ~~Alternative Input~~
- [ ] ~~UI Sound~~
- [ ] ~~Sonification~~
- [ ] ~~Description~~
- [ ] ~~Voicing~~

<h3>Focus and Special Instructions</h3>

Changes in this release:
* the Options dialog was replaced with the Preferences dialog
* dynamic locale support was added
* the sim was brought up to the latest PhET-iO standards
* includes migration support from the previous version (https://phet-io.colorado.edu/sims/molecule-polarity/1.2/).

<h3>Issues to Verify</h3>

These issues should have the "status:ready-for-review" label. Unless an issue says to close after verifying, assign the
issue back to the developer.

- [x] https://github.com/phetsims/molecule-polarity/issues/141

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<hr>

</details>

<details>
<summary><b>PhET-iO features</b></summary>

<h3>What to Test</h3>

- Make sure that public files do not have password protection. Use a private browser for this.
- Make sure that private files do have password protection. Use a private browser for this.
- Make sure standalone sim is working properly.
- Make sure the wrapper index is working properly.
- Make sure each wrapper is working properly.
- Launch the simulation in Studio with ?stringTest=xss and make sure the sim doesn't navigate to youtube
- For newer PhET-iO wrapper indices, save the "basic example of a functional wrapper" as a .html file and open it. Make
  sure the simulation loads without crashing or throwing errors.

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Interactive Description
  - Sound and Sonification
  - Pan and Zoom
  - Mobile Description
  - Voicing
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).
  - Test all forms of input with a screen reader (if applicable).

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Platforms and Screen Readers to Be Tested</h3>

- Windows 10 + Latest Chrome + Latest JAWS
- Windows 10 + Latest Firefox + Latest NVDA
- macOS + Safari + VoiceOver
- iOS + Safari + VoiceOver (only if specified in testing issue)

<h3>Critical Screen Reader Information</h3>

We are tracking known screen reader bugs in
[here](https://github.com/phetsims/qa/blob/master/documentation/accessibility-bugs.md). If you find a
screen reader bug, please check it against this list.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/master/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by pixelzoom** [comment]
@KatieWoe Let me know when QA is ready to being testing. Then I'll deploy the dev version and replace the "TBD" placeholders in this issue.

**Comment by KatieWoe** [comment]
Memory test for PhET brand looks good to me.
<img width="348" alt="moleculemem" src="https://github.com/phetsims/qa/assets/41024075/51d93540-8c0a-4c5b-b727-2f8187406690">

**Comment by KatieWoe** [comment]
The Migration wrapper is found at https://phet-dev.colorado.edu/html/molecule-polarity/1.3.0-dev.3/phet-io/wrappers/migration/

**Comment by KatieWoe** [comment]
I've noticed this error appearing in the migration wrapper. It isn't in the console, but in the section below.
![showsup](https://github.com/phetsims/qa/assets/41024075/87e863f6-93bc-4a65-9154-15858df2a85f)

**Comment by Nancy-Salpepi** [comment]
@pixelzoom this is minor, but I noticed that the dipole symbols in the View panel on the Three Atoms screen aren't aligned in English or in any locale. This is different from what I just saw when testing Geometric Optics where the symbols have right alignment. Didn't know if you wanted to keep as is or make the change. 
<img width="227" alt="Screenshot 2023-06-09 at 12 07 22 PM" src="https://github.com/phetsims/qa/assets/87318828/96e4958b-2152-49ab-8d07-bf1fdeccdc6f">

**Comment by KatieWoe** [comment]
QA is done

**Comment by Nancy-Salpepi** [comment]
Jaron Droder should be added to QA credits.

**Comment by pixelzoom** [comment]
Thanks QA.   Credits have been updated, and all sim-specific issues (all 1 of them :) have been addressed. 

We'll be ready to create the 1.3 release branch and start RC testing as soon as these common PhET-iO issues are addressed:
* https://github.com/phetsims/phet-io-wrappers/issues/521
* https://github.com/phetsims/studio/issues/305

Closing.

**Comment by pixelzoom** [comment]
Reopening.

I see that the "Issues to Verify" section has not been completed above.  There is only 1 issue, https://github.com/phetsims/molecule-polarity/issues/141 (migration rules).  It is not checked off, and it is still open.  @KatieWoe what is the status? Were migration rules tested?

**Comment by pixelzoom** [comment]
I'm guessing that migration rules https://github.com/phetsims/molecule-polarity/issues/141 was indeed tested, one issue was found https://github.com/phetsims/molecule-polarity/issues/156, and no other problems were found.  @KatieWoe is that correct?

**Comment by KatieWoe** [comment]
Migration was tested and I believe that was the only issue found. We forgot to check off https://github.com/phetsims/molecule-polarity/issues/141 since it was more open ended rather than "confirm this one problem is fixed." Sorry about that.

**Comment by pixelzoom** [comment]
Thanks for clarifying @KatieWoe.  Closing.
