### ISSUE TITLE
Dev Lite Test: PhET Desktop App 2023-06-14

### ISSUE THREAD

**Issue by jbphet** [phetsims/qa#955]
@kathy-phet, @oliver-phet, and @KatieWoe:  There is a new update of the PhET Desktop App for Windows and MacOS available at https://phet-dev.colorado.edu/weddell/dist/2023-06-14/.  This was built based on a request from @RVieyra, and the primary motivation for updating is to pick up the most recent sims and a bunch of translations that have been submitted since the last build, which was from May of 2022.  There was a failed run at this, see https://github.com/phetsims/qa/issues/954, this is the 2nd attempt.

QA, please:

- [x] Verify that Greenhouse Effect, Calculus Grapher, Geometric Optics, and any other sims that you're aware of that have been published for the first time after May of 2022 are present in the sim.
- [x] Verify that some sims are present for the `tw`, `sw`, and `az` locales and that they run correctly.  You don't need to test _all_ sims for these locales, just a handful.  These are locales for which there have been a lot of translations submitted over the last year, so the objective here is to make sure that the desktop app has picked up the recent translations.

Testing:
- [x] Tester = KW, Platform = Win 11, Time = 3
- [x] Tester = NS , Platform = macOS 13.4, Time = 2.5

**Comment by KatieWoe** [comment]
Greehouse Effect is listed as an available sim in Java despite now being in HTML (that version is also available) and the image for the java version is missing. Since I don't have Java on this device I'm not sure if the java version works.
![greenhousegone](https://github.com/phetsims/qa/assets/41024075/7baf3bd8-d507-4f09-bb9e-9cfc6979ebf5)

**Comment by jbphet** [comment]
Thanks QA team - I'll follow up on the specific issues.  Closing this one.
