### ISSUE TITLE
Regression test: Alt Input

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/qa#957]
https://github.com/phetsims/scenery/issues/1550 introduced changes that are potentially disruptive. The way scenery tracks the focused element changed quite a lot. While unit and other automated tests look OK, it would be great to catch any breaks not found by existing tests before we make our next RC/dev test.

QA team, if you have any extra time in the backlog, can you please exercise alt input for a few sims on several platforms? I am most nervous about focus management like 
- opening dialogs
- using combo boxes
- Taking things out of toolboxes

Here are recent sims that were published and have those things
- geometric-optics
- quadrilateral
- my-solar-system
- ratio-and-proportion

If you have any questions, please let me know. If you find any problems please note them in this issue.

**Comment by KatieWoe** [comment]
Geometric Optics looks ok on Win 11 Chrome after a quick check.

**Comment by Nancy-Salpepi** [comment]
@jessegreenberg the above sims looked OK to me with mac + safari/chrome and win10 + FF/chrome. 
Back to you!
