### ISSUE TITLE
Maintenance release testing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/qa#969]
For https://github.com/phetsims/special-ops/issues/244

We'll want to test the sim links, and:

1. Briefly make sure the sim doesn't seem broken (10-15 seconds?)
2. Add the stringTest query parameter present in https://github.com/phetsims/special-ops/issues/244#issue-1822496329, and see if it behaves as described in the issue (feel free to ask any questions in that issue).

beers-law-lab 1.7 (https://github.com/phetsims/special-ops/issues/244)

- [x] [beers-law-lab 1.7.5-rc.1](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.5-rc.1/phet/beers-law-lab_en_phet.html)
- [x] [beers-law-lab 1.7.5-rc.1 phet-io](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.5-rc.1/phet-io/beers-law-lab_all_phet-io.html?phetioStandalone)
- [ ] [beers-law-lab 1.7.5-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/beers-law-lab/1.7.5-rc.1/phet-io/wrappers/studio)

build-a-nucleus 1.0 (https://github.com/phetsims/special-ops/issues/244)

- [x] [build-a-nucleus 1.0.14-rc.3](https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.14-rc.3/phet/build-a-nucleus_en_phet.html)

calculus-grapher 1.0 (https://github.com/phetsims/special-ops/issues/244)

- [x] [calculus-grapher 1.0.3-rc.1](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.3-rc.1/phet/calculus-grapher_en_phet.html)
- [x] [calculus-grapher 1.0.3-rc.1 phet-io](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.3-rc.1/phet-io/calculus-grapher_all_phet-io.html?phetioStandalone)
- [ ] [calculus-grapher 1.0.3-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/calculus-grapher/1.0.3-rc.1/phet-io/wrappers/studio)

circuit-construction-kit-dc 1.3 (https://github.com/phetsims/special-ops/issues/244)

- [x] [circuit-construction-kit-dc 1.3.6-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.6-rc.1/phet/circuit-construction-kit-dc_en_phet.html)
- [x] [circuit-construction-kit-dc 1.3.6-rc.1 phet-io](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.6-rc.1/phet-io/circuit-construction-kit-dc_all_phet-io.html?phetioStandalone)
- [ ] [circuit-construction-kit-dc 1.3.6-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc/1.3.6-rc.1/phet-io/wrappers/studio)

circuit-construction-kit-dc-virtual-lab 1.3 (https://github.com/phetsims/special-ops/issues/244)

- [x] [circuit-construction-kit-dc-virtual-lab 1.3.4-rc.1](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.4-rc.1/phet/circuit-construction-kit-dc-virtual-lab_en_phet.html)
- [x] [circuit-construction-kit-dc-virtual-lab 1.3.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.4-rc.1/phet-io/circuit-construction-kit-dc-virtual-lab_all_phet-io.html?phetioStandalone)
- [ ] [circuit-construction-kit-dc-virtual-lab 1.3.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/circuit-construction-kit-dc-virtual-lab/1.3.4-rc.1/phet-io/wrappers/studio)

concentration 1.7 (https://github.com/phetsims/special-ops/issues/244)

- [x] [concentration 1.7.5-rc.1](https://phet-dev.colorado.edu/html/concentration/1.7.5-rc.1/phet/concentration_en_phet.html)
- [x] [concentration 1.7.5-rc.1 phet-io](https://phet-dev.colorado.edu/html/concentration/1.7.5-rc.1/phet-io/concentration_all_phet-io.html?phetioStandalone)
- [ ] [concentration 1.7.5-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/concentration/1.7.5-rc.1/phet-io/wrappers/studio)

density 1.1 (https://github.com/phetsims/special-ops/issues/244)

- [x] [density 1.1.1-rc.1](https://phet-dev.colorado.edu/html/density/1.1.1-rc.1/phet/density_en_phet.html)
- [x] [density 1.1.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/density/1.1.1-rc.1/phet-io/density_all_phet-io.html?phetioStandalone)
- [ ] [density 1.1.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/density/1.1.1-rc.1/phet-io/wrappers/studio)

energy-skate-park 1.2 (https://github.com/phetsims/special-ops/issues/244)

- [x] [energy-skate-park 1.2.5-rc.1](https://phet-dev.colorado.edu/html/energy-skate-park/1.2.5-rc.1/phet/energy-skate-park_en_phet.html)

friction 1.6 (https://github.com/phetsims/special-ops/issues/244)

- [x] [friction 1.6.6-rc.1](https://phet-dev.colorado.edu/html/friction/1.6.6-rc.1/phet/friction_en_phet.html)
- [x] [friction 1.6.6-rc.1 phet-io](https://phet-dev.colorado.edu/html/friction/1.6.6-rc.1/phet-io/friction_all_phet-io.html?phetioStandalone)
- [ ] [friction 1.6.6-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/friction/1.6.6-rc.1/phet-io/wrappers/studio)

geometric-optics 1.3 (https://github.com/phetsims/special-ops/issues/244)

- [x] [geometric-optics 1.3.1-rc.1](https://phet-dev.colorado.edu/html/geometric-optics/1.3.1-rc.1/phet/geometric-optics_en_phet.html)
- [x] [geometric-optics 1.3.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/geometric-optics/1.3.1-rc.1/phet-io/geometric-optics_all_phet-io.html?phetioStandalone)
- [ ] [geometric-optics 1.3.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/geometric-optics/1.3.1-rc.1/phet-io/wrappers/studio)

geometric-optics-basics 1.3 (https://github.com/phetsims/special-ops/issues/244)

- [x] [geometric-optics-basics 1.3.1-rc.1](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.1-rc.1/phet/geometric-optics-basics_en_phet.html)
- [x] [geometric-optics-basics 1.3.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.1-rc.1/phet-io/geometric-optics-basics_all_phet-io.html?phetioStandalone)
- [ ] [geometric-optics-basics 1.3.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/geometric-optics-basics/1.3.1-rc.1/phet-io/wrappers/studio)

graphing-quadratics 1.3 (https://github.com/phetsims/special-ops/issues/244)

- [x] [graphing-quadratics 1.3.1-rc.1](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.1-rc.1/phet/graphing-quadratics_en_phet.html)
- [x] [graphing-quadratics 1.3.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.1-rc.1/phet-io/graphing-quadratics_all_phet-io.html?phetioStandalone)
- [ ] [graphing-quadratics 1.3.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/graphing-quadratics/1.3.1-rc.1/phet-io/wrappers/studio)

gravity-and-orbits 1.6 (https://github.com/phetsims/special-ops/issues/244)

- [x] [gravity-and-orbits 1.6.13-rc.1](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.13-rc.1/phet/gravity-and-orbits_en_phet.html)
- [x] [gravity-and-orbits 1.6.13-rc.1 phet-io](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.13-rc.1/phet-io/gravity-and-orbits_all_phet-io.html?phetioStandalone)
- [ ] [gravity-and-orbits 1.6.13-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/gravity-and-orbits/1.6.13-rc.1/phet-io/wrappers/studio)

greenhouse-effect 1.1 (https://github.com/phetsims/special-ops/issues/244)

- [x] [greenhouse-effect 1.1.6-rc.1](https://phet-dev.colorado.edu/html/greenhouse-effect/1.1.6-rc.1/phet/greenhouse-effect_en_phet.html)

mean-share-and-balance 1.0 (https://github.com/phetsims/special-ops/issues/244)

- [x] [mean-share-and-balance 1.0.10-rc.1](https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.10-rc.1/phet/mean-share-and-balance_en_phet.html)

molecule-polarity 1.3 (https://github.com/phetsims/special-ops/issues/244)

- [x] [molecule-polarity 1.3.1-rc.1](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.1-rc.1/phet/molecule-polarity_en_phet.html)
- [x] [molecule-polarity 1.3.1-rc.1 phet-io](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.1-rc.1/phet-io/molecule-polarity_all_phet-io.html?phetioStandalone)
- [ ] [molecule-polarity 1.3.1-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-polarity/1.3.1-rc.1/phet-io/wrappers/studio)

molecule-shapes 1.6 (https://github.com/phetsims/special-ops/issues/244)

- [x] [molecule-shapes 1.6.4-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.4-rc.1/phet/molecule-shapes_en_phet.html)
- [x] [molecule-shapes 1.6.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.4-rc.1/phet-io/molecule-shapes_all_phet-io.html?phetioStandalone)
- [ ] [molecule-shapes 1.6.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-shapes/1.6.4-rc.1/phet-io/wrappers/studio)

molecule-shapes-basics 1.6 (https://github.com/phetsims/special-ops/issues/244)

- [x] [molecule-shapes-basics 1.6.4-rc.1](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.4-rc.1/phet/molecule-shapes-basics_en_phet.html)
- [x] [molecule-shapes-basics 1.6.4-rc.1 phet-io](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.4-rc.1/phet-io/molecule-shapes-basics_all_phet-io.html?phetioStandalone)
- [ ] [molecule-shapes-basics 1.6.4-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.6.4-rc.1/phet-io/wrappers/studio)

my-solar-system 1.2 (https://github.com/phetsims/special-ops/issues/244)

- [x] [my-solar-system 1.2.2-rc.1](https://phet-dev.colorado.edu/html/my-solar-system/1.2.2-rc.1/phet/my-solar-system_en_phet.html)

number-compare 1.0 (https://github.com/phetsims/special-ops/issues/244)

- [x] [number-compare 1.0.2-rc.1](https://phet-dev.colorado.edu/html/number-compare/1.0.2-rc.1/phet/number-compare_en_phet.html)

number-play 1.1 (https://github.com/phetsims/special-ops/issues/244)

- [x] [number-play 1.1.2-rc.1](https://phet-dev.colorado.edu/html/number-play/1.1.2-rc.1/phet/number-play_en_phet.html)

ph-scale 1.6 (https://github.com/phetsims/special-ops/issues/244)

- [x] [ph-scale 1.6.7-rc.1](https://phet-dev.colorado.edu/html/ph-scale/1.6.7-rc.1/phet/ph-scale_en_phet.html)
- [x] [ph-scale 1.6.7-rc.1 phet-io](https://phet-dev.colorado.edu/html/ph-scale/1.6.7-rc.1/phet-io/ph-scale_all_phet-io.html?phetioStandalone)
- [ ] [ph-scale 1.6.7-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/ph-scale/1.6.7-rc.1/phet-io/wrappers/studio)

ph-scale-basics 1.6 (https://github.com/phetsims/special-ops/issues/244)

- [x] [ph-scale-basics 1.6.6-rc.1](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.6-rc.1/phet/ph-scale-basics_en_phet.html)
- [x] [ph-scale-basics 1.6.6-rc.1 phet-io](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.6-rc.1/phet-io/ph-scale-basics_all_phet-io.html?phetioStandalone)
- [ ] [ph-scale-basics 1.6.6-rc.1 phet-io Studio](https://phet-dev.colorado.edu/html/ph-scale-basics/1.6.6-rc.1/phet-io/wrappers/studio)

quadrilateral 1.1 (https://github.com/phetsims/special-ops/issues/244)

- [x] [quadrilateral 1.1.1-rc.1](https://phet-dev.colorado.edu/html/quadrilateral/1.1.1-rc.1/phet/quadrilateral_en_phet.html)

ratio-and-proportion 1.2 (https://github.com/phetsims/special-ops/issues/244)

- [x] [ratio-and-proportion 1.2.7-rc.1](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.7-rc.1/phet/ratio-and-proportion_en_phet.html)

**Comment by KatieWoe** [comment]
A popup occurs with studio sims. If you launch the sim then the resulting sim has the popup.

**Comment by KatieWoe** [comment]
Tests aside from studio have been completed.

**Comment by kathy-phet** [comment]
> A popup occurs with studio sims. If you launch the sim then the resulting sim has the popup.

@KatieWoe - Can you expand on this and show a movie or screenshot? I don't know what you mean.

**Comment by KatieWoe** [comment]
I discussed with @jonathanolson, but basically:
1. Put the needed parameter at the end of a studio link.
2. In studio, launch the sim (press the test button)
3. The sim that is launched will have the pop-up (undesired behavior).

**Comment by KatieWoe** [comment]
Example:
The sim in studio:
![instudio](https://github.com/phetsims/qa/assets/41024075/d6ab969b-1570-4c6f-b699-b1f213260109)
The sim after you press the test button:
![pressedlaunch](https://github.com/phetsims/qa/assets/41024075/20b671b7-c824-46fa-8980-fa9ddd625a1a)

**Comment by KatieWoe** [comment]
I checked a published sim and https://github.com/phetsims/qa/issues/969#issuecomment-1669950201 happens there too.

**Comment by KatieWoe** [comment]
The fix is in https://github.com/phetsims/qa/issues/970, but it contains the studio error described in above comments. Though the pop-up is different in the dev test.
![newcode](https://github.com/phetsims/qa/assets/41024075/10bf8a45-a287-4823-9b7b-b7d7ec0349a8)

**Comment by jonathanolson** [comment]
Published the existing changes/fixes. I'll open another QA issue once I have the studio issue resolved.
