### ISSUE TITLE
Dev Test: keplers-laws 1.1.0-dev.5

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/qa#979]
<h1>Dev Test</h1>

**Mentions**: @kathy-phet @KatieWoe 

<h3>Simulation links</h3>

- [github repository for issues](https://github.com/phetsims/keplers-laws/issues)
- [phet top-level directory](https://phet-dev.colorado.edu/html/keplers-laws/1.1.0-dev.5)
- [sim: all_phet.html](https://phet-dev.colorado.edu/html/keplers-laws/1.1.0-dev.5/phet/keplers-laws_all_phet.html)

<h3>Test Matrix</h3>

Please include all (non-screen reader) feature testing in these records if applicable.

- [x] Latest macOS, Safari (Time = 2hrs)
- [x] Windows 10, Chrome (Time = 2hrs)
- [x] Windows 10/11, Firefox (Time =2hrs )
- [x] Latest iOS, Safari (Time = .75)
- [x] Windows 11, Chrome (Time = 3.5)

Light testing, or optionally skip if time crunch:

- [ ] Latest macOS, Chrome (Time = )
- [ ] Latest Chrome OS, Chrome (Time = )

<h3>Features included</h3>

- [x] Alternative Input
- [x] UI Sound
- [x] Sonification
- <s> [ ] Description </s>

<h3>Focus and Special Instructions</h3>

<h3>Issues to Verify</h3>

These issues should have the "status:ready-for-review" label. Unless an issue says to close after verifying, assign the
issue back to the developer.

- N/A

---
<h2>For QA...</h2>

<details>
<summary><b>General features</b></summary>

<h3>What to Test</h3>

- Click every single button.
- If there is sound, make sure it works.
- Make sure you can't lose anything.
- Play with the sim normally.
- Try to break the sim.
- Try to include browser version numbers
- If there is a console available, check for errors and include them in the Problem Description.
- Run through the string tests on at least one platform, especially if it is about to go to rc.
- Check the Game Up harness on one platform.

<hr>

</details>

<details>
<summary><b>Accessibility features</b></summary>

<h3>What to Test</h3>

- Specific instructions can be found above.
- Make sure the accessibility (a11y) feature that is being tested doesn't negatively affect the sim in any way. Here is
  a list of features that may be supported in this test:

  - Alternative Input
  - Sound and Sonification
  - Pan and Zoom
- Test all possible forms of input.
  - Test all mouse/trackpad inputs.
  - Test all touchscreen inputs.
  - Test all keyboard navigation inputs (if applicable).

<h3>Screen Readers</h3>

This sim may support screen readers. If you are unfamiliar with screen readers, please ask Katie to introduce you to
screen readers. If you simply need a refresher on screen readers, please consult the
[QA Book](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md), which should have all of the information
you need as well as a link to a screen reader tutorial made by Jesse. Otherwise, look over the a11y view before opening
the simulation. Once you've done that, open the simulation and make sure alerts and descriptions work as intended.

<h3>Keyboard Navigation</h3>

This sim supports keyboard navigation. Please make sure it works as intended on all platforms by itself and with a
screen reader.

<h3>Magnification</h3>

This sim supports magnification with pinch and drag gestures on touch screens, keyboard shortcuts, and mouse/wheel
controls. Please test magnfication and make sure
it is working as intended and well with the use cases of the simulation. Due to the way screen readers handle user
input, magnification is NOT expected to
work while using a screen reader so there is no need to test this case.

<hr>

</details>

<details>
<summary><b>FAQs for QA Members</b></summary>

<br>

  

  <details>
  <summary><i>There are multiple tests in this issue... Which test should I do first?</i></summary> 

Test in order! Test the first thing first, the second thing second, and so on.

  </details>

  <br>

  

  <details>
  <summary><i>How should I format my issue?</i></summary>

Here's a template for making issues:

      <b>Test Device</b>

      blah

      <b>Operating System</b>

      blah

      <b>Browser</b>

      blah

      <b>Problem Description</b>

      blah

      <b>Steps to Reproduce</b>

      blah

      <b>Visuals</b>

      blah

      <details>
      <summary><b>Troubleshooting Information</b></summary>

      blah

      </details>

  </details>

  <br>

  

  <details>
  <summary><i>Who should I assign?</i></summary>

We typically assign the developer who opened the issue in the QA repository.

  </details>

  <br>

  

  <details>
  <summary><i>My question isn't in here... What should I do?</i></summary>

You should:

1. Consult the [QA Book](https://github.com/phetsims/QA/blob/main/documentation/qa-book.md).
2. Google it.
3. Ask Katie.
4. Ask a developer.
5. Google it again.
6. Cry.

  </details>

<br>

<hr>

</details>

**Comment by KatieWoe** [comment]
Memory Test Results:
The memory footprint is a bit large, but does not grow too much.
![memtest](https://github.com/phetsims/qa/assets/41024075/942a00a1-91bb-4d24-9652-ed7f6f13f6ee)

**Comment by KatieWoe** [comment]
Calling QA here

**Comment by AgustinVallejo** [comment]
Thanks team! Closing this one as all issues have been adressed and there's the RC Test in https://github.com/phetsims/qa/issues/984
