### ISSUE TITLE
Strategy for handling QA issue reporting for sim "suites"

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/QA#98]
One issue that was raised in the CCK postmortem was we don't have a clear strategy for dealing with how to report issues for sims that have multiple flavors/repos. For instance, a sim suite like Area Model will have multiple flavors and a common repo. What should be the guidelines for what should be reported where? Examples of current "suites":

- Area Model sims
- Inverse Square law sims
- CCK variants
- likely Energy Skate Park variants

The current strategy has been for @phet-steele to ask the developer if a certain bug/issue should be in the common repo or in a specific repo. This seems inefficient (though perhaps necessary at times).

Let's discuss some guidelines/strategies for handling this question going forward.

Some initial thoughts:
- Probably bugs that are "obviously" related to a common model should be in the common repo
- Issues specific to only one flavor should be reported in the specific repo

**Comment by samreid** [comment]
Ideally, the issue will be created in the repo where a commit will solve the problem.  There problems with this are (a) we don't always know which repo will need the commit until doing a lot of research/experimentation and (b) sometimes there will be commits in several repos that are necessary to address the problem.

My recommendation is for people creating issues to be at least operationally familiar with how the code is divided into different repos, and take their best guess as to the best repo for the issue.  For example, if the problem appears in area-model-sim-1 and area-model-sim-2 and area-model-sim-3, then the issue should be created in area-model-common.  If the issue appears in area-model-sim-2 but not the other sims, then the issue would be created in area-model-sim-2.  If it is still unclear, it's fine to ask the responsible-developer which repo to use.

It's easy to move issue that have only 1-2 comments, much harder to move issues that have 10+ comments.

**Comment by jonathanolson** [comment]
For area-model, I've been handling almost all issues in area-model-common, as this is where at least               95%+ of the code exists (almost all fixes/changes will be changes to area-model-common).

For sim-specific bugs, I don't mind issues in the sim-specific repos at all.

**Comment by pixelzoom** [comment]
My recommendation is to make the QA issue in the repo for the sim that is being QA tested.  If it's appropriate to move it to another repository (common code or "sim family"), then the developer can move it.

**Comment by samreid** [comment]
*Consensus* create the issue in the repo where the problem was observed, unless you know a more specific repo (then create it there).
